Convert DomainCreateFlow to use generic tm() methods
google/nomulus pull request #1026
Opened 2021-03-19 20:08 UTC by gbrodman

Various necessary changes included as part of this:

- Make ForeignKeyIndex completely generic. Previously, only the load()
method that took a DateTime as input could use SQL, and the cached flow
was particular to Objectify Keys. Now, the cached flow and the
non-cached flow can use the same (ish) piece of code to load / create
the relevant index objects before filtering or modifying them as
necessary.
- EntityChanges should use VKeys
- FlowUtils should persist entity changes using tm(), however not all
object types are storable in SQL.
- Filling out PollMessage fields with the proper object type when
loading from SQL
- Changing a few tm() calls to ofyTm() calls when using objectify. This
is because creating a read-only transaction in SQL is quite a footgun at
the moment, because it makes the entire transaction you're in (if you
were already in one) a read-only transaction.

2021-03-24 15:23 UTC, CydeWeys requested changes
It sounds like we need to solve the footgun.  The main reason we're doing separate read-only transactions in Datastore is for performance/Datastore limitation reasons (IIRC; it should avoid enlisting a given entity group inside the main mutating transaction), whereas I don't think it makes any difference in Cloud SQL land.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1026#-:-MWZo_G36aOCp1l7T3qI:b6084ao)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/flows/FlowUtils.java, line 65 at r1](https://reviewable.io/reviews/google/nomulus/1026#-MWZoynS5WUGxNhj_hq_:-MWZoynTAMHWQScolCD0:b-kj5lq6) ([raw file](https://github.com/google/nomulus/blob/ce5735013e8c5e6a3e93a1b5c5a169449562d2db/core/src/main/java/google/registry/flows/FlowUtils.java#L65)):*
> ```Java
>                   .filter(
>                       obj ->
>                           obj.getClass().isAnnotationPresent(Entity.class)
> ```

This is a hacky way of solving this at this one particular callsite.  We need a much better, more robust, centralized way for not writing entities that don't exist in SQL to SQL.


<!-- Sent from Reviewable.io -->

2021-03-24 18:14 UTC, gbrodman reviewed
yeah, we may need to implement some sort of `transactNew` functionality for SQL then in order to have the read-only transactions :/ 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1026#-:-MW_RMIPCLCFuktYEgr8:b-rodfd5)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/flows/FlowUtils.java, line 65 at r1](https://reviewable.io/reviews/google/nomulus/1026#-MWZoynS5WUGxNhj_hq_:-MW_L5lv94gggc35oJnv:b-ll3pct) ([raw file](https://github.com/google/nomulus/blob/ce5735013e8c5e6a3e93a1b5c5a169449562d2db/core/src/main/java/google/registry/flows/FlowUtils.java#L65)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is a hacky way of solving this at this one particular callsite.  We need a much better, more robust, centralized way for not writing entities that don't exist in SQL to SQL.
</blockquote></details>

hm, yeah it seems like there already is a mechanism for that so this isn't necessary. Wonder why I was hitting issues with this before then, but we should be all good here. 


<!-- Sent from Reviewable.io -->

2021-03-24 23:36 UTC, gbrodman reviewed
Added a comment and removed the footgun -- we just will have `transactNew` and `transactNewReadOnly` use standard transactions, as they basically were before. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1026#-:-MWa_yZMAz9kDmdp5TLq:b-jxanov)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-03-29 15:42 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1026)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 198 at r2](https://reviewable.io/reviews/google/nomulus/1026#-MWydXWD-VMBeZQdn4Dz:-MWydXWD-VMBeZQdn4E-:b98erl8) ([raw file](https://github.com/google/nomulus/blob/8b782f300d7feac565d9a79afbcf35194d155678/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L198)):*
> ```Java
>     return loadIndexesFromStore(clazz, foreignKeys).entrySet().stream()
>         .filter(e -> now.isBefore(e.getValue().getDeletionTime()))
>         .collect(toImmutableMap(Map.Entry::getKey, Map.Entry::getValue));
> ```

Use `entriesToImmutableMap()` (statically imported from `CollectionUtils`)
___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 239 at r2](https://reviewable.io/reviews/google/nomulus/1026#-MWydBh_AE3pZp3R0-y8:-MWydBh_AE3pZp3R0-y9:b98erl8) ([raw file](https://github.com/google/nomulus/blob/8b782f300d7feac565d9a79afbcf35194d155678/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L239)):*
> ```Java
>                           .max(Comparator.comparing(ForeignKeyIndex::getDeletionTime))
>                           .get()))
>           .collect(toImmutableMap(Map.Entry::getKey, Map.Entry::getValue));
> ```

Use `entriesToImmutableMap()` (statically imported from `CollectionUtils`)


<!-- Sent from Reviewable.io -->

2021-03-29 15:42 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1026#-:-MWyddld4efIoBbtFOnb:bnfp4nl)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-03-29 15:45 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1026)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 198 at r2](https://reviewable.io/reviews/google/nomulus/1026#-MWydXWD-VMBeZQdn4Dz:-MWyeFRX16hvX556tUOb:be9f77) ([raw file](https://github.com/google/nomulus/blob/8b782f300d7feac565d9a79afbcf35194d155678/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L198)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use `entriesToImmutableMap()` (statically imported from `CollectionUtils`)
</blockquote></details>

oh nice, didn't know that that existed (it wasn't here before) 
___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 239 at r2](https://reviewable.io/reviews/google/nomulus/1026#-MWydBh_AE3pZp3R0-y8:-MWyeHiQ-Xm1vuudNRV9:be9f77) ([raw file](https://github.com/google/nomulus/blob/8b782f300d7feac565d9a79afbcf35194d155678/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L239)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use `entriesToImmutableMap()` (statically imported from `CollectionUtils`)
</blockquote></details>

oh nice, didn't know that that existed (it wasn't here before) 


<!-- Sent from Reviewable.io -->

2021-03-29 19:39 UTC, merged

2021-04-13 16:22 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1026)* status: 0 of 10 files reviewed, 3 unresolved discussions

___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 213 at r3](https://reviewable.io/reviews/google/nomulus/1026#-MYB1DS_8kB7IUM1c_VX:-MYB1DSa3J5RAoq_q31r:bqc7bi1) ([raw file](https://github.com/google/nomulus/blob/132ed555e27e2ac5f834494079adeb91ed67bd57/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L213)):*
> ```Java
>     if (tm().isOfy()) {
>       return ImmutableMap.copyOf(
>           tm().doTransactionless(() -> ofy().load().type(mapToFkiClass(clazz)).ids(foreignKeys)));
> ```

In hindsight, this should not have been transaction-less.  This was a bad bug.  What it's replacing is necessarily transactional, otherwise you get the potential to allow EPP resources with duplicate unique IDs (contacts with the same contact ID, domains and hosts with the same name!!).


<!-- Sent from Reviewable.io -->