Convert poll-message-related classes to use SQL as well
google/nomulus pull request #1050
Opened 2021-04-01 18:06 UTC by gbrodman

Two relatively complex parts. The first is that we needed a small
refactor on the AckPollMessagesCommand because we could theoretically be
acking more poll messages than the Datastore transaction size boundary.
This means that the normal flow of "gather the poll messages from the DB
into one collection, then act on it" needs to be changed to a more
functional flow.

The second is that acking the poll message (deleting it in most cases)
reduces the number of remaining poll messages in SQL but not in
Datastore, since in Datastore the deletion does not take effect until
after the transaction is over.

2021-04-02 17:52 UTC, mindhog requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1050)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java, line 171 at r1](https://reviewable.io/reviews/google/nomulus/1050#-MXIgM-v6oTveU1w960p:-MXIgM-w68UIui_mVMuy:b-qgk13i) ([raw file](https://github.com/google/nomulus/blob/6a351624dd15df19248229fb6de51fecb92e1fb8/core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java#L171)):*
> ```Java
>         .isTrue();
>     assertThat(one.getSqlKey()).isEqualTo(two.getSqlKey());
>     assertThat(one.getOfyKey()).isEqualTo(two.getOfyKey());
> ```

Does .equals() not work here?  In general it should, as VKey derives from ImmutableObject


<!-- Sent from Reviewable.io -->

2021-04-02 18:10 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1050)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java, line 171 at r1](https://reviewable.io/reviews/google/nomulus/1050#-MXIgM-v6oTveU1w960p:-MXIlacwCThQkL56UMRs:bo8sojx) ([raw file](https://github.com/google/nomulus/blob/6a351624dd15df19248229fb6de51fecb92e1fb8/core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java#L171)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Does .equals() not work here?  In general it should, as VKey derives from ImmutableObject
</blockquote></details>

I added a comment explaining this -- the kind / class of the VKey may not be precisely the same, since when reconstituting the key from the poll message string we only know that it is the generic PollMessage superclass, which is not technically (as far as Java knows) equal to the PollMessage.OneTime (or recurring, whatever) class. 

The DB treats them as the same though so it's fine. 


<!-- Sent from Reviewable.io -->

2021-04-02 18:38 UTC, mindhog approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1050)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java, line 171 at r1](https://reviewable.io/reviews/google/nomulus/1050#-MXIgM-v6oTveU1w960p:-MXIr3gc4Z5ih3EO6dIc:b-7axlqk) ([raw file](https://github.com/google/nomulus/blob/6a351624dd15df19248229fb6de51fecb92e1fb8/core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java#L171)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I added a comment explaining this -- the kind / class of the VKey may not be precisely the same, since when reconstituting the key from the poll message string we only know that it is the generic PollMessage superclass, which is not technically (as far as Java knows) equal to the PollMessage.OneTime (or recurring, whatever) class. 

The DB treats them as the same though so it's fine. 
</blockquote></details>

That's actually a problem, as in general we rely on the ability to compare VKeys.  Also, I thought we'd fixed that for PollMessage.

We can go with this for now, I'll make a note to investigate.  


<!-- Sent from Reviewable.io -->

2021-04-02 18:51 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1050)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java, line 171 at r1](https://reviewable.io/reviews/google/nomulus/1050#-MXIgM-v6oTveU1w960p:-MXIv7Av2aqJWVqNl9pM:bt1spf7) ([raw file](https://github.com/google/nomulus/blob/6a351624dd15df19248229fb6de51fecb92e1fb8/core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java#L171)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

That's actually a problem, as in general we rely on the ability to compare VKeys.  Also, I thought we'd fixed that for PollMessage.

We can go with this for now, I'll make a note to investigate.  
</blockquote></details>

More generally, we can for-sure count VKey kinds as equal if one is a subclass of another and if the superclass has the annotation `@Inheritance(strategy = InheritanceType.SINGLE_TABLE)` on it. 

I'm not sure about other situations, e.g. DomainHistory VKey vs HistoryEntry VKey. 


<!-- Sent from Reviewable.io -->

2021-04-02 18:55 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1050)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/tools/AckPollMessagesCommand.java, line 129 at r2](https://reviewable.io/reviews/google/nomulus/1050#-MXIw7ttE97GlQ1qZH2j:-MXIw7ttE97GlQ1qZH2k:b-8ka3k6) ([raw file](https://github.com/google/nomulus/blob/ec0220f33c9889d3e989dbe9e8dcb74f1709b00e/core/src/main/java/google/registry/tools/AckPollMessagesCommand.java#L129)):*
> ```Java
>                     jpaTm()
>                         .query(SQL_POLL_MESSAGE_QUERY_BY_MESSAGE, PollMessage.class)
>                         .setParameter("msg", String.format("%%%s%%", message));
> ```

`"%" + message + "%"` is honestly less confusing than this.


<!-- Sent from Reviewable.io -->

2021-04-02 18:57 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1050#-:-MXIwhDoBH2qeGkSMdCy:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)



<!-- Sent from Reviewable.io -->

2021-04-02 19:36 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1050)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/tools/AckPollMessagesCommand.java, line 129 at r2](https://reviewable.io/reviews/google/nomulus/1050#-MXIw7ttE97GlQ1qZH2j:-MXJ4Ht0435-stR7jW_k:b9pql5t) ([raw file](https://github.com/google/nomulus/blob/ec0220f33c9889d3e989dbe9e8dcb74f1709b00e/core/src/main/java/google/registry/tools/AckPollMessagesCommand.java#L129)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`"%" + message + "%"` is honestly less confusing than this.
</blockquote></details>

Fair point, done. 


<!-- Sent from Reviewable.io -->

2021-04-02 23:57 UTC, merged

2021-04-04 07:10 UTC, decodedfile reviewed
Duplicate of #

2021-04-04 07:14 UTC, decodedfile reviewed
Duplicate of #