Convert RefreshDnsOnHostRenameAction to tm
google/nomulus pull request #1053
Opened 2021-04-02 20:41 UTC by mindhog

This is not quite complete because it also requires the conversion of a
map-reduce which is in scope for an entirely different work.  Tests of the
map-reduce functionality are excluded from the SQL run.

This also requires the following additional fixes:

-  Convert Lock to tm, as doing so was necessary to get this action to work.
   As Lock is being targeted as DatastoreOnly, we convert all calls in it to
   use ofyTm()
-  Fix a bug in DualDatabaseTest (the check for an AppEngineExtension field is
   wrong, and captures fields of type Object as AppEngineExtension's)
-  Introduce another VKey.from() method that creates a VKey from a stringified
   Ofy Key.

2021-04-02 23:44 UTC, gbrodman requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1053)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java, line 322 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJyCU51hSCENGgbGsZ:-MXJyCU6-vy7w4bRqQKY:bvrx38) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java#L322)):*
> ```Java
>       HostResource host =
>           tm().transact(() -> tm().loadByKeyIfPresent(hostKey))
>               .orElseThrow(() -> new NullPointerException("Host to refresh doesn't exist"));
> ```

might an IllegalArgumentException or NoSuchElementException be better? Not sure what the logic is for having an NPE here 
___
*[core/src/main/java/google/registry/model/server/Lock.java, line 193 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJwimaDZr-tVeILmSB:-MXJwimaDZr-tVeILmSC:blzvwt6) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/model/server/Lock.java#L193)):*
> ```Java
>     // access to resources like GCS that can't be transactionally rolled back. Therefore, the lock
>     // must be definitively acquired before it is used, even when called inside another transaction.
>     AcquireResult acquireResult =
> ```

I think we may want to rethink how we deal with locks. Is there any reason for keeping the SQL locks and Datastore locks as separate Java objects? We may have done that at the start when we didn't really know as much about what we were doing, but like with Cursors it may make sense to combine them into one object if we don't have a seamless LockDualDatabaseDao (which we don't). 

If we have them in the same class, then we can just use tm() methods to acquire them (like what we did with the Cursor refactor in https://github.com/google/nomulus/pull/988
___
*[core/src/main/java/google/registry/persistence/VKey.java, line 233 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJxmHxEgkSfPwYa0r2:-MXJxmHxEgkSfPwYa0r3:b-pk0xj0) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/persistence/VKey.java#L233)):*
> ```Java
>    */
>   @Nullable
>   public static <T> VKey<T> from(String ofyKeyRepr) {
> ```

maybe rename to `fromWebsafeKey` like the `Key` method? this might be a little vague
___
*[core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java, line 126 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJwUEP3HcedVQMGW_8:-MXJwUEP3HcedVQMGW_9:b-dgh8nt) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java#L126)):*
> ```Java
>       fieldBuilder.addAll(
>           Stream.of(clazz.getDeclaredFields())
>               .filter(field -> AppEngineExtension.class.isAssignableFrom(field.getType()))
> ```

Wow, I'm surprised that this didn't fail much before


<!-- Sent from Reviewable.io -->

2021-04-05 11:32 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1053)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java, line 322 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJyCU51hSCENGgbGsZ:-MXWgMH67SaRmfXsQpVW:bm8yr59) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java#L322)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

might an IllegalArgumentException or NoSuchElementException be better? Not sure what the logic is for having an NPE here 
</blockquote></details>

The original call was checkNotNull(), which (somewhat suprisingly to me) throws a NullPointerException, so my intent was to preserve the original interface.
___
*[core/src/main/java/google/registry/model/server/Lock.java, line 193 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJwimaDZr-tVeILmSB:-MXWgkVG6TxiR9sB0niO:b-qumojj) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/model/server/Lock.java#L193)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we may want to rethink how we deal with locks. Is there any reason for keeping the SQL locks and Datastore locks as separate Java objects? We may have done that at the start when we didn't really know as much about what we were doing, but like with Cursors it may make sense to combine them into one object if we don't have a seamless LockDualDatabaseDao (which we don't). 

If we have them in the same class, then we can just use tm() methods to acquire them (like what we did with the Cursor refactor in https://github.com/google/nomulus/pull/988
</blockquote></details>

Yeah, I agree.   I didn't really want to get into that in the context of this PR, my intent here was to make the datastore locks (i.e. the ones that we're actually using) work correctly, since they were broken in SQL mode.

I've added this as a discussion topic for today.
___
*[core/src/main/java/google/registry/persistence/VKey.java, line 233 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJxmHxEgkSfPwYa0r2:-MXWkNLfBVNrneM6LQkX:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/persistence/VKey.java#L233)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

maybe rename to `fromWebsafeKey` like the `Key` method? this might be a little vague
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java, line 126 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJwUEP3HcedVQMGW_8:-MXWkecoC3DZOMRQ7WBt:b-krscs5) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java#L126)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Wow, I'm surprised that this didn't fail much before
</blockquote></details>

I guess there aren't many fields of type "Object" in our test classes.


<!-- Sent from Reviewable.io -->

2021-04-05 16:04 UTC, gbrodman requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1053)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java, line 322 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJyCU51hSCENGgbGsZ:-MXXlVHG3eV1TDN1qH1i:bqvy1vr) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java#L322)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

The original call was checkNotNull(), which (somewhat suprisingly to me) throws a NullPointerException, so my intent was to preserve the original interface.
</blockquote></details>

weird, can we change that while we're at it? 
___
*[core/src/main/java/google/registry/model/server/Lock.java, line 193 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJwimaDZr-tVeILmSB:-MXXlZ3PDYdxuGNEAsPn:b-xe86fw) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/model/server/Lock.java#L193)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Yeah, I agree.   I didn't really want to get into that in the context of this PR, my intent here was to make the datastore locks (i.e. the ones that we're actually using) work correctly, since they were broken in SQL mode.

I've added this as a discussion topic for today.
</blockquote></details>

Yeah the more I think about it the more i think we should just do what we did for Cursors.  We will discuss today. 


<!-- Sent from Reviewable.io -->

2021-04-05 17:23 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1053)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java, line 322 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJyCU51hSCENGgbGsZ:-MXY2wZOCtsqVXkROMAR:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java#L322)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

weird, can we change that while we're at it? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-06 14:56 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1053)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/model/server/Lock.java, line 193 at r1](https://reviewable.io/reviews/google/nomulus/1053#-MXJwimaDZr-tVeILmSB:-MXbfJpU-ZEJyFHd908w:b-gu0gkf) ([raw file](https://github.com/google/nomulus/blob/f161eff7a2b3a3fd582ec77d82e1574ecd1af170/core/src/main/java/google/registry/model/server/Lock.java#L193)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah the more I think about it the more i think we should just do what we did for Cursors.  We will discuss today. 
</blockquote></details>

As discussed yesterday: I'll remove the other lock class and make this code portable.  However, I'd like to do so in the next PR.


<!-- Sent from Reviewable.io -->

2021-04-06 15:32 UTC, gbrodman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1053#-:-MXbo7s51a4nWSfrnT9S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-04-06 18:28 UTC, merged