Add a CompareReservedListCommand
google/nomulus pull request #1054
Opened 2021-04-02 20:57 UTC by sarahcaseybot

This command loads the list of all ReservedLists in Datastore and Cloud SQL and returns the name of any list that is either missing from one of the DBs or that has differing content. The output of this command does not indicate what the actual diff between the lists are, so GetReservedListCommand should be used to actually view the contents of the offending lists. 

I already ran this comparison test on Sandbox and Production and fixed all the issues it found. (One list I missed in Sandbox when resaving, and 7 lists that were only in Cloud SQL in production.)

2021-04-02 23:33 UTC, gbrodman requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1054)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/CompareReservedListsCommand.java, line 68 at r1](https://reviewable.io/reviews/google/nomulus/1054#-MXJucab1rmT-G-MGFY6:-MXJucab1rmT-G-MGFY7:b9cu3rd) ([raw file](https://github.com/google/nomulus/blob/bb7a78226ab2a62987a9ecad6b465057b26240a8/core/src/main/java/google/registry/tools/CompareReservedListsCommand.java#L68)):*
> ```Java
>             datastoreList.getName());
>       } else {
>         String datastoreListString =
> ```

Why are you comparing a sort of toString value for each list rather than just comparing the entries themselves? 

It's likely cleaner to just do something like 

```
ImmutableSet<String> namesInSql = <load the names from SQL>
ImmutableSet<String> namesInDatastore = <load the names from ds>
Set<String> notInDatastore = Sets.difference(namesInsSql, namesInDatastore)
Set<String> notInSql = Sets.difference(namesInDatastore, namesInSql)

<do things with the differences if they're not empty>

for name in Sets.intersection(namesInSql, namesInDatastore):
  load the list from both dbs, compare the entry maps
```
___
*[core/src/main/java/google/registry/tools/CompareReservedListsCommand.java, line 110 at r1](https://reviewable.io/reviews/google/nomulus/1054#-MXJu3z2EOFBPk2h9qFe:-MXJu3z2EOFBPk2h9qFf:blgdb7q) ([raw file](https://github.com/google/nomulus/blob/bb7a78226ab2a62987a9ecad6b465057b26240a8/core/src/main/java/google/registry/tools/CompareReservedListsCommand.java#L110)):*
> ```Java
>     }
> 
>     System.out.printf("Found %s unequal lists.%n", listsWithDiffs);
> ```

nit: `list(s)`
___
*[core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java, line 33 at r1](https://reviewable.io/reviews/google/nomulus/1054#-MXJtnK68Mh9JkEr0-Fl:-MXJtnK68Mh9JkEr0-Fm:b-g2qp8z) ([raw file](https://github.com/google/nomulus/blob/bb7a78226ab2a62987a9ecad6b465057b26240a8/core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java#L33)):*
> ```Java
> public class CompareReservedListCommandTest extends CommandTestCase<CompareReservedListsCommand> {
> 
>   private ImmutableMap<String, ReservedListEntry> reservations;
> ```

these two don't need to be separate instance variables


<!-- Sent from Reviewable.io -->

2021-04-06 20:59 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1054)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/CompareReservedListsCommand.java, line 64 at r2](https://reviewable.io/reviews/google/nomulus/1054#-MXcygEp7YVroXpTZYEj:-MXcygEp7YVroXpTZYEk:bxxhku1) ([raw file](https://github.com/google/nomulus/blob/9a0325c01520dd103d1a6bac8f1b435012b9296f/core/src/main/java/google/registry/tools/CompareReservedListsCommand.java#L64)):*
> ```Java
>         listsWithDiffs++;
>         System.out.printf(
>             "ReservedList with name %s is present in Datastore, but not in Cloud SQL%n",
> ```

Missing period here and elsewhere.
___
*[core/src/main/java/google/registry/tools/CompareReservedListsCommand.java, line 82 at r2](https://reviewable.io/reviews/google/nomulus/1054#-MXcyjxL27eBOCf6QtPV:-MXcyjxL27eBOCf6QtPW:b-id9yox) ([raw file](https://github.com/google/nomulus/blob/9a0325c01520dd103d1a6bac8f1b435012b9296f/core/src/main/java/google/registry/tools/CompareReservedListsCommand.java#L82)):*
> ```Java
>           listsWithDiffs++;
>           System.out.printf(
>               "ReservedList with name %s has different entries in each database%n",
> ```

Why isn't this printing out the differences?  Is that not useful?  If the differences persist even after re-running the dual-write for some reason (like dual write is bugged), you'd definitely want to know what the differences actually are as your next step.
___
*[core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java, line 43 at r2](https://reviewable.io/reviews/google/nomulus/1054#-MXcxxLk6MNq3atDh_5q:-MXcxxLk6MNq3atDh_5r:b-twjt59) ([raw file](https://github.com/google/nomulus/blob/9a0325c01520dd103d1a6bac8f1b435012b9296f/core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java#L43)):*
> ```Java
>             .setLastUpdateTime(fakeClock.nowUtc())
>             .setShouldPublish(false)
>             .setReservedListMap(
> ```

There's an easier way to do this; see https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/testing/DatabaseHelper.java;l=350
___
*[core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java, line 71 at r2](https://reviewable.io/reviews/google/nomulus/1054#-MXcy2s45SYhBWA-RXVA:-MXcy2s45SYhBWA-RXVB:b-nbniwp) ([raw file](https://github.com/google/nomulus/blob/9a0325c01520dd103d1a6bac8f1b435012b9296f/core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java#L71)):*
> ```Java
>   void test_success() throws Exception {
>     runCommand();
>     String stdout = getStdoutAsString();
> ```

Can be inlined (elsewhere too).  `assertThat(getStdoutAsString()).....` is perfectly reasonable.
___
*[core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java, line 77 at r2](https://reviewable.io/reviews/google/nomulus/1054#-MXcyK0H0YNWqmVFDdo1:-MXcyK0H0YNWqmVFDdo2:bkspzau) ([raw file](https://github.com/google/nomulus/blob/9a0325c01520dd103d1a6bac8f1b435012b9296f/core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java#L77)):*
> ```Java
>   @Test
>   void test_listMissingFromCloudSql() throws Exception {
>     jpaTm().transact(() -> jpaTm().delete(reservedList));
> ```

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/testing/DatabaseHelper.java;drc=eabf056f9b2347f863dcc0334334d6219906e6e9;l=1241 makes these simpler.
___
*[core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java, line 102 at r2](https://reviewable.io/reviews/google/nomulus/1054#-MXcySZU7QwWFQX0Ds2O:-MXcySZU7QwWFQX0Ds2P:bdwo88c) ([raw file](https://github.com/google/nomulus/blob/9a0325c01520dd103d1a6bac8f1b435012b9296f/core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java#L102)):*
> ```Java
>         ImmutableMap.of(
>             "food",
>             ReservedListEntry.create("food", ReservationType.RESERVED_FOR_SPECIFIC_USE, null));
> ```

Another good use case for using `persistReservedList(String listName, String... lines)`


<!-- Sent from Reviewable.io -->

2021-04-06 21:00 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1054)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/CompareReservedListsCommand.java, line 94 at r2](https://reviewable.io/reviews/google/nomulus/1054#-MXcz6JR2Io32d-bHPKD:-MXcz6JR2Io32d-bHPKE:b-pyjuo5) ([raw file](https://github.com/google/nomulus/blob/9a0325c01520dd103d1a6bac8f1b435012b9296f/core/src/main/java/google/registry/tools/CompareReservedListsCommand.java#L94)):*
> ```Java
>         listsWithDiffs++;
>         System.out.printf(
>             "ReservedList with name %s is present in Cloud SQL, but not in Datastore%n",
> ```

It's a minor nit but `ReservedList '%s'` reads cleaner to me than `ReservedList with name %s`.  The latter is just a little bit clunky and overly long.
___
*[core/src/main/java/google/registry/tools/CompareReservedListsCommand.java, line 99 at r2](https://reviewable.io/reviews/google/nomulus/1054#-MXcz3hv6COigSnmZmEH:-MXcz3hv6COigSnmZmEI:bb38a0m) ([raw file](https://github.com/google/nomulus/blob/9a0325c01520dd103d1a6bac8f1b435012b9296f/core/src/main/java/google/registry/tools/CompareReservedListsCommand.java#L99)):*
> ```Java
>     }
> 
>     System.out.printf("Found %s unequal list(s).%n", listsWithDiffs);
> ```

Should be `%d`


<!-- Sent from Reviewable.io -->

2021-04-07 00:43 UTC, gbrodman requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1054)* status: all files reviewed, 8 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/CompareReservedListsCommand.java, line 68 at r1](https://reviewable.io/reviews/google/nomulus/1054#-MXJucab1rmT-G-MGFY6:-MXdlUVa7A4Cj9kT0bmj:b-7adykc) ([raw file](https://github.com/google/nomulus/blob/bb7a78226ab2a62987a9ecad6b465057b26240a8/core/src/main/java/google/registry/tools/CompareReservedListsCommand.java#L68)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think this is quite done -- you're still doing  some of the "do the databases contain lists with the same names" logic inside the datastoreList for-loop. 

If you compare the name sets initially, you can later loop over only the intersection of the lists and thus guarantee that the list you're checking exists in both DBs.
___
*[core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java, line 60 at r3](https://reviewable.io/reviews/google/nomulus/1054#-MXdlsnoCjSHk3pqr3Gv:-MXdlsnoCjSHk3pqr3Gw:b-lkjbuj) ([raw file](https://github.com/google/nomulus/blob/da3f9a071b94d6c76e3b6fedf80718bad7e6098d/core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java#L60)):*
> ```Java
>   @Test
>   void test_listMissingFromDatastore() throws Exception {
>     ofyTm()
> ```

unlike the comment on the previous test, I do believe we should be able to use DatabaseHelper::deleteResource here? 
___
*[core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java, line 93 at r3](https://reviewable.io/reviews/google/nomulus/1054#-MXdm-8FAetl9z_1Nwjs:-MXdm-8FAetl9z_1Nwjt:by2pmip) ([raw file](https://github.com/google/nomulus/blob/da3f9a071b94d6c76e3b6fedf80718bad7e6098d/core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java#L93)):*
> ```Java
>   @Test
>   void test_listsDifferAndMissing() throws Exception {
>     ofyTm()
> ```

ditto comment re: using DH:deleteResource?


<!-- Sent from Reviewable.io -->

2021-04-07 01:29 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1054)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-04-08 18:07 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1054)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/CompareReservedListsCommand.java, line 68 at r1](https://reviewable.io/reviews/google/nomulus/1054#-MXJucab1rmT-G-MGFY6:-MXmeG_d8iUCMbIHSy64:b-uwi2fs) ([raw file](https://github.com/google/nomulus/blob/bb7a78226ab2a62987a9ecad6b465057b26240a8/core/src/main/java/google/registry/tools/CompareReservedListsCommand.java#L68)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I'm not quite sure I understand what you're saying here. The if statement checks that the list with the name in Datastore also exists in cloud SQL and only checks the content of the list if it is.
</blockquote></details>

The point is that in order to reduce indentation and reduce the complexity of each loop, the "do the stores contain the same lists?" and "do the lists that are in both DBs match each other?" questions should be answered in different sections, i.e. the pseudocode snippet above 

that way, when we're loading the contents themselves we don't need to worry about whether or not the list is in both DBs since we already checked that separately 
___
*[core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java, line 60 at r3](https://reviewable.io/reviews/google/nomulus/1054#-MXdlsnoCjSHk3pqr3Gv:-MXmea7I87XX3fgWPPsD:b-mtzqx) ([raw file](https://github.com/google/nomulus/blob/da3f9a071b94d6c76e3b6fedf80718bad7e6098d/core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java#L60)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Yes, it would only delete from Datastore now, but after the asynchronous migration, it will only delete from Cloud SQL which is the wrong behavior for this test. The Datastore code for ReservedList will likely already be deleted by the time asynchronous migration happens, but in case it is not, I think this test should specify the correct transaction manager to use.
</blockquote></details>

fair enough


<!-- Sent from Reviewable.io -->

2021-04-09 23:21 UTC, gbrodman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1054#-:-MXswBt48rcCgN09Tj9d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-04-09 23:25 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1054)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/CompareReservedListsCommand.java, line 59 at r4](https://reviewable.io/reviews/google/nomulus/1054#-MXsx29J3jy19rxknQsN:-MXsx29J3jy19rxknQsO:bqvfu4k) ([raw file](https://github.com/google/nomulus/blob/aa8a68e3ed727b5af6552e5fb807775ec6d41f4b/core/src/main/java/google/registry/tools/CompareReservedListsCommand.java#L59)):*
> ```Java
>     int listsWithDiffs = 0;
> 
>     for (String listName : notInCloudSql) {
> ```

nit, which is my bad since it was my suggestion to begin with: you can inline the Sets.difference() call in this if statement since I don't think we need it anywhere else (and same for the other similar one)


<!-- Sent from Reviewable.io -->

2021-04-12 20:08 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1054)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-04-13 15:45 UTC, merged