Add a ComparePremiumLists command
google/nomulus pull request #1056
Opened 2021-04-05 22:18 UTC by sarahcaseybot

This behaves similarly to how the CompareReservedListCommand works in go/r3pr/1054. I already ran this test in Sandbox and Production and found no unequal lists.

2021-04-07 14:40 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1056)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1056#-MXgkV4J5TKsSiIumEPA:-MXgkV4J5TKsSiIumEPB:b2kew66) ([raw file](https://github.com/google/nomulus/blob/c1c8560251fd9ae95c34feac54dd5b7d83374584/core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java#L45)):*
> ```Java
>   public void run() {
>     ImmutableSet<PremiumList> datastoreLists =
>         tm().loadAllOf(PremiumList.class).stream()
> ```

Should this be `ofyTm()`?
___
*[core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java, line 50 at r1](https://reviewable.io/reviews/google/nomulus/1056#-MXgkM4pEozYE0xag_UT:-MXgkM4pEozYE0xag_UU:b-i83jp0) ([raw file](https://github.com/google/nomulus/blob/c1c8560251fd9ae95c34feac54dd5b7d83374584/core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java#L50)):*
> ```Java
>             .filter(Optional::isPresent)
>             .map(Optional::get)
>             .peek(list -> Hibernate.initialize(list.getLabelsToPrices()))
> ```

That's strange to me that loading the lists from Datastore would require anything having to do with Hibernate.
___
*[core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java, line 68 at r1](https://reviewable.io/reviews/google/nomulus/1056#-MXgkg-HEx1eqLGmN2FV:-MXgkg-HEx1eqLGmN2FW:bw1obzr) ([raw file](https://github.com/google/nomulus/blob/c1c8560251fd9ae95c34feac54dd5b7d83374584/core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java#L68)):*
> ```Java
>         .transact(
>             () -> {
>               int listsWithDiffs = 0;
> ```

Extract all of the content inside this transaction into a helper method so you can reduce the level of indentation going on.  Something like `comparePremiumLists()` would work for the name.
___
*[core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java, line 81 at r1](https://reviewable.io/reviews/google/nomulus/1056#-MXgl29J-dxFXEutkB1o:-MXgl29J-dxFXEutkB1p:b-4i6dte) ([raw file](https://github.com/google/nomulus/blob/c1c8560251fd9ae95c34feac54dd5b7d83374584/core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java#L81)):*
> ```Java
> 
>                   // Datastore and Cloud SQL use different objects to represent premium list entries
>                   // so the best way to compare them is to compare their string representations.
> ```

Really?  I would think that comparing Sets of Strings would be better than comparing newline-delimited strings.  Then you can use the Set functions like `Sets.difference()`.
___
*[core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/1056#-MXglCxSEZK40zJT-Etb:-MXglCxSEZK40zJT-Etc:bqjqic1) ([raw file](https://github.com/google/nomulus/blob/c1c8560251fd9ae95c34feac54dd5b7d83374584/core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java#L135)):*
> ```Java
>               }
> 
>               System.out.printf("Found %s unequal list(s).%n", listsWithDiffs);
> ```

Should be `%d`.

I'm getting the feeling that this PR started off as a copy-paste of the similar command for comparing reserved lists, but that the comments that were addressed over there weren't yet addressed on this one.  I'd recommend going back through this one to see if there's anything else to correct based on comments from the other PR.


<!-- Sent from Reviewable.io -->

2021-04-09 23:26 UTC, gbrodman requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1056)* status: all files reviewed, 7 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java, line 59 at r2](https://reviewable.io/reviews/google/nomulus/1056#-MXswqEV6U0bq1QG1x8z:-MXswqEV6U0bq1QG1x9-:bqvfu4k) ([raw file](https://github.com/google/nomulus/blob/b90c1035bc987bb2967bb12868b38f42eaefb345/core/src/main/java/google/registry/tools/ComparePremiumListsCommand.java#L59)):*
> ```Java
>     int listsWithDiffs = 0;
> 
>     for (String listName : notInCloudSql) {
> ```

nit, which is my bad since it was my suggestion to begin with: you can inline the Sets.difference() call in this if statement since I don't think we need it anywhere else (and same for the other similar one)
___
*[core/src/test/java/google/registry/tools/ComparePremiumListsCommandTest.java, line 50 at r2](https://reviewable.io/reviews/google/nomulus/1056#-MXsxKCK8N_sXwAQsV1v:-MXsxKCK8N_sXwAQsV1w:b-grfmie) ([raw file](https://github.com/google/nomulus/blob/b90c1035bc987bb2967bb12868b38f42eaefb345/core/src/test/java/google/registry/tools/ComparePremiumListsCommandTest.java#L50)):*
> ```Java
>         .transact(
>             () -> {
>               while (PremiumListSqlDao.getLatestRevision("how").isPresent()) {
> ```

why is this "while" loop necessary? 


<!-- Sent from Reviewable.io -->

2021-04-12 22:53 UTC, gbrodman approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1056)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-04-14 20:21 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1056)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-04-14 22:10 UTC, merged