Fix TimestampInversionException
google/nomulus pull request #1065
Opened 2021-04-07 22:57 UTC by sarahcaseybot

2021-04-08 00:55 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1065)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java, line 79 at r1](https://reviewable.io/reviews/google/nomulus/1065#-MXiyTm_AjHncR9DGanU:-MXiyTm_AjHncR9DGanV:b-7ik312) ([raw file](https://github.com/google/nomulus/blob/7b260e55a15474d72744e564545eb27b7a471cab/core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java#L79)):*
> ```
>  fakeClock.advanceOneMilli();
> ```
This won't fix the problem. Please see my comment below.
___
*[core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java, line 153 at r1](https://reviewable.io/reviews/google/nomulus/1065#-MXiw5bM4XJhpCu01cb7:-MXiw5bM4XJhpCu01cb8:b-6xg121) ([raw file](https://github.com/google/nomulus/blob/7b260e55a15474d72744e564545eb27b7a471cab/core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java#L153)):*
> ```
> PremiumListDualDao.delete(toDelete);
> ```
The delete method can cause problems in tests. It executes multiple transactions, triggering multiple commitLogs to be saved. If some of the commitLogs are mapped to the same CommitLogBucket, an exception will be thrown. And if the bucket collision persists through all retries, the test will fail.

The easiest approach is to add a autoIncrement mode to the FakeClock, similar to the FakeClock in the internal common.base class:
http://cs/google3/java/com/google/common/time/testing/FakeClock.java


<!-- Sent from Reviewable.io -->

2021-04-08 00:56 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1065)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java, line 153 at r1](https://reviewable.io/reviews/google/nomulus/1065#-MXiw5bM4XJhpCu01cb7:-MXiycui6wFab-pV_R_N:bjpgpdp) ([raw file](https://github.com/google/nomulus/blob/7b260e55a15474d72744e564545eb27b7a471cab/core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java#L153)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> PremiumListDualDao.delete(toDelete);
> ```
The delete method can cause problems in tests. It executes multiple transactions, triggering multiple commitLogs to be saved. If some of the commitLogs are mapped to the same CommitLogBucket, an exception will be thrown. And if the bucket collision persists through all retries, the test will fail.

The easiest approach is to add a autoIncrement mode to the FakeClock, similar to the FakeClock in the internal common.base class:
http://cs/google3/java/com/google/common/time/testing/FakeClock.java
</blockquote></details>

Then you can enable the autoIncrement mode in this class.


<!-- Sent from Reviewable.io -->

2021-04-12 17:17 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1065)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @mindhog, @sarahcaseybot, and @weiminyu)

___
*[common/src/testing/java/google/registry/testing/FakeClock.java, line 58 at r2](https://reviewable.io/reviews/google/nomulus/1065#-MY63nbY3Pjk5fglRfri:-MY63nbY3Pjk5fglRfrj:b5r6n93) ([raw file](https://github.com/google/nomulus/blob/97d8348262e6f489d1261d6ec5c02d4acc61c510/common/src/testing/java/google/registry/testing/FakeClock.java#L58)):*
> ```
>    * Sets the increment applied to the clock whenever it is queried. The increment is zero by
>    * default: the clock is left unchanged when queried.
> ```
We may want to emphasize here that passing in 0 unsets the auto incremental mode.
___
*[core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java, line 64 at r2](https://reviewable.io/reviews/google/nomulus/1065#-MY63wxp91uUzf6S2ISX:-MY63wxp91uUzf6S2ISY:bbvaklu) ([raw file](https://github.com/google/nomulus/blob/97d8348262e6f489d1261d6ec5c02d4acc61c510/core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java#L64)):*
> ```
> fakeClock.setAutoIncrementStep(Duration.millis(1));
> ```
It may be better to define an extension that automatically unsets the auto mode. There are tests that depend on a manually driven clock.

It doesn't have to be in this PR. We can make do with an AfterEach in this class for now.


<!-- Sent from Reviewable.io -->

2021-04-12 19:53 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1065)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java, line 64 at r2](https://reviewable.io/reviews/google/nomulus/1065#-MY63wxp91uUzf6S2ISX:-MY6bxNM688cIWQBoYbG:bg6cx2f) ([raw file](https://github.com/google/nomulus/blob/97d8348262e6f489d1261d6ec5c02d4acc61c510/core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java#L64)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> fakeClock.setAutoIncrementStep(Duration.millis(1));
> ```
It may be better to define an extension that automatically unsets the auto mode. There are tests that depend on a manually driven clock.

It doesn't have to be in this PR. We can make do with an AfterEach in this class for now.
</blockquote></details>

Rephrasing previous comment: it is better to restore the default clock state (disable the auto increment mode) after the test, so that no assumption about fakeClock allocation in the parent class is needed.


<!-- Sent from Reviewable.io -->

2021-04-13 00:43 UTC, weiminyu approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1065)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)



<!-- Sent from Reviewable.io -->

2021-04-13 13:27 UTC, mindhog approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1065)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2021-04-13 15:59 UTC, merged