Update various tests to work with SQL as well
google/nomulus pull request #1078
Opened 2021-04-14 01:13 UTC by gbrodman

The main weird bit here is adding a method in DatabaseHelper to
retrieve and initialize all objects in either database. The
initialization is necessary since it's used post-command-dry-run to make
sure that no changes were actually made.

2021-04-14 17:33 UTC, gbrodman commented
Ignore the LGTM comment; I didn't change that file

2021-04-14 19:39 UTC, mindhog requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1078)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/flows/FlowTestCase.java, line 182 at r1](https://reviewable.io/reviews/google/nomulus/1078#-MYGpm236oiKVzmIRoMU:-MYGpm236oiKVzmIRoMV:be143nm) ([raw file](https://github.com/google/nomulus/blob/4a971b827ecff4312c72e80b0a3740aa0bfd1cca/core/src/test/java/google/registry/flows/FlowTestCase.java#L182)):*
> ```Java
>   protected void assertNoHistory() {
>     if (tm().isOfy()) {
>       assertThat(ofy().load().type(HistoryEntry.class)).isEmpty();
> ```

Does HistoryEntryDao not speak ofy?  Any reason not to put this call there?


<!-- Sent from Reviewable.io -->

2021-04-14 19:58 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1078)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/test/java/google/registry/flows/FlowTestCase.java, line 182 at r1](https://reviewable.io/reviews/google/nomulus/1078#-MYGpm236oiKVzmIRoMU:-MYGwJcR3W8JkIjnAxD9:b-2uv1vb) ([raw file](https://github.com/google/nomulus/blob/4a971b827ecff4312c72e80b0a3740aa0bfd1cca/core/src/test/java/google/registry/flows/FlowTestCase.java#L182)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Does HistoryEntryDao not speak ofy?  Any reason not to put this call there?
</blockquote></details>

You are correct!


<!-- Sent from Reviewable.io -->

2021-04-15 14:57 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1078)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 1285 at r2](https://reviewable.io/reviews/google/nomulus/1078#-MYL113f-TQU24YEke5x:-MYL113f-TQU24YEke5y:bypne9w) ([raw file](https://github.com/google/nomulus/blob/936055cbcc6a35fce76dd264e6b5cd9691c02a1a/core/src/test/java/google/registry/testing/DatabaseHelper.java#L1285)):*
> ```Java
>   }
> 
>   public static List<Object> loadAllEntities() {
> ```

Missing Javadoc (common issue I see when reviewing your PRs).
___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 1297 at r2](https://reviewable.io/reviews/google/nomulus/1078#-MYL0uLZCPYLx-AuvhYB:-MYL0uLZCPYLx-AuvhYC:b-xag1sf) ([raw file](https://github.com/google/nomulus/blob/936055cbcc6a35fce76dd264e6b5cd9691c02a1a/core/src/test/java/google/registry/testing/DatabaseHelper.java#L1297)):*
> ```Java
>                         .collect(toImmutableList());
>                 ImmutableList.Builder<Object> result = new ImmutableList.Builder<>();
>                 for (Class<?> entityClass : entityClasses) {
> ```

Yeesh, what're the performance implications of this?  Not good, but only affect tests that actually use them?
___
*[core/src/test/java/google/registry/tmch/LordnTaskUtilsTest.java, line 114 at r2](https://reviewable.io/reviews/google/nomulus/1078#-MYL199mB0ipIEkZGvNB:-MYL199mB0ipIEkZGvNC:b2xtx2z) ([raw file](https://github.com/google/nomulus/blob/936055cbcc6a35fce76dd264e6b5cd9691c02a1a/core/src/test/java/google/registry/tmch/LordnTaskUtilsTest.java#L114)):*
> ```Java
>   }
> 
>   @TestOfyOnly // fails due to foreign key constraints in SQL
> ```

How do we fix it so that this succeeds?  Doesn't this test need to work in SQL?


<!-- Sent from Reviewable.io -->

2021-04-15 16:08 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1078)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 1285 at r2](https://reviewable.io/reviews/google/nomulus/1078#-MYL113f-TQU24YEke5x:-MYLHa9J-6pI2PVPwOL8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/936055cbcc6a35fce76dd264e6b5cd9691c02a1a/core/src/test/java/google/registry/testing/DatabaseHelper.java#L1285)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Missing Javadoc (common issue I see when reviewing your PRs).
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 1297 at r2](https://reviewable.io/reviews/google/nomulus/1078#-MYL0uLZCPYLx-AuvhYB:-MYLFech3vqEReEMwFW9:b1gwyp0) ([raw file](https://github.com/google/nomulus/blob/936055cbcc6a35fce76dd264e6b5cd9691c02a1a/core/src/test/java/google/registry/testing/DatabaseHelper.java#L1297)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yeesh, what're the performance implications of this?  Not good, but only affect tests that actually use them?
</blockquote></details>

Correct. It only affects tests that run dry-run flows, and there are only 21 places where `FlowTestCase::dryRuFlowAssertResponse` is called 
___
*[core/src/test/java/google/registry/tmch/LordnTaskUtilsTest.java, line 114 at r2](https://reviewable.io/reviews/google/nomulus/1078#-MYL199mB0ipIEkZGvNB:-MYLG-iOERenip7K2tG9:bphtivd) ([raw file](https://github.com/google/nomulus/blob/936055cbcc6a35fce76dd264e6b5cd9691c02a1a/core/src/test/java/google/registry/tmch/LordnTaskUtilsTest.java#L114)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

How do we fix it so that this succeeds?  Doesn't this test need to work in SQL?
</blockquote></details>

Not really, or at least this isn't the right place to test it. In SQL this fails before we even get to the lordn test part because you just *cannot* persist a domain with a nonexistent registrar

Clarified in comment


<!-- Sent from Reviewable.io -->

2021-04-15 19:50 UTC, mindhog approved these changes
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1078)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-04-19 15:48 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1078)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/tools/UpdateCursorsCommandTest.java, line 69 at r3](https://reviewable.io/reviews/google/nomulus/1078#-MYeo3Yz3tTEVJt1vrWu:-MYeo3Yz3tTEVJt1vrWv:bvbyhet) ([raw file](https://github.com/google/nomulus/blob/5e41109768cfadbd8afd72df516b5df7508311bb/core/src/test/java/google/registry/tools/UpdateCursorsCommandTest.java#L69)):*
> ```Java
>   @TestOfyAndSql
>   void testSuccess_oldValueisEmpty() throws Exception {
>     Truth8.assertThat(loadByKeyIfPresent(Cursor.createVKey(CursorType.BRDA, registry.getTldStr())))
> ```

Use `static import`s for `assertThat`.  Yes, you can statically import the same symbol from multiple packages, and we do that in dozens of other test classes for this exact `assertThat()` overload.


<!-- Sent from Reviewable.io -->

2021-04-19 16:00 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1078)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/tools/UpdateCursorsCommandTest.java, line 69 at r3](https://reviewable.io/reviews/google/nomulus/1078#-MYeo3Yz3tTEVJt1vrWu:-MYeqT1qAcMGh7tS2biP:b-t9tvgb) ([raw file](https://github.com/google/nomulus/blob/5e41109768cfadbd8afd72df516b5df7508311bb/core/src/test/java/google/registry/tools/UpdateCursorsCommandTest.java#L69)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use `static import`s for `assertThat`.  Yes, you can statically import the same symbol from multiple packages, and we do that in dozens of other test classes for this exact `assertThat()` overload.
</blockquote></details>

for real? neat


<!-- Sent from Reviewable.io -->

2021-04-20 13:45 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1078)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-04-20 15:52 UTC, merged