Defer all foreign keys in SQL
google/nomulus pull request #1094
Opened 2021-04-19 19:26 UTC by gbrodman

The main difference here is that the constraint violation exceptions
won't be thrown until the transaction is completed, rather than when the
insert is first performed within the transaction. We get the same error
message either way. The primary benefit to this is that when dealing
with large operations inside a single transaction (flows), we don't need
to worry about the order of insertions of removals with regards to
foreign keys.

2021-04-20 18:36 UTC, mindhog approved these changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1094)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-04-20 20:28 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1094)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[db/src/main/resources/sql/flyway.txt, line 93 at r1](https://reviewable.io/reviews/google/nomulus/1094#-MYkxytdAbL-cDMylX4m:-MYkxytdAbL-cDMylX4n:b-y8m0b1) ([raw file](https://github.com/google/nomulus/blob/43b3d95ed44bd514975a9febed10b76ac5d8502a/db/src/main/resources/sql/flyway.txt#L93)):*
> ```
> V93__defer_all_fkeys.sql
> ```
Need to wait V92__ is fixed.


<!-- Sent from Reviewable.io -->

2021-04-20 20:29 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1094)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[db/src/main/resources/sql/flyway.txt, line 93 at r1](https://reviewable.io/reviews/google/nomulus/1094#-MYkxytdAbL-cDMylX4m:-MYkyHi-E-g92oWSCwpW:byh75tz) ([raw file](https://github.com/google/nomulus/blob/43b3d95ed44bd514975a9febed10b76ac5d8502a/db/src/main/resources/sql/flyway.txt#L93)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> V93__defer_all_fkeys.sql
> ```
Need to wait V92__ is fixed.
</blockquote></details>

That already went through. 


<!-- Sent from Reviewable.io -->

2021-04-21 18:23 UTC, weiminyu approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1094)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-04-21 18:29 UTC, merged