Stop dual read and dual write of SMDRL
google/nomulus pull request #1095
Opened 2021-04-19 21:31 UTC by sarahcaseybot

2021-04-19 23:44 UTC, gbrodman requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1095)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 28 at r1](https://reviewable.io/reviews/google/nomulus/1095#-MYgRfN67UD6G1GIs9w-:-MYgRfN67UD6G1GIs9w0:bptl1hl) ([raw file](https://github.com/google/nomulus/blob/35c20f31243d8ed402874a767f6446778cbc75f8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L28)):*
> ```Java
>   private static final FluentLogger logger = FluentLogger.forEnclosingClass();
> 
>   /**
> ```

nit: we can one-line the javadoc comment
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 53 at r1](https://reviewable.io/reviews/google/nomulus/1095#-MYgRwO1Et2l7nY1vBNI:-MYgRwO1Et2l7nY1vBNJ:b-t20vv2) ([raw file](https://github.com/google/nomulus/blob/35c20f31243d8ed402874a767f6446778cbc75f8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L53)):*
> ```Java
>   }
> 
>   /**
> ```

same nit about one-lining the javadoc 
___
*[core/src/test/java/google/registry/model/smd/SignedMarkRevocationListDaoTest.java, line 34 at r1](https://reviewable.io/reviews/google/nomulus/1095#-MYgWEi89lEhCme8iEb2:-MYgWEi89lEhCme8iEb3:bs8zekh) ([raw file](https://github.com/google/nomulus/blob/35c20f31243d8ed402874a767f6446778cbc75f8/core/src/test/java/google/registry/model/smd/SignedMarkRevocationListDaoTest.java#L34)):*
> ```Java
> 
>   @Test
>   void testSave_cloudSqlPrimary_success() {
> ```

let's remove the references to "cloud sql" in the test names please 
___
*[core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java, line 42 at r1](https://reviewable.io/reviews/google/nomulus/1095#-MYgS5bEDOZlzDRbiza1:-MYgS5bEDOZlzDRbiza2:behhw1w) ([raw file](https://github.com/google/nomulus/blob/35c20f31243d8ed402874a767f6446778cbc75f8/core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java#L42)):*
> ```Java
> 
>   @Test
>   void testUnshardedSaveFails() {
> ```

I think this test should be deleted too right? 


<!-- Sent from Reviewable.io -->

2021-04-20 13:53 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1095)* status: all files reviewed, 5 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 32 at r1](https://reviewable.io/reviews/google/nomulus/1095#-MYjY-Ct9yi7KfKDd8tb:-MYjY-Ct9yi7KfKDd8tc:b-xx0x2q) ([raw file](https://github.com/google/nomulus/blob/35c20f31243d8ed402874a767f6446778cbc75f8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L32)):*
> ```Java
>    */
>   static SignedMarkRevocationList load() {
>     Optional<SignedMarkRevocationList> primaryList =
> ```

Why is this still called `primaryList`?  How about just naming it `smdrl` instead?


<!-- Sent from Reviewable.io -->

2021-04-20 20:26 UTC, gbrodman approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1095)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-04-20 21:01 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1095)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-04-20 21:09 UTC, merged