Remove SMDRL completely from Datastore
google/nomulus pull request #1104
Opened 2021-04-22 16:19 UTC by sarahcaseybot

2021-04-22 17:59 UTC, weiminyu requested changes
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1104)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java, line 53 at r1](https://reviewable.io/reviews/google/nomulus/1104#-MYuejzt29JmQtTsRtNu:-MYuejzt29JmQtTsRtNv:bk4uxwv) ([raw file](https://github.com/google/nomulus/blob/7a744a3168d2a9f3493f79f73d0ce576ce52860e/core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java#L53)):*
> ```
> @NotBackedUp(reason = Reason.EXTERNALLY_SOURCED)
> ```
Is this still necessary?
___
*[core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java, line 34 at r1](https://reviewable.io/reviews/google/nomulus/1104#-MYuhWRI8aavvegu-77x:-MYuhWRI8aavvegu-77y:bipzu0g) ([raw file](https://github.com/google/nomulus/blob/7a744a3168d2a9f3493f79f73d0ce576ce52860e/core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java#L34)):*
> ```
>   SignedMarkRevocationListTest() {
>     super(JpaEntityCoverageCheck.ENABLED);
>   }
> ```
Not necessary here.

The entityCoverageCheck is only meaningful in the members of the SqlIntegrationTestSuite. It ensures that every entity listed in the Persistence.xml has been used at least once in that test suite. The test suite will be run on deployed schema versions as a smoke test on schema compatibility. 

The SignedMarkRevocationListDaoTest is already a member of the suite and includes SignedMarkRevocationList in the coverage.


<!-- Sent from Reviewable.io -->

2021-04-22 20:21 UTC, weiminyu approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1104)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-04-22 20:32 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1104)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java, line 110 at r2](https://reviewable.io/reviews/google/nomulus/1104#-MYvGOCLCfxXUFmEEfj0:-MYvGOCM5JoNVVHdXCIT:b-jl4h5w) ([raw file](https://github.com/google/nomulus/blob/d094624ea2be6db6c6682d404ef7210e8012c78d/core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java#L110)):*
> ```Java
>   @Override
>   public Optional<DatastoreEntity> toDatastoreEntity() {
>     return Optional.empty(); // Not persisted in Datastore
> ```

We sure this is gonna work as intended?
___
*[core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java, line 86 at r2](https://reviewable.io/reviews/google/nomulus/1104#-MYvGmQt8LmKPxKM9bNa:-MYvGmQuEk_BXPEcPMlJ:b-mv15xy) ([raw file](https://github.com/google/nomulus/blob/d094624ea2be6db6c6682d404ef7210e8012c78d/core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java#L86)):*
> ```Java
>   @Test
>   void test_isSmdRevoked_present() {
>     final int rows = 100001;
> ```

100,000 is an awfully large number.  I don't see why it's necessary for the tests to use such a large list.  Note that Datastore was using 10,000 as the shard size, so actual different behavior happened past that size.  That's not true here in Cloud SQL, so I think we can do smaller and have the tests be more performant.


<!-- Sent from Reviewable.io -->

2021-04-26 18:48 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1104#-:-MZEVod9BMQSZ9SurPMn:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @sarahcaseybot)

___
*[core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java, line 86 at r2](https://reviewable.io/reviews/google/nomulus/1104#-MYvGmQt8LmKPxKM9bNa:-MZEVXSG4imaa7ym9hlN:bon0ta2) ([raw file](https://github.com/google/nomulus/blob/d094624ea2be6db6c6682d404ef7210e8012c78d/core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java#L86)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

10,000 is still pretty large.  You could go significantly smaller still.  10,000 was a cut-off point beyond which the behavior changed in Datastore, but that's no longer true.  Could just do 100.


<!-- Sent from Reviewable.io -->

2021-04-26 21:15 UTC, merged