Populate the domain in DomainHistory objects created in Domain flows
google/nomulus pull request #1106
Opened 2021-04-23 22:27 UTC by gbrodman

Unfortunately, much of the time there's a bit of a circular dependency
in the object creation, e.g. the Domain object stores references to the
billing events which store references to the history object which
contains the Domain object. As a result, we sort of need to create the
history object twice.

2021-04-27 21:30 UTC, mindhog requested changes
Optional: have you considered using a `Builder<DomainHistory>` instead of the `DomainHistory` object itself for the initial history object?  It's a fairly minor point, but it seems like this could save a few extra copies, as well as the associated `toBuilder()...build()` dance.

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106#-:-MZKDmnd6Cs9VH3SxiAH:bl45nj6)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 167 at r1](https://reviewable.io/reviews/google/nomulus/1106#-MZKB4-Y-8Gd4eEFHVoU:-MZKB4-Z7pFaMBrB5gCC:b-u4xxvw) ([raw file](https://github.com/google/nomulus/blob/59defe8aa2b09373532929026063ad4c80f1bc60/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L167)):*
> ```Java
>       postLoad();
>     }
>     hashCode = null; // reset the hash code since we may have changed the entities
> ```

Do we have evidence that the hash code has been created at this time?  `restoreOfyKeys()` should only be called during object construction, prior to the creation of the hash code.
___
*[core/src/test/java/google/registry/flows/ResourceFlowTestCase.java, line 198 at r1](https://reviewable.io/reviews/google/nomulus/1106#-MZKCvjdBVIpRZeYbJOQ:-MZKCvjdBVIpRZeYbJOR:br40uud) ([raw file](https://github.com/google/nomulus/blob/59defe8aa2b09373532929026063ad4c80f1bc60/core/src/test/java/google/registry/flows/ResourceFlowTestCase.java#L198)):*
> ```Java
>         assertAboutImmutableObjects()
>             .that(contactHistory.getContactBase().get())
>             .isEqualExceptFields(resource);
> ```

This can simply be isEqual(), right?  Same below.


<!-- Sent from Reviewable.io -->

2021-04-27 23:00 UTC, gbrodman reviewed
No, we cannot unfortunately. The reason is fundamental to the circular dependency, that we must know the DomainHistory's `id` value when we create the billing events et al. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106#-:-MZKYkuj7vzflJFSJvCs:bn1grea)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 167 at r1](https://reviewable.io/reviews/google/nomulus/1106#-MZKB4-Y-8Gd4eEFHVoU:-MZKU0lf7DE-RKnYuC22:b-sy3b70) ([raw file](https://github.com/google/nomulus/blob/59defe8aa2b09373532929026063ad4c80f1bc60/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L167)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Do we have evidence that the hash code has been created at this time?  `restoreOfyKeys()` should only be called during object construction, prior to the creation of the hash code.
</blockquote></details>

Yes we do, it was causing test failures because while the fields were equal in two TransferData objects stored inside their respective two DomainContent objects, the hash codes were not. (so it's an issue with nested objects) 
___
*[core/src/test/java/google/registry/flows/ResourceFlowTestCase.java, line 198 at r1](https://reviewable.io/reviews/google/nomulus/1106#-MZKCvjdBVIpRZeYbJOQ:-MZKUzWn4TqxZhs5qq4Q:bdmbjis) ([raw file](https://github.com/google/nomulus/blob/59defe8aa2b09373532929026063ad4c80f1bc60/core/src/test/java/google/registry/flows/ResourceFlowTestCase.java#L198)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

This can simply be isEqual(), right?  Same below.
</blockquote></details>

yep, I was thinking that we might need additional fields removed from consideration for host or contact objects but it appears not to be the case (i've worked through the other flows locally) 


<!-- Sent from Reviewable.io -->

2021-04-28 11:27 UTC, mindhog reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)



<!-- Sent from Reviewable.io -->

2021-04-28 11:27 UTC, mindhog approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106#-:-MZNE0wM1hpirifT5fds:bb6ywmx)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)



<!-- Sent from Reviewable.io -->

2021-04-29 15:46 UTC, CydeWeys requested changes
> The reason is fundamental to the circular dependency, that we must know the DomainHistory's id value when we create the billing events et al.

That's what `allocateId` is for.  We had this circular dependency problem in Datastore too, and we solved it there.  See e.g.: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java;l=305;drc=95fdd36c7751915efca672dff5a1fb7d3f12c9ce;bpv=1;bpt=1

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106#-:-MZTIUbD8PMzn_Qq7FUI:b-pka41h)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-04-29 15:48 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 167 at r2](https://reviewable.io/reviews/google/nomulus/1106#-MZTJ0p6A34WuAmDTmw_:-MZTJ0p6A34WuAmDTmwa:b-uviizs) ([raw file](https://github.com/google/nomulus/blob/6000b7044acf920c18b8376ce24cb0c0030f3011/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L167)):*
> ```Java
>       postLoad();
>     }
>     hashCode = null; // reset the hash code since we may have changed the entities
> ```

This seems hackish.  Why null it out instead of recalculating it?  Isn't there a risk of two entities both having a null hash code accidentally being considered equal?  Why is this line of code even here?


<!-- Sent from Reviewable.io -->

2021-04-30 21:17 UTC, gbrodman reviewed
Done, didn't know about manually allocating the ID. It required some refactoring overall but it's fairly straightforward 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106#-:-MZZS44i1V-OyUvit6kl:bpga77d)* status: 18 of 31 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 167 at r2](https://reviewable.io/reviews/google/nomulus/1106#-MZTJ0p6A34WuAmDTmw_:-MZZQt4c2YfDuVD_UHYq:b-e2djla) ([raw file](https://github.com/google/nomulus/blob/6000b7044acf920c18b8376ce24cb0c0030f3011/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L167)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This seems hackish.  Why null it out instead of recalculating it?  Isn't there a risk of two entities both having a null hash code accidentally being considered equal?  Why is this line of code even here?
</blockquote></details>

If you look in `ImmutableBuilder`'s `equals` method, it compares the hash codes using the hash code getter, which recalculates the hash codes if they're null. The point in nulling it out here is that there's no need to recompute it immediately, maybe it won't ever be necessary -- so just say "this should be recalculated if we ever need it" by nulling it. 

The line of code should be explained by the comment -- the hash code is computed at some point before this assuming immutability, and we are mutating the object. Thus, that previously-calculated hash code is no longer value. 


<!-- Sent from Reviewable.io -->

2021-05-03 12:46 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: 18 of 31 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 167 at r2](https://reviewable.io/reviews/google/nomulus/1106#-MZTJ0p6A34WuAmDTmw_:-MZmEgzP5-LlEA5f7ZFB:b-cavzh1) ([raw file](https://github.com/google/nomulus/blob/6000b7044acf920c18b8376ce24cb0c0030f3011/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L167)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

If you look in `ImmutableBuilder`'s `equals` method, it compares the hash codes using the hash code getter, which recalculates the hash codes if they're null. The point in nulling it out here is that there's no need to recompute it immediately, maybe it won't ever be necessary -- so just say "this should be recalculated if we ever need it" by nulling it. 

The line of code should be explained by the comment -- the hash code is computed at some point before this assuming immutability, and we are mutating the object. Thus, that previously-calculated hash code is no longer value. 
</blockquote></details>

As I consider this further, I'm a bit more concerned about it.  Can we find out where the hash code was previously calculated?  I've seen Hibernate do this in the past when adding objects to internal collections, but I didn't think that happened until after the post-loads for an object were called. 


<!-- Sent from Reviewable.io -->

2021-05-03 14:46 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: 18 of 31 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 167 at r2](https://reviewable.io/reviews/google/nomulus/1106#-MZTJ0p6A34WuAmDTmw_:-MZmgPIA5E7_UHQbeZ15:buu0x90) ([raw file](https://github.com/google/nomulus/blob/6000b7044acf920c18b8376ce24cb0c0030f3011/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L167)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

As I consider this further, I'm a bit more concerned about it.  Can we find out where the hash code was previously calculated?  I've seen Hibernate do this in the past when adding objects to internal collections, but I didn't think that happened until after the post-loads for an object were called. 
</blockquote></details>

The first instance that I see of the hash code being calculated in an arbitrarily-selected failing test is https://github.com/google/nomulus/blob/master/core/src/main/java/google/registry/model/domain/DomainContent.java#L800 

But where that's called is somewhat irrelevant, since it could theoretically be called from pretty much anywhere. 


<!-- Sent from Reviewable.io -->

2021-05-03 15:40 UTC, mindhog requested changes
> Reviewed 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java, line 311 at r3](https://reviewable.io/reviews/google/nomulus/1106#-MZmsZDbCKHZ0rqN-TsJ:-MZmsZDc49EQYjNULuyO:b-ry8czt) ([raw file](https://github.com/google/nomulus/blob/7dec1301ddab69ed02e91b45b401d972f833381f/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L311)):*
> ```Java
>             DomainHistory.class,
>             ObjectifyService.allocateId());
>     historyBuilder.setId(domainHistoryKey.getId());
> ```

The ofy keys, they make me sad :-(
___
*[core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java, line 489 at r3](https://reviewable.io/reviews/google/nomulus/1106#-MZmlZiN8cbiT6El-ou7:-MZmlZiN8cbiT6El-ou8:b-2e3m8f) ([raw file](https://github.com/google/nomulus/blob/7dec1301ddab69ed02e91b45b401d972f833381f/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L489)):*
> ```Java
> 
>   private DomainHistory buildDomainHistory(
>       DomainBase newDomain,
> ```

Nit: is this always a new domain?
___
*[core/src/main/java/google/registry/flows/domain/DomainTransferCancelFlow.java, line 102 at r3](https://reviewable.io/reviews/google/nomulus/1106#-MZmq9-A6dl5P9j3Nwy4:-MZmq9-A6dl5P9j3Nwy5:b-uxo23b) ([raw file](https://github.com/google/nomulus/blob/7dec1301ddab69ed02e91b45b401d972f833381f/core/src/main/java/google/registry/flows/domain/DomainTransferCancelFlow.java#L102)):*
> ```Java
> 
>     Key<DomainHistory> domainHistoryKey =
>         Key.create(Key.create(existingDomain), DomainHistory.class, ObjectifyService.allocateId());
> ```

It looks like you're doing this key creation in a number of places.  Can we put in a static method in DomainHistory, maybe?


<!-- Sent from Reviewable.io -->

2021-05-03 20:19 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java, line 311 at r3](https://reviewable.io/reviews/google/nomulus/1106#-MZmsZDbCKHZ0rqN-TsJ:-MZnqsbl1T7ZzR-UJH17:b-c6q0y0) ([raw file](https://github.com/google/nomulus/blob/7dec1301ddab69ed02e91b45b401d972f833381f/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L311)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

The ofy keys, they make me sad :-(
</blockquote></details>

yeah :/ 

they're the best way here to preserve that parent relationship as long as it's needed in Datastore I think
___
*[core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java, line 489 at r3](https://reviewable.io/reviews/google/nomulus/1106#-MZmlZiN8cbiT6El-ou7:-MZnqs7I5D5l-YfsAgcf:bqyot8r) ([raw file](https://github.com/google/nomulus/blob/7dec1301ddab69ed02e91b45b401d972f833381f/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L489)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Nit: is this always a new domain?
</blockquote></details>

it is indeed
___
*[core/src/main/java/google/registry/flows/domain/DomainTransferCancelFlow.java, line 102 at r3](https://reviewable.io/reviews/google/nomulus/1106#-MZmq9-A6dl5P9j3Nwy4:-MZns4_E0jdann2623BN:bpy3c5t) ([raw file](https://github.com/google/nomulus/blob/7dec1301ddab69ed02e91b45b401d972f833381f/core/src/main/java/google/registry/flows/domain/DomainTransferCancelFlow.java#L102)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

It looks like you're doing this key creation in a number of places.  Can we put in a static method in DomainHistory, maybe?
</blockquote></details>

Yes, I think it makes the most sense in FlowUtils (we should be able to reuse it for the contact and host flows as well). Done, thanks. 


<!-- Sent from Reviewable.io -->

2021-05-03 21:54 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: 23 of 32 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 167 at r2](https://reviewable.io/reviews/google/nomulus/1106#-MZTJ0p6A34WuAmDTmw_:-MZoDE5b0Kn9-aKJtPA7:b1b5z85) ([raw file](https://github.com/google/nomulus/blob/6000b7044acf920c18b8376ce24cb0c0030f3011/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L167)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

The first instance that I see of the hash code being calculated in an arbitrarily-selected failing test is https://github.com/google/nomulus/blob/master/core/src/main/java/google/registry/model/domain/DomainContent.java#L800 

But where that's called is somewhat irrelevant, since it could theoretically be called from pretty much anywhere. 
</blockquote></details>

It seems safest to me to recalculate the hash code here rather than nulling it out.
___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 275 at r4](https://reviewable.io/reviews/google/nomulus/1106#-MZoDN7E2NXl9qBr8fJk:-MZoDN7E2NXl9qBr8fJl:b-k2pczf) ([raw file](https://github.com/google/nomulus/blob/d4ce83197ddb5a8b56f60022e2078ced4277b1c1/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L275)):*
> ```Java
>     }
>     serverApproveEntities = forceEmptyToNull(serverApproveEntitiesBuilder.build());
>     hashCode = null; // reset the hash code since we may have changed the entities
> ```

Here too.


<!-- Sent from Reviewable.io -->

2021-05-04 03:52 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: 23 of 32 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 167 at r2](https://reviewable.io/reviews/google/nomulus/1106#-MZTJ0p6A34WuAmDTmw_:-MZpV2QcDB91vTm0KzwT:b-xx4ho8) ([raw file](https://github.com/google/nomulus/blob/6000b7044acf920c18b8376ce24cb0c0030f3011/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L167)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It seems safest to me to recalculate the hash code here rather than nulling it out.
</blockquote></details>

Why is that? The field is protected and any time it needs to be accessed, it is recomputed lazily. Why do the extra computation here when it might not be necessary? 

Especially since the code that recalculates the hash code isn't particularly neat, it's `hashCode = Arrays.hashCode(getSignificantFields().values().toArray());`
___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 275 at r4](https://reviewable.io/reviews/google/nomulus/1106#-MZoDN7E2NXl9qBr8fJk:-MZpVO8p2oEiD7MKUSD9:byz4vxa) ([raw file](https://github.com/google/nomulus/blob/d4ce83197ddb5a8b56f60022e2078ced4277b1c1/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L275)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Here too.
</blockquote></details>

see other


<!-- Sent from Reviewable.io -->

2021-05-04 13:03 UTC, mindhog approved these changes
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @mindhog)



<!-- Sent from Reviewable.io -->

2021-05-04 13:56 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/transfer/DomainTransferData.java, line 167 at r2](https://reviewable.io/reviews/google/nomulus/1106#-MZTJ0p6A34WuAmDTmw_:-MZrdZ44A8YL0oHCSDLF:b-67vmtz) ([raw file](https://github.com/google/nomulus/blob/6000b7044acf920c18b8376ce24cb0c0030f3011/core/src/main/java/google/registry/model/transfer/DomainTransferData.java#L167)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Why is that? The field is protected and any time it needs to be accessed, it is recomputed lazily. Why do the extra computation here when it might not be necessary? 

Especially since the code that recalculates the hash code isn't particularly neat, it's `hashCode = Arrays.hashCode(getSignificantFields().values().toArray());`
</blockquote></details>

yeah, it's actually better that we not recalculate it here -- keep in mind that the hash value shouldn't be calculated prior to full initialization of the object otherwise it's likely just wrong.  This function is called as part of the initialization.

That's why I'm concerned about the early initialization.  This is very relevant to issues discussed in #1116.


<!-- Sent from Reviewable.io -->

2021-05-04 14:10 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1106)* status: all files reviewed, 2 unresolved discussions (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-05-04 23:09 UTC, merged