Always use Cloud SQL as primary for Reserved and Premium Lists
google/nomulus pull request #1113
Opened 2021-04-27 19:58 UTC by sarahcaseybot

2021-04-27 23:29 UTC, gbrodman reviewed
What's the purpose of removing this code path entirely now, rather than keeping it in the SQL-primary stage for a while longer while we continue the migration on other fronts? That is to say, is there any sort of rush? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1113#-:-MZKebdJ73Y9WWp8PZ_h:b-jdagx6)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-04-29 19:34 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1113)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumListDualDao.java, line 69 at r1](https://reviewable.io/reviews/google/nomulus/1113#-MZU5vwL2t6H1DEOL98g:-MZU5vwL2t6H1DEOL98h:bmg1f2n) ([raw file](https://github.com/google/nomulus/blob/d047c5c113973913e231052e0585ef9d5a97c5b6/core/src/main/java/google/registry/model/registry/label/PremiumListDualDao.java#L69)):*
> ```Java
>           Optional<Money> secondaryResult =
>               PremiumListDatastoreDao.getPremiumPrice(premiumListName, label, registry.getTldStr());
>           if (!primaryResult.equals(secondaryResult)) {
> ```

This can be written more simply as `checkState(primaryResult.equals(secondaryResult), "Unequal prices...", label, registry.getTldStr(), ...);`
___
*[core/src/main/java/google/registry/tools/UpdateReservedListCommand.java, line 52 at r1](https://reviewable.io/reviews/google/nomulus/1113#-MZU6TcW20laGGLGiNVD:-MZU6TcW20laGGLGiNVE:bdntfgq) ([raw file](https://github.com/google/nomulus/blob/2528ee05dd8f3e23acbeb5d488d420b71d97adbd/core/src/main/java/google/registry/tools/UpdateReservedListCommand.java#L52)):*
> ```Java
>             .asBuilder()
>             .setReservedListMapFromLines(allLines)
>             .setLastUpdateTime(now)
> ```

This is being removed because Cloud SQL updates it automatically?
___
*[core/src/test/java/google/registry/model/registry/label/PremiumListTest.java, line 72 at r1](https://reviewable.io/reviews/google/nomulus/1113#-MZU6qFK2p--32xdCMVW:-MZU6qFK2p--32xdCMVX:bfg66dp) ([raw file](https://github.com/google/nomulus/blob/2528ee05dd8f3e23acbeb5d488d420b71d97adbd/core/src/test/java/google/registry/model/registry/label/PremiumListTest.java#L72)):*
> ```Java
>   @Test
>   void testProbablePremiumLabels() {
>     PremiumList pl = PremiumListDualDao.getLatestRevision("tld").get();
> ```

Sad to see the Bloom filter go :(


<!-- Sent from Reviewable.io -->

2021-04-29 19:34 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1113#-:-MZU74Th3uosEX7MeVJ5:bnfp4nl)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-04-30 20:15 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1113)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumListDualDao.java, line 17 at r2](https://reviewable.io/reviews/google/nomulus/1113#-MZZOyQlDZeYAQlsq8ao:-MZZOyQm-xeI-7nBYPZn:btvs74o) ([raw file](https://github.com/google/nomulus/blob/ca1e00b6396a6d64625f37a5b581507778e1b52e/core/src/main/java/google/registry/model/registry/label/PremiumListDualDao.java#L17)):*
> ```Java
> package google.registry.model.registry.label;
> 
> import static avro.shaded.com.google.common.base.Preconditions.checkState;
> ```

This is the wrong import.  This is some kind of repackaged Guava, by whatever avro.shaded is.
___
*[core/src/test/java/google/registry/tools/server/ListPremiumListsActionTest.java, line 55 at r2](https://reviewable.io/reviews/google/nomulus/1113#-MZZPZVo9DNpBGs9M4Cb:-MZZPZVo9DNpBGs9M4Cc:b612gyu) ([raw file](https://github.com/google/nomulus/blob/ca1e00b6396a6d64625f37a5b581507778e1b52e/core/src/test/java/google/registry/tools/server/ListPremiumListsActionTest.java#L55)):*
> ```Java
>         "^name\\s+labelsToPrices\\s*$",
>         "^-+\\s+-+\\s*$",
>         "^how\\s+\\{richer=5000.00\\}$",
> ```

Looks to me like something has gone wrong.  This figure is Yen, and there aren't fractional Yen.


<!-- Sent from Reviewable.io -->

2021-05-03 21:07 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1113)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[core/src/test/java/google/registry/tools/server/ListPremiumListsActionTest.java, line 55 at r2](https://reviewable.io/reviews/google/nomulus/1113#-MZZPZVo9DNpBGs9M4Cb:-MZo2CGK9q_Hpkv2N_zs:blhl2ro) ([raw file](https://github.com/google/nomulus/blob/ca1e00b6396a6d64625f37a5b581507778e1b52e/core/src/test/java/google/registry/tools/server/ListPremiumListsActionTest.java#L55)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Hmm, I'm not sure how to fix this. I don't think this is an issue related to this change, but instead with how Yen are modeled in Cloud SQL. How did Datastore know that there could not be fractional Yen?
</blockquote></details>

It seems like some kind of bug that was introduced in the Cloud SQL code path (unrelated to this change).  I'll look into it.  We are no longer applying Joda `Money`'s concept of division to the `BigDecimal`s that make up the prices.


<!-- Sent from Reviewable.io -->

2021-05-05 21:24 UTC, merged