change premium list command to be based off of mutating command
google/nomulus pull request #1123
Opened 2021-05-03 17:29 UTC by rachelguan

- change the implementation of premium list command to be based on the mutating command in order to use the method stageEntityChange(old_entity, new_entity) or stageEntityChange(old_entity, new_entity, vkey) from mutating command; 
- no longer use client/servlet model + action files

2021-05-03 20:25 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @mindhog, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 53 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZnsZDCDajn32ROnqo9:-MZnsZDD2IP1X3jqFKKg:b-p6urb2) ([raw file](https://github.com/google/nomulus/blob/b3d22fe60d689e551aec73cdc4467dc19eeb0837/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L53)):*
> ```
> protected AppEngineConnection connection;
> ```
Is connection still used anywhere?
___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 66 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZntdlA09x0MyicF5kq:-MZntdlA09x0MyicF5kr:b8uoj82) ([raw file](https://github.com/google/nomulus/blob/b3d22fe60d689e551aec73cdc4467dc19eeb0837/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L66)):*
> ```
> stageEntityChange
> ```
Is this the correct place to call stateEntityChange(). Shouldn't be called in init(), so that prompt() will have the correct diff to display?


<!-- Sent from Reviewable.io -->

2021-05-03 21:45 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @mindhog, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZnwrEiEdDGbgHIUk70:-MZoB9sx3MMlfQ4Cs4CR:b-v3eai1) ([raw file](https://github.com/google/nomulus/blob/2528ee05dd8f3e23acbeb5d488d420b71d97adbd/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L44)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

> ```
> CommandWithRemoteApi
> ```
I believe you will still need CommandWithRemoteApi in order to be able to load the previous version from the database.
</blockquote></details>

`MutatingCommand` was modified to extend `CommandWithRemoteApi` recently.


<!-- Sent from Reviewable.io -->

2021-05-03 21:58 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @mindhog, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZnwrEiEdDGbgHIUk70:-MZoDhP81VN0da7mePY1:bi3770l) ([raw file](https://github.com/google/nomulus/blob/2528ee05dd8f3e23acbeb5d488d420b71d97adbd/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`MutatingCommand` was modified to extend `CommandWithRemoteApi` recently.
</blockquote></details>

so i guess I can remove CommandWithRemoteApi then? 
___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 53 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZnsZDCDajn32ROnqo9:-MZoDnLaElVFsIMtXKoz:bmuxhk5) ([raw file](https://github.com/google/nomulus/blob/b3d22fe60d689e551aec73cdc4467dc19eeb0837/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L53)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> protected AppEngineConnection connection;
> ```
Is connection still used anywhere?
</blockquote></details>

dont think so. supposed to remove that. 
___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 64 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZny-2eDAeTD9l8HIGj:-MZoDUXlDmed1bBeRacg:b-grsjke) ([raw file](https://github.com/google/nomulus/blob/b3d22fe60d689e551aec73cdc4467dc19eeb0837/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L64)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Where are you loading the value for existingPremiumList?
</blockquote></details>

init() of UpdatePremiumListCommand.java
___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 66 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZntdlA09x0MyicF5kq:-MZoEBUc9BG7i82fsOaw:b-c9w2sd) ([raw file](https://github.com/google/nomulus/blob/b3d22fe60d689e551aec73cdc4467dc19eeb0837/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L66)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> stageEntityChange
> ```
Is this the correct place to call stateEntityChange(). Shouldn't be called in init(), so that prompt() will have the correct diff to display?
</blockquote></details>

but this is execute() ? 


<!-- Sent from Reviewable.io -->

2021-05-04 17:03 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @mindhog, @rachelguan, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 66 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZntdlA09x0MyicF5kq:-MZsIfmx6HkOGkH0IFVm:b-nvhw7g) ([raw file](https://github.com/google/nomulus/blob/b3d22fe60d689e551aec73cdc4467dc19eeb0837/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L66)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

but this is execute() ? 
</blockquote></details>

If I read the code in ConfirmingCommand correctly, when you call stageEntityChange in execute instead of init, you will get two lines of output like below:

```
No entity change to apply.
Perform this command?
```

Is this actually the case when you run the command? 


<!-- Sent from Reviewable.io -->

2021-05-05 18:05 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @mindhog, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 53 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZnsZDCDajn32ROnqo9:-MZx0r2h2c7fFyfm635s:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8b260c373c642cd2d4957d9b4a4ca016693f25be/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L53)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

dont think so. supposed to remove that. 
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 66 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZntdlA09x0MyicF5kq:-MZxh2OjEPtCM0tPVNxf:b-96mg4p) ([raw file](https://github.com/google/nomulus/blob/8b260c373c642cd2d4957d9b4a4ca016693f25be/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L66)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

If I read the code in ConfirmingCommand correctly, when you call stageEntityChange in execute instead of init, you will get two lines of output like below:

```
No entity change to apply.
Perform this command?
```

Is this actually the case when you run the command? 
</blockquote></details>

ok i see. so i moved part of the code to init() of create, and update, now execute() only contains save(). 


<!-- Sent from Reviewable.io -->

2021-05-05 19:20 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: all files reviewed, 4 unresolved discussions (waiting on @mindhog, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/tools/CreatePremiumListCommand.java, line 52 at r2](https://reviewable.io/reviews/google/nomulus/1123#-MZxthBSAAmoJC1ZpUus:-MZxyAny7_94U4JitoXB:bicpnwk) ([raw file](https://github.com/google/nomulus/blob/d85f3a332e25195651cfb5c8843700b4c7912dcc/core/src/main/java/google/registry/tools/CreatePremiumListCommand.java#L52)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Doesn't StageEntityChange need to be called here?
</blockquote></details>

i thought that was only required if there's an update? 
___
*[core/src/test/java/google/registry/tools/CreateOrUpdatePremiumListCommandTestCase.java, line 49 at r2](https://reviewable.io/reviews/google/nomulus/1123#-MZxvj6g7tO5VcZi7i_i:-MZxxuYD5a5gdTFRas1M:b2hffxy) ([raw file](https://github.com/google/nomulus/blob/d85f3a332e25195651cfb5c8843700b4c7912dcc/core/src/test/java/google/registry/tools/CreateOrUpdatePremiumListCommandTestCase.java#L49)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Calling ReservedListTestCase in the PremiumList tests?
</blockquote></details>

i accidentally pushed the very initial version of it by using reserved list tests as reference. will remove that asap, thanks!


<!-- Sent from Reviewable.io -->

2021-05-07 16:50 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @mindhog, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/1123#-MZnwrEiEdDGbgHIUk70:-M_6j2s4CLUB42zGwE-0:btqqu5l) ([raw file](https://github.com/google/nomulus/blob/d285edef3d75ee71ec70a1344ce38f2923ec1034/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L44)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

so i guess I can remove CommandWithRemoteApi then? 
</blockquote></details>

Correct.


<!-- Sent from Reviewable.io -->

2021-05-12 05:38 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @mindhog, @rachelguan, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 31 at r5](https://reviewable.io/reviews/google/nomulus/1123#-M_RZ21WEPXoqGHO7ZjQ:-M_U3eB32Zt3Pld6mVN4:b-896fix) ([raw file](https://github.com/google/nomulus/blob/de31733a3900a5cb1970f585590326a9303157b9/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L31)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> static final FluentLogger logger
> ```
Logger is usually made private. 
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/CreatePremiumListCommand.java, line 42 at r5](https://reviewable.io/reviews/google/nomulus/1123#-M_S1irz0ZCMxY9kfoEa:-M_TfpO6ArHD-6bh--te:b-xrw6ah) ([raw file](https://github.com/google/nomulus/blob/de31733a3900a5cb1970f585590326a9303157b9/core/src/main/java/google/registry/tools/CreatePremiumListCommand.java#L42)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Are you going to delete the CreatePremiumListAction file now that it is no longer being used by this command?
</blockquote></details>

I talked to Weimin about this and he suggested to delete the related files later, after testing this in at least sandbox. It's part of the plan but not this PR. 
___
*[core/src/main/java/google/registry/tools/CreatePremiumListCommand.java, line 58 at r5](https://reviewable.io/reviews/google/nomulus/1123#-M_S2ycW00a_2wHbcc9Y:-M_TfebH8n0JVpmemDKK:b5zt0q8) ([raw file](https://github.com/google/nomulus/blob/de31733a3900a5cb1970f585590326a9303157b9/core/src/main/java/google/registry/tools/CreatePremiumListCommand.java#L58)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I am going to be removing PremiumList from the Datastore schema soon. Will this still work once PremiumList is removed from Datastore?
</blockquote></details>

what files will you be removing? 
___
*[core/src/main/java/google/registry/tools/UpdatePremiumListCommand.java, line 44 at r5](https://reviewable.io/reviews/google/nomulus/1123#-M_S3FuD59QMT_J6pZlO:-M_Tg534EzwRYOODE6vA:b-j9sd92) ([raw file](https://github.com/google/nomulus/blob/de31733a3900a5cb1970f585590326a9303157b9/core/src/main/java/google/registry/tools/UpdatePremiumListCommand.java#L44)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Should that class be deleted?
</blockquote></details>

ideally yes. planning on doing this later. see response above.


<!-- Sent from Reviewable.io -->

2021-05-13 18:18 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: 2 of 7 files reviewed, 7 unresolved discussions (waiting on @mindhog, @rachelguan, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 32 at r6](https://reviewable.io/reviews/google/nomulus/1123#-M_avsZE1DK2Ea9Ppkwp:-M_avsZE1DK2Ea9Ppkwq:b-x4wsib) ([raw file](https://github.com/google/nomulus/blob/be9abd678b006664511c40d5ec84aa85f6e9215d/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L32)):*
> ```
> inputLineCount
> ```
I don't see the point of this variable. It is only used once in a log message. Just using allLines.size() is clear enough.
___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 33 at r6](https://reviewable.io/reviews/google/nomulus/1123#-M_awQEE11u09fGbjRvw:-M_awQEE11u09fGbjRvx:b34sq2a) ([raw file](https://github.com/google/nomulus/blob/be9abd678b006664511c40d5ec84aa85f6e9215d/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L33)):*
> ```
> allLines
> ```
'inputLines or inputFileLines would be more clear.

It is initialized in both child classes. Why not move the initialization here?


<!-- Sent from Reviewable.io -->

2021-05-13 23:33 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @mindhog, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 32 at r6](https://reviewable.io/reviews/google/nomulus/1123#-M_avsZE1DK2Ea9Ppkwp:-M_c1kXw16sR_HyoMbqS:b65okq3) ([raw file](https://github.com/google/nomulus/blob/be9abd678b006664511c40d5ec84aa85f6e9215d/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L32)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> inputLineCount
> ```
I don't see the point of this variable. It is only used once in a log message. Just using allLines.size() is clear enough.
</blockquote></details>

yep. removed that and now using .size(). 
___
*[core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java, line 33 at r6](https://reviewable.io/reviews/google/nomulus/1123#-M_awQEE11u09fGbjRvw:-M_c1pjG8sTmR-UqHxQD:btxhkmz) ([raw file](https://github.com/google/nomulus/blob/be9abd678b006664511c40d5ec84aa85f6e9215d/core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java#L33)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> allLines
> ```
'inputLines or inputFileLines would be more clear.

It is initialized in both child classes. Why not move the initialization here?
</blockquote></details>

changed the name to inputData, so it has the same convention as the other parameter, inputFile. 

Since inputData is initialized in init() and it relies on inputFile, which is assigned in init() as well. Either there's an init() in CreateOrUpdatePremiumListCommand.java with two cases, or an init() in each of the command init(). 
___
*[core/src/main/java/google/registry/tools/CreatePremiumListCommand.java, line 58 at r5](https://reviewable.io/reviews/google/nomulus/1123#-M_S2ycW00a_2wHbcc9Y:-M_c3dvTARutVh_Aj55i:bclhdof) ([raw file](https://github.com/google/nomulus/blob/de31733a3900a5cb1970f585590326a9303157b9/core/src/main/java/google/registry/tools/CreatePremiumListCommand.java#L58)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I will be removing PremiumList from the Datastore schema. Hopefully this won't cause any issues with this class, but if it does, I'll handle it then.
</blockquote></details>

sounds good. please let me know if there's an issue with that and i will take a look as well. 
___
*[core/src/main/java/google/registry/tools/UpdatePremiumListCommand.java, line 72 at r5](https://reviewable.io/reviews/google/nomulus/1123#-M_RflyJ9q47WVfpQFry:-M_c3uyvBDS5Yh_7yv9P:bsnz829) ([raw file](https://github.com/google/nomulus/blob/de31733a3900a5cb1970f585590326a9303157b9/core/src/main/java/google/registry/tools/UpdatePremiumListCommand.java#L72)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> getExistingPremiumListEntry
> ```
This is very similar to the helper method in CreateOrUpdatePremiumListCommandTestCase.java. In fact, the only difference is whether the premiumList instance is passed as param or loaded inside the method. Try to create a version that suits both use case, and put it here and make it package-private and static.
</blockquote></details>

removed that from test class and modified the helper method in UpdatePremiumListCommand.java. please take a look. 


<!-- Sent from Reviewable.io -->

2021-05-14 01:15 UTC, weiminyu approved these changes
> Reviewed 1 of 6 files at r4, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-05-14 12:40 UTC, merged