Always use Cloud SQL as primary for ClaimsList
google/nomulus pull request #1127
Opened 2021-05-04 20:04 UTC by sarahcaseybot

2021-05-06 18:43 UTC, gbrodman requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1127)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/tmch/ClaimsListDualDatabaseDao.java, line 35 at r1](https://reviewable.io/reviews/google/nomulus/1127#-M_1z3FEE-47_b983UcB:-M_1z3FEE-47_b983UcC:b-k2yxsf) ([raw file](https://github.com/google/nomulus/blob/145156ebf7dc1ebd54da1b32c1bdf573d8c878b6/core/src/main/java/google/registry/model/tmch/ClaimsListDualDatabaseDao.java#L35)):*
> ```Java
>  * success or failure, against Datastore. If Datastore fails, an error is logged (but not thrown).
>  *
>  * <p>For read actions, we will log if the primary and secondary databases have different values (or
> ```

supernit: can probably remove the generic "primary" and "secondary" terms as we do elsewhere.
___
*[core/src/test/java/google/registry/model/tmch/ClaimsListDualDatabaseDaoTest.java, line 130 at r1](https://reviewable.io/reviews/google/nomulus/1127#-M_1zTB75bKXPB68CXoA:-M_1zTB75bKXPB68CXoB:b-78q6cw) ([raw file](https://github.com/google/nomulus/blob/d285edef3d75ee71ec70a1344ce38f2923ec1034/core/src/test/java/google/registry/model/tmch/ClaimsListDualDatabaseDaoTest.java#L130)):*
> ```Java
> 
>   @Test
>   void testGetList_missingOfy_notInTest() {
> ```

I think we probably want to keep this test around until we entirely remove the Datastore code, right? 


<!-- Sent from Reviewable.io -->

2021-05-06 18:43 UTC, gbrodman reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1127)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-05-06 20:44 UTC, gbrodman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1127#-:-M_2QGnf4HqbkC_Px-oI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-05-07 17:26 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1127#-:-M_6rRbz50NuPsq3uHy-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-05-10 20:47 UTC, merged