Retry spec11pipeline test
google/nomulus pull request #1133
Opened 2021-05-05 13:28 UTC by jianglai

2021-05-06 18:09 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1133)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[core/src/test/java/google/registry/testing/DatastoreEntityExtension.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1133#-M_1rZ4dBZXelpEIsMsX:-M_1rZ4dBZXelpEIsMsY:bq9cs3e) ([raw file](https://github.com/google/nomulus/blob/b2287a81033de4a986e82fbeaa54ef490c482034/core/src/test/java/google/registry/testing/DatastoreEntityExtension.java#L45)):*
> ```Java
>     // Clear this property so that when default Guava ThreadFactory is created it will not think
>     // that it is in App Engine and return an unusable ThreadFactory.
>     System.clearProperty("com.google.appengine.runtime.environment");
> ```

If this line fixes the problem, do we need all the changes in the other classes?


<!-- Sent from Reviewable.io -->

2021-05-06 19:33 UTC, jianglai commented
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1133)_ status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)
> 
> _[core/src/test/java/google/registry/testing/DatastoreEntityExtension.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1133#-M_1rZ4dBZXelpEIsMsX:-M_1rZ4dBZXelpEIsMsY:bq9cs3e) ([raw file](https://github.com/google/nomulus/blob/b2287a81033de4a986e82fbeaa54ef490c482034/core/src/test/java/google/registry/testing/DatastoreEntityExtension.java#L45)):_
> 
> > ```java
> >     // Clear this property so that when default Guava ThreadFactory is created it will not think
> >     // that it is in App Engine and return an unusable ThreadFactory.
> >     System.clearProperty("com.google.appengine.runtime.environment");
> > ```
> 
> If this line fixes the problem, do we need all the changes in the other classes?

I think it is still a good idea to put the assertion in any calls that use the test pipeline because it is incompatible with app engine thread factory, and we'd want to know about it if there are other settings that result in the same problem.

2021-05-07 16:52 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1133#-:-M_6jgSt9hKp9uFjCm3W:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2021-05-07 17:41 UTC, weiminyu approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2021-05-07 19:01 UTC, merged