Stop writing PremiumList to Datastore
google/nomulus pull request #1160
Opened 2021-05-13 17:20 UTC by sarahcaseybot

2021-05-13 18:33 UTC, gbrodman requested changes
> Reviewed 27 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1160)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java, line 226 at r1](https://reviewable.io/reviews/google/nomulus/1160#-M_az5Pu33b9IbM-66sP:-M_az5Pu33b9IbM-66sQ:bzaat0y) ([raw file](https://github.com/google/nomulus/blob/1198efdb37c68aaad56e6ce30699f80b455ba64a/core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java#L226)):*
> ```Java
>                     .findFirst());
>   }
> ```

thoughts on renaming `PremiumListSqlDao` to just `PremiumListDao`? We likely don't need to specify SQL any more. 
___
*[core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java, line 240 at r1](https://reviewable.io/reviews/google/nomulus/1160#-M_az9KaBoAnX72r7f_V:-M_az9KaBoAnX72r7f_W:b-reyhq9) ([raw file](https://github.com/google/nomulus/blob/1198efdb37c68aaad56e6ce30699f80b455ba64a/core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java#L240)):*
> ```Java
>                         String.format("No premium list with name %s.", premiumListName)));
>     CurrencyUnit currencyUnit = premiumList.getCurrency();
>     return Streams.stream(loadPremiumListEntriesUncached(premiumList))
> ```

nit: we can probably rename `loadPremiumListEntriesUncached` to just `loadPremiumEntries`
___
*[core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java, line 243 at r1](https://reviewable.io/reviews/google/nomulus/1160#-M_azaiEBYQr3o6BjGob:-M_azaiEBYQr3o6BjGoc:b-pnp9xi) ([raw file](https://github.com/google/nomulus/blob/1198efdb37c68aaad56e6ce30699f80b455ba64a/core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java#L243)):*
> ```Java
>         .map(
>             premiumEntry ->
>                 new PremiumListEntry.Builder()
> ```

We probably can remove the `PremiumListEntry` class entirely and deal only with `PremiumEntry` objects, since IIRC, `PremiumListEntry` is only for Datastore 
___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 392 at r1](https://reviewable.io/reviews/google/nomulus/1160#-M_b-0BnBWuPKx1uNyg-:-M_b-0BnBWuPKx1uNyg0:b-wncgiy) ([raw file](https://github.com/google/nomulus/blob/1198efdb37c68aaad56e6ce30699f80b455ba64a/core/src/test/java/google/registry/testing/DatabaseHelper.java#L392)):*
> ```Java
>                             Map.Entry::getKey, entry -> entry.getValue().getValue().getAmount())))
>             .build();
>     // Since we used to persist a PremiumList to Datastore here, it is necessary to allocate an ID
> ```

What breaks in the tests? If it's just strings, we should change those rather than have a phantom call here 


<!-- Sent from Reviewable.io -->

2021-05-14 15:42 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1160)* status: 7 of 29 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 392 at r2](https://reviewable.io/reviews/google/nomulus/1160#-M_fXP0mBaRsQXHuBiJa:-M_fXP0mBaRsQXHuBiJb:b8tab2n) ([raw file](https://github.com/google/nomulus/blob/7f5d360e268e7c259867667e31554175e864d81f/core/src/test/java/google/registry/testing/DatabaseHelper.java#L392)):*
> ```Java
>                             Map.Entry::getKey, entry -> entry.getValue().getValue().getAmount())))
>             .build();
>     // Since we used to persist a PremiumList to Datastore here, it is necessary to allocate an ID
> ```

This comment doesn't really explain the why.  It needs to explain, in tests, IDs are allocated in a strictly increasing sequence, and that we made a change to remove one of said allocations, and it's easier to just pad it out than have to renumber everything everywhere.


<!-- Sent from Reviewable.io -->

2021-05-14 15:43 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1160)* status: 7 of 29 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @sarahcaseybot)

___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 392 at r1](https://reviewable.io/reviews/google/nomulus/1160#-M_b-0BnBWuPKx1uNyg-:-M_fXTfpEO2HD04HIAMV:b-nwd4a3) ([raw file](https://github.com/google/nomulus/blob/1198efdb37c68aaad56e6ce30699f80b455ba64a/core/src/test/java/google/registry/testing/DatabaseHelper.java#L392)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

It causes failures in over 350 tests that would each need to be manually fixed
</blockquote></details>

aight, fair enough then 
___
*[core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java, line 243 at r1](https://reviewable.io/reviews/google/nomulus/1160#-M_azaiEBYQr3o6BjGob:-M_fXbdL9XRlY5ALzLgP:bb7ohn6) ([raw file](https://github.com/google/nomulus/blob/1198efdb37c68aaad56e6ce30699f80b455ba64a/core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java#L243)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I will do this in a follow up PR
</blockquote></details>

sgtm


<!-- Sent from Reviewable.io -->

2021-05-14 15:43 UTC, gbrodman reviewed
> Reviewed 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1160)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-05-14 19:06 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1160)* status: 28 of 34 files reviewed, 1 unresolved discussion (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-05-14 19:26 UTC, gbrodman approved these changes
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-05-14 20:13 UTC, merged