Fix NullPointerException in StaticPremiumPricingEngine
google/nomulus pull request #1164
Opened 2021-05-17 17:06 UTC by sarahcaseybot

2021-05-17 17:17 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1164)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/pricing/StaticPremiumListPricingEngine.java, line 42 at r1](https://reviewable.io/reviews/google/nomulus/1164#-M_vJpiD4gjpOzF8KXDd:-M_vJpiED8L6jbbpUfAZ:b-okqs6y) ([raw file](https://github.com/google/nomulus/blob/832b2823acaf9a7cf3a023331a0acff4ff4221aa/core/src/main/java/google/registry/model/pricing/StaticPremiumListPricingEngine.java#L42)):*
> ```Java
>     Registry registry = Registry.get(checkNotNull(tld, "tld"));
>     Optional<Money> premiumPrice = Optional.empty();
>     if (registry.getPremiumList() != null) {
> ```

Make `Registry.getPremiumList()` return `Optional<PremiumList>` while you're at it.  If that had been in place previously it would have prevented this entire bug.

Also, very basic required procedure when fixing a bug identified in a deployed environment: Write a test first, verify that it fails, then fix it (i.e. this code) and verify that the test succeeds.  It sounds like we don't have enough testing of TLDs that aren't configured with premium lists, which is a problem.


<!-- Sent from Reviewable.io -->

2021-05-17 18:35 UTC, gbrodman requested changes
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1164)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/pricing/StaticPremiumListPricingEngine.java, line 43 at r2](https://reviewable.io/reviews/google/nomulus/1164#-M_v_nZL6FT6HLrAQDl2:-M_v_nZL6FT6HLrAQDl3:b-8xdsxz) ([raw file](https://github.com/google/nomulus/blob/4cad1b5ebe73244945f34fb36af40ee9e11665bd/core/src/main/java/google/registry/model/pricing/StaticPremiumListPricingEngine.java#L43)):*
> ```Java
>     Optional<Money> premiumPrice = Optional.empty();
>     if (registry.getPremiumList().isPresent()) {
>       premiumPrice =
> ```

can one-line this all with 

`Optional<Money> premiumPrice = registry.getPremiumList().map(list -> PremiumListDao.getPremiumPrice(list.getName(), label))`
___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 266 at r2](https://reviewable.io/reviews/google/nomulus/1164#-M_vaHGb0-MtEJKwFiv3:-M_vaHGb0-MtEJKwFiv4:banf9vd) ([raw file](https://github.com/google/nomulus/blob/4cad1b5ebe73244945f34fb36af40ee9e11665bd/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L266)):*
> ```Java
>   @Override
>   public boolean refersToKey(Registry registry, Key<? extends BaseDomainLabelList<?, ?>> key) {
>     return Objects.equals(registry.getPremiumList().get(), key);
> ```

I'm not sure this is optimal -- if there is no list on the registry, I believe this should return `false` right? 
___
*[core/src/test/java/google/registry/tools/UpdateTldCommandTest.java, line 855 at r2](https://reviewable.io/reviews/google/nomulus/1164#-M_vaXFq42nN_ZGL5h4R:-M_vaXFq42nN_ZGL5h4S:bjej9xj) ([raw file](https://github.com/google/nomulus/blob/4cad1b5ebe73244945f34fb36af40ee9e11665bd/core/src/test/java/google/registry/tools/UpdateTldCommandTest.java#L855)):*
> ```Java
>     runCommandForced("--add_reserved_lists=xn--q9jyb4c_r1,xn--q9jyb4c_r2", "xn--q9jyb4c");
>     Optional<Key<PremiumList>> premiumListKey = Registry.get("xn--q9jyb4c").getPremiumList();
>     assertThat(premiumListKey).isPresent();
> ```

nitty, but we could probably remove this line (if it fails here, it'll fail on the next line)

not a big deal either way


<!-- Sent from Reviewable.io -->

2021-05-17 19:01 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1164)* status: all files reviewed, 4 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 266 at r2](https://reviewable.io/reviews/google/nomulus/1164#-M_vaHGb0-MtEJKwFiv3:-M_vf9C6D7B1t56vqTYz:b-gmkxq0) ([raw file](https://github.com/google/nomulus/blob/4cad1b5ebe73244945f34fb36af40ee9e11665bd/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L266)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I'm not sure this is optimal -- if there is no list on the registry, I believe this should return `false` right? 
</blockquote></details>

It's not that this isn't optimal, I think it's wrong.  It needs to be `orElse(null)`; as currently written it will NPE in some situations.
___
*[core/src/test/java/google/registry/model/OteAccountBuilderTest.java, line 73 at r2](https://reviewable.io/reviews/google/nomulus/1164#-M_vfaKH1bqP9pVwcrSx:-M_vfaKH1bqP9pVwcrSy:b-cvq2vi) ([raw file](https://github.com/google/nomulus/blob/4cad1b5ebe73244945f34fb36af40ee9e11665bd/core/src/test/java/google/registry/model/OteAccountBuilderTest.java#L73)):*
> ```Java
>     Registry registry = Registry.get(tld);
>     assertThat(registry).isNotNull();
>     assertThat(registry.getPremiumList().get().getName()).isEqualTo("default_sandbox_list");
> ```

Needs another assertion above this verifying that the list is present; as written this will NPE without a useful error message if the list isn't configured as expected.  Normally I'd suggest using the `hasValue()` import from `Truth8`, but that would only work if you were asserting about the returned value of `getPremiumList()` itself, not an additional field hanging off of it.
___
*[core/src/test/java/google/registry/model/registry/RegistryTest.java, line 253 at r2](https://reviewable.io/reviews/google/nomulus/1164#-M_vg8f04KJAbR5jmiaz:-M_vg8f04KJAbR5jmib-:bcqdiy4) ([raw file](https://github.com/google/nomulus/blob/4cad1b5ebe73244945f34fb36af40ee9e11665bd/core/src/test/java/google/registry/model/registry/RegistryTest.java#L253)):*
> ```Java
>     Registry registry = Registry.get("tld").asBuilder().setPremiumList(pl2).build();
>     Key<PremiumList> plKey = registry.getPremiumList().get();
>     assertThat(plKey).isNotNull();
> ```

This no longer works; the code will NPE on the previous line.  You need to either use `orElse(null)` (not as good) or make a separate assertion along the lines of:

```
Optional<Key<PremiumList>> plKey = registry.getPremiumList();
assertThat(plKey).isPresent();
PremiumList stored = PremiumListDao.getLatestRevision(plKey.get().getName()).get();

```

More generally, there's a lot of mistakes in this PR now where an `Optional` value isn't correctly being handled.  You can't just call `.get()` on it and then work with it as if it had a value without handling the case where it doesn't have a value; that's just going to throw NPEs all day long.


<!-- Sent from Reviewable.io -->

2021-05-17 19:06 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1164)* status: all files reviewed, 4 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/test/java/google/registry/tools/UpdateTldCommandTest.java, line 855 at r2](https://reviewable.io/reviews/google/nomulus/1164#-M_vaXFq42nN_ZGL5h4R:-M_vhwUJDxM6a51XanBu:b7bj2z3) ([raw file](https://github.com/google/nomulus/blob/4cad1b5ebe73244945f34fb36af40ee9e11665bd/core/src/test/java/google/registry/tools/UpdateTldCommandTest.java#L855)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nitty, but we could probably remove this line (if it fails here, it'll fail on the next line)

not a big deal either way
</blockquote></details>

Disagree, it fails with a more useful Truth-generated error message when you explicitly assert that it has a value than with the generic non-Truth NPE you'd get below.


<!-- Sent from Reviewable.io -->

2021-05-17 19:07 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1164)* status: all files reviewed, 4 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 266 at r2](https://reviewable.io/reviews/google/nomulus/1164#-M_vaHGb0-MtEJKwFiv3:-M_viMgK3C3eDtc7UFP_:bovvlgl) ([raw file](https://github.com/google/nomulus/blob/4cad1b5ebe73244945f34fb36af40ee9e11665bd/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L266)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It's not that this isn't optimal, I think it's wrong.  It needs to be `orElse(null)`; as currently written it will NPE in some situations.
</blockquote></details>

(`Objects.equals()` expects both arguments are nullable and handles that correctly, but if you NPE before you even call `Objects.equals()` then you just have an outright failure.)


<!-- Sent from Reviewable.io -->

2021-05-17 21:50 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1164)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-05-18 14:48 UTC, gbrodman approved these changes
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/pricing/StaticPremiumListPricingEngine.java, line 43 at r2](https://reviewable.io/reviews/google/nomulus/1164#-M_v_nZL6FT6HLrAQDl2:-M_zwVOA4pSG6V6aKOUa:b3dd838) ([raw file](https://github.com/google/nomulus/blob/4cad1b5ebe73244945f34fb36af40ee9e11665bd/core/src/main/java/google/registry/model/pricing/StaticPremiumListPricingEngine.java#L43)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I tried this, but it is not working cause of type inferences.
</blockquote></details>

hm, this would warrant more investigation -- it should work, but in the interests of merging lgtm 


<!-- Sent from Reviewable.io -->

2021-05-18 14:55 UTC, merged