Add an object to store database migration stages
google/nomulus pull request #1170
Opened 2021-05-20 15:21 UTC by gbrodman

go/registry-3.0-stage-management for more details

This basically boils down to storing an enum in the database so that we
can tell what stage of the migration we're in.

We use a cross-TLD parent so that we can have strong transactional
consistency on retrieval.

2021-05-20 18:08 UTC, mindhog requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1170)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java, line 70 at r1](https://reviewable.io/reviews/google/nomulus/1170#-Ma9tTepAl_07Dq3_u0F:-Ma9tTepAl_07Dq3_u0G:b-kblscd) ([raw file](https://github.com/google/nomulus/blob/7b1ea9f45ce4babcb7746ba96b854571ca6083f2/core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java#L70)):*
> ```Java
>   // The valid state transitions. Basically, at state N, state N+1 is valid as well as all previous
>   // states, with one exception: when in SQL_ONLY, we can only move back to SQL_PRIMARY because we
>   // must assume that some writes that occurred in SQL_ONLY will not have propagated to Datastore.
> ```

As I think about it, we have a similar problem going from SQL_PRIMARY to any of the datastore primary states: there could be transactions still in the queue that would need to be applied before the datastore can be safely mutated.

You may want to introduce another state: DATASTORE_PRIMARY_READ_ONLY_ROLLBACK where we would block on a transition to DATASTORE_PRIMARY or DATASTORE_ONLY until after all transactions have been propagated.  Alternately, we can just use DATASTORE_PRIMARY_READ_ONLY for this and just make it part of the rollback procedure for the operator to verify this manually.  There's a case to be made for not making the operational constraints too strong in a case like this where human judgement is the primary driver.
___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java, line 105 at r1](https://reviewable.io/reviews/google/nomulus/1170#-Ma9wMXq3nrnB32Q9qbM:-Ma9wMXq3nrnB32Q9qbN:btnge0r) ([raw file](https://github.com/google/nomulus/blob/7b1ea9f45ce4babcb7746ba96b854571ca6083f2/core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java#L105)):*
> ```Java
>         currentState,
>         newState);
>     DatabaseMigrationStateWrapper stage = new DatabaseMigrationStateWrapper();
> ```

Remember that DatabaseMigrationStateWrapper is supposed to be an ImmutableObject: much better to pass the migration state into the constructor and make it final.


<!-- Sent from Reviewable.io -->

2021-05-20 19:03 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1170)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java, line 70 at r1](https://reviewable.io/reviews/google/nomulus/1170#-Ma9tTepAl_07Dq3_u0F:-MaA75Gz7mTfAO733Gpf:bwmmghw) ([raw file](https://github.com/google/nomulus/blob/7b1ea9f45ce4babcb7746ba96b854571ca6083f2/core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java#L70)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

As I think about it, we have a similar problem going from SQL_PRIMARY to any of the datastore primary states: there could be transactions still in the queue that would need to be applied before the datastore can be safely mutated.

You may want to introduce another state: DATASTORE_PRIMARY_READ_ONLY_ROLLBACK where we would block on a transition to DATASTORE_PRIMARY or DATASTORE_ONLY until after all transactions have been propagated.  Alternately, we can just use DATASTORE_PRIMARY_READ_ONLY for this and just make it part of the rollback procedure for the operator to verify this manually.  There's a case to be made for not making the operational constraints too strong in a case like this where human judgement is the primary driver.
</blockquote></details>

Yeah, good point. I think the easiest thing to do is just to limit it to one step back, i.e. going to the read-only state. 
___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java, line 105 at r1](https://reviewable.io/reviews/google/nomulus/1170#-Ma9wMXq3nrnB32Q9qbM:-MaA79rj3oQeJrcB556o:bf8c0yy) ([raw file](https://github.com/google/nomulus/blob/7b1ea9f45ce4babcb7746ba96b854571ca6083f2/core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java#L105)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Remember that DatabaseMigrationStateWrapper is supposed to be an ImmutableObject: much better to pass the migration state into the constructor and make it final.
</blockquote></details>

Unfortunately we cannot do that -- Objectify / Datastore require that there exists a no-arg public constructor so while this is an ImmutableObject, we must fill it out after-the-fact like Objectify does. 

See similar patterns in ServerSecret and TmchCrl 


<!-- Sent from Reviewable.io -->

2021-05-21 11:43 UTC, mindhog requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1170)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java, line 105 at r1](https://reviewable.io/reviews/google/nomulus/1170#-Ma9wMXq3nrnB32Q9qbM:-MaDhhFo2tgebbl_Megg:bx81r10) ([raw file](https://github.com/google/nomulus/blob/7b1ea9f45ce4babcb7746ba96b854571ca6083f2/core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java#L105)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Unfortunately we cannot do that -- Objectify / Datastore require that there exists a no-arg public constructor so while this is an ImmutableObject, we must fill it out after-the-fact like Objectify does. 

See similar patterns in ServerSecret and TmchCrl 
</blockquote></details>

Why not just add an additional constructor?


<!-- Sent from Reviewable.io -->

2021-05-21 14:58 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1170)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java, line 105 at r1](https://reviewable.io/reviews/google/nomulus/1170#-Ma9wMXq3nrnB32Q9qbM:-MaEQkSg7ODkaicTP2zR:b-gxztt3) ([raw file](https://github.com/google/nomulus/blob/7b1ea9f45ce4babcb7746ba96b854571ca6083f2/core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java#L105)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Why not just add an additional constructor?
</blockquote></details>

Fair enough 


<!-- Sent from Reviewable.io -->

2021-05-21 15:48 UTC, mindhog approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-05-21 15:49 UTC, merged