Add Cloud SQL read to Spec11Pipeline
google/nomulus pull request #1173
Opened 2021-05-21 18:23 UTC by sarahcaseybot

2021-05-26 02:30 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java, line 103 at r1](https://reviewable.io/reviews/google/nomulus/1173#-Ma_T5EXEFZp-CnFQoPt:-Ma_T5EXEFZp-CnFQoPu:bkavny0) ([raw file](https://github.com/google/nomulus/blob/94305ec93e3409ad29069a5ef4a625e3e4f944ba/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L103)):*
> ```
> tm().isOfy()
> ```
It might be better to make this a property in this pipeline's corresponding option class and have the Action that launches this pipeline set the property. This way we won't have to initialize Ofy in the pipeline, or tinker with the TransactionManagerFactory's static initialization.
___
*[core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java, line 148 at r1](https://reviewable.io/reviews/google/nomulus/1173#-MaaUhNiENuUPHdB8OQN:-MaaUhNiENuUPHdB8OQO:b-d6ltd4) ([raw file](https://github.com/google/nomulus/blob/94305ec93e3409ad29069a5ef4a625e3e4f944ba/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L148)):*
> ```
> emailAddress
> ```
Can email address be null in the new data model? If yes, it needs to be replaced with a "" according to the BQ query in subdomain.sql


<!-- Sent from Reviewable.io -->

2021-05-26 12:39 UTC, mindhog approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-05-27 19:16 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot and @weiminyu)

___
*[core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java, line 103 at r1](https://reviewable.io/reviews/google/nomulus/1173#-Ma_T5EXEFZp-CnFQoPt:-MajFDCs8MuTgL_8EXI5:b-fm0vza) ([raw file](https://github.com/google/nomulus/blob/94305ec93e3409ad29069a5ef4a625e3e4f944ba/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L103)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> tm().isOfy()
> ```
It might be better to make this a property in this pipeline's corresponding option class and have the Action that launches this pipeline set the property. This way we won't have to initialize Ofy in the pipeline, or tinker with the TransactionManagerFactory's static initialization.
</blockquote></details>

And then in the corresponding action class, it'll still be calling `tm().isOfy()` to determine what to set it to, right?


<!-- Sent from Reviewable.io -->

2021-06-01 14:03 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java, line 103 at r1](https://reviewable.io/reviews/google/nomulus/1173#-Ma_T5EXEFZp-CnFQoPt:-Mb6saD-2e9rQviwUOU4:bb77ufg) ([raw file](https://github.com/google/nomulus/blob/94305ec93e3409ad29069a5ef4a625e3e4f944ba/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L103)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

And then in the corresponding action class, it'll still be calling `tm().isOfy()` to determine what to set it to, right?
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2021-06-03 02:42 UTC, jianglai requested changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: all files reviewed, 8 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java, line 104 at r2](https://reviewable.io/reviews/google/nomulus/1173#-MbEg-mb5Cw8tX8FZESM:-MbEg-mb5Cw8tX8FZESN:bc2pmxa) ([raw file](https://github.com/google/nomulus/blob/269c29f6fd85d29c725d2250979f246f2df1026f/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L104)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
>           pipeline.apply(
>               "Read active domains from BigQuery",
>               BigQueryIO.read(Subdomain::parseFromRecord)
>                   .fromQuery(
>                       SqlTemplate.create(getQueryFromFile(Spec11Pipeline.class, "subdomains.sql"))
>                           .put("PROJECT_ID", options.getProject())
>                           .put("DATASTORE_EXPORT_DATASET", "latest_datastore_export")
>                           .put("REGISTRAR_TABLE", "Registrar")
>                           .put("DOMAIN_BASE_TABLE", "DomainBase")
>                           .build())
>                   .withCoder(SerializableCoder.of(Subdomain.class))
>                   .usingStandardSql()
>                   .withoutValidation()
>                   .withTemplateCompatibility());
> ```
</details>

Seems weird to inline this part but have the SQL logic in a separate function. Can we make them consistent?
___
*[core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java, line 99 at r2](https://reviewable.io/reviews/google/nomulus/1173#-MbEedXh9DNZB9Z5kiS6:-MbEedXh9DNZB9Z5kiS7:b-5giwx4) ([raw file](https://github.com/google/nomulus/blob/269c29f6fd85d29c725d2250979f246f2df1026f/core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java#L99)):*
> ```
> // TODO(sarahbot): Take in the database value as a parameter
> ```
This seems easy enough to do within the same PR, right? Inject a `@Parameter` annotated constructor parameter and provide it with a default value depending on the output of `tm().isOfy()`.
___
*[core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json, line 70 at r2](https://reviewable.io/reviews/google/nomulus/1173#-MbEexV_39B66HTLJrMs:-MbEexV_39B66HTLJrMt:b-247fmp) ([raw file](https://github.com/google/nomulus/blob/269c29f6fd85d29c725d2250979f246f2df1026f/core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json#L70)):*
> ```
> "^[0-9A-Z_]+$"
> ```
Shouldn't it just be `^DATASTORE|CLOUD_SQL$`?
___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 140 at r2](https://reviewable.io/reviews/google/nomulus/1173#-MbEgUuxAeofpnUl9a6n:-MbEgUuxAeofpnUl9a6o:b-t3s2oq) ([raw file](https://github.com/google/nomulus/blob/269c29f6fd85d29c725d2250979f246f2df1026f/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L140)):*
> ```
> options.setDatabase("CLOUD_SQL");
> ```
Why does this need to be here? Saving to SQL is orthogonal to reading from SQL. This has no effect on this test because you are not reading from SQL.
___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 208 at r2](https://reviewable.io/reviews/google/nomulus/1173#-MbEhtCMCX0TiUuTJiRZ:-MbEhtCMCX0TiUuTJiR_:b-toeds5) ([raw file](https://github.com/google/nomulus/blob/269c29f6fd85d29c725d2250979f246f2df1026f/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L208)):*
> ```
>  void testSuccess_readFromCloudSql()
> ```
Now that this step can be tested, we need to have an overall test that actually runs the entire pipeline (i. e. calling the `main` function, or creating a `Spec11Pipeline` and calling `run()`/`setupPipeline(Pipeline)` on it if it's impossible to inject the necessary parameters. You will probably also need to have `Spec11Pipeline` take a `pipeline` parameter in order to pass a test pipeline if you call `run()`) and verifies that the results are written to both GCS and SQL correctly.
___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 217 at r2](https://reviewable.io/reviews/google/nomulus/1173#-MbEhikN3vwNo6KYfraI:-MbEhikN3vwNo6KYfraJ:bwm4ta6) ([raw file](https://github.com/google/nomulus/blob/269c29f6fd85d29c725d2250979f246f2df1026f/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L217)):*
> ```
>   private void setupCloudSql() {
> ```
I feel like a lot of the resource creation here can probably use the various `persistXXX` helper functions in `DatasbaseHelper`. Have you taken a look?


<!-- Sent from Reviewable.io -->

2021-06-05 02:13 UTC, jianglai requested changes
> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @jianglai, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java, line 91 at r3](https://reviewable.io/reviews/google/nomulus/1173#-MbOwR8jCsOy0CFzjB-9:-MbOwR8jCsOy0CFzjB-A:b-747sfx) ([raw file](https://github.com/google/nomulus/blob/fc54852a80bf557baf308023e50fd9705a215462/core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java#L91)):*
> ```
>     if (tm().isOfy() && database.equals("CLOUD_SQL")) {
>       reportingBucketUrl = reportingBucketUrl.concat("-sql");
>     }
> ```
Why is this necessary?


<!-- Sent from Reviewable.io -->

2021-06-08 16:02 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: 6 of 8 files reviewed, 9 unresolved discussions (waiting on @jianglai, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java, line 145 at r4](https://reviewable.io/reviews/google/nomulus/1173#-MbgLybnARakgf5BwdWn:-MbgLybnARakgf5BwdWo:bme9qta) ([raw file](https://github.com/google/nomulus/blob/12524c6a6d7ec9848f846a8e7096accb40e125a5/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L145)):*
> ```
>     if (emailAddress.equals(null)) {
>       emailAddress = "";
>     }
> ```
No need to use equals() with null. Use == or Optional.ofNullable().orElse("") if you prefer


<!-- Sent from Reviewable.io -->

2021-06-09 02:35 UTC, jianglai requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @jianglai, @sarahcaseybot, and @weiminyu)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 217 at r2](https://reviewable.io/reviews/google/nomulus/1173#-MbEhikN3vwNo6KYfraI:-Mbia6t06qqcKgGbs3HQ:bfdsw7a) ([raw file](https://github.com/google/nomulus/blob/269c29f6fd85d29c725d2250979f246f2df1026f/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L217)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

When I tried using these, I got an error message that said 

com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call datastore_v3.BeginTransaction in a thread that is neither the original request thread nor a thread created by ThreadManager
</blockquote></details>

It's worth digging into it and figure out why. The error message basically means that you are trying to call datastore but the environment does not support it (as it has not been set up in this test). The reason is that the `persistXXX` methods call `tm().transact()` and similar methods in the end, which defaults to using `ofyTm`. The solution is to add a line `TransactionManagerFactory.setTm(jpaTm())` in the `beforeEach()` method so that `tm()` returns a `jpaTm`.


<!-- Sent from Reviewable.io -->

2021-06-10 02:07 UTC, jianglai requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: all files reviewed, 5 unresolved discussions (waiting on @sarahcaseybot and @weiminyu)

___
*[core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java, line 91 at r3](https://reviewable.io/reviews/google/nomulus/1173#-MbOwR8jCsOy0CFzjB-9:-MbncsxE6-7wKAHK6dx_:b-dehc8r) ([raw file](https://github.com/google/nomulus/blob/fc54852a80bf557baf308023e50fd9705a215462/core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java#L91)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

For the time when Datastore is primary, we don't want a run of the pipeline that uses Cloud SQL to overwrite what is in the reporting bucket for that date.  By putting it in a separate bucket, we can easily compare what was returned from the pipeline for each database.
</blockquote></details>

So you mean you want to put production in replay mode, and manually run this job in SQL mode by setting the query parameter `DATABASE`? I guess that's fair but I'd imagine that we've have done ample testing on QA with replay, where you can write the results freely.

I'll leave it to you. It's just a bit more clean up work to do if we leave this in place.
___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 207 at r4](https://reviewable.io/reviews/google/nomulus/1173#-Mbnf-sO0BXO3dOXWJLr:-Mbnf-sO0BXO3dOXWJLs:b-cmtjvt) ([raw file](https://github.com/google/nomulus/blob/12524c6a6d7ec9848f846a8e7096accb40e125a5/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L207)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
>     // Check correctly save to GCS
>     ImmutableList<String> expectedFileContents =
>         ImmutableList.copyOf(
>             ResourceUtils.readResourceUtf8(this.getClass(), "test_output.txt").split("\n"));
>     ImmutableList<String> resultFileContents = resultFileContents();
>     assertThat(resultFileContents.size()).isEqualTo(expectedFileContents.size());
>     assertThat(resultFileContents.get(0)).isEqualTo(expectedFileContents.get(0));
>     assertThat(resultFileContents.subList(1, resultFileContents.size()))
>         .comparingElementsUsing(
>             Correspondence.from(
>                 new ThreatMatchJsonPredicate(), "has fields with unordered threatTypes equal to"))
>         .containsExactlyElementsIn(expectedFileContents.subList(1, expectedFileContents.size()));
>     // Check correctly save to Cloud SQL
>     jpaTm()
>         .transact(
>             () -> {
>               ImmutableList<Spec11ThreatMatch> sqlThreatMatches =
>                   Spec11ThreatMatchDao.loadEntriesByDate(jpaTm(), new LocalDate(2020, 1, 27));
>               assertThat(sqlThreatMatches)
>                   .comparingElementsUsing(immutableObjectCorrespondence("id"))
>                   .containsExactlyElementsIn(sqlThreatMatches);
>             });
> ```
</details>

Looks like this part is just copied over from the other two tests. Can we put them in helper methods instead to avoid code duplication?


<!-- Sent from Reviewable.io -->

2021-06-11 00:46 UTC, weiminyu approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @jianglai and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-06-11 01:11 UTC, jianglai approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1173)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 139 at r5](https://reviewable.io/reviews/google/nomulus/1173#-Mbrdo4S0e9kx9M7RaoS:-Mbsbcvi6tua4vW72BLE:bgoa53v) ([raw file](https://github.com/google/nomulus/blob/e4f66f2863e916fad733e03c523c7f68bfa1a2cf/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L139)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Yes, otherwise it caused a lot of other failures.
</blockquote></details>

Interesting. What errors are you seeing? 


<!-- Sent from Reviewable.io -->

2021-06-11 18:25 UTC, merged