Safely lazy load claims and reserved lists
google/nomulus pull request #1177
Opened 2021-05-24 13:01 UTC by mindhog

This moves the entries of all of these lists into "insignificant" fields and
manages them explicitly.

2021-05-24 17:12 UTC, gbrodman requested changes
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1177)* status: all files reviewed, 6 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/label/ReservedList.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULKyBB0-C9E4g9h58:-MaULKyBB0-C9E4g9h59:be0pzsn) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/registry/label/ReservedList.java#L84)):*
> ```Java
>    * database processing on our own so we can detach it after load.
>    */
>   @Insignificant @Transient Map<String, ReservedListEntry> reservedListMap;
> ```

I think we need to keep the Mapify annotation for Datastore?
___
*[core/src/main/java/google/registry/model/registry/label/ReservedList.java, line 167 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaUJvQ-4vuZEOGKXCpI:-MaUJvQ-4vuZEOGKXCpJ:by7r0k7) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/registry/label/ReservedList.java#L167)):*
> ```Java
>     }
> 
>     public String debug() {
> ```

what's this about? 
___
*[core/src/main/java/google/registry/model/registry/label/ReservedList.java, line 207 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaUKE0o7KME0O1QDJ2H:-MaUKE0o7KME0O1QDJ2I:b10e1fq) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/registry/label/ReservedList.java#L207)):*
> ```Java
> 
>   /** Returns a {@link Map} of domain labels to {@link ReservedListEntry}. */
>   public synchronized ImmutableMap<String, ReservedListEntry> getReservedListEntries() {
> ```

nit, but can we note in the Javadoc here that this, like the other methods, is a slow fetch and should be avoided if possible? 
___
*[core/src/main/java/google/registry/model/tmch/ClaimsEntry.java, line 49 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULUcz-M8vfNC4MvDD:-MaULUcz-M8vfNC4MvDE:b-gg6mf4) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/tmch/ClaimsEntry.java#L49)):*
> ```Java
>   }
> 
>   String getClaimKey() {
> ```

super nitty here, but 
1. the order is switched between claimKey and label w/r/t the fields / constructor 
2. do we need getters if the fields are package-private anyway?
___
*[core/src/main/java/google/registry/model/tmch/ClaimsList.java, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULe8G0gOyZFLX1TrN:-MaULe8G0gOyZFLX1TrO:bc4ktof) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/tmch/ClaimsList.java#L104)):*
> ```Java
>    * database processing on our own so we can detach it after load.
>    */
>   @Insignificant @Transient ImmutableMap<String, String> labelsToKeys;
> ```

I think we want to keep the EmbedMap annotation for Datastore
___
*[core/src/main/java/google/registry/model/tmch/ClaimsList.java, line 159 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULhuW31ckdyci2uqj:-MaULhuW31ckdyci2uqk:b-7qtdho) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/tmch/ClaimsList.java#L159)):*
> ```Java
>   }
> 
>   /** Returns an {@link Map} mapping domain label to its lookup key. */
> ```

ditto comment from other file, can we add a javadoc saying that this is slow? 

I guess here this is also called in getClaimKey and size
___
*[core/src/test/java/google/registry/model/registry/label/ReservedListTest.java, line 56 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaUM0KxDUdp85eVcGZf:-MaUM0KxDUdp85eVcGZg:b-31r716) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/test/java/google/registry/model/registry/label/ReservedListTest.java#L56)):*
> ```Java
>   @RegisterExtension
>   final InjectExtension inject =
>       new InjectExtension().withStaticFieldOverride(Ofy.class, "clock", clock);
> ```

Does the `withClock(clock)` not take care of this? odd. 


<!-- Sent from Reviewable.io -->

2021-05-24 19:49 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1177)* status: 10 of 13 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/label/ReservedList.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULKyBB0-C9E4g9h58:-MaUTfEp5g-OkXwPH34p:b-o46x1j) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/registry/label/ReservedList.java#L84)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we need to keep the Mapify annotation for Datastore?
</blockquote></details>

Hmm, yeah.  Given that the tests all passed, maybe we don't?

Added it back in any case.
___
*[core/src/main/java/google/registry/model/registry/label/ReservedList.java, line 167 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaUJvQ-4vuZEOGKXCpI:-MaUU_8H5RjHP3InPuSZ:bqm280p) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/registry/label/ReservedList.java#L167)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what's this about? 
</blockquote></details>

toString() implementation for debugging, removed.
___
*[core/src/main/java/google/registry/model/registry/label/ReservedList.java, line 207 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaUKE0o7KME0O1QDJ2H:-MaUVYjJ8Nt2gUSYBQUb:b-896fix) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/registry/label/ReservedList.java#L207)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit, but can we note in the Javadoc here that this, like the other methods, is a slow fetch and should be avoided if possible? 
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/tmch/ClaimsEntry.java, line 49 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULUcz-M8vfNC4MvDD:-MaUVp5VCE9aJn9o3k0O:b-pshchg) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/tmch/ClaimsEntry.java#L49)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

super nitty here, but 
1. the order is switched between claimKey and label w/r/t the fields / constructor 
2. do we need getters if the fields are package-private anyway?
</blockquote></details>

1. haha, yeah I shifted the order on these a couple of times because it's not immediately obvious which is the key and which is the value.  Fixed.
2. we're currently using method references for these from a toImmutableMap() method.  We could use lambdas, but generally encapsulation is good :-) Made the methods private, though.
___
*[core/src/main/java/google/registry/model/tmch/ClaimsList.java, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULe8G0gOyZFLX1TrN:-MaUe-Gs3InfQQdB5lQb:b8jk8o3) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/tmch/ClaimsList.java#L104)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we want to keep the EmbedMap annotation for Datastore
</blockquote></details>

Actually, I think ClaimsList has been fully migrated.
___
*[core/src/main/java/google/registry/model/tmch/ClaimsList.java, line 159 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULhuW31ckdyci2uqj:-MaUnGi02lpOfba1vZqs:bmz9c5l) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/tmch/ClaimsList.java#L159)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ditto comment from other file, can we add a javadoc saying that this is slow? 

I guess here this is also called in getClaimKey and size
</blockquote></details>

Done.

Actually, the suboptimal use of this in getClaimKey() and size() now offends me, so fixed that, too. 
___
*[core/src/test/java/google/registry/model/registry/label/ReservedListTest.java, line 56 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaUM0KxDUdp85eVcGZf:-MaUneBuCCTU0KR-Ui25:b-7kbs0o) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/test/java/google/registry/model/registry/label/ReservedListTest.java#L56)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Does the `withClock(clock)` not take care of this? odd. 
</blockquote></details>

It only does so for the AppEngineExtension, not for the Ofy clock.


<!-- Sent from Reviewable.io -->

2021-05-24 19:55 UTC, gbrodman requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1177)* status: all files reviewed, 3 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/label/ReservedList.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULKyBB0-C9E4g9h58:-MaUvdrJ1CSazFiJT5ar:bxvw36h) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/registry/label/ReservedList.java#L84)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Hmm, yeah.  Given that the tests all passed, maybe we don't?

Added it back in any case.
</blockquote></details>

Yeah we got rid of all the code that stored ReservedLists in Datastore so that's probably why the tests are fine. We should be good either way. 
___
*[core/src/main/java/google/registry/model/tmch/ClaimsList.java, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1177#-MaULe8G0gOyZFLX1TrN:-MaUw3Cj2v9I1Cs1VUqO:btu4gvb) ([raw file](https://github.com/google/nomulus/blob/3811740d79470b9e05625f798b57cbbea7d382a6/core/src/main/java/google/registry/model/tmch/ClaimsList.java#L104)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Actually, I think ClaimsList has been fully migrated.
</blockquote></details>

Weird, I thought I saw some failing tests related to Objectify / Datastore storage but I was just skimming so I probably just misread it. 
___
*[core/src/main/java/google/registry/model/tmch/ClaimsList.java, line 207 at r2](https://reviewable.io/reviews/google/nomulus/1177#-MaUwOCe2Pva7vVZPAzd:-MaUwOCe2Pva7vVZPAze:bhwawlx) ([raw file](https://github.com/google/nomulus/blob/226ef6d69afe1cd2864ff4ef2713e8a5c60ee00d/core/src/main/java/google/registry/model/tmch/ClaimsList.java#L207)):*
> ```Java
>           .count();
>     }
>     return getLabelsToKeys().size();
> ```

Yeah this is better, though we should probably just refer to `labelsToKeys` directly here like we now do in `getClaimKey` (though this will still work otherwise) 


<!-- Sent from Reviewable.io -->

2021-05-25 13:05 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1177)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @mindhog, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/tmch/ClaimsList.java, line 207 at r2](https://reviewable.io/reviews/google/nomulus/1177#-MaUwOCe2Pva7vVZPAzd:-MaYaChW0A9mkAWHk_Pd:bz7g1iy) ([raw file](https://github.com/google/nomulus/blob/226ef6d69afe1cd2864ff4ef2713e8a5c60ee00d/core/src/main/java/google/registry/model/tmch/ClaimsList.java#L207)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah this is better, though we should probably just refer to `labelsToKeys` directly here like we now do in `getClaimKey` (though this will still work otherwise) 
</blockquote></details>

Yep, thanks.  Done.
___
*[db/src/main/resources/sql/schema/db-schema.sql.generated, line 870 at r2](https://reviewable.io/reviews/google/nomulus/1177#-MaUzOTaBpviknHYNP5z:-MaYaFuX6yKSr3lhWYPr:ba6xil5) ([raw file](https://github.com/google/nomulus/blob/5e2869405355a14151ed3dc305a1ac9897d05a4c/db/src/main/resources/sql/schema/db-schema.sql.generated#L870)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Do we need golden files for these changes?
</blockquote></details>

No, as with PremiumList we want to preserve the foreign key constraints even though Hibernate doesn't know about them.


<!-- Sent from Reviewable.io -->

2021-05-25 14:18 UTC, gbrodman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1177#-:-MaYsvp23hbUzsvpXz5o:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-05-25 15:28 UTC, merged