Add sending notification email mechanism for expiring certificiations
google/nomulus pull request #1179
Opened 2021-05-25 14:42 UTC by rachelguan

2021-05-25 18:33 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 1 at r1](https://reviewable.io/reviews/google/nomulus/1179#-MaZnK-c7SHAnjMEG6ZS:-MaZnK-c7SHAnjMEG6ZT:bjhup8) ([raw file](https://github.com/google/nomulus/blob/90e8ae8c2868b4a7c370f246f1d5650b3c5159d7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L1)):*
> ```Java
> package google.registry.batch;
> ```

Missing license header.

You should run nom_build clean build locally first and fix all errors.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 81 at r1](https://reviewable.io/reviews/google/nomulus/1179#-MaZmlCTD513NW4u54VF:-MaZmlCTD513NW4u54VG:b-2e9k2k) ([raw file](https://github.com/google/nomulus/blob/90e8ae8c2868b4a7c370f246f1d5650b3c5159d7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L81)):*
> ```
> Objects::isNull
> ```
Objects::nonNull
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 211 at r1](https://reviewable.io/reviews/google/nomulus/1179#-MaZl_ii2hXCSvmWGOtQ:-MaZl_ii2hXCSvmWGOtR:bg4jz27) ([raw file](https://github.com/google/nomulus/blob/90e8ae8c2868b4a7c370f246f1d5650b3c5159d7/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L211)):*
> ```
> daysToExpiration
> ```
You are accessing an instance field from a static function. This cannot compile.

You may either make this method not static, or make daysToExpiration a parameter of this method.


<!-- Sent from Reviewable.io -->

2021-05-26 02:45 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 57 at r2](https://reviewable.io/reviews/google/nomulus/1179#-MaaXTTg4o8i2mwMTWQr:-MaaXTTg4o8i2mwMTWQs:b-hgugdo) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L57)):*
> ```
>   @Inject CertificateChecker certificateChecker;
>   public SendExpiringCertificationNotificationEmailAction(
> ```
Use constructor injection here:

Annotate the constructor with at Injected.
Make the certificateChecker field private final. 
Add CertificateChecker as a constructor parameter and set it to the field.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 89 at r2](https://reviewable.io/reviews/google/nomulus/1179#-MaaYKP8D59-DXZuVHQ6:-MaaYKP8D59-DXZuVHQ7:b6joj9m) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L89)):*
> ```
> shouldReceiveExpiringNotification
> ```
Make this method take a string, and you don't have to expose CertificateChecker.getCertificate() method.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 170 at r2](https://reviewable.io/reviews/google/nomulus/1179#-MaaYpKoExL4XUR-GQow:-MaaYpKoExL4XUR-GQox:b-lxcynn) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L170)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     try {
>       certificate =
>           (X509Certificate)
>               CertificateFactory.getInstance("X509")
>                   .generateCertificate(new ByteArrayInputStream(certificateString.getBytes(UTF_8)));
>     } catch (CertificateException e) {
>       throw new IllegalArgumentException("Unable to read given certificate.");
>     }
> ```
</details>

Now that you've extracted this code to the getCertificate method, call that method here.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 207 at r2](https://reviewable.io/reviews/google/nomulus/1179#-MaaYj-26tMBLckubfOb:-MaaYj-3Cs6eoWYEaV_l:b-6cstib) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L207)):*
> ```
> X509Certificate certificate
> ```
Make this parameter a string, and call getCertificate inside this method.


<!-- Sent from Reviewable.io -->

2021-05-26 14:28 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 10 files reviewed, 8 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 1 at r2](https://reviewable.io/reviews/google/nomulus/1179#-Mad3gD680Bdcn9MvYnw:-Mad3gD680Bdcn9MvYnx:bxfb1ky) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L1)):*
> ```
> 20
> ```
2021


<!-- Sent from Reviewable.io -->

2021-05-26 17:44 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 10 files reviewed, 17 unresolved discussions (waiting on @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 81 at r1](https://reviewable.io/reviews/google/nomulus/1179#-MaZmlCTD513NW4u54VF:-MadkWeQCuSMpHIPB0D0:b-cmm2zj) ([raw file](https://github.com/google/nomulus/blob/90e8ae8c2868b4a7c370f246f1d5650b3c5159d7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L81)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> Objects::isNull
> ```
Objects::nonNull
</blockquote></details>

Not necessary if you use filtering properly.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 86 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadkERW6WZsBQnBfy5n:-MadkERW6WZsBQnBfy5o:b-n2pvmr) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L86)):*
> ```Java
>         .map(registrar -> {
>           if (!registrar.isLive()) {
>             return null;
> ```

Don't do this.  Use the `.filter()` method in Java's Stream API.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 91 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadkPAR-ghHq9Gphyuc:-MadkPAR-ghHq9Gphyud:b-r08wgs) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L91)):*
> ```Java
>           try {
>             return certificateChecker.shouldReceiveExpiringNotification(certificateStr)
>                 ? new InternetAddress((registrar.getEmailAddress())) : null;
> ```

This too should be a `.filter()` call.  Having a conditional that returns null in a `.map()` call is an antipattern.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 91 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadkgxK4FwDRILx4j9p:-MadkgxK4FwDRILx4j9q:bic4zke) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L91)):*
> ```Java
>           try {
>             return certificateChecker.shouldReceiveExpiringNotification(certificateStr)
>                 ? new InternetAddress((registrar.getEmailAddress())) : null;
> ```

This likely isn't the correct email address to send to.  I think we need to send to all of the technical `RegistrarContact`s for a given Registrar, maybe also all of the admin contacts.  Note that this is N email addresses, not just 1.  Work with Bruno and gTech to confirm exactly who these emails are being sent to, and refer to other email-sending within Nomulus for an overview of how this works.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 93 at r3](https://reviewable.io/reviews/google/nomulus/1179#-Madk8Jz8ld-mbqDHxUy:-Madk8K-8R1JwoYL-ciZ:b-bk6f9m) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L93)):*
> ```Java
>                 ? new InternetAddress((registrar.getEmailAddress())) : null;
>           } catch (AddressException e) {
>             e.printStackTrace();
> ```

Log this properly using Flogger.  See other instances of logging in our codebase.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 97 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadkYj85E-t9mDDgcKL:-MadkYj85E-t9mDDgcKM:brncrbj) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L97)):*
> ```Java
>           }
>         }).filter(Objects::nonNull)
>         .collect(toCollection(ArrayList::new));
> ```

Use `toImmutableSet()`.  Always prefer immutable collections over mutable ones.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 102 at r3](https://reviewable.io/reviews/google/nomulus/1179#-Madl35PAvskDtL1cp5o:-Madl35PAvskDtL1cp5p:bst1i9c) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L102)):*
> ```Java
> 
>   // 2. send email to certificate that is expiring
>   private void sendNotification(Collection<InternetAddress> addresses) {
> ```

This will work more nicely if it takes a `Set` of `Registrar`s to work on, especially given the above.

Also, per my comments on the design doc, you're going to want to update the last sent email DateTime in this method, along with filtering on it above prior to ever calling this method.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 105 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadlK2U1VqSbulHOFK_:-MadlK2U1VqSbulHOFKa:b-e9nfnn) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L105)):*
> ```Java
>     String body = "random string";
>     String subject = "random subject";
>     ImmutableSet<InternetAddress> recipients = new ImmutableSet.Builder<InternetAddress>()
> ```

`ImmutableSet.copyOf()` is a preferable way to accomplish this use case.

But you should just be collecting to an ImmutableSet to begin with (see above comment).
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 107 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadlVEi5ffyRkdiCa4n:-MadlVEi5ffyRkdiCa4o:b-qf3tla) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L107)):*
> ```Java
>     ImmutableSet<InternetAddress> recipients = new ImmutableSet.Builder<InternetAddress>()
>         .addAll(addresses).build();
>     sendEmailService.sendEmail(
> ```

What if this fails?  Needs error handling no?  Under what conditions does it throw an exception, and what kinds of exceptions does it throw?  The last sent email DateTime shouldn't be updated if this fails.
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 457 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadlhM1CBxqMix6_7sH:-MadlhM1CBxqMix6_7sI:bgi9ngr) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/config/files/default-config.yaml#L457)):*
> ```YAML
>   # certificate is nearing expiration and warnings should be sent.
>   expirationWarningDays: 30
>   # The number of days before a certificate expires that indicates the
> ```

This should really be a list. Like:

```
expirationWarningDays:
  - 15
  - 30
```


<!-- Sent from Reviewable.io -->

2021-06-09 19:41 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 14 files reviewed, 17 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 170 at r2](https://reviewable.io/reviews/google/nomulus/1179#-MaaYpKoExL4XUR-GQow:-MadjCcN9UfrOTmzMEX5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L170)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>     try {
>       certificate =
>           (X509Certificate)
>               CertificateFactory.getInstance("X509")
>                   .generateCertificate(new ByteArrayInputStream(certificateString.getBytes(UTF_8)));
>     } catch (CertificateException e) {
>       throw new IllegalArgumentException("Unable to read given certificate.");
>     }
> ```
Now that you've extracted this code to the getCertificate method, call that method here.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 207 at r2](https://reviewable.io/reviews/google/nomulus/1179#-MaaYj-26tMBLckubfOb:-MadB9l79pfH8oUHIpPQ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L207)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> X509Certificate certificate
> ```
Make this parameter a string, and call getCertificate inside this method.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 1 at r1](https://reviewable.io/reviews/google/nomulus/1179#-MaZnK-c7SHAnjMEG6ZS:-Ma_3-pq41hpp41feR_-:b-896fix) ([raw file](https://github.com/google/nomulus/blob/90e8ae8c2868b4a7c370f246f1d5650b3c5159d7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L1)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Missing license header.

You should run nom_build clean build locally first and fix all errors.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 81 at r1](https://reviewable.io/reviews/google/nomulus/1179#-MaZmlCTD513NW4u54VF:-Ma_D6s77iLtXMnGd9eT:b-896fix) ([raw file](https://github.com/google/nomulus/blob/90e8ae8c2868b4a7c370f246f1d5650b3c5159d7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L81)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> Objects::isNull
> ```
Objects::nonNull
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 1 at r2](https://reviewable.io/reviews/google/nomulus/1179#-Mad3gD680Bdcn9MvYnw:-Madebx8-hUUN0hXsKmI:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L1)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> 20
> ```
2021
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 57 at r2](https://reviewable.io/reviews/google/nomulus/1179#-MaaXTTg4o8i2mwMTWQr:-MadiplvDnNfnm3cwyJx:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L57)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>   @Inject CertificateChecker certificateChecker;
>   public SendExpiringCertificationNotificationEmailAction(
> ```
Use constructor injection here:

Annotate the constructor with at Injected.
Make the certificateChecker field private final. 
Add CertificateChecker as a constructor parameter and set it to the field.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 89 at r2](https://reviewable.io/reviews/google/nomulus/1179#-MaaYKP8D59-DXZuVHQ6:-Madirbc5xoF8kz0HoUG:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d0b0681c01a8f98459634b5a1a451ec2eb442045/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L89)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> shouldReceiveExpiringNotification
> ```
Make this method take a string, and you don't have to expose CertificateChecker.getCertificate() method.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 86 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadkERW6WZsBQnBfy5n:-MbmHfUg88xKaVR3Jaxu:b-xkppmi) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L86)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Don't do this.  Use the `.filter()` method in Java's Stream API.
</blockquote></details>

rewriting this 


<!-- Sent from Reviewable.io -->

2021-06-11 14:45 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 15 files reviewed, 17 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 457 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadlhM1CBxqMix6_7sH:-MbqbvHyBu2mtGFOCBbO:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/config/files/default-config.yaml#L457)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should really be a list. Like:

```
expirationWarningDays:
  - 15
  - 30
```
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 211 at r1](https://reviewable.io/reviews/google/nomulus/1179#-MaZl_ii2hXCSvmWGOtQ:-MbvX8a6CfW-DT0Bpy-l:b3ifrhi) ([raw file](https://github.com/google/nomulus/blob/90e8ae8c2868b4a7c370f246f1d5650b3c5159d7/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L211)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> daysToExpiration
> ```
You are accessing an instance field from a static function. This cannot compile.

You may either make this method not static, or make daysToExpiration a parameter of this method.
</blockquote></details>

rewrote the function 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 81 at r1](https://reviewable.io/reviews/google/nomulus/1179#-MaZmlCTD513NW4u54VF:-MbvXITDAQwJJ2-SyK83:b-896fix) ([raw file](https://github.com/google/nomulus/blob/90e8ae8c2868b4a7c370f246f1d5650b3c5159d7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L81)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 91 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadkPAR-ghHq9Gphyuc:-MbsslU91MqnkHC4WpX6:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L91)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This too should be a `.filter()` call.  Having a conditional that returns null in a `.map()` call is an antipattern.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 97 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadkYj85E-t9mDDgcKL:-Mbssri-BzclNviZThNu:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L97)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use `toImmutableSet()`.  Always prefer immutable collections over mutable ones.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-14 14:24 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 17 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 91 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadkgxK4FwDRILx4j9p:-MbvXQvoAK5cSN7KVbvo:b-cz18dx) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L91)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This likely isn't the correct email address to send to.  I think we need to send to all of the technical `RegistrarContact`s for a given Registrar, maybe also all of the admin contacts.  Note that this is N email addresses, not just 1.  Work with Bruno and gTech to confirm exactly who these emails are being sent to, and refer to other email-sending within Nomulus for an overview of how this works.
</blockquote></details>

figured out the emails we will be using; 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 93 at r3](https://reviewable.io/reviews/google/nomulus/1179#-Madk8Jz8ld-mbqDHxUy:-Mc9rd1g2eePDfbgGoom:b-n1jy6l) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L93)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Log this properly using Flogger.  See other instances of logging in our codebase.
</blockquote></details>

will do. but now the file is renamed due to a typo and the code structure is slightly different  (see other file: SendExpiringCertificateNotificationEmailAction)
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 102 at r3](https://reviewable.io/reviews/google/nomulus/1179#-Madl35PAvskDtL1cp5o:-Mc9u2Ao-kVvWCtvROp-:bgvs52k) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L102)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This will work more nicely if it takes a `Set` of `Registrar`s to work on, especially given the above.

Also, per my comments on the design doc, you're going to want to update the last sent email DateTime in this method, along with filtering on it above prior to ever calling this method.
</blockquote></details>

will do 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 105 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadlK2U1VqSbulHOFK_:-Mc9u37HBTBS3XNfbGkB:bamad9n) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L105)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`ImmutableSet.copyOf()` is a preferable way to accomplish this use case.

But you should just be collecting to an ImmutableSet to begin with (see above comment).
</blockquote></details>

wont use this anymore 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java, line 107 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadlVEi5ffyRkdiCa4n:-Mc9u5Zf5Mvv5pXHv79m:bu4zfpg) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/batch/SendExpiringCertificationNotificationEmailAction.java#L107)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What if this fails?  Needs error handling no?  Under what conditions does it throw an exception, and what kinds of exceptions does it throw?  The last sent email DateTime shouldn't be updated if this fails.
</blockquote></details>

sendEmailService itself will throw email exception. 


<!-- Sent from Reviewable.io -->

2021-06-14 17:57 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 93 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAcszt203_k8Zy1lE4:-McAcszt203_k8Zy1lE5:b-vgiiqe) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L93)):*
> ```Java
>   private void sendNotificationEmails() {
>     logger.atInfo().log(
>         "About to get a list of registrars with expiring certificates at %s.", DateTime.now());
> ```

There's no need to log the current time, as logged messages are already always timestamped by default.  This can simply be "Getting list of registrars with expiring certificates."
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 137 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAdjm75X1d5mnmjZbn:-McAdjm75X1d5mnmjZbo:b-u5uv5k) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L137)):*
> ```Java
>   private ImmutableList<InternetAddress> getEmailAddresses(Registrar registrar, Type contactType) {
>     ImmutableSortedSet<RegistrarContact> contacts = registrar.getContactsOfType(contactType);
>     List<InternetAddress> addressesStr = new ArrayList<>();
> ```

This should be: `ImmutableSet.Builder<String> recipientEmails = new ImmutableSet.Builder<>();`

Note that I'm using a `Set`, not a `List`, because the ordering is important and it can't contain duplicates.  (Note that `ImmutableSet`s do, however, retain insertion order, which doesn't matter here because the order of elements returned by `registrar.getContactsOfType(...)` is not meaningful.)
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 144 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAd8SS3kH2nvPzvpV1:-McAd8SS3kH2nvPzvpV2:b-u8vonj) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L144)):*
> ```Java
>       } catch (AddressException e) {
>         // log error
>         logger.atWarning().log("Error retrieving email address from contact : %s", e);
> ```

Use `.withCause(e)` to log the exception properly along with its stack trace.  Then you don't need to call toString on it in the log statement, so the log statement can be simpler: `"Error getting email address from contact %s; skipping.", contact.___someUsefulField()`

Also note that you weren't logging the contact that failed (which is useful information), and since this exception is being swallowed, the message needs to say what action is happening after the failure, hence why I put "; skipping", so that's it clear when reading the logs what happened.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 145 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAd1w255Oui8Kj-miH:-McAd1w255Oui8Kj-miI:b-ygm61) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L145)):*
> ```Java
>         // log error
>         logger.atWarning().log("Error retrieving email address from contact : %s", e);
>         e.printStackTrace();
> ```

Don't print a stack trace; who knows where that might end up (maybe logged, but maybe not).
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 149 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAe4Oi6beQM4QmMPA0:-McAe4Oi6beQM4QmMPA1:b-vs8kip) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L149)):*
> ```Java
>     }
>     ImmutableList<InternetAddress> recipients;
>     recipients = new ImmutableList.Builder<InternetAddress>().addAll(addressesStr).build();
> ```

Once you have the correct builder as above, this just looks like `return recipientEmails.build()`

But also do be aware of `ImmutableSet.copyOf(...)` and `ImmutableList.copyOf(...)`  for other situations where you do have a collection that you want an immutable copy of; that accomplishes in one line what took 3 here.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 151 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAeLUW-lLmkVo1VWu6:-McAeLUW-lLmkVo1VWu7:bofq5w) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L151)):*
> ```Java
>     recipients = new ImmutableList.Builder<InternetAddress>().addAll(addressesStr).build();
>     return recipients;
> ```

Extra newline.  This is the kind of stuff you can catch on your own by looking at the diffs carefully.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 216 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAed_78IbkJUAW__ic:-McAed_78IbkJUAW__id:b-r4zkso) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L216)):*
> ```Java
>                 .isBefore(currentDate)
>     )) {
>       return true;
> ```

```
if (foobar) {
  return true;
}
return false;
```

is a big code smell.  This should just be:

```
return foobar;
```
___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 297 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAciTT6NCgo4aXjlAw:-McAciTT6NCgo4aXjlAx:b6wuto9) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L297)):*
> ```Java
>     assertThat(certificateChecker.shouldReceiveExpiringNotification(lastExpiringNotificationSentDate, certificateStr)).isTrue();
>   }
>   @Test
> ```

Missing newline.


<!-- Sent from Reviewable.io -->

2021-06-14 19:31 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 22 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 67 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAzre98wyM61ej4O9r:-McAzre98wyM61ej4O9s:bdpyqx5) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L67)):*
> ```Java
>   @Override
>   public void run() {
> ```

Unnecessary newline.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 126 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAyuGR017vk3t7WX8A:-McAyuGR017vk3t7WX8B:b-xsfd9j) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L126)):*
> ```Java
>       // update registrar's last certificatesentDate, if applicable
>       if (certificateStr != null) {
>         registrar.asBuilder().setLastExpiringNotificationSentDate(DateTime.now());
> ```

A few things wrong with these:

1. They're not actually saving the modified registrar entities to the DB (you need to save them in a transaction for that).
2. There's no error handling on what happens if `sendEmailService.sendEmail(...)` fails, so you could be incorrectly updating them to now even though the email has failed to send.
3. You probably want to set this to now minus 10 minutes or so, otherwise you're liable to get warning emails being sent every 16 days instead of every 15 days as intended, owing to edge conditions around when the cronjob runs vs when success is saved.  If the cronjob is always running at e.g. 02:00:00 each day, and the cron job takes a minute to run, by the time it's done sending the email it's now updated the last sent time to 02:01:__ something, so it will be just shy of 15 days in the future.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 141 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAynREDOkUXJk7scj0:-McAynRFCNzIfROIpifY:b-7e3yrx) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L141)):*
> ```Java
>       try {
>         InternetAddress address = new InternetAddress(contact.getEmailAddress());
>         addressesStr.add(address);
> ```

You can inline `address`.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 144 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAd8SS3kH2nvPzvpV1:-McAyGi423H9c0xUtjBq:b11dizg) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L144)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use `.withCause(e)` to log the exception properly along with its stack trace.  Then you don't need to call toString on it in the log statement, so the log statement can be simpler: `"Error getting email address from contact %s; skipping.", contact.___someUsefulField()`

Also note that you weren't logging the contact that failed (which is useful information), and since this exception is being swallowed, the message needs to say what action is happening after the failure, hence why I put "; skipping", so that's it clear when reading the logs what happened.
</blockquote></details>

Better error: `"Contact email address %s is invalid for contact %s; skipping.", contact.getEmailAddress(), contact.getName()`
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 160 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAy8hkDCBC9r3ItCyD:-McAy8hkDCBC9r3ItCyE:bmiog0l) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L160)):*
> ```Java
>     }
>     return String
>         .format("expiring certificate(s): %s %s", certificateStr, failOverCertificateStr);
> ```

This is gonna need some work on formatting.
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 457 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadlhM1CBxqMix6_7sH:-McAwo7g9KOHvgPS84sk:bhy9ukj) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/config/files/default-config.yaml#L457)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

With the newer streamlined logic it no longer makes sense to be a list.  (It's not clear how you'd use this anyway).  It should just be `30`, as in, notifications will start being sent if the certificate is within 30 days, but no more frequently than the 15 day interval specified below.  So it's just 2 numbers.
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 457 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAx_Z9DbKwR8kBUoHY:-McAx_Z9DbKwR8kBUoHZ:bpv7r26) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/config/files/default-config.yaml#L457)):*
> ```YAML
>   # The number of days before a certificate expires that indicates the
>   # certificate is nearing expiration and should receive an expiring notification email.
>   expiringNotificationDays: [30, 15]
> ```

Isn't this just duplicating `expirationWarningDays: 30` above?  We should be using that, so this is unnecessary.
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 458 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAxk9O4NFtxstmmjvi:-McAxk9O4NFtxstmmjvj:b-g1ph83) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/config/files/default-config.yaml#L458)):*
> ```YAML
>   # certificate is nearing expiration and should receive an expiring notification email.
>   expiringNotificationDays: [30, 15]
>   # The number of days between two successive expiring notification emails
> ```

Needs another word for better clarity: "The minimum number of days between two successive expiring notification emails".
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 459 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAxdoh8oeZhrJTc7R8:-McAxdoh8oeZhrJTc7R9:b-spdrl0) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/config/files/default-config.yaml#L459)):*
> ```YAML
>   expiringNotificationDays: [30, 15]
>   # The number of days between two successive expiring notification emails
>   expiringNotificationInterval: 15
> ```

This should be `expirationWarningIntervalDays` for naming parallelism with `expirationWarningDays`.  Note that it needs to have `Days` in the name too, otherwise it's not clear what `15` means.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 197 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McB-Ba_43qaYa7P8quz:-McB-Ba_43qaYa7P8qv-:bmbp14j) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L197)):*
> ```Java
>    * Returns whether client should receive an expiring certificate notification email
>    */
>   public boolean shouldReceiveExpiringNotification(DateTime lastExpiringNotificationSentDate, [...]

2021-06-14 20:55 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 22 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @test)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 457 at r3](https://reviewable.io/reviews/google/nomulus/1179#-MadlhM1CBxqMix6_7sH:-McB9m8-2aYCseky3CTX:b-3tuduw) ([raw file](https://github.com/google/nomulus/blob/f4701310731847348d5ff755db65efbed6609da7/core/src/main/java/google/registry/config/files/default-config.yaml#L457)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

With the newer streamlined logic it no longer makes sense to be a list.  (It's not clear how you'd use this anyway).  It should just be `30`, as in, notifications will start being sent if the certificate is within 30 days, but no more frequently than the 15 day interval specified below.  So it's just 2 numbers.
</blockquote></details>

yep .. i planned on removing that. and now its gone; 
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 457 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAx_Z9DbKwR8kBUoHY:-McB9rHWDJcsPyFLzLht:b-1748t6) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/config/files/default-config.yaml#L457)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Isn't this just duplicating `expirationWarningDays: 30` above?  We should be using that, so this is unnecessary.
</blockquote></details>

removed that . 
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 458 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAxk9O4NFtxstmmjvi:-McB9uc73-60817AgtaF:b-cy40hh) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/config/files/default-config.yaml#L458)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs another word for better clarity: "The minimum number of days between two successive expiring notification emails".
</blockquote></details>

ok fixed 
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 459 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAxdoh8oeZhrJTc7R8:-McB9sfd1Ndlv21bJxbZ:bb7lyxf) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/config/files/default-config.yaml#L459)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should be `expirationWarningIntervalDays` for naming parallelism with `expirationWarningDays`.  Note that it needs to have `Days` in the name too, otherwise it's not clear what `15` means.
</blockquote></details>

ok. 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 197 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McB-Ba_43qaYa7P8quz:-McB9WtV4Q0-W3JByJ02:blkwbl4) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L197)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`lastExpiringNotificationSentDate` needs to be annotated with `@Nullable`, given that it can be null.
</blockquote></details>

fixed' 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 198 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McB-2CRDBqkeKJ_DWk7:-McB9Y-L9Vz5pwGpFnAJ:b-i4dibd) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L198)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Does `google-java-format` like this curly brace on its own line like this?
</blockquote></details>

no it doesnt; fixed. 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 200 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McB-7R5DacFq9GNcpcr:-McB9_Fs04vMD1ds3KEu:b-qsseb8) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L200)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Can just be called `now`
</blockquote></details>

fixed;
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 216 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAed_78IbkJUAW__ic:-McB8SVeDjZISbjE_H3F:b-qssebz) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L216)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

```
if (foobar) {
  return true;
}
return false;
```

is a big code smell.  This should just be:

```
return foobar;
```
</blockquote></details>

fixed 
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 517 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McB-L3A2UP7TzKx0TTe:-McB7aJz17h8nlwDwAC_:b-qssebz) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/model/registrar/Registrar.java#L517)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Missing space after curly brace.
</blockquote></details>

fixed 
___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 297 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAciTT6NCgo4aXjlAw:-McB6Q7yEpS-5xj0jFbK:b-9sve37) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L297)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Missing newline.
</blockquote></details>

line 327 is @Test and line 326 is an empty line. 


<!-- Sent from Reviewable.io -->

2021-06-14 21:25 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 22 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @test)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 67 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAzre98wyM61ej4O9r:-McBP1YLA4qlQuOosd6f:b6p811c) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L67)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Unnecessary newline.
</blockquote></details>

removed; 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 93 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAcszt203_k8Zy1lE4:-McBP3zzA-IAwSMrkNhi:b-qsseb8) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L93)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There's no need to log the current time, as logged messages are already always timestamped by default.  This can simply be "Getting list of registrars with expiring certificates."
</blockquote></details>

fixed;
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 141 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAynREDOkUXJk7scj0:-McBMrvs20su98W88ill:b32wtd) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L141)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You can inline `address`.
</blockquote></details>

ok
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 145 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAd1w255Oui8Kj-miH:-McBN2Gp51XPHFm8U9Wr:b6p80q5) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L145)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Don't print a stack trace; who knows where that might end up (maybe logged, but maybe not).
</blockquote></details>

removed. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 151 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAeLUW-lLmkVo1VWu6:-McBPOJ_A0yOcfdJKOzK:b-7s4r6i) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L151)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Extra newline.  This is the kind of stuff you can catch on your own by looking at the diffs carefully.
</blockquote></details>

copy 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 160 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAy8hkDCBC9r3ItCyD:-McBMaB85Pn9slITfi2S:b-95m77e) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L160)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is gonna need some work on formatting.
</blockquote></details>

it randomly got disabled, the google formmatter. re-enabled. 


<!-- Sent from Reviewable.io -->

2021-06-15 15:17 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 22 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @test)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 137 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAdjm75X1d5mnmjZbn:-McFEYtl9P0pEbxe4qYr:b-9yckaw) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L137)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should be: `ImmutableSet.Builder<String> recipientEmails = new ImmutableSet.Builder<>();`

Note that I'm using a `Set`, not a `List`, because the ordering is important and it can't contain duplicates.  (Note that `ImmutableSet`s do, however, retain insertion order, which doesn't matter here because the order of elements returned by `registrar.getContactsOfType(...)` is not meaningful.)
</blockquote></details>

i thought the type had to be InternetAddress not string since setReceipients from EmailMessage Builder takes Collection<InternetAddress>recipients


<!-- Sent from Reviewable.io -->

2021-06-15 19:06 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 22 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @test)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 144 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAd8SS3kH2nvPzvpV1:-McG3IMP5mfK82l7vZHs:b-896fix) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L144)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Better error: `"Contact email address %s is invalid for contact %s; skipping.", contact.getEmailAddress(), contact.getName()`
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 149 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAe4Oi6beQM4QmMPA0:-McG3GcZ6xDwQLX3CK0N:b-896fix) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L149)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Once you have the correct builder as above, this just looks like `return recipientEmails.build()`

But also do be aware of `ImmutableSet.copyOf(...)` and `ImmutableList.copyOf(...)`  for other situations where you do have a collection that you want an immutable copy of; that accomplishes in one line what took 3 here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-15 20:56 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 22 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @test)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 126 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAyuGR017vk3t7WX8A:-McG3trM7TDqgYkfGv3H:bu94imj) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L126)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

A few things wrong with these:

1. They're not actually saving the modified registrar entities to the DB (you need to save them in a transaction for that).
2. There's no error handling on what happens if `sendEmailService.sendEmail(...)` fails, so you could be incorrectly updating them to now even though the email has failed to send.
3. You probably want to set this to now minus 10 minutes or so, otherwise you're liable to get warning emails being sent every 16 days instead of every 15 days as intended, owing to edge conditions around when the cronjob runs vs when success is saved.  If the cronjob is always running at e.g. 02:00:00 each day, and the cron job takes a minute to run, by the time it's done sending the email it's now updated the last sent time to 02:01:__ something, so it will be just shy of 15 days in the future.
</blockquote></details>

1. done 
2. done. 
3. done


<!-- Sent from Reviewable.io -->

2021-06-15 22:59 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 93 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAcszt203_k8Zy1lE4:-McGo8gM6sOHSFoamIpw:baji7n8) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L93)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

fixed;
</blockquote></details>

You missed the period.  (General rule of thumb is that logging is written in complete sentences.)
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 137 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAdjm75X1d5mnmjZbn:-McGqaumB4WX3H4NXH6k:b-twycth) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L137)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

i thought the type had to be InternetAddress not string since setReceipients from EmailMessage Builder takes Collection<InternetAddress>recipients
</blockquote></details>

`String` was a mistake on my part.  the larger point of using the `ImmutableSet.Builder` here at the beginning stands, which you've now changed it to.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 59 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGrE1QCSVwoZq6m1sB:-McGrE1RCFLy_1tXJT2f:b-gv62qy) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L59)):*
> ```Java
>       @Config("gSuiteOutgoingEmailAddress") InternetAddress gSuiteOutgoingEmailAddress,
>       SendEmailService sendEmailService,
>       @InjectedParameter CertificateChecker certificateChecker) {
> ```

I've never seen this `@InjectedParameter` before; what is it exactly and why is it necessary?  The package it's in, `org.graalvm.compiler.api.replacements.Fold`, doesn't make sense to me; all of the injection-related annotations we use in Nomulus come from the `javax.inject` package.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGoMMJ0dFoMTw-CE7i:-McGoMMJ0dFoMTw-CE7j:b-lxigvu) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
> ```Java
>     ImmutableList<Registrar> registrars = getRegistrarsWithExpiringCertificates();
>     // TODO: remove placeholder text once there's more info on email from business side
>     String subject = "random subject";
> ```

You're going to want to get this from a new config option, and then have the placeholder be in that config option.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 94 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGpr6XDe-WngNVlPzn:-McGpr6XDe-WngNVlPzo:b-6yf9to) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L94)):*
> ```Java
> 
>     for (Registrar registrar : registrars) {
>       String certificateStr = null, failOverCertificateStr = null;
> ```

A few things wrong here:

1. Per the style guide, variable initializations are limited to 1 per line.
2. The naming is a bit confusing (and confused me when I was reading the logic below); the names should make it clear that these aren't just the certificate strings, but specifically always expiring certificate strings.  So `expiringCertificate` and `expiringFailoverCertificate` (I removed the `Str` suffix since it's redundant.)
3. No need to explicitly set these null as that is the default value of an otherwise uninitialized variable.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 108 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGriwo1j4AnGG4kmOt:-McGriwo1j4AnGG4kmOu:b9wajo1) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L108)):*
> ```Java
>       }
>       if (certificateStr != null || failOverCertificateStr != null) {
>         // using an offset when updating time when dealing with cases when a few minutes of
> ```

This comment doesn't explain what it's doing very well.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 110 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGramdBbh2Zl01ig3o:-McGramdBbh2Zl01ig3p:b-clmbep) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L110)):*
> ```Java
>         // using an offset when updating time when dealing with cases when a few minutes of
>         // difference means a different day; 
>         int updateTimeOffset = 10;
> ```

This should be a static final UPPER_SNAKE_CASE variable on the class itself.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 117 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGtXwJ6sq8D-jO8_oT:-McGtXwJ6sq8D-jO8_oU:b-8vgqay) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L117)):*
> ```Java
>                   .setBody(getEmailBody(certificateStr, failOverCertificateStr))
>                   .setSubject(subject)
>                   .setRecipients(getEmailAddresses(registrar, Type.TECH))
> ```

What happens if there are no recipients set, e.g. a registrar has no contacts of this type?  We should probably be logging that at error.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 118 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGstg67VLipY50yNAF:-McGstg67VLipY50yNAG:b-h4thq1) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L118)):*
> ```Java
>                   .setSubject(subject)
>                   .setRecipients(getEmailAddresses(registrar, Type.TECH))
>                   .setBccs(getEmailAddresses(registrar, Type.ADMIN))
> ```

I don't think a BCC is the right way to go here; is there really any need to hide the ADMIN email addresses from the TECH recipients?  A BCC that would make sense would be BCCing the email to ourselves, so that we have a record in our inbox of these having being sent out (and indeed this is what we do for Spec11, which we should do here too: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/reporting/spec11/Spec11EmailUtils.java;l=165?q=setbccs&sq=&ss=nomulus%2Fnomulus

ADMIN contacts should be normal CC recipients, not BCCs.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 123 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGohAl92W6Dgub4Hmr:-McGohAl92W6Dgub4Hms:bqxltvx) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab9 [...]

2021-06-16 17:29 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 23 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 93 at r4](https://reviewable.io/reviews/google/nomulus/1179#-McAcszt203_k8Zy1lE4:-McKqIRbAaLeaGk5cBwG:bmog362) ([raw file](https://github.com/google/nomulus/blob/574996167106702adc225066a0e14018adb69f87/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L93)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You missed the period.  (General rule of thumb is that logging is written in complete sentences.)
</blockquote></details>

noted and fixed. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 59 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGrE1QCSVwoZq6m1sB:-McKqGtMEXnGZdnDxPHu:b6p80q5) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L59)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I've never seen this `@InjectedParameter` before; what is it exactly and why is it necessary?  The package it's in, `org.graalvm.compiler.api.replacements.Fold`, doesn't make sense to me; all of the injection-related annotations we use in Nomulus come from the `javax.inject` package.
</blockquote></details>

removed. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGoMMJ0dFoMTw-CE7i:-McKqMyW8sseg4PLDuCD:b-xr0bgb) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You're going to want to get this from a new config option, and then have the placeholder be in that config option.
</blockquote></details>

should this be in the default-config.yaml file ? 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 110 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGramdBbh2Zl01ig3o:-McKrmtJ16ee9MF-TwS9:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L110)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should be a static final UPPER_SNAKE_CASE variable on the class itself.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-16 23:27 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 25 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 118 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGstg67VLipY50yNAF:-McM8fGM6O309WWN9k-T:blkwbr5) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L118)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I don't think a BCC is the right way to go here; is there really any need to hide the ADMIN email addresses from the TECH recipients?  A BCC that would make sense would be BCCing the email to ourselves, so that we have a record in our inbox of these having being sent out (and indeed this is what we do for Spec11, which we should do here too: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/reporting/spec11/Spec11EmailUtils.java;l=165?q=setbccs&sq=&ss=nomulus%2Fnomulus

ADMIN contacts should be normal CC recipients, not BCCs.
</blockquote></details>

fixed. 


<!-- Sent from Reviewable.io -->

2021-06-17 05:07 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 25 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 59 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGrE1QCSVwoZq6m1sB:-McNMDs01cQkFDOPw2_o:b6p80q5) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L59)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

removed. 
</blockquote></details>

removed. 


<!-- Sent from Reviewable.io -->

2021-06-17 15:30 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 25 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 108 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGriwo1j4AnGG4kmOt:-McNaTIe8M9EzvNGbc_u:bo1are7) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L108)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This comment doesn't explain what it's doing very well.
</blockquote></details>

moved the comment to the top right above private static final int UPDATE_TIME_OFFSET = 10; 

"  // This value is used as an offset when storing the last notification email sent date. This is
  // used to handle corner cases when the update happens in between the day switch.
  // For instance,if the job starts at 2:00 am every day and it finishes at 2:03 of the same day,
  // then next day at 2am, the date difference will be less than a day, which will lead to the date
  // difference between two successive email sent date being the expected email interval days + 1;
"
  
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 117 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGtXwJ6sq8D-jO8_oT:-McNajEq5TgZZrG5jRpG:b-t9490b) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L117)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What happens if there are no recipients set, e.g. a registrar has no contacts of this type?  We should probably be logging that at error.
</blockquote></details>

added 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 142 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGqlvcC3ynp8CKVbFp:-McNn2Ce00_YhjsVBNzl:b-qssebz) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L142)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You are writing this to the logs, so saying "check logs for more details" doesn't mean anything (as the stack trace logged by `withCause(e)` is going to be logged directly adjacent to this message).  "Check logs for more details" only makes sense if it's written out somewhere that isn't the logs.  A better error message is just "Failed to send expiring certificate notification email to registrar %s."
</blockquote></details>

fixed 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 168 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGqTutCeseKGm5M1am:-McNdmT09r-LFoG4AZqD:b-qssebz) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L168)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Both of these parameters need to be annotated with `@Nullable`.
</blockquote></details>

fixed 


<!-- Sent from Reviewable.io -->

2021-06-17 17:21 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml, line 160 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGs2Xi6e4_42N8Arqh:-McPscaf6CvwArxU2lUZ:b-68r6z2) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml#L160)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Probably best to pick a time that isn't the exact same time as another task (`/_dr/task/expandRecurringBillingEvents` runs daily at 03:00Z too).
</blockquote></details>

changed it to 04:30  
___
*[core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml, line 201 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGsVtN52MqyuxcrDEc:-McPu-zr-b5kcl44DYwW:bpotwtn) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml#L201)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto re: time.
</blockquote></details>

 changed to 04:30 
___
*[core/src/main/java/google/registry/env/qa/default/WEB-INF/cron.xml, line 101 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGsXSDABqBF9frb8I4:-McPxwr9AOGtWxYMuIle:boamjz3) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/env/qa/default/WEB-INF/cron.xml#L101)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

"
</blockquote></details>

changed to 04:30
___
*[core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml, line 172 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGscVR32MkeffjksKX:-McPy4HpA_osM3hZXEB9:bku40m4) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml#L172)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You should probably check with gTech regarding whether we actually want to send emails to registrars for expiring certs on sandbox.  That may just be noise to them.  We may also want to, more generally, not attempt to notify for expiring emails on any non-production environment.
</blockquote></details>

for now, this is scheduled to run at 4:30 am in all environment; will check with gTech to see later this afternoon to see in which environments these expiring emails should be sent. 
___
*[core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml, line 176 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGsbuzDkB8wrS0QMrD:-McPy1O81rZCoDeEVIGW:boamjz3) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml#L176)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

"
</blockquote></details>

changed to 04:30


<!-- Sent from Reviewable.io -->

2021-06-18 06:29 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 25 files reviewed, 21 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 94 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGpr6XDe-WngNVlPzn:-McSkpvV5BcObGROGi-X:b-25hmij) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L94)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

A few things wrong here:

1. Per the style guide, variable initializations are limited to 1 per line.
2. The naming is a bit confusing (and confused me when I was reading the logic below); the names should make it clear that these aren't just the certificate strings, but specifically always expiring certificate strings.  So `expiringCertificate` and `expiringFailoverCertificate` (I removed the `Str` suffix since it's redundant.)
3. No need to explicitly set these null as that is the default value of an otherwise uninitialized variable.
</blockquote></details>

1. fixed; 
2. changed that part now. modified the approach since now we want to include the expiration date(s) of the certificate(s) in email. 
3. Without setting it explicitly to null, intelliJ would complain that it might not have been initialize. What is an alternative way to fix that? 


<!-- Sent from Reviewable.io -->

2021-06-18 14:47 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 21 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 123 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGohAl92W6Dgub4Hmr:-McU_WH38tbQgTwB_0Vi:b-jjcdgw) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L123)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The way you've written this, you're storing the same modified object twice in two separate transactions, which will actually overwrite the result of the first transaction since you're not re-loading it as part of the second transaction.

There should be only 1 larger wrapping transaction, and the Registrar entity needs to be reloaded from the DB inside of that transaction (to guard against any changes made since the version that we retrieved in the cache), have all the relevant modifications made to it, and then saved precisely once.  Otherwise you risk clobbering conflicting changes being made anywhere else.  The caches are safe for read purposes only, but here you're writing back the contents of the cache into the database, which is bad.
</blockquote></details>

not sure how to cover all cases in one large wrapping transaction but now only one transaction will be made. 


<!-- Sent from Reviewable.io -->

2021-06-18 15:25 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 13 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 55 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhjmO43-ff87P3por:-McUhjmP26op2Z7CgkE6:b99uyvc) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L55)):*
> ```Java
>   private static final FluentLogger logger = FluentLogger.forEnclosingClass();
> 
>   // This value is used as an offset when storing the last notification email sent date. This is
> ```

This should be a Javadoc (general rule of thumb is that if things can be Javadoc comments, they should be).
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 84 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhnl5AZosX5Oklnt9:-McUhnl5AZosX5OklntA:b-lmjwwj) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L84)):*
> ```Java
>   }
> 
>   // get a list of registrars that should receive expiring notification emails; there are two
> ```

Should be a Javadoc comment.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 103 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhqAj7Qx3jTL2Nqdp:-McUhqAj7Qx3jTL2Nqdq:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L103)):*
> ```Java
>   }
> 
>   // send notification emails to registrars with expiring certificates
> ```

Ditto.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 218 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUi-VM9lndHaw5sRG-:-McUi-VM9lndHaw5sRG0:bhxw66a) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L218)):*
> ```Java
>    * Returns whether client should receive an expiring certificate notification email
>    */
>   public boolean shouldReceiveExpiringNotification(@Nullable DateTime lastExpiringNotificationSentDate,
> ```

Is this formatting OK?  I'm not used to seeing breaks in the function definition like this.
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 521 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUiKKA331FxIB-bE1R:-McUiKKA331FxIB-bE1S:beawewx) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/model/registrar/Registrar.java#L521)):*
> ```Java
>   }
> 
>   public DateTime getLastExpiringNotificationSentDate() { return lastExpiringCertNotificationSentDate; }
> ```

Formatting is wrong.
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 687 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUiNWECmSk2_pCwQWj:-McUiNWECmSk2_pCwQWk:bsa2ooi) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/model/registrar/Registrar.java#L687)):*
> ```Java
>         .putString("lastCertificateUpdateTime", lastCertificateUpdateTime)
>         .putString("lastExpiringCertNotificationSentDate", lastExpiringCertNotificationSentDate)
>         .putString("lastExpiringFailoverCertNotificationSentDate",
> ```

Formatting looks wrong to me.

(Are you running the formatter?  Is the build succeeding when the code is formatted like this?)


<!-- Sent from Reviewable.io -->

2021-06-18 15:27 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 247 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUihck1w6tjQqEKnWy:-McUihck1w6tjQqEKnWz:bzb62hh) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L247)):*
> ```Java
>               DATE_FORMATTER.print(new DateTime(failOverCertificateExpirationDate)));
>     }
>     return firstLine + mainContent + expiringCertificates;
> ```

Use a `StringBuilder` for this instead of concatenating various strings.  It's simpler and more performant (the latter doesn't really matter in this case because it's a fixed small number of concatenations occurring, but it's good to keep in mind in general).
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 687 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUiNWECmSk2_pCwQWj:-McUiUrB1V8Wi1i9StAY:b-1homnd) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/model/registrar/Registrar.java#L687)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Formatting looks wrong to me.

(Are you running the formatter?  Is the build succeeding when the code is formatted like this?)
</blockquote></details>

Another reminder about the `gradlew coreDev` build target, which automatically runs formatting and then builds/tests the core subproject.  It's very useful.


<!-- Sent from Reviewable.io -->

2021-06-18 15:50 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 16 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 123 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGohAl92W6Dgub4Hmr:-McUmMll27zKji_ejrOG:beinlq5) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L123)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

not sure how to cover all cases in one large wrapping transaction but now only one transaction will be made. 
</blockquote></details>

There are plenty of other use cases within our codebase of large wrapping transactions.  For example, every `TransactionalFlow` has the entirety of its logic run in a single wrapping transaction.  And you haven't reloaded the registrar inside the transaction either.

You've now added lots of duplication to how this is handled.  Here's a better way to handle it (mildly pseudo-codish):

```
tm().transact():
  Registrar.Builder newRegistrar = tm().loadEntity(registrar).asBuilder();
  if certificateExpirationDate != null:
    newRegistrar.setLastExpiringCertNotificationSentDate(...);
  if failOverCertificateExpirationDate != null:
    newRegistrar.setLastExpiringFailoverCertNotificationSentDate(...);
  tm().put(newRegistrar.build());
```
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 158 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUnzmbEXcCHZqOOmfU:-McUnzmbEXcCHZqOOmfV:b2esh9l) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L158)):*
> ```Java
>                   .setRecipients(recipients);
>           if (!ccs.isEmpty()) {
>             msgBuilder.setCcs(ccs);
> ```

I believe you can narrow this down as follows:

```
          EmailMessage emailMessage =
              EmailMessage.newBuilder()
                  .setFrom(gSuiteOutgoingEmailAddress)
                  .setBody(
                      getEmailBody(
                          registrar.getRegistrarName(),
                          certificateExpirationDate,
                          failOverCertificateExpirationDate))
                  .setSubject(subject)
                  .setRecipients(recipients)
                  .setCcs(getEmailAddresses(registrar, Type.ADMIN))
                  .build();
           sendEmailService.sendEmail(emailMessage);
```

(My logic here being that `EmailMessage.Builder.setCcs()` should be able to handle an empty collection as input.)
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 176 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUmllmBGFQm4X1qPaI:-McUmllmBGFQm4X1qPaJ:b-i96962) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L176)):*
> ```Java
>                                         lastNotificationSentDate)
>                                     .setLastExpiringCertNotificationSentDate(
>                                         lastNotificationSentDate)));
> ```

You're not calling `.build()` on the builder, so this won't work.  You can't persist a `Registrar.Builder` (and I'm surprised tests aren't failing -- are your tests actually exercising this logic and validating that the last expiring notification date was updated?).
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 231 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUlaNH-YGoCwRVqFEc:-McUlaNH-YGoCwRVqFEd:b-bz6aha) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L231)):*
> ```Java
>       @Nullable Date certificateExpirationDate,
>       @Nullable Date failOverCertificateExpirationDate) {
>     if (certificateExpirationDate == null && failOverCertificateExpirationDate == null) return "";
> ```

Bad formatting -- curly braces are mandatory per the Java style guide.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 231 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUlgc2A8GYeuZ7aQB3:-McUlgc36QhsAOB1dprE:b7wyay4) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L231)):*
> ```Java
>       @Nullable Date certificateExpirationDate,
>       @Nullable Date failOverCertificateExpirationDate) {
>     if (certificateExpirationDate == null && failOverCertificateExpirationDate == null) return "";
> ```

This return value doesn't make sense, as the end result would seem to be that an email with an empty body is sent.  If the result of this function can truly be that no email should be sent at all, then the return type should be `Optional<String>`, and the call site should handle that correctly.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 233 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUlX4m47AbKfS_98-s:-McUlX4m47AbKfS_98-t:bkvoghe) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L233)):*
> ```Java
>     if (certificateExpirationDate == null && failOverCertificateExpirationDate == null) return "";
>     String firstLine = String.format("Hi %s,\n", registrar);
>     String mainContent = "  We are here to inform you:\n";
> ```

This needs to be coming from the config file.


<!-- Sent from Reviewable.io -->

2021-06-18 15:53 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 16 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 123 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGohAl92W6Dgub4Hmr:-McUohYo4t9GHM_HS1fV:b-jw5mrc) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L123)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There are plenty of other use cases within our codebase of large wrapping transactions.  For example, every `TransactionalFlow` has the entirety of its logic run in a single wrapping transaction.  And you haven't reloaded the registrar inside the transaction either.

You've now added lots of duplication to how this is handled.  Here's a better way to handle it (mildly pseudo-codish):

```
tm().transact():
  Registrar.Builder newRegistrar = tm().loadEntity(registrar).asBuilder();
  if certificateExpirationDate != null:
    newRegistrar.setLastExpiringCertNotificationSentDate(...);
  if failOverCertificateExpirationDate != null:
    newRegistrar.setLastExpiringFailoverCertNotificationSentDate(...);
  tm().put(newRegistrar.build());
```
</blockquote></details>

Not that those flows are the _best_ example of what a larger wrapping transaction looks like for this particular use case, mind you.  A more suitable one might be this:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/batch/DeleteContactsAndHostsAction.java;l=315-323?q=deletecon&ss=nomulus%2Fnomulus


<!-- Sent from Reviewable.io -->

2021-06-18 15:57 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 15 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGoMMJ0dFoMTw-CE7i:-McUp1mmBlIjBthhwZ2_:b-y8be5f) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

should this be in the default-config.yaml file ? 
</blockquote></details>

Yes, all config options should be in `default-config.yaml` with suitable generic default options for the open source build (i.e. nothing Google-specific).  You'll then want to write the Google-Registry-specific messages into the per-environment config files in our internal repo after this PR goes in (that necessarily is a separate commit because it happens in a separate source code repo).
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 94 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGpr6XDe-WngNVlPzn:-McUpivRDcXgJy_aW1ws:bc0xs2h) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L94)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

1. fixed; 
2. changed that part now. modified the approach since now we want to include the expiration date(s) of the certificate(s) in email. 
3. Without setting it explicitly to null, intelliJ would complain that it might not have been initialize. What is an alternative way to fix that? 
</blockquote></details>

Oh, if IntelliJ is complaining then listen to it.


<!-- Sent from Reviewable.io -->

2021-06-18 16:00 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 17 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 227 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUq2JZ4x1-Zm2f5ew6:-McUq2JZ4x1-Zm2f5ew7:b-r2lbbe) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L227)):*
> ```Java
>       return false;
>     }
>     /*
> ```

Please see the style guide for how to format multi-line non-Javadoc comments: https://google.github.io/styleguide/javaguide.html#s4.8.6-comments

It's worth reading through the entire style guide, and the internal best practices page.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 234 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUq0T-Bz9hDdMGW7pW:-McUq0T-Bz9hDdMGW7pX:b-vvq68u) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L234)):*
> ```Java
>     between lastExpiringNotificationSentDate and currentDate is greater than 15 days
>     */
>     // daysToExpiration = 30  expiringNotificationInterval = 15
> ```

This probably shouldn't still be here?


<!-- Sent from Reviewable.io -->

2021-06-18 16:01 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 20 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUqZHh2lAQ7mewrskp:-McUqZHh2lAQ7mewrskq:bhccpfy) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L188)):*
> ```Java
> 
>   /**
>    * Returns a certificate object by providing a serialized certificate
> ```

https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment   `the fragment is capitalized and punctuated as if it were a complete sentence.`
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 204 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUqZkVBV0SxDzsIM-7:-McUqZkVBV0SxDzsIM-8:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L204)):*
> ```Java
> 
>   /**
>    * serializes a Certificate object
> ```

Ditto.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 216 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUqeSC1NHf8fbiu5G5:-McUqeSC1NHf8fbiu5G6:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L216)):*
> ```Java
> 
>   /**
>    * Returns whether client should receive an expiring certificate notification email
> ```

Ditto.


<!-- Sent from Reviewable.io -->

2021-06-18 16:03 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 20 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/test/java/google/registry/tools/ValidateLoginCredentialsCommandTest.java, line 68 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUr-EF0dUohVYgF13b:-McUr-EF0dUohVYgF13c:bbo8ayj) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/test/java/google/registry/tools/ValidateLoginCredentialsCommandTest.java#L68)):*
> ```Java
>             ImmutableSortedMap.of(START_OF_TIME, 825, DateTime.parse("2020-09-01T00:00:00Z"), 398),
>             30,
>            15,
> ```

Formatting off?  Something in your code writing/pushing process is neglecting to format the code.


<!-- Sent from Reviewable.io -->

2021-06-18 16:05 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 22 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 99 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUrgV7A3x-KwLa8wVf:-McUrgV7A3x-KwLa8wVg:b-pnwnuv) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L99)):*
> ```Java
>                     .setCountryCode("US")
>                     .build())
>             .setPhoneNumber("+1.6464612123")
> ```

What are these phone/fax numbers?
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 167 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUr_7GAo1KUU_ypord:-McUr_7GAo1KUU_ypore:be0ajbz) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L167)):*
> ```Java
>         .setInternationalizedAddress(
>             new RegistrarAddress.Builder()
>                 .setStreet(ImmutableList.of("27 2nd Ave"))
> ```

I'll bite -- is there anything special about this address?  It's some gym?

Probably best to use fake data.


<!-- Sent from Reviewable.io -->

2021-06-18 16:10 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 24 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 44 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUsj_l-S8KogkwetZ7:-McUsj_m0npLU7ruKGGr:bfxo7bk) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L44)):*
> ```Java
> import org.joda.time.format.DateTimeFormatter;
> 
> /* An action that sends notification emails to registrars whose certificates are expiring soon.
> ```

Incorrectly formatted Javadoc comment.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 107 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUsgIf9IfU0cAncUuX:-McUsgIf9IfU0cAncUuY:b3bja83) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L107)):*
> ```Java
>     logger.atInfo().log("Getting list of registrars with expiring certificates.");
> 
>     ImmutableList<Registrar> registrars = getRegistrarsWithExpiringCertificates();
> ```

Looks to me like this can be inlined.


<!-- Sent from Reviewable.io -->

2021-06-18 16:11 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 26 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 191 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUsrqW3Gd9r7YT-1ra:-McUsrqW3Gd9r7YT-1rb:bumejkn) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L191)):*
> ```Java
> 
>     ImmutableList<Registrar> registrars = action.getRegistrarsWithExpiringCertificates();
>     assertThat(registrars.size()).isEqualTo(2);
> ```

Make a stronger assertion here -- assert that it's the correct registrars.
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 252 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUswHQBxFAEU5pl2ml:-McUswHQBxFAEU5pl2mm:bcy985j) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L252)):*
> ```Java
>     persistResource(registrar);
>     ImmutableSet<InternetAddress> recipients = action.getEmailAddresses(registrar, Type.TECH);
>     assertThat(recipients.size()).isEqualTo(3);
> ```

Ditto.  Needs to assert the actual recipients, not merely the # of them.  Same applies generally.


<!-- Sent from Reviewable.io -->

2021-06-18 16:11 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 27 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 249 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUt2PP7wFFcjL0mZbs:-McUt2PP7wFFcjL0mZbt:buapn44) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L249)):*
> ```Java
>   void test_getCertificate_throwsException() {
>     String invalidStr = "invalidStr";
>     assertThrows(IllegalArgumentException.class,
> ```

Formatting looks off to me.


<!-- Sent from Reviewable.io -->

2021-06-18 16:13 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 26 files reviewed, 28 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 104 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUtMDW9JJaFFGcB7Cz:-McUtMDXA72rK7pLa7Ep:b-j60zyg) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L104)):*
> ```Java
> 
>   // send notification emails to registrars with expiring certificates
>   protected void sendNotificationEmails() {
> ```

This method is long enough now that it probably makes sense to split off at least one helper function to get the length more manageable and make it overall more intelligible at a high level.


<!-- Sent from Reviewable.io -->

2021-06-21 03:24 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 32 files reviewed, 28 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 44 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUsj_l-S8KogkwetZ7:-McVd0JE-RWsNQXXzRhb:blkwc2c) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Incorrectly formatted Javadoc comment.
</blockquote></details>

fixed; 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 55 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhjmO43-ff87P3por:-McVojq26lquvvY2HhzS:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L55)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should be a Javadoc (general rule of thumb is that if things can be Javadoc comments, they should be).
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 84 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhnl5AZosX5Oklnt9:-McVvX6i7LsZA_S4XzTp:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L84)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should be a Javadoc comment.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 158 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUnzmbEXcCHZqOOmfU:-McUod_b5XujVbZMSbQ9:bgp3rm) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L158)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I believe you can narrow this down as follows:

```
          EmailMessage emailMessage =
              EmailMessage.newBuilder()
                  .setFrom(gSuiteOutgoingEmailAddress)
                  .setBody(
                      getEmailBody(
                          registrar.getRegistrarName(),
                          certificateExpirationDate,
                          failOverCertificateExpirationDate))
                  .setSubject(subject)
                  .setRecipients(recipients)
                  .setCcs(getEmailAddresses(registrar, Type.ADMIN))
                  .build();
           sendEmailService.sendEmail(emailMessage);
```

(My logic here being that `EmailMessage.Builder.setCcs()` should be able to handle an empty collection as input.)
</blockquote></details>

verified. i added a test case for empty immutable list for cc. removing the check. 
added a test case for empty immutable list for bcc as well. 
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 687 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUiNWECmSk2_pCwQWj:-McUmhKS6CrXBnLPeG1f:b-v4l2pg) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/model/registrar/Registrar.java#L687)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Another reminder about the `gradlew coreDev` build target, which automatically runs formatting and then builds/tests the core subproject.  It's very useful.
</blockquote></details>

i usually just reformat selected part of code after i modify, i have not gotten the chance to verify formatting in all file at the moment. thanks for reminding.   


<!-- Sent from Reviewable.io -->

2021-06-21 05:03 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 32 files reviewed, 28 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 103 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhqAj7Qx3jTL2Nqdp:-McgaKMV-17X_AGbhA4B:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L103)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 107 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUsgIf9IfU0cAncUuX:-Mcgd3Rg4fFQK6-k1P7W:b-193pc4) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L107)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Looks to me like this can be inlined.
</blockquote></details>

fixed by making in part of the for loop 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUqZHh2lAQ7mewrskp:-Mcgkct25bUT-WVHik8p:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L188)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment   `the fragment is capitalized and punctuated as if it were a complete sentence.`
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 204 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUqZkVBV0SxDzsIM-7:-McgkeC99G130sLeHDv4:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L204)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 216 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUqeSC1NHf8fbiu5G5:-Mcgqb5o16UYIGQMTvHu:b-qssebz) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L216)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

fixed 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 218 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUi-VM9lndHaw5sRG-:-McgqxLf2KglGRTQe_Gg:bbs1ksz) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L218)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is this formatting OK?  I'm not used to seeing breaks in the function definition like this.
</blockquote></details>

ran gradlew jIFA and it was successful 
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 521 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUiKKA331FxIB-bE1R:-McgwrJ7C4j-yvIj8xYJ:b-7ql1td) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/model/registrar/Registrar.java#L521)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Formatting is wrong.
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2021-06-21 05:26 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 32 files reviewed, 28 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 231 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUlaNH-YGoCwRVqFEc:-Mch-vEKBC9FciBKKSaC:b-7ql1td) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L231)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Bad formatting -- curly braces are mandatory per the Java style guide.
</blockquote></details>

fixed
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 227 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUq2JZ4x1-Zm2f5ew6:-Mch02O09nVijQsQfFZb:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L227)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Please see the style guide for how to format multi-line non-Javadoc comments: https://google.github.io/styleguide/javaguide.html#s4.8.6-comments

It's worth reading through the entire style guide, and the internal best practices page.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 234 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUq0T-Bz9hDdMGW7pW:-Mch02i0-S52mADLtPnN:b-rpej0f) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L234)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This probably shouldn't still be here?
</blockquote></details>

What shouldnt ? 
i included the rules for reviewer(s) to determine if the code and rules match. I included the values to show what each variable equals to. 
___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 249 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUt2PP7wFFcjL0mZbs:-Mch1Cut2j46l-NyqohX:blkwbr5) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L249)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Formatting looks off to me.
</blockquote></details>

fixed. 
___
*[core/src/test/java/google/registry/tools/ValidateLoginCredentialsCommandTest.java, line 68 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUr-EF0dUohVYgF13b:-Mch1EHmEdsl7RCPiLSN:b-qssebz) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/test/java/google/registry/tools/ValidateLoginCredentialsCommandTest.java#L68)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Formatting off?  Something in your code writing/pushing process is neglecting to format the code.
</blockquote></details>

fixed 
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 99 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUrgV7A3x-KwLa8wVf:-Mch0ciTAz-ChWy2Qr-D:b-x6rlgl) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L99)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What are these phone/fax numbers?
</blockquote></details>

hardcoded random values. i assumed they are mandatory when creating a registrar object ? 
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 167 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUr_7GAo1KUU_ypord:-Mch0qrY4KfIozmaY504:bwy2x1b) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L167)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I'll bite -- is there anything special about this address?  It's some gym?

Probably best to use fake data.
</blockquote></details>

yep. changed to fake data. 
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 191 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUsrqW3Gd9r7YT-1ra:-Mch0syz68_nNQxfIyYh:b-gs2s2l) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L191)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Make a stronger assertion here -- assert that it's the correct registrars.
</blockquote></details>

improved. 


<!-- Sent from Reviewable.io -->

2021-06-21 06:02 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 32 files reviewed, 28 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 252 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUswHQBxFAEU5pl2ml:-Mch96Au60Bs2_0Nf1YS:b-bkvmx8) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L252)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto.  Needs to assert the actual recipients, not merely the # of them.  Same applies generally.
</blockquote></details>

fixed that. 
For the getRegistrarsWithExpiringCertificates(), should i assert by using the registrar client id then. i also used the size of the list as the way to verify. 


<!-- Sent from Reviewable.io -->

2021-06-22 05:29 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 32 files reviewed, 28 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGoMMJ0dFoMTw-CE7i:-Mcm9cXQ-ssKIPlkW-2k:b-a2yf5) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yes, all config options should be in `default-config.yaml` with suitable generic default options for the open source build (i.e. nothing Google-specific).  You'll then want to write the Google-Registry-specific messages into the per-environment config files in our internal repo after this PR goes in (that necessarily is a separate commit because it happens in a separate source code repo).
</blockquote></details>

noted. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 231 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUlgc2A8GYeuZ7aQB3:-McmAcskCYM5PEpkL0xU:b-8iad9h) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L231)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This return value doesn't make sense, as the end result would seem to be that an email with an empty body is sent.  If the result of this function can truly be that no email should be sent at all, then the return type should be `Optional<String>`, and the call site should handle that correctly.
</blockquote></details>

changed this. I'm thinking to throw an exception if expiration date is null or certificate type is null. This method should be called only if both are assigned, along with registrar name. I assumed getRegistrarName() always returns a string. The email would still make sense even if getRegistrarName(0 returns an empty string. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 233 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUlX4m47AbKfS_98-s:-McmAIPu9E6f58BtWpqR:bhqnzi3) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L233)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This needs to be coming from the config file.
</blockquote></details>

added  expirationWarningEmailSubjectText and expirationWarningEmailBodyText in config with placeholder text. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 247 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUihck1w6tjQqEKnWy:-Mcm98Jw5gVfhlYa_lTt:b-36mh45) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L247)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use a `StringBuilder` for this instead of concatenating various strings.  It's simpler and more performant (the latter doesn't really matter in this case because it's a fixed small number of concatenations occurring, but it's good to keep in mind in general).
</blockquote></details>

storing the entire email body in config. The getEmailBody() method takes 3 parameters and in text there's three %s. This way avoids using StringBuilder, or instead of storing multiple parts of the email body, only one large text string is stored in config. 


<!-- Sent from Reviewable.io -->

2021-06-23 19:39 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 28 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 123 at r5](https://reviewable.io/reviews/google/nomulus/1179#-McGohAl92W6Dgub4Hmr:-McuNT8i01GGqGKz-h1f:bg28jga) ([raw file](https://github.com/google/nomulus/blob/4d596565cadd9c92c9a3987df0bd9d06d9ab989d/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L123)):*
> https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/batch/DeleteContactsAndHostsAction.java;l=315-323?q=deletecon&ss=nomulus%2Fnomulus
noted and used that as reference. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 104 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUtMDW9JJaFFGcB7Cz:-McuN8uQCzbFfACCfI3Z:byw77ea) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L104)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This method is long enough now that it probably makes sense to split off at least one helper function to get the length more manageable and make it overall more intelligible at a high level.
</blockquote></details>

there are now two helper methods within. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 176 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUmllmBGFQm4X1qPaI:-McuNZc_1qK76BjRp1JI:b-8rf79u) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L176)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You're not calling `.build()` on the builder, so this won't work.  You can't persist a `Registrar.Builder` (and I'm surprised tests aren't failing -- are your tests actually exercising this logic and validating that the last expiring notification date was updated?).
</blockquote></details>

fixed and test cases were not in at the moment. 


<!-- Sent from Reviewable.io -->

2021-06-24 16:15 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 37 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 54 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McycIxU8pcPY7Nu7RcR:-McycIxU8pcPY7Nu7RcS:b-2d9jd9) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L54)):*
> ```
> private static final FluentLogger logger = FluentLogger.forEnclosingClass();
> ```
nit: it is a good habit to make logger definition the first statement of the class. It doesn't matter here but in other cases it could catch static initialization logs.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 63 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcyd1cS6RPxM0Crb4YP:-Mcyd1cS6RPxM0Crb4YQ:b-ns49am) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L63)):*
> ```
> UPDATE_TIME_OFFSET
> ```
Use appropriate joda time classes such as duration.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 98 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McydeZc5mcX4kAPxK95:-McydeZc5mcX4kAPxK96:brybcd2) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L98)):*
> ```
> protected
> ```
Why protected? Unless you mean to subclass this class, protected does not make sense here. 

Make it either private, or , if this method is tested, make it package-private (i.e., no access modifier) and annotation with VisiableForTesting
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 106 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McyjqF227npo7V8vTiQ:-McyjqF227npo7V8vTiR:b-xy76s6) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L106)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>         .filter(
>             registrar ->
>                 (registrar.getClientCertificate().isPresent()
>                         && certificateChecker.shouldReceiveExpiringNotification(
>                             registrar.getLastExpiringCertNotificationSentDate(),
>                             registrar.getClientCertificate().get()))
>                     || (registrar.getFailoverClientCertificate().isPresent()
>                         && certificateChecker.shouldReceiveExpiringNotification(
>                             registrar.getLastExpiringFailoverCertNotificationSentDate(),
>                             registrar.getFailoverClientCertificate().get())))
> ```
</details>

You are repeating the same checks in sendNotificationEmail(s) methods. 

Instead of filtering here, you man want to map each registrar into an Optional<NotificationAction> where NotificationAction (or some name you prefer) could contain:

the registrar object,
boolean notifyForClientCert
boolean notifyForFailOverCert

This way you want have to call shouldReceiveExpiringNotification again.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 164 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McyhMBV6pOrdnesEjoH:-McyhMBWAYjCG9QIvMEk:bo3zzw5) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L164)):*
> ```
> if (!lastNotificationSentDate.equals(START_OF_TIME))
> ```
Consider checking for the reverse condition and make an early return. See go/tott455.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 180 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McynMlk8ji_QIVPfbKf:-McynMlk8ji_QIVPfbKg:b-r8jeun) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L180)):*
> ```
> Registrar %
> ```
Be consistent with whether to use period at the end.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 185 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcyn8hd9rJL2LQ4F5Te:-Mcyn8hd9rJL2LQ4F5Tf:bh2d2q8) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L185)):*
> ```
> certificate "
> ```
Add period and remove trailing whitespace.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 200 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McylnJz-CQIPpL05D_V:-McylnJz-CQIPpL05D_W:b-6f9na) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L200)):*
> ```
> updateLastNotificationSentDate
> ```
Why not make sendNotificationEmail() update this. Is there a use case where the data is updated without sending a email?
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 242 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcymflt2-byv8MHEboW:-Mcymflt2-byv8MHEboX:bjh288n) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L242)):*
> ```
> if (expirationDate == null || type == null) {
> ```
Use Guava (com.google.common.base.Preconditions) checkNotNull checks:
checkNotNull(expirationdate, "expirationDate");
checkNotNull(type, "type");


<!-- Sent from Reviewable.io -->

2021-06-24 19:38 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 55 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhjmO43-ff87P3por:-MczRvoq0X9g6J7AsmPw:bryo66d) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L55)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It has no summary fragment now.  It's just one big paragraph.  See other code files for what these Javadocs should look like.  https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 84 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhnl5AZosX5Oklnt9:-MczSIuq-GKUggHU9Eni:b-faujmz) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L84)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same comment re: summary fragment.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 54 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McycIxU8pcPY7Nu7RcR:-MczRang1aB73o19cH-t:b87wvs5) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L54)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> private static final FluentLogger logger = FluentLogger.forEnclosingClass();
> ```
nit: it is a good habit to make logger definition the first statement of the class. It doesn't matter here but in other cases it could catch static initialization logs.
</blockquote></details>

Wow, TIL.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 242 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcymflt2-byv8MHEboW:-MczSbwVBtzGkpncN-8H:bgsbnom) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L242)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> if (expirationDate == null || type == null) {
> ```
Use Guava (com.google.common.base.Preconditions) checkNotNull checks:
checkNotNull(expirationdate, "expirationDate");
checkNotNull(type, "type");

</blockquote></details>

Even better would be using `checkArgumentNotNull()` (which we have throughout our codebase), as it throws the more specifically useful `IllegalArgumentException` vs a generic `NullPointerException` which could really be caused by anything.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUqZHh2lAQ7mewrskp:-MczRh6z0pL22GDzvJQ6:bqynxp0) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L188)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not punctuated as if it were a complete sentence.  It's missing ending punctuation (a period in this case).
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 196 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczT1GV4NhwwZ2U9ScH:-MczT1GV4NhwwZ2U9ScI:b-fpims0) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L196)):*
> ```Java
>                   .generateCertificate(new ByteArrayInputStream(certificateStr.getBytes(UTF_8)));
>     } catch (CertificateException e) {
>       throw new IllegalArgumentException("Unable to read given certificate.");
> ```

I know this is pre-existing, but as long as you're changing things you may as well fix it.  It should look like this:

`throw new IllegalArgumentException("Unable to read given certificate", e);`

Note the two changes I've made -- removing the period at the end of the exception message (Java does not use them), and more importantly, not swallowing the inner exception.  Generally if you're gonna rethrow on an exception you should pass along the caught exception as an inner exception rather than discarding it, as is currently happening here.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 254 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczTnew18E-CF3QBVxK:-MczTnew18E-CF3QBVxL:b-ry5gsq) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L254)):*
> ```Java
>       return false;
>     }
>     /**
> ```

Javadoc comments don't make sense inside functions.  This should be `/*` (a normal multiline comment).
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 687 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUiNWECmSk2_pCwQWj:-MczU8_U5pOHkY10vt09:bepfaim) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/model/registrar/Registrar.java#L687)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

i usually just reformat selected part of code after i modify, i have not gotten the chance to verify formatting in all file at the moment. thanks for reminding.   
</blockquote></details>

So this is formatted according to what `google-java-format` wants?
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 461 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczTvvEC6PLc_9p6ObK:-MczTvvEC6PLc_9p6ObL:b-fhco5n) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/model/registrar/Registrar.java#L461)):*
> ```Java
>   DateTime lastCertificateUpdateTime;
> 
>   /** The time that an email was sent to notify expiring certificate  */
> ```

These two are formatted strangely -- they're missing an ending period and have two spaces at the end.  You've got to look through every line of the diff.
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 464 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczU1K3B1LAJ4i-pqdV:-MczU1K3B1LAJ4i-pqdW:b3kql) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/model/registrar/Registrar.java#L464)):*
> ```Java
>   DateTime lastExpiringCertNotificationSentDate;
> 
>   /** The time that an email was sent to notify expiring certificate  */
> ```

"
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 99 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUrgV7A3x-KwLa8wVf:-MczUOokAKH313Y-zuON:bfyw086) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L99)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

hardcoded random values. i assumed they are mandatory when creating a registrar object ? 
</blockquo [...]

2021-06-25 04:51 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 55 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhjmO43-ff87P3por:-Md0AzT61L0xFsazlN7u:b-kf6g9h) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L55)):*
> https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 84 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhnl5AZosX5Oklnt9:-Md0V0c43gtQVqehGRTu:bedaidc) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L84)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Same comment re: summary fragment.
</blockquote></details>

i thought it only applied to first sentence of a javadoc. I thought the first sentence has the same structure as "/** Returns the customer ID. */." except i included a condition instead of just "Returns a list of registrars" . 


<!-- Sent from Reviewable.io -->

2021-06-25 05:14 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 55 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhjmO43-ff87P3por:-Md0_Fiy-vihOpX8Smlm:b3e266c) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L55)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

> https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment
</blockquote></details>

so I changed it so then first line is a summary fragment. Since i'm explaining the purpose of this variable, can the rest be in complete sentences? 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 54 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McycIxU8pcPY7Nu7RcR:-Md0XlS_DH3rS8ssNhun:b-cq6haf) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L54)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Wow, TIL.
</blockquote></details>

wow. noted ! 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 63 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcyd1cS6RPxM0Crb4YP:-Md0_W_tBLmcy_WBFD_Z:b-lcdx1u) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L63)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> UPDATE_TIME_OFFSET
> ```
Use appropriate joda time classes such as duration.
</blockquote></details>

i changed it to Duration and now the calculation is written this way 
DateTime.now(UTC).minusMinutes((int) UPDATE_TIME_OFFSET.getStandardMinutes());
it involves more conversion. Is this the preferred way? 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 98 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McydeZc5mcX4kAPxK95:-Md0YAQ8AHZ2PIM0p_Fc:b-7kbjd4) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L98)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> protected
> ```
Why protected? Unless you mean to subclass this class, protected does not make sense here. 

Make it either private, or , if this method is tested, make it package-private (i.e., no access modifier) and annotation with VisiableForTesting
</blockquote></details>

annotated the helpers with VisibleForTesting.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 180 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McynMlk8ji_QIVPfbKf:-Md0VpDUCHm0OLIBQFGk:b9u1sev) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L180)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> Registrar %
> ```
Be consistent with whether to use period at the end.
</blockquote></details>

Done. going to use period at the end . thanks for catching that. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 185 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcyn8hd9rJL2LQ4F5Te:-Md0XryX3o0H7PxMCL3C:b-y5em8g) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L185)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> certificate "
> ```
Add period and remove trailing whitespace.
</blockquote></details>

added period and removed trailing whitespace. 


<!-- Sent from Reviewable.io -->

2021-06-25 16:04 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 114 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczVEs18REleE7H22uz:-Md2u3pO5Sy7Yr6zi5lT:baa627d) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L114)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There seems to be significant duplication here with the code above in the `beforeEach()` method, and also with various methods in `DatabaseHelper`.  I posit that you don't need most of this at all, and can get along fine by doing stuff like:

```
persistResource(Registrar.loadByClientId("TheRegistrar").get().asBuilder().setCert....(...).build())
```

(This loads one of the two existing registrars created by our App Engine test harness, and then just modifies the one or two things on it you need to change.)

I encourage you to grep `Registrar` in other tests and see how those are handling setup of them.  It seems like you're reinventing the wheel a lot here.  Definitely also look through `DatabaseHelper` to get an idea for the sum total of test helper methods available therein.

The single largest problem I'm seeing in this code review overall is a lack of reading the rest of the codebase to get a feel for how things are generally done, and then simply copying how it's done here.
</blockquote></details>

To expand on these with some specific codebase references that perhaps you haven't found yet:

Here's the two registrars `TheRegistrar` and `NewRegistrar` that are always available in any test that uses `AppEngineExtension` (which is every test that has an interaction with simulated database): https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/testing/AppEngineExtension.java;l=269-322?q=appengineex&ss=nomulus%2Fnomulus

And then here's one of many examples of reusing said registrars, with slight modifications, in tests, rather than having to create entirely new registrar entities from scratch: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/tools/UpdateRegistrarCommandTest.java;l=126-130?q=updateregistrarcom&ss=nomulus%2Fnomulus


<!-- Sent from Reviewable.io -->

2021-06-25 19:54 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 164 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McyhMBV6pOrdnesEjoH:-Md3WIkOAj01NwxXj2iu:b3ws4gh) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L164)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> if (!lastNotificationSentDate.equals(START_OF_TIME))
> ```
Consider checking for the reverse condition and make an early return. See go/tott455.
</blockquote></details>

removed this check because this is called in sendNotificationEmail(). The date no longer needs to be checked. If there's an error sending an email, an exception should be thrown and it should not get to updating the last sent date part of the workflow. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 200 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McylnJz-CQIPpL05D_V:-Md3WfJD7x0h0C7r7W2Q:b-it7hmt) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L200)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> updateLastNotificationSentDate
> ```
Why not make sendNotificationEmail() update this. Is there a use case where the data is updated without sending a email?
</blockquote></details>

calling this update method in sendNotificationEmail() now right after sendEmailService
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 242 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcymflt2-byv8MHEboW:-Md0glifC8kIrlch2U3W:bh2xs26) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L242)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Even better would be using `checkArgumentNotNull()` (which we have throughout our codebase), as it throws the more specifically useful `IllegalArgumentException` vs a generic `NullPointerException` which could really be caused by anything.
</blockquote></details>

i see. will start using checkArgumentNotNull() from now on. thanks! 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUqZHh2lAQ7mewrskp:-Md3aGeX-B8pIwi0A13e:b-rnrapz) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L188)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It's not punctuated as if it were a complete sentence.  It's missing ending punctuation (a period in this case).
</blockquote></details>

done. 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 196 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczT1GV4NhwwZ2U9ScH:-Md3ahyUCJrX-K_4YUdc:b26hpdv) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L196)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I know this is pre-existing, but as long as you're changing things you may as well fix it.  It should look like this:

`throw new IllegalArgumentException("Unable to read given certificate", e);`

Note the two changes I've made -- removing the period at the end of the exception message (Java does not use them), and more importantly, not swallowing the inner exception.  Generally if you're gonna rethrow on an exception you should pass along the caught exception as an inner exception rather than discarding it, as is currently happening here.
</blockquote></details>

regarding the period that you dropped here. Is that only the case for exception message? But for comments and javadoc, period should be there at the end of each sentence?  
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 254 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczTnew18E-CF3QBVxK:-Md3b6t192mu4lo15ASo:b-duvkbk) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L254)):*
> javadoc
fixed . I'm trying to clarify here:
It seems to me that javadoc comments are used usually at the beginning of the method. but for a more detailed comment that explains part of the method, should I just use multiline comment? I assume comment should be in multi line block if there's multiple lines. Is repeatedly using // acceptable for multiline then? I saw that in our codebase. 
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 687 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUiNWECmSk2_pCwQWj:-Md3ik0qAiH3MhGX4DIF:bpk64g) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/model/registrar/Registrar.java#L687)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

So this is formatted according to what `google-java-format` wants?
</blockquote></details>

surprisingly not caught when running gradlew coreDev. 
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 461 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczTvvEC6PLc_9p6ObK:-Md3h7wQ1dV8Y2CwZrKh:bpk6gjz) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/model/registrar/Registrar.java#L461)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These two are formatted strangely -- they're missing an ending period and have two spaces at the end.  You've got to look through every line of the diff.
</blockquote></details>

fixed this and the other ones in this file. 
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 464 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczU1K3B1LAJ4i-pqdV:-Md3hEyaAfwQyRivZpYo:b2x6cdy) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/model/registrar/Registrar.java#L464)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

"
</blockquote></details>

yes. meant to fix this when i noticed the inconsistency 


<!-- Sent from Reviewable.io -->

2021-06-25 21:33 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 106 at r9](https://reviewable.io/reviews/google/nomulus/1179#-McyjqF227npo7V8vTiQ:-Md3ktmY-n4I5bMYMZwi:bf9u41v) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L106)):*
> Optional
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 464 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczU1K3B1LAJ4i-pqdV:-Md3vD6r39PeZUuk8bof:bp9nknt) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/model/registrar/Registrar.java#L464)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

yes. meant to fix this when i noticed the inconsistency 
</blockquote></details>

a question related to these two dates. In previous discussion, we decided to set the initial value of both dates as START_OF_TIME. I was going to assign the values in Registrar.java, 

  DateTime lastExpiringCertNotificationSentDate = START_OF_TIME;
  DateTime lastExpiringFailoverCertNotificationSentDate = START_OF_TIME;

Since these DateTime objects are used in a similar way as lastCertificateUpdateTime, I thought about using it as a reference. I noticed that, there's no initialization of a previously declared variable DateTime lastCertificateUpdateTime. Was this by design? 


<!-- Sent from Reviewable.io -->

2021-06-29 19:26 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 87 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczV0rw5ESc5Xe8wRn4:-MdJdoFl30Q5JkrsIOMy:b-va6dq) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L87)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is named confusingly similar to the test registrar `TheRegistrar` which is created by default by `AppEngineExtension`.  Either pick an entirely different and unique registrar ID, or better idea, just reuse the existing `TheRegistrar`.
</blockquote></details>

i prefer to set up the registrar manually since the default one created by AppEngineExtension contains the info that i might not necessarily need. 
i will pick an entirely different unique registrar name for the sample registrar set up by calling the createRegistrar() method I wrote for testing purposes. 
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 93 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczUknf03YEeCTvMkBr:-Md44yQ06BjGApALCiMK:b-wxbnv6) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L93)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The Perfect Pint?  Any particular reason for this address?

It's really better to use fake data in tests.  `123 Fake St` works fine (and as an added bonus, is a Simpsons reference).  It's not like any address validation is actually being done here; these are just strings.

Also, are the addresses even required?
</blockquote></details>

Misinterpreted the meaning of fake data. Will make sure that the these addresses don't exist. 
and one of them is required , either local or international so I included only international address in the createRegistrar() helper. 


<!-- Sent from Reviewable.io -->

2021-06-29 19:47 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 464 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczU1K3B1LAJ4i-pqdV:-MdOIRws1hOwOP3JWl3w:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/model/registrar/Registrar.java#L464)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

a question related to these two dates. In previous discussion, we decided to set the initial value of both dates as START_OF_TIME. I was going to assign the values in Registrar.java, 

  DateTime lastExpiringCertNotificationSentDate = START_OF_TIME;
  DateTime lastExpiringFailoverCertNotificationSentDate = START_OF_TIME;

Since these DateTime objects are used in a similar way as lastCertificateUpdateTime, I thought about using it as a reference. I noticed that, there's no initialization of a previously declared variable DateTime lastCertificateUpdateTime. Was this by design? 


</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 99 at r7](https://reviewable.io/reviews/google/nomulus/1179#-McUrgV7A3x-KwLa8wVf:-MdOEFhK5U2j1MnflP-u:b-ros7ow) ([raw file](https://github.com/google/nomulus/blob/da5f9842cb28c6b686934ab65017276dbe46df60/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L99)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Don't assume, check the code.  And I wouldn't use random phone numbers (which might be real!) in test data that's being published publicly like this.  Best to use a 555 number.  All of this should be obviously fake.
</blockquote></details>

understood your point on fake data for testing. Changed the phone number to something that should obviously be fake. these fields are required. 
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 323 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczWH0j0aI6TcYkGEAh:-MdOIYlf30D5WAKqSFdX:b-xzn4xo) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L323)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This doesn't make sense to me.  Why are you deleting all registrars, rather than just `registrar`?  Also I don't think this works anyway, as you're still passing in the in-memory `registrar` variable to `getEmailAddresses()`, and `getEmailAddresses()` itself is not reloading from memory.

What you should be doing is not deleting registrars, but rather, deleting the `RegistrarContact`s of type `TECH` for a given registrar, and then asserting that the returned recipients list is empty.
</blockquote></details>

changed the way registrar is created and now all the delete resource statement can be removed. everything that is supposed to be created is created via createRegistrar(registrarname, shouldreceivenotif, shouldreceivefailovernotf) helper. 


<!-- Sent from Reviewable.io -->

2021-06-29 21:42 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 55 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhjmO43-ff87P3por:-MdOh31AEY1wO87iaBDd:bagcaiy) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L55)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

so I changed it so then first line is a summary fragment. Since i'm explaining the purpose of this variable, can the rest be in complete sentences? 
</blockquote></details>

I'm not seeing a summary fragment.  All I'm seeing is one big paragraph here.  For examples of what Javadocs should look like, see e.g: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/persistence/transaction/TransactionManager.java;l=31?q=transactionmanager&sq=&ss=nomulus%2Fnomulus

Also "Uses as an offset when..." should be something like "The offset used when ..."
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 84 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhnl5AZosX5Oklnt9:-MdOhtbf3-61qnSP0kwr:bk70j9i) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L84)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

i thought it only applied to first sentence of a javadoc. I thought the first sentence has the same structure as "/** Returns the customer ID. */." except i included a condition instead of just "Returns a list of registrars" . 
</blockquote></details>

See the rest of the codebase for how Javadoc comments work, e.g.: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java;l=52-69;bpv=1;bpt=1
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 63 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcyd1cS6RPxM0Crb4YP:-MdOhioR4ojTPdcm-cQ2:bd2u11m) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L63)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

i changed it to Duration and now the calculation is written this way 
DateTime.now(UTC).minusMinutes((int) UPDATE_TIME_OFFSET.getStandardMinutes());
it involves more conversion. Is this the preferred way? 
</blockquote></details>

See the rest of our codebase for how `Duration`s are typically used.  Here's one such example: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/batch/DeleteProberDataAction.java;l=185;drc=0e5605b1759da4813c8665ae0edcfc4ab60e099a;bpv=1;bpt=1
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 242 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcymflt2-byv8MHEboW:-MdOiCpR0ZLM_TAN493j:b-kzcawr) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L242)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

i see. will start using checkArgumentNotNull() from now on. thanks! 
</blockquote></details>

You should be using the overload that takes an error message, as the version that doesn't take an error message does not generate a meaningful Exception message.  See examples of how `checkArgumentNotNull()` is used throughout our codebase:  https://cs.opensource.google/search?q=checkargumentnotnull&sq=&ss=nomulus%2Fnomulus


<!-- Sent from Reviewable.io -->

2021-06-29 21:43 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 21 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 196 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczT1GV4NhwwZ2U9ScH:-MdOiUzD13hzbGzGO3kv:b-sre8m8) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L196)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

regarding the period that you dropped here. Is that only the case for exception message? But for comments and javadoc, period should be there at the end of each sentence?  
</blockquote></details>

Yes.  It's a weird inconsistency, but Java's exception messages are not full sentences in the same way that most other things are.


<!-- Sent from Reviewable.io -->

2021-06-29 21:48 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 20 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 254 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczTnew18E-CF3QBVxK:-MdOihQ-7U2A8pyGHIlW:b-w4lfzf) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L254)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

> javadoc
fixed . I'm trying to clarify here:
It seems to me that javadoc comments are used usually at the beginning of the method. but for a more detailed comment that explains part of the method, should I just use multiline comment? I assume comment should be in multi line block if there's multiple lines. Is repeatedly using // acceptable for multiline then? I saw that in our codebase. 
</blockquote></details>

Yes, we usually use repeated `//` for multiline comments.

Regarding Javadoc comments, the entire point of them is to automatically generate Javadoc documentation, e.g. for our codebase it's: https://javadoc.nomulus.foo/

Javadoc comments should be thought of as annotations on top of classes, methods, and fields.  They flat out don't work when they are inlined inside a method; they won't actually generate anything in the Javadoc.  They should maybe even be a presubmit error.

https://en.wikipedia.org/wiki/Javadoc
___
*[util/src/main/java/google/registry/util/EmailMessage.java, line 35 at r23](https://reviewable.io/reviews/google/nomulus/1179#-MdOj_QGENMGqlftKkVl:-MdOj_QGENMGqlftKkVm:bzda4v1) ([raw file](https://github.com/google/nomulus/blob/6e634256698ea41c865d23e8888b9389da976a21/util/src/main/java/google/registry/util/EmailMessage.java#L35)):*
> ```Java
> 
>   public abstract ImmutableSet<InternetAddress> bccs();
>   public abstract ImmutableSet<InternetAddress> ccs();
> ```

Fyi the changes to add CCs in these two files (and associated testing) would be a great example of something you could split off into a separate PR (in the spirit of http://go/small-cls ) and get in earlier.


<!-- Sent from Reviewable.io -->

2021-06-29 21:54 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 19 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 464 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczU1K3B1LAJ4i-pqdV:-MdOjvKJ01qVBSh7Bu2U:b47ilxr) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/model/registrar/Registrar.java#L464)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No idea if it was done by design.  `lastCertificateUpdateTime` was added over 5 years ago.  I'd just leave that as-is.  Plus, there is a tiny bit of semantic difference between the last mutation time of _this_ entity and the last time an external event happened.  It's a slightly more meaningful question to ask if a given entity was never updated than to ask if a given certificate was never notified about.


<!-- Sent from Reviewable.io -->

2021-06-29 21:54 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 20 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 460 at r23](https://reviewable.io/reviews/google/nomulus/1179#-MdOl2ob7obvnkZliXGd:-MdOl2ob7obvnkZliXGe:bb9qntm) ([raw file](https://github.com/google/nomulus/blob/6e634256698ea41c865d23e8888b9389da976a21/core/src/main/java/google/registry/config/files/default-config.yaml#L460)):*
> ```YAML
>   expirationWarningEmailSubjectText: Certificate Expring Within 30 Days.
>   # Text for expiring certificate notification email body that accepts 3 parameters: registrar name,
>   # certificate type and expiration date, respectively.
> ```

You're missing a comma here.


<!-- Sent from Reviewable.io -->

2021-07-02 15:37 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 20 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[util/src/main/java/google/registry/util/EmailMessage.java, line 35 at r23](https://reviewable.io/reviews/google/nomulus/1179#-MdOj_QGENMGqlftKkVl:-Mdbr6Bu0CXZjPWrc6hL:b-wkbwmt) ([raw file](https://github.com/google/nomulus/blob/6e634256698ea41c865d23e8888b9389da976a21/util/src/main/java/google/registry/util/EmailMessage.java#L35)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Fyi the changes to add CCs in these two files (and associated testing) would be a great example of something you could split off into a separate PR (in the spirit of http://go/small-cls ) and get in earlier.
</blockquote></details>

sounds good. im going to create a separate PR for that. 
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 325 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczWfVk6reaCMtIdSun:-MdOIvUj-WCqw0QUUnhs:b-i4r9bs) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L325)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This can be inlined.
</blockquote></details>

will fix this inline problem and others if i find more as i review the implementation and test cases again. 


<!-- Sent from Reviewable.io -->

2021-07-09 21:11 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 34 files reviewed, 25 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 48 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC5oTQ0YsFnU5u-J2P:-MeC5oTQ0YsFnU5u-J2Q:bk45vzj) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L48)):*
> ```Java
> 
> /** An utility to check that a given certificate meets our requirements */
> public class CertificateChecker {
> ```

I think you can separate out the changes to this class, its test class, and the related config option into a separate PR.
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 461 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC62tKEivk6imC4ywX:-MeC62tKEivk6imC4ywY:b1xu741) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/main/java/google/registry/model/registrar/Registrar.java#L461)):*
> ```Java
>   DateTime lastCertificateUpdateTime;
> 
>   /** The time that an expiring certificate notification email was sent to the registrar. */
> ```

I think you can separate out the changes to this class (along with the `RegistrarTest` changes) to a separate PR.

And think about whether there's anything else in this PR that's separable too?
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 49 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC4zFz4dKeA-Mvw721:-MeC4zFz4dKeA-Mvw722:b-xtkh1m) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L49)):*
> ```Java
> import org.mockito.Mock;
> 
> class SendExpiringCertificateNotificationEmailActionTest {
> ```

Missing Javadoc.  Also I think you're missing the `@DualDatabaseTest` annotation which you want here, and then have the tests below be annotated with `@TestOfyAndSql`.
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 132 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC5O4b9oixxqrtKgk4:-MeC5O4b9oixxqrtKgk5:b-k8ucac) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L132)):*
> ```Java
> 
>   @Test
>   void sendNotificationEmail_returnsCurrentDateTime() {
> ```

These test method bodies have been empty for weeks now.
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 283 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC5VvI35xm-ln4S1Co:-MeC5VvI35xm-ln4S1Cp:bq88riw) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L283)):*
> ```Java
>     ImmutableList<Registrar> results = action.getRegistrarsWithExpiringCertificates();
>     int numOfRegistrars = 0;
>     assertThat(results.size()).isEqualTo(numOfRegistrars);
> ```

Should be asserting that the registrars are the correct ones, not just that the right number of them is being returned.


<!-- Sent from Reviewable.io -->

2021-07-12 21:49 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 460 at r23](https://reviewable.io/reviews/google/nomulus/1179#-MdOl2ob7obvnkZliXGd:-MeRXjUF5ILNIDKhDJ9e:b-w8zikl) ([raw file](https://github.com/google/nomulus/blob/6e634256698ea41c865d23e8888b9389da976a21/core/src/main/java/google/registry/config/files/default-config.yaml#L460)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You're missing a comma here.
</blockquote></details>

i think you're referring to the comment for expirationWarningEmailBodyText. Done.
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 283 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC5VvI35xm-ln4S1Co:-MeRgKsw61xYMpm5UVSK:bmp73z4) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L283)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should be asserting that the registrars are the correct ones, not just that the right number of them is being returned.
</blockquote></details>

fixed inline problem . since this is an empty check. checked isEmpty() instead  of array size being zero. 


<!-- Sent from Reviewable.io -->

2021-07-13 20:02 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 63 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcyd1cS6RPxM0Crb4YP:-MeWSYGz1FSCZgfLYE9K:byjkqw5) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L63)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

See the rest of our codebase for how `Duration`s are typically used.  Here's one such example: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/batch/DeleteProberDataAction.java;l=185;drc=0e5605b1759da4813c8665ae0edcfc4ab60e099a;bpv=1;bpt=1
</blockquote></details>

Done. The way I use duration is in a similar way. 


<!-- Sent from Reviewable.io -->

2021-07-20 14:27 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 242 at r9](https://reviewable.io/reviews/google/nomulus/1179#-Mcymflt2-byv8MHEboW:-MeYZnzeBE_0rlHglbH8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L242)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You should be using the overload that takes an error message, as the version that doesn't take an error message does not generate a meaningful Exception message.  See examples of how `checkArgumentNotNull()` is used throughout our codebase:  https://cs.opensource.google/search?q=checkargumentnotnull&sq=&ss=nomulus%2Fnomulus
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 48 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC5oTQ0YsFnU5u-J2P:-Mf3Ij2-4ZFdlHpFgBK3:b-896fix) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L48)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think you can separate out the changes to this class, its test class, and the related config option into a separate PR.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 461 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC62tKEivk6imC4ywX:-Mf3J-xM-fKWOANxb7k6:b-896fix) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/main/java/google/registry/model/registrar/Registrar.java#L461)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think you can separate out the changes to this class (along with the `RegistrarTest` changes) to a separate PR.

And think about whether there's anything else in this PR that's separable too?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-20 21:02 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 464 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczU1K3B1LAJ4i-pqdV:-Mf4gKd72NKN2UQJAaEg:b-fzmbb3) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/model/registrar/Registrar.java#L464)):*
>  there is a tiny bit of semantic difference between the last mutation time of this entity and the last time an external event happened.  It's a sli
if that's the case, i would keep it consistent with lastCertificateUpdateTime. No initial values for  lastExpiringCertNotificationSentDate nor lastExpiringFailoverCertNotificationSentDate

Registrar portion of this PR has been extracted to https://github.com/google/nomulus/pull/1247


<!-- Sent from Reviewable.io -->

2021-07-21 19:40 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 254 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczTnew18E-CF3QBVxK:-Mf9Zuyq4eNSbL8os4hc:bccsyh6) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L254)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yes, we usually use repeated `//` for multiline comments.

Regarding Javadoc comments, the entire point of them is to automatically generate Javadoc documentation, e.g. for our codebase it's: https://javadoc.nomulus.foo/

Javadoc comments should be thought of as annotations on top of classes, methods, and fields.  They flat out don't work when they are inlined inside a method; they won't actually generate anything in the Javadoc.  They should maybe even be a presubmit error.

https://en.wikipedia.org/wiki/Javadoc
</blockquote></details>

Ack and Done. used /* (normal multiline comment). included the changes of this file to PR #1245. https://github.com/google/nomulus/pull/1245


<!-- Sent from Reviewable.io -->

2021-08-03 21:30 UTC, weiminyu requested changes
> Reviewed 1 of 12 files at r6, 1 of 10 files at r9, 1 of 2 files at r16, 1 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 30 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r23](https://reviewable.io/reviews/google/nomulus/1179#-Me6QTeB6CYDhm05f6mI:-Me6QTeB6CYDhm05f6mJ:bipmmxg) ([raw file](https://github.com/google/nomulus/blob/6e634256698ea41c865d23e8888b9389da976a21/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
> ```
>   public void run() {
>     sendNotificationEmails();
>   }
> ```
A one-liner function that just calls another looks weird. Why not move the content of sendNotificationEmails here?
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 58 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCn9NOE_P5mNUnRpMo:-MgCn9NP9nTSEOi1dQyk:bwrw8gr) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L58)):*
> ```
> Uses as an offset
> ```
This sounds a bit strange.

Should this be 'Used as an offset', which is short for "An offset that is used as ..."?
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 81 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCn_X75T2AN9IqqnjD:-MgCn_X75T2AN9IqqnjE:b-1sd0gd) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L81)):*
> ```Java
>       SendEmailService sendEmailService,
>       CertificateChecker certificateChecker) {
> ```

Extra blank line that is inconsistent with the rest of this class.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCnicJ066-DULTy7gg:-MgCnicJ066-DULTy7gh:b-8l9m0s) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
> ```
> sendNotificationEmails();
> ```
Why not move the body of sendNotificationEmails here? What is the benefit of the extra method?
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 140 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCocGBCi_JeUjT7fc8:-MgCocGBCi_JeUjT7fc9:b-kh0wur) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L140)):*
<details><summary><i alt="summary">Quoted 34 lines of code…</i></summary>

> ```
>     if (certificate.isPresent()
>         && certificateChecker.shouldReceiveExpiringNotification(
>             lastExpiringCertNotificationSentDate, certificate.get())) {
>       try {
>         ImmutableSet<InternetAddress> recipients = getEmailAddresses(registrar, Type.TECH);
>         if (!recipients.isEmpty()) {
>           sendEmailService.sendEmail(
>               EmailMessage.newBuilder()
>                   .setFrom(gSuiteOutgoingEmailAddress)
>                   .setSubject(expirationWarningEmailSubjectText)
>                   .setBody(
>                       getEmailBody(
>                           registrar.getRegistrarName(),
>                           certificateType,
>                           certificateChecker.getCertificate(certificate.get()).getNotAfter()))
>                   .setRecipients(recipients)
>                   .setCcs(getEmailAddresses(registrar, Type.ADMIN))
>                   .build());
>           updateLastNotificationSentDate(
>               registrar,
>               DateTime.now(UTC).minusMinutes((int) UPDATE_TIME_OFFSET.getStandardMinutes()),
>               certificateType);
>         } else {
>           logger.atWarning().log(
>               "Registrar %s contains no email addresses to receive notification email.",
>               registrar.getRegistrarName());
>         }
>       } catch (Exception e) {
>         logger.atWarning().withCause(e).log(
>             "Failed to send expiring certificate notification email to registrar %s",
>             registrar.getRegistrarName());
>       }
>     }
>     return START_OF_TIME;
> ```
</details>

This method is a good candidate for using guard clauses to reduce nesting. See go/tott-455

if (!certificate || !.....) {
  return START_OF_TIME;
}
if (recipients.isEmpty()) {
  log...
  return ...
}
...
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 151 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCsH4I5Q1-NOjEkFj5:-MgCsH4I5Q1-NOjEkFj6:b2nz5q) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L151)):*
> ```
>           logger.atWarning().log(
>               "Registrar %s contains no email addresses to receive notification email.",
>               registrar.getRegistrarName());
> ```
There are many such logs scattered in leaf methods. It is very verbose, and does not give a clear view of what errors are tracked.

You should consider change all warning logs to exceptions, and catch-and-log them in the run() method.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 167 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCrCuc1PvoTKyGIN4w:-MgCrCuc1PvoTKyGIN4x:b-a606m7) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L167)):*
> ```
> Uses
> ```
Note: with inline documentation of a code blocks, you don't have to follow the javadoc rule on class/method/variable and start with a partial sentence. You may start with  normal sentence here.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 177 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCr8fw2xaLC1cckEEB:-MgCr8fw2xaLC1cckEEC:b-7jbvva) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L177)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>                 if (certificateType == CertificateType.FAILOVER) {
>                   newRegistrar.setLastExpiringFailoverCertNotificationSentDate(
>                       lastNotificationSentDate);
>                   tm().put(newRegistrar.build());
>                 } else if (certificateType == CertificateType.PRIMARY) {
>                   newRegistrar.setLastExpiringCertNotificationSentDate(lastNotificationSentDate);
>                   tm().put(newRegistrar.build());
>                 } else {
>                   logger.atWarning().log("Unsupported Certificate Type: %s", certificateType);
>                 }
> ```
</details>

Can you use the switch/case/default statement here?
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 204 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCtQ-N2Yf32Y1l9fBo:-MgCtQ-O8-30Sn17XjjJ:b-t0ccra) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L204)):*
<details><summary><i alt="summary">Quoted 4 [...]

2021-08-06 15:16 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 30 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 55 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhjmO43-ff87P3por:-MfdnSZd25S2ygikE5lG:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L55)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I'm not seeing a summary fragment.  All I'm seeing is one big paragraph here.  For examples of what Javadocs should look like, see e.g: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/persistence/transaction/TransactionManager.java;l=31?q=transactionmanager&sq=&ss=nomulus%2Fnomulus

Also "Uses as an offset when..." should be something like "The offset used when ..."
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 84 at r6](https://reviewable.io/reviews/google/nomulus/1179#-McUhnl5AZosX5Oklnt9:-MfdnOeA7d9fFJHcGlkW:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ad2236bed6029dbd7c7ee2e8a47ee5255c64df8a/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L84)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

See the rest of the codebase for how Javadoc comments work, e.g.: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java;l=52-69;bpv=1;bpt=1
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 114 at r9](https://reviewable.io/reviews/google/nomulus/1179#-MczVEs18REleE7H22uz:-MgCL3Q2BFx5h0xo642u:bu76hsr) ([raw file](https://github.com/google/nomulus/blob/bd84a5b3ee5783d782440d9ce0addd4b41f196bb/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L114)):*
> .asBuilder().setCert....(...).build())
yes i'm aware their existence but those included other things that i don't need for the test cases. i think its better to include what exactly are needed when writing test cases than including setups that i dont need. 
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 49 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC4zFz4dKeA-Mvw721:-MgCLSKD0VR-KONlozK9:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L49)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Missing Javadoc.  Also I think you're missing the `@DualDatabaseTest` annotation which you want here, and then have the tests below be annotated with `@TestOfyAndSql`.
</blockquote></details>

done
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 132 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC5O4b9oixxqrtKgk4:-MgBRkdhABbK9l_PhgZs:b-896fix) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L132)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These test method bodies have been empty for weeks now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-08 23:28 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 30 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r23](https://reviewable.io/reviews/google/nomulus/1179#-Me6QTeB6CYDhm05f6mI:-MgbWpzm-2LxMVmCwse5:bn4dlz7) ([raw file](https://github.com/google/nomulus/blob/6e634256698ea41c865d23e8888b9389da976a21/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>   public void run() {
>     sendNotificationEmails();
>   }
> ```
A one-liner function that just calls another looks weird. Why not move the content of sendNotificationEmails here?
</blockquote></details>

added try catch. within the block, i added http response set up and logger message when exception happens. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 58 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCn9NOE_P5mNUnRpMo:-MgbWiaZ4ZGdPHFrRxcl:b-ge3lox) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L58)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> Uses as an offset
> ```
This sounds a bit strange.

Should this be 'Used as an offset', which is short for "An offset that is used as ..."?
</blockquote></details>

revised. this should be a javadoc right since i'm explaining what this variable does.  
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 81 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCn_X75T2AN9IqqnjD:-MgbX0x48L2bphffV6kn:b-896fix) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L81)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Extra blank line that is inconsistent with the rest of this class.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCnicJ066-DULTy7gg:-MgbXAEwDmjBlvqc6DaV:b17sy1o) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> sendNotificationEmails();
> ```
Why not move the body of sendNotificationEmails here? What is the benefit of the extra method?
</blockquote></details>

in case run() in the future gets expanded with other things. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 140 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCocGBCi_JeUjT7fc8:-MgbYGpL8MH7_O97zAiU:blkwbr5) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L140)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>     if (certificate.isPresent()
>         && certificateChecker.shouldReceiveExpiringNotification(
>             lastExpiringCertNotificationSentDate, certificate.get())) {
>       try {
>         ImmutableSet<InternetAddress> recipients = getEmailAddresses(registrar, Type.TECH);
>         if (!recipients.isEmpty()) {
>           sendEmailService.sendEmail(
>               EmailMessage.newBuilder()
>                   .setFrom(gSuiteOutgoingEmailAddress)
>                   .setSubject(expirationWarningEmailSubjectText)
>                   .setBody(
>                       getEmailBody(
>                           registrar.getRegistrarName(),
>                           certificateType,
>                           certificateChecker.getCertificate(certificate.get()).getNotAfter()))
>                   .setRecipients(recipients)
>                   .setCcs(getEmailAddresses(registrar, Type.ADMIN))
>                   .build());
>           updateLastNotificationSentDate(
>               registrar,
>               DateTime.now(UTC).minusMinutes((int) UPDATE_TIME_OFFSET.getStandardMinutes()),
>               certificateType);
>         } else {
>           logger.atWarning().log(
>               "Registrar %s contains no email addresses to receive notification email.",
>               registrar.getRegistrarName());
>         }
>       } catch (Exception e) {
>         logger.atWarning().withCause(e).log(
>             "Failed to send expiring certificate notification email to registrar %s",
>             registrar.getRegistrarName());
>       }
>     }
>     return START_OF_TIME;
> ```
This method is a good candidate for using guard clauses to reduce nesting. See go/tott-455

if (!certificate || !.....) {
  return START_OF_TIME;
}
if (recipients.isEmpty()) {
  log...
  return ...
}
...
</blockquote></details>

fixed. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 167 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCrCuc1PvoTKyGIN4w:-MgbZL4b7Ed4HN-vczZn:b-rnrapz) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L167)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> Uses
> ```
Note: with inline documentation of a code blocks, you don't have to follow the javadoc rule on class/method/variable and start with a partial sentence. You may start with  normal sentence here.


</blockquote></details>

done. 
___
*[core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml, line 202 at r23](https://reviewable.io/reviews/google/nomulus/1179#-Me2gixp9e2Rt9C-9taq:-MgbaMXUDgfv9GzkyP04:b-sj5h69) ([raw file](https://github.com/google/nomulus/blob/6e634256698ea41c865d23e8888b9389da976a21/core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml#L202)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>   <cron>
>     <url><![CDATA[/_dr/task/sendExpiringCertificateNotificationEmail]]></url>
>     <description>
>       This job runs an action that sends emails to partners if their certificates are expiring soon.
>     </description>
>     <schedule>every day 04:30</schedule>
>     <target>backend</target>
>   </cron>
> ```
We should throughly test this in sandbox before releasing this to production.
</blockquote></details>

extracted this cron.xml to a separate PR. will ask for approval once the feature is fully tested in sandbox. 


<!-- Sent from Reviewable.io -->

2021-08-08 23:28 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 30 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 177 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCr8fw2xaLC1cckEEB:-Mgc5Fhc1N3XoNEhI5Oq:b-3huukv) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L177)):*
>  change all warning logs to exceptions, a
done


<!-- Sent from Reviewable.io -->

2021-08-10 20:41 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCnicJ066-DULTy7gg:-MglmuXOC3u07gFvNyKY:biub8l7) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

in case run() in the future gets expanded with other things. 
</blockquote></details>

I'm actually OK with this as-is, but not for Rachel's stated reason.  We shouldn't structure code now in anticipation of future changes down the pike that might be coming (we should instead just refactor then).  But I do legitimately like this structure as-is now; it breaks the error/response-handling out from the rest of the business logic.  If merged together into a single function, it'd be a bit on the long side for my taste, plus with extra indentation levels from the `try {}`.


<!-- Sent from Reviewable.io -->

2021-08-10 20:53 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 29 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 209 at r44](https://reviewable.io/reviews/google/nomulus/1179#-MglpBqgCkrA8mhiBigp:-MglpBqgCkrA8mhiBigq:b3zafb2) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L209)):*
> ```Java
>                     tm().put(newRegistrar.build());
>                     logger.atInfo().log(
>                         "Updated Last Notification Email Sent Date for %s Certificate of Registrar %s.",
> ```

Too much unnecessary capitalization here and elsewhere.  Use sentence casing.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 224 at r44](https://reviewable.io/reviews/google/nomulus/1179#-Mglnpqr7ycC1cLCZiDG:-Mglnpqs5DQIC10Eeka_:b8yzkrt) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L224)):*
> ```Java
>   }
> 
>   /** Sends notification emails to registrars with expiring certificates. */
> ```

Why is this method returning a value at all given that said value isn't used?
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 227 at r44](https://reviewable.io/reviews/google/nomulus/1179#-Mglo1VH1XYNwYerDOuR:-Mglo1VH1XYNwYerDOuS:b-pgt29n) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L227)):*
> ```Java
>   @VisibleForTesting
>   int sendNotificationEmails() {
>     int emailSent = 0;
> ```

Should be `emailsSent`.  `emailSent` would just be a `boolean`.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 248 at r44](https://reviewable.io/reviews/google/nomulus/1179#-MgloANDBcEet1-QHU11:-MgloANDBcEet1-QHU12:b-z0h92e) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L248)):*
> ```Java
>     }
>     logger.atInfo().log(
>         "Notification Emails have been attempted to send to all registrars that contain "
> ```

Wording here is awkward and you aren't even taking advantage of your counter.  Something like `log("Sent %d expiring certificate warning emails to registrars.", emailsSent)` would be better.  Also note that I didn't capitalize "email".
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 292 at r44](https://reviewable.io/reviews/google/nomulus/1179#-Mgloym9ETwZKpxvdcE7:-Mgloym9ETwZKpxvdcE8:bieh7x1) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L292)):*
> ```Java
>    */
>   public enum CertificateType {
>     PRIMARY("Primary"),
> ```

How exactly are these used?  Can you give me examples of strings where these are gonna be used?  I have a feeling that they shouldn't be capitalized, and "FailOver" in particular should be something like "fail-over"
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 297 at r44](https://reviewable.io/reviews/google/nomulus/1179#-Mglom865F9b7coxEeaK:-Mglom865F9b7coxEeaL:b-g0orhr) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L297)):*
> ```Java
>     private final String displayName;
> 
>     CertificateType(String display) {
> ```

I think this should be private?  Assuming that doesn't error out for any reason.


<!-- Sent from Reviewable.io -->

2021-08-10 20:53 UTC, CydeWeys reviewed
Looks about done from my POV, modulo some small stylistic niggles.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179#-:-MglprE54R2iCeCNM8Ab:batp0j1)* status: 0 of 58 files reviewed, 29 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)



<!-- Sent from Reviewable.io -->

2021-08-11 00:00 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 29 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 151 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCsH4I5Q1-NOjEkFj5:-MgmVNA49vXhYdiDDV-8:bsh6ds1) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L151)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>           logger.atWarning().log(
>               "Registrar %s contains no email addresses to receive notification email.",
>               registrar.getRegistrarName());
> ```
There are many such logs scattered in leaf methods. It is very verbose, and does not give a clear view of what errors are tracked.

You should consider change all warning logs to exceptions, and catch-and-log them in the run() method.
</blockquote></details>

noted. for all the catch block of sendNotificationEmail () and updateLastNotificationSentDate(), a throw is now used and the error will be handled in run(). 
 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 204 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCtQ-N2Yf32Y1l9fBo:-MgmUrXo4CKQcIsYbrCG:b-4nx1ou) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L204)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>           registrar,
>           registrar.getLastExpiringCertNotificationSentDate(),
>           CertificateType.PRIMARY,
>           registrar.getClientCertificate());
> ```
This method signature loses information. The callee does not know both the certificate and the timestamp are obtained from the registrar itself. 

Consider enhance the CertificateType enum with a couple methods:


  public enum CertificateType {
    PRIMARY("Primary") {
      DateTime getLastSendDate(Registrar registrar) {
        registrar.getLastExpiringCertNotificationSentDate()
      }
    },
    FAILOVER("Failover") {
      DateTime getLastSendDate(Registrar registrar) {
        registrar.getLastExpiringFailoverCertNotificationSentDate()
      }
    };
    private final String displayName;

    CertificateType(String display) {
      this.displayName = display;
    }
    public String getDisplayName() {
      return displayName;
    }

   abstract DateTime getLastSendDate(Registrar registrar);

   abstract Certificate getCertificate(Registrar);
  }

Then you can reduce the parameters to sendNotificationEmail to two (registrar, CertificationType) and it is also less error prone.


</blockquote></details>

noted. This is a good suggestion but for this use case, it's unnecessary to add last sent date since it doesnt require the previous value for anything. in fact, it's a misnomer, last sent date is really the dateTime object that's created right before this update method. I changed the name of the dateTime variable to now instead. 


<!-- Sent from Reviewable.io -->

2021-08-11 00:00 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 29 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 151 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCsH4I5Q1-NOjEkFj5:-MgmVcOg6BIlKmpIVP80:bs5bmfk) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L151)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

noted. for all the catch block of sendNotificationEmail () and updateLastNotificationSentDate(), a throw is now used and the error will be handled in run(). 
 
</blockquote></details>

both with throw new runTimeException ()


<!-- Sent from Reviewable.io -->

2021-08-11 18:57 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 29 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 91 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCnicJ066-DULTy7gg:-MgqXcFC7U5ar2KdprP0:b-se2p6t) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L91)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I'm actually OK with this as-is, but not for Rachel's stated reason.  We shouldn't structure code now in anticipation of future changes down the pike that might be coming (we should instead just refactor then).  But I do legitimately like this structure as-is now; it breaks the error/response-handling out from the rest of the business logic.  If merged together into a single function, it'd be a bit on the long side for my taste, plus with extra indentation levels from the `try {}`.
</blockquote></details>

after looking into weimin's suggestion, i modified this method. i added RunTimeException handling (two methods throw RunTimeException so the logs don't scattered like they were before). 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 209 at r44](https://reviewable.io/reviews/google/nomulus/1179#-MglpBqgCkrA8mhiBigp:-MgptHV2Aiw0FQ9J0nc3:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L209)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Too much unnecessary capitalization here and elsewhere.  Use sentence casing.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 224 at r44](https://reviewable.io/reviews/google/nomulus/1179#-Mglnpqr7ycC1cLCZiDG:-MgptJsWDNpyfzK1JVdM:b-a0uen6) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L224)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why is this method returning a value at all given that said value isn't used?
</blockquote></details>

this is used during testing and i can log that as well.. not sure how useful it is though. added that in log. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 227 at r44](https://reviewable.io/reviews/google/nomulus/1179#-Mglo1VH1XYNwYerDOuR:-MgptRMe1xzFnCfGF8Zc:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L227)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should be `emailsSent`.  `emailSent` would just be a `boolean`.
</blockquote></details>

done
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 248 at r44](https://reviewable.io/reviews/google/nomulus/1179#-MgloANDBcEet1-QHU11:-MgqUJ_pE_FXBJ3lS2l_:b-joamk7) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L248)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Wording here is awkward and you aren't even taking advantage of your counter.  Something like `log("Sent %d expiring certificate warning emails to registrars.", emailsSent)` would be better.  Also note that I didn't capitalize "email".
</blockquote></details>

yep. doing that now. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 292 at r44](https://reviewable.io/reviews/google/nomulus/1179#-Mgloym9ETwZKpxvdcE7:-MgqYCsvCUELvx5TL8l2:bynfd79) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L292)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

How exactly are these used?  Can you give me examples of strings where these are gonna be used?  I have a feeling that they shouldn't be capitalized, and "FailOver" in particular should be something like "fail-over"
</blockquote></details>

just to ensure that there are only two types of certificates and to avoid typos. Certificate Type is used directly in getEmailBody (), UpdateLastNotificationSentDate() . Two branches (primary, fail-over) that triggers different setter/getter of registrar. I changed to primary and fail-over for display. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 297 at r44](https://reviewable.io/reviews/google/nomulus/1179#-Mglom865F9b7coxEeaK:-MgqXF7fC7B56GqsECVh:b-423r7m) ([raw file](https://github.com/google/nomulus/blob/6de69c1f23ba6fd01ca17f1832f2d5b56b0466c0/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L297)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think this should be private?  Assuming that doesn't error out for any reason.
</blockquote></details>

yep errored out. changed it to protected. 


<!-- Sent from Reviewable.io -->

2021-08-12 17:15 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 27 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 177 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCr8fw2xaLC1cckEEB:-MguuWy93AosQpUP-If7:b-5r6i19) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L177)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You need a `default:` case here that throws an Exception on an unrecognized `certificateType`.  Otherwise, as currently written, if a new certificate type is added in the future, this will start silently failing rather than loudly failing.  In general, for safety reasons, `switch` statements should almost always have a `default:` case, and when what you're switching off is specifically the values of an enum, then the `default:` case should be throwing an exception.
</blockquote></details>

originally i included a default but i wasn't sure what exactly to include within the default because that should fail. but im going to throw an exception within default. 
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 262 at r45](https://reviewable.io/reviews/google/nomulus/1179#-MgqgN-u4i9q9DC-sPfU:-Mgutsd63Jev1chtf8US:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e71baea913779c00195d089cf09d6e7191c9097c/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L262)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should be `displayName`, not `display`.  The variable names of the constructor args should match the instance variable names exactly.  As-is this is confusing, because you set it as `display` on creation but then get it back later as `getDisplayName()` -- it's not clear that those would be the same thing from looking at the method signatures (but they are the same thing, just not named the same).
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 223 at r48](https://reviewable.io/reviews/google/nomulus/1179#-MgqhgrJ578E0mqh0Ce6:-MguuNOX1qcb92XWxLUa:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/4c89cc385bb14e94fc1e9e1dac3839867ba77f86/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L223)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You should be using the `getDisplayName()` getter here, not calling the field directly.  That's why I wasn't seeing where the displayName was used.

Also, `CertificateType.displayName` is private (as it should be), so how does referencing it here by field name even work?  Does this work?  I wouldn't expect that it would compile.
</blockquote></details>

done
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 252 at r48](https://reviewable.io/reviews/google/nomulus/1179#-MgqgzAz-iFrVg6__zjW:-MguuPQO1CyL7F7lvBrX:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/4c89cc385bb14e94fc1e9e1dac3839867ba77f86/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L252)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should be using the `%d` format string for a number, not `%s`.

Also, Flogger's `log()` method already has a built-in method that supports a format string with args, so use that instead of calling `String.format()`.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-08-12 19:12 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 58 files reviewed, 27 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 177 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCr8fw2xaLC1cckEEB:-MgvlKdR2JoCYaUIU91V:bw8jvru) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L177)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

originally i included a default but i wasn't sure what exactly to include within the default because that should fail. but im going to throw an exception within default. 
</blockquote></details>

but a problem with default is that, i think it will not even get there. Let's say i call updateLastNotificationSentDate(registrar, now, CertificateType.valueOf("invalidType").  There's only two defined CertificateType enums. If its not PRIMARY or FAILOVER, it will error out with java.lang.IllegalArgumentException: no enum constant ...CertificateType.invalidType. and it will not even get to default. This was why i removed the default case. I can still include it here but i couldn't come up with a case to get to the default block. 


<!-- Sent from Reviewable.io -->

2021-08-12 20:18 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 59 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 177 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCr8fw2xaLC1cckEEB:-MgvzLsqAQPrfpAurj7E:b-hrbrtf) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L177)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

but a problem with default is that, i think it will not even get there. Let's say i call updateLastNotificationSentDate(registrar, now, CertificateType.valueOf("invalidType").  There's only two defined CertificateType enums. If its not PRIMARY or FAILOVER, it will error out with java.lang.IllegalArgumentException: no enum constant ...CertificateType.invalidType. and it will not even get to default. This was why i removed the default case. I can still include it here but i couldn't come up with a case to get to the default block. 
</blockquote></details>

The point of the default case is to protect us further down the line if someone then adds another value to the enum without realizing that there exist other parts of the codebase (like this one) that expect to be handling every single possible value. See e.g.: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/dns/RefreshDnsAction.java;l=63-73?q=switch%5C%20%5C(&ss=nomulus%2Fnomulus&start=11

Also, given that `certificateType` is being passed in as an argument, something like `IllegalArgumentException` is better to throw than the more generic `RuntimeException`.


<!-- Sent from Reviewable.io -->

2021-08-13 14:29 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 59 files reviewed, 23 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 177 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCr8fw2xaLC1cckEEB:-Mgw32qP2H4rNdC992Hl:b-mv7snv) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L177)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The point of the default case is to protect us further down the line if someone then adds another value to the enum without realizing that there exist other parts of the codebase (like this one) that expect to be handling every single possible value. See e.g.: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/dns/RefreshDnsAction.java;l=63-73?q=switch%5C%20%5C(&ss=nomulus%2Fnomulus&start=11

Also, given that `certificateType` is being passed in as an argument, something like `IllegalArgumentException` is better to throw than the more generic `RuntimeException`.
</blockquote></details>

ok that makes sense . switched to IllegalArgumentException . 


<!-- Sent from Reviewable.io -->

2021-08-17 16:11 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 59 files reviewed, 24 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 204 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCtQ-N2Yf32Y1l9fBo:-MhJrb4xCr6zKu1M2x6I:bz2n1xs) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L204)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

noted. This is a good suggestion but for this use case, it's unnecessary to add last sent date since it doesnt require the previous value for anything. in fact, it's a misnomer, last sent date is really the dateTime object that's created right before this update method. I changed the name of the dateTime variable to now instead. 
</blockquote></details>

Are we talking about the same method? I'm looking at sendNotificationEmail(Registrar, DateTime, CertificateType, Optional<String>). Both DateTime and Optional<String> are extracted from the first parameter, the registrar. By passing in these two parameters separately, it is redundant and error-prone.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 112 at r60](https://reviewable.io/reviews/google/nomulus/1179#-MhJphVG6TSNrhp7O_E4:-MhJphVG6TSNrhp7O_E5:bqnj77o) ([raw file](https://github.com/google/nomulus/blob/3d613e4f65efd79c82461c59b6aae76c0aa45624/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L112)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>     } catch (IllegalArgumentException e) {
>       logger.atWarning().withCause(e).log(
>           "Illegal arguments being passed in when sending expiring certificate notification "
>               + "emails.");
>     } catch (RuntimeException e) {
>       logger.atWarning().withCause(e).log(
>           "Exception thrown when sending expiring certificate notification emails.");
>     } catch (Exception e) {
>       logger.atSevere().withCause(e).log(
>           "Unexpected error when sending expiring certificate notification emails.");
>       response.setStatus(SC_INTERNAL_SERVER_ERROR);
>       response.setPayload(String.format("Errored out with cause: %s", e));
>     }
> ```
</details>

You did not set response in two of the catch blocks.

You can combine all three, i.e., use on catch (Exception e) block. The reason for failure is in the cause, you can't add more information here.


<!-- Sent from Reviewable.io -->

2021-08-17 18:26 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 59 files reviewed, 18 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 204 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCtQ-N2Yf32Y1l9fBo:-MhKBwG78okKSv8_VmOu:b-6u4dre) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L204)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Are we talking about the same method? I'm looking at sendNotificationEmail(Registrar, DateTime, CertificateType, Optional<String>). Both DateTime and Optional<String> are extracted from the first parameter, the registrar. By passing in these two parameters separately, it is redundant and error-prone.
</blockquote></details>

DateTime and Optional are both from Registrar but there are two kinds of DateTime and Optional that can be extracted from Registrar. Having them as parameters allows us to pass those in  instead of handle all cases within one helper method. Registrar is being used for the registrar name getter in most cases except for getEmailAddresses() where getContactsOfType() is called.  
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 112 at r60](https://reviewable.io/reviews/google/nomulus/1179#-MhJphVG6TSNrhp7O_E4:-MhKAtVRDtUGGV7aAzAi:b-yc3uf9) ([raw file](https://github.com/google/nomulus/blob/3d613e4f65efd79c82461c59b6aae76c0aa45624/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L112)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>     } catch (IllegalArgumentException e) {
>       logger.atWarning().withCause(e).log(
>           "Illegal arguments being passed in when sending expiring certificate notification "
>               + "emails.");
>     } catch (RuntimeException e) {
>       logger.atWarning().withCause(e).log(
>           "Exception thrown when sending expiring certificate notification emails.");
>     } catch (Exception e) {
>       logger.atSevere().withCause(e).log(
>           "Unexpected error when sending expiring certificate notification emails.");
>       response.setStatus(SC_INTERNAL_SERVER_ERROR);
>       response.setPayload(String.format("Errored out with cause: %s", e));
>     }
> ```
You did not set response in two of the catch blocks.

You can combine all three, i.e., use on catch (Exception e) block. The reason for failure is in the cause, you can't add more information here.
</blockquote></details>

how should we handle exceptions that we expect vs the ones we dont expect? shouldn't there be branches to log them? 


<!-- Sent from Reviewable.io -->

2021-08-18 19:11 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 59 files reviewed, 18 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 112 at r60](https://reviewable.io/reviews/google/nomulus/1179#-MhJphVG6TSNrhp7O_E4:-MhPeqzWBX3HGsEz54JN:b-pfaisi) ([raw file](https://github.com/google/nomulus/blob/3d613e4f65efd79c82461c59b6aae76c0aa45624/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L112)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

how should we handle exceptions that we expect vs the ones we dont expect? shouldn't there be branches to log them? 
</blockquote></details>

changed it to catch (Exception e) and now handling them all by just logging warning logs. will catch up with ben monitoring once he comes back. 


<!-- Sent from Reviewable.io -->

2021-08-18 19:29 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 59 files reviewed, 18 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 204 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCtQ-N2Yf32Y1l9fBo:-MhPiBRhCFkoiuScbSVJ:b-cl9w9w) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L204)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

DateTime and Optional are both from Registrar but there are two kinds of DateTime and Optional that can be extracted from Registrar. Having them as parameters allows us to pass those in  instead of handle all cases within one helper method. Registrar is being used for the registrar name getter in most cases except for getEmailAddresses() where getContactsOfType() is called.  
</blockquote></details>

I think its fine to have Registrar and DateTime since Registrar is used by another helper method for email. 


<!-- Sent from Reviewable.io -->

2021-08-19 14:10 UTC, weiminyu approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 59 files reviewed, 16 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)



<!-- Sent from Reviewable.io -->

2021-08-19 16:38 UTC, rachelguan reviewed
> Reviewed 1 of 2 files at r16.
> Dismissed @CydeWeys from 12 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 0 of 59 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 177 at r34](https://reviewable.io/reviews/google/nomulus/1179#-MgCr8fw2xaLC1cckEEB:-MhUFl9y464Ow1pJNtX5:b-40qkub) ([raw file](https://github.com/google/nomulus/blob/b0ae3712b29a648298c471eb78be9ecc4e1b685f/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L177)):*
> Done [Dismissing this comment Ben is currently out and Weimin has approved the PR]. 
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 461 at r26](https://reviewable.io/reviews/google/nomulus/1179#-MeC62tKEivk6imC4ywX:-MhUFb7a4IoH9V1gllal:bh9yaxw) ([raw file](https://github.com/google/nomulus/blob/843da66286ccbd5de09872fa240ae1eefa8b6b5d/core/src/main/java/google/registry/model/registrar/Registrar.java#L461)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

[Ben is currently out and Weimin has approved the PR]. 


<!-- Sent from Reviewable.io -->

2021-08-19 16:45 UTC, rachelguan reviewed
> Reviewed 1 of 10 files at r9, 2 of 29 files at r25, 1 of 2 files at r53, 1 of 9 files at r58, 7 of 7 files at r67, 1 of 7 files at r68, 1 of 1 files at r69.
> Dismissed @CydeWeys and @weiminyu from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1179)* status: 6 of 59 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)



<!-- Sent from Reviewable.io -->

2021-08-19 16:49 UTC, merged