Unwrap the return value of loadMostRecentRevisionAtTime
google/nomulus pull request #1205
Opened 2021-06-10 20:33 UTC by jianglai

In SQL we do not need to wrap it in a Result. Unfortunately we cannot
overload a function based on its return value so we renamed the existing
one and created a new one with the old name that returns the resource
directly. Once we no longer have use of Datastore we can delete the now
renamed function that returns a Result<? extends EppResource>

2021-06-11 15:26 UTC, gbrodman requested changes
Let's change all the `loadResultAtPointInTime(...).now()` calls to use the synchronous version. I think there are only a couple (at most) situations where we want the asynchronicity. 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1205#-:-MbvdT4m2naGXtPzx2Dy:bb0u2i0)* status: all files reviewed, 3 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 301 at r1](https://reviewable.io/reviews/google/nomulus/1205#-Mbvesll4FafUZPLtEU4:-Mbvesll4FafUZPLtEU5:bbews77) ([raw file](https://github.com/google/nomulus/blob/c8c66c22e70f845cc2b37954bdb2dca509bbfe77/core/src/main/java/google/registry/model/EppResourceUtils.java#L301)):*
> ```Java
>    * objects can be restored to any revision.
>    *
>    * <p>TODO(b/177567432): Once Datastore is completely removed, remove the Result wrapping.
> ```

this comment is now out of date
___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1205#-Mbvew_u9KIyx9SS6wod:-Mbvew_u9KIyx9SS6woe:bbews77) ([raw file](https://github.com/google/nomulus/blob/c8c66c22e70f845cc2b37954bdb2dca509bbfe77/core/src/main/java/google/registry/model/EppResourceUtils.java#L313)):*
> ```Java
>     }
>     // If the resource was not modified after the requested time, then use it as-is, otherwise find
>     // the most recent revision asynchronously, and return an async result that wraps that revision
> ```

this comment is now out of date
___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 330 at r1](https://reviewable.io/reviews/google/nomulus/1205#-MbveSQr27hl_8zzItKT:-MbveSQr27hl_8zzItKU:b-nx2pff) ([raw file](https://github.com/google/nomulus/blob/c8c66c22e70f845cc2b37954bdb2dca509bbfe77/core/src/main/java/google/registry/model/EppResourceUtils.java#L330)):*
> ```Java
>    * Rewinds an {@link EppResource} object to a given point in time.
>    *
>    * <p>This method costs nothing if {@code resource} is already current. Otherwise it needs to
> ```

Technically this method always costs nothing; it's the async function that it provides that can cost something.


<!-- Sent from Reviewable.io -->

2021-06-14 13:13 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1205)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 301 at r1](https://reviewable.io/reviews/google/nomulus/1205#-Mbvesll4FafUZPLtEU4:-Mc9_eDl9odMwaFjUAJB:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c8c66c22e70f845cc2b37954bdb2dca509bbfe77/core/src/main/java/google/registry/model/EppResourceUtils.java#L301)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this comment is now out of date
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1205#-Mbvew_u9KIyx9SS6wod:-Mc9_t7qDubxK-2KXRHN:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c8c66c22e70f845cc2b37954bdb2dca509bbfe77/core/src/main/java/google/registry/model/EppResourceUtils.java#L313)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this comment is now out of date
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 330 at r1](https://reviewable.io/reviews/google/nomulus/1205#-MbveSQr27hl_8zzItKT:-Mc9apmYC4pdcf9-pvQ7:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c8c66c22e70f845cc2b37954bdb2dca509bbfe77/core/src/main/java/google/registry/model/EppResourceUtils.java#L330)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Technically this method always costs nothing; it's the async function that it provides that can cost something.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-14 14:29 UTC, gbrodman approved these changes
lgtm modulo necessary formatting changes 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1205#-:-Mc9vNrG976VtjBhRexx:b-3lzbks)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2021-06-14 15:00 UTC, gbrodman approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1205)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2021-06-14 15:55 UTC, merged