Add new domain list fields
google/nomulus pull request #1208
Opened 2021-06-14 21:44 UTC by sarahcaseybot

As part of b/186247597, this adds new fields to the Registry object that represent Premium and Reserved list. Once this code is live, all existing Registry entities should be resaved in order to populate these new fields. Then, the old premiumList and ReservedList fields can be removed to allow for the removal of Premium and Reserved list entities from the Datastore schema.

2021-06-15 14:55 UTC, CydeWeys requested changes
You're also going to want a quick scrap `ResaveAllTldsCommand` nomulus tool command.  It should boil down to one line, something like:

```
tm().transact(() -> tm().putAll(tm().loadAllOf(Registry.class)));
```

(I just typed that up quickly in Reviewable, so not every method name is necessarily perfect.)

And run that on all environments once this is deployed to effect the data migration.  Then you can clean all the migration code up and leave only the new String fields.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1208#-:-McF91bG-okY9gdbpz1M:b-nni442)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 115 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McF8sqx5UoaZ8hXiHNq:-McF8sqx5UoaZ8hXiHNr:b-8f71q5) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L115)):*
> ```Java
>   void postLoad() {
>     tldStr = tldStrId;
>     if (premiumListName != null) {
> ```

Add TODOs on these methods to remove them once this data migration is done.
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 119 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McF7xIhBntWaVSopHXT:-McF7xIhBntWaVSopHXU:bsqak4t) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L119)):*
> ```Java
>     }
>     if (reservedListNames != null) {
>       ImmutableSet.Builder<Key<ReservedList>> builder = new ImmutableSet.Builder<>();
> ```

You can do this more legibly using Streams.  Something like:

```
reservedLists = reservedListNames.stream().map(name -> Key.create(getCrossTldKey(), ReservedList.class, name)).collect(toImmuatbleSet());
```
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 131 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McF8akx6ttedw_mQsDV:-McF8akx6ttedw_mQsDW:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L131)):*
> ```Java
>     if (reservedLists != null) {
>       ImmutableSet.Builder<String> builder = new ImmutableSet.Builder<>();
>       for (Key<ReservedList> reservedListKey : reservedLists) {
> ```

Ditto.
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 421 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McF7hgu1V246fb3oZtd:-McF7hgu1V246fb3oZte:bwj0scq) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L421)):*
> ```Java
> 
>   /**
>    * Retrieves an ImmutableSet of all ReservedLists associated with this tld. This set contains only
> ```

Needs to follow the Javadoc style guide of a one line summary (used for IDE hover-over hints and such), followed by additional paragraphs of elaboration.
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 434 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McF7pg2514NRWRnCgvO:-McF7pg2514NRWRnCgvP:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L434)):*
> ```Java
> 
>   /**
>    * The name of the {@link PremiumList} for this TLD, if there is one. This is only the name of the
> ```

Ditto.
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 931 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McF7T7U5Kgo_pOiAbLB:-McF7T7U5Kgo_pOiAbLC:b3zp5m5) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L931)):*
> ```Java
>     }
> 
>     public Builder setPremiumList(PremiumList premiumList) {
> ```

The parameter should be annotated with `@Nullable` seeing as how that is allowable.


<!-- Sent from Reviewable.io -->

2021-06-15 15:13 UTC, mindhog requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1208)* status: all files reviewed, 8 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 418 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McFDQsr8OcLi0HdkFSQ:-McFDQsr8OcLi0HdkFSR:b1hxrnp) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L418)):*
> ```Java
>   /** The set of reserved list names that are applicable to this registry. */
>   @Column(name = "reserved_list_names")
>   Set<String> reservedListNames;
> ```

This field should probably be at-Ignore'd (we don't need it in datastore, Registry is replicated)
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 440 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McFDdogBHv1Bqam-Rhq:-McFDdogBHv1Bqam-Rhr:bpxxhbx) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L440)):*
> ```Java
>    */
>   @Column(name = "premium_list_name", nullable = true)
>   String premiumListName;
> ```

Should also be at-Ignore'd


<!-- Sent from Reviewable.io -->

2021-06-15 19:29 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1208)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @CydeWeys, @mindhog, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 418 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McFDQsr8OcLi0HdkFSQ:-McG4uxt6dbXoj4xvx1E:b-i27mh6) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L418)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

But won't we need it once we remove the reservedList field after all the Registry entities are resaved?
</blockquote></details>

Ok, right.  You're doing this so you can convert these references in Datastore.

You know, as I think about it, are you sure you want to do this whole change to Registry?  It's not buying us very much, we're going to have to do another pass through this code anyway and this change will be a lot easier after we're fully on the SQL side (where you _can_ just convert these sets to strings).

Alternately, since you've already done some work to make use of the fact that these are named, and since you have the code here to convert from Set<Key> to Set<String>, why not just leave the datastore records as they are?  Then you won't have to worry about migrating the data in datastore and you can make these fields at-Ignore'd.


<!-- Sent from Reviewable.io -->

2021-06-15 19:47 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1208)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @CydeWeys, @mindhog, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 418 at r1](https://reviewable.io/reviews/google/nomulus/1208#-McFDQsr8OcLi0HdkFSQ:-McGCM9L9W0Tsw-nngoj:b-q26ixr) ([raw file](https://github.com/google/nomulus/blob/6cd35058001b02dd11cdc9238162a8be33680468/core/src/main/java/google/registry/model/registry/Registry.java#L418)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Ok, right.  You're doing this so you can convert these references in Datastore.

You know, as I think about it, are you sure you want to do this whole change to Registry?  It's not buying us very much, we're going to have to do another pass through this code anyway and this change will be a lot easier after we're fully on the SQL side (where you _can_ just convert these sets to strings).

Alternately, since you've already done some work to make use of the fact that these are named, and since you have the code here to convert from Set<Key> to Set<String>, why not just leave the datastore records as they are?  Then you won't have to worry about migrating the data in datastore and you can make these fields at-Ignore'd.
</blockquote></details>

(sorry that should have read "convert from Set&lt;Key&gt; to Set&lt;String&gt;" -- who thought HTML tags in markdown were a good idea?)


<!-- Sent from Reviewable.io -->

2021-06-15 22:34 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1208)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 419 at r2](https://reviewable.io/reviews/google/nomulus/1208#-McGnaCH0kmrbMvA_WqW:-McGnaCI1ZH8ldadBmdb:bp22aml) ([raw file](https://github.com/google/nomulus/blob/df9ed563ddf97c86d4f7e3b2b51a8c112c29fdc5/core/src/main/java/google/registry/model/registry/Registry.java#L419)):*
> ```Java
> 
>   /**
>    * Retrieves an ImmutableSet of all ReservedLists associated with this tld.
> ```

TLD is an acronym and should be capitalized as such (as it is elsewhere).


<!-- Sent from Reviewable.io -->

2021-06-15 22:34 UTC, CydeWeys approved these changes
LGTM pending resolution of Mike's comments.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1208#-:-McGnvGLCrHD7jjYxQOw:b-2diwlb)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @mindhog and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-06-16 14:47 UTC, mindhog commented
Following up on this because I don't see my comment in reviewable (it's still visible in the PR history on github).  TL;DR -- with the conversion code you've added, you don't really need to do a data migration: you could `@Ignore` the new fields, remove the scrap command and be done with it :-)

I don't feel strongly about this -- if you want to migrate this in datastore, I'm otherwise basically ok with this PR.

2021-06-16 17:52 UTC, mindhog approved these changes
Ah, I see.  This makes sense now, thanks for checking!

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1208#-:-McKwjLr3JuQCp6hVxln:bzenz50)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-06-16 19:13 UTC, merged