Make SQL queries return scrollable results
google/nomulus pull request #1214
Opened 2021-06-22 04:49 UTC by weiminyu

With Postgresql, we must override the default fetchSize (0) to enable
scrollable result sets. Previously we only did this in QueryComposer.

In this change we enable scrollable results for all queries by default.
We also provide a helper function
(JpaTransactionManager.setQueryFetchSize) that can override the default.

2021-06-22 17:12 UTC, mindhog requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1214)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jianglai and @weiminyu)

___
*[core/src/main/java/google/registry/beam/common/JpaDemoPipeline.java, line 46 at r1](https://reviewable.io/reviews/google/nomulus/1214#-Mcoh6VjC5C5zH1IdXOf:-Mcoh6VjC5C5zH1IdXOg:b-dqsg5m) ([raw file](https://github.com/google/nomulus/blob/c9f5334d988c9af410bd50e98324f201275fd356/core/src/main/java/google/registry/beam/common/JpaDemoPipeline.java#L46)):*
> ```Java
>             RegistryJpaIO.read(
>                 () -> CriteriaQueryBuilder.create(ContactResource.class).build(),
>                 ContactResource::getRepoId))
> ```

Is this change related to the bulk of this PR?


<!-- Sent from Reviewable.io -->

2021-06-22 18:17 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1214)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jianglai and @mindhog)

___
*[core/src/main/java/google/registry/beam/common/JpaDemoPipeline.java, line 46 at r1](https://reviewable.io/reviews/google/nomulus/1214#-Mcoh6VjC5C5zH1IdXOf:-Mcow2XH5UKojPBYyJla:bmhya3a) ([raw file](https://github.com/google/nomulus/blob/c9f5334d988c9af410bd50e98324f201275fd356/core/src/main/java/google/registry/beam/common/JpaDemoPipeline.java#L46)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Is this change related to the bulk of this PR?
</blockquote></details>

Updated class doc. With this change this class can be used to test RegistryJpaIO in the future.


<!-- Sent from Reviewable.io -->

2021-06-22 18:21 UTC, mindhog approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @mindhog)



<!-- Sent from Reviewable.io -->

2021-06-22 20:04 UTC, jianglai reviewed
Is there a way to test this?

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1214#-:-McpJ_vSDDj93twPYohk:b-pi3xet)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-06-22 20:08 UTC, weiminyu reviewed
Yes, by running the demo pipeline against a db with a lot of contacts. 

Without setting the fetchSize, the job will enter into a crash retry loop because workers are killed for GC thrashing.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1214#-:-McpJokl2HNSAKABWnB3:bd5yp5p)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-06-23 01:20 UTC, jianglai approved these changes
Is it getting tested right now? If not can we add a TODO?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1214#-:-McqRyZFCbIOKUvHzAUt:b-cdewyj)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-06-23 02:13 UTC, weiminyu reviewed
No easy way to test for presubmits. Need to populate a postgres db with gigs of data.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1214#-:-Mcqd4Tr7ILjIHksQYVQ:b-og741j)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-06-23 02:13 UTC, merged