Add SQL functionality to DeleteProberDataAction
google/nomulus pull request #1218
Opened 2021-06-24 18:04 UTC by gbrodman

This includes a change to how the JPA transaction manager handles
existence and load checks for entities with compound IDs. Previously, we
relied on the fields all being named the same in the ID entity and the
parent entity. This didn't work for History objects (e.g. DomainHistory)
so existence checks were broken. Now, we use the methods the same way
that Hibernate does (if possible).

2021-06-28 20:49 UTC, jianglai requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 111 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdIocWc6IXtmxlXfs9S:-MdIocWc6IXtmxlXfs9T:b-yylncm) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L111)):*
> ```
> registr
> ```
registry
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJJwVl5NGI2f8dC8LB:-MdJJwVm0xS6QH1C2YiN:boz8695) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L149)):*
> ```
>   tm().transact(() -> deleteProberDataSql(proberRoidSuffixes, deletableTlds));
> ```
Should we break out the delete into multiple transactions, at least one per TLD? In a similar migration Mike pointed out that there's a limit on how many entities can be modified per transaction. It may even make sense to do it one transaction per domain, but I don't know if that'll add too much overhead. Although given that this action is running in the backend and not time sensitive it probably is OK.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 161 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJM881DMnAJluQM9e6:-MdJM881DMnAJluQM9e7:bvnvwvr) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L161)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     String roidSuffix = Iterables.getLast(Splitter.on('-').split(domain.getRepoId()));
>     if (!proberRoidSuffixes.contains(roidSuffix)) {
>       return;
>     }
>     DateTime now = tm().getTransactionTime();
>     if (now.isBefore(domain.getCreationTime().plus(DOMAIN_USED_DURATION))) {
>       return;
>     }
> ```
</details>

These checks can be done as part of the query in `loadRelevantDomainsSql`, right?
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 282 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJKVo83_AnNWdAYyHK:-MdJKVo83_AnNWdAYyHL:bnm9ncr) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L282)):*
> ```
> .setParameter("nic", "nic.%")
> ```
Is there a reason to not just hard-code this?
___
*[core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java, line 653 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdIQN7N92fpIrxCMZ1l:-MdIQN7O2Aj36atl5exz:b-dkpdca) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L653)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>               try {
>                 Method method = idContainer.getClass().getDeclaredMethod(methodName);
>                 method.setAccessible(true);
>                 Object idValue = method.invoke(idContainer);
>                 return new EntityId(attribute.getName(), idValue);
>               } catch (NoSuchMethodException
>                   | IllegalAccessException
>                   | InvocationTargetException e) {
>                 String idName = attribute.getName();
>                 Object idValue = getFieldValue(idContainer, idName);
>                 return new EntityId(idName, idValue);
> ```
</details>

Might be easier to understand if we only set the values of `idName` and `idValue` in the try-catch block and have a single return statement at the end.
___
*[core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java, line 807 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdIOsZuC7VpJRqHLAXZ:-MdIOsZuC7VpJRqHLAX_:b-h2ovea) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java#L807)):*
> ```
> getNameField
> ```
Shouldn't all these methods end without Field?


<!-- Sent from Reviewable.io -->

2021-06-28 21:34 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 6 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 111 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdIocWc6IXtmxlXfs9S:-MdJSs4B491_N8vctbTY:byg9odt) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L111)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> registr
> ```
registry
</blockquote></details>

womp :) 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJJwVl5NGI2f8dC8LB:-MdJTkux6EqOa0XkFb2Y:b-99h7ju) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L149)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>   tm().transact(() -> deleteProberDataSql(proberRoidSuffixes, deletableTlds));
> ```
Should we break out the delete into multiple transactions, at least one per TLD? In a similar migration Mike pointed out that there's a limit on how many entities can be modified per transaction. It may even make sense to do it one transaction per domain, but I don't know if that'll add too much overhead. Although given that this action is running in the backend and not time sensitive it probably is OK.
</blockquote></details>

Is there such a limit in SQL? I wasn't aware of one in SQL, only in Datastore. If so yeah we should break it out. 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 161 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJM881DMnAJluQM9e6:-MdJWnPe4rrqcDg7YfsO:bc2xx49) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L161)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>     String roidSuffix = Iterables.getLast(Splitter.on('-').split(domain.getRepoId()));
>     if (!proberRoidSuffixes.contains(roidSuffix)) {
>       return;
>     }
>     DateTime now = tm().getTransactionTime();
>     if (now.isBefore(domain.getCreationTime().plus(DOMAIN_USED_DURATION))) {
>       return;
>     }
> ```
These checks can be done as part of the query in `loadRelevantDomainsSql`, right?
</blockquote></details>

Yes, this can all be refactored. Done. 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 282 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJKVo83_AnNWdAYyHK:-MdJTE7D9fBWmj4Em51W:b-nulyt2) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L282)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> .setParameter("nic", "nic.%")
> ```
Is there a reason to not just hard-code this?
</blockquote></details>

nah, I think this was an accidental remnant of thinking about including the TLD(s) in particular 
___
*[core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java, line 653 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdIQN7N92fpIrxCMZ1l:-MdJXreS3huTNzYqLQFr:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L653)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>               try {
>                 Method method = idContainer.getClass().getDeclaredMethod(methodName);
>                 method.setAccessible(true);
>                 Object idValue = method.invoke(idContainer);
>                 return new EntityId(attribute.getName(), idValue);
>               } catch (NoSuchMethodException
>                   | IllegalAccessException
>                   | InvocationTargetException e) {
>                 String idName = attribute.getName();
>                 Object idValue = getFieldValue(idContainer, idName);
>                 return new EntityId(idName, idValue);
> ```
Might be easier to understand if we only set the values of `idName` and `idValue` in the try-catch block and have a single return statement at the end.
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java, line 807 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdIOsZuC7VpJRqHLAXZ:-MdJShSEAMgVesm94cd_:bo13zlx) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java#L807)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> getNameField
> ```
Shouldn't all these methods end without Field?
</blockquote></details>

No, we need the getter to match the name of the field that exists inside the ID class (DomainHistory and the other similar history classes have the same structure) 


<!-- Sent from Reviewable.io -->

2021-06-29 13:34 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 5 of 9 files reviewed, 6 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJJwVl5NGI2f8dC8LB:-MdMyXSu0VDaUr5nO-aB:bs3ix3t) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L149)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Is there such a limit in SQL? I wasn't aware of one in SQL, only in Datastore. If so yeah we should break it out. 
</blockquote></details>

This needs to be using a non-replaying transaction like the corresponding action on Datastore.


<!-- Sent from Reviewable.io -->

2021-06-29 14:03 UTC, jianglai requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJJwVl5NGI2f8dC8LB:-MdMyKaN3-vALD6FaJfb:b-t3gfzd) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L149)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This needs to be using a non-replaying transaction like the corresponding action on Datastore.
</blockquote></details>

Per the discussion on chat, there doesn't seem to be such a limit? But if we write too much in a transaction that may be a problem for SQL -> Ofy replay. We should either break it up or find a way to not have these transactions replayed.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 161 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJM881DMnAJluQM9e6:-MdMvR900olPX6Ncktj7:b-e3krey) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L161)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yes, this can all be refactored. Done. 
</blockquote></details>

It should be converted to actual SQL query, not a filter on the results. It's more efficient to have the SQL engine to handle this. We should check if the fields that we filter on are indexed. 
___
*[core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java, line 807 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdIOsZuC7VpJRqHLAXZ:-MdMrQsF6nSS3pnogbCl:b-mdjj3t) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java#L807)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

No, we need the getter to match the name of the field that exists inside the ID class (DomainHistory and the other similar history classes have the same structure) 
</blockquote></details>

So this is only testing that the field itself can be of a different name than what the getter would have suggested?


<!-- Sent from Reviewable.io -->

2021-06-29 18:27 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJJwVl5NGI2f8dC8LB:-MdNuSUzDrJVWtb2Wg7i:b-hc21oc) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L149)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Per the discussion on chat, there doesn't seem to be such a limit? But if we write too much in a transaction that may be a problem for SQL -> Ofy replay. We should either break it up or find a way to not have these transactions replayed.
</blockquote></details>

Likely both. Split into multiple transactions, and used the `*withoutBackup` methods. 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 161 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJM881DMnAJluQM9e6:-MdNuH576iPTzaQIf8QC:big7yvn) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L161)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It should be converted to actual SQL query, not a filter on the results. It's more efficient to have the SQL engine to handle this. We should check if the fields that we filter on are indexed. 
</blockquote></details>

It's a bit of a hairy query as you can see, but done. All are indexed except the subordinate hosts field but that shouldn't really matter since that shouldn't be a heavy filter. 
___
*[core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java, line 807 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdIOsZuC7VpJRqHLAXZ:-MdNFcNf8ugfjqBHtbti:b6cjstq) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java#L807)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

So this is only testing that the field itself can be of a different name than what the getter would have suggested?
</blockquote></details>

Yeah basically, that's what happens in the history classes.


<!-- Sent from Reviewable.io -->

2021-06-29 21:30 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 8 of 9 files reviewed, 10 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJJwVl5NGI2f8dC8LB:-MdOd1P_5K4V3EtEA5pE:bcdxf9y) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L149)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Likely both. Split into multiple transactions, and used the `*withoutBackup` methods. 
</blockquote></details>

This isn't split into multiple transactions; there's still a wrapping transaction on this line.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 156 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOd8KQ3BPHK2bdMBwC:-MdOd8KQ3BPHK2bdMBwD:b7m5bd) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L156)):*
> ```Java
>   private void deleteProberDataSql(
>       ImmutableSet<String> deletableTlds, ImmutableSet<String> proberRoidSuffixes) {
>     loadRelevantDomainsSql(deletableTlds, proberRoidSuffixes).forEach(this::deleteDomain);
> ```

What is the point of a one-line helper method?  Just inline it.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 160 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOdh6Q2SQbYKCw01fv:-MdOdh6Q2SQbYKCw01fw:b6t5vhn) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L160)):*
> ```Java
> 
>   private void deleteDomain(DomainBase domain) {
>     tm().transact(
> ```

Doesn't this need to be `transactWithoutBackup()`?  JpaTransactionManager's `deleteWithoutBackup()` doesn't do anything special -- it just calls `delete()`.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 183 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOe84wDirxu3hN_y21:-MdOe84wDirxu3hN_y22:b-xotokl) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L183)):*
> ```Java
>   private void hardDeleteDomainSql(DomainBase domain, DateTime now) {
>     // Delete billing events, history objects, poll messages, subordinate hosts, and the domain
>     getBillingEventsForDomain(domain).forEach(this::hardDeleteIfNotDryRun);
> ```

Is it the right thing to do to call delete individually on all of these rather than accumulating them in a collection and calling a single bulk `delete(Iterable)` method?  I'd wager it's not.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 205 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOfApzCcKmYUASH6gY:-MdOfApzCcKmYUASH6gZ:b-88gfvy) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L205)):*
> ```Java
>   private static void softDeleteDomain(
>       DomainBase domain, String registryAdminRegistrarId, DnsQueue localDnsQueue) {
>     tm().transactNew(
> ```

Wrong transaction type to do this without transaction logs.

Also why are you even starting a transaction here if the callsite also has a transaction?  Sit back, look at all this stuff more carefully, and plan exactly which *one* place the transaction will be declared and stick with it.  You currently have three layers of wrapping transactions in this call path.  Makes things hard to reason about and you're not doing what you intend to be doing here.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 248 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeNgnAnYwgr0vgllB:-MdOeNgnAnYwgr0vgllC:b-mxkjcd) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L248)):*
> ```Java
>     String repoId = domain.getRepoId();
>     return Streams.concat(
>         tm()
> ```

There's gotta be a better way to do this than concatenating the results of three separate queries together.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 252 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeVbm11kp-UrwpaK9:-MdOeVbm11kp-UrwpaKA:b-7i9mc9) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L252)):*
> ```Java
>             .where("domainRepoId", Comparator.EQ, repoId)
>             .stream()
>             .map(BillingEvent.OneTime::createVKey),
> ```

Wait, you're loading these into memory and then converting them to a `VKey`?  Seems wasteful.  Load the IDs to begin with, not the entire entities that you're not doing anything with.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 282 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOefGb-FgAXlZCl7Vp:-MdOefGb-FgAXlZCl7Vq:b-cwh2vd) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L282)):*
> ```Java
>                 jpaTm()
>                     .query(
>                         "FROM Domain d WHERE d.tld IN :tlds AND d.fullyQualifiedDomainName NOT"
> ```

Needs to be a static final String to pass presubmit rules.  That would also help it to be more legible since it would have less indentation and thus more characters per line with fewer lines total.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 299 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOevl424TyjgUlJqxR:-MdOevl5ErfG4L1QL9_K:b-pov4sm) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L299)):*
> ```Java
>                         domain ->
>                             proberRoidSuffixes.contains(
>                                 Iterables.getLast(Splitter.on('-').split(domain.getRepoId()))))
> ```

Why is this query being done in memory rather than as part of the query?  Seems inefficient.


<!-- Sent from Reviewable.io -->

2021-06-29 21:32 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 8 of 9 files reviewed, 10 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 183 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOe84wDirxu3hN_y21:-MdOfp2Y9GzYFgSMoXja:b-ukqeqi) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L183)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is it the right thing to do to call delete individually on all of these rather than accumulating them in a collection and calling a single bulk `delete(Iterable)` method?  I'd wager it's not.
</blockquote></details>

(It occurs to me that while the current implementation of `delete(Iterable)` might still do them all individually, this won't necessarily be the case in the future if we realize we need to be smarter about that for performance reasons.)


<!-- Sent from Reviewable.io -->

2021-06-30 15:32 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 8 of 9 files reviewed, 10 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJJwVl5NGI2f8dC8LB:-MdSHA3TBqmbwiZ7W8dj:bi79xrn) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L149)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This isn't split into multiple transactions; there's still a wrapping transaction on this line.
</blockquote></details>

Done, it was an accident to leave it in.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 156 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOd8KQ3BPHK2bdMBwC:-MdSHAQO9TlFXhldRGtK:b-896fix) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L156)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What is the point of a one-line helper method?  Just inline it.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 160 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOdh6Q2SQbYKCw01fv:-MdSQGv_EV1V8HJza2HS:bkjlw4r) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L160)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Doesn't this need to be `transactWithoutBackup()`?  JpaTransactionManager's `deleteWithoutBackup()` doesn't do anything special -- it just calls `delete()`.
</blockquote></details>

No, because that method does not exist. 

The fact that `deleteWithoutBackup` does nothing special was what we were all discussing on chat the other day, that there needs to be some way for SQL->Datastore replays to not occur for these methods, but none currently exists. 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 183 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOe84wDirxu3hN_y21:-MdSVNjKAdRVnWA65s7Q:b-j8upyp) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L183)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

(It occurs to me that while the current implementation of `delete(Iterable)` might still do them all individually, this won't necessarily be the case in the future if we realize we need to be smarter about that for performance reasons.)
</blockquote></details>

Yeah we can do that, even if it doesn't really change anything now. I didn't think that efficiency was a particular concern with this action.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 205 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOfApzCcKmYUASH6gY:-MdSPHtR701P0ughuZ8A:b-biu7j9) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L205)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Wrong transaction type to do this without transaction logs.

Also why are you even starting a transaction here if the callsite also has a transaction?  Sit back, look at all this stuff more carefully, and plan exactly which *one* place the transaction will be declared and stick with it.  You currently have three layers of wrapping transactions in this call path.  Makes things hard to reason about and you're not doing what you intend to be doing here.
</blockquote></details>

1. Not the wrong transaction type, there is no such thing as `transactWithoutBackup`
2. The callsite didn't have a transaction in the Datastore world so it needed one here, though it does now. 
3. There were only two actual transaction layers (one was a typo which was my bad), and that was because Datastore is a lot more lenient about when transactions are required. Either way, this is done. 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 248 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeNgnAnYwgr0vgllB:-MdSLeQt-Sk0HLR5qf8l:bl0sui3) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L248)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There's gotta be a better way to do this than concatenating the results of three separate queries together.
</blockquote></details>

I'm open to suggestions but unless you're loading by key I don't believe you can specify an abstract class (I've tried using loadAllOf with BillingEvents, and this is roughly what DatabaseHelper does) 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 252 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeVbm11kp-UrwpaK9:-MdSOg40CULl9q-e_3SE:beck4p6) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L252)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Wait, you're loading these into memory and then converting them to a `VKey`?  Seems wasteful.  Load the IDs to begin with, not the entire entities that you're not doing anything with.
</blockquote></details>

It's cleaner code with fewer hardcoded strings to do it this previous way and I didn't really think we cared about performance here but all right 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 282 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOefGb-FgAXlZCl7Vp:-MdSHCsR-fvTOxvVDJlV:b-ea3nhg) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L282)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs to be a static final String to pass presubmit rules.  That would also help it to be more legible since it would have less indentation and thus more characters per line with fewer lines total.
</blockquote></details>

Not actually true re: presubmit rules (see that the only failing tests are some flakes(?)), but yeah we can have it be a static var anyway for length purposes.

There's an argument to be made that having the query definition exist close to the usage is helpful for variable substitution purposes, but Hibernate will let us know if we forget a variable / define an extra variable in the future. 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 299 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOevl424TyjgUlJqxR:-MdSK-2EBkv7Ku04niDq:bh6436l) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L299)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why is this query being done in memory rather than as part of the query?  Seems inefficient.
</blockquote></details>

actually should this even be necessary at all? It exists in the Datastore code but it's just verifying that the domain's ROID ends with a suffix associated with one of the tlds-to-delete, and since we're restricting our search to those TLDs anyway this should never be false 


<!-- Sent from Reviewable.io -->

2021-07-01 14:39 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 7 of 9 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 205 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOfApzCcKmYUASH6gY:-MdXV_iP496bSIocRuKW:b6i9zuc) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L205)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

1. Not the wrong transaction type, there is no such thing as `transactWithoutBackup`
2. The callsite didn't have a transaction in the Datastore world so it needed one here, though it does now. 
3. There were only two actual transaction layers (one was a typo which was my bad), and that was because Datastore is a lot more lenient about when transactions are required. Either way, this is done. 

</blockquote></details>

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java;l=161


<!-- Sent from Reviewable.io -->

2021-07-01 14:54 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 7 of 9 files reviewed, 9 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 205 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOfApzCcKmYUASH6gY:-MdXXAFN88pP7WcCRAy0:bqjw9n7) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L205)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java;l=161
</blockquote></details>

ugh i wasn't added on that PR so I didn't see it, and the method didn't exist as of a couple days ago 


<!-- Sent from Reviewable.io -->

2021-07-08 15:08 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 3 of 9 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 160 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOdh6Q2SQbYKCw01fv:-Me5dvJX9AD1fsjKI45Y:b-8bkuuy) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L160)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

No, because that method does not exist. 

The fact that `deleteWithoutBackup` does nothing special was what we were all discussing on chat the other day, that there needs to be some way for SQL->Datastore replays to not occur for these methods, but none currently exists. 
</blockquote></details>

So are you working on it in this PR or in a separate one?  Because that lack is blocking this.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 96 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5dHDf7FmOlADbG8jV:-Me5dHDf7FmOlADbG8jW:b6wuto9) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L96)):*
> ```Java
>    */
>   private static final Duration DOMAIN_USED_DURATION = Duration.standardHours(1);
>   /**
> ```

Missing newline.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 109 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5eRQO3668oCOpFwtK:-Me5eRQO3668oCOpFwtL:b-ywaj9m) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L109)):*
> ```Java
>   // 1. Be in one of the prober TLDs
>   // 2. Not be a nic domain
>   // 3. Have no subordinate hosts
> ```

Is there a sensible assertion to be made on the `currentSponsorClientId` as well?  Just for extra safety?
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 112 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5dR6I0g6TCh1H5RIz:-Me5dR6I0g6TCh1H5RJ-:b-i5zz7v) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L112)):*
> ```Java
>   // 4. Not still be used (within an hour of creation time)
>   // 5. Either be active (creationTime <= now < deletionTime) or have been deleted a while ago (this
>   // prevents accidental double-map with the same key from immediately deleting active domains)
> ```

Nit, but, there should be some spaces added to the beginning of this comment so it's clear it's part of 5.


<!-- Sent from Reviewable.io -->

2021-07-08 15:12 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 3 of 9 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 160 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOdh6Q2SQbYKCw01fv:-Me5fCA0Cn92rcU6b4Ih:bsoenrm) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L160)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

So are you working on it in this PR or in a separate one?  Because that lack is blocking this.
</blockquote></details>

Oh I see you switched to using it now.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 167 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5erQo-GV1UjcQGLDD:-Me5erQo-GV1UjcQGLDE:b-ggq3p4) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L167)):*
> ```Java
>   }
> 
>   private void deleteDomain(DomainBase domain) {
> ```

I'm still worried about the performance about this.  You're taking what had been a mapreduce in GAE, that ran on many shards, and converting it into an action that runs in only one thread that deletes one domain at a time, in a bunch of serial transactions.  I think this is going to slow the action way, way down.  It needs to be processing a lot more than one domain at a time to even remotely have a chance of keeping up with the pace of the Datastore implementation.  I think you need batching at the very minimum.


<!-- Sent from Reviewable.io -->

2021-07-08 15:27 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 3 of 9 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 185 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5fNDEAyQTmU8HK3Yk:-Me5fNDEAyQTmU8HK3Yl:b-afej2f) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L185)):*
> ```Java
>                 }
>               } else {
>                 hardDeleteDomainSql(domain, now);
> ```

Is this not missing a dry-run check here?  Surely it shouldn't be hard-deleting domains when run in dry-run mode?
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 229 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5fls_EmoI8ho3_DTE:-Me5fls_EmoI8ho3_DTF:bfd67a6) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L229)):*
> ```Java
>     // runs anyway.
>     tm().putAllWithoutBackup(ImmutableList.of(deletedDomain, historyEntry));
>     updateForeignKeyIndexDeletionTime(deletedDomain);
> ```

It seems like a mistake to be calling this method in Cloud SQL operation mode.
___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 340 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5gVeW02nLHDr68hVn:-Me5gVeW02nLHDr68hVo:bfoppjg) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L340)):*
> ```Java
>   private static void assertNotDeleted(Iterable<ImmutableObject> entities) {
>     for (ImmutableObject entity : entities) {
>       assertThat(existsInDatabase(entity)).isTrue();
> ```

These assertions don't seem like they generate useful exception messages if they aren't met; they're just gonna say something like "Expected: true, but got: false".  You either need to write a new Truth `Subject` that has better error messages for checking the existence of given entities in the DB, or maybe adding a method to `ImmutableObjectSubject` is a better fit, , or at least modify the `existsInDatabase` method to throw useful messages (i.e. `assertWithMessage`).

https://truth.dev/faq#full-chain


<!-- Sent from Reviewable.io -->

2021-07-08 15:34 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 3 of 9 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 248 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeNgnAnYwgr0vgllB:-Me5jKxC2jsr3hYB8DyM:bac8ivc) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L248)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I'm open to suggestions but unless you're loading by key I don't believe you can specify an abstract class (I've tried using loadAllOf with BillingEvents, and this is roughly what DatabaseHelper does) 
</blockquote></details>

Why are you loading the IDs at all though?  Why not just running something like the following SQL command?

```
DELETE FROM BillingEvent WHERE domainRepoId = :repoId
DELETE FROM BillingRecurrence WHERE domainRepoId = :repoId
DELETE FROM BillingCancellation WHERE domainRepoId = :repoId
```

I think there's still a lot of streamlining gains that can be had here, and the current code is still hewing too closely to a Datastore-specific pattern.

Deleting a bunch of test data shouldn't be _that_ hard.  It should just be a relatively small number of `DELETE` statements, one for each table, and then have a bunch of those batched up into a single larger transaction for efficiency.

I'm starting to think this action would really benefit from a design document outlining the approach.


<!-- Sent from Reviewable.io -->

2021-07-08 15:36 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 3 of 9 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 248 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeNgnAnYwgr0vgllB:-Me5kgKk8SnbEHnBU78f:b-yodil1) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L248)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why are you loading the IDs at all though?  Why not just running something like the following SQL command?

```
DELETE FROM BillingEvent WHERE domainRepoId = :repoId
DELETE FROM BillingRecurrence WHERE domainRepoId = :repoId
DELETE FROM BillingCancellation WHERE domainRepoId = :repoId
```

I think there's still a lot of streamlining gains that can be had here, and the current code is still hewing too closely to a Datastore-specific pattern.

Deleting a bunch of test data shouldn't be _that_ hard.  It should just be a relatively small number of `DELETE` statements, one for each table, and then have a bunch of those batched up into a single larger transaction for efficiency.

I'm starting to think this action would really benefit from a design document outlining the approach.
</blockquote></details>

To put in other words, imagine if you rewrote this entire delete prober data functionality from scratch, in a completely separate action, rather than trying to reuse a bunch of the Datastore implementation bits.  What would it look like?


<!-- Sent from Reviewable.io -->

2021-07-14 14:46 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 2 of 9 files reviewed, 10 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 248 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeNgnAnYwgr0vgllB:-MeWkTph-oX2lEcE3x4y:bbeq34i) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L248)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

To put in other words, imagine if you rewrote this entire delete prober data functionality from scratch, in a completely separate action, rather than trying to reuse a bunch of the Datastore implementation bits.  What would it look like?
</blockquote></details>

Fair point -- the main question then becomes where to draw the SQL-transaction boundary. Currently it's at one transaction per domain

I'm not sure it requires a design document -- I think the version I have now is much simpler in that it loads the domain then just deletes from the other tables based on that domain's repoId (or subordinate hosts). 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 96 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5dHDf7FmOlADbG8jV:-Me_MkA9DoPfFSRCfk-c:b-896fix) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L96)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Missing newline.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 109 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5eRQO3668oCOpFwtK:-Me_MKFU3htxFkh8dLlk:bm13y4r) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L109)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is there a sensible assertion to be made on the `currentSponsorClientId` as well?  Just for extra safety?
</blockquote></details>

I don't know of one, but I don't know which registrars the prober uses. 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 167 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5erQo-GV1UjcQGLDD:-MeWo7Oo9cV_bZcvuKet:bz2640x) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L167)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I'm still worried about the performance about this.  You're taking what had been a mapreduce in GAE, that ran on many shards, and converting it into an action that runs in only one thread that deletes one domain at a time, in a bunch of serial transactions.  I think this is going to slow the action way, way down.  It needs to be processing a lot more than one domain at a time to even remotely have a chance of keeping up with the pace of the Datastore implementation.  I think you need batching at the very minimum.
</blockquote></details>

Yeah, looks like the last run had roughly 79k domains hard-deleted (https://backend-dot-domain-registry.appspot.com/_ah/pipeline/status.html?root=dea08dc5-3d9c-409c-853f-6f6953db18ed#pipeline-f669f2bb-746d-42d6-baa2-57a06b240c4e) so.....yeah, batching!

side note, that also shows <1k domains soft-deleted and a non-meaningful number of other domains processed but skipped 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 185 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5fNDEAyQTmU8HK3Yk:-MeWezk6B6Y7byEB5yYt:b86gvsv) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L185)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is this not missing a dry-run check here?  Surely it shouldn't be hard-deleting domains when run in dry-run mode?
</blockquote></details>

It calls the `hardDeleteIfNotDryRun` methods but eh we are revisiting this all anyway, this is now moot
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 229 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5fls_EmoI8ho3_DTE:-MeWgcVJ-bc-R8sBSfyH:b-7ydeis) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L229)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It seems like a mistake to be calling this method in Cloud SQL operation mode.
</blockquote></details>

Eh, it's a no-op in SQL and it allows us to use the same code 
___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 340 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5gVeW02nLHDr68hVn:-Me_SK3o8IYfmBo9qIeO:b-tmredb) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L340)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These assertions don't seem like they generate useful exception messages if they aren't met; they're just gonna say something like "Expected: true, but got: false".  You either need to write a new Truth `Subject` that has better error messages for checking the existence of given entities in the DB, or maybe adding a method to `ImmutableObjectSubject` is a better fit, , or at least modify the `existsInDatabase` method to throw useful messages (i.e. `assertWithMessage`).

https://truth.dev/faq#full-chain
</blockquote></details>

Done, since this is about simple existence I don't think we need a custom subject.


<!-- Sent from Reviewable.io -->

2021-07-14 19:15 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 2 of 9 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 252 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeVbm11kp-UrwpaK9:-MeaQo_v7ETFKq3L4mLE:bbd8lg8) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L252)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It's cleaner code with fewer hardcoded strings to do it this previous way and I didn't really think we cared about performance here but all right 
</blockquote></details>

This new version is an improvement, both from a performance perspective but also from a code readbility / "does the right thing in an obvious way" perspective.


<!-- Sent from Reviewable.io -->

2021-07-14 19:17 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 2 of 9 files reviewed, 10 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 243 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaR_jGABiestTPi1aE:-MeaR_jGABiestTPi1aF:b-q7fcoj) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L243)):*
> ```Java
>             () -> {
>               DateTime now = tm().getTransactionTime();
>               return ImmutableList.copyOf(
> ```

No `LIMIT` on this query?  No batching?  Seems to me like it needs to use a cursor/results stream rather than trying to load all domain names into memory simultaneously, which isn't guaranteed to be possible.  If you're running this for the first time in awhile on a given environment then it might have millions of entities to delete.


<!-- Sent from Reviewable.io -->

2021-07-14 19:23 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 2 of 9 files reviewed, 12 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 268 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaTKutAdMlJbyCPySI:-MeaTKutAdMlJbyCPySJ:bdr0que) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L268)):*
> ```Java
>             DateTime.now(UTC).minusYears(1));
>     runMapreduce();
>     assertThat(existsInDatabase(domainWithSubord)).isTrue();
> ```

These don't have useful error messages.
___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 339 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaShgB6cg8F_Q1LB5R:-MeaShgB6cg8F_Q1LB5S:b-grqym2) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L339)):*
> ```Java
>   }
> 
>   private static void assertNotDeleted(Iterable<ImmutableObject> entities) {
> ```

`assertDeleted` and `assertNotDeleted` seem like negatively phrased statements, that don't actually match up with the corresponding error messages which are positively phrased statements (which is easier to reason about).  I'd make everything a positively phrased statement -- `assertExists()` and `assertAbsent()` (or similar).  Because you aren't specifically asserting here that a given entity was *deleted* -- it's possible it actually never existed in the first place, which should be a different failure rather than a success.
___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 1353 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaTECn7XjUo-1TsZUx:-MeaTECn7XjUo-1TsZUy:bxc3cm6) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/testing/DatabaseHelper.java#L1353)):*
> ```Java
>   }
> 
>   public static boolean existsInDatabase(Object object) {
> ```

Missing Javadoc, also, this seems like a pretty simple function that doesn't necessarily need to exist.


<!-- Sent from Reviewable.io -->

2021-07-14 19:33 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 2 of 9 files reviewed, 13 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 339 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaVaMBAMlOVW1GdlAh:-MeaVaMC0Z2B_pA5Vr7w:b-vhrv2l) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L339)):*
> ```Java
>   }
> 
>   private static void assertNotDeleted(Iterable<ImmutableObject> entities) {
> ```

Also I just realized that these don't work correctly in that they will thrown on the first one that doesn't exist rather than alerting on all that don't exist.  If it's gonna take an iterable to assert over then it need to report on all that don't exist.


<!-- Sent from Reviewable.io -->

2021-07-14 19:35 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 2 of 9 files reviewed, 13 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 339 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaVaMBAMlOVW1GdlAh:-MeaVrUBDum0YoRidVKh:b-mi5ewb) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L339)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Also I just realized that these don't work correctly in that they will thrown on the first one that doesn't exist rather than alerting on all that don't exist.  If it's gonna take an iterable to assert over then it need to report on all that don't exist.
</blockquote></details>

The pattern used should be something like `assertThat(reloadEntities(entities)).containsExactly(entities);`, maybe also with a custom message as necessary.


<!-- Sent from Reviewable.io -->

2021-07-16 15:54 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 2 of 9 files reviewed, 12 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 243 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaR_jGABiestTPi1aE:-Mek-Xk5AOkmM15Y016_:bkdmmvs) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L243)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

No `LIMIT` on this query?  No batching?  Seems to me like it needs to use a cursor/results stream rather than trying to load all domain names into memory simultaneously, which isn't guaranteed to be possible.  If you're running this for the first time in awhile on a given environment then it might have millions of entities to delete.
</blockquote></details>

Good point. Done. 
___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 268 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaTKutAdMlJbyCPySI:-MefiAtr5W3msAvc1WE4:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L268)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These don't have useful error messages.
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 339 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaVaMBAMlOVW1GdlAh:-Mefgj8HAiZB21f3LyrV:bo5jped) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L339)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The pattern used should be something like `assertThat(reloadEntities(entities)).containsExactly(entities);`, maybe also with a custom message as necessary.
</blockquote></details>

This feels a bit like we're nitpicking previously existing code, but sure 
___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 339 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaShgB6cg8F_Q1LB5R:-MefhAIo7D9LsDLhwAlt:bo5jped) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L339)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`assertDeleted` and `assertNotDeleted` seem like negatively phrased statements, that don't actually match up with the corresponding error messages which are positively phrased statements (which is easier to reason about).  I'd make everything a positively phrased statement -- `assertExists()` and `assertAbsent()` (or similar).  Because you aren't specifically asserting here that a given entity was *deleted* -- it's possible it actually never existed in the first place, which should be a different failure rather than a success.
</blockquote></details>

This feels a bit like we're nitpicking previously existing code, but sure 
___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 1353 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaTECn7XjUo-1TsZUx:-Mefgfcs97n1a64MUgYd:bq2lzku) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/testing/DatabaseHelper.java#L1353)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Missing Javadoc, also, this seems like a pretty simple function that doesn't necessarily need to exist.
</blockquote></details>

saves the transaction call, just like all the others. Added javadoc. 


<!-- Sent from Reviewable.io -->

2021-07-16 15:54 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 2 of 9 files reviewed, 12 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 243 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaR_jGABiestTPi1aE:-Mek0cpK6nw_TVsXjZdo:bqs0rqh) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L243)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Good point. Done. 
</blockquote></details>

oh and fwiw it's returning domains, not repo IDs, since we need to know info about the domain in order to process it 


<!-- Sent from Reviewable.io -->

2021-07-23 14:21 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 1 of 9 files reviewed, 10 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 65 at r8](https://reviewable.io/reviews/google/nomulus/1218#-MfIj86a18fGhmj6Jn1P:-MfIj86a18fGhmj6Jn1Q:bszed19) ([raw file](https://github.com/google/nomulus/blob/8cf88b7e18dc97d5051826a8367e5046d1dc7323/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L65)):*
> ```Java
>  * billing events, along with their ForeignKeyDomainIndex and EppResourceIndex entities.
>  *
>  * <p>See: https://www.youtube.com/watch?v=xuuv0syoHnM
> ```

Ah man, they removed the YouTube video.


<!-- Sent from Reviewable.io -->

2021-07-23 14:23 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 339 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaShgB6cg8F_Q1LB5R:-MfIjgQx8V4Yj7-B-_j8:b-8b6s9j) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L339)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This feels a bit like we're nitpicking previously existing code, but sure 
</blockquote></details>

It looked like it was new here.


<!-- Sent from Reviewable.io -->

2021-07-23 14:33 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 248 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeNgnAnYwgr0vgllB:-MfIkrCF17YUjAjExPqR:ba2il1v) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L248)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Fair point -- the main question then becomes where to draw the SQL-transaction boundary. Currently it's at one transaction per domain

I'm not sure it requires a design document -- I think the version I have now is much simpler in that it loads the domain then just deletes from the other tables based on that domain's repoId (or subordinate hosts). 
</blockquote></details>

A better way to do this might be to batch up the deletes and do a bunch at a time in a single `DELETE` call.  So rather than `DELETE FROM ____ WHERE domainRepoId = :repoId`, it'd be `WHERE domainRepoId IN :repoIds` for all the repo IDs in a batch.  Same for the other hard delete methods.

What do you think?


<!-- Sent from Reviewable.io -->

2021-07-23 14:34 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 109 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5eRQO3668oCOpFwtK:-MfImKPs7SBZNxyi32s6:bqfk85) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L109)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't know of one, but I don't know which registrars the prober uses. 
</blockquote></details>

Might be worth looking into what registrars the probers use.


<!-- Sent from Reviewable.io -->

2021-07-23 14:38 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 1 of 9 files reviewed, 8 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 177 at r8](https://reviewable.io/reviews/google/nomulus/1218#-MfInGIb6aBsVu-0Pp5G:-MfInGIb6aBsVu-0Pp5H:b-ah384p) ([raw file](https://github.com/google/nomulus/blob/7cd109874c9efa191c211acc909ab2f274b9fea9/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L177)):*
> ```Java
>       Lists.partition(nextBatch, DOMAIN_PROCESSING_BATCH_SIZE).forEach(this::processDomainBatch);
>       if (nextBatch.size() < DOMAIN_RETRIEVAL_BATCH_SIZE) {
>         // we can short-circuit if it's clear by the size that this was the last batch
> ```

I don't think this minor optimization merits the additional code complexity.  Plus, once you remove it, then the loop can be rewritten as a non-breaking, non-infinite loop like:

```
do {


} while (!nextBatch.isEmpty())
```


<!-- Sent from Reviewable.io -->

2021-07-23 14:57 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 1 of 9 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 184 at r8](https://reviewable.io/reviews/google/nomulus/1218#-MfIqtSXC8y1lAzJzmTc:-MfIqtSXC8y1lAzJzmTd:b-f0ahkm) ([raw file](https://github.com/google/nomulus/blob/7cd109874c9efa191c211acc909ab2f274b9fea9/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L184)):*
> ```Java
>   }
> 
>   private ImmutableList<DomainBase> nextDomainBatch(
> ```

This is going to load 10,000 `DomainBase` entities into memory at one go?  That seems way too many given the GAE 1GB memory limit for our instance size.

Why do there need to be two separate batch sizes anyway?  Why not just load up one batch at a time, delete them, then go on to the next?


<!-- Sent from Reviewable.io -->

2021-07-23 17:01 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 248 at r3](https://reviewable.io/reviews/google/nomulus/1218#-MdOeNgnAnYwgr0vgllB:-MfJ4lMaCdt9D1_MsOgO:bbzcjjp) ([raw file](https://github.com/google/nomulus/blob/9b88bd15c07099dcd997bae6b925f998a10239a0/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L248)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

A better way to do this might be to batch up the deletes and do a bunch at a time in a single `DELETE` call.  So rather than `DELETE FROM ____ WHERE domainRepoId = :repoId`, it'd be `WHERE domainRepoId IN :repoIds` for all the repo IDs in a batch.  Same for the other hard delete methods.

What do you think?
</blockquote></details>

Yeah, I think that makes sense 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 109 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5eRQO3668oCOpFwtK:-MfJIU7v0deVzFpOD-Yt:b-u3w2zr) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L109)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Might be worth looking into what registrars the probers use.
</blockquote></details>

Seems like, from https://playbooks.corp.google.com/domain_registry/procedures/how-to-setup-registry-blackbox-probers.md?cl=head, that we can add/remove probers without too much difficulty. 

Doing a `SELECT * FROM `domain-registry.latest_datastore_export.Registrar` WHERE type = 'MONITORING'` gives 28 results, unfortunately not all of them have the same naming pattern (and we probably don't want to rely on that anyway). It's probably not worth joining on the Registrar table to see if it's a MONITORING registrar type? 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 65 at r8](https://reviewable.io/reviews/google/nomulus/1218#-MfIj86a18fGhmj6Jn1P:-MfIvhby6dsAogACwBi1:bary0bk) ([raw file](https://github.com/google/nomulus/blob/8cf88b7e18dc97d5051826a8367e5046d1dc7323/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L65)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ah man, they removed the YouTube video.
</blockquote></details>

yeah i had the same reaction 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 177 at r8](https://reviewable.io/reviews/google/nomulus/1218#-MfInGIb6aBsVu-0Pp5G:-MfIw6YI9rTozq6QR1uE:bva6h4z) ([raw file](https://github.com/google/nomulus/blob/7cd109874c9efa191c211acc909ab2f274b9fea9/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L177)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I don't think this minor optimization merits the additional code complexity.  Plus, once you remove it, then the loop can be rewritten as a non-breaking, non-infinite loop like:

```
do {


} while (!nextBatch.isEmpty())
```
</blockquote></details>

fair enough, done 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 184 at r8](https://reviewable.io/reviews/google/nomulus/1218#-MfIqtSXC8y1lAzJzmTc:-MfIw8Ag3TwgF4p6cRsa:b-3sfck6) ([raw file](https://github.com/google/nomulus/blob/7cd109874c9efa191c211acc909ab2f274b9fea9/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L184)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is going to load 10,000 `DomainBase` entities into memory at one go?  That seems way too many given the GAE 1GB memory limit for our instance size.

Why do there need to be two separate batch sizes anyway?  Why not just load up one batch at a time, delete them, then go on to the next?
</blockquote></details>

It's really only one gigabyte? oof yeah it should be smaller then, and then we can have just one batch size of 1k

per batch:
open transaction
load domains
process soft deletions
process hard deletions
close transaction 
___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 339 at r6](https://reviewable.io/reviews/google/nomulus/1218#-MeaShgB6cg8F_Q1LB5R:-MfJ4qfZ0mLCARUzVHGm:b4hpaha) ([raw file](https://github.com/google/nomulus/blob/2c1d05f4e5901b605a14194b9b866c691d46ab78/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L339)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It looked like it was new here.
</blockquote></details>

nah it was old, but it's moot 


<!-- Sent from Reviewable.io -->

2021-07-27 21:26 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 109 at r5](https://reviewable.io/reviews/google/nomulus/1218#-Me5eRQO3668oCOpFwtK:-MfdpdAV5utaqmIcrkN6:b7j89yk) ([raw file](https://github.com/google/nomulus/blob/3c2c0510265e985e017e0da343d63fbe87527515/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L109)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Seems like, from https://playbooks.corp.google.com/domain_registry/procedures/how-to-setup-registry-blackbox-probers.md?cl=head, that we can add/remove probers without too much difficulty. 

Doing a `SELECT * FROM `domain-registry.latest_datastore_export.Registrar` WHERE type = 'MONITORING'` gives 28 results, unfortunately not all of them have the same naming pattern (and we probably don't want to rely on that anyway). It's probably not worth joining on the Registrar table to see if it's a MONITORING registrar type? 
</blockquote></details>

Yeah, probably not worth it.  Oh well.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 169 at r9](https://reviewable.io/reviews/google/nomulus/1218#-MfdqX-u5WVMfNme3LZk:-MfdqX-u5WVMfNme3LZl:b-23zf8y) ([raw file](https://github.com/google/nomulus/blob/0b7169f36f2f6ad1406f9438610bc9c40d688752/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L169)):*
> ```Java
>     String lastSeenRepoId = null;
>     do {
>       final String finalLastSeenRepoId = lastSeenRepoId;
> ```

Would a better name for this be `previousLastSeenRepoId` or similar?  From the name `final` it's not clear what it's actually doing.


<!-- Sent from Reviewable.io -->

2021-07-27 21:35 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 169 at r9](https://reviewable.io/reviews/google/nomulus/1218#-MfdqX-u5WVMfNme3LZk:-Mfdt7366hjsBaXjNwDU:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0b7169f36f2f6ad1406f9438610bc9c40d688752/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L169)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Would a better name for this be `previousLastSeenRepoId` or similar?  From the name `final` it's not clear what it's actually doing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 21:09 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 169 at r9](https://reviewable.io/reviews/google/nomulus/1218#-MfdqX-u5WVMfNme3LZk:-Mfo5HJV4GyghC5fK55N:bit4zi1) ([raw file](https://github.com/google/nomulus/blob/0b7169f36f2f6ad1406f9438610bc9c40d688752/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L169)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it done?


<!-- Sent from Reviewable.io -->

2021-07-29 21:10 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJJwVl5NGI2f8dC8LB:-Mfo5VD38wmIoH5UhiRa:b-cfihti) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L149)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Done, it was an accident to leave it in.
</blockquote></details>

@jianglai you still have a blocking comment here


<!-- Sent from Reviewable.io -->

2021-07-29 21:33 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 169 at r9](https://reviewable.io/reviews/google/nomulus/1218#-MfdqX-u5WVMfNme3LZk:-MfoAqO8C2nc6j0bhlqa:bvct3px) ([raw file](https://github.com/google/nomulus/blob/0b7169f36f2f6ad1406f9438610bc9c40d688752/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L169)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is it done?
</blockquote></details>

what, you're telling me you couldn't read the files on my local filesystem that I hadn't pushed to Github yet? Weirdo 


<!-- Sent from Reviewable.io -->

2021-07-30 19:46 UTC, gbrodman reviewed
> Dismissed @jianglai from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJJwVl5NGI2f8dC8LB:-Mfswyo872uAMOHxN8zH:b-p6b9i0) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L149)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

@jianglai you still have a blocking comment here
</blockquote></details>

Talked with Lai and he's fine dismissing this 


<!-- Sent from Reviewable.io -->

2021-08-05 17:24 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 161 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJM881DMnAJluQM9e6:-MgMKyYNE5vpXdil8ZEq:brk790u) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L161)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It's a bit of a hairy query as you can see, but done. All are indexed except the subordinate hosts field but that shouldn't really matter since that shouldn't be a heavy filter. 
</blockquote></details>

@jianglai you're still blocking on this comment as well.


<!-- Sent from Reviewable.io -->

2021-08-05 17:28 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 182 at r10](https://reviewable.io/reviews/google/nomulus/1218#-MgMLowGCwHLBVDIbDzk:-MgMLowGCwHLBVDIbDzl:b-zfqtqz) ([raw file](https://github.com/google/nomulus/blob/02a93a9f269812fad6f2f4ef979162db3c90f548/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L182)):*
> ```Java
>                         : Iterables.getLast(nextBatch).getRepoId();
>                   });
>     } while (lastSeenRepoId != null);
> ```

There's some missing logging here at the end of the job.  You should be counting how many domains were hard-deleted, soft-deleted, and skipped (by reason), and logging that here once done.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 251 at r10](https://reviewable.io/reviews/google/nomulus/1218#-MgMLLUF2OM6x-yZiub_:-MgMLLUF2OM6x-yZiuba:bve3qwl) ([raw file](https://github.com/google/nomulus/blob/02a93a9f269812fad6f2f4ef979162db3c90f548/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L251)):*
> ```Java
>   }
> 
>   private void hardDeletePollMessages(ImmutableList<String> domainRepoIds) {
> ```

I don't know if all most of these helper methods are merited anymore (they're only being called from one place and it wouldn't be that crazy to simply inline them all there).


<!-- Sent from Reviewable.io -->

2021-08-05 19:26 UTC, gbrodman reviewed
> Dismissed @jianglai from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 161 at r1](https://reviewable.io/reviews/google/nomulus/1218#-MdJM881DMnAJluQM9e6:-MgMbmXk8dANLbaGuQDv:bt8l5uo) ([raw file](https://github.com/google/nomulus/blob/2545c755a2bae8f8bc3847c85be1d82cedbfec62/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L161)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

@jianglai you're still blocking on this comment as well.
</blockquote></details>

Dismissing this for the same reason as the other one 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 182 at r10](https://reviewable.io/reviews/google/nomulus/1218#-MgMLowGCwHLBVDIbDzk:-MgMhYns43pZrShloYE2:b8on45n) ([raw file](https://github.com/google/nomulus/blob/02a93a9f269812fad6f2f4ef979162db3c90f548/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L182)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There's some missing logging here at the end of the job.  You should be counting how many domains were hard-deleted, soft-deleted, and skipped (by reason), and logging that here once done.
</blockquote></details>

Is it worth logging how many were skipped? I'm not sure how useful that info would be, and it'd require another set of queries, slowing down the action. 

Added the other logs though. 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 251 at r10](https://reviewable.io/reviews/google/nomulus/1218#-MgMLLUF2OM6x-yZiub_:-MgMcA1y7HK_2_gYOcTl:b-rgtxo1) ([raw file](https://github.com/google/nomulus/blob/02a93a9f269812fad6f2f4ef979162db3c90f548/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L251)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I don't know if all most of these helper methods are merited anymore (they're only being called from one place and it wouldn't be that crazy to simply inline them all there).
</blockquote></details>

fair, given that we delete directly from the table name it should be pretty clear what's going on 


<!-- Sent from Reviewable.io -->

2021-08-20 16:05 UTC, jianglai requested changes
> Reviewed 1 of 2 files at r8, 4 of 5 files at r9, 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 109 at r11](https://reviewable.io/reviews/google/nomulus/1218#-MhZ3bvmBgV83sSjUC3y:-MhZ3bvmBgV83sSjUC3z:bi9kxte) ([raw file](https://github.com/google/nomulus/blob/25860388e426fc5cf5685b99e28db264bd8c062f/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L109)):*
> ```
>           + " :creationTimeCutoff AND ((d.creationTime <= :nowAutoTimestamp AND d.deletionTime >"
>           + " current_timestamp()) OR d.deletionTime < :nowMinusSoftDeleteDelay)";
> ```
Why are we using different times for now (`:nowAutoTimestamp` vs `current_timestamp()`)?
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 191 at r11](https://reviewable.io/reviews/google/nomulus/1218#-MhZEnxC7cX2niKyqEmE:-MhZEnxC7cX2niKyqEmF:b-ft1ymw) ([raw file](https://github.com/google/nomulus/blob/25860388e426fc5cf5685b99e28db264bd8c062f/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L191)):*
> ```
> nextDomainBatch
> ```
Have you looked into using [`ScrollableResults`](https://docs.jboss.org/hibernate/orm/5.5/userguide/html_single/Hibernate_User_Guide.html#hql-api-scroll) for pagination? No need to reinvent the wheel if that works for us.


<!-- Sent from Reviewable.io -->

2021-08-20 16:44 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 109 at r11](https://reviewable.io/reviews/google/nomulus/1218#-MhZ3bvmBgV83sSjUC3y:-MhZQfog04-cXnVRordx:b-r34f7j) ([raw file](https://github.com/google/nomulus/blob/25860388e426fc5cf5685b99e28db264bd8c062f/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L109)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>           + " :creationTimeCutoff AND ((d.creationTime <= :nowAutoTimestamp AND d.deletionTime >"
>           + " current_timestamp()) OR d.deletionTime < :nowMinusSoftDeleteDelay)";
> ```
Why are we using different times for now (`:nowAutoTimestamp` vs `current_timestamp()`)?
</blockquote></details>

It's because they're not the same data type -- `nowAutoTimestamp` is a CreateAutoTimestamp object which is compared to the Java object `creationTime`, and `current_timestamp()` is the SQL timestamp object, which is compared directly to the DateTime `deletionTime` 
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 191 at r11](https://reviewable.io/reviews/google/nomulus/1218#-MhZEnxC7cX2niKyqEmE:-MhZRdmR7N8BduBdmaLR:boeq4vf) ([raw file](https://github.com/google/nomulus/blob/25860388e426fc5cf5685b99e28db264bd8c062f/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L191)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> nextDomainBatch
> ```
Have you looked into using [`ScrollableResults`](https://docs.jboss.org/hibernate/orm/5.5/userguide/html_single/Hibernate_User_Guide.html#hql-api-scroll) for pagination? No need to reinvent the wheel if that works for us.
</blockquote></details>

It seems like that API is focused toward selecting particular fields / columns from a result set rather than the auto-conversion-to-Java that we already have here. I could be missing something though; are you more familiar with it? 


<!-- Sent from Reviewable.io -->

2021-08-23 13:13 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 109 at r11](https://reviewable.io/reviews/google/nomulus/1218#-MhZ3bvmBgV83sSjUC3y:-Mhn2W72CR1BAOO3nV20:b1n9u1s) ([raw file](https://github.com/google/nomulus/blob/25860388e426fc5cf5685b99e28db264bd8c062f/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L109)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It's because they're not the same data type -- `nowAutoTimestamp` is a CreateAutoTimestamp object which is compared to the Java object `creationTime`, and `current_timestamp()` is the SQL timestamp object, which is compared directly to the DateTime `deletionTime` 
</blockquote></details>

That's annoying. Is it possible to convert a `CreationAutoTimestamp` to some Java type that will be comparable to a SQL `DataTime`? Failing that we should at least make a note of this fact in the comment.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 191 at r11](https://reviewable.io/reviews/google/nomulus/1218#-MhZEnxC7cX2niKyqEmE:-Mhn7E2P6A6RHJOBZQce:bbr71nm) ([raw file](https://github.com/google/nomulus/blob/25860388e426fc5cf5685b99e28db264bd8c062f/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L191)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It seems like that API is focused toward selecting particular fields / columns from a result set rather than the auto-conversion-to-Java that we already have here. I could be missing something though; are you more familiar with it? 
</blockquote></details>

From [this example](https://www.baeldung.com/hibernate-pagination#hql-scroll) it looks like you can use HQL and get java objects in `ScrollableResults`.  I didn't check whether our `TransactionManager` API allows exposing such  results, though. But I think it should be straightforward to add support for that.

This also has the added benefit of not needing to do a query for each page, all the results are obtained in a single query and the pagination is handled by the API intrinsically.


<!-- Sent from Reviewable.io -->

2021-08-23 15:42 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 109 at r11](https://reviewable.io/reviews/google/nomulus/1218#-MhZ3bvmBgV83sSjUC3y:-MhnfOCJBnSXUg_duK7I:b-n9trcp) ([raw file](https://github.com/google/nomulus/blob/25860388e426fc5cf5685b99e28db264bd8c062f/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L109)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

That's annoying. Is it possible to convert a `CreationAutoTimestamp` to some Java type that will be comparable to a SQL `DataTime`? Failing that we should at least make a note of this fact in the comment.
</blockquote></details>

I'm not sure it's possible, no. Added a comment.
___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 191 at r11](https://reviewable.io/reviews/google/nomulus/1218#-MhZEnxC7cX2niKyqEmE:-Mhnf02nAHZ1v9g7fxt2:bao6qjg) ([raw file](https://github.com/google/nomulus/blob/25860388e426fc5cf5685b99e28db264bd8c062f/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L191)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

From [this example](https://www.baeldung.com/hibernate-pagination#hql-scroll) it looks like you can use HQL and get java objects in `ScrollableResults`.  I didn't check whether our `TransactionManager` API allows exposing such  results, though. But I think it should be straightforward to add support for that.

This also has the added benefit of not needing to do a query for each page, all the results are obtained in a single query and the pagination is handled by the API intrinsically.
</blockquote></details>

Ah, I see what you mean. The documentation suggests it only gets single columns, rather than the full result. Done! 

Note: I think this requires intermittently flushing / clearing the session so we don't OOM but this should work all in one transaction. 


<!-- Sent from Reviewable.io -->

2021-08-23 18:58 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 201 at r12](https://reviewable.io/reviews/google/nomulus/1218#-MhoMd7y19ilfu1uMzeh:-MhoMd7y19ilfu1uMzei:b-fr3rl2) ([raw file](https://github.com/google/nomulus/blob/84f158c2e3bbb666d677268ee33c55769ee4a12a/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L201)):*
> ```
>               ImmutableList<String> domainRepoIds = domainRepoIdsToHardDelete.build();
>               hardDeleteDomainsAndHosts(domainRepoIds, hostNamesToHardDelete.build());
> ```
This should be processed within the for loop -- once the domainsToDelete hit `BATCH_SIZE` we delete them and clear the list. Otherwise we are processing each domains one by one but still deleting all those need to be deleted in one go, risking hitting some database transaction size limit.


<!-- Sent from Reviewable.io -->

2021-08-23 19:18 UTC, gbrodman commented
Reviewable is failing to load for me, but that's done.

2021-08-23 20:23 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)



<!-- Sent from Reviewable.io -->

2021-08-24 21:13 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 201 at r12](https://reviewable.io/reviews/google/nomulus/1218#-MhoMd7y19ilfu1uMzeh:-Mhu-9BK7_8-oOhCul_o:b-g0zs3d) ([raw file](https://github.com/google/nomulus/blob/84f158c2e3bbb666d677268ee33c55769ee4a12a/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L201)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>               ImmutableList<String> domainRepoIds = domainRepoIdsToHardDelete.build();
>               hardDeleteDomainsAndHosts(domainRepoIds, hostNamesToHardDelete.build());
> ```
This should be processed within the for loop -- once the domainsToDelete hit `BATCH_SIZE` we delete them and clear the list. Otherwise we are processing each domains one by one but still deleting all those need to be deleted in one go, risking hitting some database transaction size limit.
</blockquote></details>

Reviewable is working now; this is done. 


<!-- Sent from Reviewable.io -->

2021-08-25 02:21 UTC, jianglai approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 201 at r12](https://reviewable.io/reviews/google/nomulus/1218#-MhoMd7y19ilfu1uMzeh:-Mhv4ce10TaEjr5X1OaR:b-omx4rt) ([raw file](https://github.com/google/nomulus/blob/84f158c2e3bbb666d677268ee33c55769ee4a12a/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L201)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Reviewable is working now; this is done. 
</blockquote></details>

Two nitpicks:

1. The iterator `i` should start at 1 (otherwise you always process the first result by itself) and it can be incremented with `i++ % BATCH_SIZE` instead of `i++`. Not that integer overflow is a real concern here though...

2. You can check the size of `domainRepoIdsToHardDelete` and decide when to process it (and `hostNamesToHardDelete`) when it hits `BATCH_SIZE`, instead of always processing them when `i` warps around `BATCH_SIZE`, because not all domains processed are to be hard deleted. In practice it might not affect performance given that the majority of domains should be hard deleted. 


<!-- Sent from Reviewable.io -->

2021-08-25 14:38 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1218)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteProberDataAction.java, line 201 at r12](https://reviewable.io/reviews/google/nomulus/1218#-MhoMd7y19ilfu1uMzeh:-MhxiLrWB377OPhvB1hW:bnn5a7t) ([raw file](https://github.com/google/nomulus/blob/84f158c2e3bbb666d677268ee33c55769ee4a12a/core/src/main/java/google/registry/batch/DeleteProberDataAction.java#L201)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Two nitpicks:

1. The iterator `i` should start at 1 (otherwise you always process the first result by itself) and it can be incremented with `i++ % BATCH_SIZE` instead of `i++`. Not that integer overflow is a real concern here though...

2. You can check the size of `domainRepoIdsToHardDelete` and decide when to process it (and `hostNamesToHardDelete`) when it hits `BATCH_SIZE`, instead of always processing them when `i` warps around `BATCH_SIZE`, because not all domains processed are to be hard deleted. In practice it might not affect performance given that the majority of domains should be hard deleted. 
</blockquote></details>

1. Sure, then we can just check for i == 0
2. Yeah, I think the ratio of hard deletes to soft deletes was something like 100:1. In any case, I think we probably want to keep it this way because the concerns here are with regards to memory and keeping track of the DomainBase objects, rather than the actual writes back to the DB 


<!-- Sent from Reviewable.io -->

2021-08-28 01:09 UTC, merged