Remove old DomainList fields from Registry
google/nomulus pull request #1231
Opened 2021-07-02 17:26 UTC by sarahcaseybot

I also resaved all Registry objects in sandbox and production to make sure that the new field is populated on all entity objects.

2021-07-07 17:33 UTC, gbrodman requested changes
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1231)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/export/ExportUtils.java, line 43 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me104udAyNCO9OP8UAO:-Me104udAyNCO9OP8UAP:b90a7n2) ([raw file](https://github.com/google/nomulus/blob/047444831b233e11d7fa2689980317c2939a26b8/core/src/main/java/google/registry/export/ExportUtils.java#L43)):*
> ```Java
>     Set<String> reservedTerms = new TreeSet<>();
>     for (Key<ReservedList> key : registry.getReservedLists()) {
>       ReservedList reservedList = ReservedList.load(key).get();
> ```

I think we should be able to remove ReservedList::load entirely? 
___
*[core/src/main/java/google/registry/export/ExportUtils.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me10CRV6llYgFc3u4cW:-Me10CRV6llYgFc3u4cX:b-dt0rw9) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/main/java/google/registry/export/ExportUtils.java#L44)):*
> ```Java
>     Set<String> reservedTerms = new TreeSet<>();
>     for (String rlName : registry.getReservedLists()) {
>       Optional<ReservedList> reservedList = ReservedListDao.getLatestRevision(rlName);
> ```

 nitty but we could do 

`ReservedList reservedList = RLDao.getLatestRevision(rlName).orElseThrow(() -> new IllegalStateException(...))`
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 402 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me10WVw2YagXyR_Hz8e:-Me10WVw2YagXyR_Hz8f:b-ny0tgd) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/main/java/google/registry/model/registry/Registry.java#L402)):*
> ```Java
>    * largest revision ID.
>    */
>   public ImmutableSet<String> getReservedLists() {
> ```

How about changing this to `getReservedListNames`? 
___
*[core/src/main/java/google/registry/model/registry/label/ReservedList.java, line 190 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me10kLM1kyAdNCrHm0T:-Me10kLNBQgaqlnyLCui:b-sty7cr) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/main/java/google/registry/model/registry/label/ReservedList.java#L190)):*
> ```Java
>   @Override
>   protected boolean refersToKey(Registry registry, Key<? extends BaseDomainLabelList<?, ?>> key) {
>     return registry.getReservedLists().contains(key.getName());
> ```

Can we have a task for refactoring the BaseDomainLabelList to remove these Key references? It seems like we shouldn't need them any more now that both PremiumList and ReservedList are entirely in SQL 


<!-- Sent from Reviewable.io -->

2021-07-07 19:10 UTC, gbrodman approved these changes
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-07-07 19:18 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1231)* status: all files reviewed, 7 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/export/ExportUtils.java, line 43 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me1IdC00G5TU8Ae6jfD:-Me1IdC00G5TU8Ae6jfE:b5xrohr) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/main/java/google/registry/export/ExportUtils.java#L43)):*
> ```Java
>     StringBuilder termsBuilder = new StringBuilder(reservedTermsExportDisclaimer).append("\n");
>     Set<String> reservedTerms = new TreeSet<>();
>     for (String rlName : registry.getReservedLists()) {
> ```

Just use `reservedListName` here.  Yeah it's more verbose, but it's also clearer.
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 116 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me1NpkyC6kPjlokTnZJ:-Me1NpkyC6kPjlokTnZK:b-yjfv0y) ([raw file](https://github.com/google/nomulus/blob/047444831b233e11d7fa2689980317c2939a26b8/core/src/main/java/google/registry/model/registry/Registry.java#L116)):*
> ```Java
>     tldStr = tldStrId;
>     // TODO(sarahbot@): Remove the rest of this method after this data migration is complete
>     if (premiumListName != null) {
> ```

You've re-saved all `Registry` entities in all environments already to ensure that the data migration is complete, right?  If not, you need to do so before submitting this change.

If yes, what did you use to re-save all those entities?
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 623 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me1Nh-iAZFV-037aDFc:-Me1Nh-iAZFV-037aDFd:b-v0jtd9) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/main/java/google/registry/model/registry/Registry.java#L623)):*
> ```Java
>   }
> 
>   public Optional<String> getPremiumList() {
> ```

Should be renamed to `getPremiumListName`?
___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 909 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me1O3kv4R-xC0Sad2TT:-Me1O3kv4R-xC0Sad2TU:bnkl4ok) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/main/java/google/registry/model/registry/Registry.java#L909)):*
> ```Java
> 
>     @VisibleForTesting
>     public Builder setPremiumListKey(@Nullable Key<PremiumList> premiumList) {
> ```

Any particular reason this set by Key method still needs to exist?  Is it widely referred to in tests or something?  If so, and that would balloon the size of this PR, that's acceptable to do in a follow-up, but leave a TODO at least (and mark this method as `@Deprecated`).
___
*[core/src/test/java/google/registry/model/registry/RegistryTest.java, line 251 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me1OgDf7nSIpGfBFTeJ:-Me1OgDf7nSIpGfBFTeK:b-ku622d) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/test/java/google/registry/model/registry/RegistryTest.java#L251)):*
> ```Java
>     Registry registry = Registry.get("tld").asBuilder().setPremiumList(pl2).build();
>     Optional<String> pl = registry.getPremiumList();
>     assertThat(pl).isPresent();
> ```

A better assertion here would be `assertThat(pl).hasValue("tld2");`
___
*[core/src/test/java/google/registry/tools/CreateTldCommandTest.java, line 522 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me1OqWh3a6fBCE6W0mq:-Me1OqWh3a6fBCE6W0mr:b-dvu5jk) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/test/java/google/registry/tools/CreateTldCommandTest.java#L522)):*
> ```Java
>         "xn--q9jyb4c");
>     assertThat(Registry.get("xn--q9jyb4c").getPremiumList()).isPresent();
>     assertThat(Registry.get("xn--q9jyb4c").getPremiumList().get()).isEqualTo("xn--q9jyb4c");
> ```

This should be `assertThat(Registry.get("xn--q9jyb4c").getPremiumList()).hasValue("xn--q9jyb4c");`
___
*[core/src/test/java/google/registry/tools/UpdateTldCommandTest.java, line 851 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me1OxRp4wNgtmkRGmpf:-Me1OxRp4wNgtmkRGmpg:be6ghn4) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/test/java/google/registry/tools/UpdateTldCommandTest.java#L851)):*
> ```Java
>     runCommandForced("--add_reserved_lists=xn--q9jyb4c_r1,xn--q9jyb4c_r2", "xn--q9jyb4c");
>     Optional<String> premiumListName = Registry.get("xn--q9jyb4c").getPremiumList();
>     assertThat(premiumListName).isPresent();
> ```

Use `hasValue()` here, which allows you to collapse these two lines into one assertion.


<!-- Sent from Reviewable.io -->

2021-07-08 15:02 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1231)* status: 6 of 17 files reviewed, 7 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/test/java/google/registry/model/OteAccountBuilderTest.java, line 74 at r3](https://reviewable.io/reviews/google/nomulus/1231#-Me5ct_V5TSm-szAqNHV:-Me5ct_V5TSm-szAqNHW:b-9otd5w) ([raw file](https://github.com/google/nomulus/blob/b83937e28e2c0a5ebcd6590d6c005bc185174eb1/core/src/test/java/google/registry/model/OteAccountBuilderTest.java#L74)):*
> ```Java
>     assertThat(registry).isNotNull();
>     assertThat(registry.getPremiumListName()).isPresent();
>     assertThat(registry.getPremiumListName().get()).isEqualTo("default_sandbox_list");
> ```

Ditto (see below).
___
*[core/src/test/java/google/registry/tools/CreateTldCommandTest.java, line 521 at r3](https://reviewable.io/reviews/google/nomulus/1231#-Me5cOgLE5LMjOsv7tsb:-Me5cOgLE5LMjOsv7tsc:b-xjpe1q) ([raw file](https://github.com/google/nomulus/blob/b83937e28e2c0a5ebcd6590d6c005bc185174eb1/core/src/test/java/google/registry/tools/CreateTldCommandTest.java#L521)):*
> ```Java
>         "--dns_writers=FooDnsWriter",
>         "xn--q9jyb4c");
>     assertThat(Registry.get("xn--q9jyb4c").getPremiumListName()).isPresent();
> ```

This line is no longer needed.  The `hasValue()` line below it is asserting presence.
___
*[core/src/test/java/google/registry/tools/SetupOteCommandTest.java, line 75 at r3](https://reviewable.io/reviews/google/nomulus/1231#-Me5cX2CBd7d_CCUO8jW:-Me5cX2CBd7d_CCUO8jX:b2am4r9) ([raw file](https://github.com/google/nomulus/blob/b83937e28e2c0a5ebcd6590d6c005bc185174eb1/core/src/test/java/google/registry/tools/SetupOteCommandTest.java#L75)):*
> ```Java
>     assertThat(registry.getTldState(DateTime.now(UTC))).isEqualTo(tldState);
>     assertThat(registry.getDnsWriters()).containsExactly("VoidDnsWriter");
>     assertThat(registry.getPremiumListName()).isNotNull();
> ```

This assertion doesn't make sense anymore now that this returns an Optional.
___
*[core/src/test/java/google/registry/tools/SetupOteCommandTest.java, line 76 at r3](https://reviewable.io/reviews/google/nomulus/1231#-Me5cZM71SlM5hE06_Wb:-Me5cZM71SlM5hE06_Wc:b-9ptcw3) ([raw file](https://github.com/google/nomulus/blob/b83937e28e2c0a5ebcd6590d6c005bc185174eb1/core/src/test/java/google/registry/tools/SetupOteCommandTest.java#L76)):*
> ```Java
>     assertThat(registry.getDnsWriters()).containsExactly("VoidDnsWriter");
>     assertThat(registry.getPremiumListName()).isNotNull();
>     assertThat(registry.getPremiumListName().get()).isEqualTo("default_sandbox_list");
> ```

Should be `hasValue()`
___
*[core/src/test/java/google/registry/tools/UpdateTldCommandTest.java, line 851 at r1](https://reviewable.io/reviews/google/nomulus/1231#-Me1OxRp4wNgtmkRGmpf:-Me5ciIo9hMXiVituN7K:bulygo3) ([raw file](https://github.com/google/nomulus/blob/f1e617b89df2f4cd684c4c7f98ea0391cd98dc3e/core/src/test/java/google/registry/tools/UpdateTldCommandTest.java#L851)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it?
___
*[core/src/test/java/google/registry/tools/UpdateTldCommandTest.java, line 853 at r3](https://reviewable.io/reviews/google/nomulus/1231#-Me5ccg8DbffLyn-tolq:-Me5ccg8DbffLyn-tolr:b-4zv35q) ([raw file](https://github.com/google/nomulus/blob/b83937e28e2c0a5ebcd6590d6c005bc185174eb1/core/src/test/java/google/registry/tools/UpdateTldCommandTest.java#L853)):*
> ```Java
>     runCommandForced("--add_reserved_lists=xn--q9jyb4c_r1,xn--q9jyb4c_r2", "xn--q9jyb4c");
>     Optional<String> premiumListName = Registry.get("xn--q9jyb4c").getPremiumListName();
>     assertThat(premiumListName).isPresent();
> ```

Another `isPresent()` call that is no longer necessary.
___
*[core/src/test/java/google/registry/tools/UpdateTldCommandTest.java, line 922 at r3](https://reviewable.io/reviews/google/nomulus/1231#-Me5cmnk1K9A7dBY-7ep:-Me5cmnk1K9A7dBY-7eq:b-89a4l7) ([raw file](https://github.com/google/nomulus/blob/b83937e28e2c0a5ebcd6590d6c005bc185174eb1/core/src/test/java/google/registry/tools/UpdateTldCommandTest.java#L922)):*
> ```Java
>   void testSuccess_setPremiumList() throws Exception {
>     runCommandForced("--premium_list=xn--q9jyb4c", "xn--q9jyb4c");
>     assertThat(Registry.get("xn--q9jyb4c").getPremiumListName()).isPresent();
> ```

Ditto


<!-- Sent from Reviewable.io -->

2021-07-08 20:08 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1231)* status: 6 of 17 files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-07-08 21:19 UTC, merged