Fix hanging threads in GcsDiffFileLister
google/nomulus pull request #1243
Opened 2021-07-15 15:42 UTC by gbrodman

When retrieving the object info for each file in GCS, the threads
should be created using the standard Java executor service. If we use
the request thread factory (as it did before), it attempts to create
background threads (threads with no ties to the request in question).
For starters, we don't mind the threads having a connection to the
request in question, but more importantly AppEngine limits us to 10
background threads per instance
(https://cloud.google.com/appengine/docs/standard/java/runtime#threads)
and some of these might be taken up by other requests / services. As a
result, much of the time the request to GCS never actually happens.

2021-07-15 19:39 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 160 at r3](https://reviewable.io/reviews/google/nomulus/1243#-MeffInrC9OGG8uqMhj6:-MeffIns6saX86B6UsHe:b-4ng6hs) ([raw file](https://github.com/google/nomulus/blob/d2c5f51b981a3fe69c841f1bcf9ed7c1cc371c5a/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L160)):*
> ```Java
>         "Actual restore from time: %s", getLowerBoundTime(sequence.firstEntry().getValue()));
>     logger.atInfo().log("Found %d files to restore", sequence.size());
>     lazyExecutor.get().shutdown();
> ```

Stick this in a `finally {}` block.  As-is it seems like there's many ways it might end up not executing on error conditions.


<!-- Sent from Reviewable.io -->

2021-07-15 19:42 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 160 at r3](https://reviewable.io/reviews/google/nomulus/1243#-MeffInrC9OGG8uqMhj6:-Mefg5c73aw0_dbRpqmB:bfp0gm4) ([raw file](https://github.com/google/nomulus/blob/d2c5f51b981a3fe69c841f1bcf9ed7c1cc371c5a/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L160)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Stick this in a `finally {}` block.  As-is it seems like there's many ways it might end up not executing on error conditions.
</blockquote></details>

Yeah the consequences of failing to shut down are minor (no logs) but yeah we should do it. Done. 


<!-- Sent from Reviewable.io -->

2021-07-15 19:48 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-07-16 13:18 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 72 at r6](https://reviewable.io/reviews/google/nomulus/1243#-MejSnM2AG_5-_J4_ujs:-MejSnM2AG_5-_J4_ujt:bmfwtzz) ([raw file](https://github.com/google/nomulus/blob/55950f51b1669a672268b78cd778d0a98b513501/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L72)):*
> ```Java
>         blobInfo =
>             Futures.getUnchecked(
>                 Futures.withTimeout(
> ```

This throws a `TimeoutException` wrapped in an `ExecutionException` (runtime).  It might be OK to rethrow that as-is.  Should be documented in the Javadoc at least.
___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 74 at r6](https://reviewable.io/reviews/google/nomulus/1243#-MejSI45-b8_xaYgVUzp:-MejSI45-b8_xaYgVUzq:b-rhfgft) ([raw file](https://github.com/google/nomulus/blob/55950f51b1669a672268b78cd778d0a98b513501/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L74)):*
> ```Java
>                 Futures.withTimeout(
>                     upperBoundTimesToBlobInfo.get(checkpointTime),
>                     Duration.ofMinutes(3),
> ```

3 minutes is pretty long?  It seems to me like getting the info of a file should take a lot less than that, and if it's taking longer than, say, even a minute, then it's liable to not be successful at all.

Also, make this a descriptively named static final field on the class.
___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 75 at r6](https://reviewable.io/reviews/google/nomulus/1243#-MejSBES2VBd2X4RTcjN:-MejSBES2VBd2X4RTcjO:blsxkum) ([raw file](https://github.com/google/nomulus/blob/55950f51b1669a672268b78cd778d0a98b513501/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L75)):*
> ```Java
>                     upperBoundTimesToBlobInfo.get(checkpointTime),
>                     Duration.ofMinutes(3),
>                     scheduledExecutorService));
> ```

And this works, even though this is using a different executor service than the one that the task was submitted to?


<!-- Sent from Reviewable.io -->

2021-07-16 14:22 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 72 at r6](https://reviewable.io/reviews/google/nomulus/1243#-MejSnM2AG_5-_J4_ujs:-MejgQbHBdoZO-K7Yrs1:b-pqpvnp) ([raw file](https://github.com/google/nomulus/blob/55950f51b1669a672268b78cd778d0a98b513501/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L72)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This throws a `TimeoutException` wrapped in an `ExecutionException` (runtime).  It might be OK to rethrow that as-is.  Should be documented in the Javadoc at least.
</blockquote></details>

Documented, but since both `TimeoutException` and `ExecutionException` are checked exceptions, I'm inclined to keep as is. 
___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 74 at r6](https://reviewable.io/reviews/google/nomulus/1243#-MejSI45-b8_xaYgVUzp:-MejdLU1-0Fe3cqOUikD:byeu1jg) ([raw file](https://github.com/google/nomulus/blob/55950f51b1669a672268b78cd778d0a98b513501/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L74)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

3 minutes is pretty long?  It seems to me like getting the info of a file should take a lot less than that, and if it's taking longer than, say, even a minute, then it's liable to not be successful at all.

Also, make this a descriptively named static final field on the class.
</blockquote></details>

I mean, it's not just "getting the info of a file", it's that plus waiting for any file-gets to finish first. But point taken. 
___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 75 at r6](https://reviewable.io/reviews/google/nomulus/1243#-MejSBES2VBd2X4RTcjN:-Mejd9j75O2gkMB8_iI3:b2q27cs) ([raw file](https://github.com/google/nomulus/blob/55950f51b1669a672268b78cd778d0a98b513501/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L75)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

And this works, even though this is using a different executor service than the one that the task was submitted to?
</blockquote></details>

Yes, it's supposed to -- this one keeps track of the timeouts. 


<!-- Sent from Reviewable.io -->

2021-07-16 16:08 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 72 at r6](https://reviewable.io/reviews/google/nomulus/1243#-MejSnM2AG_5-_J4_ujs:-Mek3RVW7jJdHJqW7EGy:bnl1u16) ([raw file](https://github.com/google/nomulus/blob/55950f51b1669a672268b78cd778d0a98b513501/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L72)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Documented, but since both `TimeoutException` and `ExecutionException` are checked exceptions, I'm inclined to keep as is. 
</blockquote></details>

If they're checked exceptions, then how is this even working without a try/catch or a `throws` on the method signature?


<!-- Sent from Reviewable.io -->

2021-07-16 16:09 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 47 at r7](https://reviewable.io/reviews/google/nomulus/1243#-Mek3yd8CEFv6WdS0Fop:-Mek3yd93t0sYACTX_MZ:biobel6) ([raw file](https://github.com/google/nomulus/blob/0dda525fc7cb9ba053b073d3adbf845aa7247f72/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L47)):*
> ```Java
> 
>   private static final FluentLogger logger = FluentLogger.forEnclosingClass();
>   /** Timeout for retrieving per-file information from GCS. */
> ```

Missing newline before this.


<!-- Sent from Reviewable.io -->

2021-07-16 16:58 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 72 at r6](https://reviewable.io/reviews/google/nomulus/1243#-MejSnM2AG_5-_J4_ujs:-MekF9IkEsRTgRONnqdY:b-27hair) ([raw file](https://github.com/google/nomulus/blob/55950f51b1669a672268b78cd778d0a98b513501/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L72)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

If they're checked exceptions, then how is this even working without a try/catch or a `throws` on the method signature?
</blockquote></details>

Because of the `getUnchecked` call


<!-- Sent from Reviewable.io -->

2021-07-16 17:07 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 64 at r8](https://reviewable.io/reviews/google/nomulus/1243#-MekHDS09cci8xMgSlM-:-MekHDS09cci8xMgSlM0:b-nf49sn) ([raw file](https://github.com/google/nomulus/blob/cc4c902ecd838badf2ab9b3aa767a06e48221068/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L64)):*
> ```Java
>    * more files are missing.
>    *
>    * @throws AssertionError wrapping a {@link java.util.concurrent.TimeoutException} if the GCS call
> ```

This throws an `AssertionError`?  That doesn't seem right.


<!-- Sent from Reviewable.io -->

2021-07-16 17:23 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 64 at r8](https://reviewable.io/reviews/google/nomulus/1243#-MekHDS09cci8xMgSlM-:-MekKyuG5U9i3uIR23Ky:busgk5a) ([raw file](https://github.com/google/nomulus/blob/cc4c902ecd838badf2ab9b3aa767a06e48221068/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L64)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This throws an `AssertionError`?  That doesn't seem right.
</blockquote></details>

ugh yeah that was the wrong copy+paste my bad. 

fixed 


<!-- Sent from Reviewable.io -->

2021-07-16 17:31 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/backup/GcsDiffFileLister.java, line 64 at r8](https://reviewable.io/reviews/google/nomulus/1243#-MekHDS09cci8xMgSlM-:-MekMtlJDuTBffUb5uDq:b-ct3kwy) ([raw file](https://github.com/google/nomulus/blob/cc4c902ecd838badf2ab9b3aa767a06e48221068/core/src/main/java/google/registry/backup/GcsDiffFileLister.java#L64)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ugh yeah that was the wrong copy+paste my bad. 

fixed 
</blockquote></details>

that is, i misread the code and copy+pasted the wrong thing 


<!-- Sent from Reviewable.io -->

2021-07-16 18:03 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1243)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-07-16 18:13 UTC, merged