Add method that checks if client should be notified for expiring certificate
google/nomulus pull request #1245
Opened 2021-07-16 15:30 UTC by rachelguan

2021-07-20 21:47 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 462 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf4qjYR7FNmmYe8Uiuz:-Mf4qjYR7FNmmYe8Uiv-:b-3ganqv) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/config/files/default-config.yaml#L462)):*
> ```YAML
>   allowedEcdsaCurves:
>     - secp256r1
>     - secp384r1
> ```

Trailing whitespaces here. Are they intentional?
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf4r-zs7Jf0IfHmeFg8:-Mf4r-zs7Jf0IfHmeFg9:b42al76) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L45)):*
> ```
> import org.testcontainers.shaded.org.bouncycastle.openssl.jcajce.JcaMiscPEMGenerator;
> import org.testcontainers.shaded.org.bouncycastle.util.io.pem.PemObjectGenerator;
> import org.testcontainers.shaded.org.bouncycastle.util.io.pem.PemWriter;
> ```
Wrong import.

A class may exist in multiple jars, and you need to choose the canonical one. In this case they should be org.bouncycastle....
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf4rUN739Ouy7pB8aDi:-Mf4rUN739Ouy7pB8aDj:b7n77nq) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L104)):*
> ```
> org.bouncycastle.jce.spec.
> ```
You can import this class and use its simple name right?


<!-- Sent from Reviewable.io -->

2021-07-21 18:42 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @rachelguan, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 462 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf4qjYR7FNmmYe8Uiuz:-Mf9Mf-b09bso9VDbjLk:b6t6k3u) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/config/files/default-config.yaml#L462)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Trailing whitespaces here. Are they intentional?
</blockquote></details>

i actually have no idea how to fix this. Reformatting the file couldn't fix it. 


<!-- Sent from Reviewable.io -->

2021-07-21 19:30 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf4r-zs7Jf0IfHmeFg8:-Mf9Y00R6dvQIX2CfBIC:blkwbr5) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L45)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> import org.testcontainers.shaded.org.bouncycastle.openssl.jcajce.JcaMiscPEMGenerator;
> import org.testcontainers.shaded.org.bouncycastle.util.io.pem.PemObjectGenerator;
> import org.testcontainers.shaded.org.bouncycastle.util.io.pem.PemWriter;
> ```
Wrong import.

A class may exist in multiple jars, and you need to choose the canonical one. In this case they should be org.bouncycastle....
</blockquote></details>

fixed. 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf4rUN739Ouy7pB8aDi:-Mf9WmE1CX8-fjNrX9eZ:b-l6bq3y) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L104)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> org.bouncycastle.jce.spec.
> ```
You can import this class and use its simple name right?
</blockquote></details>

existing issue. will fix that. this file has to be reformatted in order to pass the java style test for some reason. 


<!-- Sent from Reviewable.io -->

2021-07-21 20:34 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 0 of 13 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 462 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf4qjYR7FNmmYe8Uiuz:-Mf9lZXT7GYNZa16gEEL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/config/files/default-config.yaml#L462)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

i actually have no idea how to fix this. Reformatting the file couldn't fix it. 
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 206 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf9Xkks115opA-z45U0:-Mf9duHE5pbHsyr3IPpS:b-4oceul) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L206)):*
> isNearingExpiration
i don't see this method being used besides its test cases. I can create a separate PR to remove this method in the future. 
___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 246 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf9ZOPk1XK_K7fgXjf5:-Mf9gBq-28l_9sAtuRUd:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L246)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Test name should be more descriptive, something like test_getCertificate_throwsExceptionForInvalidCertificateString
</blockquote></details>

done
___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 249 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf9ZZqO49y4Peh6erZK:-Mf9gCXYB4FsqOOHLc5L:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L249)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

This should also check the message in the exception
</blockquote></details>

done
___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 265 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf9Zoww8Dn0csL_Fnrb:-Mf9h2VN7qebO7Wp5puL:blkwbr5) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L265)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

This doesn't return a certificate object, it returns a String representation of the certificate
</blockquote></details>

fixed. 
___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 272 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf9Zze4BPV7zFOVcV7q:-Mf9h4a42iO5ERGYq0Ht:blkwbr5) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L272)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

This test should change a certificate string to a certificate and back again and check that the strings are equal. Similar to what is done in the test before this one, but the other way around.
</blockquote></details>

fixed. 
___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 288 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf9_nkk9H17sNP2TJWl:-Mf9edbM4tkXkn_ljWTn:b-896fix) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L288)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

a variable declaration isn't needed here, Just inline this in the next line. Same thing in the other tests
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-23 14:58 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @sarahcaseybot and @weiminyu)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 462 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf4qjYR7FNmmYe8Uiuz:-MfIrrqU9g7l5Zd68Tis:bwbj3v5) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/config/files/default-config.yaml#L462)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

One way to fix it would always just be to delete the whitespace in a text editor.

And I don't know if we have a YAML formatter anyway.  This format is manually maintained as far as I'm aware.  IntelliJ might have some kind of YAML formatting built in, but it's not part of our build toolchain.


<!-- Sent from Reviewable.io -->

2021-07-23 15:02 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @sarahcaseybot and @weiminyu)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 462 at r1](https://reviewable.io/reviews/google/nomulus/1245#-Mf4qjYR7FNmmYe8Uiuz:-MfIslgU8zVenlHcnICl:b-sv4wtr) ([raw file](https://github.com/google/nomulus/blob/aa1cd2128a444e8aaa18158d5a0b7bdd8f8a530e/core/src/main/java/google/registry/config/files/default-config.yaml#L462)):*
> One way to fix it would always just be to delete the whitespace in a text editor.
> And I don't know if we have a YAML formatter anyway.  This format is manually maintained as far as I'm aware.  IntelliJ might have some kind of YAML formatting built in, but it's not part of our build toolchain.
thanks for the explanation Ben! 


<!-- Sent from Reviewable.io -->

2021-07-23 15:07 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 12 of 13 files reviewed, 6 unresolved discussions (waiting on @rachelguan, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 104 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIsRSY1mxjTNmM2i6o:-MfIsRSY1mxjTNmM2i6p:b-hsfo62) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L104)):*
> ```Java
> 
>   /** Checks if the curve used for a public key is in the list of acceptable curves. */
>   private static boolean checkCurveName(PublicKey key, ImmutableSet<String> allowedEcdsaCurves) {
> ```

Needs a more descriptive name, something like `checkEcdsaCurveAllowed()`
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 117 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIsBYqB-u_vjnpaS5a:-MfIsBYqB-u_vjnpaS5b:b2l6hkw) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L117)):*
> ```Java
>       params = ecKey.getParameters();
>     } else {
>       throw new IllegalArgumentException("Unrecognized instance of PublicKey.");
> ```

Use a better error message.  How about:

```
throw new IllegalArgumentException("Unrecognized subclass of PublicKey: " + key.getClass());
```
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 256 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfItKDA9pyD7y-Oq3d5:-MfItKDA9pyD7y-Oq3d6:b9wubck) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L256)):*
This is confusing to follow along.  Better formatting would be:
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> Client should receive a notification email if both of these conditions are met:
>
> 1) certificate's expiration date < current date + 30 days AND
> 2) lastExpiringNotificationSentDate is null (client has not received their
>     first notification) OR lastExpiringNotificationSentDate is not null but the gap
>     between lastExpiringNotificationSentDate and currentDate is greater than
>     15 days.
> ```
</details>



<!-- Sent from Reviewable.io -->

2021-07-23 15:16 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 12 of 13 files reviewed, 10 unresolved discussions (waiting on @rachelguan, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 90 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIuHdY5Q_L2l7t8iUs:-MfIuHdY5Q_L2l7t8iUt:bnxkx7j) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L90)):*
> ```Java
>         "Max validity length schedule must contain an entry for START_OF_TIME");
>     this.maxValidityLengthSchedule = maxValidityDaysSchedule;
>     this.daysToExpiration = expirationWarningDays;
> ```

Name this variable the same as the config option.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 245 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIuso084eye4H05kab:-MfIuso084eye4H05kac:bhipirv) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L245)):*
> ```Java
>   }
> 
>   /** Returns {@code true} if the client should receive a notification email. */
> ```

`Returns whether the client should receive...`
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 256 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfItKDA9pyD7y-Oq3d5:-MfIvBlR5gHY1vhvJGwf:bycff59) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L256)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is confusing to follow along.  Better formatting would be:

> ```
> Client should receive a notification email if both of these conditions are met:
>
> 1) certificate's expiration date < current date + 30 days AND
> 2) lastExpiringNotificationSentDate is null (client has not received their
>     first notification) OR lastExpiringNotificationSentDate is not null but the gap
>     between lastExpiringNotificationSentDate and currentDate is greater than
>     15 days.
> ```

</blockquote></details>

Also that `<` in 1) seems like it should be a `<=` based on the logic below, no?
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 261 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIuOzcAcrAi3tmzfvn:-MfIuOzcAcrAi3tmzfvo:b-d7mart) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L261)):*
> ```Java
>      * lastExpiringNotificationSentDate and currentDate is greater than 15 days.
>      *
>      * <p>daysToExpiration = 30, expiringNotificationInterval = 15;
> ```

These are all configured, right?  So the value isn't necessarily these.  (Also I don't know what `expiringNotificationInterval` is; is that an old name?)

Probably best not to refer to any specific values like 30 or 15 in these comments, since that's configurable, except explicitly when used as an example value.  In the above comment block it says "30 days" and "15 days" but those might actually be wrong depending on configuration, so that needs to be generalized.
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 263 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIvZx5AdO52rhgHj6m:-MfIvZx5AdO52rhgHj6n:b-hhurt0) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L263)):*
> ```Java
>      * <p>daysToExpiration = 30, expiringNotificationInterval = 15;
>      */
>     return (expirationDate.before(now.plusDays(daysToExpiration).toDate())
> ```

These "A before B OR A equals B" constructions are confusing.  They make the code longer than necessary and thus harder to reason about when something simpler will do.  All of this can be rewritten as:

```
return !expirationDate.after(now.plusDays(daysToExpiration).toDate())
&& (lastExpiringNotificationSentDate == null ||
    !lastExpiringNotificationSentDate.plusDays(expirationWarningIntervalDays).isAfter(now));
```

(gonna need proper formatting but you get the idea)


<!-- Sent from Reviewable.io -->

2021-07-23 17:16 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 10 of 13 files reviewed, 10 unresolved discussions (waiting on @CydeWeys, @rachelguan, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 90 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIuHdY5Q_L2l7t8iUs:-MfJJLRmDIyF0hHZZCiT:bdm1g7g) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L90)):*
> Name this variable the same as the config option.
it was already set up this way before this PR. I changed the name to to its config option and changed the corresponding name in RegistryConfig.java. 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 104 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIsRSY1mxjTNmM2i6o:-MfJ2cQj1yqfv0WCpMMq:b-9jwzpt) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L104)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs a more descriptive name, something like `checkEcdsaCurveAllowed()`
</blockquote></details>

this method was already there before this PR. I think it should be done in a separate PR just for existing naming and styling issues of CertificateChecker.java 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 117 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIsBYqB-u_vjnpaS5a:-MfJKICPDod1fxyQwy6Q:b70o0sm) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L117)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use a better error message.  How about:

```
throw new IllegalArgumentException("Unrecognized subclass of PublicKey: " + key.getClass());
```
</blockquote></details>

this method was already there before this PR. I think it should be done in a separate PR just for existing naming and styling issues of CertificateChecker.java 
(I had to reformat the file to pass java formatting test when doing gradlew build.. not sure why that had to be the case though). 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 245 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIuso084eye4H05kab:-MfJKzcc3DnzSzKd4uRk:bdm02x8) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L245)):*
> ```
> /** Returns {@code true} 
> ```
https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/registrar/Registrar.java;l=527?q=registrar.java&ss=nomulus%2Fnomulus

I wrote it that way because of examples like the one above. Should this be the style we keep or should we start writing "Returns whether .." for boolean methods in general. 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 261 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIuOzcAcrAi3tmzfvn:-MfJLNLH3gtlfNvTsgyL:b-wal5gn) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L261)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These are all configured, right?  So the value isn't necessarily these.  (Also I don't know what `expiringNotificationInterval` is; is that an old name?)

Probably best not to refer to any specific values like 30 or 15 in these comments, since that's configurable, except explicitly when used as an example value.  In the above comment block it says "30 days" and "15 days" but those might actually be wrong depending on configuration, so that needs to be generalized.
</blockquote></details>

makes sense. I will remove that part. This was an attempt to show where 30 and 15 in the comment take place so reviewers can have a better understanding of the logic. 

removed <p>daysToExpiration = 30, expiringNotificationInterval = 15;
and replaced all the numbers with variable names.  


<!-- Sent from Reviewable.io -->

2021-07-23 18:50 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 10 of 13 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @rachelguan, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 245 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIuso084eye4H05kab:-MfJgtKcAJwEQBrQwzKU:b-3kl93d) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L245)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

> ```
> /** Returns {@code true} 
> ```
https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/registrar/Registrar.java;l=527?q=registrar.java&ss=nomulus%2Fnomulus

I wrote it that way because of examples like the one above. Should this be the style we keep or should we start writing "Returns whether .." for boolean methods in general. 
</blockquote></details>

Yeah that's pretty old (4 years ago).  I think "Returns whether..." for a function with a boolean return is a better pattern, as it implies the "iff" describing the converse case that the mere "if" here doesn't.


<!-- Sent from Reviewable.io -->

2021-07-23 21:19 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 10 of 13 files reviewed, 6 unresolved discussions (waiting on @CydeWeys, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 245 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIuso084eye4H05kab:-MfK3RqbAWOzfK1uFq0r:b-ulas8s) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L245)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yeah that's pretty old (4 years ago).  I think "Returns whether..." for a function with a boolean return is a better pattern, as it implies the "iff" describing the converse case that the mere "if" here doesn't.
</blockquote></details>

thanks for the explanation and i fixed that. 
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 256 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfItKDA9pyD7y-Oq3d5:-MfK4diz8YtrB9Czo_ns:b-gd6hwq) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L256)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Also that `<` in 1) seems like it should be a `<=` based on the logic below, no?
</blockquote></details>

rewrote the comment. please take a look. thanks!
___
*[core/src/main/java/google/registry/flows/certs/CertificateChecker.java, line 263 at r4](https://reviewable.io/reviews/google/nomulus/1245#-MfIvZx5AdO52rhgHj6m:-MfK4jgX9uD6sqej31Zb:bxyw82n) ([raw file](https://github.com/google/nomulus/blob/c33bc38f413142aaa6ad58a61918a6d300733682/core/src/main/java/google/registry/flows/certs/CertificateChecker.java#L263)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These "A before B OR A equals B" constructions are confusing.  They make the code longer than necessary and thus harder to reason about when something simpler will do.  All of this can be rewritten as:

```
return !expirationDate.after(now.plusDays(daysToExpiration).toDate())
&& (lastExpiringNotificationSentDate == null ||
    !lastExpiringNotificationSentDate.plusDays(expirationWarningIntervalDays).isAfter(now));
```

(gonna need proper formatting but you get the idea)
</blockquote></details>

yep. but i changed the second part to use after instead of isAfter since X509Certificate object only stores the date and now is a DateTime object, the time portion can be omitted. 


<!-- Sent from Reviewable.io -->

2021-07-26 20:20 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245#-:-MfZTYdb-bzcOyUnMtGQ:bnfp4nl)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @rachelguan, @sarahcaseybot, and @weiminyu)

___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 382 at r6](https://reviewable.io/reviews/google/nomulus/1245#-MfZTT1v741f29iKttAK:-MfZTT1v741f29iKttAL:b-e0sp4i) ([raw file](https://github.com/google/nomulus/blob/c6e36fb223c95118af32d6f3958327fcb41eec6a/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L382)):*
> ```Java
>     String certificateStr = certificateChecker.serializeCertificate(certificate);
>     DateTime lastExpiringNotificationSentDate = DateTime.parse("2021-07-01T00:00:00Z");
>     // The first notification date is late and difference between now and
> ```

Line wrapping on these comment lines looks off.


<!-- Sent from Reviewable.io -->

2021-07-26 20:30 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java, line 382 at r6](https://reviewable.io/reviews/google/nomulus/1245#-MfZTT1v741f29iKttAK:-MfZV2E30WBmGiG9IRay:b-k16x8s) ([raw file](https://github.com/google/nomulus/blob/c6e36fb223c95118af32d6f3958327fcb41eec6a/core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java#L382)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Line wrapping on these comment lines looks off.
</blockquote></details>

Note that the java formatter ignores comments behind // but will reformat text between /* */
You can use the latter for multi-line comments if you don't want to format by hand.  


<!-- Sent from Reviewable.io -->

2021-07-26 20:39 UTC, weiminyu approved these changes
> Reviewed 8 of 13 files at r1, 2 of 4 files at r3, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1245)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachelguan)



<!-- Sent from Reviewable.io -->

2021-07-26 21:20 UTC, merged