Fix flaky test issues caused by lack of ofy init
google/nomulus pull request #1246
Opened 2021-07-19 15:20 UTC by gbrodman

2021-07-19 20:17 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1246)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jianglai and @sarahcaseybot)

___
*[core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java, line 358 at r1](https://reviewable.io/reviews/google/nomulus/1246#-Mf-OgGDABT8tTTxb-yf:-Mf-PVPO48cXgp_oR5qO:bsbts52) ([raw file](https://github.com/google/nomulus/blob/6de2c416c3d8ebfd7cfa7f14162b8762f61d1e63/core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java#L358)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Why is this check needed in both places? Can't you just always call DatabaseHelper.assertDetachedFromEntityManager from here since the tm will be checked there?
</blockquote></details>

I think you may be mis-reading the code; the check does not exist in both places (we cannot, in general, guarantee that the check will always work when in JPA mode) 


<!-- Sent from Reviewable.io -->

2021-07-20 01:45 UTC, jianglai requested changes
Where exactly is the code that ensures that ofy is always initiated when `tm()` is called?

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1246#-:-Mf0Zxg67Q083V8R7zcS:b-aruerh)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/test/java/google/registry/beam/rde/RdePipelineTest.java, line 169 at r1](https://reviewable.io/reviews/google/nomulus/1246#-Mf0ZP1f921weGELXzbH:-Mf0ZP1g4htlX8rROKPQ:b-8m6rj4) ([raw file](https://github.com/google/nomulus/blob/6de2c416c3d8ebfd7cfa7f14162b8762f61d1e63/core/src/test/java/google/registry/beam/rde/RdePipelineTest.java#L169)):*
> ```
> TransactionManagerFactory.removeTmOverrideForTest();
> ```
Let's be consistent with the call to `setTmForTest`. Either static import both methods, or import the class instead.


<!-- Sent from Reviewable.io -->

2021-07-20 01:49 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1246)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[core/src/test/java/google/registry/beam/rde/RdePipelineTest.java, line 169 at r1](https://reviewable.io/reviews/google/nomulus/1246#-Mf0ZP1f921weGELXzbH:-Mf0aBh5Av1PlQB1MfvE:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6de2c416c3d8ebfd7cfa7f14162b8762f61d1e63/core/src/test/java/google/registry/beam/rde/RdePipelineTest.java#L169)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> TransactionManagerFactory.removeTmOverrideForTest();
> ```
Let's be consistent with the call to `setTmForTest`. Either static import both methods, or import the class instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-20 01:50 UTC, gbrodman reviewed
In `TransactionManagerFactory` if you call `tm()` without first setting the override, then we inspect the `DatabaseMigrationSchedule`, which is loaded from Datastore. Does that answer your question? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1246#-:-Mf0ajcM83pDWUIDmRFC:bk8dnf1)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-07-20 15:02 UTC, jianglai approved these changes
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1246)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java, line 358 at r1](https://reviewable.io/reviews/google/nomulus/1246#-Mf-OgGDABT8tTTxb-yf:-Mf3QqYO5vYr4GA-QUoV:b-r2gzme) ([raw file](https://github.com/google/nomulus/blob/6de2c416c3d8ebfd7cfa7f14162b8762f61d1e63/core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java#L358)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think you may be mis-reading the code; the check does not exist in both places (we cannot, in general, guarantee that the check will always work when in JPA mode) 
</blockquote></details>

I think Gus is moving the check here to avoid calling `tm()` in `JpaTransactionManagerImplTest`, which would have tried to initiate ofy and failed, right?


<!-- Sent from Reviewable.io -->

2021-07-20 15:05 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1246)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java, line 358 at r1](https://reviewable.io/reviews/google/nomulus/1246#-Mf-OgGDABT8tTTxb-yf:-Mf3RqaDDKfnlgv22bLd:b2nhtan) ([raw file](https://github.com/google/nomulus/blob/6de2c416c3d8ebfd7cfa7f14162b8762f61d1e63/core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java#L358)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I think Gus is moving the check here to avoid calling `tm()` in `JpaTransactionManagerImplTest`, which would have tried to initiate ofy and failed, right?
</blockquote></details>

Yup


<!-- Sent from Reviewable.io -->

2021-07-20 17:14 UTC, merged