Add a cron job to periodically empty out fields on deleted entities t…
google/nomulus pull request #1303
Opened 2021-08-30 15:17 UTC by rachelguan

…hat are at least 18 months old

2021-09-07 12:19 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @rachelguan)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 42 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-AGjfDi_uTO3LN44H:-Mj-AGjfDi_uTO3LN44I:b7r9ybw) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L42)):*
> ```Java
>     auth = Auth.AUTH_INTERNAL_OR_ADMIN)
> /**
>  * An action that removes the fields on contact entities in history entries that have been stored
> ```

Needs a slight rework.  History entries are a Datastore concept; in Cloud SQL we have the `ContactHistory` table.  And just to be clear, this doesn't just affect deleted contacts, it's _all_ information older than a certain amount of time, right?
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 67 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-BPqI6Dc7yzjjhrAD:-Mj-BPqI6Dc7yzjjhrAE:b-84qguk) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L67)):*
> ```Java
>     try {
>       for (ContactHistory contactHistory : getAllHistoryEntriesOlderThan(minMonthsBeforeWipeOut)) {
>         wipeOutContactHistoryPii(contactHistory);
> ```

You need to batch these rather than doing each one individually in a separate transaction.  Doing them individually is going to take way too long.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 80 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-BHclE3x8EilsGqnm:-Mj-BHclE3x8EilsGqnn:b-qbflrt) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L80)):*
> ```Java
>   /** Returns a list of ContactHistory entities that are @param numOfMonths from now. */
>   @VisibleForTesting
>   List<ContactHistory> getAllHistoryEntriesOlderThan(int numOfMonths) {
> ```

Return type should be `ImmutableList<ContactHistory>`.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 81 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-AZNe8lpwuzMBIuzn:-Mj-AZNe8lpwuzMBIuzo:bfz30k9) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L81)):*
> ```Java
>   @VisibleForTesting
>   List<ContactHistory> getAllHistoryEntriesOlderThan(int numOfMonths) {
>     if (!tm().isOfy()) {
> ```

I don't think this check is necessary.  You're already calling `jpaTm()` below, so why does it matter if the primary database mode is Datastore?  You still want to wipe out old contact data in Cloud SQL even when Datastore is primary, no?

If not, then don't check it here in an inner function; just have it be a short-circuit return with a relevant logging statement at the beginning of `run()`.  Something like "Aborting because the primary database isn't Cloud SQL."
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 88 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-BVyd1lD9MQE1GLtf:-Mj-BVyd1lD9MQE1GLtg:b-yi7z2g) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L88)):*
> ```Java
>                       jpaTm()
>                           .query(
>                               "FROM ContactHistory WHERE modificationTime < :date "
> ```

The fundamental error in this query is that it isn't filtering out `ContactHistory` rows that have already had their contact info wiped out.  That means that this action can't resume safely, and the amount of work it will attempt to do with each run will grow without bound as the number of contacts in the system continues to grow over time.  It needs to be smarter.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 98 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-B7zwBtCIMr0tr3VA:-Mj-B7zwBtCIMr0tr3VB:bamgiho) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L98)):*
> ```Java
>           numOfMonths,
>           resultList.stream()
>               .map(ContactHistory::getModificationTime)
> ```

This is way too much to log, and isn't worth logging anyway.  We have millions of contacts in our system.  Just log the number that were wiped out; it's way too much to try to log individual information about any of them in particular.


<!-- Sent from Reviewable.io -->

2021-09-07 14:32 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 0 of 11 files reviewed, 7 unresolved discussions (waiting on @rachelguan)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 92 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-ebZu5i8y8NLDw8Ep:-Mj-ebZu5i8y8NLDw8Eq:b5rvy4y) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L92)):*
> ```Java
>                               ContactHistory.class)
>                           .setParameter("date", clock.nowUtc().minusMonths(numOfMonths))
>                           .getResultList());
> ```

You can't just load all of these into memory; it'll OOM in the future.  There's a _lot_ of `ContactHistory` rows.  You need to batch/cursorify this.  The simplest way would be to run processing in a loop, handling one batch of ~100 at a time with a `WHERE _______ ORDER BY modificationTime ASC LIMIT 100`, ensuring that you have the aforementioned filter in place (the `WHERE`) to ensure that you're not reprocessing the same rows.  Oh, and make sure to add the relevant index(es) so that that query is performant.


<!-- Sent from Reviewable.io -->

2021-09-07 14:33 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @rachelguan)

___
*[core/src/main/java/google/registry/config/RegistryConfig.java, line 1314 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-fFXvAuyl4m73u41J:-Mj-fFXw-6hrj89YhpAa:b-9wa6pc) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/config/RegistryConfig.java#L1314)):*
> ```Java
>     public static int provideMinMonthsBeforeWipeOut(RegistryConfigSettings config) {
>       return config.contactHistory.minMonthsBeforeWipeOut;
>     } 
> ```

Looks like there's some extra trailing spaces here?  Needs a formatting run.


<!-- Sent from Reviewable.io -->

2021-09-07 14:33 UTC, CydeWeys reviewed
Just realized that this wasn't yet sent out for review -- if you weren't done with it yet, and were going to address some of my comments on your own already, feel free to mark them as such.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303#-:-Mj-fMXt7wjCmz7vSBj3:b6qtp2v)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @rachelguan)



<!-- Sent from Reviewable.io -->

2021-09-07 19:51 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @CydeWeys and @rachelguan)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 42 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-AGjfDi_uTO3LN44H:-Mj0dFqm5G8Np6xs_D4S:b-bpn6w7) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L42)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs a slight rework.  History entries are a Datastore concept; in Cloud SQL we have the `ContactHistory` table.  And just to be clear, this doesn't just affect deleted contacts, it's _all_ information older than a certain amount of time, right?
</blockquote></details>

just PII fields of contact info of ContactHistory that's older than 18 months.  the value 18 comes from config file which was why i didn't include the exact amount of time in the javadoc. 
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 80 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-BHclE3x8EilsGqnm:-Mj0l8W06S7mj-s1DDET:b-w0moon) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L80)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Return type should be `ImmutableList<ContactHistory>`.
</blockquote></details>

fixed. I noticed List is being used as the return type. For instance, https://github.com/google/nomulus/blob/master/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L1098
and 
https://github.com/google/nomulus/blob/d57597f40fd27afd34e7090d73f817f434606b47/core/src/main/java/google/registry/model/replay/ReplicateToDatastoreAction.java#L66

should there be a separate PR to fix them? 
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 81 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-AZNe8lpwuzMBIuzn:-Mj0kxYODwFGXE4z7h7h:bh4h7r9) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L81)):*
> essary.  You're already calling jpaTm() below, so why does it matter if the primary database mode is Datastore?  You still want to wipe out old contact data in Cloud SQL even when Datastore is primary, no?
> If not, then don't check it here in an inner function; just have it be a short-circuit return with a relevant logging statement at the beginning of run().  Something like "Aborting b

removed the check. 
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 88 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-BVyd1lD9MQE1GLtf:-Mj0mGP78Jx4UP1WXSl0:bj06gym) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L88)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The fundamental error in this query is that it isn't filtering out `ContactHistory` rows that have already had their contact info wiped out.  That means that this action can't resume safely, and the amount of work it will attempt to do with each run will grow without bound as the number of contacts in the system continues to grow over time.  It needs to be smarter.
</blockquote></details>

that makes sense. would adding a boolean variable in Contact history to indicate pii  field has been wiped out or not. It can be isPiiWiped or something like that. By default the value is set to false. The query will return the ones that have never been wiped..once the pii fields are wiped, change the value of the boolean variable to true.  
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 98 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-B7zwBtCIMr0tr3VA:-Mj0nFiY-XFgaacVz9sc:b-ceisr1) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L98)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is way too much to log, and isn't worth logging anyway.  We have millions of contacts in our system.  Just log the number that were wiped out; it's way too much to try to log individual information about any of them in particular.
</blockquote></details>

what should be logged in this case ? 
___
*[core/src/main/java/google/registry/config/RegistryConfig.java, line 1314 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-fFXvAuyl4m73u41J:-Mj0nuoD1Cg7BWosztRg:bqnioec) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/config/RegistryConfig.java#L1314)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Looks like there's some extra trailing spaces here?  Needs a formatting run.
</blockquote></details>

accidental white space from one of the commit --amend. thanks ! 


<!-- Sent from Reviewable.io -->

2021-09-07 19:52 UTC, rachelguan reviewed
thanks for the review. will fix the the issues that were being pointed out and see if there's other things i should improve based on the comments. thanks!  

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303#-:-Mj0o7i9Bf-QIxfNWOHU:bs8egv8)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @CydeWeys and @rachelguan)



<!-- Sent from Reviewable.io -->

2021-09-14 02:26 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 67 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-BPqI6Dc7yzjjhrAD:-MjX6i0kAJzEeju7MOoT:b-vfqbw8) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L67)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You need to batch these rather than doing each one individually in a separate transaction.  Doing them individually is going to take way too long.
</blockquote></details>

using ScrollableResults as @gbrodman suggested it. 
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 92 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-ebZu5i8y8NLDw8Ep:-MjX6ofN-dhVydahqBQ7:bfc87zg) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L92)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You can't just load all of these into memory; it'll OOM in the future.  There's a _lot_ of `ContactHistory` rows.  You need to batch/cursorify this.  The simplest way would be to run processing in a loop, handling one batch of ~100 at a time with a `WHERE _______ ORDER BY modificationTime ASC LIMIT 100`, ensuring that you have the aforementioned filter in place (the `WHERE`) to ensure that you're not reprocessing the same rows.  Oh, and make sure to add the relevant index(es) so that that query is performant.
</blockquote></details>

noted. added emailAddress IS NOT NULL as another condition to filter out ContactHistory entities that have already been processed. 


<!-- Sent from Reviewable.io -->

2021-09-14 21:03 UTC, weiminyu requested changes
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 2 of 11 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 69 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mja5i-M3hwfT0mjQi1Z:-Mja5i-M3hwfT0mjQi1_:b-vyghqn) ([raw file](https://github.com/google/nomulus/blob/3256e88b0e453c619e1c19903c1d698f57813563/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L69)):*
> ```
> processData(getAllHistoryEntriesOlderThan(minMonthsBeforeWipeOut))
> ```
You may want to set a limit to how many entities you process in this method, call it in a loop.

There are almost 10 million contact histories entities. The first run will turn up a huge number, and one error will have all changes in the transaction rolled back.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 84 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mj_yf5sD928zuF3GWNc:-Mj_yf5sD928zuF3GWNd:bxicjed) ([raw file](https://github.com/google/nomulus/blob/3256e88b0e453c619e1c19903c1d698f57813563/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L84)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     return jpaTm()
>         // email is one of the fields that indicate if the pii data of a ContactHistory entity
>         // have been wiped already. Refer to RFC 5733 for more information
>         .query(
> ```
</details>


Can you use the QueryComposer and get a Stream<ContactHistory>? It fits our goal of reducing plain text queries.

As far as I can tell, the only missing features are setting scroll mode and probably setting no-cache.

Also check with Mike if you have questions about using it.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 55 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mja6a_K7W_DU4ceZs0f:-Mja6a_K7W_DU4ceZs0g:b4iuyx4) ([raw file](https://github.com/google/nomulus/blob/3256e88b0e453c619e1c19903c1d698f57813563/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L55)):*
> ```
> batchSize = 100
> ```
Need a test where the number of entities to be wiped is greater than the patch size.


<!-- Sent from Reviewable.io -->

2021-09-14 21:16 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 2 of 11 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 55 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mja6a_K7W_DU4ceZs0f:-Mja94Zs1_DohcIDEVlE:b-k2ylmm) ([raw file](https://github.com/google/nomulus/blob/3256e88b0e453c619e1c19903c1d698f57813563/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L55)):*
>  a test where the number of entities to be wiped is greater than the patch size.
i have two tests related to that ..
https://github.com/google/nomulus/blob/3256e88b0e453c619e1c19903c1d698f57813563/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L175

didn't label them explicitly that the numbers of entities returned were 450 and 10000, respectively. 


<!-- Sent from Reviewable.io -->

2021-09-14 21:17 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 2 of 11 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 69 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mja5i-M3hwfT0mjQi1Z:-Mja9sGFDTlMpxlOPtvJ:b-imz7lw) ([raw file](https://github.com/google/nomulus/blob/3256e88b0e453c619e1c19903c1d698f57813563/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L69)):*
>  get a Stream? It fits our goal of reducing plain text queries.
> As far as I can tell, the only missing features are setting scroll mode and probably setting no-cache.
> Also check with Mike if you have questions about using it.

why should the limit be set there when the batch size is set to 100. within process data, there's already an iterative method and session gets reset after every 100 entities . 


<!-- Sent from Reviewable.io -->

2021-09-16 20:19 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 2 of 11 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 84 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mj_yf5sD928zuF3GWNc:-MjkFjhA6raC75qk1s9_:b66fadw) ([raw file](https://github.com/google/nomulus/blob/c5f782f46efdf89cbd30a9bb72dc4f601dfbfe52/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L84)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>     return jpaTm()
>         // email is one of the fields that indicate if the pii data of a ContactHistory entity
>         // have been wiped already. Refer to RFC 5733 for more information
>         .query(
> ```

Can you use the QueryComposer and get a Stream<ContactHistory>? It fits our goal of reducing plain text queries.

As far as I can tell, the only missing features are setting scroll mode and probably setting no-cache.

Also check with Mike if you have questions about using it.
</blockquote></details>

since email is embedded in ContactBase.class and based on the discussion in the group chat, we should just use plain text query in this case. 


<!-- Sent from Reviewable.io -->

2021-09-20 17:35 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 98 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-B7zwBtCIMr0tr3VA:-Mk320fl6mlQHPX5JSOT:bd4ytqe) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L98)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

what should be logged in this case ? 
</blockquote></details>

AT info-level, just log how many are found and/or processed in each run in the top level function. 

When you have an error in a loop that you want to log for future debugging but don't want to abort the loop for it, you can use FluentLogger's atMostEvery(int, TimeUnit) method.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 69 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mja5i-M3hwfT0mjQi1Z:-Mk30MCe3YSND6ipbOsO:b-c6w1kz) ([raw file](https://github.com/google/nomulus/blob/c5f782f46efdf89cbd30a9bb72dc4f601dfbfe52/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L69)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

>  get a Stream? It fits our goal of reducing plain text queries.
> As far as I can tell, the only missing features are setting scroll mode and probably setting no-cache.
> Also check with Mike if you have questions about using it.

why should the limit be set there when the batch size is set to 100. within process data, there's already an iterative method and session gets reset after every 100 entities . 
</blockquote></details>

Query.setFetchSize(100) tells Hibernate to read 100 entities from the database in each batch. However, the changes you make are not committed until the end of the transaction which is also the end of the stream. In the case of the initial run, if some transient error pops up during the transaction, all your changes will be rolled back. To make reliable progress, you may want to limit the number entities processed in a transaction, and make a loop to clean up repeatedly until nothing is found. 


<!-- Sent from Reviewable.io -->

2021-09-20 19:42 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 98 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-B7zwBtCIMr0tr3VA:-Mk3iTC04kslObUK0MOG:bi4vki1) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L98)):*
> ```
>     logger.atFine().atMostEvery(2, TimeUnit.SECONDS).log(
>         "Wiped out the last batch of data with %d contact history entities",
>         lastBatchOfData.size());
> ```

Is the following a reasonable way to use FluentLogger's atMostEvery(int, TimeUnit) method ? 
    logger.atFine().atMostEvery(2, TimeUnit.SECONDS).log(
        "Wiped out the last batch of data with %d contact history entities",
        lastBatchOfData.size());
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 69 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mja5i-M3hwfT0mjQi1Z:-Mk3i4dHEkxRKj8F9U-M:bl3d86j) ([raw file](https://github.com/google/nomulus/blob/c5f782f46efdf89cbd30a9bb72dc4f601dfbfe52/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L69)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Query.setFetchSize(100) tells Hibernate to read 100 entities from the database in each batch. However, the changes you make are not committed until the end of the transaction which is also the end of the stream. In the case of the initial run, if some transient error pops up during the transaction, all your changes will be rolled back. To make reliable progress, you may want to limit the number entities processed in a transaction, and make a loop to clean up repeatedly until nothing is found. 
</blockquote></details>

moved jpaTm().transact within the ScrollableResults loop. The code now commits once a batch is full (unless it's the last batch which is outside of the for loop). 


<!-- Sent from Reviewable.io -->

2021-09-20 20:44 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 7 unresolved discussions (waiting on @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 80 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-BHclE3x8EilsGqnm:-Mk3wBZX27p8CTo1wXXQ:b-hb4vh3) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L80)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

fixed. I noticed List is being used as the return type. For instance, https://github.com/google/nomulus/blob/master/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L1098
and 
https://github.com/google/nomulus/blob/d57597f40fd27afd34e7090d73f817f434606b47/core/src/main/java/google/registry/model/replay/ReplicateToDatastoreAction.java#L66

should there be a separate PR to fix them? 
</blockquote></details>

It's not worth going back with a separate PR just to fix that, but just keep in mind for the future that `ImmutableCollection` types are preferred where they make sense (and it does make sense here).
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 88 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-BVyd1lD9MQE1GLtf:-Mk3wNw01cNLYwQqBz6Z:b-maxusd) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L88)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

that makes sense. would adding a boolean variable in Contact history to indicate pii  field has been wiped out or not. It can be isPiiWiped or something like that. By default the value is set to false. The query will return the ones that have never been wiped..once the pii fields are wiped, change the value of the boolean variable to true.  
</blockquote></details>

Per offline discussion, we determined that the email address is required in EPP and thus always present, so checking if it's null is a good proxy to see if the data has been wiped out without needing to separately track a boolean for that purpose.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 45 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3vws_2FiqrVoYMEl7:-Mk3vws_2FiqrVoYMEl8:bcm3d2u) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L45)):*
> ```Java
>     auth = Auth.AUTH_INTERNAL_OR_ADMIN)
> /**
>  * An action that wipes out the pii fields of ContactHistory entities that are older than a certain
> ```

PII is an acronym, so it should be capitalized.  And it should be `{@link ContactHistory}` so people can click through to it.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 132 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3wcfw4Fl-Gp4dt3uX:-Mk3wcfw4Fl-Gp4dt3uY:b3h443r) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L132)):*
> ```Java
>     numOfProcessedEntities.addAndGet(lastBatchOfData.size());
>     logger.atInfo().log(
>         "Wiped out pii fields of %d ContactHistory entities", numOfProcessedEntities.get());
> ```

PII is an acronym and should be capitalized.  Also you're missing periods at the end of these log lines.  (Lacking period in log lines makes it a little harder to understand them, as it's not immediately clear as you're reading through the lines where a sentence absolutely stops vs where it might be continued on the next line.)


<!-- Sent from Reviewable.io -->

2021-09-20 20:52 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 10 unresolved discussions (waiting on @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 75 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3yqqIDf9riTtIJrZI:-Mk3yqqIDf9riTtIJrZJ:bcmekwq) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L75)):*
> ```Java
>       response.setStatus(SC_OK);
>     } catch (Exception e) {
>       logger.atWarning().withCause(e).log("Exception thrown when wiping out contact history pii");
> ```

There's more lower-case acronyms around this section.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 88 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3yMmg5WlljO4jaTFb:-Mk3yMmg5WlljO4jaTFc:b-mmscoo) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L88)):*
> ```
> WHERE modificationTime < :numOfMonthsFromNow
> ```

A better name would help clarify this.  "A number of months from now" implies, to me, a date in the future, but here you're talking about a date 18 months in the past.  I'd name this parameter something like `wipeoutTime`.
___
*[core/src/test/java/google/registry/model/history/ContactHistoryTest.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3xhCG3GMyd3xo5r-O:-Mk3xhCG3GMyd3xo5r-P:b36ejog) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/test/java/google/registry/model/history/ContactHistoryTest.java#L188)):*
> ```Java
>     assertThat(contactHistory.getContactBase().get().getFaxNumber()).isNotNull();
> 
>     contactHistory = contactHistory.asBuilder().wipeOutPii().build();
> ```

A good general programming tip is to not reuse local variable names.  This would be clearer if, rather than reusing the existing variable name, you had a new one named something like `wipedContactHistory`, and then it's clearer at a glance that the next batch of assertions is on a different thing than the previous batch of assertions.


<!-- Sent from Reviewable.io -->

2021-09-20 21:06 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 16 unresolved discussions (waiting on @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 99 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk4-K4J8ZphqoE8tntP:-Mk4-K4J8ZphqoE8tntQ:bafp3hm) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L99)):*
> ```Java
> 
>   @VisibleForTesting
>   int processData(ScrollableResults oldContactHistoryData) {
> ```

`processData()` is super-generic (that could be just about any method in the entire codebase).  Pick something more specific that encapsulates what's actually going on here.  Something like `wipeOutContactHistoryData()` would be good.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 103 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk400Bm8gFKbFPzRQdL:-Mk400Bm8gFKbFPzRQdM:bf7bflh) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L103)):*
> ```Java
>     ImmutableList.Builder<ContactHistory> contactHistoryBatchBuilder =
>         new ImmutableList.Builder<>();
>     for (int i = 1; oldContactHistoryData.next(); i = (i + 1) % wipeOutQueryBatchSize) {
> ```

What's going on here?  Why is a for loop necessary rather than a simple for-in loop, or maybe a while loop is best here?  What's i and why does an i of zero need special handling inside the for loop?  Refactor this all to be simpler and need less special handling.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 103 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk40wF24EkXjBhqMniV:-Mk40wF24EkXjBhqMniW:b-ls3nyp) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L103)):*
> ```
> i = (i + 1) % wipeOutQueryBatchSize
> ```

What is this?  The query batch size is 100 so how does this even work?
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 115 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk4-Xc3D2Dlq_qE5r_6:-Mk4-Xc3D2Dlq_qE5r_7:b-h0ls8v) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L115)):*
> ```Java
>                       "Wiped out a full batch of data with %d contact history entities",
>                       fullBatchOfContactHistoryData.size());
>                   numOfProcessedEntities.addAndGet(wipeOutQueryBatchSize);
> ```

The use of an `AtomicInteger` here is unnecessary.  You aren't doing any multithreading, and you can simply return this inside the lambda and then `+=` it to a normal integer outside the lambda.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 121 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk4-mmADFlCkN6ELavX:-Mk4-mmADFlCkN6ELavY:b-5bpq9q) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L121)):*
> ```Java
>         jpaTm().getEntityManager().clear();
>         // reset contact history batch after the transaction
>         contactHistoryBatchBuilder = new ImmutableList.Builder<>();
> ```

This is not a good way to do this.  You're reusing a local variable when that's not necessary.  Simply define `contactHistoryBatchBuilder` inside the for loop, in the first line, and then Java's garbage collector will automatically take care of it at the end.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 127 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3zcEt6fnZmwLiqnMy:-Mk3zcEt6fnZmwLiqnMz:bctjltr) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L127)):*
> ```
> .atMostEvery(2, TimeUnit.SECONDS).
> ```

This strikes me as unnecessary and potentially confusing.  We don't use this mechanism anywhere else, and it would be a bit hard to understand the logs if you see it occur in the logs a smaller number of times than processing actually occurs.  We also don't use the `FINE` logging level anywhere; I'd just stick with `INFO`.

Also, if this is the last batch of data, wouldn't you only see it once?  Why rate-limit it?


<!-- Sent from Reviewable.io -->

2021-09-20 21:46 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 45 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3vws_2FiqrVoYMEl7:-Mk46E7O01NoPAGoN995:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L45)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Actually, you should expand the acronym here at its first use.  Something like:  "An action that wipes out the fields containing Personally Identifiable Information (PII) older than a certain amount of time.\n\n<p>...."
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 75 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3yqqIDf9riTtIJrZI:-Mk406lm3Rtej4bYHiEp:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L75)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There's more lower-case acronyms around this section.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 88 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3yMmg5WlljO4jaTFb:-Mk435a830blE49Z-VTK:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L88)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

> ```
> WHERE modificationTime < :numOfMonthsFromNow
> ```

A better name would help clarify this.  "A number of months from now" implies, to me, a date in the future, but here you're talking about a date 18 months in the past.  I'd name this parameter something like `wipeoutTime`.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 115 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk4-Xc3D2Dlq_qE5r_6:-Mk47aMQDoyPySyuZE6s:b-auvghn) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L115)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The use of an `AtomicInteger` here is unnecessary.  You aren't doing any multithreading, and you can simply return this inside the lambda and then `+=` it to a normal integer outside the lambda.
</blockquote></details>

since the ```numOfProcessedEntities``` is incremented within ```jpaTm().transact()```, which is a lambda expression, intelliJ was complaining it and made it a ```AtomicInteger```
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 127 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3zcEt6fnZmwLiqnMy:-Mk46xKj03Vp4OMF9VbV:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L127)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

> ```
> .atMostEvery(2, TimeUnit.SECONDS).
> ```

This strikes me as unnecessary and potentially confusing.  We don't use this mechanism anywhere else, and it would be a bit hard to understand the logs if you see it occur in the logs a smaller number of times than processing actually occurs.  We also don't use the `FINE` logging level anywhere; I'd just stick with `INFO`.

Also, if this is the last batch of data, wouldn't you only see it once?  Why rate-limit it?
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 132 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3wcfw4Fl-Gp4dt3uX:-Mk44WJIBJUSm9p6RlQx:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L132)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

PII is an acronym and should be capitalized.  Also you're missing periods at the end of these log lines.  (Lacking period in log lines makes it a little harder to understand them, as it's not immediately clear as you're reading through the lines where a sentence absolutely stops vs where it might be continued on the next line.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-20 22:15 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/model/history/ContactHistoryTest.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3xhCG3GMyd3xo5r-O:-Mk4GJzBE8ylsiqdd78U:b-5egrf2) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/test/java/google/registry/model/history/ContactHistoryTest.java#L188)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

A good general programming tip is to not reuse local variable names.  This would be clearer if, rather than reusing the existing variable name, you had a new one named something like `wipedContactHistory`, and then it's clearer at a glance that the next batch of assertions is on a different thing than the previous batch of assertions.
</blockquote></details>

noted but this case is no longer in the the current version of the PR. 


<!-- Sent from Reviewable.io -->

2021-09-20 22:15 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 99 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk4-K4J8ZphqoE8tntP:-Mk4GiSd220x08YAbnZR:bem1g37) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L99)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`processData()` is super-generic (that could be just about any method in the entire codebase).  Pick something more specific that encapsulates what's actually going on here.  Something like `wipeOutContactHistoryData()` would be good.
</blockquote></details>

renamed. 


<!-- Sent from Reviewable.io -->

2021-09-20 22:52 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 103 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk400Bm8gFKbFPzRQdL:-Mk4JWHv5iOHk1inxJr9:bkctzj2) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L103)):*
> ide the for loop, in the first line, and then 
https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/batch/DeleteProberDataAction.java;l=197-212?q=scrollableResults&ss=nomulus%2Fnomulus

similar way of using ScrollableResults from hibernate. This can be written as either for or while loop. 
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 103 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk40wF24EkXjBhqMniV:-Mk4Jz7U2Pwd0WBk3REq:bn7xeo6) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L103)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

> ```
> i = (i + 1) % wipeOutQueryBatchSize
> ```

What is this?  The query batch size is 100 so how does this even work?
</blockquote></details>

starting at 1 instead of 0 to avoid db flush and session refreshing at the very beginning. The batch size in our case is 100. 

from i = 1  to 99 which becomes 0 after mod, all 99 entities are stored in the immutable list. ```wipeOutContactHistoryPii()``` method is called to erase pii from all contacts in the list. The list then gets resets. 
i then starts from 1 again. 

if we want to keep this logic, we can change the wipeOutQueryBatchSize to 101 to make sure 100 entities are in the list each time. 
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 121 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk4-mmADFlCkN6ELavX:-Mk4OJgSECtpaXY9h2GD:b-3rwoa6) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L121)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is not a good way to do this.  You're reusing a local variable when that's not necessary.  Simply define `contactHistoryBatchBuilder` inside the for loop, in the first line, and then Java's garbage collector will automatically take care of it at the end.
</blockquote></details>

if ```contactHistoryBatchBuilder``` is defined in the first line in the for loop, how is it even going to be able to store more than one entity within in the list. 


<!-- Sent from Reviewable.io -->

2021-09-20 23:13 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 103 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk40wF24EkXjBhqMniV:-Mk4U3Ry36sZeFwbf4G_:b9fykre) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L103)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

starting at 1 instead of 0 to avoid db flush and session refreshing at the very beginning. The batch size in our case is 100. 

from i = 1  to 99 which becomes 0 after mod, all 99 entities are stored in the immutable list. ```wipeOutContactHistoryPii()``` method is called to erase pii from all contacts in the list. The list then gets resets. 
i then starts from 1 again. 

if we want to keep this logic, we can change the wipeOutQueryBatchSize to 101 to make sure 100 entities are in the list each time. 
</blockquote></details>

rewrote this loop; using a while loop instead. hopefully more readable in this case. 


<!-- Sent from Reviewable.io -->

2021-09-21 01:00 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 15 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 69 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mja5i-M3hwfT0mjQi1Z:-Mk4pe784d3yvCTj0aKn:b3dill5) ([raw file](https://github.com/google/nomulus/blob/c5f782f46efdf89cbd30a9bb72dc4f601dfbfe52/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L69)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

moved jpaTm().transact within the ScrollableResults loop. The code now commits once a batch is full (unless it's the last batch which is outside of the for loop). 
</blockquote></details>

This won't work. A query must be run in a transaction, and its result set also must be accessed in the same transaction.
The tests didn't catch the problem because none of them call action.run().
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 204 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mk4oYzD2qlayqBjQ1lO:-Mk4oYzD2qlayqBjQ1lP:b-4v7bfy) ([raw file](https://github.com/google/nomulus/blob/c5f782f46efdf89cbd30a9bb72dc4f601dfbfe52/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L204)):*
> ```
>  ImmutableList<ContactHistory> persistLotsOfContactHistoryEntities(
> ```
nit: move this method behind the last test method.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 46 at r9](https://reviewable.io/reviews/google/nomulus/1303#-Mk4qYRvBnXQpxaC0nFo:-Mk4qYRvBnXQpxaC0nFp:b-hy21i3) ([raw file](https://github.com/google/nomulus/blob/00768b5c8727b76277c18e55d83c84d063c45668/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L46)):*
> ```Java
> /** Unit tests for {@link WipeOutContactHistoryPiiAction}. */
> @DualDatabaseTest
> class WipeOutContactHistoryPiiActionTest {
> ```

You need to have at least one end-to-end test method that calls action.run().


<!-- Sent from Reviewable.io -->

2021-09-21 01:10 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 15 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 98 at r1](https://reviewable.io/reviews/google/nomulus/1303#-Mj-B7zwBtCIMr0tr3VA:-Mk4s7en06gq2iFowzFt:b-yo24it) ([raw file](https://github.com/google/nomulus/blob/878656c9fbf86d05cb8a4a0a0077d0ca2783336d/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L98)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

> ```
>     logger.atFine().atMostEvery(2, TimeUnit.SECONDS).log(
>         "Wiped out the last batch of data with %d contact history entities",
>         lastBatchOfData.size());
> ```

Is the following a reasonable way to use FluentLogger's atMostEvery(int, TimeUnit) method ? 
    logger.atFine().atMostEvery(2, TimeUnit.SECONDS).log(
        "Wiped out the last batch of data with %d contact history entities",
        lastBatchOfData.size());

</blockquote></details>

No. It is one-time log and you can log it normally or ignore it. Since two statements down there is the final summary log, you probably don't need to log this statement. 

The atMostEvery method is used when the number of log statements is large or non-deterministic, such that you cannot safely log everything.  Mostly in the below kinds of scenarios:

while (input.hasNext()) {
  try {
    process(input.next());
   } catch (Exception e) {
     // Errors can be tolerated. Logging some for debugging. 
     logger.atInfo().atMostEvery(...).log(...);
   }
}


<!-- Sent from Reviewable.io -->

2021-09-21 20:41 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 69 at r4](https://reviewable.io/reviews/google/nomulus/1303#-Mja5i-M3hwfT0mjQi1Z:-Mk94jpd9iWRG5R0AfnV:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/c5f782f46efdf89cbd30a9bb72dc4f601dfbfe52/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L69)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This won't work. A query must be run in a transaction, and its result set also must be accessed in the same transaction.
The tests didn't catch the problem because none of them call action.run().
</blockquote></details>

done
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 46 at r9](https://reviewable.io/reviews/google/nomulus/1303#-Mk4qYRvBnXQpxaC0nFo:-Mk94lIu-Mp6Y8iwZLLW:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/00768b5c8727b76277c18e55d83c84d063c45668/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L46)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

You need to have at least one end-to-end test method that calls action.run().
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-09-21 20:56 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 15 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 116 at r12](https://reviewable.io/reviews/google/nomulus/1303#-Mk95fjc-z7aPqIOeB3Q:-Mk95fjc-z7aPqIOeB3R:bqjx1fr) ([raw file](https://github.com/google/nomulus/blob/c04f3323dc077baaac202a064f0e00f362327f36/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L116)):*
> ```
>         jpaTm()
>             .transact(
> ```
This is a recursive call to JpaTransactionManager.transact and is a NOOP. Only the outmost transaction would commit. (See JpaTransactionManagerImpl.transact() for details.)

Therefore, if we want to process in batches, we will have to let the outmost transaction commit. A side effect is of it is we have to run the query for wipeout candidates repeatedly.

You need to:
1. remove the jpaTm().transact call here.
2. Change the while loop to something like while (numEntities< batchSize && scrollableResults.next())
3.  Change the run() method to something like (you should refactor to make it look better):
while (true) {
  if (jpaTm().transact(() -> wipeOutContactHistoryData(getAllHistoryEntriesOlderThan(minMonthsBeforeWipeOut))) < batchSize) {
    break;
  }
}
4. Increase the configured batchSize to some larger number, say 500 or 1000.
5. Remove the flush() and clear() calls below. 


<!-- Sent from Reviewable.io -->

2021-09-21 21:04 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 10 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 43 at r12](https://reviewable.io/reviews/google/nomulus/1303#-Mk9A-f44kVorp2l7DJQ:-Mk9A-f44kVorp2l7DJR:b383i1o) ([raw file](https://github.com/google/nomulus/blob/c04f3323dc077baaac202a064f0e00f362327f36/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L43)):*
> ```Java
>     auth = Auth.AUTH_INTERNAL_OR_ADMIN)
> /**
>  * An action that wipes out the fields containing Personal Identifiable Information (PII) of {@link
> ```

This has now gotten too long for the Javadoc summary fragment, and needs to be broken into a summary fragment and then additional paragraphs of explanation.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 1 at r12](https://reviewable.io/reviews/google/nomulus/1303#-Mk99pi07gj3bM0bP-jY:-Mk99pi07gj3bM0bP-jZ:b-dzvezy) ([raw file](https://github.com/google/nomulus/blob/c04f3323dc077baaac202a064f0e00f362327f36/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L1)):*
> ```Java
> // Copyright 2017 The Nomulus Authors. All Rights Reserved.
> ```

Copyright year is wrong.


<!-- Sent from Reviewable.io -->

2021-09-21 21:07 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 10 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 121 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk4-mmADFlCkN6ELavX:-Mk9AGulBC3h847tojz9:b-pazkf5) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L121)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

if ```contactHistoryBatchBuilder``` is defined in the first line in the for loop, how is it even going to be able to store more than one entity within in the list. 
</blockquote></details>

It seems to me like you're overloading one loop to do two things in a way that hinders legibility.  To me, it seems what's really going on is:

```
while there is still data left to process:
  batch = []
  while size of batch < max batch size:
    add next item to batch
  process batch
```

That seems to make the most sense, and won't involve reusing the same local variables or needing to do modulus arithmetic.


<!-- Sent from Reviewable.io -->

2021-09-21 21:25 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 10 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 43 at r12](https://reviewable.io/reviews/google/nomulus/1303#-Mk9A-f44kVorp2l7DJQ:-Mk9DQEV3pMkb6YxG4ng:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c04f3323dc077baaac202a064f0e00f362327f36/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L43)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This has now gotten too long for the Javadoc summary fragment, and needs to be broken into a summary fragment and then additional paragraphs of explanation.
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 1 at r12](https://reviewable.io/reviews/google/nomulus/1303#-Mk99pi07gj3bM0bP-jY:-Mk9DTLK0mJTe0Xf6xwm:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c04f3323dc077baaac202a064f0e00f362327f36/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L1)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Copyright year is wrong.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-22 14:49 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 13 unresolved discussions (waiting on @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 90 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCy1EoABs-lJRDv4Q5:-MkCy1EoABs-lJRDv4Q6:bs2ttk2) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L90)):*
> ```Java
>    */
>   @VisibleForTesting
>   Query getAllHistoryEntriesOlderThan(int numOfMonths) {
> ```

Should this `Query` here have a typed associated with it?  Surely it's a `Query<_____>` right?  `Query<ContactHistory>` perhaps?  Isn't IntelliJ throwing an error here for inappropriate use of a generic type?
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 186 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCwKI_Eb6qi6kBwsVh:-MkCwKIa0UKEzOrbsgQp:b-njjn41) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L186)):*
> ```Java
>             () -> {
>               int actualNumOfOldEntities = 0;
>               ImmutableList<ContactHistory> entities =
> ```

It seems to me like only this line needs to be inside the transaction and everything else need not.  On the balance of things it's generally better not to put test assertions inside of transactions, because of the way that can interact with transaction retrying (i.e. it might trigger it).
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 192 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCwjqK-a7-iGeWSNRo:-MkCwjqK-a7-iGeWSNRp:b-twd54o) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L192)):*
> ```Java
>                           .getResultList());
>               for (ContactHistory entity : entities) {
>                 assertThat(expectedToBeWipedOut.contains(entity)).isTrue();
> ```

Why not use the `containsExactlyElementsIn()` assertion?  Why is this for loop necessary?  This is a badly written assertion anyway, as the failure message will only contain the first missing one, not all of them.  Generally you shouldn't be making assertions inside of loops.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 195 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxD3U6HyJspHsR7Ij:-MkCxD3U6HyJspHsR7Ik:b-1oq046) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L195)):*
> ```Java
>                 actualNumOfOldEntities++;
>               }
>               assertThat(actualNumOfOldEntities).isEqualTo(expectedToBeWipedOut.size());
> ```

Assert that a given collection is a specific size is a pretty weak assertion that doesn't add much testing value.  You should be making assertions on the contents of the collection.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 200 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxX038fZxpUZ7jh6c:-MkCxX038fZxpUZ7jh6d:b7di3e3) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L200)):*
> ```Java
> 
>   @TestSqlOnly
>   void wipeOutContactHistoryData_testOneBatch_Success() {
> ```

"Success" shouldn't be capitalized in this method name, here and elsewhere.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 209 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxaaq3BEt-rGkWUdr:-MkCxaar8TxZ5UEarLUn:b3kvqik) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L209)):*
> ```Java
>                         action.wipeOutContactHistoryData(
>                             action.getAllHistoryEntriesOlderThan(MIN_MONTHS_BEFORE_WIPE_OUT))))
>         .isEqualTo(expectedToBeWipedOut.size());
> ```

This is a weak assertion.  You need to actually inspect the entities and ensure that the relevant fields were wiped out.  Here and elsewhere.  You'll probably want to add two helper methods in this test class, something like:

```
void ensurePiiFieldsWipedOut(Collection<ContactHistory> contactHistories) { ... }
void ensurePiiFieldsStillPresent(Collection<ContactHistory> contactHistories) { ... }
```

(each of which makes a single collective assertion about all contents of the collection)
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 311 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCyXI2AiyteALkZ1Ad:-MkCyXI2AiyteALkZ1Ae:b-o6hmeo) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L311)):*
> ```Java
>               assertThat(contactHistoryFromDb.getParentVKey())
>                   .isEqualTo(contactHistory.getParentVKey());
>               ContactBase contactResourceFromDb = contactHistoryFromDb.getContactBase().get();
> ```

Nit: This isn't a "contact resource from the database", this is the embedded portion of the contact history that contains the contact details.  "Contact resource from the database" to me would imply that you're loading a row from the `Contact` table, which is not what's happening here.
___
*[core/src/test/java/google/registry/model/history/ContactHistoryTest.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3xhCG3GMyd3xo5r-O:-MkCysXkBvoSpzANIoxt:b-6f6mag) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/test/java/google/registry/model/history/ContactHistoryTest.java#L188)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

noted but this case is no longer in the the current version of the PR. 
</blockquote></details>

Is it?  I still see `contactHistory` being reused.


<!-- Sent from Reviewable.io -->

2021-09-23 14:02 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 12 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 121 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk4-mmADFlCkN6ELavX:-MkFIhvjDKTjZs0skIPm:bwfkcgn) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L121)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It seems to me like you're overloading one loop to do two things in a way that hinders legibility.  To me, it seems what's really going on is:

```
while there is still data left to process:
  batch = []
  while size of batch < max batch size:
    add next item to batch
  process batch
```

That seems to make the most sense, and won't involve reusing the same local variables or needing to do modulus arithmetic.
</blockquote></details>

no longer using a list and the loop is now in run()
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 116 at r12](https://reviewable.io/reviews/google/nomulus/1303#-Mk95fjc-z7aPqIOeB3Q:-MkD6NGR7n7_AbaKYi0A:b-rnrapz) ([raw file](https://github.com/google/nomulus/blob/c04f3323dc077baaac202a064f0e00f362327f36/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L116)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>         jpaTm()
>             .transact(
> ```
This is a recursive call to JpaTransactionManager.transact and is a NOOP. Only the outmost transaction would commit. (See JpaTransactionManagerImpl.transact() for details.)

Therefore, if we want to process in batches, we will have to let the outmost transaction commit. A side effect is of it is we have to run the query for wipeout candidates repeatedly.

You need to:
1. remove the jpaTm().transact call here.
2. Change the while loop to something like while (numEntities< batchSize && scrollableResults.next())
3.  Change the run() method to something like (you should refactor to make it look better):
while (true) {
  if (jpaTm().transact(() -> wipeOutContactHistoryData(getAllHistoryEntriesOlderThan(minMonthsBeforeWipeOut))) < batchSize) {
    break;
  }
}
4. Increase the configured batchSize to some larger number, say 500 or 1000.
5. Remove the flush() and clear() calls below. 
</blockquote></details>

done. 
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 90 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCy1EoABs-lJRDv4Q5:-MkFJIqN4U7_Ps7rQwx1:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L90)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should this `Query` here have a typed associated with it?  Surely it's a `Query<_____>` right?  `Query<ContactHistory>` perhaps?  Isn't IntelliJ throwing an error here for inappropriate use of a generic type?
</blockquote></details>

done
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 186 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCwKI_Eb6qi6kBwsVh:-MkHxk3Q4N9K9Y5FR-Yi:b-q9t1m1) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L186)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It seems to me like only this line needs to be inside the transaction and everything else need not.  On the balance of things it's generally better not to put test assertions inside of transactions, because of the way that can interact with transaction retrying (i.e. it might trigger it).
</blockquote></details>

fixed that/
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 192 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCwjqK-a7-iGeWSNRo:-MkFJSRV3hSWGHeMs6j5:bwynpv2) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L192)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why not use the `containsExactlyElementsIn()` assertion?  Why is this for loop necessary?  This is a badly written assertion anyway, as the failure message will only contain the first missing one, not all of them.  Generally you shouldn't be making assertions inside of loops.
</blockquote></details>

or directly comparing the two lists which is what i have now. 
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 195 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxD3U6HyJspHsR7Ij:-MkFIuAN9P342ygkmqbb:b-b5c35t) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L195)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Assert that a given collection is a specific size is a pretty weak assertion that doesn't add much testing value.  You should be making assertions on the contents of the collection.
</blockquote></details>

changed.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 200 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxX038fZxpUZ7jh6c:-MkFIwAI9j-RX1VrFjQl:b-b5c35t) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L200)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

"Success" shouldn't be capitalized in this method name, here and elsewhere.
</blockquote></details>

changed.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 209 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxaaq3BEt-rGkWUdr:-MkFIyPb8gGEeGl7s4Rn:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L209)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is a weak assertion.  You need to actually inspect the entities and ensure that the relevant fields were wiped out.  Here and elsewhere.  You'll probably want to add two helper methods in this test class, something like:

```
void ensurePiiFieldsWipedOut(Collection<ContactHistory> contactHistories) { ... }
void ensurePiiFieldsStillPresent(Collection<ContactHistory> contactHistories) { ... }
```

(each of which makes a single collective assertion about all contents of the collection)
</blockquote></details>

done
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 311 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCyXI2AiyteALkZ1Ad:-MkFJ8BT7cu4Yb0BH8_v:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L311)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Nit: This isn't a "contact resource from the database", this is the embedded portion of the contact history that contains the contact details.  "Contact resource from the database" to me would imply that you're loading a row from the `Contact` table, which is not what's happening here.
</b [...]

2021-09-23 20:51 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 16 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 80 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJNnHO32nrOczGTW6r:-MkJNnHO32nrOczGTW6s:bhkwqxw) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L80)):*
> ```Java
>     int totalNumOfProcessedEntities = 0;
>     try {
>       while (true) {
> ```

Infinite loops are dangerous and don't express what's going on in as clear of a way as possible.  I think you can rewrite this as follows:

```
int totalWipedOut = 0;
do {
  int batchWipedOut = .....;
  totalWipedOut += batchWipedOut;
} while (batchWipedOut > 0)
```

This way it keeps running until it has no work left to do.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 88 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJONoc4rVmcV0Cjfcx:-MkJONoc4rVmcV0Cjfcy:b-h6n3mj) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L88)):*
> ```Java
>                             getAllHistoryEntitiesOlderThan(minMonthsBeforeWipeOut)));
>         totalNumOfProcessedEntities += numOfProcessedEntities;
>         // If the set of data contains less than the default number of entities to process, it means
> ```

I don't believe this is necessarily a safe assumption to make -- I think this could lead to an early termination.  Or, alternatively, the last batch could by change happen to be exactly the same size as the full batch, so then the next run of the query will return 0 entities, and I'm not 100% sure that's being handled correctly.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 95 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJPKPXDNC3BndA_nXX:-MkJPKPXDNC3BndA_nXY:b-dc6wz3) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L95)):*
> ```Java
>       }
>       logger.atInfo().log(
>           "Processed total number of %d ContactHistory entities.", totalNumOfProcessedEntities);
> ```

"Processed" is too generic.  Say "Wiped out" here.  "Processed" is also misleading because one could think of it as all the contact histories older than 18 months, when it's really just the ones that needed to be wiped out.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 98 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJPfIM1f4IZ7Ty39hc:-MkJPfIM1f4IZ7Ty39hd:bbu7ghx) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L98)):*
> ```Java
>       response.setStatus(SC_OK);
>     } catch (Exception e) {
>       logger.atWarning().withCause(e).log(
> ```

Make this `atSevere()` for better visibility.  We don't expect this to ever happen in the course of normal operation, so when it does, we want to be alerted to that fact.  And if this is continually failing, but only logging at WARNING, then we may not realize that it's failing, which is bad.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 124 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJOgMT17eIUC2aD_Ma:-MkJOgMT17eIUC2aD_Mb:bmdzj8b) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L124)):*
> ```Java
>                     + "AND email IS NOT NULL ORDER BY modificationTime ASC",
>                 ContactHistory.class)
>             .setParameter("wipeOutTime", clock.nowUtc().minusMonths(numOfMonths));
> ```

This means that, each time you run the query, you're using a different time calculation, which makes things harder to reason about (and also means that the amount of data under consideration will steadily expand as the action continues running).  You don't want that.  What you want is a single `DateTime` that is calculated once, at the very beginning of the action's execution.  Something like ...

```
public void run() {
  DateTime wipeOutTime = clock.nowUtc().minusMonths(numOfMonths);
  logger.atInfo().log("Wiping out all contact histories prior to %s.", wipeOutTime);
  ...
  ... getAllHistoryEntitiesOlderThan(wipeOutTime) ...;
  
}

```
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 125 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJL8V00H-6SXyb8vja:-MkJL8V00H-6SXyb8vjb:b4mvsak) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L125)):*
> ```Java
>                 ContactHistory.class)
>             .setParameter("wipeOutTime", clock.nowUtc().minusMonths(numOfMonths));
>     query
> ```

Is there a need to have the `query` local variable at all?  It seems to me like this entire method could simply be one long return statement:

```
return jpaTm().query(...).setParameter(...).unwrap(...).others(....).getResultStream();
```
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 128 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJLrAL0PfKTLUT66jC:-MkJLrAL0PfKTLUT66jD:bfp9pot) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L128)):*
> ```Java
>         .unwrap(Query.class)
>         .setCacheMode(CacheMode.IGNORE)
>         .setFetchSize(wipeOutQueryBatchSize)
> ```

What's the meaning behind having a separate fetch size and number of max results?  Does this even make sense anymore?  Especially because the fetch size is set to 1000, which is twice the max results of the entire query, it seems like something isn't going to work right here?  Shouldn't the fetch size be smaller than the max results of the query?
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 136 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJMF2e5iU7C15MVChJ:-MkJMF2e5iU7C15MVChK:b-3f11ub) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L136)):*
> ```Java
>   @VisibleForTesting
>   int wipeOutContactHistoryData(Stream<ContactHistory> contactHistoryEntities) {
>     AtomicInteger numOfEntities = new AtomicInteger(0);
> ```

A better way to rewrite this method body is:

```
ImmutableSet<ContactHistory> wipedOutContactHistories = contactHistoryEntities.stream().map(entity -> entity.asBuilder().wipeOutPii().build()).collect(toImmutableSet());
jpaTm().updateAll(wipedOutContactHistories);
return wipedOutContactHistories.size();
```

That way you don't need to bother with an `AtomicInteger` (which is still not the right construct for this use case; that's for concurrency-related code only), and you're also batching all the updates into a single `updateAll()` call rather than 500 calls to `update()` which in theory could be made to be more efficient.
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 450 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJPupa0FQsx0iEOjS1:-MkJPupb1HbgTNa0ue8S:bfr9rk6) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/config/files/default-config.yaml#L450)):*
> ```YAML
>   minMonthsBefor [...]

2021-09-23 20:53 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 16 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/model/history/ContactHistoryTest.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3xhCG3GMyd3xo5r-O:-MkJQqRq4R0gtbZKwqkW:b-cszgjm) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/test/java/google/registry/model/history/ContactHistoryTest.java#L188)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

done
</blockquote></details>

Is it done?  I still see `contactHistory` being reused.


<!-- Sent from Reviewable.io -->

2021-09-23 20:54 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 16 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/model/history/ContactHistoryTest.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3xhCG3GMyd3xo5r-O:-MkJQwuD8B54fW-6RgF2:bouq0mj) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/test/java/google/registry/model/history/ContactHistoryTest.java#L188)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is it done?  I still see `contactHistory` being reused.
</blockquote></details>

To be clear, my suggestion is to change this line to `ContactHistory wipedContactHistory = contactHistory.asBuilder().wipeOutPii().build();` and then have every subsequent line start with `assertThat(wipedContactHistory....)`


<!-- Sent from Reviewable.io -->

2021-09-23 20:59 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 19 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 122 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJJOE1E60ksuznvTn8:-MkJJOE1E60ksuznvTn9:b-89tb2c) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L122)):*
> ```
> ORDER BY modificationTime ASC
> ```
I don't see why "order by" is needed as long as we are sure that our wipeout job can work down the backlog. 
Ordering would only be an issue if we cannot work down the backlog fast enough AND out of compliance by 2 days is worse than out of compliance by 1 day. 
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 136 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJMF2e5iU7C15MVChJ:-MkJRe0QDmbmQ2K3kGP3:b-mac6oz) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L136)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

A better way to rewrite this method body is:

```
ImmutableSet<ContactHistory> wipedOutContactHistories = contactHistoryEntities.stream().map(entity -> entity.asBuilder().wipeOutPii().build()).collect(toImmutableSet());
jpaTm().updateAll(wipedOutContactHistories);
return wipedOutContactHistories.size();
```

That way you don't need to bother with an `AtomicInteger` (which is still not the right construct for this use case; that's for concurrency-related code only), and you're also batching all the updates into a single `updateAll()` call rather than 500 calls to `update()` which in theory could be made to be more efficient.
</blockquote></details>

AtomicInteger was my suggestion. It allows us to avoid collecting the stream into a list. Personally I hate unnecessary copying.
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 450 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJBSYvEC4uyhu5sqhL:-MkJBSYvEC4uyhu5sqhM:b-x2az1j) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/config/files/default-config.yaml#L450)):*
> ```
> 1000
> ```
500. Also see next comment.
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 451 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJBfZL4DWFKi0-FfX0:-MkJBfZL4DWFKi0-FfX1:btlal04) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/config/files/default-config.yaml#L451)):*
> ```
> The number of entities to wipe per transaction.
> ```
Add: "This value should be a multiple of wipeOutQueryBatchSize."
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 192 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCwjqK-a7-iGeWSNRo:-MkJOtoo-eA7SvZbtuQZ:bx5fbkw) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L192)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

or directly comparing the two lists which is what i have now. 
</blockquote></details>

Again, try assert on the Stream directly, and use containsExactlyElementsIn. Please also check the other test methods for similar scenarios.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 195 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxD3U6HyJspHsR7Ij:-MkJPJEc1KET1kO-sQIP:bdqenfw) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L195)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

changed.
</blockquote></details>

If you already asserted that returnedEntities isEqualTo or containsExactlyElementsIn expectedToBeWipedOut, why do you have to check assert about expectNotTobeWipedout? Unless expectedToBeWipedOut and expectNotTobeWipedout has common elements, the second check is guaranteed, right?
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 209 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxaaq3BEt-rGkWUdr:-MkJQ8-f1_4w4ZWUQXG1:b2886zq) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L209)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

done
</blockquote></details>

This is the sanity check of the setup and result set should be the same as expectedToBeWipedOut. You should assert with containsExactlyElementIn here, and remove the loop below.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 146 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJI3QoD3Ody4BKA1MX:-MkJI3QoD3Ody4BKA1MY:b-veibhb) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L146)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     assertThat(
>             jpaTm()
>                 .transact(
>                     () ->
>                         action
>                             .getAllHistoryEntitiesOlderThan(MIN_MONTHS_BEFORE_WIPE_OUT)
>                             .collect(toImmutableList())))
>         .isEqualTo(expectedToBeWipedOut);
> ```
</details>

A couple things here:

1. If you also import static Truth8.assertThat, you don't need to append the .collect(toImmutableList()) part to the query result.
2. The isEqualTo() method is problematic. Since the persisted entities all have the same modification time, the order in the query result is not deterministic. You should use containsExactlyElementsIn. Also see my comments in the action class. I don't see why the query should order the entities.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 161 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJNpNkB3THEx4feinI:-MkJNpNl6z0arn7iUhlu:b-3przfo) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L161)):*
> ```
> collect(toImmutableList())
> ```
Don't convert to list if you can use methods in the Stream class or asserts that knows about stream. 
For example, Stream.count() tells the size of a bounded stream and can be safely used in tests. 

For this test:
Truth8.assertThat(        jpaTm()
            .transact(
                () ->
                    action
                        .getAllHistoryEntitiesOlderThan(MIN_MONTHS_BEFORE_WIPE_OUT))).isEmpty();


<!-- Sent from Reviewable.io -->

2021-09-24 00:28 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 19 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 72 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkKAKH5B9gGmf4Wxo3Q:-MkKAKH6AkZ48iZwJ94K:b-5vx3et) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L72)):*
> ```
>     // the maximum returned number of entities per transaction
>     this.numOfEntitiesToWipeOutPerTransaction = numOfEntitiesToWipeOutPerTransaction;
> ```
On second thought, let's drop this parameter and just use wipeOutQueryBatchSize for both JDBC batching and processing batching.
Set to 500 or 1000 in the config file. The separation doesn't bring many benefits.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 88 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJONoc4rVmcV0Cjfcx:-MkKBEtzEVwQ7ds9NqkE:b-a1dqpk) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L88)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I don't believe this is necessarily a safe assumption to make -- I think this could lead to an early termination.  Or, alternatively, the last batch could by change happen to be exactly the same size as the full batch, so then the next run of the query will return 0 entities, and I'm not 100% sure that's being handled correctly.
</blockquote></details>

0 is covered by < so it will terminate.
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 451 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJBfZL4DWFKi0-FfX0:-MkKBmkb1yIjZzOPF52m:b-ai2hhy) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/config/files/default-config.yaml#L451)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> The number of entities to wipe per transaction.
> ```
Add: "This value should be a multiple of wipeOutQueryBatchSize."
</blockquote></details>

Actually let's drop this parameter. See my comments at start of class.


<!-- Sent from Reviewable.io -->

2021-09-24 13:56 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 19 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 80 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJNnHO32nrOczGTW6r:-MkKJJzO98HdvVcFL7VH:bhrk7by) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L80)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Infinite loops are dangerous and don't express what's going on in as clear of a way as possible.  I think you can rewrite this as follows:

```
int totalWipedOut = 0;
do {
  int batchWipedOut = .....;
  totalWipedOut += batchWipedOut;
} while (batchWipedOut > 0)
```

This way it keeps running until it has no work left to do.
</blockquote></details>

would this even work though since batchWipedOut is declared within do and batchWipedOut is used to for the condition.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 88 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJONoc4rVmcV0Cjfcx:-MkKJddSEt3O3N0jQAL7:b-urbfxy) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L88)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

0 is covered by < so it will terminate.
</blockquote></details>

agree with weimin. 
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 95 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJPKPXDNC3BndA_nXX:-MkJwGZy6EGCOHImw6D7:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L95)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

"Processed" is too generic.  Say "Wiped out" here.  "Processed" is also misleading because one could think of it as all the contact histories older than 18 months, when it's really just the ones that needed to be wiped out.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 98 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJPfIM1f4IZ7Ty39hc:-MkJwLFc91Bvih-TMCbH:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L98)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Make this `atSevere()` for better visibility.  We don't expect this to ever happen in the course of normal operation, so when it does, we want to be alerted to that fact.  And if this is continually failing, but only logging at WARNING, then we may not realize that it's failing, which is bad.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 122 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJJOE1E60ksuznvTn8:-MkJxXCs7m_PXRQsoN1J:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L122)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> ORDER BY modificationTime ASC
> ```
I don't see why "order by" is needed as long as we are sure that our wipeout job can work down the backlog. 
Ordering would only be an issue if we cannot work down the backlog fast enough AND out of compliance by 2 days is worse than out of compliance by 1 day. 
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 125 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJL8V00H-6SXyb8vja:-MkJxa-95EgxB2nCvbyi:bj7y2u6) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L125)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is there a need to have the `query` local variable at all?  It seems to me like this entire method could simply be one long return statement:

```
return jpaTm().query(...).setParameter(...).unwrap(...).others(....).getResultStream();
```
</blockquote></details>

intellij didnt like it: Unchecked assignment: 'java.util.stream.Stream' to 'java.util.stream.Stream<google.registry.model.contact.ContactHistory> has raw type .. it has to do with using TypedQuery and unwrap(Query.class). using unwrap(Query.class) allows to set max results and fetch size
___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 128 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJLrAL0PfKTLUT66jC:-MkN4eao9KKaGLQj9G9b:b6ja07m) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L128)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What's the meaning behind having a separate fetch size and number of max results?  Does this even make sense anymore?  Especially because the fetch size is set to 1000, which is twice the max results of the entire query, it seems like something isn't going to work right here?  Shouldn't the fetch size be smaller than the max results of the query?
</blockquote></details>

@weiminyu 
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 450 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJBSYvEC4uyhu5sqhL:-MkN4nKHEEVv312txGr0:bmea6mh) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/config/files/default-config.yaml#L450)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> 1000
> ```
500. Also see next comment.
</blockquote></details>

removing numOfEntitiesToWipeOutPerTransaction
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 451 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJBfZL4DWFKi0-FfX0:-MkN4kQ4BJfjRmtPDQCI:bmea6mh) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/config/files/default-config.yaml#L451)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Actually let's drop this parameter. See my comments at start of class.
</blockquote></details>

removing numOfEntitiesToWipeOutPerTransaction


<!-- Sent from Reviewable.io -->

2021-09-24 14:11 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 19 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 72 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkKAKH5B9gGmf4Wxo3Q:-MkN8Ko1D0gD61hW5mfj:biuck6i) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L72)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>     // the maximum returned number of entities per transaction
>     this.numOfEntitiesToWipeOutPerTransaction = numOfEntitiesToWipeOutPerTransaction;
> ```
On second thought, let's drop this parameter and just use wipeOutQueryBatchSize for both JDBC batching and processing batching.
Set to 500 or 1000 in the config file. The separation doesn't bring many benefits.
</blockquote></details>

set wipeOutQueryBatchSize = 500 in config file 
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 450 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJPupa0FQsx0iEOjS1:-MkN68Iw7NO_zV593XB6:bfseul7) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/config/files/default-config.yaml#L450)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These two figures are off with relation to each other.
</blockquote></details>

which two?


<!-- Sent from Reviewable.io -->

2021-09-24 14:13 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 19 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 136 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJMF2e5iU7C15MVChJ:-MkN8Zrl-w5narFOwFE3:bhmihtm) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L136)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

AtomicInteger was my suggestion. It allows us to avoid collecting the stream into a list. Personally I hate unnecessary copying.
</blockquote></details>

originally i converted to a Immutable list but decided to go with weimin's suggestion to use stream instead.. and because of lambda expression, atomicInteger has to be used. 


<!-- Sent from Reviewable.io -->

2021-09-24 14:34 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 124 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJOgMT17eIUC2aD_Ma:-MkNDcHG4v_1tlZxwmBs:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L124)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This means that, each time you run the query, you're using a different time calculation, which makes things harder to reason about (and also means that the amount of data under consideration will steadily expand as the action continues running).  You don't want that.  What you want is a single `DateTime` that is calculated once, at the very beginning of the action's execution.  Something like ...

```
public void run() {
  DateTime wipeOutTime = clock.nowUtc().minusMonths(numOfMonths);
  logger.atInfo().log("Wiping out all contact histories prior to %s.", wipeOutTime);
  ...
  ... getAllHistoryEntitiesOlderThan(wipeOutTime) ...;
  
}

```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-09-24 20:27 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 209 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxaaq3BEt-rGkWUdr:-MkO6RImCNH8liOXLQ7n:brpmqbp) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L209)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This is the sanity check of the setup and result set should be the same as expectedToBeWipedOut. You should assert with containsExactlyElementIn here, and remove the loop below.
</blockquote></details>

removed 


<!-- Sent from Reviewable.io -->

2021-09-24 20:27 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 195 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxD3U6HyJspHsR7Ij:-MkOUS6_Aa5hNu5tAP0S:b6p80q5) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L195)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

If you already asserted that returnedEntities isEqualTo or containsExactlyElementsIn expectedToBeWipedOut, why do you have to check assert about expectNotTobeWipedout? Unless expectedToBeWipedOut and expectNotTobeWipedout has common elements, the second check is guaranteed, right?
</blockquote></details>

removed. 


<!-- Sent from Reviewable.io -->

2021-09-24 20:27 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 192 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCwjqK-a7-iGeWSNRo:-MkOUY0M-H8itg9sdhLP:b-m8ffjb) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L192)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Again, try assert on the Stream directly, and use containsExactlyElementsIn. Please also check the other test methods for similar scenarios.
</blockquote></details>

yep, doing that now


<!-- Sent from Reviewable.io -->

2021-09-24 20:30 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 146 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJI3QoD3Ody4BKA1MX:-MkOUawI-Rp3b37sTNx8:b-mdr89d) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L146)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>     assertThat(
>             jpaTm()
>                 .transact(
>                     () ->
>                         action
>                             .getAllHistoryEntitiesOlderThan(MIN_MONTHS_BEFORE_WIPE_OUT)
>                             .collect(toImmutableList())))
>         .isEqualTo(expectedToBeWipedOut);
> ```
A couple things here:

1. If you also import static Truth8.assertThat, you don't need to append the .collect(toImmutableList()) part to the query result.
2. The isEqualTo() method is problematic. Since the persisted entities all have the same modification time, the order in the query result is not deterministic. You should use containsExactlyElementsIn. Also see my comments in the action class. I don't see why the query should order the entities.
</blockquote></details>

1) ben's suggesting earlier it's better not to have assertion within transaction but since these are just test cases and it's better not to create copy of data just to perform comparison. now removing .collect(toImmutableList()) 
2) changed to containsExactlyElementsIn
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 161 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJNpNkB3THEx4feinI:-MkOUyrHBju7jpHmhNOt:b-7m2y43) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L161)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> collect(toImmutableList())
> ```
Don't convert to list if you can use methods in the Stream class or asserts that knows about stream. 
For example, Stream.count() tells the size of a bounded stream and can be safely used in tests. 

For this test:
Truth8.assertThat(        jpaTm()
            .transact(
                () ->
                    action
                        .getAllHistoryEntitiesOlderThan(MIN_MONTHS_BEFORE_WIPE_OUT))).isEmpty();

</blockquote></details>

noted


<!-- Sent from Reviewable.io -->

2021-09-24 20:37 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/test/java/google/registry/model/history/ContactHistoryTest.java, line 188 at r6](https://reviewable.io/reviews/google/nomulus/1303#-Mk3xhCG3GMyd3xo5r-O:-MkOWgGe71LqJjQrGuQH:bfdr0ha) ([raw file](https://github.com/google/nomulus/blob/cdadf364403b9ea37708a30ad989ea38cc933016/core/src/test/java/google/registry/model/history/ContactHistoryTest.java#L188)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

To be clear, my suggestion is to change this line to `ContactHistory wipedContactHistory = contactHistory.asBuilder().wipeOutPii().build();` and then have every subsequent line start with `assertThat(wipedContactHistory....)`
</blockquote></details>

oh. i removed that issue in a different file but not this. fixed. 


<!-- Sent from Reviewable.io -->

2021-09-27 13:54 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 80 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJNnHO32nrOczGTW6r:-MkbX5UQ1cbPgY_7inLL:b-raacj8) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L80)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

would this even work though since batchWipedOut is declared within do and batchWipedOut is used to for the condition.
</blockquote></details>

changed it to do-while loop 


<!-- Sent from Reviewable.io -->

2021-09-28 18:05 UTC, weiminyu approved these changes
Looks good to me. Please resolve Ben's issues.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303#-:-Mkh_54c9i46sSiGon6O:bjpz78e)* status: 1 of 11 files reviewed, 12 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)



<!-- Sent from Reviewable.io -->

2021-09-28 21:06 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 136 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJMF2e5iU7C15MVChJ:-MkiCq8B0YY_sI5HMBQx:bhplzu5) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L136)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

originally i converted to a Immutable list but decided to go with weimin's suggestion to use stream instead.. and because of lambda expression, atomicInteger has to be used. 
</blockquote></details>

Just use a normal for-each loop then, so you can use a normal `int`.
___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 450 at r14](https://reviewable.io/reviews/google/nomulus/1303#-MkJPupa0FQsx0iEOjS1:-MkiDa-nD964T8exQfjc:b-6e7k9m) ([raw file](https://github.com/google/nomulus/blob/e59e90eaeaa755ce274cd6b679b954dfb53cf04b/core/src/main/java/google/registry/config/files/default-config.yaml#L450)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

which two?
</blockquote></details>

You had a batch size and a separate fetch size (or whatever), but now it's just down to one.


<!-- Sent from Reviewable.io -->

2021-09-28 21:13 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 209 at r13](https://reviewable.io/reviews/google/nomulus/1303#-MkCxaaq3BEt-rGkWUdr:-MkiE6g3C715P6pHPui5:b-zbkmts) ([raw file](https://github.com/google/nomulus/blob/42007c6ba22a6990832909e66096f55c694a6b3c/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L209)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

removed 
</blockquote></details>

To expand on how these helpers should work, they won't fail on the first entity that is incorrect; they'll fail after examining all of them.  E.g. something like:

```
void ensurePiiFieldsWipedOut(Collection<ContactHistory> contactHistories) {
  ImmutableSet.Builder<ContactHistory> notWipedOut = new ...;
  for (ContactHistory contactHistory : contactHistories) {
    if (contactHistory has PII fields that aren't null) {
      notWipedOut.add(contactHistory);
    }
  }
  assertWithMessage(.....).that(notWipedOut.build()).isEmpty();
}
```

That way you correctly get an alert about every single element that was expected to be wiped out, but wasn't.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 289 at r19](https://reviewable.io/reviews/google/nomulus/1303#-MkiDmAA01eZqAkdNLLk:-MkiDmAA01eZqAkdNLLl:b4zuzbm) ([raw file](https://github.com/google/nomulus/blob/528827249f21915167f6f9c55861783fc825d3b4/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L289)):*
> ```Java
>         .isEqualTo(0);
> 
>     for (ContactHistory originalEntity : expectedToBeWipedOut) {
> ```

All such loops in these tests need to be removed.  You need to make a simultaneous assertion about all elements in the collection, not just try them one by one and then fail on the first with an error.  I left a comment above about the kinds of helpers you should implement for this:

```
void ensurePiiFieldsWipedOut(Collection<ContactHistory> contactHistories) { ... }
void ensurePiiFieldsStillPresent(Collection<ContactHistory> contactHistories) { ... }
```


<!-- Sent from Reviewable.io -->

2021-09-29 20:00 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 3 unresolved discussions (waiting on @gbrodman, @rachelguan, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 106 at r20](https://reviewable.io/reviews/google/nomulus/1303#-Mkn7ET-EZGmrxZXmW1T:-Mkn7ET-EZGmrxZXmW1U:b-exm5dj) ([raw file](https://github.com/google/nomulus/blob/6acddd1480997a19d1c04f912fc9ba16aefee2e3/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L106)):*
> ```Java
>    */
>   @VisibleForTesting
>   Stream<ContactHistory> getAllHistoryEntitiesOlderThan(DateTime wipeOutTime) {
> ```

The function name and Javadoc here aren't quite correct.  This is not _all_ history entries older than a given date, it's the non-wiped-out history entries older than a given date. Also there's a max results size on this, so it's also not _all_ history entries for that reason.  It's really just the next batch. So fix the Javadoc and rename it to something more suitable like `loadNextHistoryEntriesWithPiiBatch()`
___
*[core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml, line 253 at r20](https://reviewable.io/reviews/google/nomulus/1303#-Mkn85qv7iwavP4GPpy7:-Mkn85qv7iwavP4GPpy8:b2nhljf) ([raw file](https://github.com/google/nomulus/blob/6acddd1480997a19d1c04f912fc9ba16aefee2e3/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml#L253)):*
> ```XML
>     <url><![CDATA[/_dr/task/wipeOutContactHistoryPii]]></url>
>     <description>
>       This job runs weekly to wipe out pii fields of ContactHistory entities
> ```

PII
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 352 at r20](https://reviewable.io/reviews/google/nomulus/1303#-Mkn6B6V5g2OoFJkZ1VS:-Mkn6B6V5g2OoFJkZ1VT:b-orocey) ([raw file](https://github.com/google/nomulus/blob/6acddd1480997a19d1c04f912fc9ba16aefee2e3/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L352)):*
> ```Java
>     ImmutableSet.Builder<ContactHistory> notWipedEntities = new ImmutableSet.Builder<>();
>     for (ContactHistory entity : entities) {
>       ContactHistory entityFromDb = jpaTm().transact(() -> jpaTm().loadByEntity(entity));
> ```

I'm surprised to see that you're reloading these inside these helper functions.  That's not what you'd expect from seeing an invocation at the call site, which is passing in the pre-action version of the entities.

Remove the load in here (and in the helper below) and operate solely on the entities that are actually being passed in.  Then handle the reload at the callsite, so it's more clear exactly what's going on.  A callsite that looks like the following will be more obvious:

```
    assertAllEntitiesContainPii(entities);

    action.run();
    assertAllPiiFieldsAreWipedOut(DatabaseHelper.loadByEntities(entities));
```

That makes it really obvious that you've persisted some data, which has PII, then you run the wipeout action, and then after that, you reload them and verify they're wiped out.


<!-- Sent from Reviewable.io -->

2021-09-29 21:56 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303)* status: 1 of 11 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 106 at r20](https://reviewable.io/reviews/google/nomulus/1303#-Mkn7ET-EZGmrxZXmW1T:-MknYS822ZsP0ds-Gwt2:b-sfsw6y) ([raw file](https://github.com/google/nomulus/blob/6acddd1480997a19d1c04f912fc9ba16aefee2e3/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L106)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The function name and Javadoc here aren't quite correct.  This is not _all_ history entries older than a given date, it's the non-wiped-out history entries older than a given date. Also there's a max results size on this, so it's also not _all_ history entries for that reason.  It's really just the next batch. So fix the Javadoc and rename it to something more suitable like `loadNextHistoryEntriesWithPiiBatch()`
</blockquote></details>

done. that was the initial idea, by getting all data older than a given date. 
changed the name to getNextContactHistoryEntitiesWithPiiBathc()
___
*[core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml, line 253 at r20](https://reviewable.io/reviews/google/nomulus/1303#-Mkn85qv7iwavP4GPpy7:-MknY-5Z05yxBZ-a4xbx:b-7ql1td) ([raw file](https://github.com/google/nomulus/blob/6acddd1480997a19d1c04f912fc9ba16aefee2e3/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml#L253)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

PII
</blockquote></details>

fixed
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 352 at r20](https://reviewable.io/reviews/google/nomulus/1303#-Mkn6B6V5g2OoFJkZ1VS:-MknY8ZB-oEheWSlRXC0:b-63a9n7) ([raw file](https://github.com/google/nomulus/blob/6acddd1480997a19d1c04f912fc9ba16aefee2e3/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L352)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I'm surprised to see that you're reloading these inside these helper functions.  That's not what you'd expect from seeing an invocation at the call site, which is passing in the pre-action version of the entities.

Remove the load in here (and in the helper below) and operate solely on the entities that are actually being passed in.  Then handle the reload at the callsite, so it's more clear exactly what's going on.  A callsite that looks like the following will be more obvious:

```
    assertAllEntitiesContainPii(entities);

    action.run();
    assertAllPiiFieldsAreWipedOut(DatabaseHelper.loadByEntities(entities));
```

That makes it really obvious that you've persisted some data, which has PII, then you run the wipeout action, and then after that, you reload them and verify they're wiped out.
</blockquote></details>

done but shouldn't assertAllEntitiesContainPii() check the entities that are in the database? instead of just using the objects just to verify that the entities in db contain PII?  


<!-- Sent from Reviewable.io -->

2021-09-30 19:07 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1303#-:-Mks5flr0_UF-Gb8p956:bnfp4nl)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 352 at r20](https://reviewable.io/reviews/google/nomulus/1303#-Mkn6B6V5g2OoFJkZ1VS:-Mks5GQ26nt-AmtrefRA:bgbqbv5) ([raw file](https://github.com/google/nomulus/blob/6acddd1480997a19d1c04f912fc9ba16aefee2e3/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L352)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

done but shouldn't assertAllEntitiesContainPii() check the entities that are in the database? instead of just using the objects just to verify that the entities in db contain PII?  
</blockquote></details>

No, it should make the assertion based on what's being passed to it as a parameter.  It's an unintuitive pattern to have a function that works like this:

"Take a bunch of entities are parameters, but only extract the primary keys from them, and otherwise ignore them, and use those primary keys to reload them from the database, and _then_ check those"

If you want to bake the loading from the DB into the method then it should be taking just the keys of the entities to load, not the full entities.


<!-- Sent from Reviewable.io -->

2021-09-30 19:17 UTC, merged