Skip synthetic history entries for resources that don't need them
google/nomulus pull request #1320
Opened 2021-09-14 17:44 UTC by gbrodman

The reason for creating synthetic history entries is so that we can
guarantee that each EppResource has at least one corresponding *History
object that contains the resource at that point in time. If we have
history objects in SQL that contain a particular resource already, there
is no need to create a synthetic history entry for that resource.

2021-09-15 14:45 UTC, CydeWeys requested changes
I'm confused about the logic here.  What I expected was "Give this command a DateTime (after the most recent initial DB import) as input and then it writes out synthetic HistoryEntries for every EPP resource that doesn't have a HistoryEntry more recent than that DateTime".

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-MjduXUD9yzpqudouUSa:blhta1g)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 136 at r1](https://reviewable.io/reviews/google/nomulus/1320#-MjduMzsEPYde3jsJEZz:-MjduMzsEPYde3jsJE_-:blccdpa) ([raw file](https://github.com/google/nomulus/blob/3a80412481597ac6f50df289b7b3716422c97c99/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L136)):*
> ```Java
>   private static Class<? extends HistoryEntry> getHistoryClassFromParent(
>       Class<? extends EppResource> parent) {
>     if (parent.equals(ContactResource.class)) {
> ```

This should be a Map.


<!-- Sent from Reviewable.io -->

2021-09-15 14:55 UTC, gbrodman reviewed
It isn't necessary to give it a DateTime; this accomplishes the same thing without the manual step. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-MjdwjcW6S1kF5dPnsps:b-fek6xx)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 136 at r1](https://reviewable.io/reviews/google/nomulus/1320#-MjduMzsEPYde3jsJEZz:-MjdwhtN6SMDkJ32Q3d_:bb74ce2) ([raw file](https://github.com/google/nomulus/blob/3a80412481597ac6f50df289b7b3716422c97c99/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L136)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should be a Map.
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2021-09-15 15:40 UTC, CydeWeys reviewed
So then what is this doing exactly?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-Mje6K3O55eF_cKkKxLb:b-bhrejk)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-09-15 15:43 UTC, gbrodman reviewed
for every resource, if we already have a history object in SQL that contains a representation of that resource at that point in time, we skip it 

alternatively put, for every resource, we save a new HistoryEntry if and only if there does not exist a *History object in SQL that contains that object at that point in time. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-Mje6t8EEHv97qUuLNzq:bd1yzw9)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-09-15 15:44 UTC, CydeWeys reviewed
That's not strictly accurate though, right?  It's not if there exists an object in SQL that contains that object at that point in time, it's only if the most _recent_ history object contains that information, right?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-Mje6wMoDvqoYj8QG3Nx:b-6os748)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-09-15 15:46 UTC, gbrodman reviewed
If you want to nitpick semantics yes, however those statements are equivalent. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-Mje7gNo3jK7Xkl4zfjN:b-hzanan)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-09-15 21:04 UTC, CydeWeys requested changes
They're not equivalent though.  There's a difference between "the most recent X" and "any X".  The former seems like it works here in this case, and fortunately is more performant to calculate, but it's not the same.  The commit log message is still not accurate in that regard and it's inhibiting understanding as to exactly what's going on.

So, is there any situation where the most recent history entry has data, but that data is wrong/unusable for some reason?  Or in all such cases would we be wiping out the existing contents of Cloud SQL and re-importing (as we're currently doing in sandbox and will do in prod soon on account of the incorrect update times)?

Anyway, looking good overall, modulo a few remaining questions.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-MjfD_smDclnTMovTbEv:bysg2tv)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[config/presubmits.py, line 215 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfFUI82H4i1-KDCcRA:-MjfFUI96qfP0mwCrSYr:bgfxry) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/config/presubmits.py#L215)):*
> ```Python
>          # CriteriaQueryBuilder is a false positive
>          "CriteriaQueryBuilder.java",
>          "CreateSyntheticHistoryEntriesAction.java",
> ```

Why is this necessary?  Offhand, I don't see you doing anything that would cause this presubmit to fail.
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 126 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfFnO07cZF9cJWSeb7:-MjfFnO07cZF9cJWSeb8:b-25bptn) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L126)):*
> ```Java
>                       .orderByDesc("modificationTime")
>                       .build();
>               return jpaTm().query(criteriaQuery).setMaxResults(1).getResultStream().findFirst();
> ```

What happens if this returns zero results?  Is that even possible?  In theory there's always that initial create, but is it somehow possible for the resource itself to have been async written over but the corresponding create history entry hasn't yet been?
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 143 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfEEwh5cEduaJ-N4i8:-MjfEEwh5cEduaJ-N4i9:b-wnmwp5) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L143)):*
> ```Java
>   private static String getRepoIdFieldNameFromHistoryClass(
>       Class<? extends HistoryEntry> historyClass) {
>     return historyClass.equals(ContactHistory.class)
> ```

This isn't strictly safe -- it's using `hostRepoId` as a default value on an unexpected class rather than throwing an error.  It seems to me like the preferred solution here would be something like `abstract String getRepoIdFieldName();` in `HistoryEntry`, then all implementations are forced to implement this.


<!-- Sent from Reviewable.io -->

2021-09-15 21:34 UTC, gbrodman reviewed
No, the only time we ever write resourceless entries to the History tables is during the initial SQL population. The result is that the questions "are there any history rows with resources?" and "does the last history row have a resource?" will always have the same answer 

Updated commit message

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-MjfKZcWB0UtlK1EFjRK:bntng84)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[config/presubmits.py, line 215 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfFUI82H4i1-KDCcRA:-MjfJZXw56Tsd1u6f0n-:b-8593as) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/config/presubmits.py#L215)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why is this necessary?  Offhand, I don't see you doing anything that would cause this presubmit to fail.
</blockquote></details>

it's the call to `jpaTm().query(criteriaQuery)`

because we use a simple regex, we can't differentiate between `query(String)` and `query(CriteriaQuery)`
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 126 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfFnO07cZF9cJWSeb7:-MjfKFcSD96-6hd_qzAi:bpnz4gu) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L126)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What happens if this returns zero results?  Is that even possible?  In theory there's always that initial create, but is it somehow possible for the resource itself to have been async written over but the corresponding create history entry hasn't yet been?
</blockquote></details>

It shouldn't be possible, since every transaction that creates an EppResource should also create a HistoryEntry for said resource
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 143 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfEEwh5cEduaJ-N4i8:-MjfJrqT15iGyQiVpIkZ:b-20fqes) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L143)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This isn't strictly safe -- it's using `hostRepoId` as a default value on an unexpected class rather than throwing an error.  It seems to me like the preferred solution here would be something like `abstract String getRepoIdFieldName();` in `HistoryEntry`, then all implementations are forced to implement this.
</blockquote></details>

We cannot make `HistoryEntry` abstract until post-migration, but we can use a map. 


<!-- Sent from Reviewable.io -->

2021-09-16 15:40 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[config/presubmits.py, line 215 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfFUI82H4i1-KDCcRA:-MjjFoJS2JtQxh6XvFKj:bug047i) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/config/presubmits.py#L215)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it's the call to `jpaTm().query(criteriaQuery)`

because we use a simple regex, we can't differentiate between `query(String)` and `query(CriteriaQuery)`
</blockquote></details>

It sounds like the presubmit isn't really working out for us so much then if it can't differentiate between these two.  Wonder if it'd be worth renaming the `query(CriteriaQuery)` method so the presubmit can be more targeted?
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 143 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfEEwh5cEduaJ-N4i8:-Mjj-ZrI3kEZmsr_dN52:b6ou0by) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L143)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We cannot make `HistoryEntry` abstract until post-migration, but we can use a map. 
</blockquote></details>

It wouldn't need to be abstract -- it could also have a base method that throws an 'Unknown type' exception, and then it's overridden on all three that inherit it.


<!-- Sent from Reviewable.io -->

2021-09-16 15:42 UTC, CydeWeys approved these changes
That's good context to have to explain how/why this works.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-MjjGJcMBL2z6IdtmsTT:b-xpl52w)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-09-16 15:49 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[config/presubmits.py, line 215 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfFUI82H4i1-KDCcRA:-MjjH5x5EdskMw4u3i2K:b-mh1vhf) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/config/presubmits.py#L215)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It sounds like the presubmit isn't really working out for us so much then if it can't differentiate between these two.  Wonder if it'd be worth renaming the `query(CriteriaQuery)` method so the presubmit can be more targeted?
</blockquote></details>

Yes, I think so. Done. 
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 143 at r2](https://reviewable.io/reviews/google/nomulus/1320#-MjfEEwh5cEduaJ-N4i8:-MjjGl2-6mXQoRXxFLks:b-msc265) ([raw file](https://github.com/google/nomulus/blob/384bdd880d09e336532336ccca57959e443121e0/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L143)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It wouldn't need to be abstract -- it could also have a base method that throws an 'Unknown type' exception, and then it's overridden on all three that inherit it.
</blockquote></details>

I think I don't like that given that we don't actually have an instance of the history object here (that is what we are trying to get). So we'd have to do some reflection 


<!-- Sent from Reviewable.io -->

2021-09-16 17:23 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 179 at r4](https://reviewable.io/reviews/google/nomulus/1320#-MjjXz2UAc1XNk1GWolM:-MjjXz2V8OufKswzCVCU:b-s40xj1) ([raw file](https://github.com/google/nomulus/blob/52ea527846039112ed0d066566b022f5ae74ebbf/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L179)):*
> ```Java
>                         .put(
>                             HistoryEntry.createBuilderForResource(eppResource)
>                                 .setClientId(registryAdminRegistrarId)
> ```

You'll need to change this now that https://github.com/google/nomulus/pull/1317 is merged.


<!-- Sent from Reviewable.io -->

2021-09-16 17:27 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 179 at r4](https://reviewable.io/reviews/google/nomulus/1320#-MjjXz2UAc1XNk1GWolM:-MjjdQGg52kzj0IuZgn-:b-896fix) ([raw file](https://github.com/google/nomulus/blob/52ea527846039112ed0d066566b022f5ae74ebbf/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L179)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You'll need to change this now that https://github.com/google/nomulus/pull/1317 is merged.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-16 19:09 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1320#-:-Mjk-mJb6-DFMmkyEfBF:bnfp4nl)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-09-17 16:10 UTC, merged