Include Cursor in the initial SQL population
google/nomulus pull request #1323
Opened 2021-09-16 18:33 UTC by gbrodman

The test for this also required a bit of a fix in the Cursor scope
initialization -- we can't rely on the key being equal to the cross-tld
key but we can rely on the kind of the key (for GLOBAL it's
EntityGroupRoot, for per-registry it's that TLD).

2021-09-16 20:35 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1323)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @weiminyu)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/google/nomulus/1323#-MjkJTvUBPOeiwO1hvSM):*
Why can't we rely on this?


<!-- Sent from Reviewable.io -->

2021-09-16 20:40 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1323)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/google/nomulus/1323#-MjkJTvUBPOeiwO1hvSM):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why can't we rely on this?
</blockquote></details>

I honestly don't know. 

They even have the same String representation -- `Key<?>(EntityGroupRoot("cross-tld"))`

Something weird with `Key`'s `.equals()`? 


<!-- Sent from Reviewable.io -->

2021-09-16 20:48 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1323)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/google/nomulus/1323#-MjkJTvUBPOeiwO1hvSM):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I honestly don't know. 

They even have the same String representation -- `Key<?>(EntityGroupRoot("cross-tld"))`

Something weird with `Key`'s `.equals()`? 
</blockquote></details>

oh wait, the app ID is different in the keys


<!-- Sent from Reviewable.io -->

2021-09-17 16:04 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1323)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/google/nomulus/1323#-MjkJTvUBPOeiwO1hvSM):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

oh wait, the app ID is different in the keys
</blockquote></details>

ok yeah so what's happening here is that if you persist a `Key<?>` in some object in Datastore, it persists just the standard data you'd expect, which basically only includes the parent, the kind, and the ID. Then, when you load it back in from Datastore, it uses the app ID of whatever environment you're loading it in 

If you persist the websafe string (which is what we do for cursors) it includes the app ID 

In the pipelines, we use the default environment which has a different app ID from the test environment 


<!-- Sent from Reviewable.io -->

2021-09-17 17:24 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1323)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @weiminyu)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/google/nomulus/1323#-MjkJTvUBPOeiwO1hvSM):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ok yeah so what's happening here is that if you persist a `Key<?>` in some object in Datastore, it persists just the standard data you'd expect, which basically only includes the parent, the kind, and the ID. Then, when you load it back in from Datastore, it uses the app ID of whatever environment you're loading it in 

If you persist the websafe string (which is what we do for cursors) it includes the app ID 

In the pipelines, we use the default environment which has a different app ID from the test environment 
</blockquote></details>

Wow, TIL that the app ID is in the key.  No idea.  May as well update the commit message then.


<!-- Sent from Reviewable.io -->

2021-09-17 17:59 UTC, gbrodman commented
Commit message updated

2021-09-17 18:42 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1323#-:-Mjp3NjpDCTB1vyAhZ2d:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2021-09-19 13:23 UTC, merged