Don't inject random string gen in BackfillRegistryLocksCommand
google/nomulus pull request #1337
Opened 2021-09-23 16:47 UTC by gbrodman

It's not necessary and it's causing failures -- specifically we're
getting an NPE when running it in prod trying to access the string
generator (injection seems to be silently failing).

2021-09-23 18:16 UTC, jianglai requested changes
This seems incredible. We have other injected fields on this class, but they are not throwing NPE?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1337#-:-MkIqkYX05Rqaut9dGvd:bjybuj5)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/tools/javascrap/BackfillRegistryLocksCommandTest.java, line 113 at r1](https://reviewable.io/reviews/google/nomulus/1337#-MkIroPp0K5CNrLWlxAl:-MkIroPp0K5CNrLWlxAm:b-4enwew) ([raw file](https://github.com/google/nomulus/blob/eeac49135004cb1b670efa6fdb10650c7ab6d01f/core/src/test/java/google/registry/tools/javascrap/BackfillRegistryLocksCommandTest.java#L113)):*
> ```
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> ```
Is it the same as `command.stringGenerator.createString(32)`? Does it matter?


<!-- Sent from Reviewable.io -->

2021-09-23 18:25 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1337)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/test/java/google/registry/tools/javascrap/BackfillRegistryLocksCommandTest.java, line 113 at r1](https://reviewable.io/reviews/google/nomulus/1337#-MkIroPp0K5CNrLWlxAl:-MkItq98EEVur_HVLdXp:b-as7vt) ([raw file](https://github.com/google/nomulus/blob/eeac49135004cb1b670efa6fdb10650c7ab6d01f/core/src/test/java/google/registry/tools/javascrap/BackfillRegistryLocksCommandTest.java#L113)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> ```
Is it the same as `command.stringGenerator.createString(32)`? Does it matter?
</blockquote></details>

It isn't, but it doesn't matter (we don't actually check the verification code for this action since it's irrelevant to backfilled locks) 


<!-- Sent from Reviewable.io -->

2021-09-23 18:55 UTC, jianglai reviewed
OK I figured out why, you forgot to add the members inject method here:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/tools/RegistryToolComponent.java;l=85;bpv=0;bpt=1?q=registrytoolcomponent&ss=nomulus%2Fnomulus

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1337#-:-MkJ-dAM9ix0LbVGDCML:bmtgaer)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2021-09-23 19:25 UTC, gbrodman reviewed
oooof, that's rough, thank you. Wish that had failed at compile-time! 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1337#-:-MkJ6c6GA70Hfn6jQLSR:b-f6f5x1)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2021-09-23 19:55 UTC, jianglai requested changes
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1337)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[core/src/main/java/google/registry/tools/javascrap/BackfillRegistryLocksCommand.java, line 97 at r3](https://reviewable.io/reviews/google/nomulus/1337#-MkJDPNQEC-b43Dh8byx:-MkJDPNR-sjh_JqE2Ene:b8lh7ju) ([raw file](https://github.com/google/nomulus/blob/7fb7d18d11b8def3e3f6efcc1d2173469109c0ac/core/src/main/java/google/registry/tools/javascrap/BackfillRegistryLocksCommand.java#L97)):*
> ```
> String
> ```
Can we add in the PR description why this change is included?


<!-- Sent from Reviewable.io -->

2021-09-23 19:57 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1337)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/main/java/google/registry/tools/javascrap/BackfillRegistryLocksCommand.java, line 97 at r3](https://reviewable.io/reviews/google/nomulus/1337#-MkJDPNQEC-b43Dh8byx:-MkJE4y_5_CDxZraVoya:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7fb7d18d11b8def3e3f6efcc1d2173469109c0ac/core/src/main/java/google/registry/tools/javascrap/BackfillRegistryLocksCommand.java#L97)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> String
> ```
Can we add in the PR description why this change is included?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-24 01:32 UTC, jianglai approved these changes
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1337)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2021-09-24 18:08 UTC, merged