Add handling for UpdateAutoTimestamp when not in a transaction
google/nomulus pull request #1341
Opened 2021-09-24 18:44 UTC by CydeWeys

It's not clear why this is sometimes causing test flakes, but getting better
logging involved should help clear it up.

2021-09-24 20:38 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1341)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 1207 at r1](https://reviewable.io/reviews/google/nomulus/1341#-MkOWkgR6aNcRtchlLdE:-MkOWkgS7cif4TrZPADf:b-2jhto8) ([raw file](https://github.com/google/nomulus/blob/edcea01e2cb7e657055fec2fdebeeea03b6e20e1/core/src/test/java/google/registry/testing/DatabaseHelper.java#L1207)):*
> ```Java
>    * ForeignKeyedEppResources.
>    */
>   public static <R> ImmutableList<R> persistSimpleResources(final Iterable<R> resources) {
> ```

Does this cause any issue with any possible situations where the caller of `persistSimpleResources` is persisting something for which a version has already been persisted? I'd imagine that that could possibly result in errors with the `tm().insertAll()` calls


<!-- Sent from Reviewable.io -->

2021-09-24 20:40 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1341)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 1207 at r1](https://reviewable.io/reviews/google/nomulus/1341#-MkOWkgR6aNcRtchlLdE:-MkOXNTE9vUvJGTNeANu:b6amt45) ([raw file](https://github.com/google/nomulus/blob/edcea01e2cb7e657055fec2fdebeeea03b6e20e1/core/src/test/java/google/registry/testing/DatabaseHelper.java#L1207)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Does this cause any issue with any possible situations where the caller of `persistSimpleResources` is persisting something for which a version has already been persisted? I'd imagine that that could possibly result in errors with the `tm().insertAll()` calls
</blockquote></details>

None that are immediately obvious (`persistSimpleResources()` isn't used that widely).  And if it did cause any tests to fail, just fix those tests!  All the callsites I looked at were persisting things for the first time.


<!-- Sent from Reviewable.io -->

2021-09-24 20:44 UTC, gbrodman approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1341)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 1207 at r1](https://reviewable.io/reviews/google/nomulus/1341#-MkOWkgR6aNcRtchlLdE:-MkOY6Mj5HcUUDS6Go0s:b-mtzqx) ([raw file](https://github.com/google/nomulus/blob/edcea01e2cb7e657055fec2fdebeeea03b6e20e1/core/src/test/java/google/registry/testing/DatabaseHelper.java#L1207)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

None that are immediately obvious (`persistSimpleResources()` isn't used that widely).  And if it did cause any tests to fail, just fix those tests!  All the callsites I looked at were persisting things for the first time.
</blockquote></details>

fair enough


<!-- Sent from Reviewable.io -->

2021-09-24 20:50 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1341)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/model/UpdateAutoTimestamp.java, line 74 at r1](https://reviewable.io/reviews/google/nomulus/1341#-MkOZ_Q8E1S0Ini_ygEU:-MkOZ_Q8E1S0Ini_ygEV:b-y8h6xd) ([raw file](https://github.com/google/nomulus/blob/edcea01e2cb7e657055fec2fdebeeea03b6e20e1/core/src/main/java/google/registry/model/UpdateAutoTimestamp.java#L74)):*
> ```Java
>     }
>     if (autoUpdateEnabled() || lastUpdateTime == null) {
>       timestamp = jpaTm().getTransactionTime();
> ```

we should keep setting the timestamp for comparison purposes 


<!-- Sent from Reviewable.io -->

2021-09-24 20:51 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1341)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/UpdateAutoTimestamp.java, line 74 at r1](https://reviewable.io/reviews/google/nomulus/1341#-MkOZ_Q8E1S0Ini_ygEU:-MkO_-0mECdcnWUDJReW:b6czevz) ([raw file](https://github.com/google/nomulus/blob/edcea01e2cb7e657055fec2fdebeeea03b6e20e1/core/src/main/java/google/registry/model/UpdateAutoTimestamp.java#L74)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we should keep setting the timestamp for comparison purposes 
</blockquote></details>

Already done.


<!-- Sent from Reviewable.io -->

2021-09-24 20:53 UTC, gbrodman requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1341)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/model/UpdateAutoTimestamp.java, line 74 at r1](https://reviewable.io/reviews/google/nomulus/1341#-MkOZ_Q8E1S0Ini_ygEU:-MkO_ID21LeAQwEJftQb:b8h7irn) ([raw file](https://github.com/google/nomulus/blob/edcea01e2cb7e657055fec2fdebeeea03b6e20e1/core/src/main/java/google/registry/model/UpdateAutoTimestamp.java#L74)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Already done.
</blockquote></details>

it doesn't look like it, I'm referring to setting the `timestamp` object


<!-- Sent from Reviewable.io -->

2021-09-24 21:02 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1341)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/UpdateAutoTimestamp.java, line 74 at r1](https://reviewable.io/reviews/google/nomulus/1341#-MkOZ_Q8E1S0Ini_ygEU:-MkObVt43kfJlYEP8joE:brmt4rv) ([raw file](https://github.com/google/nomulus/blob/edcea01e2cb7e657055fec2fdebeeea03b6e20e1/core/src/main/java/google/registry/model/UpdateAutoTimestamp.java#L74)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it doesn't look like it, I'm referring to setting the `timestamp` object
</blockquote></details>

Whoops, my bad.  Didn't realize that `timestamp` was itself a field and not just a local variable.  Set it too.


<!-- Sent from Reviewable.io -->

2021-09-24 21:04 UTC, gbrodman approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1341)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-09-27 15:32 UTC, merged

2021-09-27 15:37 UTC, gbrodman commented on core/src/test/java/google/registry/model/registrar/RegistrarTest.java
> +            .setName("John Abussy")
What was the reason for this change?