Fix BigQuery data set name handling in activity reporting
google/nomulus pull request #1361
Opened 2021-10-01 15:35 UTC by CydeWeys

This is not a constant (as it depends on runtime state), so it can't be named
using UPPER_SNAKE_CASE. Additionally, it's not good practice to use field
initialization when there's logic depending on runtime state involved. So this
PR changes the class to use constructor injection and moves the logic into the
constructor.

2021-10-01 16:01 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jianglai, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java, line 151 at r1](https://reviewable.io/reviews/google/nomulus/1361#-MkwZlLj2KgVuZk0Peb5:-Mkw_jp9-NkUo4WzacZ2:b-cg3flu) ([raw file](https://github.com/google/nomulus/blob/3764ab1fb7fb2f2f603681e9bcd6e1cc78233bae/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L151)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

why did you choose to remove public and not make it a private method 
</blockquote></details>

Because it's being called from `IcannReportingStager`, which is a different class.  `private` wouldn't work.


<!-- Sent from Reviewable.io -->

2021-10-01 16:04 UTC, jianglai approved these changes

2021-10-01 16:08 UTC, rachelguan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361#-:-MkwbJtH-p5Mtr_dAGp0:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-10-01 19:54 UTC, rachelguan approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-10-04 15:35 UTC, jianglai requested changes
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java, line 51 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAvapPEetaykOMoY5I:-MlAvapPEetaykOMoY5J:bg4vb66) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L51)):*
> ```
>     this.bigQueryDatasetName = tm().isOfy() ? "icann_reporting" : "cloud_sql_icann_reporting";
>   }
> ```
This should be injected as well like `TransactionReportingQueryBuilder`.
___
*[core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java, line 31 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAw5Mx8LRuoUh5Q9zn:-MlAw5Mx8LRuoUh5Q9zo:bw2axe7) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java#L31)):*
> ```
>  AppEngineExtension.builder().withDatastoreAndCloudSql().build();
> ```
Is `JpaTransactionManagerExtension` sufficient?


<!-- Sent from Reviewable.io -->

2021-10-04 17:30 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @jianglai, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java, line 51 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAvapPEetaykOMoY5I:-MlBFnGI0ifUkWQOpSrk:b-vi1l8m) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L51)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>     this.bigQueryDatasetName = tm().isOfy() ? "icann_reporting" : "cloud_sql_icann_reporting";
>   }
> ```
This should be injected as well like `TransactionReportingQueryBuilder`.
</blockquote></details>

Why?  Unlike `TransactionReportingQueryBuilder`, this isn't being depended on for another injection, so it doesn't strictly have to be an injection.  Given that it's only used in this one place, what's the benefit of injecting it?  It's just more lines of code doing the same thing.
___
*[core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java, line 31 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAw5Mx8LRuoUh5Q9zn:-MlBLrpx8Y-Kkwmrdet2:b-896fix) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java#L31)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>  AppEngineExtension.builder().withDatastoreAndCloudSql().build();
> ```
Is `JpaTransactionManagerExtension` sufficient?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-04 17:43 UTC, jianglai requested changes
> Reviewed 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 213 at r6](https://reviewable.io/reviews/google/nomulus/1361#-MlBNpKiE6v9YrG_IGiw:-MlBNpKiE6v9YrG_IGix:bqa5j3n) ([raw file](https://github.com/google/nomulus/blob/e2aea399a1cd63af519f85b865ea0e737c55f78e/core/src/main/java/google/registry/persistence/PersistenceModule.java#L213)):*
> ```
>   static TransactionManager provideTransactionManager() {
>     return tm();
> ```
Let's not do this for now. I'm not convince that this is the correct fix. And also the fix should not be in a single test, it should be in the DatabaseMigrationSchedule I believe, otherwise we could have another test that we forgot to put the jpa transaction manager extension in, which still succeeds when it runs after other tests.
___
*[core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java, line 51 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAvapPEetaykOMoY5I:-MlBOZjmEDaCARyX6VXE:bl94guw) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L51)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why?  Unlike `TransactionReportingQueryBuilder`, this isn't being depended on for another injection, so it doesn't strictly have to be an injection.  Given that it's only used in this one place, what's the benefit of injecting it?  It's just more lines of code doing the same thing.
</blockquote></details>

How is that different? Don't both of them depend on ` @Named(ICANN_REPORTING_DATA_SET)`?
___
*[core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java, line 31 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAw5Mx8LRuoUh5Q9zn:-MlBOMWMEaRoi9X5ccnT:b-q7f6xe) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java#L31)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Man, we have `JpaTransactionManagerExtension` and `JpaTestExtension`? The error messages says to use `JpaTransactionManagerExtension`.


<!-- Sent from Reviewable.io -->

2021-10-04 17:55 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java, line 31 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAw5Mx8LRuoUh5Q9zn:-MlBRaeZAjIuglJ8aqAz:b781mqt) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java#L31)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Man, we have `JpaTransactionManagerExtension` and `JpaTestExtension`? The error messages says to use `JpaTransactionManagerExtension`.
</blockquote></details>

Sorry, never mind. I read the code and understood the different now.


<!-- Sent from Reviewable.io -->

2021-10-04 19:10 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: all files reviewed, 3 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 213 at r6](https://reviewable.io/reviews/google/nomulus/1361#-MlBNpKiE6v9YrG_IGiw:-MlBhZMvCOZCcfUOvkJD:b-t5qb8o) ([raw file](https://github.com/google/nomulus/blob/e2aea399a1cd63af519f85b865ea0e737c55f78e/core/src/main/java/google/registry/persistence/PersistenceModule.java#L213)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>   static TransactionManager provideTransactionManager() {
>     return tm();
> ```
Let's not do this for now. I'm not convince that this is the correct fix. And also the fix should not be in a single test, it should be in the DatabaseMigrationSchedule I believe, otherwise we could have another test that we forgot to put the jpa transaction manager extension in, which still succeeds when it runs after other tests.
</blockquote></details>

This isn't an intended fix for anything, just a way to explicitly express that `IcannReportingModule.provideIcannReportingDataSet()` is dependent on the `TransactionManager`, rather than implicitly being dependent on it by calling the static `tm()` within its method body.
___
*[core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java, line 51 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAvapPEetaykOMoY5I:-MlBh8qT5dTrRbpVNmVD:b-m7atw2) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L51)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

How is that different? Don't both of them depend on ` @Named(ICANN_REPORTING_DATA_SET)`?
</blockquote></details>

In `IcannReportingModule`, `provideBigqueryConnection()` depends on the value being injected by `provideIcannReportingDataSet()`, which is why the latter is injected.  The same is not true here.  If I were to add `provideBigQueryDatasetName()`, no other provides method would be depending on it, so it'd be superfluous.  I don't see the point in adding it.
___
*[core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java, line 31 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAw5Mx8LRuoUh5Q9zn:-MlBhWvq9AOWDCIwR1e4:b-896fix) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/test/java/google/registry/reporting/icann/IcannReportingModuleTest.java#L31)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Sorry, never mind. I read the code and understood the different now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-04 19:35 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 213 at r6](https://reviewable.io/reviews/google/nomulus/1361#-MlBNpKiE6v9YrG_IGiw:-MlBn5qk8oZOtf6eP-GU:b-rkybo9) ([raw file](https://github.com/google/nomulus/blob/e2aea399a1cd63af519f85b865ea0e737c55f78e/core/src/main/java/google/registry/persistence/PersistenceModule.java#L213)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This isn't an intended fix for anything, just a way to explicitly express that `IcannReportingModule.provideIcannReportingDataSet()` is dependent on the `TransactionManager`, rather than implicitly being dependent on it by calling the static `tm()` within its method body.
</blockquote></details>

I don't see what's so special about this use case to make it worthwhile to explicitly express the dependency. We have a lot of incidents where we call `tm()` to make conditional choices.
___
*[core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java, line 51 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAvapPEetaykOMoY5I:-MlBk6ZU5l0kkG7klqYi:bfh3q0s) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L51)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

In `IcannReportingModule`, `provideBigqueryConnection()` depends on the value being injected by `provideIcannReportingDataSet()`, which is why the latter is injected.  The same is not true here.  If I were to add `provideBigQueryDatasetName()`, no other provides method would be depending on it, so it'd be superfluous.  I don't see the point in adding it.
</blockquote></details>

OK I'm more confused now. In `TransactionsReportingQueryBuilder`, you injected `@Named(ICANN_REPORTING_DATA_SET)` from `IcannReportingModule.provideBigQueryDatasetName()`, is that correct? What's wrong with injecting the same value here, assuming you get both `ActivityReportingQueryBuilder` and `TransactionsReportingQueryBuilder` from the same Dagger component. You don't have to add another `provideBigQueryDatasetName()` method.


<!-- Sent from Reviewable.io -->

2021-10-05 15:19 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java, line 51 at r4](https://reviewable.io/reviews/google/nomulus/1361#-MlAvapPEetaykOMoY5I:-MlG1MQ24E65bg62MNgI:b-afc3so) ([raw file](https://github.com/google/nomulus/blob/596684d901929eb774c1fb4da7cfad894ce04d7c/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L51)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

OK I'm more confused now. In `TransactionsReportingQueryBuilder`, you injected `@Named(ICANN_REPORTING_DATA_SET)` from `IcannReportingModule.provideBigQueryDatasetName()`, is that correct? What's wrong with injecting the same value here, assuming you get both `ActivityReportingQueryBuilder` and `TransactionsReportingQueryBuilder` from the same Dagger component. You don't have to add another `provideBigQueryDatasetName()` method.
</blockquote></details>

Done, using the same provides.


<!-- Sent from Reviewable.io -->

2021-10-05 15:21 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @jianglai, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 213 at r6](https://reviewable.io/reviews/google/nomulus/1361#-MlBNpKiE6v9YrG_IGiw:-MlG1YHmAF5-3tHEtcRK:b-n0ylyk) ([raw file](https://github.com/google/nomulus/blob/e2aea399a1cd63af519f85b865ea0e737c55f78e/core/src/main/java/google/registry/persistence/PersistenceModule.java#L213)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I don't see what's so special about this use case to make it worthwhile to explicitly express the dependency. We have a lot of incidents where we call `tm()` to make conditional choices.
</blockquote></details>

What's special about it is that it's in the dependency graph itself.  It feels dirty having a provides method implicitly depend on the current transaction manager, but not explicitly call that out as a dependency so that the Dagger dependency graph can be aware of that.  The other places where we call `tm()` to make conditional choices are not in Dagger provides methods as far as I'm aware.


<!-- Sent from Reviewable.io -->

2021-10-05 15:24 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @jianglai, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 213 at r6](https://reviewable.io/reviews/google/nomulus/1361#-MlBNpKiE6v9YrG_IGiw:-MlG2U2M6CAiYPZ8arlY:b-fp3tkm) ([raw file](https://github.com/google/nomulus/blob/e2aea399a1cd63af519f85b865ea0e737c55f78e/core/src/main/java/google/registry/persistence/PersistenceModule.java#L213)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What's special about it is that it's in the dependency graph itself.  It feels dirty having a provides method implicitly depend on the current transaction manager, but not explicitly call that out as a dependency so that the Dagger dependency graph can be aware of that.  The other places where we call `tm()` to make conditional choices are not in Dagger provides methods as far as I'm aware.
</blockquote></details>

If we have any other such places, they should explicitly be part of the Dependency graph as well.


<!-- Sent from Reviewable.io -->

2021-10-05 15:25 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @jianglai, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/rde/RdeStagingAction.java, line 227 at r8](https://reviewable.io/reviews/google/nomulus/1361#-MlG2e1GB1FUKMCbiQhc:-MlG2e1GB1FUKMCbiQhd:b-jltnk) ([raw file](https://github.com/google/nomulus/blob/f355d850349fe2e04350d19bf985f813b5ab505b/core/src/main/java/google/registry/rde/RdeStagingAction.java#L227)):*
> ```Java
>   @Inject GcsUtils gcsUtils;
>   @Inject MapreduceRunner mrRunner;
> ```

I don't know what's going on here, but the formatter was barfing on this file and insisted that I reformat it.


<!-- Sent from Reviewable.io -->

2021-10-05 15:41 UTC, weiminyu reviewed
PR 1371 is another attempt to fix TransactionReportingQueryBuilderTest. I think it is simpler.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361#-:-MlG67Qm9W4rZbcvzAHT:b-vh4a4w)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @jianglai, @rachelguan, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-10-05 17:27 UTC, jianglai requested changes
> Reviewed 6 of 7 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @jianglai, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/rde/BrdaCopyAction.java, line 76 at r11](https://reviewable.io/reviews/google/nomulus/1361#-MlGUBdj5JDVnu2dtoc2:-MlGUBdkEjDKatkvoFj-:bqivsqj) ([raw file](https://github.com/google/nomulus/blob/65ba6e5742d93d12f9f2b28e498fd27a76e7c4b3/core/src/main/java/google/registry/rde/BrdaCopyAction.java#L76)):*
> ```
>   @Inject
>   @Parameter(RdeModule.PARAM_PREFIX)
>   Optional<String> prefix;
> ```
This looks very out of place. The formater will say this is what it likes but I think you should either ignore it or convert every field to have annotations on separate lines.
___
*[core/src/main/java/google/registry/rde/RdeReportAction.java, line 73 at r11](https://reviewable.io/reviews/google/nomulus/1361#-MlGUNHM26TF8iySviin:-MlGUNHN0icsX3GzirPO:bxjsurd) ([raw file](https://github.com/google/nomulus/blob/65ba6e5742d93d12f9f2b28e498fd27a76e7c4b3/core/src/main/java/google/registry/rde/RdeReportAction.java#L73)):*
> ```
>   @Inject
>   @Parameter(RdeModule.PARAM_PREFIX)
>   Optional<String> prefix;
> ```
Same here.


<!-- Sent from Reviewable.io -->

2021-10-05 17:51 UTC, jianglai approved these changes
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @rachelguan, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-10-05 17:51 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai, @rachelguan, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/rde/BrdaCopyAction.java, line 76 at r11](https://reviewable.io/reviews/google/nomulus/1361#-MlGUBdj5JDVnu2dtoc2:-MlG_ENuCCxCKAtkfEqD:b1dhew9) ([raw file](https://github.com/google/nomulus/blob/65ba6e5742d93d12f9f2b28e498fd27a76e7c4b3/core/src/main/java/google/registry/rde/BrdaCopyAction.java#L76)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>   @Inject
>   @Parameter(RdeModule.PARAM_PREFIX)
>   Optional<String> prefix;
> ```
This looks very out of place. The formater will say this is what it likes but I think you should either ignore it or convert every field to have annotations on separate lines.
</blockquote></details>

Backed it out, maybe it'll pass now.
___
*[core/src/main/java/google/registry/rde/RdeReportAction.java, line 73 at r11](https://reviewable.io/reviews/google/nomulus/1361#-MlGUNHM26TF8iySviin:-MlGYD63D-HOnQNKZTWW:b1dhew9) ([raw file](https://github.com/google/nomulus/blob/65ba6e5742d93d12f9f2b28e498fd27a76e7c4b3/core/src/main/java/google/registry/rde/RdeReportAction.java#L73)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>   @Inject
>   @Parameter(RdeModule.PARAM_PREFIX)
>   Optional<String> prefix;
> ```
Same here.
</blockquote></details>

Backed it out, maybe it'll pass now.


<!-- Sent from Reviewable.io -->

2021-10-05 18:31 UTC, jianglai approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachelguan and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-10-05 19:11 UTC, merged