Provide useful error messages on flows run during read-only mode
google/nomulus pull request #1425
Opened 2021-11-16 20:41 UTC by gbrodman

We want to keep the read-only-mode-exception as an unchecked exception,
so we introduce a temporary check in the EppController that provides a
specific error message for this situation (rather than letting it fall
through to the generic "command failed" messaging

2021-11-18 18:57 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1425)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/flows/EppController.java, line 137 at r1](https://reviewable.io/reviews/google/nomulus/1425#-MooPInZ007idB2Yp3lZ:-MooPInZ007idB2Yp3l_:bvaarlm) ([raw file](https://github.com/google/nomulus/blob/c8835b16a97e643c28efaa18e1a561914854f290/core/src/main/java/google/registry/flows/EppController.java#L137)):*
> ```Java
>       EppException eppEx = (EppException) (e instanceof EppException ? e : e.getCause());
>       return getErrorResponse(eppEx.getResult(), flowComponent.trid());
>     } catch (ReadOnlyModeException e) {
> ```

Why this special-handling here rather than just having an `EppException`?


<!-- Sent from Reviewable.io -->

2021-11-18 19:05 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1425)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/flows/EppController.java, line 137 at r1](https://reviewable.io/reviews/google/nomulus/1425#-MooPInZ007idB2Yp3lZ:-MooQp3T8GH_KYeTZzEp:b-ifbyy5) ([raw file](https://github.com/google/nomulus/blob/c8835b16a97e643c28efaa18e1a561914854f290/core/src/main/java/google/registry/flows/EppController.java#L137)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why this special-handling here rather than just having an `EppException`?
</blockquote></details>

EppExceptions are checked exceptions, meaning that any place that threw it (e.g. the ReadOnlyCheckingEntityManager) would have to declare that it threw it, which isn't possible since we don't control the EntityManager interface. 


<!-- Sent from Reviewable.io -->

2021-11-19 20:41 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1425)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/flows/EppController.java, line 137 at r1](https://reviewable.io/reviews/google/nomulus/1425#-MooPInZ007idB2Yp3lZ:-MotusR41CSFpge6oqPn:b-tzpgcn) ([raw file](https://github.com/google/nomulus/blob/c8835b16a97e643c28efaa18e1a561914854f290/core/src/main/java/google/registry/flows/EppController.java#L137)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

EppExceptions are checked exceptions, meaning that any place that threw it (e.g. the ReadOnlyCheckingEntityManager) would have to declare that it threw it, which isn't possible since we don't control the EntityManager interface. 
</blockquote></details>

Can you implement this here as a catch and then rethrow an `EppException`?  This manual handling is a little strange.  I'd prefer if it were handled the same as any other `EppException` in the block above.  See `EppRuntimeException` -- that already has built-in handling and may be exactly what we need here.  That way `ReadOnlyModeException` can correctly be an `EppException`, but throw it wrapped inside an `EppRuntimeException` to get around checking concerns.  Then you won't need any special handling here at all.

The problem with your current implementation is that, by not declaring it as an `EppException` like everything else, you're violating some of the constraints for stuff we have built up around `EppException`s.  Namely, you're bypassing the presubmit that ensures that all exceptions can be thrown from EPP flows are documented properly in `flows.md` (which this read-only exception currently is not).


<!-- Sent from Reviewable.io -->

2021-11-22 18:24 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1425)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/flows/EppController.java, line 137 at r1](https://reviewable.io/reviews/google/nomulus/1425#-MooPInZ007idB2Yp3lZ:-Mp7sYau1Zq7ny-ivj0h:b3278fb) ([raw file](https://github.com/google/nomulus/blob/c8835b16a97e643c28efaa18e1a561914854f290/core/src/main/java/google/registry/flows/EppController.java#L137)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Can you implement this here as a catch and then rethrow an `EppException`?  This manual handling is a little strange.  I'd prefer if it were handled the same as any other `EppException` in the block above.  See `EppRuntimeException` -- that already has built-in handling and may be exactly what we need here.  That way `ReadOnlyModeException` can correctly be an `EppException`, but throw it wrapped inside an `EppRuntimeException` to get around checking concerns.  Then you won't need any special handling here at all.

The problem with your current implementation is that, by not declaring it as an `EppException` like everything else, you're violating some of the constraints for stuff we have built up around `EppException`s.  Namely, you're bypassing the presubmit that ensures that all exceptions can be thrown from EPP flows are documented properly in `flows.md` (which this read-only exception currently is not).
</blockquote></details>

not here, this is the place where exceptions get finally caught and converted to reasonable XML outputs. 

`EppRuntimeException` seems like a hack to get around the fact that `tm().transact()` doesn't declare any checked exceptions. 

Should `ReadOnlyModeException` be an EppException after all? It can be thrown from places other than EPP flows.


<!-- Sent from Reviewable.io -->

2021-11-23 16:09 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1425)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/flows/EppController.java, line 137 at r1](https://reviewable.io/reviews/google/nomulus/1425#-MooPInZ007idB2Yp3lZ:-MpCXCK_C4gmAwl-ikoz:b1q130o) ([raw file](https://github.com/google/nomulus/blob/c8835b16a97e643c28efaa18e1a561914854f290/core/src/main/java/google/registry/flows/EppController.java#L137)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

not here, this is the place where exceptions get finally caught and converted to reasonable XML outputs. 

`EppRuntimeException` seems like a hack to get around the fact that `tm().transact()` doesn't declare any checked exceptions. 

Should `ReadOnlyModeException` be an EppException after all? It can be thrown from places other than EPP flows.
</blockquote></details>

It should be an `EppException` so that it gets reported correctly through EPP (and documented as such).  If that's not feasible from the `TransactionManager` because it would create a circular package dependency, then add handling to catch and re-throw the correct one inside the flow package.  The most logical place for that would be here:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/flows/FlowRunner.java;l=82-100?q=flowrunner&ss=nomulus%2Fnomulus  And then, you would remove all of this special-cased handling here and just let it be handled as a normal `EppException`.

But as a general rule, any error that is thrown during an EPP flow and that is visible to the end user _MUST_ (in the RFC sense) be an `EppException`.  We tell registrars about `flows.md` and they use it as documentation when integrating with us.


<!-- Sent from Reviewable.io -->

2021-11-23 20:29 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1425)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/flows/EppController.java, line 137 at r1](https://reviewable.io/reviews/google/nomulus/1425#-MooPInZ007idB2Yp3lZ:-MpCtkG1D14belAzjPwA:b81s38p) ([raw file](https://github.com/google/nomulus/blob/c8835b16a97e643c28efaa18e1a561914854f290/core/src/main/java/google/registry/flows/EppController.java#L137)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It should be an `EppException` so that it gets reported correctly through EPP (and documented as such).  If that's not feasible from the `TransactionManager` because it would create a circular package dependency, then add handling to catch and re-throw the correct one inside the flow package.  The most logical place for that would be here:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/flows/FlowRunner.java;l=82-100?q=flowrunner&ss=nomulus%2Fnomulus  And then, you would remove all of this special-cased handling here and just let it be handled as a normal `EppException`.

But as a general rule, any error that is thrown during an EPP flow and that is visible to the end user _MUST_ (in the RFC sense) be an `EppException`.  We tell registrars about `flows.md` and they use it as documentation when integrating with us.
</blockquote></details>

It's infeasible to do that from the TransactionManager not because of the circular dependency, but because we don't control the declared checked exceptions on the interfaces that the ReadOnly* classes implement. 

Fun fact: you last paragraph is definitely not satisfied by the current code. An example is that `NotLoggedInException` can be thrown by (pretty much?) any flow but because it's tested in `ResourceFlowTestCase` it's not documented in any of the flow javadocs other than `LogoutFlow`. 

In order to document this exception we'd have to add a test to each flow, as shown here.  


<!-- Sent from Reviewable.io -->

2021-11-24 03:31 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1425)* status: 0 of 44 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/flows/EppController.java, line 137 at r1](https://reviewable.io/reviews/google/nomulus/1425#-MooPInZ007idB2Yp3lZ:-MpEz4QN7cwu-Ks8dAiV:bcgz2zw) ([raw file](https://github.com/google/nomulus/blob/c8835b16a97e643c28efaa18e1a561914854f290/core/src/main/java/google/registry/flows/EppController.java#L137)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It's infeasible to do that from the TransactionManager not because of the circular dependency, but because we don't control the declared checked exceptions on the interfaces that the ReadOnly* classes implement. 

Fun fact: you last paragraph is definitely not satisfied by the current code. An example is that `NotLoggedInException` can be thrown by (pretty much?) any flow but because it's tested in `ResourceFlowTestCase` it's not documented in any of the flow javadocs other than `LogoutFlow`. 

In order to document this exception we'd have to add a test to each flow, as shown here.  
</blockquote></details>

It might be worthwhile to separately fix the `NotLoggedInException` issue.
___
*[core/src/main/java/google/registry/flows/FlowRunner.java, line 103 at r2](https://reviewable.io/reviews/google/nomulus/1425#-MpEzMxS3ESnCqlIVTbQ:-MpEzMxS3ESnCqlIVTbR:bmun3iu) ([raw file](https://github.com/google/nomulus/blob/8721a2e5b8d86b18c2d0cf6859b8a431c1cc9c3e/core/src/main/java/google/registry/flows/FlowRunner.java#L103)):*
> ```Java
>       throw e.getCause();
>     } catch (ReadOnlyModeException e) {
>       throw new ReadOnlyModeEppException();
> ```

You're discarding `e` here.  Why not pass it as an inner exception to `ReadOnlyModeEppException`?  Then you can preserve the stack trace, so you can see where it was originally thrown.


<!-- Sent from Reviewable.io -->

2021-11-24 17:21 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1425)* status: 0 of 44 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/flows/EppController.java, line 137 at r1](https://reviewable.io/reviews/google/nomulus/1425#-MooPInZ007idB2Yp3lZ:-MpHvpXr475XQbxytxD1:b-olijr) ([raw file](https://github.com/google/nomulus/blob/c8835b16a97e643c28efaa18e1a561914854f290/core/src/main/java/google/registry/flows/EppController.java#L137)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It might be worthwhile to separately fix the `NotLoggedInException` issue.
</blockquote></details>

sure, that can be in a separate PR 
___
*[core/src/main/java/google/registry/flows/FlowRunner.java, line 103 at r2](https://reviewable.io/reviews/google/nomulus/1425#-MpEzMxS3ESnCqlIVTbQ:-MpHvSMNCZW2cdX927S3:b-84dktc) ([raw file](https://github.com/google/nomulus/blob/8721a2e5b8d86b18c2d0cf6859b8a431c1cc9c3e/core/src/main/java/google/registry/flows/FlowRunner.java#L103)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You're discarding `e` here.  Why not pass it as an inner exception to `ReadOnlyModeEppException`?  Then you can preserve the stack trace, so you can see where it was originally thrown.
</blockquote></details>

It requires rejiggering of EppException but sure 


<!-- Sent from Reviewable.io -->

2021-11-24 18:55 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1425)* status: 0 of 44 files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2021-11-24 19:57 UTC, merged