Add a new parameter headers to existing createTask() method
google/nomulus pull request #1448
Opened 2021-12-02 21:33 UTC by rachelguan

2021-12-06 17:22 UTC, jianglai requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jianglai and @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 116 at r1](https://reviewable.io/reviews/google/nomulus/1448#-MqFX3Ga4ndZeAu0TMXF:-MqFX3Ga4ndZeAu0TMXG:b-7tod19) ([raw file](https://github.com/google/nomulus/blob/4ad80239af9c297c980390ccec7b2148c73e65f0/util/src/main/java/google/registry/util/CloudTasksUtils.java#L116)):*
> ```
> checkNotNull(params, "Params cannot be empty");
> ```
I think it is OK for the params to be empty. We should make sure that the code handles null params correctly.
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/1448#-MqFl2p94Ms4hjS7D-HB:-MqFl2p94Ms4hjS7D-HC:b-oh9btq) ([raw file](https://github.com/google/nomulus/blob/4ad80239af9c297c980390ccec7b2148c73e65f0/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L55)):*
> ```
>     headers.put("X-DomainRegistry-ProjectId", "pid");
>     headers.put("X-DomainRegistry-JobId", "jid");
>     headers.put("X-DomainRegistry-ChainedTaskQueue", "ctq");
> ```
If these are all the things that you plan to put in the headers, why not just put them in the params?


<!-- Sent from Reviewable.io -->

2021-12-06 17:41 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 116 at r1](https://reviewable.io/reviews/google/nomulus/1448#-MqFX3Ga4ndZeAu0TMXF:-MqFoBXm0g5O7yFo_yUD:be1kb87) ([raw file](https://github.com/google/nomulus/blob/4ad80239af9c297c980390ccec7b2148c73e65f0/util/src/main/java/google/registry/util/CloudTasksUtils.java#L116)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> checkNotNull(params, "Params cannot be empty");
> ```
I think it is OK for the params to be empty. We should make sure that the code handles null params correctly.
</blockquote></details>

oh ok, because it actually breaks at encodedParam when params is null. 
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/1448#-MqFl2p94Ms4hjS7D-HB:-MqFp6pD9_qhq0tk7cy6:bw4lchd) ([raw file](https://github.com/google/nomulus/blob/4ad80239af9c297c980390ccec7b2148c73e65f0/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L55)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>     headers.put("X-DomainRegistry-ProjectId", "pid");
>     headers.put("X-DomainRegistry-JobId", "jid");
>     headers.put("X-DomainRegistry-ChainedTaskQueue", "ctq");
> ```
If these are all the things that you plan to put in the headers, why not just put them in the params?
</blockquote></details>

i am actually not sure why they were set as headers instead of regular params. 
I don't know if adding them to params would break the existing functionality/ 
https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/export/BigqueryPollJobAction.java;l=170?q=X-DomainRegistry-ProjectId&ss=nomulus%2Fnomulus


<!-- Sent from Reviewable.io -->

2021-12-06 20:48 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 116 at r1](https://reviewable.io/reviews/google/nomulus/1448#-MqFX3Ga4ndZeAu0TMXF:-MqGVFlwA_GfjejzxKoB:b-ik2o8v) ([raw file](https://github.com/google/nomulus/blob/4ad80239af9c297c980390ccec7b2148c73e65f0/util/src/main/java/google/registry/util/CloudTasksUtils.java#L116)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

oh ok, because it actually breaks at encodedParam when params is null. 
</blockquote></details>

    if (method == HttpMethod.GET) {
      path = String.format("%s?%s", path, encodedParams);
    } else if (method == HttpMethod.POST) {
      requestBuilder
          .putHeaders(HttpHeaders.CONTENT_TYPE, MediaType.FORM_DATA.toString())
          .setBody(ByteString.copyFrom(encodedParams, StandardCharsets.UTF_8));
    }
both use cases require params not to be null. 


<!-- Sent from Reviewable.io -->

2021-12-07 22:05 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jianglai and @rachelguan)

___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/1448#-MqFl2p94Ms4hjS7D-HB:-MqLv0zIC38sUTG2MbGk:b-xicgh1) ([raw file](https://github.com/google/nomulus/blob/4ad80239af9c297c980390ccec7b2148c73e65f0/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L55)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

i am actually not sure why they were set as headers instead of regular params. 
I don't know if adding them to params would break the existing functionality/ 
https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/export/BigqueryPollJobAction.java;l=170?q=X-DomainRegistry-ProjectId&ss=nomulus%2Fnomulus
</blockquote></details>

As discussed in standup, since we control both how the request is generated and how it is used, it is up to us where the information is saved, in the header or in query params. 


<!-- Sent from Reviewable.io -->

2021-12-10 18:21 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/1448#-MqFl2p94Ms4hjS7D-HB:-Mq_ZkbJEW1eG_jaG5VM:b-2bz9d5) ([raw file](https://github.com/google/nomulus/blob/4ad80239af9c297c980390ccec7b2148c73e65f0/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L55)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

As discussed in standup, since we control both how the request is generated and how it is used, it is up to us where the information is saved, in the header or in query params. 
</blockquote></details>

dropped the idea of adding a new parameter to ```createTask()```. The info is going to be in query params. This PR now is about adding support for null/empty params.


<!-- Sent from Reviewable.io -->

2021-12-11 03:43 UTC, jianglai requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: all files reviewed, 3 unresolved discussions (waiting on @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 118 at r2](https://reviewable.io/reviews/google/nomulus/1448#-MqbYbnR8Po-ES1lOSPk:-MqbYbnR8Po-ES1lOSPl:b-aobiwl) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L118)):*
> ```
> if (params != null) {
> ```
You only need to modify the path or the body when the param is not null, so why not put everything under the `if (params != null)` block?

```
if (params != null && !params.isEmpty()) {
  encodedParams = ...
  if (method == GET) {
  ...  
  } else {
  ...
  }
}
```
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 131 at r2](https://reviewable.io/reviews/google/nomulus/1448#-Mqb_Ao8Cu9fnzS3BgWK:-Mqb_Ao8Cu9fnzS3BgWL:b648bkn) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L131)):*
> ```
> "/" 
> ```
If you do what I suggested above, this would be irrelevant, but shouldn't it be `path : String.format(...)` instead of `"/" : String.format(...)`?
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 132 at r2](https://reviewable.io/reviews/google/nomulus/1448#-MqbYKiG7VLYuFxR0elM:-MqbYKiG7VLYuFxR0elN:b-6jq1xr) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L132)):*
> ```
> else if
> ```
This can just be `else` now, since you ruled out any method that is not a POST or GET.


<!-- Sent from Reviewable.io -->

2021-12-13 04:18 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: all files reviewed, 3 unresolved discussions (waiting on @jianglai and @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 118 at r2](https://reviewable.io/reviews/google/nomulus/1448#-MqbYbnR8Po-ES1lOSPk:-MqlzkrKEHal8AHuD_VB:b-xj5x6l) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L118)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> if (params != null) {
> ```
You only need to modify the path or the body when the param is not null, so why not put everything under the `if (params != null)` block?

```
if (params != null && !params.isEmpty()) {
  encodedParams = ...
  if (method == GET) {
  ...  
  } else {
  ...
  }
}
```
</blockquote></details>

well if  everything goes under  that check, then it means we are only handling case if param contains data. The cleanest way would be ```checkNotNull()``` at the very beginning for params. 

If GET and SET branches are under not null param block, a request will still be sent out with no param, but the task is still being built. Is that really the output we want to return? 


<!-- Sent from Reviewable.io -->

2021-12-13 05:06 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @jianglai)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 131 at r2](https://reviewable.io/reviews/google/nomulus/1448#-Mqb_Ao8Cu9fnzS3BgWK:-Mqm8Vnq6N03hBdjm6Hn:b-m7varr) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L131)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> "/" 
> ```
If you do what I suggested above, this would be irrelevant, but shouldn't it be `path : String.format(...)` instead of `"/" : String.format(...)`?
</blockquote></details>

should path stay the same for GET if there's params contains no value or null? 
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 132 at r2](https://reviewable.io/reviews/google/nomulus/1448#-MqbYKiG7VLYuFxR0elM:-Mqm8FCQ4XuIXTClVWKo:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L132)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> else if
> ```
This can just be `else` now, since you ruled out any method that is not a POST or GET.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-13 22:14 UTC, jianglai requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jianglai and @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 118 at r2](https://reviewable.io/reviews/google/nomulus/1448#-MqbYbnR8Po-ES1lOSPk:-MqpoxwNEFNF2KbcMiIc:bsr0f1s) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L118)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

well if  everything goes under  that check, then it means we are only handling case if param contains data. The cleanest way would be ```checkNotNull()``` at the very beginning for params. 

If GET and SET branches are under not null param block, a request will still be sent out with no param, but the task is still being built. Is that really the output we want to return? 
</blockquote></details>

Not sure whether we are on the same page here. I am proposing to put the GET and POST branches under the the null param block. You are given a path and potentially a list of query parameters. If the list is not empty then you need to either modify the path in case of a GET, or add a body in case of a POST. If it is null or empty you can just build the request with the given path.
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 131 at r2](https://reviewable.io/reviews/google/nomulus/1448#-Mqb_Ao8Cu9fnzS3BgWK:-MqpqmnC23Ap-dZdDw2j:b-kuw3ne) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L131)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

should path stay the same for GET if there's params contains no value or null? 
</blockquote></details>

Yes, we are only modifying the path if the params are not empty (and the request is a GET). We should never disregard the path that is provided to us.


<!-- Sent from Reviewable.io -->

2021-12-13 23:54 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 118 at r2](https://reviewable.io/reviews/google/nomulus/1448#-MqbYbnR8Po-ES1lOSPk:-MqqBD_d2twCSkwiNGRB:b-17rh4o) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L118)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Not sure whether we are on the same page here. I am proposing to put the GET and POST branches under the the null param block. You are given a path and potentially a list of query parameters. If the list is not empty then you need to either modify the path in case of a GET, or add a body in case of a POST. If it is null or empty you can just build the request with the given path.
</blockquote></details>

I extracted  ```   if (method == HttpMethod.POST) {
      requestBuilder.putHeaders(HttpHeaders.CONTENT_TYPE, MediaType.FORM_DATA.toString());
    } ``` out of the ```if (params != null && !params.isEmpty())``` because it's breaking test cases in ```TldFannoutActionTest```

i believe the cases that failed were the following which had to do with missing headers.  How should I handle these two cases? Should I modify the following test cases or do method check twice . 

```
  @Test
  void testSuccess_methodPostAndServiceBackendAreDefault() {
    run(getParamsMap("runInEmpty", ""));
    cloudTasksHelper.assertTasksEnqueued(
        QUEUE, new TaskMatcher().method(HttpMethod.POST).service("backend"));
  }

  @Test
  void testSuccess_runInEmpty() {
    run(getParamsMap("runInEmpty", ""));
    assertTaskWithoutTld();
  }

```
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 131 at r2](https://reviewable.io/reviews/google/nomulus/1448#-Mqb_Ao8Cu9fnzS3BgWK:-MqqBD831k9QuptLDIFy:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L131)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Yes, we are only modifying the path if the params are not empty (and the request is a GET). We should never disregard the path that is provided to us.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-14 00:00 UTC, CydeWeys requested changes
What's the motivation for this change?  Add a paragraph to the commit description explaining why we want to support null or empty params.  What's the use case there?

2021-12-14 00:00 UTC, CydeWeys commented on util/src/main/java/google/registry/util/CloudTasksUtils.java
> +        String.format("HTTP method %s is used. Only GET and POST are allowed.", method));
You don't need to use `String.format` inside a `checkArgument` call.  There's an overload of `checkArgument()` that already takes a format string on its own.

2021-12-14 00:00 UTC, CydeWeys commented on util/src/main/java/google/registry/util/CloudTasksUtils.java
> +    if (params != null && !params.isEmpty()) {
`CollectionUtils.isNullOrEmpty()` should be applicable here (not 100% sure if I got that exactly right but it's used elsewhere in our codebase).

2021-12-14 18:55 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 111 at r4](https://reviewable.io/reviews/google/nomulus/1448#-Mpx3CsKTLsekf94cU99-r4-111:-MquH4Nj5wFg7tQ-RG0I:b-896fix) ([raw file](https://github.com/google/nomulus/blob/87266fd11d7159baabc80a43f33faae282099bd7/util/src/main/java/google/registry/util/CloudTasksUtils.java#L111)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You don't need to use `String.format` inside a `checkArgument` call.  There's an overload of `checkArgument()` that already takes a format string on its own.
</blockquote></details>

Done.
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 120 at r4](https://reviewable.io/reviews/google/nomulus/1448#-Mpx3CsKTLsekf94cU99-r4-120:-MquH54c5_AFOnRUWxgG:b9sd8nt) ([raw file](https://github.com/google/nomulus/blob/87266fd11d7159baabc80a43f33faae282099bd7/util/src/main/java/google/registry/util/CloudTasksUtils.java#L120)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`CollectionUtils.isNullOrEmpty()` should be applicable here (not 100% sure if I got that exactly right but it's used elsewhere in our codebase).
</blockquote></details>

```CollectionUtils.isNullOrEmpty()``` takes either a ```Map``` or ```Iterable```   . Because the existing method uses a ```MultiMap```, in order to use the method from ```CollectionUtils```, ```params``` has to be converted using either ```params.asMap()``` or ```params.entries()```, which wouldn't work if ```params``` itself is already null. 


<!-- Sent from Reviewable.io -->

2021-12-16 21:49 UTC, jianglai requested changes
Given that this is a private method and none of its callers passes a null parameter, the check is not strictly necessary. But it is still good practice, and by moving the nullness and emptyness check before construction of `encodedParams` we bypass some unnecessary code.

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448#-:-Mr4CXpJ3gaN2l4eFw_J:bm6mcad)* status: all files reviewed, 2 unresolved discussions (waiting on @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 118 at r2](https://reviewable.io/reviews/google/nomulus/1448#-MqbYbnR8Po-ES1lOSPk:-Mr4AqJF3--xxTY78Dog:b-55inh2) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L118)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

I extracted  ```   if (method == HttpMethod.POST) {
      requestBuilder.putHeaders(HttpHeaders.CONTENT_TYPE, MediaType.FORM_DATA.toString());
    } ``` out of the ```if (params != null && !params.isEmpty())``` because it's breaking test cases in ```TldFannoutActionTest```

i believe the cases that failed were the following which had to do with missing headers.  How should I handle these two cases? Should I modify the following test cases or do method check twice . 

```
  @Test
  void testSuccess_methodPostAndServiceBackendAreDefault() {
    run(getParamsMap("runInEmpty", ""));
    cloudTasksHelper.assertTasksEnqueued(
        QUEUE, new TaskMatcher().method(HttpMethod.POST).service("backend"));
  }

  @Test
  void testSuccess_runInEmpty() {
    run(getParamsMap("runInEmpty", ""));
    assertTaskWithoutTld();
  }

```
</blockquote></details>

The latest commit has the `if (method == POST)` block inside the null & empty conditional block. Is it still breaking the tests? If so, what's the failure message?
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 104 at r5](https://reviewable.io/reviews/google/nomulus/1448#-Mr4CGNv8ajclRLT8yLP:-Mr4CGNv8ajclRLT8yLQ:b-8gtaeg) ([raw file](https://github.com/google/nomulus/blob/3ad7ecc33f74a9a2091cc4a44b2bf122105ba245/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L104)):*
> ```Java
>         .isEqualTo("application/x-www-form-urlencoded");
>     assertThat(task.getAppEngineHttpRequest().getBody().toString(StandardCharsets.UTF_8))
>         .isEqualTo("");
> ```

You can use `isEmpty()`. Same below.



_Code quote:_
```Java
.isEqualTo("");
```


<!-- Sent from Reviewable.io -->

2021-12-16 22:20 UTC, rachelguan reviewed
In additional to Lai's comment, there are existing ```TaskOptions``` objects that are created with no parameters. All the public methods for creating tasks in ```CloudTasksUtil``` assume params to always be non empty. For example, in ```IcannReportingStagingAction```, an upload task is created with a path, method, and countdown millis, then it gets added to ```CRON_QUEUE```.             
```TaskOptions uploadTask =
                TaskOptions.Builder.withUrl(IcannReportingUploadAction.PATH)
                    .method(Method.POST)
                    .countdownMillis(Duration.standardMinutes(2).getMillis());
            QueueFactory.getQueue(CRON_QUEUE).add(uploadTask);
```

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448#-:-Mr4IcaK1eaM2CckuQb8:bfsq70m)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 118 at r2](https://reviewable.io/reviews/google/nomulus/1448#-MqbYbnR8Po-ES1lOSPk:-Mr4HS_BD_YBwN7GiMqs:b-ddhnzo) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L118)):*
> d and none of its callers passes a null parameter, the check is not strictly necessary. But it is still good practice, and by moving the nullness and emptyness check before construction of encodedParams we bypass some unnecessary code.

the latest commit has ```if(method === POST) ``` twice, one as itself and another inside the null & empty conditional block. This way, it wont break the two existing test cases in ```TldFanoutAction```


<!-- Sent from Reviewable.io -->

2021-12-17 03:02 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: all files reviewed, 1 unresolved discussion (waiting on @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 118 at r2](https://reviewable.io/reviews/google/nomulus/1448#-MqbYbnR8Po-ES1lOSPk:-Mr5JCJxBP7QDxkYBz3l:brm966q) ([raw file](https://github.com/google/nomulus/blob/8bf21543752cdae893960ec29a9d6837eec35740/util/src/main/java/google/registry/util/CloudTasksUtils.java#L118)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

> d and none of its callers passes a null parameter, the check is not strictly necessary. But it is still good practice, and by moving the nullness and emptyness check before construction of encodedParams we bypass some unnecessary code.

the latest commit has ```if(method === POST) ``` twice, one as itself and another inside the null & empty conditional block. This way, it wont break the two existing test cases in ```TldFanoutAction```
</blockquote></details>

OK I see what you meant. So I gave it some thoughts and I think when there's no param to set (hence no body) in a POST,  we should not set the content type because there is no content. However regardless of if there is a body we should always set the [`Content-Length`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) to be equal to the size of the body. App engine can work without this header because it can determine the content length when the connection is terminated, but other web server might fail to parse a POST without this header when a connection is long lived. For best practice it is always a good idea to explicitly set `Content-Length`.

If there are tests that fail after you make the change, we should modify the tests.


<!-- Sent from Reviewable.io -->

2022-01-10 21:03 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 104 at r5](https://reviewable.io/reviews/google/nomulus/1448#-Mr4CGNv8ajclRLT8yLP:-Mr5TBYBAiT39ctkarlY:b-896fix) ([raw file](https://github.com/google/nomulus/blob/3ad7ecc33f74a9a2091cc4a44b2bf122105ba245/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L104)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

You can use `isEmpty()`. Same below.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 15:35 UTC, jianglai requested changes
> Reviewed 1 of 1 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @rachelguan)

___
*[core/src/test/java/google/registry/testing/CloudTasksHelper.java, line 240 at r8](https://reviewable.io/reviews/google/nomulus/1448#-Mt8l6Pg1b3AIsP5flgY:-Mt8l6Pg1b3AIsP5flgZ:b-ubfili) ([raw file](https://github.com/google/nomulus/blob/99184a7e07f6ec593c33e3fca05d5f9a1a63c347/core/src/test/java/google/registry/testing/CloudTasksHelper.java#L240)):*
> ```Java
>         query = task.getAppEngineHttpRequest().getBody().toString(StandardCharsets.UTF_8);
>       }
>       if (query != null) {
> ```

You can check `query.isEmpty()`, instead of in the if statement. It's easier for readers to understand why the check is necessary this way.



_Code quote:_
```Java
      if (query != null) {
```


<!-- Sent from Reviewable.io -->

2022-01-11 19:04 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1448)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[core/src/test/java/google/registry/testing/CloudTasksHelper.java, line 240 at r8](https://reviewable.io/reviews/google/nomulus/1448#-Mt8l6Pg1b3AIsP5flgY:-Mt9W_ZM9C4a4CCkE-rj:b76h1zf) ([raw file](https://github.com/google/nomulus/blob/99184a7e07f6ec593c33e3fca05d5f9a1a63c347/core/src/test/java/google/registry/testing/CloudTasksHelper.java#L240)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

You can check `query.isEmpty()`, instead of in the if statement. It's easier for readers to understand why the check is necessary this way.
</blockquote></details>

I actually removed the variable `query` and assigned the string directly to `paramBuilder` since there's no use case for it to be `null`. 


<!-- Sent from Reviewable.io -->

2022-01-13 17:44 UTC, merged