Speed up updating of premium lists
google/nomulus pull request #1482
Opened 2021-12-29 22:21 UTC by gbrodman

There are two parts to this:
1. Don't load the premium entries in the command prompt (this isn't
necessary and we didn't display that information anyway).
2. Set a proper batch size (rather than just 1) when saving all the
premium entries. This means that we generate only one INSERT statement
rather than N statements.

2021-12-29 23:13 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/model/tld/label/PremiumListDao.java, line 177 at r1](https://reviewable.io/reviews/google/nomulus/1482#-Ms7Sysi-DIn_YqB5XWU:-Ms7SysjDW-qLk8C1PEt:b42zkft) ([raw file](https://github.com/google/nomulus/blob/0dcf7501dd5690d58773b5261ba2e0443c9a60ff/core/src/main/java/google/registry/model/tld/label/PremiumListDao.java#L177)):*
> ```Java
>                                     savedPremiumList.get().getRevisionId(), value, key)));
>                 ImmutableSet<PremiumEntry> entries = entriesBuilder.build();
>                 jpaTm().getEntityManager().unwrap(Session.class).setJdbcBatchSize(entries.size());
> ```

Let's do this globally rather than just in one place.  It will probably speed up other things as well.


<!-- Sent from Reviewable.io -->

2021-12-29 23:28 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/model/tld/label/PremiumListDao.java, line 177 at r1](https://reviewable.io/reviews/google/nomulus/1482#-Ms7Sysi-DIn_YqB5XWU:-Ms7WCSy-2lxvn7fLPBH:b-ts545a) ([raw file](https://github.com/google/nomulus/blob/0dcf7501dd5690d58773b5261ba2e0443c9a60ff/core/src/main/java/google/registry/model/tld/label/PremiumListDao.java#L177)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Let's do this globally rather than just in one place.  It will probably speed up other things as well.
</blockquote></details>

Yeah, was just doing this after our conversation. It gets us most of the benefits (in the test, it only goes from like 2.1 to 2.2 seconds whereas no batching gives like 7.5 seconds) 


<!-- Sent from Reviewable.io -->

2021-12-29 23:30 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/model/tld/label/PremiumListDao.java, line 177 at r1](https://reviewable.io/reviews/google/nomulus/1482#-Ms7Sysi-DIn_YqB5XWU:-Ms7Wr1f4o4fMx_8-_p3:bh8586r) ([raw file](https://github.com/google/nomulus/blob/0dcf7501dd5690d58773b5261ba2e0443c9a60ff/core/src/main/java/google/registry/model/tld/label/PremiumListDao.java#L177)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah, was just doing this after our conversation. It gets us most of the benefits (in the test, it only goes from like 2.1 to 2.2 seconds whereas no batching gives like 7.5 seconds) 
</blockquote></details>

hibernate docs seem to be down btw

https://web.archive.org/web/20211102130501/https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html


<!-- Sent from Reviewable.io -->

2021-12-30 17:59 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 100 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUTFR3JCKM4w2D14r:-MsBUTFR3JCKM4w2D14s:bc1hbcf) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/main/java/google/registry/persistence/PersistenceModule.java#L100)):*
> ```Java
>   public static final String JDBC_BATCH_SIZE = "hibernate.jdbc.batch_size";
> 
>   private static final int DEFAULT_SERVER_BATCH_SIZE = 50;
> ```

Does it make sense to make these two YAML-configurable?  (They would go under the `cloudSql:` section.)  Any reason they can't be?
___
*[core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java, line 257 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUAoK52zQ-b8yLrfA:-MsBUAoK52zQ-b8yLrfB:b-vtwvwg) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java#L257)):*
> ```Java
> 
>   @Test
>   @Timeout(value = 5)
> ```

It seems like this test will fail needlessly on less powerful hardware or when the integration server is busy?  I just don't think it makes sense to write a test that is timeboxed on an arbitrary amount of time?


<!-- Sent from Reviewable.io -->

2021-12-30 18:12 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 100 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUTFR3JCKM4w2D14r:-MsBX6pY-5p82HUv4V4M:bibev0z) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/main/java/google/registry/persistence/PersistenceModule.java#L100)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Does it make sense to make these two YAML-configurable?  (They would go under the `cloudSql:` section.)  Any reason they can't be?
</blockquote></details>

No, I don't believe so. Fetch and batch size shouldn't vary by user (i.e. us vs some other theoretical registry that uses the open-source software) and even the Hibernate docs seem to recommend a simple set-it-and-forget-it setting in the hardcoded XML config. 
___
*[core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java, line 257 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUAoK52zQ-b8yLrfA:-MsBWFbG8g9BxiQtyNZu:bp4za95) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java#L257)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It seems like this test will fail needlessly on less powerful hardware or when the integration server is busy?  I just don't think it makes sense to write a test that is timeboxed on an arbitrary amount of time?
</blockquote></details>

Do you have any better suggestions? On my machine this test took  ~2.2 seconds to pass with the changes implemented and ~6.2 seconds without them implemented. 


<!-- Sent from Reviewable.io -->

2021-12-30 19:01 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 100 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUTFR3JCKM4w2D14r:-MsBhhrD2Jo3xbJ2E6YQ:bqfcx61) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/main/java/google/registry/persistence/PersistenceModule.java#L100)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

No, I don't believe so. Fetch and batch size shouldn't vary by user (i.e. us vs some other theoretical registry that uses the open-source software) and even the Hibernate docs seem to recommend a simple set-it-and-forget-it setting in the hardcoded XML config. 
</blockquote></details>

I can easily see use cases where other registries might want to change this (e.g. if they're using a differently sized Cloud SQL instance than we are).  Plus, this is something we ourselves might want to configure, and it's nicer to be able to change a line in a text file in an emergency (e.g. download the project, change this one line, re-upload the project) rather than having to rebuild/re-deploy the entire project.
___
*[core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java, line 257 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUAoK52zQ-b8yLrfA:-MsBhWF51V1gY9M7hyyK:bl0jct8) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java#L257)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Do you have any better suggestions? On my machine this test took  ~2.2 seconds to pass with the changes implemented and ~6.2 seconds without them implemented. 
</blockquote></details>

Yeah, a performance benchmark suite.  The key thing is it's metrics, rather than pass/fail.  You can track the performance of tests over time and spot regressions.

Pass/fail just doesn't work though.


<!-- Sent from Reviewable.io -->

2021-12-30 19:18 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 100 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUTFR3JCKM4w2D14r:-MsBkIhu2r9gPFkb9ZsZ:bn7r3cr) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/main/java/google/registry/persistence/PersistenceModule.java#L100)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I can easily see use cases where other registries might want to change this (e.g. if they're using a differently sized Cloud SQL instance than we are).  Plus, this is something we ourselves might want to configure, and it's nicer to be able to change a line in a text file in an emergency (e.g. download the project, change this one line, re-upload the project) rather than having to rebuild/re-deploy the entire project.
</blockquote></details>

Different SQL sizes won't affect this, the only thing that would affect this is the data. This is a safe and recommended-by-Hibernate setting, one that we shouldn't ever need to change. I think you're overthinking it. 
___
*[core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java, line 257 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUAoK52zQ-b8yLrfA:-MsBlkNt9tq8eDXLO450:b-ib2z0m) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java#L257)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yeah, a performance benchmark suite.  The key thing is it's metrics, rather than pass/fail.  You can track the performance of tests over time and spot regressions.

Pass/fail just doesn't work though.
</blockquote></details>

Are you suggesting we add that in? It seems like complete overkill for this one test, and the alternative is just removing the test entirely. Pass/fail definitely works here, especially since the test would have to take three times the usual length of time for it to fail. 


<!-- Sent from Reviewable.io -->

2021-12-30 19:30 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 100 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUTFR3JCKM4w2D14r:-MsBoKZh7NAbC5T5CKx1:bwyrl8d) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/main/java/google/registry/persistence/PersistenceModule.java#L100)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Different SQL sizes won't affect this, the only thing that would affect this is the data. This is a safe and recommended-by-Hibernate setting, one that we shouldn't ever need to change. I think you're overthinking it. 
</blockquote></details>

How am I overthinking it?  Look at how much stuff is in the YAML configs.  This fits right in with everything else.  We already have an entire section of Hibernate config options in the YAML files.  If anything it's weird to have this one thing not be in there when all of those are, as this is just another knob to be tuned.
___
*[core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java, line 257 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUAoK52zQ-b8yLrfA:-MsBnzS20tw4pZfIr9Dr:b-pyig8v) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java#L257)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Are you suggesting we add that in? It seems like complete overkill for this one test, and the alternative is just removing the test entirely. Pass/fail definitely works here, especially since the test would have to take three times the usual length of time for it to fail. 
</blockquote></details>

Yes, it would be separate and certainly a nice thing to have.  But pass/fail simply doesn't work -- this is going to cause flakes.


<!-- Sent from Reviewable.io -->

2022-01-05 20:58 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 100 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUTFR3JCKM4w2D14r:-Msg0vaI2aLa15DugFa5:bfl5f1t) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/main/java/google/registry/persistence/PersistenceModule.java#L100)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

How am I overthinking it?  Look at how much stuff is in the YAML configs.  This fits right in with everything else.  We already have an entire section of Hibernate config options in the YAML files.  If anything it's weird to have this one thing not be in there when all of those are, as this is just another knob to be tuned.
</blockquote></details>

I just don't think we or anyone else will need to change this, and it's the way we previously implemented the JDBC fetch size parameter, but eh 
___
*[core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java, line 257 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUAoK52zQ-b8yLrfA:-Msg12k279dwRIsS8KLF:b-rr2pg9) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java#L257)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yes, it would be separate and certainly a nice thing to have.  But pass/fail simply doesn't work -- this is going to cause flakes.
</blockquote></details>

There's not really any way of doing  this test then, which I suppose isn't the worst thing in the world since it's a speed issue and not a correctness one. 


<!-- Sent from Reviewable.io -->

2022-01-07 20:51 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java, line 257 at r2](https://reviewable.io/reviews/google/nomulus/1482#-MsBUAoK52zQ-b8yLrfA:-MsqINKjDw5-d3LrQial:bj0dbzj) ([raw file](https://github.com/google/nomulus/blob/545e47f7f9ca9042b486074910755efdbc2ad327/core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java#L257)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

There's not really any way of doing  this test then, which I suppose isn't the worst thing in the world since it's a speed issue and not a correctness one. 
</blockquote></details>

Probably the best thing to do for now in the absence of proper benchmark/performance testing would be to have the test as a normal test (no `@Timeout`), record its own timing, and then log to stderr if the test takes too long, without throwing an Exception that causes the test to fail.  That way it will create output that someone will probably see at some point if it persists (and people running on slow hardware can just get used to ignoring it), but it won't cause the test suite to fail.


<!-- Sent from Reviewable.io -->

2022-01-07 20:52 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 224 at r4](https://reviewable.io/reviews/google/nomulus/1482#-MsqJ0_l1lAsBB_dBbQD:-MsqJ0_l1lAsBB_dBbQE:b-w1xxl0) ([raw file](https://github.com/google/nomulus/blob/99fefae9b8893ce14d49c7661fe2d862c0d66f6e/core/src/main/java/google/registry/config/files/default-config.yaml#L224)):*
> ```YAML
>   hikariMaximumPoolSize: 10
>   hikariIdleTimeout: 300000
>   jdbcBatchSize: 50
> ```

Add comments explaining these (note how everything else in this file is commented with an explanation of what it is).


<!-- Sent from Reviewable.io -->

2022-01-07 21:19 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/config/files/default-config.yaml, line 224 at r4](https://reviewable.io/reviews/google/nomulus/1482#-MsqJ0_l1lAsBB_dBbQD:-MsqMd6K0I2zruYm5_4L:b-lvdnze) ([raw file](https://github.com/google/nomulus/blob/99fefae9b8893ce14d49c7661fe2d862c0d66f6e/core/src/main/java/google/registry/config/files/default-config.yaml#L224)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Add comments explaining these (note how everything else in this file is commented with an explanation of what it is).
</blockquote></details>

not everything :) 


<!-- Sent from Reviewable.io -->

2022-01-07 21:52 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java, line 267 at r6](https://reviewable.io/reviews/google/nomulus/1482#-MsqWq4ZDffd7J8A90dx:-MsqWq4ZDffd7J8A90dy:bvfuqf6) ([raw file](https://github.com/google/nomulus/blob/76300b4ef42a26b4c6f22dc7f6f89514b5f23c0e/core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java#L267)):*
> ```Java
>   @Test
>   void testSave_largeSize_savedQuickly() {
>     long start = System.currentTimeMillis();
> ```

Fwiw, `StopWatch` is a nicer way of handling this: https://guava.dev/releases/24.0-jre/api/docs/com/google/common/base/Stopwatch.html
___
*[core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java, line 281 at r6](https://reviewable.io/reviews/google/nomulus/1482#-MsqWIZtAd2XcNa6s8Qd:-MsqWIZtAd2XcNa6s8Qe:b1kkkz6) ([raw file](https://github.com/google/nomulus/blob/76300b4ef42a26b4c6f22dc7f6f89514b5f23c0e/core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java#L281)):*
> ```Java
>     if (duration >= 6000) {
>       // Don't fail directly since we can't rely on what sort of machines the test is running on
>       System.err.println(
> ```

Fwiw, this is what `printf` is for.


<!-- Sent from Reviewable.io -->

2022-01-07 21:52 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1482#-:-MsqWwzzEElq6zaOhHG3:bnfp4nl)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)



<!-- Sent from Reviewable.io -->

2022-01-10 21:33 UTC, merged