Add DS validation to match Cloud DNS
google/nomulus pull request #1487
Opened 2022-01-10 22:32 UTC by sarahcaseybot

Add checks to only allow the creation of DS records that use record types or algorithms that are recognized by Cloud DNS. See b/209037111 for more details.

2022-01-11 15:58 UTC, mindhog requested changes
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/Algorithm.java, line 57 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8oBQj5bis31sUWNB6:-Mt8oBQk3sBL5-fnE9pe:b-b25hnd) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/Algorithm.java#L57)):*
> ```Java
>   }
> 
>   public static Algorithm fromWireValue(int wireValue) {
> ```

Add the "at-Nullable" annotation on the return type (and a comment indicating that it returns null on an unrecognized algorithm type).
___
*[core/src/main/java/google/registry/tools/DigestType.java, line 43 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8okZn-tFJeCB8WIic:-Mt8okZn-tFJeCB8WIid:b-a2s3gw) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/DigestType.java#L43)):*
> ```Java
> 
>   /** Fetches a DigestType enumeration constant by its IANA assigned value. */
>   public static DigestType fromWireValue(int wireValue) {
> ```

Same here ("at-Nullable" annotation, noted in comment)
___
*[core/src/main/java/google/registry/tools/DsRecord.java, line 51 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8qCuX4bH3YbPvaDKS:-Mt8qCuX4bH3YbPvaDKT:b-uweabs) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/DsRecord.java#L51)):*
> ```Java
>     checkArgument(
>         DigestType.fromWireValue(digestType) != null, "DS record uses an unrecognized digest type");
>     checkArgument(Algorithm.fromWireValue(alg) != null, "DS record uses an unrecognized algorithm");
> ```

checkArgumentNotNull() for these?


<!-- Sent from Reviewable.io -->

2022-01-11 16:27 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/Algorithm.java, line 57 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8oBQj5bis31sUWNB6:-Mt8xja_9J_jTfYxVlHF:b-hzfizz) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/Algorithm.java#L57)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Add the "at-Nullable" annotation on the return type (and a comment indicating that it returns null on an unrecognized algorithm type).
</blockquote></details>

Even better, this should be returning `Optional<Algorithm>`.  This is exactly the use case for `Optional`.  It will make the validity checking at the callsites better too.
___
*[core/src/main/java/google/registry/tools/DigestType.java, line 43 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8okZn-tFJeCB8WIic:-Mt8xqUY0G_j2bzKtynU:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/DigestType.java#L43)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Same here ("at-Nullable" annotation, noted in comment)
</blockquote></details>

Ditto.


<!-- Sent from Reviewable.io -->

2022-01-11 16:28 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/Algorithm.java, line 26 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8y2O26fVvcGY-LLR6:-Mt8y2O26fVvcGY-LLR7:b1ge6q3) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/Algorithm.java#L26)):*
> ```Java
>  * be found here: http://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml
>  */
> public enum Algorithm {
> ```

Why reinvent the wheel?  https://javadoc.io/static/dnsjava/dnsjava/3.3.1/org/xbill/DNS/DNSSEC.Algorithm.html


<!-- Sent from Reviewable.io -->

2022-01-11 16:31 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/DsRecord.java, line 51 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8qCuX4bH3YbPvaDKS:-Mt8ydo8A7Y_dwShEd5T:bdurcbq) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/DsRecord.java#L51)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

checkArgumentNotNull() for these?
</blockquote></details>

Would be `checkArgumentPresent()` per my suggestions.


<!-- Sent from Reviewable.io -->

2022-01-11 16:33 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/DsRecord.java, line 50 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8yqoB5MCTfivlyjct:-Mt8yqoB5MCTfivlyjcu:b-7y6qqc) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/DsRecord.java#L50)):*
> ```Java
>         digest.length());
>     checkArgument(
>         DigestType.fromWireValue(digestType) != null, "DS record uses an unrecognized digest type");
> ```

It's worth including the invalid data in the exception message for better clarity with registrars.
___
*[core/src/main/java/google/registry/tools/DsRecord.java, line 50 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8yyQm5iRfjRBqt44M:-Mt8yyQm5iRfjRBqt44N:b-juljc8) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/DsRecord.java#L50)):*
> ```Java
>         digest.length());
>     checkArgument(
>         DigestType.fromWireValue(digestType) != null, "DS record uses an unrecognized digest type");
> ```

Rather than a generic `IllegalArgumentException`, these need to be throwing `EppException`s so that they're handled properly in the EPP flow error response.  Remember, these are going to be visible to registrars as the returned result of a domain create or update flow.


<!-- Sent from Reviewable.io -->

2022-01-13 15:13 UTC, mindhog requested changes
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: 12 of 13 files reviewed, 8 unresolved discussions (waiting on @CydeWeys, @mindhog, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java, line 321 at r2](https://reviewable.io/reviews/google/nomulus/1487#-MtIz3bZ0bzXQBshQXFo:-MtIz3bZ0bzXQBshQXFp:bp2p8l6) ([raw file](https://github.com/google/nomulus/blob/bf3f7b5ea5eb5211067afde636496d9d81291fbe/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L321)):*
> ```Java
>                 data.getDigestType()));
>       }
>     }
> ```

Since we're getting in the business of DS record validation, I'm thinking we should also be verifying that the signature length is appropriate for the signature type. (I don't _think_ we need to worry about signature content, I think all of these types are opaque hash values but it might be worthwhile to do a quick verification of that from the RFCs)

We don't necessarily need to do that in this PR, but a TODO and a follow-up PR would be good.
___
*[core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java, line 648 at r2](https://reviewable.io/reviews/google/nomulus/1487#-MtIxaBuEuYH2RmYYhm9:-MtIxaBuEuYH2RmYYhmA:bifm6to) ([raw file](https://github.com/google/nomulus/blob/bf3f7b5ea5eb5211067afde636496d9d81291fbe/core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java#L648)):*
> ```Java
>       builder.add(DelegationSignerData.create(i, 2, 2, new byte[] {0, 1, 2}));
>     }
>     ImmutableSet<DelegationSignerData> commonDsData = builder.build();
> ```

Add a test that GOST (type 3) is invalid? (sorry, I should have caught this in the first pass)


<!-- Sent from Reviewable.io -->

2022-01-13 19:47 UTC, mindhog approved these changes
> Reviewed 1 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed, 6 unresolved discussions (waiting on @CydeWeys and @mindhog)



<!-- Sent from Reviewable.io -->

2022-01-13 21:20 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed, 6 unresolved discussions (waiting on @CydeWeys, @mindhog, and @sarahcaseybot)

___
*[core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java, line 818 at r3](https://reviewable.io/reviews/google/nomulus/1487#-MtKIzjI5IaoEk3UW1BQ:-MtKIzjI5IaoEk3UW1BR:b-172uz9) ([raw file](https://github.com/google/nomulus/blob/b14fb652a93911866a0bfcfb70aedc6092fad295/core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java#L818)):*
> ```Java
> 
>   @TestOfyAndSql
>   void testFailure_secDnsinvalidDigestType() throws Exception {
> ```

Tests like these should be in the domain create flow tests too.


<!-- Sent from Reviewable.io -->

2022-01-13 21:26 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @mindhog, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java, line 310 at r3](https://reviewable.io/reviews/google/nomulus/1487#-MtKJYMC1pW0U8PO9_m-:-MtKJYMC1pW0U8PO9_m0:b-c1bq42) ([raw file](https://github.com/google/nomulus/blob/b14fb652a93911866a0bfcfb70aedc6092fad295/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L310)):*
> ```Java
>         try {
>           Algorithm.string(data.getAlgorithm());
>         } catch (IllegalArgumentException e) {
> ```

It's kind of a code smell to immediately catch and check for an exception you're throwing.  Also, the call to `Algorithm.string(...)` is kind of awkward since you aren't using the return value at all.  Rather than using thrown Exceptions to represent the fact that the algorithm is invalid, just implement a `validate()` method that returns `true`/`false`.  That's a better practice, and it's more performant.

Then you can do something like:

```
ImmutableSet<DelegationSignerData> invalidAlgorithms = dsData.stream().filter(ds -> !Algorithm.isValid(ds.getAlgorithm()).collect(toImmutableSet());
if (!invalidAlgorithms.isEmpty()) {
  // throw EPP exception with contents of invalidAlgorithms in message
}
```
___
*[core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java, line 311 at r3](https://reviewable.io/reviews/google/nomulus/1487#-MtKJS0a9rv8IwQS9SPv:-MtKJS0a9rv8IwQS9SPw:b-k9f4ai) ([raw file](https://github.com/google/nomulus/blob/b14fb652a93911866a0bfcfb70aedc6092fad295/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L311)):*
> ```Java
>           Algorithm.string(data.getAlgorithm());
>         } catch (IllegalArgumentException e) {
>           throw new InvalidDsRecordException(
> ```

This will only throw on the first invalid DS record, rather than all invalid DS records.  It needs to collect all that are invalid and then return all of them in the returned error message.
___
*[core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java, line 1245 at r3](https://reviewable.io/reviews/google/nomulus/1487#-MtKJEhe95_6E2lOyOf_:-MtKJEhe95_6E2lOyOfa:bz38ums) ([raw file](https://github.com/google/nomulus/blob/b14fb652a93911866a0bfcfb70aedc6092fad295/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L1245)):*
> ```Java
> 
>   /** Domain has an invalid DS record. */
>   static class InvalidDsRecordException extends ParameterValuePolicyErrorException {
> ```

You need to add matching ` * @error {@link DomainFlowUtils.InvalidDsRecordException}` lines to all EPP flows that can throw this exception, and update `flows.md` accordingly.  I think this affects, at a minimum, the create and update flow. Any others?


<!-- Sent from Reviewable.io -->

2022-01-20 16:39 UTC, mindhog approved these changes
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @mindhog, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/DsRecord.java, line 69 at r4](https://reviewable.io/reviews/google/nomulus/1487#-MtsLLtV33npIEDelQm8:-MtsLLtV33npIEDelQm9:bx0dymr) ([raw file](https://github.com/google/nomulus/blob/db1e4e0efcc7cac72906d50d245aa4da63a097d3/core/src/main/java/google/registry/tools/DsRecord.java#L69)):*
> ```Java
>     // integer wire value.
>     String algorithm = Algorithm.string(alg);
>     return !algorithm.equals(Integer.toString(alg));
> ```

It looks like this is duplicated in DomainFlowUtils.  Perhaps you could make this one public and call it from there?


<!-- Sent from Reviewable.io -->

2022-01-24 22:06 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed, 7 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/main/java/google/registry/tools/DsRecord.java, line 50 at r1](https://reviewable.io/reviews/google/nomulus/1487#-Mt8yyQm5iRfjRBqt44M:-MuD6e7j3lPSVIXzmT-h:b7akdr9) ([raw file](https://github.com/google/nomulus/blob/4aef333dc78472cf72c107643774f0403ec93be2/core/src/main/java/google/registry/tools/DsRecord.java#L50)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I noticed when trying to change this to an EppException, that this code is only called from the nomulus tool, and not from EPP commands. Keeping the error as an IAE here, but added similar checks to the DomainFlowUtils file that throws EppExceptions.
</blockquote></details>

`checkArgumentPresent(x)` is still better than `checkArgument(x.isPresent())`
___
*[core/src/test/java/google/registry/tools/CreateDomainCommandTest.java, line 330 at r4](https://reviewable.io/reviews/google/nomulus/1487#-MuD6ovB3tUMpHjdis5s:-MuD6ovB3tUMpHjdis5t:b-4atdkf) ([raw file](https://github.com/google/nomulus/blob/db1e4e0efcc7cac72906d50d245aa4da63a097d3/core/src/test/java/google/registry/tools/CreateDomainCommandTest.java#L330)):*
> ```Java
>                     "--ds_records=1 2 3 abcd",
>                     "example.tld"));
>     assertThat(thrown).hasMessageThat().contains("DS record uses an unrecognized digest type");
> ```

Can you make these `isEqualTo()` checks instead so that we can see the entire formatted error message, including the display presentation of the invalid digest types?  Same for these other tests.
___
*[core/src/test/resources/google/registry/flows/domain/domain_create_dsdata_bad_algorithms.xml, line 77 at r4](https://reviewable.io/reviews/google/nomulus/1487#-MuD721717phftXPbH8n:-MuD7218-Y5Z8Him60lP:b6wuto9) ([raw file](https://github.com/google/nomulus/blob/db1e4e0efcc7cac72906d50d245aa4da63a097d3/core/src/test/resources/google/registry/flows/domain/domain_create_dsdata_bad_algorithms.xml#L77)):*
> ```XML
>     <clTRID>ABC-12345</clTRID>
>   </command>
> </epp>
> ```

Missing newline.
___
*[core/src/test/resources/google/registry/flows/domain/domain_create_dsdata_bad_digest_types.xml, line 77 at r4](https://reviewable.io/reviews/google/nomulus/1487#-MuD7-S24EN2Q8R6WxNB:-MuD7-S24EN2Q8R6WxNC:b6wuto9) ([raw file](https://github.com/google/nomulus/blob/db1e4e0efcc7cac72906d50d245aa4da63a097d3/core/src/test/resources/google/registry/flows/domain/domain_create_dsdata_bad_digest_types.xml#L77)):*
> ```XML
>     <clTRID>ABC-12345</clTRID>
>   </command>
> </epp>
> ```

Missing newline.


<!-- Sent from Reviewable.io -->

2022-01-26 13:02 UTC, mindhog reviewed
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @mindhog)



<!-- Sent from Reviewable.io -->

2022-01-27 18:27 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed, 2 unresolved discussions (waiting on @mindhog and @sarahcaseybot)

___
*[core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java, line 819 at r5](https://reviewable.io/reviews/google/nomulus/1487#-MuRm73I-PUQ7NCoot4K:-MuRm73I-PUQ7NCoot4L:b-mjs34v) ([raw file](https://github.com/google/nomulus/blob/08c65721552d76cd5d3e47ac56af6612f8239ba7/core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java#L819)):*
> ```Java
>   @TestOfyAndSql
>   void testFailure_secDnsInvalidDigestType() throws Exception {
>     ImmutableSet.Builder<DelegationSignerData> builder = new ImmutableSet.Builder<>();
> ```

I'm not seeing why you're using `Builder`s in these tests.  This would be simpler if it were just:

```
ImmutableSet<DelegationSignerData> dsData = ImmutableSet.of(DelegationSignerData.create(1, 2, 3, new byte[] {0, 1, 2}));
// ...
persistResource(newDomainBase(getUniqueIdFromCommand()).asBuilder().setDsData(dsData).build());
```

If you have a small, static number of elements you're putting into a collection, you don't really need a Builder.  Just use the `of()` methods.  Same for everything below.


<!-- Sent from Reviewable.io -->

2022-01-28 19:19 UTC, mindhog reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1487)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)



<!-- Sent from Reviewable.io -->

2022-02-01 20:25 UTC, merged