Revert "Change from TaskQueueUtils to CloudTasksUtils in RdeStaging"
google/nomulus pull request #1513
Opened 2022-02-03 21:40 UTC by rachelguan

Reverts google/nomulus#1411

2022-02-03 21:41 UTC, jianglai commented
Let's give a brief description of the reason for the reversion.

2022-02-03 21:42 UTC, jianglai approved these changes

2022-02-03 22:01 UTC, weiminyu reviewed
I'll fix the test, and the duplicate task enqueueing is probably not a problem. Let's hold off for now.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1513#-:-Mv0aLDMCb_wOYQ53s9x:b-c0e8o1)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-04 03:27 UTC, jianglai requested changes
Looks like we don't have to do this after all.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1513#-:-Mv1lNp59ddCtMA6JvAm:bf2iir9)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-04 05:18 UTC, closed without merging