Make a few quality-of-life improvements in CloudTasksUtils
google/nomulus pull request #1521
Opened 2022-02-11 21:25 UTC by jianglai

1. Update the method names. There are too many overloaded methods and it
   is hard to figure out which one does which without checking the
   javadoc.

2. Added a method in the task matcher to specify the delay time in
   DateTime, so the caller does not need to convert it to Timestamp.

2022-02-14 22:02 UTC, rachelguan requested changes
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1521)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[core/src/test/java/google/registry/testing/CloudTasksHelper.java, line 311 at r3](https://reviewable.io/reviews/google/nomulus/1521#-MvuEuJc8IZIj7Cgvjxv:-MvuEuJd95Hk0s-A4V1g:bxqyj4u) ([raw file](https://github.com/google/nomulus/blob/243c7a4d7d711da954f1fd6b901d9e243bd7ca73/core/src/test/java/google/registry/testing/CloudTasksHelper.java#L311)):*
> ```Java
>     }
> 
>     public TaskMatcher scheduleTime(Timestamp scheduleTime) {
> ```

Since ```DateTime``` is now introduced to do time comparison, is it necessary to keep ```Timestamp``` schedule time method then?
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 227 at r3](https://reviewable.io/reviews/google/nomulus/1521#-MvuFN1c8OxmgVnX-vVa:-MvuFN1d1yo7QL80X5Z5:b-b0s2vn) ([raw file](https://github.com/google/nomulus/blob/243c7a4d7d711da954f1fd6b901d9e243bd7ca73/util/src/main/java/google/registry/util/CloudTasksUtils.java#L227)):*
> ```Java
>   public Task createPostTaskWithJitter(
>       String path,
>       String service,
> ```

I would like to know the reason behind removing static. I think that It's actually good that an instance of ```CloudTasksUtils``` is not required to create a task. A scenario could be, let's say you want to just create a Task object to do Task comparison.. without enqueueing or deleting a task from the queue.


<!-- Sent from Reviewable.io -->

2022-02-15 15:40 UTC, jianglai reviewed
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1521)* status: all files reviewed, 2 unresolved discussions (waiting on @rachelguan)

___
*[core/src/test/java/google/registry/testing/CloudTasksHelper.java, line 311 at r3](https://reviewable.io/reviews/google/nomulus/1521#-MvuEuJc8IZIj7Cgvjxv:-Mvy1Qhi1FMcuPoEykOZ:baf3ihw) ([raw file](https://github.com/google/nomulus/blob/243c7a4d7d711da954f1fd6b901d9e243bd7ca73/core/src/test/java/google/registry/testing/CloudTasksHelper.java#L311)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Since ```DateTime``` is now introduced to do time comparison, is it necessary to keep ```Timestamp``` schedule time method then?
</blockquote></details>

It doesn't hurt to keep it around. In general it make sense to have at least the setter that takes the exact same type and optionally there can be more setters that does implicit conversion of the arguments.
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 227 at r3](https://reviewable.io/reviews/google/nomulus/1521#-MvuFN1c8OxmgVnX-vVa:-Mvy12ZtDlVImFt4jRZu:b-a2rrh9) ([raw file](https://github.com/google/nomulus/blob/243c7a4d7d711da954f1fd6b901d9e243bd7ca73/util/src/main/java/google/registry/util/CloudTasksUtils.java#L227)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

I would like to know the reason behind removing static. I think that It's actually good that an instance of ```CloudTasksUtils``` is not required to create a task. A scenario could be, let's say you want to just create a Task object to do Task comparison.. without enqueueing or deleting a task from the queue.
</blockquote></details>

It's because all of the methods rely on the injected `clock`. It's conceivable that we can have static methods that create vanilla tasks and then non-static methods that create tasks with delays. But are there actually use cases where we'd create tasks but not compare them?


<!-- Sent from Reviewable.io -->

2022-02-15 20:32 UTC, rachelguan requested changes
The PR itself seems fine but there's a test case ```GenerateSpec11ReportActionTest.testSuccess()``` failing. Once that's fixed, this PR should be good to go! 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1521#-:-Mvz45HhBM45CawyKTun:bbhf8qh)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 227 at r3](https://reviewable.io/reviews/google/nomulus/1521#-MvuFN1c8OxmgVnX-vVa:-Mvyv2nB-rEw6epddHe8:b7dwt1s) ([raw file](https://github.com/google/nomulus/blob/243c7a4d7d711da954f1fd6b901d9e243bd7ca73/util/src/main/java/google/registry/util/CloudTasksUtils.java#L227)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It's because all of the methods rely on the injected `clock`. It's conceivable that we can have static methods that create vanilla tasks and then non-static methods that create tasks with delays. But are there actually use cases where we'd create tasks but not compare them?
</blockquote></details>

I don't think there's any use case that would do that..before using Cloud Task, when a task method whose purpose is to create a certain task without being enqueued. I think it does make sense to have to have ```CloudTaskUtil``` instance to call all the methods in the class. 


<!-- Sent from Reviewable.io -->

2022-02-18 20:24 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1521)* status: all files reviewed, 1 unresolved discussion (waiting on @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 227 at r3](https://reviewable.io/reviews/google/nomulus/1521#-MvuFN1c8OxmgVnX-vVa:-MwC9XMH9rtjgf69Leol:bb6sh2i) ([raw file](https://github.com/google/nomulus/blob/243c7a4d7d711da954f1fd6b901d9e243bd7ca73/util/src/main/java/google/registry/util/CloudTasksUtils.java#L227)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

I don't think there's any use case that would do that..before using Cloud Task, when a task method whose purpose is to create a certain task without being enqueued. I think it does make sense to have to have ```CloudTaskUtil``` instance to call all the methods in the class. 
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2022-02-18 21:21 UTC, jianglai reviewed
Fixed the test. PTAL.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1521#-:-MwDhRmRCCDxTQ3bWcNG:b-z3wg1x)* status: all files reviewed, 1 unresolved discussion (waiting on @rachelguan)



<!-- Sent from Reviewable.io -->

2022-02-19 01:21 UTC, merged