Fix DTR creation in one location and clean up replay comparison
google/nomulus pull request #1529
Opened 2022-02-22 19:41 UTC by gbrodman

We can't easily compare objects that are embedded in Datastore entities because when loading them from Datastore, we have no way of knowing their assigned SQL IDs. This shouldn't be super relevant because we're still comparing the parent entities to one another, so as long as those come back clean we should be OK.

2022-02-22 21:18 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java, line 1116 at r1](https://reviewable.io/reviews/google/nomulus/1529#-MwYHn70CB3TBSIO20Qh:-MwYHn70CB3TBSIO20Qi:bs7td6o) ([raw file](https://github.com/google/nomulus/blob/019b2826f600fa667abe7b98300075768452bd85/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L1116)):*
> ```Java
>           int cancelledAmount = -1 * record.getReportAmount();
>           recordsBuilder.add(
>               DomainTransactionRecord.create(
> ```

What is the intent of this change?  Is it to generate a new ID?


<!-- Sent from Reviewable.io -->

2022-02-22 21:39 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java, line 1116 at r1](https://reviewable.io/reviews/google/nomulus/1529#-MwYHn70CB3TBSIO20Qh:-MwYMTe-9UKgAigq67wk:b1wvcuf) ([raw file](https://github.com/google/nomulus/blob/019b2826f600fa667abe7b98300075768452bd85/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L1116)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What is the intent of this change?  Is it to generate a new ID?
</blockquote></details>

It resets the ID field and breaks the connection to the previous DomainTransactionRecord object. Otherwise, when you save the new parent history object, it re-parents the DTR on to that, meaning that the old history object loses it entirely. 


<!-- Sent from Reviewable.io -->

2022-02-22 22:33 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java, line 1116 at r1](https://reviewable.io/reviews/google/nomulus/1529#-MwYHn70CB3TBSIO20Qh:-MwYZ81f5cWyOYlqIzml:b-xsns9r) ([raw file](https://github.com/google/nomulus/blob/019b2826f600fa667abe7b98300075768452bd85/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L1116)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It resets the ID field and breaks the connection to the previous DomainTransactionRecord object. Otherwise, when you save the new parent history object, it re-parents the DTR on to that, meaning that the old history object loses it entirely. 
</blockquote></details>

Can you put that as a comment here?  It's super helpful.  Otherwise, this could end up being refactored using the `asBuilder().set...().build()` pattern later on by someone who doesn't know why it's specifically being done this way.


<!-- Sent from Reviewable.io -->

2022-02-22 22:37 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java, line 1116 at r1](https://reviewable.io/reviews/google/nomulus/1529#-MwYHn70CB3TBSIO20Qh:-MwY_58010pLMl_I2VNV:b-896fix) ([raw file](https://github.com/google/nomulus/blob/019b2826f600fa667abe7b98300075768452bd85/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L1116)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Can you put that as a comment here?  It's super helpful.  Otherwise, this could end up being refactored using the `asBuilder().set...().build()` pattern later on by someone who doesn't know why it's specifically being done this way.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-22 22:43 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529#-:-MwYaXrxBbTVAhNVCuKK:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-02-22 22:43 UTC, CydeWeys reviewed
Any way to test this?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529#-:-MwYa_wD5XVnfUTwOnsY:b-9t4a6q)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-02-22 22:43 UTC, CydeWeys reviewed
The ID rewriting specifically that is.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529#-:-MwYackJBA2oRliQjGNO:b2wpsnt)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-02-23 00:40 UTC, gbrodman reviewed
The DomainTransferRejectFlow tests fail without this fix, if that's what you're asking. That is, the state of the DB at the end of (some of) the test(s) isn't the same in Datastore/SQL without this fix. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529#-:-MwZ0KEY3oV9-3ix5_AX:b-xxke5a)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-02-23 12:33 UTC, mindhog requested changes
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 67 at r2](https://reviewable.io/reviews/google/nomulus/1529#-MwaYhwa21_b9NxMKXA7:-MwaYhwa21_b9NxMKXA8:b-289x4g) ([raw file](https://github.com/google/nomulus/blob/cc9783ab4fe6201e193c550d512d18a9979664c5/core/src/main/java/google/registry/model/contact/ContactHistory.java#L67)):*
> ```Java
>   // Store ContactBase instead of ContactResource so we don't pick up its @Id
>   // Nullable for the sake of pre-Registry-3.0 history objects
>   @DoNotCompare @Nullable ContactBase contactBase;
> ```

Why are we avoiding comparison on these?
___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 108 at r2](https://reviewable.io/reviews/google/nomulus/1529#-MwaZ0PNCPrQGxuO_SQW:-MwaZ0PNCPrQGxuO_SQX:bvjeajk) ([raw file](https://github.com/google/nomulus/blob/cc9783ab4fe6201e193c550d512d18a9979664c5/core/src/main/java/google/registry/model/domain/DomainHistory.java#L108)):*
> ```Java
>   // we change to use a composite primary key.
>   // TODO(b/166776754): Investigate if we can reuse domainContent.nsHosts for storing host keys.
>   @DoNotCompare
> ```

We definitely don't want to forego comparison for nsHosts.  If it's an issue in the context of DomainHistory, shouldn't excluding DomainContent above be adequate?  I'm not even clear on why we're excluding it from DomainHistory, TBH.


<!-- Sent from Reviewable.io -->

2022-02-23 14:45 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 67 at r2](https://reviewable.io/reviews/google/nomulus/1529#-MwaYhwa21_b9NxMKXA7:-Mwb1IrsA-6awrUoEXc5:brb9ndl) ([raw file](https://github.com/google/nomulus/blob/cc9783ab4fe6201e193c550d512d18a9979664c5/core/src/main/java/google/registry/model/contact/ContactHistory.java#L67)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Why are we avoiding comparison on these?
</blockquote></details>

Because Datastore doesn't have these fields at all, so when a ContactHistory reconstituted from the parent HistoryEntry object, this field is null 
___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 108 at r2](https://reviewable.io/reviews/google/nomulus/1529#-MwaZ0PNCPrQGxuO_SQW:-Mwb1gd098ZrhvKo1UYu:b-ygee9t) ([raw file](https://github.com/google/nomulus/blob/cc9783ab4fe6201e193c550d512d18a9979664c5/core/src/main/java/google/registry/model/domain/DomainHistory.java#L108)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

We definitely don't want to forego comparison for nsHosts.  If it's an issue in the context of DomainHistory, shouldn't excluding DomainContent above be adequate?  I'm not even clear on why we're excluding it from DomainHistory, TBH.
</blockquote></details>

Same reason why the domain content can be null -- Datastore doesn't know about it. 


<!-- Sent from Reviewable.io -->

2022-02-23 15:52 UTC, mindhog requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 108 at r2](https://reviewable.io/reviews/google/nomulus/1529#-MwaZ0PNCPrQGxuO_SQW:-MwbFsuo9T2eaONB8YQ3:by1heh5) ([raw file](https://github.com/google/nomulus/blob/cc9783ab4fe6201e193c550d512d18a9979664c5/core/src/main/java/google/registry/model/domain/DomainHistory.java#L108)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Same reason why the domain content can be null -- Datastore doesn't know about it. 
</blockquote></details>

No, actually it's a datastore field, too.  In any case, it's certainly reconstituted for DomainBase objects for both databases.  Is this not the case for history objects?

I'm going to try this PR without the DNC's to try to get a better understanding of what's going on here.


<!-- Sent from Reviewable.io -->

2022-02-23 15:54 UTC, mindhog requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 108 at r2](https://reviewable.io/reviews/google/nomulus/1529#-MwaZ0PNCPrQGxuO_SQW:-MwbHMHnCUomBX9Z7eBP:bihhxo) ([raw file](https://github.com/google/nomulus/blob/cc9783ab4fe6201e193c550d512d18a9979664c5/core/src/main/java/google/registry/model/domain/DomainHistory.java#L108)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

No, actually it's a datastore field, too.  In any case, it's certainly reconstituted for DomainBase objects for both databases.  Is this not the case for history objects?

I'm going to try this PR without the DNC's to try to get a better understanding of what's going on here.
</blockquote></details>

Ohhh... wait.  I see my confusion.  This is the override in DomainHistory, not DomainContent.  Apologies.


<!-- Sent from Reviewable.io -->

2022-02-23 16:04 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 108 at r2](https://reviewable.io/reviews/google/nomulus/1529#-MwaZ0PNCPrQGxuO_SQW:-MwbJt6vBale5S1RVr9D:bzao5al) ([raw file](https://github.com/google/nomulus/blob/cc9783ab4fe6201e193c550d512d18a9979664c5/core/src/main/java/google/registry/model/domain/DomainHistory.java#L108)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Ohhh... wait.  I see my confusion.  This is the override in DomainHistory, not DomainContent.  Apologies.
</blockquote></details>

Right, this is all in the history objects which are meaningfully different across the two databases. 


<!-- Sent from Reviewable.io -->

2022-02-23 16:06 UTC, mindhog approved these changes
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1529)* status: all files reviewed, 2 unresolved discussions (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-02-23 16:07 UTC, merged