Fix a subtle issue in BRDA copy caused by Cloud Tasks
google/nomulus pull request #1556
Opened 2022-03-15 03:39 UTC by jianglai

After the Cloud Tasks migration and #1508, the BRDA copy job now
routinely fail on the first try because the revision update is not
commited by the time the Cloud Tasks job enqueued in the same
transaction runs for  the first time. This is because the enqueueing is
a side effect and not part of the transaction. The job eventually
succeeds because of retries.

This PR attempts to mitigate the initial failure by saving the revisions
in a separate transaction before the enqueueing happens, insuring that
it is updated by the time the job runs.

2022-03-16 02:14 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rachelguan and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdeIO.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1556#-MyDVOSi9DGayVoZzoB5:-MyFS5A9AYOZv4c6eIaA:b-n4s609) ([raw file](https://github.com/google/nomulus/blob/e0972580ee4426b67920843680de84e991940874/core/src/main/java/google/registry/beam/rde/RdeIO.java#L313)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

I agree and it seems like the amount of delay doesn't have to be as long as the task in go/r3pr/1554, based on the logs of tasks that trigger `RdeUploadAction`
</blockquote></details>

The cursor only records the time that a certain should run next. It does not concern itself with revisions as far as I can tell. In fact, with BRDA, the copy action is not guarded by a lock. So if the revision advanced and the copy job enqueued, but the cursor advancement failed, the entire process will run again. Should there be a new revision for the new run? With this PR, there will be. If we add a delay instead, there won't be because the revision is rolled back. It seems more reasonable to have a new revision so to not override whatever is already copied to the escrow provider by the copy job. WDYT?

Also I have to say that the lack of transactionality is starting to bug me more and more. Maybe we should think of a way to guarantee it? I don't have anything on top of my head, but all the scrutinizing over edge cases is bad as we are always making some compromise, not to mention the mental toll :P


<!-- Sent from Reviewable.io -->

2022-03-16 12:48 UTC, mindhog reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rachelguan and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdeIO.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1556#-MyDVOSi9DGayVoZzoB5:-MyHkl7B9NFkLB6Cd6aA:bma9vmy) ([raw file](https://github.com/google/nomulus/blob/e0972580ee4426b67920843680de84e991940874/core/src/main/java/google/registry/beam/rde/RdeIO.java#L313)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The cursor only records the time that a certain should run next. It does not concern itself with revisions as far as I can tell. In fact, with BRDA, the copy action is not guarded by a lock. So if the revision advanced and the copy job enqueued, but the cursor advancement failed, the entire process will run again. Should there be a new revision for the new run? With this PR, there will be. If we add a delay instead, there won't be because the revision is rolled back. It seems more reasonable to have a new revision so to not override whatever is already copied to the escrow provider by the copy job. WDYT?

Also I have to say that the lack of transactionality is starting to bug me more and more. Maybe we should think of a way to guarantee it? I don't have anything on top of my head, but all the scrutinizing over edge cases is bad as we are always making some compromise, not to mention the mental toll :P
</blockquote></details>

Not to belabor the point, but you are making a case for rolling our own task-queues ;-)


<!-- Sent from Reviewable.io -->

2022-03-16 14:43 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rachelguan and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdeIO.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1556#-MyDVOSi9DGayVoZzoB5:-MyIAF2WC_yxM_vm2aO8:b-xuakh5) ([raw file](https://github.com/google/nomulus/blob/e0972580ee4426b67920843680de84e991940874/core/src/main/java/google/registry/beam/rde/RdeIO.java#L313)):*
> belabor
Yes, I am leaning more and more toward that given the subtleties that we are discovering more and more.

But I also recognize that this is not a small undertaking and probably require a design doc, and that we'd probably be reinventing the wheel somewhere. I wonder if we should raise this question with Cloud Tasks. I'd bet we are not the first ones to want the transactionality back.


<!-- Sent from Reviewable.io -->

2022-03-16 15:37 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jianglai, @mindhog, and @rachelguan)

___
*[core/src/main/java/google/registry/beam/rde/RdeIO.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1556#-MyDVOSi9DGayVoZzoB5:-MyILOkg9mVgfXMtZ2Ws:b-8dt336) ([raw file](https://github.com/google/nomulus/blob/e0972580ee4426b67920843680de84e991940874/core/src/main/java/google/registry/beam/rde/RdeIO.java#L313)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> belabor
Yes, I am leaning more and more toward that given the subtleties that we are discovering more and more.

But I also recognize that this is not a small undertaking and probably require a design doc, and that we'd probably be reinventing the wheel somewhere. I wonder if we should raise this question with Cloud Tasks. I'd bet we are not the first ones to want the transactionality back.
</blockquote></details>

Isn't this code called in the RDE pipeline that generates the data escrow files?
The cursors would be the per-tld RDE_STAGING cursors and the revision number
would be used in the generated file names.

With the new code, if revision is updated and cursor is not, we will rerun RDE staging and 
the revision would have a gap. In one scenario, the very first copy we send to IronMountain
and Icann would be R1 instead of R0.


<!-- Sent from Reviewable.io -->

2022-03-16 15:57 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rachelguan and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdeIO.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1556#-MyDVOSi9DGayVoZzoB5:-MyINjdrCkGCLXc3ibvJ:b-exrdxa) ([raw file](https://github.com/google/nomulus/blob/e0972580ee4426b67920843680de84e991940874/core/src/main/java/google/registry/beam/rde/RdeIO.java#L313)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Isn't this code called in the RDE pipeline that generates the data escrow files?
The cursors would be the per-tld RDE_STAGING cursors and the revision number
would be used in the generated file names.

With the new code, if revision is updated and cursor is not, we will rerun RDE staging and 
the revision would have a gap. In one scenario, the very first copy we send to IronMountain
and Icann would be R1 instead of R0.
</blockquote></details>

That's true for RDE, but for BRDA it's the opposite, because BRDA copy is not guarded by a cursor. So if the BRDA revision is updated and the copy job is enqueued, R0 will be sent. If they cursor updates fails, the job reruns and R1 will be generated and sent.

If we add a delay instead and keep everything in one transaction, nothing will be updated but the copy job will still be enqueued. If the revision is unset, we then have a copy job that keep retrying. If a revision is already set, then the copy job would be copying the old (un-updated revision), which probably is not the right thing to do.

So it looks like if we want to be exact, we need to put the BRDA copy action behind a cursor and do the delayed enqueueing in one transaction.


<!-- Sent from Reviewable.io -->

2022-03-16 16:32 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jianglai, @mindhog, and @rachelguan)

___
*[core/src/main/java/google/registry/beam/rde/RdeIO.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1556#-MyDVOSi9DGayVoZzoB5:-MyIYlTL8GDzB--ZXiWp:b-jzifgv) ([raw file](https://github.com/google/nomulus/blob/e0972580ee4426b67920843680de84e991940874/core/src/main/java/google/registry/beam/rde/RdeIO.java#L313)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

That's true for RDE, but for BRDA it's the opposite, because BRDA copy is not guarded by a cursor. So if the BRDA revision is updated and the copy job is enqueued, R0 will be sent. If they cursor updates fails, the job reruns and R1 will be generated and sent.

If we add a delay instead and keep everything in one transaction, nothing will be updated but the copy job will still be enqueued. If the revision is unset, we then have a copy job that keep retrying. If a revision is already set, then the copy job would be copying the old (un-updated revision), which probably is not the right thing to do.

So it looks like if we want to be exact, we need to put the BRDA copy action behind a cursor and do the delayed enqueueing in one transaction.
</blockquote></details>

Yes. I think we can add a delay here (and in RdeStagingReducer) and update BrdaCopyAction in another PR.
As of now, it is just some annoying error messages and nothing truly bad, right. 


<!-- Sent from Reviewable.io -->

2022-03-17 15:02 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rachelguan and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdeIO.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1556#-MyDVOSi9DGayVoZzoB5:-MyJ86tADSuQ-fl75WsG:b-iy3rt2) ([raw file](https://github.com/google/nomulus/blob/e0972580ee4426b67920843680de84e991940874/core/src/main/java/google/registry/beam/rde/RdeIO.java#L313)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Yes. I think we can add a delay here (and in RdeStagingReducer) and update BrdaCopyAction in another PR.
As of now, it is just some annoying error messages and nothing truly bad, right. 
</blockquote></details>

Yes, for now it's just annoyance. I added the delay and also the check for cursor in `BrdaCopyAction`. I don't think a lock is necessary as the copy to GCS is atomic. PTAL.


<!-- Sent from Reviewable.io -->

2022-03-17 16:01 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jianglai, @mindhog, and @rachelguan)

___
*[core/src/main/java/google/registry/beam/rde/RdeIO.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1556#-MyDVOSi9DGayVoZzoB5:-MyNb0gz0AkSEcXcmiyy:b-hcujpj) ([raw file](https://github.com/google/nomulus/blob/e0972580ee4426b67920843680de84e991940874/core/src/main/java/google/registry/beam/rde/RdeIO.java#L313)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Yes, for now it's just annoyance. I added the delay and also the check for cursor in `BrdaCopyAction`. I don't think a lock is necessary as the copy to GCS is atomic. PTAL.
</blockquote></details>

Have you pushed a new revision? I only see r1 here.


<!-- Sent from Reviewable.io -->

2022-03-17 17:58 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rachelguan and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdeIO.java, line 313 at r1](https://reviewable.io/reviews/google/nomulus/1556#-MyDVOSi9DGayVoZzoB5:-MyO0tFX4r69CGpr6g8c:b-32ck94) ([raw file](https://github.com/google/nomulus/blob/e0972580ee4426b67920843680de84e991940874/core/src/main/java/google/registry/beam/rde/RdeIO.java#L313)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Have you pushed a new revision? I only see r1 here.
</blockquote></details>

I think GitHub is somehow broked by the outage this morning. If you go to my branch you can see it's updated: https://github.com/jianglai/nomulus/tree/brda-copy.


<!-- Sent from Reviewable.io -->

2022-03-17 20:32 UTC, merged