Set the initial worker count for the RDE beam pipeline at 24
google/nomulus pull request #1572
Opened 2022-03-25 20:50 UTC by jianglai

This likely will speed up the pipeline by skipping the initially slow
process of spinning up instances.

2022-03-26 04:20 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1572)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jianglai and @weiminyu)

___
*[core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json, line 62 at r1](https://reviewable.io/reviews/google/nomulus/1572#-Mz3REG7-uI15RDlkAp0:-Mz3REG7-uI15RDlkAp1:b-5si6bd) ([raw file](https://github.com/google/nomulus/blob/3c8f9ca4a7574ddd6b21c07d2a9879bca1852031/core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json#L62)):*
> ```JSON
>     },
>     {
>       "name": "numWorkers",
> ```

We shouldn't have to add this parameter to the metadata file. This is a builtin parameter in Dataflow.

Did you run into problem without it?



_Code quote:_
```JSON
numWorkers
```


<!-- Sent from Reviewable.io -->

2022-03-26 12:27 UTC, jianglai commented
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1572)_ status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jianglai and @weiminyu)
> 
> _[core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json, line 62 at r1](https://reviewable.io/reviews/google/nomulus/1572#-Mz3REG7-uI15RDlkAp0:-Mz3REG7-uI15RDlkAp1:b-5si6bd) ([raw file](https://github.com/google/nomulus/blob/3c8f9ca4a7574ddd6b21c07d2a9879bca1852031/core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json#L62)):_
> 
> > ```json
> >     },
> >     {
> >       "name": "numWorkers",
> > ```
> 
> We shouldn't have to add this parameter to the metadata file. This is a builtin parameter in Dataflow.
> 
> Did you run into problem without it?
> 
> _Code quote:_
> 
> ```json
> numWorkers
> ```

The similar `workerMachineType` (above this one) also is included in the metadata file. I suspect any parameter to the pipeline needs to be explicitly specified here, builtin or not.

2022-03-26 13:35 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1572)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jianglai and @weiminyu)

___
*[core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json, line 62 at r1](https://reviewable.io/reviews/google/nomulus/1572#-Mz3REG7-uI15RDlkAp0:-Mz5Q_6wETMJFqT6Z2FA:b-qxp5db) ([raw file](https://github.com/google/nomulus/blob/3c8f9ca4a7574ddd6b21c07d2a9879bca1852031/core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json#L62)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The similar `workerMachineType` (above this one) also is included in the metadata file. I suspect any parameter to the pipeline needs to be explicitly specified here, builtin or not.
</blockquote></details>

I think that one can be removed too. 

The db-comparison pipeline's meta doesn't have these parameters: https://github.com/google/nomulus/blob/master/core/src/main/resources/google/registry/beam/validate_database_pipeline_metadata.json

But we can specify them on the command line: https://github.com/google/nomulus/blob/342f7d72a2432cd7ab2f546b40c3ffa8261208fb/core/src/main/java/google/registry/tools/ValidateDatabaseMigrationCommand.java#L186


<!-- Sent from Reviewable.io -->

2022-03-27 13:33 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1572)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json, line 62 at r1](https://reviewable.io/reviews/google/nomulus/1572#-Mz3REG7-uI15RDlkAp0:-MzA_GYsE7JiDatXb-ap:b-pzklqd) ([raw file](https://github.com/google/nomulus/blob/3c8f9ca4a7574ddd6b21c07d2a9879bca1852031/core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json#L62)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

I think that one can be removed too. 

The db-comparison pipeline's meta doesn't have these parameters: https://github.com/google/nomulus/blob/master/core/src/main/resources/google/registry/beam/validate_database_pipeline_metadata.json

But we can specify them on the command line: https://github.com/google/nomulus/blob/342f7d72a2432cd7ab2f546b40c3ffa8261208fb/core/src/main/java/google/registry/tools/ValidateDatabaseMigrationCommand.java#L186

</blockquote></details>

Tested in Alpha. You are correct. Removed builtin params.


<!-- Sent from Reviewable.io -->

2022-03-28 01:52 UTC, weiminyu approved these changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1572)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2022-03-28 02:51 UTC, merged