Change use of BillingIdentifier to BillingAccountMap in invoicing pipeline
google/nomulus pull request #1577
Opened 2022-03-30 21:39 UTC by sarahcaseybot

2022-03-31 17:54 UTC, jianglai requested changes
`BillingIdentifier` is not used anymore. We can just delete the field and remove it from the schema.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1577#-:-MzW6CYs0FYJ2I98HhVz:b-jvebk8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2022-03-31 17:56 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1577)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 130 at r1](https://reviewable.io/reviews/google/nomulus/1577#-MzW6YVdBD7EdTD2_Bnw:-MzW6YVdBD7EdTD2_Bnx:b-ftubeb) ([raw file](https://github.com/google/nomulus/blob/f3e849d78848334f181ae5fc876f8216924c7b61/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L130)):*
> ```Java
>         DateTimeUtils.toZonedDateTime(oneTime.getEventTime(), ZoneId.of("UTC")),
>         registrar.getRegistrarId(),
>         registrar.getBillingAccountMap().get(oneTime.getCost().getCurrencyUnit()),
> ```

What happens when the billing account map itself exists (therefore is included in the query output) but the entry for the required current unit does not? We need to handle that case gracefully.



_Code quote:_
```Java
registrar.getBillingAccountMap().get(oneTime.getCost().getCurrencyUnit()),
```


<!-- Sent from Reviewable.io -->

2022-03-31 19:23 UTC, gbrodman reviewed
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1577)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 130 at r1](https://reviewable.io/reviews/google/nomulus/1577#-MzW6YVdBD7EdTD2_Bnw:-MzWQ1CJ8-_z6pMP8sBn:b-okrxig) ([raw file](https://github.com/google/nomulus/blob/f3e849d78848334f181ae5fc876f8216924c7b61/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L130)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Added a default empty string
</blockquote></details>

This really shouldn't happen, right? I **believe** that the BigQuery code in `billing_events.sql` assumes that if there's a billing event for a registrar, that that billing event's currency must exist in the registrar's billing account map. 


<!-- Sent from Reviewable.io -->

2022-04-01 16:18 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1577)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 130 at r1](https://reviewable.io/reviews/google/nomulus/1577#-MzW6YVdBD7EdTD2_Bnw:-Mz_umpZ8NnFCl7j5VC7:b-yzvyhf) ([raw file](https://github.com/google/nomulus/blob/f3e849d78848334f181ae5fc876f8216924c7b61/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L130)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

That's the assumption. But does it always hold? I don't think there's anything to prevent a registrar to create a domain if the corresponding PAK is not set.

In any case, this should be an error, instead of being silently ignored. If we send a CSV to the billing team with an empty PAK, they will ask us to fix it anyway. It's better that we found out the problem ourselves.
</blockquote></details>

This would be separate from this PR, but should we be checking that the provided registrar has a billing account entry for the relevant currency when creating a domain? It seems like we probably should? 


<!-- Sent from Reviewable.io -->

2022-04-01 20:22 UTC, jianglai approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1577)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 130 at r1](https://reviewable.io/reviews/google/nomulus/1577#-MzW6YVdBD7EdTD2_Bnw:-MzamrGq87mh5dCcCIM2:b-r8bcbc) ([raw file](https://github.com/google/nomulus/blob/f3e849d78848334f181ae5fc876f8216924c7b61/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L130)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Changed this to throw an error for a missing PAK
</blockquote></details>

Needs a corresponding test.


<!-- Sent from Reviewable.io -->

2022-04-01 20:27 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1577)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 128 at r3](https://reviewable.io/reviews/google/nomulus/1577#-MzanVq12TNje4Noabkw:-MzanVq12TNje4Noabkx:b-x0mmzx) ([raw file](https://github.com/google/nomulus/blob/adbbbe7344c0f0efc47fd190ba0bac28bb025bff/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L128)):*
> ```Java
>     CurrencyUnit currency = oneTime.getCost().getCurrencyUnit();
>     if (!registrar.getBillingAccountMap().containsKey(currency)) {
>       throw new RuntimeException(
> ```

`RunTimeException` is quite vague.

This entire section can be rewritten as:

```
checkState(
    registrar.getBillingAccountMap().containsKey(currency),
    "Registrar %s does not have a product account key for the currency unit: %s",
    registrar.getRegistrarId(), currency));
```

`IllegalStateException` seems like a more suitable exception to use, and you also eliminate the `if` and `String.format` this way.


<!-- Sent from Reviewable.io -->

2022-04-04 18:15 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1577#-:-MzpmYUW1EDtpEzZCWZX:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2022-04-04 20:16 UTC, merged