Ignore read-only when saving commit logs
google/nomulus pull request #1584
Opened 2022-04-05 19:56 UTC by mindhog

Ignore read-only when saving commit logs and commit log mutations so that we
can safely replicate in read-only mode.  This should be safe, as we only ever
to the situation of saving commit logs and mutations when something has
already actually been modified in a transaction, meaning that we should have hit
the "read only" sentinel already.

This also introduces the ability to set the Clock in the
TransactionManagerFactory so that we can test this functionality.

2022-04-05 19:58 UTC, weiminyu approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys and @gbrodman)



<!-- Sent from Reviewable.io -->

2022-04-05 20:07 UTC, CydeWeys requested changes
> Ignore read-only when saving commit logs

Where is the actual change that implements this?  I'm expecting to see a change to `ReplicateToDatastoreAction` in this PR, but I'm not seeing that change included in this PR?  Did you forget it?  (Also this new test isn't passing without that change is it?!)

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1584#-:-MzvKb1QDvHjGKY_5cqC:b24ko50)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java, line 224 at r2](https://reviewable.io/reviews/google/nomulus/1584#-MzvK29W8D49P0ceKPlq:-MzvK29W8D49P0ceKPlr:b-64ctk8) ([raw file](https://github.com/google/nomulus/blob/4f4408b82ff8275cf592556a49c44ce0cb3d6ac2/core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java#L224)):*
> ```Java
>   /** Allows us to set the clock used by the factory in unit tests. */
>   @VisibleForTesting
>   public static void setClock(Clock clock) {
> ```

Should be named `setClockForTesting()` 


<!-- Sent from Reviewable.io -->

2022-04-05 20:08 UTC, CydeWeys reviewed
Oh wait never mind, it's the change to `CommitLoggedWork` isn't it.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1584#-:-MzvKnJ2EXMsKxF4weLB:bsgg79w)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @mindhog, and @weiminyu)



<!-- Sent from Reviewable.io -->

2022-04-05 20:13 UTC, mindhog reviewed
Yeah, the fix happens in `CommitLoggedWork` and `CommitLogMutation`.  The action code turned out to be just fine.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1584#-:-MzvLpVX5zad4DbRiVFS:bhtdcth)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @mindhog, and @weiminyu)



<!-- Sent from Reviewable.io -->

2022-04-05 20:25 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1584)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java, line 224 at r2](https://reviewable.io/reviews/google/nomulus/1584#-MzvK29W8D49P0ceKPlq:-MzvOnUf240xchzJJb6k:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4f4408b82ff8275cf592556a49c44ce0cb3d6ac2/core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java#L224)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should be named `setClockForTesting()` 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-05 21:03 UTC, gbrodman approved these changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/model/replay/ReplicateToDatastoreActionTest.java, line 397 at r3](https://reviewable.io/reviews/google/nomulus/1584#-MzvXSysA5qm8Gs92eaF:-MzvXSyt47GwcNy5tNnM:b-i7onab) ([raw file](https://github.com/google/nomulus/blob/960e99c9572cdc59ad1ba3b5bf9cbd35fe410bc8/core/src/test/java/google/registry/model/replay/ReplicateToDatastoreActionTest.java#L397)):*
> ```Java
>   @Test
>   void replicationWorksInReadOnly() {
> ```

I don't really care if this gets fixed since it's the nittiest nit, but there's an extra newline here 


<!-- Sent from Reviewable.io -->

2022-04-06 12:04 UTC, mindhog reviewed
Not sure what's going on with the tests on these, they're passing locally.  Investigating.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1584#-:-MzyklLP7D6zRWEYf2HX:b-uxbg01)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2022-04-06 17:05 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1584#-:-MzzpYyp5KhMBGnuccDt:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2022-04-06 17:06 UTC, merged