Replace .get()).isEqualTo() with hasValue()
google/nomulus pull request #1589
Opened 2022-04-11 23:28 UTC by rachelguan

When verifying the value in `Optional<?>` variables, the most intuitive way seems to be using `get()` to get the value then comparing the value by calling `isEqualTo()`. However, this way is not preferred way since manually calling `get()`returns a worse error message and might potentially throw `NullPointerException`. We can use `hasValue()` from `Truth8.assertThat` for value comparison.

2022-04-13 21:45 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1589)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @rachelguan)

___
*[core/src/test/java/google/registry/ui/forms/FormFieldTest.java, line 326 at r1](https://reviewable.io/reviews/google/nomulus/1589#-N-ZsCFjD92kobMz-Zl-:-N-ZsCFjD92kobMz-Zl0:bw66wa5) ([raw file](https://github.com/google/nomulus/blob/6e0ccd7385869cebf8db0626e2a04537925c04fb/core/src/test/java/google/registry/ui/forms/FormFieldTest.java#L326)):*
> ```Java
>   void testAsList() {
>     assertThat(FormField.named("lol").asList().build().convert(ImmutableList.of("lol", "cat", "")))
>         .hasValue(ImmutableList.of("lol", "cat", ""));
> ```

I suspect that`.hasValue(list)` results in a worse error message when the test fails than `.containsExactly(...)`

Can you run it both ways with failing values and paste the failures here so we can determine which is more readable?  If, as I suspect, `containsExactly()` is better, then we'll probably want these to all be something like:

```
list = whateverListCanBeAbsent
assertThat(list).isPresent();
assertThat(list.get()).containsExactly(...);
```


<!-- Sent from Reviewable.io -->

2022-04-14 19:13 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1589)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/ui/forms/FormFieldTest.java, line 326 at r1](https://reviewable.io/reviews/google/nomulus/1589#-N-ZsCFjD92kobMz-Zl-:-N-dS_LXCEpRnEZipPEh:b8on9ai) ([raw file](https://github.com/google/nomulus/blob/6e0ccd7385869cebf8db0626e2a04537925c04fb/core/src/test/java/google/registry/ui/forms/FormFieldTest.java#L326)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I suspect that`.hasValue(list)` results in a worse error message when the test fails than `.containsExactly(...)`

Can you run it both ways with failing values and paste the failures here so we can determine which is more readable?  If, as I suspect, `containsExactly()` is better, then we'll probably want these to all be something like:

```
list = whateverListCanBeAbsent
assertThat(list).isPresent();
assertThat(list.get()).containsExactly(...);
```
</blockquote></details>

IT does seem like `containsExactly` has a better error message when handling failure since it shows what actually is missing (cant show if its there but in the wrong order tho)

```
  @Test
  void testAsList_hasValue_nonEmpty() {
    assertThat(FormField.named("lol").asList().build().convert(ImmutableList.of("lol", "dog", "")))
        .hasValue(ImmutableList.of("lol", "cat", ""));
  }

output

value of: optional.get()
expected: [lol, cat, ]
but was : [lol, dog, ]
value of: optional.get()
expected: [lol, cat, ]
but was : [lol, dog, ]
	at google.registry.ui.forms.FormFieldTest.testAsList_hasValue_nonEmpty(FormFieldTest.java:332)
```

```
  @Test
  void testAsList_containsExactly_nonEmpty() {
    assertThat(
        FormField.named("lol")
            .asList()
            .build()
            .convert(ImmutableList.of("lol", "cat", ""))
            .get())
        .containsExactly("lol", "dog", "")
        .inOrder();
  }

output:
missing (1)   : dog
unexpected (1): cat
---
expected      : [lol, dog, ]
but was       : [lol, cat, ]
missing (1)   : dog
unexpected (1): cat
---
expected      : [lol, dog, ]
but was       : [lol, cat, ]
```


<!-- Sent from Reviewable.io -->

2022-04-15 19:39 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1589)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @rachelguan)

___
*[core/src/test/java/google/registry/ui/forms/FormFieldTest.java, line 443 at r2](https://reviewable.io/reviews/google/nomulus/1589#-N-ijE254kknFk-YlHro:-N-ijE254kknFk-YlHrp:bxk7es2) ([raw file](https://github.com/google/nomulus/blob/8594a61fd4708a7f8cfd47ac532e7a22b2603cea/core/src/test/java/google/registry/ui/forms/FormFieldTest.java#L443)):*
> ```Java
>         .containsExactly("lol", "cat");
>   }
> ```

This newline needs to be put back.


<!-- Sent from Reviewable.io -->

2022-04-18 18:48 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1589)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/ui/forms/FormFieldTest.java, line 443 at r2](https://reviewable.io/reviews/google/nomulus/1589#-N-ijE254kknFk-YlHro:-N-xsJ7sCizUc_F8SGxQ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8594a61fd4708a7f8cfd47ac532e7a22b2603cea/core/src/test/java/google/registry/ui/forms/FormFieldTest.java#L443)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This newline needs to be put back.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-18 20:54 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1589)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @rachelguan)

___
*[core/src/test/java/google/registry/ui/forms/FormFieldTest.java, line 444 at r3](https://reviewable.io/reviews/google/nomulus/1589#-N-yRyPPCIERlW1qFNo7:-N-yRyPPCIERlW1qFNo8:bbaqk70) ([raw file](https://github.com/google/nomulus/blob/088f9356788912eedb720995c7bbf2f764d8c4e2/core/src/test/java/google/registry/ui/forms/FormFieldTest.java#L444)):*
> ```Java
>         .containsExactly("lol", "cat");
>   }
>   
> ```

Any idea why this is rendering as two dots?  Are there accidental trailing spaces here or something?



_Code quote:_
```Java
··
```


<!-- Sent from Reviewable.io -->

2022-04-18 21:08 UTC, rachelguan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1589)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/ui/forms/FormFieldTest.java, line 444 at r3](https://reviewable.io/reviews/google/nomulus/1589#-N-yRyPPCIERlW1qFNo7:-N-yV78dCt4i9aiBL196:bk2kvep) ([raw file](https://github.com/google/nomulus/blob/088f9356788912eedb720995c7bbf2f764d8c4e2/core/src/test/java/google/registry/ui/forms/FormFieldTest.java#L444)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Any idea why this is rendering as two dots?  Are there accidental trailing spaces here or something?
</blockquote></details>

Had no idea why a regular space didn't do the job. I had to copy `@Test` from an existing line and the empty line above to fix it. Thanks for catching it.


<!-- Sent from Reviewable.io -->

2022-04-18 22:18 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1589)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2022-04-18 22:35 UTC, merged