Don't fail invoicing on missing PAK
google/nomulus pull request #1595
Opened 2022-04-18 22:42 UTC by sarahcaseybot

2022-04-19 17:06 UTC, gbrodman requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1595)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 133 at r1](https://reviewable.io/reviews/google/nomulus/1595#-N01mSK6-IaDV0pOrjjd:-N01mSK721Y0aep3ECFw:bl8zal0) ([raw file](https://github.com/google/nomulus/blob/e4f61c29726731cc7925f5a39e1bb9783a5e37a2/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L133)):*
> ```Java
>         DateTimeUtils.toZonedDateTime(oneTime.getEventTime(), ZoneId.of("UTC")),
>         registrar.getRegistrarId(),
>         registrar.getBillingAccountMap().getOrDefault(currency, ""),
> ```

Do we know for sure that a blank PAK in the output CSV is fine and will be ignored? Just curious what the handling of that would end up looking like 


<!-- Sent from Reviewable.io -->

2022-04-19 19:03 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1595)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 129 at r1](https://reviewable.io/reviews/google/nomulus/1595#-N02CA6JBC7RmeLYf_Z_:-N02CA6JBC7RmeLYf_Za:bh804jh) ([raw file](https://github.com/google/nomulus/blob/073d0a416a1fc77501267c9554a0ea452180d009/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L129)):*
> ```Java
>     CurrencyUnit currency = oneTime.getCost().getCurrencyUnit();
>     checkState(
>         registrar.getBillingAccountMap().containsKey(currency),
> ```

Don't remove this entirely, just turn it into logging at `SEVERE`.
___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 133 at r1](https://reviewable.io/reviews/google/nomulus/1595#-N01mSK6-IaDV0pOrjjd:-N02CDM81llZtQw5huxO:b-ep697x) ([raw file](https://github.com/google/nomulus/blob/e4f61c29726731cc7925f5a39e1bb9783a5e37a2/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L133)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Do we know for sure that a blank PAK in the output CSV is fine and will be ignored? Just curious what the handling of that would end up looking like 
</blockquote></details>

Agreed, I was expecting these to be skipped entirely (i.e. not submitted to billing3).  I don't know that it makes sense to submit them to billing3 but with blank billing IDs -- what will they do with them then?  They won't know who to bill or how to process it.


<!-- Sent from Reviewable.io -->

2022-04-19 19:04 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1595)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @sarahcaseybot)

___
*[core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java, line 303 at r1](https://reviewable.io/reviews/google/nomulus/1595#-N02CRc_5ILr6HnalxOf:-N02CRc_5ILr6HnalxOg:b-hz0wme) ([raw file](https://github.com/google/nomulus/blob/073d0a416a1fc77501267c9554a0ea452180d009/core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java#L303)):*
> ```Java
> 
>   @Test
>   void testFailure_readFromCloudSqlMissingPAK() throws Exception {
> ```

Rather than this test being removed entirely, it should be testing the correct behavior when a PAK is missing.


<!-- Sent from Reviewable.io -->

2022-04-19 22:28 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1595)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 133 at r1](https://reviewable.io/reviews/google/nomulus/1595#-N01mSK6-IaDV0pOrjjd:-N02vj3q2CHVUiQjSy_3:b-we1yjq) ([raw file](https://github.com/google/nomulus/blob/e4f61c29726731cc7925f5a39e1bb9783a5e37a2/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L133)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Changed to return null here, and then filter out the null later in the pipeline.
</blockquote></details>

`parseRow()` either needs to be annotated with `@Nullable`, or it needs to return `Optional<BillingEvent>`.  I think the latter is better and more clearly communicates what's going on even from the callsite.
___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 129 at r2](https://reviewable.io/reviews/google/nomulus/1595#-N02vbmn3epKIk1r7bmP:-N02vbmn3epKIk1r7bmQ:boptjty) ([raw file](https://github.com/google/nomulus/blob/8ff8a089a28f55a6552e3f1a8e9d2e0bebb9b954/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L129)):*
> ```Java
>     return billingEventsWithNulls.apply(
>         Filter.by(
>             new SerializableFunction<BillingEvent, Boolean>() {
> ```

Can you do this in a more terse way by using a lambda?  E.g. something like this?  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java;l=163?q=filter%5C.by&ss=nomulus

As written it feels quite pre-Java-8.
___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 144 at r2](https://reviewable.io/reviews/google/nomulus/1595#-N02qmIIENJ2M1FVpy0H:-N02qmIIENJ2M1FVpy0I:b-x0a4ib) ([raw file](https://github.com/google/nomulus/blob/8ff8a089a28f55a6552e3f1a8e9d2e0bebb9b954/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L144)):*
> ```Java
>     if (!registrar.getBillingAccountMap().containsKey(currency)) {
>       logger.atSevere().log(
>           String.format(
> ```

You don't need `String.format()` with `logger`.  It's less performant as it incurs the cost of string mangling even if the given logging level is disabled.
___
*[core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java, line 322 at r2](https://reviewable.io/reviews/google/nomulus/1595#-N02wBbs1tE5oPVjX-46:-N02wBbs1tE5oPVjX-47:bvivlbq) ([raw file](https://github.com/google/nomulus/blob/8ff8a089a28f55a6552e3f1a8e9d2e0bebb9b954/core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java#L322)):*
> ```Java
>     PCollection<BillingEvent> billingEvents = InvoicingPipeline.readFromCloudSql(options, pipeline);
>     billingEvents = billingEvents.apply(new ChangeDomainRepo());
>     PAssert.that(billingEvents).containsInAnyOrder(INPUT_EVENTS);
> ```

Just to make it really explicit, can you add an assert here that it does NOT contain the CAD billing event that you added?
___
*[core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java, line 329 at r2](https://reviewable.io/reviews/google/nomulus/1595#-N02vyT-5h56jpwYhA6I:-N02vyT-5h56jpwYhA6J:b40efgy) ([raw file](https://github.com/google/nomulus/blob/8424c85258cbfcce11df90385e60497594999c7c/core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java#L329)):*
> ```Java
>         .hasMessageThat()
>         .contains(
>             "Registrar TheRegistrar does not have a product account key for the currency unit:"
> ```

You should still assert for the presence of this in the logs.


<!-- Sent from Reviewable.io -->

2022-04-21 19:10 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1595)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 127 at r3](https://reviewable.io/reviews/google/nomulus/1595#-N0CW14FAW_hWkx0xto0:-N0CW14FAW_hWkx0xto1:b-ie269i) ([raw file](https://github.com/google/nomulus/blob/f9cb52a6bc6a32f4e345fc0a9ac24307c57b226c/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L127)):*
> ```Java
> 
>     // Remove null billing events
>     return billingEventsWithNulls.apply(Filter.by(Objects::nonNull));
> ```

Is this correct?  You aren't filtering out `null`s anymore, you're filtering out absent `Optional`s.


<!-- Sent from Reviewable.io -->

2022-04-21 20:03 UTC, gbrodman reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 127 at r3](https://reviewable.io/reviews/google/nomulus/1595#-N0CW14FAW_hWkx0xto0:-N0CfeVv6hP9xqoKeN6H:b-mjayb9) ([raw file](https://github.com/google/nomulus/blob/f9cb52a6bc6a32f4e345fc0a9ac24307c57b226c/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L127)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Yes, but in line 121 it is replacing the absent optionals with a null. I verified that without this filter, the testSuccess_readFromCloudSqlMissingPAK() test fails.
</blockquote></details>

is it possible to have the read be a `Read<Object[], Optional<BillingEvent>>`? Then we could remove the `orElse` above and just have this be a filter on whether or not the optional is present. 


<!-- Sent from Reviewable.io -->

2022-04-21 20:24 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 127 at r3](https://reviewable.io/reviews/google/nomulus/1595#-N0CW14FAW_hWkx0xto0:-N0CmdtM8_NEJ2zVVpdB:bxfuli6) ([raw file](https://github.com/google/nomulus/blob/f9cb52a6bc6a32f4e345fc0a9ac24307c57b226c/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L127)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

is it possible to have the read be a `Read<Object[], Optional<BillingEvent>>`? Then we could remove the `orElse` above and just have this be a filter on whether or not the optional is present. 
</blockquote></details>

Yeah, just use Optionals throughout; it doesn't make sense to coerce them to null only to then filter them out.  You can filter out absent Optionals just as easily and skip a step.

Note that having `null` values in a collection is kind of an antipattern -- to the point that Guava explicitly disallows it (but `PCollection` apparently does not).


<!-- Sent from Reviewable.io -->

2022-04-22 15:27 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1595)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 127 at r3](https://reviewable.io/reviews/google/nomulus/1595#-N0CW14FAW_hWkx0xto0:-N0GsTP37iR6iOcavps1:bdy9x4r) ([raw file](https://github.com/google/nomulus/blob/f9cb52a6bc6a32f4e345fc0a9ac24307c57b226c/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L127)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Spent a while trying to make this optionals throughout, took quite a bit of refactoring, but I can't seem to avoid serialization failures. 

java.lang.ClassCastException: class java.util.Optional cannot be cast to class java.io.Serializable (java.util.Optional and java.io.Serializable are in module java.base of loader 'bootstrap')
</blockquote></details>

Ah well. I was worried something like that might happen.


<!-- Sent from Reviewable.io -->

2022-04-22 15:57 UTC, gbrodman approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1595)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java, line 127 at r3](https://reviewable.io/reviews/google/nomulus/1595#-N0CW14FAW_hWkx0xto0:-N0GzYKU5XPx_o-mMviJ:b30pcu2) ([raw file](https://github.com/google/nomulus/blob/f9cb52a6bc6a32f4e345fc0a9ac24307c57b226c/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L127)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ah well. I was worried something like that might happen.
</blockquote></details>

yeah, my question was an actual question since I didn't know if Optionals could be serialized. I guess not :/ 


<!-- Sent from Reviewable.io -->

2022-04-22 17:00 UTC, merged