Check PAK is present on domain create
google/nomulus pull request #1605
Opened 2022-04-26 00:36 UTC by sarahcaseybot

2022-04-26 15:26 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1605)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java` line 1512 at r1](https://reviewable.io/reviews/google/nomulus/1605#-N0aRhP0399uCM_fSSIk:-N0aRhP12XKiNZLmTUN6:b-dnuqgn) ([raw file](https://github.com/google/nomulus/blob/22bcf23408eab1b294b0544abda20fd38487aef7/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L1512)):*
> ```Java
>   public static class MissingBillingAccountMapException extends AuthorizationErrorException {
>     public MissingBillingAccountMapException(CurrencyUnit currency) {
>       super("Registrar does not have a billing account set up for the currency type " + currency);
> ```

Keeping in mind that this is an externally visible exception message that registrars will see in their EPP command responses, I think the following tweak might be better:

`"Registrar is not yet onboarded for TLDs that bill in " + currency`

(Billing account is an implementation detail for billing3 that isn't something registrars really know about.)
___
*[`core/src/test/java/google/registry/flows/EppLifecycleHostTest.java` line 115 at r1](https://reviewable.io/reviews/google/nomulus/1605#-N0aSUm0DMCE50ezGFVO:-N0aSUm0DMCE50ezGFVP:bmibiu3) ([raw file](https://github.com/google/nomulus/blob/22bcf23408eab1b294b0544abda20fd38487aef7/core/src/test/java/google/registry/flows/EppLifecycleHostTest.java#L115)):*
> ```Java
>         loadRegistrar("NewRegistrar")
>             .asBuilder()
>             .setBillingAccountMap(ImmutableMap.of(USD, "123"))
> ```

Is this necessary?  The default dummy data registrars are already persisted with a default billing account for USD: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/testing/AppEngineExtension.java;l=293?q=appengineexten&ss=nomulus%2Fnomulus
___
*[`core/src/test/java/google/registry/flows/EppLifecycleHostTest.java` line 170 at r1](https://reviewable.io/reviews/google/nomulus/1605#-N0aSaHk6wQG3TWx7T3m:-N0aSaHk6wQG3TWx7T3n:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/22bcf23408eab1b294b0544abda20fd38487aef7/core/src/test/java/google/registry/flows/EppLifecycleHostTest.java#L170)):*
> ```Java
>         loadRegistrar("NewRegistrar")
>             .asBuilder()
>             .setBillingAccountMap(ImmutableMap.of(USD, "123"))
> ```

Ditto.
___
*[`core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java` line 211 at r1](https://reviewable.io/reviews/google/nomulus/1605#-N0aScLj8RmD4ynosYCY:-N0aScLj8RmD4ynosYCZ:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/22bcf23408eab1b294b0544abda20fd38487aef7/core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java#L211)):*
> ```Java
>         loadRegistrar("TheRegistrar")
>             .asBuilder()
>             .setBillingAccountMap(ImmutableMap.of(USD, "123"))
> ```

Ditto.
___
*[`core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java` line 154 at r1](https://reviewable.io/reviews/google/nomulus/1605#-N0aSrNk12d4C-CjYpxL:-N0aSrNk12d4C-CjYpxM:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/22bcf23408eab1b294b0544abda20fd38487aef7/core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java#L154)):*
> ```Java
>         loadRegistrar("TheRegistrar")
>             .asBuilder()
>             .setBillingAccountMap(ImmutableMap.of(USD, "123"))
> ```

Ditto.


<!-- Sent from Reviewable.io -->

2022-04-26 21:48 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1605)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 183 at r2](https://reviewable.io/reviews/google/nomulus/1605#-N0bpm4U5y9VYpo1QOS7:-N0bpm4U5y9VYpo1QOS8:b-5wc4u2) ([raw file](https://github.com/google/nomulus/blob/82c4deda4641740b44734be6f631986c84302509/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L183)):*
> ```Java
>  * @error {@link DomainFlowUtils.MaxSigLifeNotSupportedException}
>  * @error {@link DomainFlowUtils.MissingAdminContactException}
>  * @error {@link DomainFlowUtils.MissingBillingAccountMapException}
> ```

This needs to be on every flow that throws the EPP exception, so you'll need to add a test case to every flow that can throw this in order to list it there.
___
*[`core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java` line 290 at r2](https://reviewable.io/reviews/google/nomulus/1605#-N0bp8ZN8LhQEhysnGhq:-N0bp8ZN8LhQEhysnGhr:bzbupbc) ([raw file](https://github.com/google/nomulus/blob/82c4deda4641740b44734be6f631986c84302509/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L290)):*
> ```Java
> 
>   /** Check if the registrar running the flow has access to the TLD in question. */
>   public static void checkAllowedAccessToTld(String registrarId, String tld) throws EppException {
> ```

This helper method is used by a large number of different flows (I count 11), some of which probably should not have the billing account map requirement.  E.g. we shouldn't prohibit deletes, nor approving/rejecting outgoing transfers, nor most domain updates (except ones that have a cost), and then probably also not domain checks (though I'm on the fence with this one, because generally you do want the check to return the same thing the create does).

We should probably loop in Bruno to figure out exactly which operations should/shouldn't be allowed based on the presence of the currency in the billing account map, keeping in mind that there are existing domains that won't meet this criteria.


<!-- Sent from Reviewable.io -->

2022-04-27 22:47 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1605)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java` line 290 at r2](https://reviewable.io/reviews/google/nomulus/1605#-N0bp8ZN8LhQEhysnGhq:-N0hBjdU36Mxp_8ngmvL:b6ni8mb) ([raw file](https://github.com/google/nomulus/blob/82c4deda4641740b44734be6f631986c84302509/core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java#L290)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This helper method is used by a large number of different flows (I count 11), some of which probably should not have the billing account map requirement.  E.g. we shouldn't prohibit deletes, nor approving/rejecting outgoing transfers, nor most domain updates (except ones that have a cost), and then probably also not domain checks (though I'm on the fence with this one, because generally you do want the check to return the same thing the create does).

We should probably loop in Bruno to figure out exactly which operations should/shouldn't be allowed based on the presence of the currency in the billing account map, keeping in mind that there are existing domains that won't meet this criteria.
</blockquote></details>

So I spoke with Bruno and the decision is that this error should be thrown only on flows that have billable implications, and then also the domain check flow, because the check flow behavior mirrors what the actual behavior of a create will be (e.g. currently if you don't have access to a TLD, the check will fail as well).

So the flows that should fail are: domain create, domain renew, domain check, domain claims check, domain transfer request, and domain restore request.  The other 5 should succeed.


<!-- Sent from Reviewable.io -->

2022-04-28 19:05 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1605#-:-N0lZB4s0V-4l8ZH1o-w:bnfp4nl)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java` line 609 at r3](https://reviewable.io/reviews/google/nomulus/1605#-N0lYqFU5FvcgD1phghY:-N0lYqFU5FvcgD1phghZ:b-904gbr) ([raw file](https://github.com/google/nomulus/blob/bc9cdd0d71600c522aefe276cccd3646c1c1ea3d/core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java#L609)):*
> ```Java
>     persistResource(
>         Registry.get("tld")
>             .asBuilder()
> ```

Rather than copy-pasting this large blob a lot, you could be doing something simpler: 

`persistResource(Registrar.loadByRegistrarId("TheRegistrar").asBuilder().setBillingAccountMap(...something without USD...).build());`


<!-- Sent from Reviewable.io -->

2022-04-28 19:06 UTC, CydeWeys reviewed
+reviewer:@ergelo 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1605#-:-N0lZCff8YtSSYh2tTZm:bsok3mp)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @ergelo and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2022-04-28 19:15 UTC, ergelo commented on core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
> +      super("Registrar is not yet onboarded for TLDs that bill in " + currency);
Can we make this 'Registrar is not **fully** onboarded..' ? I'd like to cover edge cases in which something changes following an originally successful onboarding

2022-04-29 18:30 UTC, merged