Remove all uses of the billingIdentifier field
google/nomulus pull request #1608
Opened 2022-04-27 20:14 UTC by sarahcaseybot

2022-04-28 17:54 UTC, gbrodman requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608)* status: all files reviewed, 3 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java` line 123 at r1](https://reviewable.io/reviews/google/nomulus/1608#-N0lHpEl2NC5by_jL-gv:-N0lHpEl2NC5by_jL-gw:bg74sjp) ([raw file](https://github.com/google/nomulus/blob/f27378389414a868bf46bcd409ee517d8741c484/core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java#L123)):*
> ```Java
>                   builder.put("state", convert(registrar.getState()));
>                   builder.put("ianaIdentifier", convert(registrar.getIanaIdentifier()));
>                   builder.put("billingIdentifier", convert(registrar.getBillingIdentifier()));
> ```

Have you tested this to make sure that removing columns in the existing sheet is safe? Given that we manually sync / compare the values, it's possible there could be problems. 
___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 390 at r1](https://reviewable.io/reviews/google/nomulus/1608#-N0lIhEeBtc4YCoKr0tV:-N0lIhEeBtc4YCoKr0tW:b-mr9wak) ([raw file](https://github.com/google/nomulus/blob/ea29e30b2edfc96b621c7e7c798a2fa391421a26/core/src/main/java/google/registry/model/registrar/Registrar.java#L390)):*
> ```Java
>   @Index @Nullable Long ianaIdentifier;
> 
>   /** Identifier of registrar used in external billing system (e.g. Oracle). */
> ```

Can we remove this from SQL?
___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 391 at r1](https://reviewable.io/reviews/google/nomulus/1608#-N0lIc0LALv6tksPebf_:-N0lIc0LALv6tksPebfa:b-fcztlx) ([raw file](https://github.com/google/nomulus/blob/ea29e30b2edfc96b621c7e7c798a2fa391421a26/core/src/main/java/google/registry/model/registrar/Registrar.java#L391)):*
> ```Java
> 
>   /** Identifier of registrar used in external billing system (e.g. Oracle). */
>   @Nullable @Deprecated Long billingIdentifier;
> ```

maybe annotate this with the "to remove after we've moved to SQL" annotation? 


<!-- Sent from Reviewable.io -->

2022-04-28 17:55 UTC, gbrodman reviewed
also can you add a short description of why we're doing this in the commit description please? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608#-:-N0lJ0NX5yI8W-Ka4Pql:bid9t7h)* status: all files reviewed, 3 unresolved discussions (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2022-04-28 19:35 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608)* status: all files reviewed, 3 unresolved discussions (waiting on @ignore and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 390 at r1](https://reviewable.io/reviews/google/nomulus/1608#-N0lIhEeBtc4YCoKr0tV:-N0lehrH4FZzn837vrYv:b45pudj) ([raw file](https://github.com/google/nomulus/blob/ea29e30b2edfc96b621c7e7c798a2fa391421a26/core/src/main/java/google/registry/model/registrar/Registrar.java#L390)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Can we remove this from SQL?
</blockquote></details>

It seems like it would need to be a two step process -- the first PR (this one) annotates this with @Ignore, or whatever it is that is used to tell Hibernate to ignore it, and then the second PR (after the first PR is deployed) drops the column from the table in a Flyway script.


<!-- Sent from Reviewable.io -->

2022-05-03 18:13 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, @ignore, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 393 at r2](https://reviewable.io/reviews/google/nomulus/1608#-N1A6xIS-gcdcqkix-8G:-N1A6xIS-gcdcqkix-8H:b-5ouwvy) ([raw file](https://github.com/google/nomulus/blob/e92910741cf13729c5f6cd9617f50b1df8bc95f3/core/src/main/java/google/registry/model/registrar/Registrar.java#L393)):*
> ```Java
>   /** Identifier of registrar used in external billing system (e.g. Oracle). */
>   // TODO(sarahbot@): Drop this column from the table in a flyway script in a follow up PR.
>   @Nullable @Deprecated @Ignore Long billingIdentifier;
> ```

You've added the Objectify `@Ignore` annotation, but you should have added whatever the correct Hibernate one is.  We're not using Datastore anymore.


<!-- Sent from Reviewable.io -->

2022-05-03 18:47 UTC, gbrodman requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 391 at r1](https://reviewable.io/reviews/google/nomulus/1608#-N0lIc0LALv6tksPebf_:-N1AEp04-R5dJYtwmYnR:b6r7oxh) ([raw file](https://github.com/google/nomulus/blob/ea29e30b2edfc96b621c7e7c798a2fa391421a26/core/src/main/java/google/registry/model/registrar/Registrar.java#L391)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nah I meant `@DeleteAfterMigration` 
___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 393 at r2](https://reviewable.io/reviews/google/nomulus/1608#-N1A6xIS-gcdcqkix-8G:-N1AErF89xKPK1JsaV26:b-9m3a6y) ([raw file](https://github.com/google/nomulus/blob/e92910741cf13729c5f6cd9617f50b1df8bc95f3/core/src/main/java/google/registry/model/registrar/Registrar.java#L393)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You've added the Objectify `@Ignore` annotation, but you should have added whatever the correct Hibernate one is.  We're not using Datastore anymore.
</blockquote></details>

should be `@Transient` iirc


<!-- Sent from Reviewable.io -->

2022-05-06 16:18 UTC, gbrodman requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot and @transient)

___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 391 at r1](https://reviewable.io/reviews/google/nomulus/1608#-N0lIc0LALv6tksPebf_:-N1P9Sq-ENkYyvTMLxNu:beqobch) ([raw file](https://github.com/google/nomulus/blob/ea29e30b2edfc96b621c7e7c798a2fa391421a26/core/src/main/java/google/registry/model/registrar/Registrar.java#L391)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think this change didn't get pushed 


<!-- Sent from Reviewable.io -->

2022-05-18 17:43 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608)* status: all files reviewed, 1 unresolved discussion (waiting on @transient)

___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 393 at r2](https://reviewable.io/reviews/google/nomulus/1608#-N1A6xIS-gcdcqkix-8G:-N2NF_bN7B7XorUX0Moi:b-v9a1yo) ([raw file](https://github.com/google/nomulus/blob/e92910741cf13729c5f6cd9617f50b1df8bc95f3/core/src/main/java/google/registry/model/registrar/Registrar.java#L393)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I cannot add the @Transient annotation because that causes the GenerateSqlSchemaCommandTest to fail. I will have to remove the field from the schema to add this annotation, and we don't want to actually remove the field from the schema in this PR.
</blockquote></details>

Are you sure about the ordering here, that it has to be dropped from the schema first, then from the Java object?  I would expect it to be the opposite order of how it's added.

How is `GenerateSqlSchemaCommandTest` failing exactly?  What's the error message?


<!-- Sent from Reviewable.io -->

2022-05-18 18:55 UTC, gbrodman approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608)* status: all files reviewed, 1 unresolved discussion (waiting on @transient)

___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 393 at r2](https://reviewable.io/reviews/google/nomulus/1608#-N1A6xIS-gcdcqkix-8G:-N2NWF5-91xwiTtqO5ne:b-q0ojxa) ([raw file](https://github.com/google/nomulus/blob/e92910741cf13729c5f6cd9617f50b1df8bc95f3/core/src/main/java/google/registry/model/registrar/Registrar.java#L393)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

GenerateSqlSchemaCommandTest.validateGeneratedSchemaIsSameAsSchemaInFile() fails with message "Files differ in content. Displaying side_by_side_markdown" In the markdown the only difference is the missing billing_identifier field in the Registrar table. It says in step 7 in the db/README.md (https://sourcegraph.com/github.com/google/nomulus/-/blob/db/README.md) that the flyway files for the schema change must be submitted first.
</blockquote></details>

This is, I believe,  the first time in a long time (since we've added the relevant checks) that we've actually removed a column from SQL. 

I do believe we'll want, as Sarah says, to add the `@Transient` annotation and to drop the column together in the same PR. 


<!-- Sent from Reviewable.io -->

2022-05-18 21:12 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608)* status: all files reviewed, 1 unresolved discussion (waiting on @transient)

___
*[`core/src/main/java/google/registry/model/registrar/Registrar.java` line 393 at r2](https://reviewable.io/reviews/google/nomulus/1608#-N1A6xIS-gcdcqkix-8G:-N2O-uy4CsHTbzYRnjgb:b21l9mo) ([raw file](https://github.com/google/nomulus/blob/e92910741cf13729c5f6cd9617f50b1df8bc95f3/core/src/main/java/google/registry/model/registrar/Registrar.java#L393)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This is, I believe,  the first time in a long time (since we've added the relevant checks) that we've actually removed a column from SQL. 

I do believe we'll want, as Sarah says, to add the `@Transient` annotation and to drop the column together in the same PR. 
</blockquote></details>

Curious to see how that goes.


<!-- Sent from Reviewable.io -->

2022-05-18 21:12 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1608#-:-N2O-yIh-Mccz0NXNjVW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @transient)



<!-- Sent from Reviewable.io -->

2022-05-18 21:15 UTC, merged

2022-05-18 21:16 UTC, CydeWeys commented
Note that the instructions say that the Flyway files for newly added columns must be added first -- I'm thinking it may be in reverse order for removing columns.  Think about it this way -- if you've already removed the data from the DB, but the field is there in the Java class and it's not marked as `@Transient` by Hibernate, then won't Hibernate error out when it's trying to populate that field from data in the DB that doesn't exist?  You can have data in the DB that doesn't map to a Java field (i.e. a column is added to the DB before it is used, or is removed from the Java object but still exists in the DB), but not vice-versa.

@weiminyu care to chime in?

2022-05-18 21:19 UTC, CydeWeys commented
But we'll see, this'll be a learning experience for us.