Remove to-be-deprecated OOB OAuth flow in nomulus login
google/nomulus pull request #1625
Opened 2022-05-05 20:55 UTC by jianglai

The Out-of-Band flow will be deprecated in October 2022. Unfortunately
there is no alternative provided that can perform login on a remote host
(which is probably WAI as the OOB flow is susceptible to remote phishing
attacks).

In this PR we switch to using the same loopback IP address redirect URI that a
normal local login session uses, and added instructions on how to set up
SSH port forwarding to complete the flow on a local host when the nomulus
tool runs remotely.

See https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html for
more details on the deprecation.

TESTED=run the new login flow from a remote host and verified it worked.

2022-05-06 20:47 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1625)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jianglai and @weiminyu)

___
*[`core/src/main/java/google/registry/tools/LoginCommand.java` line 35 at r1](https://reviewable.io/reviews/google/nomulus/1625#-N1Q6qADEW4RSduQMT1-:-N1Q6qADEW4RSduQMT10:b7bw223) ([raw file](https://github.com/google/nomulus/blob/cb44a9feeac015378b30dee27361b3c77e3f1923/core/src/main/java/google/registry/tools/LoginCommand.java#L35)):*
> ```Java
>       names = "--port",
>       description =
>           "A free port on the local host. When set, it is assumed that the nomulus tool runs on a"
> ```

Why not just pick a free one randomly, or use a default value here that is unlikely to normally be in use?

Forcing the user to pick a port isn't a great user experience.  Usually this isn't something you'd have to deal with.


<!-- Sent from Reviewable.io -->

2022-05-06 20:47 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1625)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jianglai and @weiminyu)

___
*[`core/src/main/java/google/registry/tools/LoginCommand.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/1625#-N1Q794J1vs2NorO5iFS:-N1Q794J1vs2NorO5iFT:b-d0069i) ([raw file](https://github.com/google/nomulus/blob/cb44a9feeac015378b30dee27361b3c77e3f1923/core/src/main/java/google/registry/tools/LoginCommand.java#L57)):*
> ```Java
>                     "Please first run the following command in a separate terminal on"
>                         + " your local host:\n\n"
>                         + "  ssh -L "
> ```

Use better String formatting than this, e.g. `System.out.printf()`


<!-- Sent from Reviewable.io -->

2022-05-07 03:22 UTC, jianglai reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1625)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[`core/src/main/java/google/registry/tools/LoginCommand.java` line 35 at r1](https://reviewable.io/reviews/google/nomulus/1625#-N1Q6qADEW4RSduQMT1-:-N1RTCNw5AgrIWROzDXg:b-l9go7p) ([raw file](https://github.com/google/nomulus/blob/cb44a9feeac015378b30dee27361b3c77e3f1923/core/src/main/java/google/registry/tools/LoginCommand.java#L35)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why not just pick a free one randomly, or use a default value here that is unlikely to normally be in use?

Forcing the user to pick a port isn't a great user experience.  Usually this isn't something you'd have to deal with.
</blockquote></details>

That would have been nice, wouldn't it :package: 

But this command runs on the remote host, and what we need is to initiate an SSH tunnel from the local host and forward the local port  to the remote host. There is no way for the remote host to know which port is available on the local host.

What we can do is to perform the tunneling and port forwarding from the other side with in Java, i. e. from the remote host to the local host,  to eliminate the need for the user to have to run a command in terminal. But that involves setting up credentials for the remote host to access the local host (not to mention whether the local host is accessible), and still does not solve the problem that it needs to find a free local port. I guess if we really really want to make the user experience nice, we can randomly generate a port number and try to establish the tunnel from the remote host, and retry until we find a free local port.

That said, what I described above is probably over-engineering for minimal benefits...
___
*[`core/src/main/java/google/registry/tools/LoginCommand.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/1625#-N1Q794J1vs2NorO5iFS:-N1RX-Pj53EOZQrU2kdB:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cb44a9feeac015378b30dee27361b3c77e3f1923/core/src/main/java/google/registry/tools/LoginCommand.java#L57)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use better String formatting than this, e.g. `System.out.printf()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-09 21:17 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1625#-:-N1efgQn72CSWeIpwSz5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2022-05-09 21:17 UTC, merged