Optimize RDAP entity event query
google/nomulus pull request #1635
Opened 2022-05-18 06:24 UTC by weiminyu

For each EPP entity, directly load the latest HistoryEntry per event type
instead of loading all events through the HistoryEntryDao.

Although most entities have a small number of history entries, there are
a few entities with many entries, enough to cause OutOfMemory error.

2022-05-18 19:25 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @mindhog, and @weiminyu)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 165 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2Na1gEAb36ERBLO__X:-N2Na1gEAb36ERBLO__Y:b-ji3uig) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L165)):*
> ```Java
>    * DomainHistory where domainRepoId = '17-Q9JYB4C' and type is not null group by type)}
>    */
>   private static final String GET_LAST_HISTORY_BY_TYPE_JPQL_TEMPLATE =
> ```

I'm not 100% sure how this would work in HQL, but in raw Postgres you can do 

`SELECT DISTINCT ON (history_type) * FROM "%entityName%" WHERE %repoIdField = '%repoIdValue' ORDER BY history_type, history_modification_time DESC;`

and it gets the same results without having nested statements 
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 890 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2NZRtMEuS-oV5Sib9w:-N2NZRtNB6n3OzPZgTJ7:b5zjptg) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L890)):*
> ```Java
>     // domain name has not been transferred since it was created.
>     Iterable<? extends HistoryEntry> historyEntries;
>     if (tm().isOfy()) {
> ```

We don't need the `isOfy` check anymore, right? 
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 897 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2N_EnkDJT8tUg48oIj:-N2N_EnkDJT8tUg48oIk:b-tnxu48) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L897)):*
> ```Java
>           HistoryEntryDao.getHistoryClassFromParent(resourceVkey.getKind());
>       String entityName = historyClass.getAnnotation(Entity.class).name();
>       if (Strings.isNullOrEmpty(entityName)) {
> ```

I don't think this is the case for any of our history classes right?
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 902 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2N_Xv0CoRgE31Ta5g4:-N2N_Xv0CoRgE31Ta5g5:b-n8e8s5) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L902)):*
> ```Java
>       String repoIdFieldName = HistoryEntryDao.getRepoIdFieldNameFromHistoryClass(historyClass);
>       String jpql =
>           GET_LAST_HISTORY_BY_TYPE_JPQL_TEMPLATE
> ```

thoughts on using `String::format`?


<!-- Sent from Reviewable.io -->

2022-05-18 19:45 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 165 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2Na1gEAb36ERBLO__X:-N2NgVdWE5QfWarFsKQR:b-i5b4kl) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L165)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I'm not 100% sure how this would work in HQL, but in raw Postgres you can do 

`SELECT DISTINCT ON (history_type) * FROM "%entityName%" WHERE %repoIdField = '%repoIdValue' ORDER BY history_type, history_modification_time DESC;`

and it gets the same results without having nested statements 
</blockquote></details>

select distinct **ON (column)** is postgresql-specific, so unlikely to be supported by JPQL.
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 890 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2NZRtMEuS-oV5Sib9w:-N2NczXb0rJBK7EVZDVx:b-43az7n) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L890)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We don't need the `isOfy` check anymore, right? 
</blockquote></details>

Until we remove TestOfyAndSql tags from all Rdap tests, we need it.
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 897 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2N_EnkDJT8tUg48oIj:-N2NdPxYAEIGTwLfP_HK:bjui0jh) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L897)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think this is the case for any of our history classes right?
</blockquote></details>

It is. All of them are annotated with a plain Entity annotation without name.

I can call getSimpleName directly, but feel that calling getAnnotation first is a good habit.
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 902 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2N_Xv0CoRgE31Ta5g4:-N2Nep0E08W6oRWx_tO4:bc5r6t) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L902)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

thoughts on using `String::format`?
</blockquote></details>

I think this makes the template more readable. Even if we use argument indexes, the template itself can be confusing unless it is put next to the place when the actual query is generated.


<!-- Sent from Reviewable.io -->

2022-05-18 19:50 UTC, mindhog approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @gbrodman)



<!-- Sent from Reviewable.io -->

2022-05-19 16:51 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman, @mindhog, and @weiminyu)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 165 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2Na1gEAb36ERBLO__X:-N2SCz4V4J6YlsXBCZtD:b-5raa8t) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L165)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

select distinct **ON (column)** is postgresql-specific, so unlikely to be supported by JPQL.
</blockquote></details>

If the `SELECT DISTINCT ON (column)` is more performant, then we should probably just use that even though it's PostgreSQL-specific.  (Is it more performant?)

We're already using SQL arrays, so we're already locked into PostgreSQL anyway.
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 897 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2N_EnkDJT8tUg48oIj:-N2SDJipBqDBHIGB9MRN:blmjlkx) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L897)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

It is. All of them are annotated with a plain Entity annotation without name.

I can call getSimpleName directly, but feel that calling getAnnotation first is a good habit.


</blockquote></details>

Is there anything in `TypeUtils` that is useful here?  `getClassFromString()` perhaps?
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 902 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2N_Xv0CoRgE31Ta5g4:-N2SDQrF2rHnVIhBN7fQ:bdyfmue) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L902)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

I think this makes the template more readable. Even if we use argument indexes, the template itself can be confusing unless it is put next to the place when the actual query is generated.
</blockquote></details>

Any reason this replacement isn't happening using built-in SQL 
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 907 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2SD_X21-ul6S-XxL_P:-N2SD_X21-ul6S-XxL_Q:b-v5ipzi) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L907)):*
> ```Java
>               .replace("%repoIdValue%", resourceVkey.getSqlKey().toString());
>       historyEntries =
>           jpaTm().transact(() -> jpaTm().getEntityManager().createQuery(jpql).getResultList());
> ```

Why not use `setParameter()` here instead of String munging from above?  Does it not work on column names?  `repoIdValue` at least is not a column name -- it's actual data.


<!-- Sent from Reviewable.io -->

2022-05-19 17:22 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, @mindhog, and @weiminyu)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 165 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2Na1gEAb36ERBLO__X:-N2SJa-fCdpDw4S6oX4Z:b-gtgk7w) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L165)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

If the `SELECT DISTINCT ON (column)` is more performant, then we should probably just use that even though it's PostgreSQL-specific.  (Is it more performant?)

We're already using SQL arrays, so we're already locked into PostgreSQL anyway.
</blockquote></details>

I didn't actually know which one was superior before but I just did a test using separate repo IDs on prod (if I don't use separate repo IDs, whichever query runs last is faster due to caching):

`explain analyze select distinct on (history_type) * FROM "DomainHistory" WHERE domain_repo_id = '339578985-DEV' ORDER BY history_type, history_modification_time DESC;` Planning Time: 0.177 ms
 Execution Time: 0.364 ms
(8 rows)


`explain analyze select e from "DomainHistory" e where domain_repo_id = '436E9C8CE-DEV' and history_modification_time in (select max(history_modification_time) from "DomainHistory" where domain_repo_id = '436E9C8CE-DEV' and history_type is not null group by history_type);`
 Planning Time: 0.240 ms
 Execution Time: 8.925 ms
(16 rows)

Interestingly, it seems like the second one (with the select(max)) has a lot more variance when testing it with various domains. The highest execution time I saw with a few different choices was 35ms, and the lowest was about 1ms 

I'm not sure if this is a meaningful difference. There is a tangible benefit to writing HQL (what already exists here), but there's also probably a benefit in a simpler shorter SQL statement. 
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 897 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2N_EnkDJT8tUg48oIj:-N2NhlNH8PkqrrKZBK-L:b-rzudru) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L897)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

It is. All of them are annotated with a plain Entity annotation without name.

I can call getSimpleName directly, but feel that calling getAnnotation first is a good habit.


</blockquote></details>

what I meant was that our classes don't have a name in the Entity annotation, so this doesn't seem necessary 


<!-- Sent from Reviewable.io -->

2022-05-19 17:23 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, @mindhog, and @weiminyu)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 890 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2NZRtMEuS-oV5Sib9w:-N2SKxMD3Z5FppqIb0Vj:b-ygm5bs) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L890)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Until we remove TestOfyAndSql tags from all Rdap tests, we need it.
</blockquote></details>

boo :/ 


<!-- Sent from Reviewable.io -->

2022-05-19 18:52 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, @mindhog, and @weiminyu)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 911 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2SduDI480As9NF4SoR:-N2SduDI480As9NF4SoS:blcg8gp) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L911)):*
> ```Java
>     for (HistoryEntry historyEntry : historyEntries) {
>       EventAction rdapEventAction =
>           HISTORY_ENTRY_TYPE_TO_RDAP_EVENT_ACTION_MAP.get(historyEntry.getType());
> ```

Looking at the contents of this map, it seems like we can make our query above smarter, by only querying for the relevant types from the DB, rather than querying for all distinct ones and ignroing them.  In particular, `HISTORY_ENTRY_TYPE_TO_RDAP_EVENT_ACTION_MAP` does not even contain UPDATEs, which are the types causing us all these problems in the first place!


<!-- Sent from Reviewable.io -->

2022-05-19 19:16 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman, @mindhog, and @weiminyu)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 165 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2Na1gEAb36ERBLO__X:-N2Sg3OeEWnTt2ROGrvJ:b-kwmtry) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L165)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I didn't actually know which one was superior before but I just did a test using separate repo IDs on prod (if I don't use separate repo IDs, whichever query runs last is faster due to caching):

`explain analyze select distinct on (history_type) * FROM "DomainHistory" WHERE domain_repo_id = '339578985-DEV' ORDER BY history_type, history_modification_time DESC;` Planning Time: 0.177 ms
 Execution Time: 0.364 ms
(8 rows)


`explain analyze select e from "DomainHistory" e where domain_repo_id = '436E9C8CE-DEV' and history_modification_time in (select max(history_modification_time) from "DomainHistory" where domain_repo_id = '436E9C8CE-DEV' and history_type is not null group by history_type);`
 Planning Time: 0.240 ms
 Execution Time: 8.925 ms
(16 rows)

Interestingly, it seems like the second one (with the select(max)) has a lot more variance when testing it with various domains. The highest execution time I saw with a few different choices was 35ms, and the lowest was about 1ms 

I'm not sure if this is a meaningful difference. There is a tangible benefit to writing HQL (what already exists here), but there's also probably a benefit in a simpler shorter SQL statement. 

</blockquote></details>

In my measurements comparing domains with similar number of history entries, the sub-select query is usually faster. E.g., 334745225-DEV (select distint) took 170ms while 34040F2D0-DEV (sub select) took 130ms, on cold starts. When cache is loaded, it's 50ms vs 40ms, still in subselect's favor. Note that explain analyze does not execute the query. The Execution Time reported is the analysis cost.

Performance is a smaller matter. Only the sub-select query can be executed in JPQL. If we use select distinct with native query, we will have to 
cast string to Enum and DateTime.  


PS: Here is someone else's report of select distinct on being a bit slower: https://stackoverflow.com/questions/54810250/postgresql-latest-row-in-distinct-on-less-performant-than-max-row-in-group-by


<!-- Sent from Reviewable.io -->

2022-05-19 19:24 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 902 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2N_Xv0CoRgE31Ta5g4:-N2SkBaD6KO7pl9sVoD8:bv65dx7) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L902)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Any reason this replacement isn't happening using built-in SQL 
</blockquote></details>

If only parameter **values** are undetermined, we can use Query.setParameter to set them.
Here the table and column names are variables. We have to replace them before creation the query.
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 907 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2SD_X21-ul6S-XxL_P:-N2SkcA30FfqU1vq5Nys:bjw7gtn) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L907)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why not use `setParameter()` here instead of String munging from above?  Does it not work on column names?  `repoIdValue` at least is not a column name -- it's actual data.
</blockquote></details>

Entityname and repoIdFieldName cannot be set with setParameter(). It's an extra mental cost to repoIdValue separately.
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 911 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2SduDI480As9NF4SoR:-N2SlBcd4L5AY8ChblP-:b-daw641) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L911)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Looking at the contents of this map, it seems like we can make our query above smarter, by only querying for the relevant types from the DB, rather than querying for all distinct ones and ignroing them.  In particular, `HISTORY_ENTRY_TYPE_TO_RDAP_EVENT_ACTION_MAP` does not even contain UPDATEs, which are the types causing us all these problems in the first place!
</blockquote></details>

The query as it stands  takes < 10s  for the million-row repoId on cold start, and 1s if cache is loaded. For the others it is at millisecond level.
We don't need to spend too much time on it right now.


<!-- Sent from Reviewable.io -->

2022-05-19 19:28 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 897 at r1](https://reviewable.io/reviews/google/nomulus/1635#-N2N_EnkDJT8tUg48oIj:-N2SmNdI0i0745tiExVn:b-wezghw) ([raw file](https://github.com/google/nomulus/blob/e8412bb8c9d5941bf6385f962cfdc746747d1aba/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L897)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what I meant was that our classes don't have a name in the Entity annotation, so this doesn't seem necessary 
</blockquote></details>

There is a getEntityName() utility method in some test utils. We should move it to production and replace the few places entity name is needed. That can be left for later.


<!-- Sent from Reviewable.io -->

2022-05-19 21:08 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635#-:-N2T8XMM3rmHi-DQdODl:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @mindhog)



<!-- Sent from Reviewable.io -->

2022-05-20 02:50 UTC, gbrodman approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1635)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-05-20 03:35 UTC, merged