Add batching to ExpandRecurringBillingEventsAction
google/nomulus pull request #1636
Opened 2022-05-18 15:09 UTC by CydeWeys

It's OOMing on trying to load every single BillingRecurrence that needs to be
expanded simultaneously (which is to be expected). So this processes them in
transactional batches of 50.

2022-05-18 15:15 UTC, mindhog commented
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 147 at r1](https://reviewable.io/reviews/google/nomulus/1636#-N2Miz2333UNtInAyECh:-N2Miz24CQUGamd0n3kc:bltc20k) ([raw file](https://github.com/google/nomulus/blob/a184ab431e2df30808c92a832a8698f1af41e6f9/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L147)):*
> ```Java
>                                   + "WHERE eventTime <= :executeTime "
>                                   + "AND eventTime < recurrenceEndTime "
>                                   + "LIMIT :batchSize",
> ```

Are you sure this works?  I recall "LIMIT" being problematic in this context.

We use the `setMaxResults()` method elsewhere.


<!-- Sent from Reviewable.io -->

2022-05-18 15:18 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 147 at r1](https://reviewable.io/reviews/google/nomulus/1636#-N2Miz2333UNtInAyECh:-N2MjM4g49o5dKZV2kTw:bt053l5) ([raw file](https://github.com/google/nomulus/blob/a184ab431e2df30808c92a832a8698f1af41e6f9/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L147)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Are you sure this works?  I recall "LIMIT" being problematic in this context.

We use the `setMaxResults()` method elsewhere.
</blockquote></details>

And this may load the same thing again and again?

I would think the query should be like

where ... and id > max_processed_id order by id ASC

and each iteration should update max_processed_id.


<!-- Sent from Reviewable.io -->

2022-05-18 15:24 UTC, mindhog requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 147 at r1](https://reviewable.io/reviews/google/nomulus/1636#-N2Miz2333UNtInAyECh:-N2MlGX7BiCXIXgyt63y:b-8zmflj) ([raw file](https://github.com/google/nomulus/blob/a184ab431e2df30808c92a832a8698f1af41e6f9/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L147)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

And this may load the same thing again and again?

I would think the query should be like

where ... and id > max_processed_id order by id ASC

and each iteration should update max_processed_id.
</blockquote></details>

It's probably worth adding a test.


<!-- Sent from Reviewable.io -->

2022-05-18 16:14 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)

___
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 147 at r1](https://reviewable.io/reviews/google/nomulus/1636#-N2Miz2333UNtInAyECh:-N2MweJA7xkAGVwzxhf_:b-896fix) ([raw file](https://github.com/google/nomulus/blob/a184ab431e2df30808c92a832a8698f1af41e6f9/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L147)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

It's probably worth adding a test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-18 17:04 UTC, mindhog approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-05-18 18:23 UTC, mindhog requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 181 at r4](https://reviewable.io/reviews/google/nomulus/1636#-N2NNCs5BHOveeQwgPI6:-N2NNCs6A9bfINtymWgu:bfpo7ta) ([raw file](https://github.com/google/nomulus/blob/b05537f04c141568950f434d7777b9fea8c4a1f7/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L181)):*
> ```Java
>                       batchBillingEventsSaved +=
>                           expandBillingEvent(recurring, executeTime, cursorTime, isDryRun);
>                       if (batchBillingEventsSaved > 0) {
> ```

I'm not quite clear on the logic here: wouldn't this add `recurring` to the expanded domains even if the event itself was not expanded but the event for some previous domain was?


<!-- Sent from Reviewable.io -->

2022-05-18 19:19 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @mindhog)

___
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 181 at r4](https://reviewable.io/reviews/google/nomulus/1636#-N2NNCs5BHOveeQwgPI6:-N2NaXGP30QQtSP8ktRz:b-3nc14s) ([raw file](https://github.com/google/nomulus/blob/b05537f04c141568950f434d7777b9fea8c4a1f7/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L181)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I'm not quite clear on the logic here: wouldn't this add `recurring` to the expanded domains even if the event itself was not expanded but the event for some previous domain was?
</blockquote></details>

Good catch, fixed.  It needs to operate on just what was returned by `expandBillingEvent()`.


<!-- Sent from Reviewable.io -->

2022-05-18 19:20 UTC, CydeWeys reviewed
PTAL

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636#-:-N2NbCEmEtGD02pKW9Sa:bb71pro)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-05-18 19:30 UTC, mindhog approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-05-18 19:55 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 194 at r5](https://reviewable.io/reviews/google/nomulus/1636#-N2Nj-oU40g2Ju1ugbYN:-N2Nj-oU40g2Ju1ugbYO:b-h54wpj) ([raw file](https://github.com/google/nomulus/blob/3b246a6a575cfbb2909e5fcfed95291e700dcf0c/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L194)):*
> ```Java
>           "Saved %d billing events in batch with max recurrence id %d.",
>           sqlBatchResults.batchBillingEventsSaved(), maxProcessedRecurrenceId);
>     } while (sqlBatchResults.batchBillingEventsSaved() > 0);
> ```

This is not safe if every record in a batch test true for if (expandedDomains.contains(recurring.getTargetId()))

We need to count loaded entities separately.



_Code quote:_
```Java
batchBillingEventsSaved(
```


<!-- Sent from Reviewable.io -->

2022-05-18 21:01 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @mindhog and @weiminyu)

___
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 194 at r5](https://reviewable.io/reviews/google/nomulus/1636#-N2Nj-oU40g2Ju1ugbYN:-N2NyOGJ7l5YKOFIMsOY:bqxhjot) ([raw file](https://github.com/google/nomulus/blob/3b246a6a575cfbb2909e5fcfed95291e700dcf0c/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L194)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This is not safe if every record in a batch test true for if (expandedDomains.contains(recurring.getTargetId()))

We need to count loaded entities separately.
</blockquote></details>

Good catch.  This was very unlikely to ever happen, but worth covering it just in case.  PTAL.


<!-- Sent from Reviewable.io -->

2022-05-19 02:09 UTC, weiminyu approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1636)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2022-05-19 13:13 UTC, merged