Slightly improve performance of ExpandRecurringBillingEventsAction
google/nomulus pull request #1642
Opened 2022-05-23 17:03 UTC by CydeWeys

We don't need to log every single no-op batch of 50 Recurrences that are
processed (considering we have 1.5M total in our system), and we also don't need
to process Recurrences that already ended prior to the Cursor time (this gets us
down to 420k from 1.5M).

2022-05-24 00:50 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1642)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 210 at r1](https://reviewable.io/reviews/google/nomulus/1642#-N2nXZny64OQbnaEkAr9:-N2nXZny64OQbnaEkArA:b86i64q) ([raw file](https://github.com/google/nomulus/blob/0ef60fa8c7afc4af04361f61c2fbb305b540cda4/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L210)):*
> ```Java
>         // then only log one no-op every so often as a good balance between letting the user track
>         // that the action is still running while also not spamming the logs incessantly.
>         logger.atInfo().log(
> ```

logger.atInfo().atMostEvery(1, TimeUnit.Minute(3)).log(...) behave more or less the same?



_Code quote:_
```Java
logger.atInfo().log(
```


<!-- Sent from Reviewable.io -->

2022-05-24 21:25 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1642)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java` line 210 at r1](https://reviewable.io/reviews/google/nomulus/1642#-N2nXZny64OQbnaEkAr9:-N2rxM1k6FPGIVnn0jqp:b-poeylv) ([raw file](https://github.com/google/nomulus/blob/0ef60fa8c7afc4af04361f61c2fbb305b540cda4/core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java#L210)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

logger.atInfo().atMostEvery(1, TimeUnit.Minute(3)).log(...) behave more or less the same?
</blockquote></details>

Done. It's not exactly the same semantics (as now it'll be outputting potentially immediately after a non-noop batch), but that's probably fine.  And the trade-off is that the implementation is simpler.


<!-- Sent from Reviewable.io -->

2022-05-24 21:25 UTC, CydeWeys reviewed
PTAL

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1642#-:-N2rxUpf1Rd8_QBLCT_S:bb71pro)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2022-05-25 20:21 UTC, weiminyu approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1642)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2022-05-25 21:27 UTC, merged