Split failing dns update batches and kill after 10 retries
google/nomulus pull request #1664
Opened 2022-06-09 20:12 UTC by sarahcaseybot

2022-06-10 17:30 UTC, gbrodman requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 68 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4DX3_PAq6V1gE-wZYg:-N4DX3_PAq6V1gE-wZYh:bmb7t77) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L68)):*
> ```Java
>   public static final String PATH = "/_dr/task/publishDnsUpdates";
>   public static final String LOCK_NAME = "DNS updates";
>   public static final String RETRY_HEADER = "X-AppEngine-TaskRetryCount";
> ```

do you happen to know what we'll do once we move away from appengine? 
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 147 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4D_mwQ3o4zESOQ9zKa:-N4D_mwQ3o4zESOQ9zKb:b4eb4jk) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L147)):*
> ```Java
>       // If executeWithLocks fails to get the lock, it does not throw an exception, simply returns
>       // false. We need to make sure to take note of this error; otherwise, a failed lock might
>       // result
> ```

nit: comment formatting 
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 158 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4Ddejr0KSWrW2bBcIK:-N4Ddejr0KSWrW2bBcIL:b7o92eu) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L158)):*
> ```Java
>         throw new ServiceUnavailableException("Lock failure");
>       }
>     } catch (Throwable e) {
> ```

Don't we already handle this in the `call` method below? 
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 169 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4Dd8HP9K2LvdLQpEcC:-N4Dd8HP9K2LvdLQpEcD:b-mtycc9) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L169)):*
> ```Java
>       }
>       // If the batch only contains 1 name, allow it 10 retries
>       else if (retryCount < 10) {
> ```

nit, switch the ordering of this line and the previous (comment) line 
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 203 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4DeKhW5en7WutSejee:-N4DeKhW5en7WutSejef:bi5jqra) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L203)):*
> ```Java
> 
>   /** Splits the domains and hosts in a batch into 2 batches and adds them to the queue. */
>   private void splitBatch() {
> ```

Is there any reason why we can't just use `Iterables::partition` to split the domains and hosts? 
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 225 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4DeQcX9ZpRGWtgVClG:-N4DeQcX9ZpRGWtgVClH:b-69lxml) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L225)):*
> ```Java
>     }
> 
>     // Enqueue set 1
> ```

to be safe we can have this be a method to which we pass `domains` and `hosts` so that we don't accidentally mess up task enqueueing 
___
*[`core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4Dea1i8jMmLiV7QxxI:-N4Dea1i8jMmLiV7QxxJ:b-gnw7kt) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java#L113)):*
> ```Java
>     action.clock = clock;
>     action.taskQueueUtils = taskQueueUtils;
>     action.retryCount = 1;
> ```

I'm not sure if this matters but the retry count starts at 0 right? 
___
*[`core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java` line 256 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4Dekjo1yp_J98aTG69:-N4Dekjo1yp_J98aTG6A:bbvbvf0) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java#L256)):*
> ```Java
>     verify(taskQueueUtils).enqueue(queue, taskOptions2);
>   }
> ```

Shouldn't we also test that we stop after the 10th failure? 


<!-- Sent from Reviewable.io -->

2022-06-14 19:02 UTC, jianglai requested changes
It's better to include a summary of what this PR does in the description. Not everyone has access to the design doc.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664#-:-N4YZXu0EFUBuctruqCv:b-qyewxo)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/DnsModule.java` line 137 at r2](https://reviewable.io/reviews/google/nomulus/1664#-N4YXshd7c1LhFgk3HQe:-N4YXshd7c1LhFgk3HQf:bt3ms37) ([raw file](https://github.com/google/nomulus/blob/e7938837ab90d575c81d71e67899f3e9e3ad62b4/core/src/main/java/google/registry/dns/DnsModule.java#L137)):*
> ```Java
> 
>   @Provides
>   @Header(RETRY_HEADER)
> ```

I think it is better to provide this binding in `RequestModule`, as the header is generic to all requests.



_Code quote:_
```Java
  @Provides
  @Header(RETRY_HEADER)
  static int provideRetryCount(HttpServletRequest req) {
    return Integer.parseInt(extractRequiredHeader(req, RETRY_HEADER));
```
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 68 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4DX3_PAq6V1gE-wZYg:-N4YX4CP-WadmS9Bn5B4:b-gw3eao) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L68)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I don't know what the plan is for that. Do we know yet what we will do with the task queues?
</blockquote></details>

https://cloud.google.com/tasks/docs/creating-http-target-tasks

It looks to be `X-CloudTasks-TaskRetryCount`. Not really a surprise here.



_Code quote:_
```Java
X-AppEngine-TaskRetryCount
```
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 158 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4Ddejr0KSWrW2bBcIK:-N4Y_zve2r1_6atc6ZTw:b-oiz38i) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L158)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

This is needed here too since we only call run() in tests
</blockquote></details>

If that's the case, why do we need the try block in the `call` method? Is it called anywhere other than inside the `run` method?
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 111 at r2](https://reviewable.io/reviews/google/nomulus/1664#-N4YXFd58sgZeZSXHhxY:-N4YXFd58sgZeZSXHhxZ:bzbrnwh) ([raw file](https://github.com/google/nomulus/blob/e7938837ab90d575c81d71e67899f3e9e3ad62b4/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L111)):*
> ```Java
>   @Inject LockHandler lockHandler;
>   @Inject Clock clock;
>   @Inject TaskQueueUtils taskQueueUtils;
> ```

We should not be using TaskQueueUtils anymore. Use `CloudTasksUtils` instead.



_Code quote:_
```Java
TaskQueueUtils taskQueueUtil
```


<!-- Sent from Reviewable.io -->

2022-06-15 01:22 UTC, gbrodman requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 203 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4DeKhW5en7WutSejee:-N4Zw3gz4qRtCmiWyM3f:b-psip5g) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L203)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Using partition could work, but there is a lot of extra handling that needs to be added since domains or hosts could be empty lists which would cause an IllegalArgumentException in partition. 

Also, partition would split into 2 or 3 lists depending on if the size is even or odd. Then, there may be more lists for host than there are for domains or vice versa. Ex: there may be no lists for host if there are no hosts in the original batch but if the domain list was originally of size 3 it would be split into 3 lists of size 1 which would leave us with zero host lists and 3 domain lists. 

Obviously all that could all be handled, but it just seemed cleaner to do it this way instead.  
</blockquote></details>

actually a better solution that would solve all of this would be to just convert them to a list (or inject them as a list, whichever) then just use `domains.subList(0, domains.size() / 2)` and `domains.subList(domains.size() / 2, domains.size())` as your two lists 

then, to create the strings, we can use the better-supported `Joiner.on(",").join(...)` 
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 111 at r2](https://reviewable.io/reviews/google/nomulus/1664#-N4YXFd58sgZeZSXHhxY:-N4Zug6jBoDb1Epo-gIt:b7pembw) ([raw file](https://github.com/google/nomulus/blob/e7938837ab90d575c81d71e67899f3e9e3ad62b4/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L111)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

We should not be using TaskQueueUtils anymore. Use `CloudTasksUtils` instead.
</blockquote></details>

in addition to doing this, while you're at it maybe mark TaskQueueUtils as `@Deprecated` so that others don't run into the same thing? 
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 163 at r2](https://reviewable.io/reviews/google/nomulus/1664#-N4ZwmjQABOCM89ljdBO:-N4ZwmjQABOCM89ljdBP:bs4iouq) ([raw file](https://github.com/google/nomulus/blob/e7938837ab90d575c81d71e67899f3e9e3ad62b4/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L163)):*
> ```Java
>       }
>       // After 3 retries, split the batch
>       if (domains.size() > 1 || hosts.size() > 1) {
> ```

What happens if we have a ton of domains but no hosts, but it's still failing? Wouldn't we still want to split the domains up? 

(also we'd want isEmpty checks here anyway) 


<!-- Sent from Reviewable.io -->

2022-06-15 15:41 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 158 at r1](https://reviewable.io/reviews/google/nomulus/1664#-N4Ddejr0KSWrW2bBcIK:-N4c0ixb0AGdpD-KDGSX:b-3l0lae) ([raw file](https://github.com/google/nomulus/blob/d31e295220b39898029e283c200f0bd49ce06614/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L158)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

If that's the case, why do we need the try block in the `call` method? Is it called anywhere other than inside the `run` method?
</blockquote></details>

right, the thinking is that we only want to handle exceptions in one place 


<!-- Sent from Reviewable.io -->

2022-06-15 17:49 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 111 at r2](https://reviewable.io/reviews/google/nomulus/1664#-N4YXFd58sgZeZSXHhxY:-N4cTv8t89wTVhc0iorI:b-mctn33) ([raw file](https://github.com/google/nomulus/blob/e7938837ab90d575c81d71e67899f3e9e3ad62b4/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L111)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

in addition to doing this, while you're at it maybe mark TaskQueueUtils as `@Deprecated` so that others don't run into the same thing? 
</blockquote></details>

#1669 is now merged. We can rebase this PR, replace `TaskQueueUtils` with `CloudTasksUtils` and deploy to alpha to test.


<!-- Sent from Reviewable.io -->

2022-06-21 15:23 UTC, jianglai requested changes
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 70 at r3](https://reviewable.io/reviews/google/nomulus/1664#-N55q8og4g59h5opmZLM:-N55q8og4g59h5opmZLN:bt22cva) ([raw file](https://github.com/google/nomulus/blob/9d0a48d4b91113688b24b177895cbe56be5a4ffe/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L70)):*
> ```Java
>   public static final String PATH = "/_dr/task/publishDnsUpdates";
>   public static final String LOCK_NAME = "DNS updates";
>   public static final String RETRY_HEADER = "X-CloudTasks-TaskRetryCount";
> ```

Let's link to the source:

https://cloud.google.com/tasks/docs/creating-http-target-tasks

Also, have you tried this on alpha yet? My concern is that Cloud Tasks allows you to create either an App Engine task or an HTTP task. We currently still create the former because we still use GAE, but this header is listed in the documentation for the latter. So we should make sure that App Engine tasks created by Cloud Tasks contains this header.

Ultimately once we move off of GAE, we will need to refactor `CloudTasksUtils` to create HTTP tasks instead and this header will definitely be the one to use, but I'm not sure for the time being.



_Code quote:_
```Java
public static final String RETRY_HEADER = "X-CloudTasks-TaskRetryCount";
```


<!-- Sent from Reviewable.io -->

2022-06-23 14:01 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 70 at r3](https://reviewable.io/reviews/google/nomulus/1664#-N55q8og4g59h5opmZLM:-N5FrH5_59YMyjQPkmhM:b-q7eim6) ([raw file](https://github.com/google/nomulus/blob/9d0a48d4b91113688b24b177895cbe56be5a4ffe/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L70)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Changed this back to the App Engine Header as the Cloud Tasks header did not work in Alpha. Added a TODO in CloudTasksUtils to change the header once CloudTasksUtils is refactored to create HTTP tasks
</blockquote></details>

It would be more resilient to check _both_, and use whichever happens to be present, with a TODO to remove the App Engine one post-migration.  That method should be more resilient across the migration boundary.


<!-- Sent from Reviewable.io -->

2022-06-23 14:17 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 163 at r2](https://reviewable.io/reviews/google/nomulus/1664#-N4ZwmjQABOCM89ljdBO:-N5Fv5XM1VdimR6G8S-S:bp7ea0n) ([raw file](https://github.com/google/nomulus/blob/e7938837ab90d575c81d71e67899f3e9e3ad62b4/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L163)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I think this handles the situation you're describing.  If we have say...

domains.size() = 5
hosts.size() = 0
retryCount = 3

this code would call splitBatch()

I don't think isEmpty checks are necessary since a .size() call on an empty set returns 0
</blockquote></details>

What if there's 1 domain and 1 host?  Shouldn't that still be split?


<!-- Sent from Reviewable.io -->

2022-06-23 14:17 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 170 at r4](https://reviewable.io/reviews/google/nomulus/1664#-N5FvA5c-VQ7GwxC3Rtc:-N5FvA5c-VQ7GwxC3Rtd:bky9zie) ([raw file](https://github.com/google/nomulus/blob/2fcf73ebfcac1cb42933265a259ad8d7adffe30f/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L170)):*
> ```Java
>       }
>       // If the batch only contains 1 name, allow it 10 retries
>       else if (retryCount < 10) {
> ```

Don't hard-code a magic number like 10.  This should, at minimum, be a `static final int`, and then possibly, configurable.


<!-- Sent from Reviewable.io -->

2022-06-23 14:19 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java` line 239 at r4](https://reviewable.io/reviews/google/nomulus/1664#-N5Fvg2UChPC_vYyn9St:-N5Fvg2UChPC_vYyn9Su:b-ftutdg) ([raw file](https://github.com/google/nomulus/blob/2fcf73ebfcac1cb42933265a259ad8d7adffe30f/core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java#L239)):*
> ```Java
>     action.domains =
>         ImmutableSet.of(
>             "example1.xn--q9jyb4c",
> ```

Can you make this 5 domains?  I want to see how `subList()` handles an uneven split.


<!-- Sent from Reviewable.io -->

2022-06-23 14:22 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 187 at r4](https://reviewable.io/reviews/google/nomulus/1664#-N5FwH073ERmQzTmozMX:-N5FwH073ERmQzTmozMY:brpla7r) ([raw file](https://github.com/google/nomulus/blob/2fcf73ebfcac1cb42933265a259ad8d7adffe30f/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L187)):*
> ```Java
>   /** Splits the domains and hosts in a batch into smaller batches and adds them to the queue. */
>   private void splitBatch() {
>     List<String> domainList = new ArrayList<>(domains);
> ```

Use `ImmutableList` here instead of `ArrayList`.  Basic guidance on Guava's immutable collections is to always use them unless for some reason you can't (e.g. you need to continually modify the contents, which isn't required here).


<!-- Sent from Reviewable.io -->

2022-06-23 14:29 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 173 at r4](https://reviewable.io/reviews/google/nomulus/1664#-N5Fwx_PAXVLnCoL9YR5:-N5Fwx_PAXVLnCoL9YR6:b37ftqv) ([raw file](https://github.com/google/nomulus/blob/2fcf73ebfcac1cb42933265a259ad8d7adffe30f/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L173)):*
> ```Java
>         throw e;
>       }
>       // If we get here, we should terminate this task as it is likely a perpetually failing task.
> ```

Set the HTTP response code to something different in this case to distinguish it from the `200` response that would indicate total success.  Maybe `202` is suitable?  This should still cause App Engine task queue to not retry, but will have a different status code we could e.g. search out in the logs.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 173 at r4](https://reviewable.io/reviews/google/nomulus/1664#-N5FxszW8x7XS592WJ2c:-N5FxszW8x7XS592WJ2d:bdkxu4g) ([raw file](https://github.com/google/nomulus/blob/2fcf73ebfcac1cb42933265a259ad8d7adffe30f/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L173)):*
> ```Java
>         throw e;
>       }
>       // If we get here, we should terminate this task as it is likely a perpetually failing task.
> ```

There's a missing log statement here.  Log the permanently failed task at `SEVERE`.


<!-- Sent from Reviewable.io -->

2022-07-01 17:56 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @CydeWeys, @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 173 at r4](https://reviewable.io/reviews/google/nomulus/1664#-N5Fwx_PAXVLnCoL9YR5:-N5usYvf09tzJvhtUSkK:b-82l2x9) ([raw file](https://github.com/google/nomulus/blob/2fcf73ebfcac1cb42933265a259ad8d7adffe30f/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L173)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I could not figure out how to set a specific response code, but I added a new action status "TIMED_OUT" that is recorded here.
</blockquote></details>

See https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/Response.java;l=29;bpv=1;bpt=1?q=response.setstatus&ss=nomulus%2Fnomulus

`response.setStatus()` is a common pattern across our codebase with many invocations.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 127 at r7](https://reviewable.io/reviews/google/nomulus/1664#-N5us6anBpXrrhboqfIT:-N5us6anBpXrrhboqfIU:bjpfvsu) ([raw file](https://github.com/google/nomulus/blob/4d32b71841e3c8f9c698f2d90fcdd198b5dbcffb/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L127)):*
> ```Java
>     this.dnsMetrics = dnsMetrics;
>     this.timeout = timeout;
>     this.appEngineRetryCount = appEngineRetryCount;
> ```

I think you can handle the logic here.  Rather than having two member fields, `appEngineRetryCount` and `cloudTasksRetryCount`, and having to choose between them each time one is used, just have one local variable set as follows:

`this.retryCount = cloudTasksRetryCount.orElse(appEngineRetryCount)`

(and see below on comment for making the headers `Optional`)
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 211 at r7](https://reviewable.io/reviews/google/nomulus/1664#-N5utTcf3ik5GQ8Di8gK:-N5utTcf3ik5GQ8Di8gL:b-fgzw67) ([raw file](https://github.com/google/nomulus/blob/4d32b71841e3c8f9c698f2d90fcdd198b5dbcffb/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L211)):*
> ```Java
>       // TODO(b/237302821): Send an email notifying partner the dns update failed
>       recordActionResult(ActionStatus.TIMED_OUT);
>       logger.atSevere().log("Terminated task after too many retries");
> ```

You are missing `.withCause(e)`.  Whenever there is a relevant exception to log, it should always be logged.  As written you are still swallowing the exception and never logging its actual contents.

As a general rule of thumb, if there's a log messages inside a `catch` block it should always log the exception unless the exception is being re-thrown.
___
*[`core/src/main/java/google/registry/request/RequestModule.java` line 254 at r7](https://reviewable.io/reviews/google/nomulus/1664#-N5urmtqBBxJzyOpepoL:-N5urmtqBBxJzyOpepoM:b-5sod7y) ([raw file](https://github.com/google/nomulus/blob/4d32b71841e3c8f9c698f2d90fcdd198b5dbcffb/core/src/main/java/google/registry/request/RequestModule.java#L254)):*
> ```Java
>   @Provides
>   @Header(APP_ENGINE_RETRY_HEADER)
>   static int provideAppEngineRetryCount(HttpServletRequest req) {
> ```

Why isn't this returning `Optional<Integer>`?  Same for the one below.  It doesn't make sense to me to default these to 0.

Then at the callsite that uses these it'd simply be `cloudTasksRetryCount.orElse(appEngineRetryCount)`


<!-- Sent from Reviewable.io -->

2022-07-06 17:11 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 214 at r8](https://reviewable.io/reviews/google/nomulus/1664#-N6JTX97-qXrspEoRsDo:-N6JTX97-qXrspEoRsDp:ba3ms18) ([raw file](https://github.com/google/nomulus/blob/70f6cca54702b85954959c74036543f0c11014fc/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L214)):*
> ```Java
>       // If we get here, we should terminate this task as it is likely a perpetually failing task.
>       // TODO(b/237302821): Send an email notifying partner the dns update failed
>       recordActionResult(ActionStatus.TIMED_OUT);
> ```

`TIMED_OUT` doesn't quite convey the correct thing to me.  It's not that this task has timed out (Cloud DNS API calls can time out, but that's not what's going on here).  What's happened is that the task has permanently failed after too many retries, which is typically caused by the task itself containing invalid DS data that will cause failures from the Cloud DNS API regardless of how many times it's retried.  This isn't a time out.

So something like `PERMANENT_FAILURE` or `PERMANENT_FAILURE_MAX_RETRIES_ATTEMPTED` seems like it would encapsulate the correct meaning here, and fit in naming-wise with the other existing values of `ActionStatus`.  The latter might be too verbose.


<!-- Sent from Reviewable.io -->

2022-07-07 21:16 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @CydeWeys, @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/request/RequestModule.java` line 257 at r9](https://reviewable.io/reviews/google/nomulus/1664#-N6PVzvf8l8usUkGzpkG:-N6PVzvf8l8usUkGzpkH:b-r25in5) ([raw file](https://github.com/google/nomulus/blob/077d9b5bb1241645a9b30404a8616881ae0ef7a1/core/src/main/java/google/registry/request/RequestModule.java#L257)):*
> ```Java
>   static Optional<Integer> provideAppEngineRetryCount(HttpServletRequest req) {
>     return extractOptionalHeader(req, APP_ENGINE_RETRY_HEADER)
>         .map(s -> Optional.of(Integer.parseInt(s)))
> ```

You're not using `map()` correctly here.  See documentations and other examples in our codebase.  This can be written more succinctly as:

```
return extractOptionalHeader(req, APP_ENGINE_RETRY_HEADER).map(Integer::parseInt)
```

Note that `map()` is already doing the work of returning an empty `Optional` if the `Optional` it's called on is already empty.



_Code quote:_
```Java
    return extractOptionalHeader(req, APP_ENGINE_RETRY_HEADER)
        .map(s -> Optional.of(Integer.parseInt(s)))
        .orElse(Optional.empty());
```
___
*[`core/src/main/java/google/registry/request/RequestModule.java` line 264 at r9](https://reviewable.io/reviews/google/nomulus/1664#-N6PWF33EnINlYn-Ga3-:-N6PWF33EnINlYn-Ga30:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/077d9b5bb1241645a9b30404a8616881ae0ef7a1/core/src/main/java/google/registry/request/RequestModule.java#L264)):*
> ```Java
>   @Header(CLOUD_TASKS_RETRY_HEADER)
>   static Optional<Integer> provideCloudTasksRetryCount(HttpServletRequest req) {
>     return extractOptionalHeader(req, CLOUD_TASKS_RETRY_HEADER)
> ```

Ditto.


<!-- Sent from Reviewable.io -->

2022-07-07 21:16 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @CydeWeys, @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/request/RequestModule.java` line 257 at r9](https://reviewable.io/reviews/google/nomulus/1664#-N6PVzvf8l8usUkGzpkG:-N6PWQ1H0RgKX8XOO8aF:be4ty2y) ([raw file](https://github.com/google/nomulus/blob/077d9b5bb1241645a9b30404a8616881ae0ef7a1/core/src/main/java/google/registry/request/RequestModule.java#L257)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You're not using `map()` correctly here.  See documentations and other examples in our codebase.  This can be written more succinctly as:

```
return extractOptionalHeader(req, APP_ENGINE_RETRY_HEADER).map(Integer::parseInt)
```

Note that `map()` is already doing the work of returning an empty `Optional` if the `Optional` it's called on is already empty.
</blockquote></details>

I highly recommend reading the relevant Javadocs in this and all other circumstances: https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#map-java.util.function.Function-


<!-- Sent from Reviewable.io -->

2022-07-07 21:19 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 214 at r8](https://reviewable.io/reviews/google/nomulus/1664#-N6JTX97-qXrspEoRsDo:-N6PWpwq4tLz2IwAXtZs:bndhmun) ([raw file](https://github.com/google/nomulus/blob/70f6cca54702b85954959c74036543f0c11014fc/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L214)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ugh, sorry to come back to this, but I think `MAX_RETRIES_EXCEEDED` is actually the best possible name for this, and the verbiage that is most widely used in our industry.  It's more descriptive than "permanent failure" too.  Naming things is hard.


<!-- Sent from Reviewable.io -->

2022-07-11 17:14 UTC, gbrodman approved these changes
> Reviewed 1 of 4 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @jianglai)



<!-- Sent from Reviewable.io -->

2022-07-18 18:50 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 130 at r10](https://reviewable.io/reviews/google/nomulus/1664#-N7GlHCCDaCmtVaIu4ZW:-N7Hd709EdqyEmvjT10B:brj0wad) ([raw file](https://github.com/google/nomulus/blob/87521ef7b7fc1e54732393d27a034ed29ecdb777/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L130)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

This might cause intended issues if one accidentally sets the cloud tasks retry header before we switch away from app engine. Maybe we should just hardcode to use app engine retry header now. We will have to remember to switch the header to set when the runtime changes, so it's not likely that we'd forget to change where header to look for here.
</blockquote></details>

This is not a header we're using, this is a header that GCP uses.  I don't see what the problem is?  Is the concern that both might be present somehow?


<!-- Sent from Reviewable.io -->

2022-07-18 18:51 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once use of `CloudTasksHelper` is addresssed.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664#-:-N7HdXCeC2ywS5h8Z9Uk:bz2gb4x)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2022-07-18 20:42 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 130 at r10](https://reviewable.io/reviews/google/nomulus/1664#-N7GlHCCDaCmtVaIu4ZW:-N7I1djQEb2uTORlne6L:bmgbrw6) ([raw file](https://github.com/google/nomulus/blob/87521ef7b7fc1e54732393d27a034ed29ecdb777/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L130)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is not a header we're using, this is a header that GCP uses.  I don't see what the problem is?  Is the concern that both might be present somehow?
</blockquote></details>

Hmm, I think you are right. I don't believe GCP would set both headers. If we use the Task Queue API, it would only set the app engine header. If we use the Cloud Tasks API, depending on whether we are creating an app engine task, or a generic HTTP task, it should use the corresponding header.


<!-- Sent from Reviewable.io -->

2022-07-25 13:04 UTC, jianglai approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1664)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys and @gbrodman)



<!-- Sent from Reviewable.io -->

2022-07-25 14:45 UTC, merged