Add email notification when DNS update fails
google/nomulus pull request #1734
Opened 2022-08-05 13:07 UTC by ptkach

I will update email template once I hear back about the text that should go there.

2022-08-05 15:59 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1734)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ptkach and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 225 at r1](https://reviewable.io/reviews/google/nomulus/1734#-N8ihV7mB-p58INAur58:-N8ihV7mB-p58INAur59:b-79odbh) ([raw file](https://github.com/google/nomulus/blob/f0c9eca28cd0f7fadcc724b7f8190c4d739d6de7/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L225)):*
> ```Java
>         throw e;
>       } else {
>         domains.stream()
> ```

It's worth pointing out that, by the time we get to this point, there is either a single domain or a single host that is failing.  Might be worth leaving a comment at least, lest people think that we might be sending lots of emails here all at once (because if we were doing so, the logical thing would be to group the emails by registrar).
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 272 at r1](https://reviewable.io/reviews/google/nomulus/1734#-N8iiBBd2axnh8Jb7V3Z:-N8iiBBd2axnh8Jb7V3_:b1tro2x) ([raw file](https://github.com/google/nomulus/blob/f0c9eca28cd0f7fadcc724b7f8190c4d739d6de7/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L272)):*
> ```Java
> 
>     sendEmailUtils.sendEmail(
>         "Subj",
> ```

Per your review comment, these are placeholders that need to be filled in.  You're going to want to create new configuration entries in `RegistryConfig` (which ultimately flows through from the YAML config files).  We have examples of other emails that work in this manner.  Also note that the specific configuration text is going to need to go into the other repo `nomulus-internal`.

Also note that you'll need to include the failing domain/host name in the email body, so the configured body should be a String template (i.e. include a `%s` in it).


<!-- Sent from Reviewable.io -->

2022-08-05 16:01 UTC, CydeWeys reviewed
BTW, I know it's not the approach you went for on this PR, but for future knowledge, here's what enqueuing a poll message looks like (including construction of the requisite history entry): https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/tools/EnqueuePollMessageCommand.java;l=105-126?q=enqueuepoll&ss=nomulus%2Fnomulus

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1734#-:-N8ij7jj9dxnj1TltHR8:b9cjjeh)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ptkach and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2022-08-12 04:06 UTC, jianglai requested changes
> Reviewed 3 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1734)* status: all files reviewed, 11 unresolved discussions (waiting on @CydeWeys and @ptkach)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 482 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CnyQB78n5xJFTYD7w:-N9CnyQB78n5xJFTYD7x:b2nhcro) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L482)):*
> ```YAML
> # Configuration options relevant to the dns update functionality.
> dnsUpdate:
>   # Email subject text template to notify partners after repeatedly failing dns update
> ```

DNS



_Code quote:_
```YAML
dns
```
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 489 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CoWDRC5CLhqSn-7dh:-N9CoWDS4eUj4S9ywkeK:bj64oum) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L489)):*
> ```YAML
>     Dear %1$s,
> 
>     We are contacting you regarding the changes you recently made to one of your %2$ss. 
> ```

Remove the trailing whitespaces here and below.



_Code quote:_
```YAML
·
```
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 490 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CojdI330TErHdJyP4:-N9CojdI330TErHdJyP5:b-8dsoqq) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L490)):*
> ```YAML
> 
>     We are contacting you regarding the changes you recently made to one of your %2$ss. 
>     The DNS update for the %3$s %2$s failed to process. Please review your %2$s's DS data 
> ```

Is it only DS record that needs to be examined? The update can fail for other records, right?



_Code quote:_
```YAML
DS data
```
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 494 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CosDbADOukzNJDOgd:-N9CosDbADOukzNJDOge:b-o6dj34) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L494)):*
> ```YAML
> 
>     If you have any questions or require additional support, please contact us 
>     at registry-support@google.com.
> ```

This needs to be a parameter as well.



_Code quote:_
```YAML
registry-support@google.com
```
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 497 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9Cov9iAzARZuUlmwPk:-N9Cov9iAzARZuUlmwPl:b-1ec2im) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L497)):*
> ```YAML
> 
>     Regards,
>     Google Registry
> ```

And this.



_Code quote:_
```YAML
Google Registry
```
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 225 at r1](https://reviewable.io/reviews/google/nomulus/1734#-N8ihV7mB-p58INAur58:-N9D3UlZ3HDM5XFV5Kgj:bwd7647) ([raw file](https://github.com/google/nomulus/blob/f0c9eca28cd0f7fadcc724b7f8190c4d739d6de7/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L225)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It's worth pointing out that, by the time we get to this point, there is either a single domain or a single host that is failing.  Might be worth leaving a comment at least, lest people think that we might be sending lots of emails here all at once (because if we were doing so, the logical thing would be to group the emails by registrar).
</blockquote></details>

If there's only one domain/host, why don't we call the `.get(0)` method?
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 114 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9Cp4jN018lIDua9D3k:-N9Cp4jN018lIDua9D3l:bxp7u0x) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L114)):*
> ```Java
>   private final Response response;
>   private final SendEmailUtils sendEmailUtils;
> ```

Remove the empty line.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 252 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9D3mXm2v_lfOo9ULX7:-N9D3mXm2v_lfOo9ULX8:b4gxggv) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L252)):*
> ```Java
>   }
> 
>   private String getRegistrarIdByHostName(String hostName) {
> ```

There doesn't seem to be a need to have these two helper methods. You can just call them in place.



_Code quote:_
```Java
  private String getRegistrarIdByHostName(String hostName) {
    Host host =
        loadByForeignKey(Host.class, hostName, clock.nowUtc())
            .orElseThrow(
                () ->
                    new NotFoundException(String.format("Host entity for %s not found", hostName)));

    return host.getPersistedCurrentSponsorRegistrarId();
  }

  private String getRegistrarIdByDomainName(String domainName) {
    Domain domain =
        loadByForeignKey(Domain.class, domainName, clock.nowUtc())
            .orElseThrow(
                () ->
                    new NotFoundException(
                        String.format("Domain entity for %s not found", domainName)));

    return domain.getCurrentSponsorRegistrarId();
  }
```
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 280 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9D57kiBUNwZ-YVhhln:-N9D57kiBUNwZ-YVhhlo:b963mom) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L280)):*
> ```Java
>             .orElseThrow(
>                 () ->
>                     new IllegalArgumentException(
> ```

What is going to happen to all these exceptions thrown here (and above when loading the domain/host)? Would it cause a non-2XX response to be sent and therefore trigger another retry in Cloud Tasks? @sarahcaseybot 


<!-- Sent from Reviewable.io -->

2022-08-12 16:04 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1734)* status: 0 of 5 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 482 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CnyQB78n5xJFTYD7w:-N9HlhCfB014Fn5PLIFV:b-896fix) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L482)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

DNS
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 489 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CoWDRC5CLhqSn-7dh:-N9HlhzP-1rLdTtRoN4Y:b-896fix) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L489)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Remove the trailing whitespaces here and below.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 490 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CojdI330TErHdJyP4:-N9Hlkbb-pvOsOO_5EQ3:b-a4aq8q) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L490)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is it only DS record that needs to be examined? The update can fail for other records, right?
</blockquote></details>

According to Ben it's only DS record that fails, see b/201311174
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 494 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CosDbADOukzNJDOgd:-N9Hly1s5HjtgGHF0sIC:b-896fix) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L494)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

This needs to be a parameter as well.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 497 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9Cov9iAzARZuUlmwPk:-N9Hlyz0Aa-h3syfndKf:b-896fix) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L497)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

And this.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 225 at r1](https://reviewable.io/reviews/google/nomulus/1734#-N8ihV7mB-p58INAur58:-N9Hm-xVC9z9kvnWNd-u:b-w73bwh) ([raw file](https://github.com/google/nomulus/blob/f0c9eca28cd0f7fadcc724b7f8190c4d739d6de7/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L225)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

If there's only one domain/host, why don't we call the `.get(0)` method?
</blockquote></details>

there's no get(0) on a set, so shortest and more "functional" was foreach
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 272 at r1](https://reviewable.io/reviews/google/nomulus/1734#-N8iiBBd2axnh8Jb7V3Z:-N9Hn6sjBKf5Rh_myWlt:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f0c9eca28cd0f7fadcc724b7f8190c4d739d6de7/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L272)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Per your review comment, these are placeholders that need to be filled in.  You're going to want to create new configuration entries in `RegistryConfig` (which ultimately flows through from the YAML config files).  We have examples of other emails that work in this manner.  Also note that the specific configuration text is going to need to go into the other repo `nomulus-internal`.

Also note that you'll need to include the failing domain/host name in the email body, so the configured body should be a String template (i.e. include a `%s` in it).
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 262 at r2](https://reviewable.io/reviews/google/nomulus/1734#-N8jQOv94tbAKVLDzPw6:-N9HmPng3mMvzwfHzcUd:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e3b28428ebaafc84bbf6600e48f4207bf24d7244/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L262)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Should also pass in the domain or host that failed to update to include in the email message.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 114 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9Cp4jN018lIDua9D3k:-N9HlzyR-2Gavu1_E8XT:b-896fix) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L114)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Remove the empty line.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 252 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9D3mXm2v_lfOo9ULX7:-N9HmP041bCylttC_9_v:b-896fix) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L252)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

There doesn't seem to be a need to have these two helper methods. You can just call them in place.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 280 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9D57kiBUNwZ-YVhhln:-N9HmSWY-RUrhP3vxQ-Q:b-9xi09o) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L280)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

What is going to happen to all these exceptions thrown here (and above when loading the domain/host)? Would it cause a non-2XX response to be sent and therefore trigger another retry in Cloud Tasks? @sarahcaseybot 
</blockquote></details>

As far as i understand original intend here by @sarahcaseybot it shouldn't be retriggered as it's not being added to the queue again 


<!-- Sent from Reviewable.io -->

2022-08-12 18:47 UTC, jianglai requested changes
> Reviewed 3 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1734)* status: all files reviewed, 8 unresolved discussions (waiting on @CydeWeys, @jianglai, @ptkach, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 482 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CnyQB78n5xJFTYD7w:-N9ILPcgCAyy0zstk4Gc:b-3aekc5) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L482)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not really :D it's still "dns" instead of "DNS".
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 490 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CojdI330TErHdJyP4:-N9IMeedBe4aG8amoWdP:b-an5yly) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L490)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

According to Ben it's only DS record that fails, see b/201311174
</blockquote></details>

I don't think he meant that only DS record fails can lead to this. In this specific case it was bad DS data that resulted in DNS update failures, but in general any bad data that passed our validation but failed the DNS server's can lead to this.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 225 at r1](https://reviewable.io/reviews/google/nomulus/1734#-N8ihV7mB-p58INAur58:-N9INDwbCjfrP6ZtIclw:bf8txa7) ([raw file](https://github.com/google/nomulus/blob/f0c9eca28cd0f7fadcc724b7f8190c4d739d6de7/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L225)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

there's no get(0) on a set, so shortest and more "functional" was foreach
</blockquote></details>

You can use `set.stream().findFirst().get()`.


<!-- Sent from Reviewable.io -->

2022-08-12 21:25 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1734)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 482 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CnyQB78n5xJFTYD7w:-N9Igb_1CwCR2qMYBGIL:b-go0b2u) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L482)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Not really :D it's still "dns" instead of "DNS".
</blockquote></details>

Done. There was multiple apparently
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 490 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CojdI330TErHdJyP4:-N9IwWNI1vC2uabKmOjL:bmzrdr9) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L490)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I don't think he meant that only DS record fails can lead to this. In this specific case it was bad DS data that resulted in DNS update failures, but in general any bad data that passed our validation but failed the DNS server's can lead to this.
</blockquote></details>

I have removed "DS" for now, let me know if you envision some other way to cover that
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 482 at r6](https://reviewable.io/reviews/google/nomulus/1734#-N9IBBoc4cJ_JmgzRaZI:-N9IPpnYB2LAU8GbP-wC:b-ankt5p) ([raw file](https://github.com/google/nomulus/blob/d3be5e6319bc746e56e22e40e5ae56e8e5912abf/core/src/main/java/google/registry/config/files/default-config.yaml#L482)):*
> registrySupportEmail
I first thought so too, but there's already a provider with this name and the same return type, so I figured I will make it more specific
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 483 at r6](https://reviewable.io/reviews/google/nomulus/1734#-N9IBJmo8tRAFWiExIOI:-N9IwISCDMuqIhO1hkua:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d3be5e6319bc746e56e22e40e5ae56e8e5912abf/core/src/main/java/google/registry/config/files/default-config.yaml#L483)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

can just be registrySupportEmail
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 225 at r1](https://reviewable.io/reviews/google/nomulus/1734#-N8ihV7mB-p58INAur58:-N9Iwef557LbXkHfl4sf:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f0c9eca28cd0f7fadcc724b7f8190c4d739d6de7/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L225)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

You can use `set.stream().findFirst().get()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-14 12:53 UTC, jianglai approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1734)* status: all files reviewed, 8 unresolved discussions (waiting on @CydeWeys, @ptkach, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 490 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CojdI330TErHdJyP4:-N9RP-FKEX3kr2iEWgbw:b6xxeg1) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L490)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I have removed "DS" for now, let me know if you envision some other way to cover that
</blockquote></details>

Let's use "DNS records" here. "data" to a little to broad.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 190 at r7](https://reviewable.io/reviews/google/nomulus/1734#-N9RP8uOC2ty6XdmKp-S:-N9RP8uOC2ty6XdmKp-T:borp4jl) ([raw file](https://github.com/google/nomulus/blob/e796f3ddc360ac421c6a059861dc2e7022960785/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L190)):*
> ```Java
>         new Duration(enqueuedTime, now));
>   }
> ```

Remove extra newline.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 239 at r7](https://reviewable.io/reviews/google/nomulus/1734#-N9RPIzeDwRBboClKpoL:-N9RPIzeDwRBboClKpoM:b-ilkrfe) ([raw file](https://github.com/google/nomulus/blob/e796f3ddc360ac421c6a059861dc2e7022960785/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L239)):*
> ```Java
>         domains.stream()
>             .findFirst()
>             .ifPresent(
> ```

Based on the comment above, I think we can call `.get()` directly here.



_Code quote:_
```Java
.ifPresent(
```


<!-- Sent from Reviewable.io -->

2022-08-15 15:45 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1734)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 490 at r5](https://reviewable.io/reviews/google/nomulus/1734#-N9CojdI330TErHdJyP4:-N9XACMS2F0HDYVWGij4:b-896fix) ([raw file](https://github.com/google/nomulus/blob/96a05ad0717e5881aed7a2d0698508de1056bb0d/core/src/main/java/google/registry/config/files/default-config.yaml#L490)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Let's use "DNS records" here. "data" to a little to broad.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 190 at r7](https://reviewable.io/reviews/google/nomulus/1734#-N9RP8uOC2ty6XdmKp-S:-N9XADxl2z_1qV351kKF:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e796f3ddc360ac421c6a059861dc2e7022960785/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L190)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Remove extra newline.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 239 at r7](https://reviewable.io/reviews/google/nomulus/1734#-N9RPIzeDwRBboClKpoL:-N9XAFe80CkYxI_lLdvq:b-inqf3k) ([raw file](https://github.com/google/nomulus/blob/e796f3ddc360ac421c6a059861dc2e7022960785/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L239)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Based on the comment above, I think we can call `.get()` directly here.
</blockquote></details>

As discussed in chat ifPresent suits better as it's either domain or host that fails


<!-- Sent from Reviewable.io -->

2022-08-16 01:06 UTC, jianglai approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1734)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2022-08-16 16:59 UTC, merged