Add registry email to bcc for outgoing DNS failure emails
google/nomulus pull request #1755
Opened 2022-08-22 21:58 UTC by ptkach

This adds registry support email to bcc for when DNS failure occurs and we send DNS failure emails. This should help us to track how many and what kind of emails are getting sent by us and make sure partners don't get flooded with emails.

2022-08-23 14:59 UTC, jianglai requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1755)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 143 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAAAxiwASmcivejY8Oh:-NAAAxiwASmcivejY8Oi:bh0brhj) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L143)):*
> ```Java
>       Clock clock,
>       CloudTasksUtils cloudTasksUtils,
>       SendEmailService sendEmailService,
> ```

This is probably the better way as `SendEmailUtils` seems to be only used in the UI backend.



_Code quote:_
```Java
 SendEmailService sendEmailService
```
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 281 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABNQVA352YyIP4kFZ:-NAABNQW4lLsUkn_-qrB:b-nlchtd) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L281)):*
> ```Java
>           String.format(
>               "Could not parse email contact %s to send DNS failure notification", email));
>       return null;
> ```

Is it going to be a problem if we pass `null` to `SendEmailService`?

I think we should just inject `InternetAddress` for `registrySupportEmail` and `registryCcemail`, like how `gSuiteOutgoingEmailAddress` is injected.



_Code quote:_
```Java
return null;
```
___
*[`core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABXw43I_yHrBV8jFi:-NAABXw43I_yHrBV8jFj:b-4r2mha) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java#L139)):*
> ```Java
>     try {
>       outgoingRegistry = new InternetAddress("outgoing@registry.example");
>     } catch (Exception e) {
> ```

I'm not sure what this does? You could just add `throws Exception` to the function signature. It is OK to not handle exceptions in tests when you know the exception will not be thrown. We do this all the time in tests to save having to write all the try-catch blocks.



_Code quote:_
```Java
    } catch (Exception e) {
      System.out.println("");
    }
```


<!-- Sent from Reviewable.io -->

2022-08-23 15:38 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1755)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 143 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAAAxiwASmcivejY8Oh:-NAADPHdARJrs1FmfNMQ:b66s4da) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L143)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

This is probably the better way as `SendEmailUtils` seems to be only used in the UI backend.
</blockquote></details>

Yeah, I agree, with bcc requirement "util" is not a fit anymore. 
___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 281 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABNQVA352YyIP4kFZ:-NAAEZ378IgPzWaB1U0k:b-yd5eh1) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L281)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is it going to be a problem if we pass `null` to `SendEmailService`?

I think we should just inject `InternetAddress` for `registrySupportEmail` and `registryCcemail`, like how `gSuiteOutgoingEmailAddress` is injected.
</blockquote></details>

No, it shouldn't be a problem, this is essentially what SendEmailUtils does under the hood when converting 
___
*[`core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABXw43I_yHrBV8jFi:-NAADkt1AtdiuwNwMLAq:bijk3l9) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java#L139)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I'm not sure what this does? You could just add `throws Exception` to the function signature. It is OK to not handle exceptions in tests when you know the exception will not be thrown. We do this all the time in tests to save having to write all the try-catch blocks.
</blockquote></details>

Unfortunately simple "throws" to the function is not gonna do the trick as then it also requires updates across all the places that call this function to either handle or throw and so on. I figured, it's guaranteed not to throw and probably the shortest way to handle it is this.


<!-- Sent from Reviewable.io -->

2022-08-23 18:43 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1755)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 55 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAA_zIp6-RWxQTk8q4Q:-NAB00EpBsCkdymmfil7:b-886gsx) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L55)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Don't use wildcard imports - see Java style guide: go/java-style#s3.3.1-wildcard-imports
</blockquote></details>

Fixed
___
*[`core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABXw43I_yHrBV8jFi:-NAB-yqK2Clbfc5n2lT0:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java#L139)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I agree with Lai, you should change each of the tests that call createAction to have `throws Exception` in the function signature
</blockquote></details>

Updated


<!-- Sent from Reviewable.io -->

2022-08-23 20:48 UTC, jianglai requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1755)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 281 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABNQVA352YyIP4kFZ:-NABRPpF-zljgWQ0592N:botv8xk) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L281)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

No, it shouldn't be a problem, this is essentially what SendEmailUtils does under the hood when converting 
</blockquote></details>

Still, is there a reason not to inject an `InternetAddress`? We already have a [parseEmailClass](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/config/RegistryConfig.java;drc=6dd96c247a78e8f1ea26a77628d003c794fe71b1;l=1570?q=registryconfig&ss=nomulus%2Fnomulus) method in `RegistryConfig` to do exactly this.
___
*[`core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABXw43I_yHrBV8jFi:-NABSOD9BtKA3UaCPvNR:b3ovcx5) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java#L139)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Updated
</blockquote></details>

You can create the `InternetAccess` in a `@BeforeEach` method (with `throws Exception`) and use it here, this way you don't have to add `throws Exception` to every test methods.


<!-- Sent from Reviewable.io -->

2022-08-23 22:49 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1755)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 281 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABNQVA352YyIP4kFZ:-NABpccR91MR3tTJ2-UW:bns2umt) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L281)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Still, is there a reason not to inject an `InternetAddress`? We already have a [parseEmailClass](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/config/RegistryConfig.java;drc=6dd96c247a78e8f1ea26a77628d003c794fe71b1;l=1570?q=registryconfig&ss=nomulus%2Fnomulus) method in `RegistryConfig` to do exactly this.
</blockquote></details>

registrySupportEmail is not used as InternetAddress, it's used as a String in email template, so it has to stay as is. Recipients is derived from registrar contacts, which is a String, so transformation in this class is still necessary (unless we expose  parseEmailClass). To sum it up only registryCcemail that can currently be injected as InternetAddress, but on a flip side it will cause a transformation being done ahead of time, wasting computation, unless we do it lazy. Please let me know if you think it's necessary and I will update. 
___
*[`core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABXw43I_yHrBV8jFi:-NABtOKYCMMEHd525j4X:bdcv6kv) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java#L139)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

You can create the `InternetAccess` in a `@BeforeEach` method (with `throws Exception`) and use it here, this way you don't have to add `throws Exception` to every test methods.
</blockquote></details>

Good point!


<!-- Sent from Reviewable.io -->

2022-08-24 14:05 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1755)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai, @ptkach, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 281 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABNQVA352YyIP4kFZ:-NAF8iSC29HWka66jXQx:b-l4e3nn) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L281)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

registrySupportEmail is not used as InternetAddress, it's used as a String in email template, so it has to stay as is. Recipients is derived from registrar contacts, which is a String, so transformation in this class is still necessary (unless we expose  parseEmailClass). To sum it up only registryCcemail that can currently be injected as InternetAddress, but on a flip side it will cause a transformation being done ahead of time, wasting computation, unless we do it lazy. Please let me know if you think it's necessary and I will update. 
</blockquote></details>

It actually might not be a bad idea to inject registrySupportEmail as an `InternetAddress` precisely because it does validation on the address. You can then call `InternetAddress.getAddress()` to get the string.

The transformation should be pretty lightweight, but good point on not wasting resources when we don't have to. We can lazy inject all three of them.



_Code quote:_
```Java
javax.mail.internet.InternetAddress
```


<!-- Sent from Reviewable.io -->

2022-08-24 21:49 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1755)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java` line 281 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABNQVA352YyIP4kFZ:-NAGp2PG8kRZhZQmnMOI:b7c0akr) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java#L281)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It actually might not be a bad idea to inject registrySupportEmail as an `InternetAddress` precisely because it does validation on the address. You can then call `InternetAddress.getAddress()` to get the string.

The transformation should be pretty lightweight, but good point on not wasting resources when we don't have to. We can lazy inject all three of them.
</blockquote></details>

There's just 2 to inject, which I've now updated as per your suggestion. Done!
___
*[`core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/1755#-NAABXw43I_yHrBV8jFi:-NAGpBTJ7dFrtb-ApyUx:b-896fja) ([raw file](https://github.com/google/nomulus/blob/a9c602e86247cfc1f8d32a7eb5acda1f06252ed2/core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java#L139)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Good point!
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2022-08-25 03:30 UTC, jianglai approved these changes
Remember to change the corresponding file in the private repo.

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1755#-:-NAI2EJz92EMG_mMRNpw:b-q43iho)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2022-08-25 18:15 UTC, merged