Add a packageToken EPP extension for use in the DomainInfo flow
google/nomulus pull request #1760
Opened 2022-08-25 19:20 UTC by sarahcaseybot

2022-08-26 20:08 UTC, gbrodman reviewed
re: ben's comments on https://reviewable.io/reviews/google/nomulus/1758#-, we might not want to do this after all, sorry sarah :/ 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1760#-:-NAQlE_S2_rXjbl3lPH6:bts1w7h)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @ptkach)



<!-- Sent from Reviewable.io -->

2022-08-29 16:32 UTC, gbrodman requested changes
ok, disregarding my comment (different type of action) 

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1760#-:-NAeLL3V6ltsOhbeJ0N8:bu2k8m8)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @ptkach, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainInfoFlow.java` line 159 at r1](https://reviewable.io/reviews/google/nomulus/1760#-NAeN3ZN0Dh1VmmXeFlH:-NAeN3ZN0Dh1VmmXeFlI:b-6lmus5) ([raw file](https://github.com/google/nomulus/blob/3d0b732aa7df4b74e5558125ade98e5d9c092221/core/src/main/java/google/registry/flows/domain/DomainInfoFlow.java#L159)):*
> ```Java
>     if (packageInfo.isPresent()) {
>       // Package info was requested.
>       if (registrarId.equals(domain.getCurrentSponsorRegistrarId())) {
> ```

Should also allow this if the user is a superuser (and corresponding test)
___
*[`core/src/main/java/google/registry/model/domain/packagetoken/PackageTokenResponseExtension.java` line 35 at r1](https://reviewable.io/reviews/google/nomulus/1760#-NAePKsUAfcUAwVwlHUg:-NAePKsUAfcUAwVwlHUh:btgh5v2) ([raw file](https://github.com/google/nomulus/blob/3d0b732aa7df4b74e5558125ade98e5d9c092221/core/src/main/java/google/registry/model/domain/packagetoken/PackageTokenResponseExtension.java#L35)):*
> ```Java
>  */
> @XmlRootElement(name = "packageData")
> @XmlType(propOrder = {"token"})
> ```

what happens if we remove the propOrder? I would expect with one element the order doesn't really matter
___
*[`core/src/main/java/google/registry/model/domain/packagetoken/PackageTokenResponseExtension.java` line 39 at r1](https://reviewable.io/reviews/google/nomulus/1760#-NAePUDg1Xs0q3-P0hyL:-NAePUDg1Xs0q3-P0hyM:b-cq41zn) ([raw file](https://github.com/google/nomulus/blob/3d0b732aa7df4b74e5558125ade98e5d9c092221/core/src/main/java/google/registry/model/domain/packagetoken/PackageTokenResponseExtension.java#L39)):*
> ```Java
> 
>   /** Token string of the PACKAGE token the name belongs to. */
>   @XmlElement(name = "token")
> ```

similarly, I think the name can likely be omitted here as well
___
*[`core/src/main/java/google/registry/model/domain/packagetoken/PackageTokenResponseExtension.java` line 47 at r1](https://reviewable.io/reviews/google/nomulus/1760#-NAeQdaF9H6vps1kY900:-NAeQdaF9H6vps1kY901:b-hv4ylu) ([raw file](https://github.com/google/nomulus/blob/3d0b732aa7df4b74e5558125ade98e5d9c092221/core/src/main/java/google/registry/model/domain/packagetoken/PackageTokenResponseExtension.java#L47)):*
> ```Java
>     instance.token = "";
>     if (tokenKey.isPresent()) {
>       instance.token = tm().transact(() -> tm().loadByKey(tokenKey.get())).getToken();
> ```

The token VKey is just the token as far as I know, so we shouldn't need to do a DB load 
___
*[`core/src/main/java/google/registry/xml/xsd/packageToken.xsd` line 3 at r1](https://reviewable.io/reviews/google/nomulus/1760#-NAeRFsk-yi8a9blnkum:-NAeRFsk-yi8a9blnkun:b-yg0rj2) ([raw file](https://github.com/google/nomulus/blob/3d0b732aa7df4b74e5558125ade98e5d9c092221/core/src/main/java/google/registry/xml/xsd/packageToken.xsd#L3)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> 
> <schema targetNamespace="urn:ietf:params:xml:ns:packageToken"
> ```

I might ask Ben to comment here about the XML namespacing -- is it necessary / desirable to have the `ietf:params:xml:ns:` prefix to the packageToken naming? My primary hesitation would be if there's some sort of pre-existing set of "allowed" names that fall into the ietf... namespacing and this isn't one of them. 


<!-- Sent from Reviewable.io -->

2022-08-29 20:29 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1760)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman, @ptkach, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/domain/packagetoken/PackageTokenResponseExtension.java` line 47 at r1](https://reviewable.io/reviews/google/nomulus/1760#-NAeQdaF9H6vps1kY900:-NAfHOMQCwHd1j6t0NQu:bmr94d4) ([raw file](https://github.com/google/nomulus/blob/3d0b732aa7df4b74e5558125ade98e5d9c092221/core/src/main/java/google/registry/model/domain/packagetoken/PackageTokenResponseExtension.java#L47)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

The token VKey is just the token as far as I know, so we shouldn't need to do a DB load 
</blockquote></details>

Agreed, the extension itself shouldn't be eagerly loading tokens.
___
*[`core/src/main/java/google/registry/xml/xsd/packageToken.xsd` line 3 at r1](https://reviewable.io/reviews/google/nomulus/1760#-NAeRFsk-yi8a9blnkum:-NAfHdjkE-KgeGwXmnnT:bgxnylb) ([raw file](https://github.com/google/nomulus/blob/3d0b732aa7df4b74e5558125ade98e5d9c092221/core/src/main/java/google/registry/xml/xsd/packageToken.xsd#L3)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I might ask Ben to comment here about the XML namespacing -- is it necessary / desirable to have the `ietf:params:xml:ns:` prefix to the packageToken naming? My primary hesitation would be if there's some sort of pre-existing set of "allowed" names that fall into the ietf... namespacing and this isn't one of them. 
</blockquote></details>

Yeah this definitely doesn't seem right.  Especially when comparing it to our other custom EPP extension (e.g. the metadata one), which uses the `google:params:xml:ns:metadata-1.0` namespace.  And see also the `superuser` extension (also ours).


<!-- Sent from Reviewable.io -->

2022-08-30 20:05 UTC, gbrodman approved these changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1760)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ptkach)



<!-- Sent from Reviewable.io -->

2022-08-30 21:50 UTC, merged