Fail generate invoices job when billing events not finished expanding
google/nomulus pull request #1791
Opened 2022-09-15 21:15 UTC by ptkach

In case expand billing events job overlaps with generate invoices job, there's a chance that some auto-renewals might not get properly billed. This PR ensures ```/_dr/task/generateInvoices``` fails if last successful ```/_dr/task/expandRecurringBillingEvents``` is older than 1 day.

2022-09-19 04:37 UTC, jianglai requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1791)* status: all files reviewed, 4 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java` line 74 at r1](https://reviewable.io/reviews/google/nomulus/1791#-NCIt3vS0clbHUPT7YCW:-NCIt3vS0clbHUPT7YCX:b4gpaa5) ([raw file](https://github.com/google/nomulus/blob/7209fc90b46d2db392310e1bc11f26d2ec341b2a/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L74)):*
> ```Java
> public class InvoicingPipeline implements Serializable {
> 
>   @Inject Clock clock;
> ```

This will not work. You need Dagger to actually inject the field. The class right now is not managed or created by dagger.



_Code quote:_
```Java
@Inject Clock clock;
```
___
*[`core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java` line 97 at r1](https://reviewable.io/reviews/google/nomulus/1791#-NCIty3O-kKlJQfGXZWD:-NCIty3PCLHPShD8lNI5:bn1qe2v) ([raw file](https://github.com/google/nomulus/blob/7209fc90b46d2db392310e1bc11f26d2ec341b2a/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L97)):*
> ```Java
>                         .getCursorTime());
> 
>     if (currentCursorTime.isBefore(clock.nowUtc().minusDays(1))) {
> ```

`RECURRING_BILLING` is the inclusive upper limit the time for which the billing event has been expanded to:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/common/Cursor.java;l=87?q=recurring_bill&sq=&ss=nomulus%2Fnomulus

What you want to make sure is that when the billing pipeline runs, all the recurring billing events that need to be expanded for the time period you care about are indeed expanded. That means you want to make sure this cursor is after the end of the month that the invoice is generated for. The current time that the pipeline runs doesn't really matter. The `yearMonth` value in `options` is what matters, for it designates the time period the invoice is for.

Also, if all you want to do is to not run the pipeline given this condition, you can do this check in the main function below, or even better, in the action that actually kicks off the pipeline: [`GenerateInvoicesAction`](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/reporting/billing/GenerateInvoicesAction.java;l=107?q=generateinvoic&ss=nomulus%2Fnomulus).



_Code quote:_
```Java
(currentCursorTime.isBefore(clock.nowUtc().minusDays(1)))
```
___
*[`core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java` line 98 at r1](https://reviewable.io/reviews/google/nomulus/1791#-NCIzQE2AlGyfvu3vmNo:-NCIzQE2AlGyfvu3vmNp:b-djvjig) ([raw file](https://github.com/google/nomulus/blob/7209fc90b46d2db392310e1bc11f26d2ec341b2a/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L98)):*
> ```Java
> 
>     if (currentCursorTime.isBefore(clock.nowUtc().minusDays(1))) {
>       throw new RuntimeException(
> ```

This is not the most elegant solution as throwing an exception will fail the pipeline outright, and we will have to fix it (most likely by waiting a bit and rerunning it later) manually.

Granted, I don't think this should happen very often, as we kick off the pipeline at [17:00 on the first day of a month](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml;l=270;drc=775f672f2a1235832996ee8c2c98da7edd99a043;bpv=0;bpt=0), and the recurring expansion job runs at [03:00 each day](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml;l=139;drc=775f672f2a1235832996ee8c2c98da7edd99a043;bpv=0;bpt=0). So we have 14 hours for the expansion (of just one day's worth of new billing events) to finish.

But still, a better way to handle it is to use Cloud Tasks so we can have retries with exponential back off. In that case, you'd have a cron job that runs an action, which enqueues a task for `GenerateInvoicesAction`. When that task runs, it compares `yearMonth` and the cursor to determine if it should launch this pipeline. If not, it will return a [non-2XX](https://cloud.google.com/appengine/docs/legacy/standard/java/taskqueue/push/retrying-tasks) response, indicating to Cloud Tasks that it should be retried latter.



_Code quote:_
```Java
      throw new RuntimeException(
          "Latest billing events expansion cycle hasn't finished yet, terminating invoicing"
              + " pipeline");
```
___
*[`core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java` line 245 at r1](https://reviewable.io/reviews/google/nomulus/1791#-NCItM6Y12LLpjv7ew4j:-NCItM6Y12LLpjv7ew4k:b-k1jaaz) ([raw file](https://github.com/google/nomulus/blob/7209fc90b46d2db392310e1bc11f26d2ec341b2a/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L245)):*
> ```Java
>     InvoicingPipelineOptions options =
>         PipelineOptionsFactory.fromArgs(args).withValidation().as(InvoicingPipelineOptions.class);
>     new InvoicingPipeline(options).run();
> ```

If you do want to provide a `Clock`, use `SystemClock` as a constructor argument here, no need to use Dagger. But as I mentioned in the comment above, there's no need to use a `Clock` at all. What you should check is the `yearMonth` against the cursor, here, or more preferably in `GenerateInvoicesAction`.



_Code quote:_
```Java
InvoicingPipeline(options).run();
```


<!-- Sent from Reviewable.io -->

2022-09-19 20:48 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1791)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java` line 74 at r1](https://reviewable.io/reviews/google/nomulus/1791#-NCIt3vS0clbHUPT7YCW:-NCMUfSU1QZ_yJDNVFa5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7209fc90b46d2db392310e1bc11f26d2ec341b2a/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L74)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

This will not work. You need Dagger to actually inject the field. The class right now is not managed or created by dagger.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java` line 97 at r1](https://reviewable.io/reviews/google/nomulus/1791#-NCIty3O-kKlJQfGXZWD:-NCMUhA92WwfQ9nQ8E6T:b-q8d5ex) ([raw file](https://github.com/google/nomulus/blob/7209fc90b46d2db392310e1bc11f26d2ec341b2a/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L97)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

`RECURRING_BILLING` is the inclusive upper limit the time for which the billing event has been expanded to:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/common/Cursor.java;l=87?q=recurring_bill&sq=&ss=nomulus%2Fnomulus

What you want to make sure is that when the billing pipeline runs, all the recurring billing events that need to be expanded for the time period you care about are indeed expanded. That means you want to make sure this cursor is after the end of the month that the invoice is generated for. The current time that the pipeline runs doesn't really matter. The `yearMonth` value in `options` is what matters, for it designates the time period the invoice is for.

Also, if all you want to do is to not run the pipeline given this condition, you can do this check in the main function below, or even better, in the action that actually kicks off the pipeline: [`GenerateInvoicesAction`](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/reporting/billing/GenerateInvoicesAction.java;l=107?q=generateinvoic&ss=nomulus%2Fnomulus).
</blockquote></details>

Thanks, that was very helpful. Updated accordingly! 
___
*[`core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java` line 98 at r1](https://reviewable.io/reviews/google/nomulus/1791#-NCIzQE2AlGyfvu3vmNo:-NCMUnjN5RGBjAmNAFwV:b-qeg7qb) ([raw file](https://github.com/google/nomulus/blob/7209fc90b46d2db392310e1bc11f26d2ec341b2a/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L98)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

This is not the most elegant solution as throwing an exception will fail the pipeline outright, and we will have to fix it (most likely by waiting a bit and rerunning it later) manually.

Granted, I don't think this should happen very often, as we kick off the pipeline at [17:00 on the first day of a month](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml;l=270;drc=775f672f2a1235832996ee8c2c98da7edd99a043;bpv=0;bpt=0), and the recurring expansion job runs at [03:00 each day](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml;l=139;drc=775f672f2a1235832996ee8c2c98da7edd99a043;bpv=0;bpt=0). So we have 14 hours for the expansion (of just one day's worth of new billing events) to finish.

But still, a better way to handle it is to use Cloud Tasks so we can have retries with exponential back off. In that case, you'd have a cron job that runs an action, which enqueues a task for `GenerateInvoicesAction`. When that task runs, it compares `yearMonth` and the cursor to determine if it should launch this pipeline. If not, it will return a [non-2XX](https://cloud.google.com/appengine/docs/legacy/standard/java/taskqueue/push/retrying-tasks) response, indicating to Cloud Tasks that it should be retried latter.
</blockquote></details>

Updated. It looks like it's run under retryable-cron-tasks and should repeat 3 times if response if non-2XX, which should now be the case with my change. 
___
*[`core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java` line 245 at r1](https://reviewable.io/reviews/google/nomulus/1791#-NCItM6Y12LLpjv7ew4j:-NCMVOdB3oNUhBpW56U2:br6k48n) ([raw file](https://github.com/google/nomulus/blob/7209fc90b46d2db392310e1bc11f26d2ec341b2a/core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java#L245)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

If you do want to provide a `Clock`, use `SystemClock` as a constructor argument here, no need to use Dagger. But as I mentioned in the comment above, there's no need to use a `Clock` at all. What you should check is the `yearMonth` against the cursor, here, or more preferably in `GenerateInvoicesAction`.
</blockquote></details>

I removed, thanks for your suggestions! 


<!-- Sent from Reviewable.io -->

2022-09-21 13:20 UTC, merged

2022-09-21 14:07 UTC, jianglai commented
I thought we are not going to rely on the cron queue retry logic? We should return a 2XX message to stop the retry and send an email eng when the cursor is not up to date.

2022-09-21 14:23 UTC, ptkach commented
> I thought we are not going to rely on the cron queue retry logic? We should return a 2XX message to stop the retry and send an email eng when the cursor is not up to date.

We agreed upon email and shifting cron job 17.00 -> 19.00, but I don't think we settled on 2XX. 
I believe non-2XX response seems more natural here as it's not a successful scenario, plus with retries we still increase (by tiny little) our chances to success. The only downside is 4 emails that will be sent out instead of one, but given that it's a rare event and we actually want to draw attention maybe it's not bad. Anyway both options are good and should suffice, so if you strongly feel that 2XX is required I can update. Let me know.