Use injected times in URSC and CommandTestCase
google/nomulus pull request #1805
Opened 2022-10-03 16:27 UTC by gbrodman

We started getting failures because some of the tests used October. In general we should freeze the clock for testing as much as possible.

2022-10-03 17:41 UTC, gbrodman commented
github / kokoro integration is being wonky for now, but this should pass tests

2022-10-03 17:57 UTC, jianglai requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1805)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/main/java/google/registry/tools/GetEppResourceCommand.java` line 60 at r1](https://reviewable.io/reviews/google/nomulus/1805#-NDTz4a01krFgNvmy_Qf:-NDTz4a01krFgNvmy_Qg:b-bm90tn) ([raw file](https://github.com/google/nomulus/blob/0606694bb69d95accab77444c78a338a5f0143b2/core/src/main/java/google/registry/tools/GetEppResourceCommand.java#L60)):*
> ```Java
>   @Override
>   public void run() {
>     DateTime now = tm().transact(() -> tm().getTransactionTime());
> ```

Is there a reason why we want to get the time from a transaction? The `run()` method doesn't run in a transaction, does it? The old way seems to be working just fine. Same question for the change in the next file.



_Code quote:_
```Java
    DateTime now = tm().transact(() -> tm().getTransactionTime());
    if (readTimestamp == null) {
      readTimestamp = now;
    }
```


<!-- Sent from Reviewable.io -->

2022-10-03 19:38 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1805)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[`core/src/main/java/google/registry/tools/GetEppResourceCommand.java` line 60 at r1](https://reviewable.io/reviews/google/nomulus/1805#-NDTz4a01krFgNvmy_Qf:-NDULcrU33DuiRK261ae:b-w9sqgv) ([raw file](https://github.com/google/nomulus/blob/0606694bb69d95accab77444c78a338a5f0143b2/core/src/main/java/google/registry/tools/GetEppResourceCommand.java#L60)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is there a reason why we want to get the time from a transaction? The `run()` method doesn't run in a transaction, does it? The old way seems to be working just fine. Same question for the change in the next file.
</blockquote></details>

It does not run in a transaction. You are correct that the tests for these classes, as they stand, work fine. However changing the FakeClock in the CommandTestCase causes some of them to break. 

Even if they work now, we can't guarantee that they'll work in the future because any usage of DateTime.now() is potentially dangerous to tests. 


<!-- Sent from Reviewable.io -->

2022-10-04 03:04 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1805)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/main/java/google/registry/tools/GetEppResourceCommand.java` line 60 at r1](https://reviewable.io/reviews/google/nomulus/1805#-NDTz4a01krFgNvmy_Qf:-NDVvEFvB7pt_QAhiJIZ:bb89joa) ([raw file](https://github.com/google/nomulus/blob/0606694bb69d95accab77444c78a338a5f0143b2/core/src/main/java/google/registry/tools/GetEppResourceCommand.java#L60)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It does not run in a transaction. You are correct that the tests for these classes, as they stand, work fine. However changing the FakeClock in the CommandTestCase causes some of them to break. 

Even if they work now, we can't guarantee that they'll work in the future because any usage of DateTime.now() is potentially dangerous to tests. 
</blockquote></details>

I am still a bit confused as to why the change here is necessary. I understand that the URS command test used a fake clock that was initialized to `DateTime.now()`, but some resources were constructed with expiration date as of 2022-10-01, thus leading to the failure.

But that seems to be fixed by just setting the clock to a fixed value in `CommandTestCase`? You also changed a few other tests which depends on `DateTime.now()` to depend on the fake clock instead, which makes sense.

But why does the production code needs to change to use the transaction time as well? Unless the return value of `DateTime.now()` is somehow affected by the fake clock in tests, calling `tm().transact(() -> tm().getTransactionTime())` should effectively give you the same time as calling `DateTime.now()`, I think.

I feel like I'm missing something (maybe obvious) here... :O


<!-- Sent from Reviewable.io -->

2022-10-04 18:51 UTC, jianglai approved these changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1805)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2022-10-04 19:36 UTC, merged