Remove package token on manual transfer approval
google/nomulus pull request #1819
Opened 2022-10-17 22:53 UTC by sarahcaseybot

2022-10-18 04:06 UTC, jianglai requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1819)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 180 at r1](https://reviewable.io/reviews/google/nomulus/1819#-NEdC8o2BwqeXqUxJrfq:-NEdC8o2BwqeXqUxJrfr:b-8o88db) ([raw file](https://github.com/google/nomulus/blob/ea1f839d0469104a10cb62c49b327ecfdb121a6e/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L180)):*
> ```Java
>     // If domain was in a package, remove it from the package and reset the renewal price behavior
>     // to default
>     if (existingDomain.getCurrentPackageToken().isPresent()) {
> ```

Is there a reason to maintain a distinction between `existingXXX` and `existingXXXWithoutPackage`? If the condition is met, shouldn't we just overwrite `existingXXX` with the new value? Are there places downstream from here where you have to use the original value?



_Code quote:_
```Java
 if (existingDomain.getCurrentPackageToken().isPresent()) {
```
___
*[`core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java` line 834 at r1](https://reviewable.io/reviews/google/nomulus/1819#-NEdGPKW7pfGte-zdfQo:-NEdGPKW7pfGte-zdfQp:brz4bnj) ([raw file](https://github.com/google/nomulus/blob/ea1f839d0469104a10cb62c49b327ecfdb121a6e/core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java#L834)):*
> ```Java
>     assertHistoryEntriesDoNotContainTransferBillingEventsOrGracePeriods();
>   }
>   
> ```

Remove extra whitespaces.



_Code quote:_
```Java
··
```


<!-- Sent from Reviewable.io -->

2022-10-18 22:13 UTC, jianglai approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1819)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java` line 458 at r2](https://reviewable.io/reviews/google/nomulus/1819#-NEh8ozo0kmtG99kA3ow:-NEh8ozo0kmtG99kA3ox:b-m472g1) ([raw file](https://github.com/google/nomulus/blob/b47db19906c15db6dcb060fbf539840df4af442a/core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java#L458)):*
> ```Java
>         .isEqualTo(RenewalPriceBehavior.DEFAULT);
>   }
>  
> ```

Another extra whitespace.



_Code quote:_
```Java
·
```


<!-- Sent from Reviewable.io -->

2022-10-19 18:42 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1819)* status: all files reviewed, 5 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 176 at r2](https://reviewable.io/reviews/google/nomulus/1819#-NElYIhO7nM5F64xOEKr:-NElYIhO7nM5F64xOEKs:b7vbx7t) ([raw file](https://github.com/google/nomulus/blob/b47db19906c15db6dcb060fbf539840df4af442a/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L176)):*
> ```Java
>                     .build());
> 
>     // Close the old autorenew event and poll message at the transfer time (aka now). This may end
> ```

Why was this moved up?
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 187 at r2](https://reviewable.io/reviews/google/nomulus/1819#-NElXvW8CD4eJb7XoSyO:-NElXvW8CD4eJb7XoSyP:bbp8akq) ([raw file](https://github.com/google/nomulus/blob/b47db19906c15db6dcb060fbf539840df4af442a/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L187)):*
> ```Java
>     // to default
>     if (existingDomain.getCurrentPackageToken().isPresent()) {
>       existingDomain = existingDomain.asBuilder().setCurrentPackageToken(null).build();
> ```

The `existingDomain` is the existing domain in the database.  It doesn't make sense to make changes to it.  (It's also an anti-pattern generally to reuse a local variable when creating a new one makes more sense.)
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 268 at r2](https://reviewable.io/reviews/google/nomulus/1819#-NElY8LD3vhJzB-mX5S3:-NElY8LD3vhJzB-mX5S4:b-vezz4r) ([raw file](https://github.com/google/nomulus/blob/b47db19906c15db6dcb060fbf539840df4af442a/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L268)):*
> ```Java
>         approvePendingTransfer(existingDomain, TransferStatus.CLIENT_APPROVED, now);
>     String repoId = existingDomain.getRepoId();
>     Domain newDomain =
> ```

This is what you should be making the package token changes to.
___
*[`core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java` line 453 at r2](https://reviewable.io/reviews/google/nomulus/1819#-NElXmkP-sIdMcZwmyBb:-NElXmkP-sIdMcZwmyBc:b-vrlquu) ([raw file](https://github.com/google/nomulus/blob/b47db19906c15db6dcb060fbf539840df4af442a/core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java#L453)):*
> ```Java
>             .setRenewalPrice(Money.of(USD, new BigDecimal("10.00")))
>             .build());
>     Truth8.assertThat(domain.getCurrentPackageToken()).isEmpty();
> ```

Statically import this.


<!-- Sent from Reviewable.io -->

2022-10-28 18:17 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1819)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 157 at r4](https://reviewable.io/reviews/google/nomulus/1819#-NFUn7-P4URMHN7rHCiT:-NFUn7-P4URMHN7rHCiU:bbu0wf1) ([raw file](https://github.com/google/nomulus/blob/a04d9ddd3ae581106cf28922c5510370d33c07a3/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L157)):*
> ```Java
>             ? Optional.empty()
>             : Optional.of(
>                 new BillingEvent.OneTime.Builder()
> ```

All of this is getting overwritten below by similar values when you create a new billing event.  It's confusing.  Just set these values once.
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 177 at r4](https://reviewable.io/reviews/google/nomulus/1819#-NFUltMl5XOa6plfGsUU:-NFUltMl5XOa6plfGsUV:b-apz2f7) ([raw file](https://github.com/google/nomulus/blob/a04d9ddd3ae581106cf28922c5510370d33c07a3/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L177)):*
> ```Java
>                     .build());
> 
>     boolean wasPackageName = existingDomain.getCurrentPackageToken().isPresent();
> ```

`wasPackageName` seems a little bit off.  How about `hasPackageToken`
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 181 at r4](https://reviewable.io/reviews/google/nomulus/1819#-NFUnk7NEMKfIdOJVjdD:-NFUnk7NEMKfIdOJVjdE:bmwor1) ([raw file](https://github.com/google/nomulus/blob/a04d9ddd3ae581106cf28922c5510370d33c07a3/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L181)):*
> ```Java
>     // If domain was in a package, reset the transfer price
>     if (wasPackageName) {
>       renewalPrice = null;
> ```

It's confusing that renewalPrice is being rewritten here when the previous line of `Money renewalPrice = existingRecurring.getRenewalPrice().orElse(null);` seems like it's giving it the value in all circumstances. `renewalPrice` should have its value assigned exactly once.
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 183 at r4](https://reviewable.io/reviews/google/nomulus/1819#-NFUmZZS15IG8buYmMyw:-NFUmZZS15IG8buYmMyx:b-vgvkwm) ([raw file](https://github.com/google/nomulus/blob/a04d9ddd3ae581106cf28922c5510370d33c07a3/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L183)):*
> ```Java
>       renewalPrice = null;
>       if (billingEvent.isPresent()) {
>         billingEvent =
> ```

Don't override a local variable here.  Same problem was when you were overriding the existing domain.  You need to refactor the code above that starts with ` Optional<BillingEvent.OneTime> billingEvent =....` and change that to have a builder, and then simply make updates to it here (or set them correctly, once, above).

As a general principle code is more legible when immutability principles are followed, namely, variables are assigned a value once, and not then reassigned entirely later on.


<!-- Sent from Reviewable.io -->

2022-11-17 21:46 UTC, CydeWeys submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1819)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 171 at r5](https://reviewable.io/reviews/google/nomulus/1819#-NH6YQQHC02QbJDqgNwq:-NH6YQQHC02QbJDqgNwr:b-qxpn7a) ([raw file](https://github.com/google/nomulus/blob/c8fc027a186c1a47cf8a52807c9863bf526bef8e/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L171)):*
> ```Java
>                                 transferData.getTransferRequestTime(),
>                                 hasPackageToken
>                                     ? existingRecurring
> ```

This is a little bit strange ... enough to warrant an inline comment anyway.

Perhaps a better way to implement this would be to, rather than faking the state of the existing recurring to something that it is not (which is confusing), just add another parameter to `getTransferPrice()`?  Something like `isLeavingPackage`?


<!-- Sent from Reviewable.io -->

2022-11-28 20:30 UTC, merged