Remove names from packages on automatic transfers
google/nomulus pull request #1827
Opened 2022-10-24 21:06 UTC by sarahcaseybot

2022-10-25 19:42 UTC, jianglai requested changes
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1827)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java` line 210 at r1](https://reviewable.io/reviews/google/nomulus/1827#-NFFXN--7H0Pzg5VQm-6:-NFFXN--7H0Pzg5VQm-7:br6jmum) ([raw file](https://github.com/google/nomulus/blob/56ccf5614ab8da2b2c12695bc84e8a26511d236c/core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java#L210)):*
> ```Java
>     if (existingDomain.getCurrentPackageToken().isPresent()) {
>       feesAndCredits =
>           (period.getValue() == 0)
> ```

The parentheses are unnecessary. While you are at it, why not remove the unnecessary parentheses above as well?



_Code quote:_
```Java
(period.getValue() == 0)
```
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferUtils.java` line 147 at r1](https://reviewable.io/reviews/google/nomulus/1827#-NFFYcn5-AFIzXGLxFAV:-NFFYcn5-AFIzXGLxFAW:bu3mnsl) ([raw file](https://github.com/google/nomulus/blob/56ccf5614ab8da2b2c12695bc84e8a26511d236c/core/src/main/java/google/registry/flows/domain/DomainTransferUtils.java#L147)):*
> ```Java
>             automaticTransferTime, now, domainHistoryKey, targetId, existingDomain, transferCost)
>         .ifPresent(builder::add);
>     Recurring existingRecurringWithoutPackage = existingRecurring;
> ```

There doesn't seem to be any value in having a different local variable here, given that you immediately change it (or not) and use it in a return statement below.



_Code quote:_
```Java
Recurring existingRecurringWithoutPackage = existingRecurring;
```
___
*[`core/src/main/java/google/registry/model/domain/DomainBase.java` line 489 at r1](https://reviewable.io/reviews/google/nomulus/1827#-NFFYtV2-g8fS_SFqaY0:-NFFYtV2-g8fS_SFqaY1:bqqv1m3) ([raw file](https://github.com/google/nomulus/blob/56ccf5614ab8da2b2c12695bc84e8a26511d236c/core/src/main/java/google/registry/model/domain/DomainBase.java#L489)):*
> ```Java
>               .setAutorenewBillingEvent(transferData.getServerApproveAutorenewEvent())
>               .setAutorenewPollMessage(transferData.getServerApproveAutorenewPollMessage())
>               .setCurrentPackageToken(null);
> ```

Is it correct to always set the package token to null when projecting a domain in time? You probably want set the token to null outside this function only at the call site where you process a domain transfer, otherwise it will be applied to all call sites.



_Code quote:_
```Java
.setCurrentPackageToken(null);
```


<!-- Sent from Reviewable.io -->

2022-10-28 18:25 UTC, CydeWeys submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1827)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java` line 207 at r2](https://reviewable.io/reviews/google/nomulus/1827#-NFUp2oZ-nN17qrQJDZo:-NFUp2oZ-nN17qrQJDZp:b-rshkf0) ([raw file](https://github.com/google/nomulus/blob/cce8f5912ad136a481105477d5848f8a5a13d1e6/core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java#L207)):*
> ```Java
>     // behavior
>     if (existingDomain.getCurrentPackageToken().isPresent()) {
>       feesAndCredits =
> ```

Reassigning the existing `feesAndCredits` variable right after it's gotten from an API call is a violation of immutability, and worse, it's bad performance, as `getTransferPrice()` can require an expensive round-trip to the DB, only for its result to be completely discarded when a package token is present.  A better way to structure this code is:

```
Optional<FeesAndCredits> feesAndCredits;
if (existingDomain.getCurrentPackageToken().isPresent()) {
  // do new code in this PR to get values here
} else {
  // use existing code to get values here
}
```

Now `feesAndCredits` is assigned a value precisely once in all code paths, and previous work isn't later being thrown out.

I've been seeing this kind of issue a lot in your code, so please pay attention to it in future PRs.


<!-- Sent from Reviewable.io -->

2022-10-29 23:19 UTC, jianglai requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1827)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/test/java/google/registry/model/domain/DomainTest.java` line 931 at r2](https://reviewable.io/reviews/google/nomulus/1827#-NF_zzk8-JQ4Oc2M0jA8:-NF_zzk8-JQ4Oc2M0jA9:b-wexbxa) ([raw file](https://github.com/google/nomulus/blob/cce8f5912ad136a481105477d5848f8a5a13d1e6/core/src/test/java/google/registry/model/domain/DomainTest.java#L931)):*
> ```Java
>     assertThat(clonedDomain.getRegistrationExpirationTime()).isEqualTo(previousExpiration);
>     assertThat(clonedDomain.getCurrentPackageToken().get()).isEqualTo(allocationToken.createVKey());
>     assertThat(loadByKey(clonedDomain.getAutorenewBillingEvent())).isEqualTo(recurring);
> ```

Why testing the recurring event here, but not in the previous test? Does it get affected by the clone operation? Based on the javadoc in `DomainTransferRequestFlow`, billing events and poll messages are speculatively set during the transfer request to be active after explicit approval, so the clone operation should not affect it.



_Code quote:_
```Java
assertThat(loadByKey(clonedDomain.getAutorenewBillingEvent())).isEqualTo(recurring);
```


<!-- Sent from Reviewable.io -->

2022-11-02 14:37 UTC, jianglai approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1827)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java` line 207 at r2](https://reviewable.io/reviews/google/nomulus/1827#-NFUp2oZ-nN17qrQJDZo:-NFsjo6ECdtq7xs1YIem:bb5zdjp) ([raw file](https://github.com/google/nomulus/blob/cce8f5912ad136a481105477d5848f8a5a13d1e6/core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java#L207)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Fixed, and I will make sure to pay closer attention to this moving forward
</blockquote></details>

minor suggestion, you might want to switch the last two if statement so the one with shorter block is on top. This way it's easier to see all three blocks at a first glace.
___
*[`core/src/test/java/google/registry/model/domain/DomainTest.java` line 931 at r2](https://reviewable.io/reviews/google/nomulus/1827#-NF_zzk8-JQ4Oc2M0jA8:-NFsjG-15XlaPKkoP5dC:ba9wbca) ([raw file](https://github.com/google/nomulus/blob/cce8f5912ad136a481105477d5848f8a5a13d1e6/core/src/test/java/google/registry/model/domain/DomainTest.java#L931)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Yes, clone does not affect the recurring event. I just added the check in the test to verify that it was not affected, but removed it now to eliminate confusion. 
</blockquote></details>

If you add the same assertion in the previous test, does it also pass? If yes, then there's no point to include it. If no, then we do want to have it in both tests.


<!-- Sent from Reviewable.io -->

2022-11-02 20:44 UTC, jianglai approved these changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1827)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2022-11-23 20:48 UTC, merged