Add package monitoring for active domain limits
google/nomulus pull request #1867
Opened 2022-12-02 20:40 UTC by sarahcaseybot

2022-12-02 21:39 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1867)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 83 at r1](https://reviewable.io/reviews/google/nomulus/1867#-NIJc-Mj2d9o0SXwr10E:-NIJc-Mj2d9o0SXwr10F:b-q2lofl) ([raw file](https://github.com/google/nomulus/blob/5e17df74c582b7402404e94968d34fb8e794af71/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L83)):*
> ```Java
>   @Override
>   public void run() {
>     tm().transact(
> ```

This method is too long now. 

Maybe consider declaring two methods: handlePackageCreationOverage and handleActiveDomainOverage().



_Code quote:_
```Java
tm().transact(
```
___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 130 at r1](https://reviewable.io/reviews/google/nomulus/1867#-NIJdWl3CVq_Lo1QeuK7:-NIJdWl3CVq_Lo1QeuK8:b-blv4k) ([raw file](https://github.com/google/nomulus/blob/5e17df74c582b7402404e94968d34fb8e794af71/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L130)):*
> ```Java
>                 }
>               }
>               if (packagesOverCreateLimit.build().isEmpty()) {
> ```

This builder is built multiple times. Should build once.



_Code quote:_
```Java
packagesOverCreateLimit.build()
```
___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 172 at r1](https://reviewable.io/reviews/google/nomulus/1867#-NIJh_o91zZszAbPN2x-:-NIJh_o91zZszAbPN2x0:b-z7zdan) ([raw file](https://github.com/google/nomulus/blob/5e17df74c582b7402404e94968d34fb8e794af71/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L172)):*
> ```Java
>                         .getLastNotificationSent()
>                         .get()
>                         .isAfter(clock.nowUtc().minusDays(30))) {
> ```

Multiple such statements can be difficult to read.

Consider the following:

int daysSinceLastNotification = packagePromotion.getLastNotificationSent().map(
    sentDate -> org.joda.time.Days.daysBetween(clock.nowUtc(), sentDate).getDays())
    .orElse(Integer.MAX_VALUE);

if (daysSinceLastNotification < 30) { ...}
else if (daysSinceLastNotification < 40) { ...}
else { ... }

Also, please make 30, 40 etc named constants, even FORTY_DAYS is better than a number.



_Code quote:_
```Java
                    if (packagePromotion
                        .getLastNotificationSent()
                        .get()
                        .isAfter(clock.nowUtc().minusDays(30))) {
```
___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 216 at r1](https://reviewable.io/reviews/google/nomulus/1867#-NIJglxuBNPN7ONCCTkl:-NIJglxuBNPN7ONCCTkm:b-4og6cs) ([raw file](https://github.com/google/nomulus/blob/5e17df74c582b7402404e94968d34fb8e794af71/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L216)):*
> ```Java
>                         String.format(
>                             "Could not find registrar for package token %s", packageToken));
>                   }
> ```

Consider make this a method that takes email type (warning or upgrade) as parameter.



_Code quote:_
```Java
                  AllocationToken packageToken = tm().loadByKey(packagePromotion.getToken());
                  Optional<Registrar> registrar =
                      Registrar.loadByRegistrarIdCached(
                          packageToken.getAllowedRegistrarIds().iterator().next());
                  if (registrar.isPresent()) {
                    String body =
                        String.format(
                            emailTemplate,
                            registrar.get().getRegistrarName(),
                            packageToken.getToken(),
                            registrySupportEmail);
                    sendNotification(packageToken, emailSubject, body, registrar.get());
                    jpaTm()
                        .put(
                            packagePromotion
                                .asBuilder()
                                .setLastNotificationSent(clock.nowUtc())
                                .build());
                  } else {
                    logger.atSevere().log(
                        String.format(
                            "Could not find registrar for package token %s", packageToken));
                  }
```
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 557 at r1](https://reviewable.io/reviews/google/nomulus/1867#-NIJaUV0AJ2NWHWuSaRn:-NIJaUV1-aUrDy-iKUm4:bgojrhi) ([raw file](https://github.com/google/nomulus/blob/5e17df74c582b7402404e94968d34fb8e794af71/core/src/main/java/google/registry/config/files/default-config.yaml#L557)):*
> ```YAML
>     Example Registry
> 
>   # Email subject text to notify partners their package has exceeded the limit for current active domains and warn them their package will be upgraded in 30 days
> ```

Line too long.  Line length should be <=80 in non-java files.



_Code quote:_
```YAML
# Email subject text to notify partners their package has exceeded the limit for current active domains and warn them their package will be upgraded in 30 days
```
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 569 at r1](https://reviewable.io/reviews/google/nomulus/1867#-NIJavar5qHIYAKuiMjl:-NIJavar5qHIYAKuiMjm:b-3h3n61) ([raw file](https://github.com/google/nomulus/blob/5e17df74c582b7402404e94968d34fb8e794af71/core/src/main/java/google/registry/config/files/default-config.yaml#L569)):*
> ```YAML
>     If you have any questions or require additional support, please contact us
>     at %3$s.
>       
> ```

Are the dots here for formatting? 



_Code quote:_
```YAML
······
```
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 587 at r1](https://reviewable.io/reviews/google/nomulus/1867#-NIJanbC06nuJEyk80V-:-NIJanbC06nuJEyk80V0:bdm2pj8) ([raw file](https://github.com/google/nomulus/blob/5e17df74c582b7402404e94968d34fb8e794af71/core/src/main/java/google/registry/config/files/default-config.yaml#L587)):*
> ```YAML
>     
>     Regards,
>     Example Registry
> ```

Please add newline


<!-- Sent from Reviewable.io -->

2022-12-02 21:51 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1867)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 180 at r1](https://reviewable.io/reviews/google/nomulus/1867#-NIJoPT-Awuzo8zHi5as:-NIJoPT-Awuzo8zHi5at:b-pqk9gv) ([raw file](https://github.com/google/nomulus/blob/5e17df74c582b7402404e94968d34fb8e794af71/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L180)):*
> ```Java
>                         .get()
>                         .isBefore(clock.nowUtc().minusDays(40))) {
>                       // Send a warning if last warning email was more than 40 days ago
> ```

I'm a bit confused with the 30 vs 40 day handling. Is this covered in the design docs you sent? If so could you resend the link?
Thanks.



_Code quote:_
```Java
// Send a warning if last warning email was more than 40 days ago
```


<!-- Sent from Reviewable.io -->

2022-12-06 21:03 UTC, gbrodman requested changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1867)* status: all files reviewed, 14 unresolved discussions (waiting on @sarahcaseybot and @weiminyu)

___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 85 at r2](https://reviewable.io/reviews/google/nomulus/1867#-NIdA1lH1HwmnarfCArz:-NIdA1lH1HwmnarfCAs-:b-wa2yr7) ([raw file](https://github.com/google/nomulus/blob/1152b4c9bdb9c75fb04d9c81ea53083d3175a6ee/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L85)):*
> ```Java
>   @Override
>   public void run() {
>     tm().transact(
> ```

you don't have to do this, but if you have the run method being only the transact call, e.g. `tm().transact(this::actuallyRunTheThing);` or whatever the method is called, then the actual code itself has less indentation and looks nicer 
___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 118 at r2](https://reviewable.io/reviews/google/nomulus/1867#-NId9m3iBmgrWdp4n2Pd:-NId9m3iBmgrWdp4n2Pe:bj7gmnz) ([raw file](https://github.com/google/nomulus/blob/1152b4c9bdb9c75fb04d9c81ea53083d3175a6ee/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L118)):*
> ```Java
>                             .query(
>                                 "SELECT COUNT(*) FROM Domain WHERE current_package_token = :token"
>                                     + " AND deletion_time = :time")
> ```

kinda nitty, but use `:endOfTime` here so that anyone reading it at a glance knows this isn't just a random time (or whatever time we happen to be running), but always EOT 
___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 140 at r2](https://reviewable.io/reviews/google/nomulus/1867#-NIdAM-JDUIwwwqN_4Fy:-NIdAM-JDUIwwwqN_4Fz:bsn8637) ([raw file](https://github.com/google/nomulus/blob/1152b4c9bdb9c75fb04d9c81ea53083d3175a6ee/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L140)):*
> ```Java
>     if (overageList.isEmpty()) {
>       logger.atInfo().log("Found no packages over their create limit.");
>     } else {
> ```

kinda nitty, but it's better to avoid long `else` blocks by adding a return statement above in the no-domain case. Reduces indentation and makes cases clearer 

same note below for the other method 
___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 172 at r2](https://reviewable.io/reviews/google/nomulus/1867#-NIdAz620VZEKDalV3Sn:-NIdAz620VZEKDalV3So:b15yhry) ([raw file](https://github.com/google/nomulus/blob/1152b4c9bdb9c75fb04d9c81ea53083d3175a6ee/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L172)):*
> ```Java
>             packagePromotion
>                 .getLastNotificationSent()
>                 .map(sentDate -> org.joda.time.Days.daysBetween(sentDate, clock.nowUtc()).getDays())
> ```

can we not import `Days` without the qualifier? 
___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 196 at r2](https://reviewable.io/reviews/google/nomulus/1867#-NIdEPGYB7q2mPnE_eSI:-NIdEPGYB7q2mPnE_eSJ:b3h222o) ([raw file](https://github.com/google/nomulus/blob/1152b4c9bdb9c75fb04d9c81ea53083d3175a6ee/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L196)):*
> ```Java
>     AllocationToken packageToken = tm().loadByKey(packagePromotion.getToken());
>     Optional<Registrar> registrar =
>         Registrar.loadByRegistrarIdCached(packageToken.getAllowedRegistrarIds().iterator().next());
> ```

Do we have verification that allocation tokens corresponding to package promotions can only have exactly one registrar ID associated with them? If so, just use Iterables.getOnlyElement 
___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 207 at r2](https://reviewable.io/reviews/google/nomulus/1867#-NIdEMW4A4rGq3OanHA1:-NIdEMW4A4rGq3OanHA2:b8yh2h4) ([raw file](https://github.com/google/nomulus/blob/1152b4c9bdb9c75fb04d9c81ea53083d3175a6ee/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L207)):*
> ```Java
>       jpaTm().put(packagePromotion.asBuilder().setLastNotificationSent(clock.nowUtc()).build());
>     } else {
>       logger.atSevere().log(
> ```

Seems like this should be more than just a log message, right? 
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 569 at r1](https://reviewable.io/reviews/google/nomulus/1867#-NIJavar5qHIYAKuiMjl:-NIdCrK--4ME4xWZvmO9:b-h3je73) ([raw file](https://github.com/google/nomulus/blob/8faaa1ba60a123e4799036d1df7fe2befa4eaa3e/core/src/main/java/google/registry/config/files/default-config.yaml#L569)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

These dots must be added by reviewable as they aren't in the actual code and don't show up in the Github UI
</blockquote></details>

I believe these dots are showing space characters, which can be deleted 
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 558 at r2](https://reviewable.io/reviews/google/nomulus/1867#-NIdCYsl1c0_68hiGT8e:-NIdCYsl1c0_68hiGT8f:b-dj1d4a) ([raw file](https://github.com/google/nomulus/blob/1152b4c9bdb9c75fb04d9c81ea53083d3175a6ee/core/src/main/java/google/registry/config/files/default-config.yaml#L558)):*
> ```YAML
> 
>   # Email subject text to notify partners their package has exceeded the limit for current active domains and warn them their package will be upgraded in 30 days
>   packageDomainLimitWarningEmailSubject: "WARNING: Your Package Has Exceeded The Domain Limit"
> ```

Kind of nitty, but I believe in general email subjects should be written as sentences, not titles re: capitalization  (same for other subject) 

(this also goes for the existing ones unfortunately)


<!-- Sent from Reviewable.io -->

2022-12-09 02:20 UTC, weiminyu approved these changes
LGTM, with two nits comments.

Please address Gus' comments.

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1867#-:-NIofY5_724KfIU1FQ8-:bz3njop)* status: all files reviewed, 11 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 132 at r2](https://reviewable.io/reviews/google/nomulus/1867#-NIoe0wi3wT_QkD7d6bd:-NIoe0wi3wT_QkD7d6be:b6cfws) ([raw file](https://github.com/google/nomulus/blob/1152b4c9bdb9c75fb04d9c81ea53083d3175a6ee/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L132)):*
> ```Java
>                 }
>               }
>               handlePackageCreationOverage(packagesOverCreateLimitBuilder.build());
> ```

nit: It would be better if we move this method right after the packagesOverCreateLimit is generated, and before the query for actives is called.

So the loop body would look like:

creates = ...
handlePackageCreationOverage()
actives  = ...
handleActiveDomainsOverage()



_Code quote:_
```Java
handlePackageCreationOverage(packagesOverCreateLimitBuilder.build());
```
___
*[`core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java` line 180 at r2](https://reviewable.io/reviews/google/nomulus/1867#-NIof2it8mvLxSCSRw3I:-NIof2it8mvLxSCSRw3J:b-hce9hi) ([raw file](https://github.com/google/nomulus/blob/1152b4c9bdb9c75fb04d9c81ea53083d3175a6ee/core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java#L180)):*
> ```Java
>         } else if (daysSinceLastNotification < FORTY_DAYS) {
>           // Send an upgrade email if last email was between 30 and 40 days ago
>           sendActiveDomainOverageEmail(false, packagePromotion);
> ```

nit: Consider adding inline document of boolean param.

sendActiveDomainOverageEmail( /* warning= */false, packagePromotion);



_Code quote:_
```Java
sendActiveDomainOverageEmail(false, packagePromotion);
```


<!-- Sent from Reviewable.io -->

2022-12-14 15:55 UTC, gbrodman approved these changes
> Reviewed 3 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1867)* status: all files reviewed, 3 unresolved discussions (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2022-12-14 17:10 UTC, merged