New console backbone
google/nomulus pull request #1876
Opened 2022-12-08 20:35 UTC by ptkach

This change sets up new console - basic project, new tasks, integrates tasks with existing tasks routine, sets up Karma testing and adds Material Design, adds console to the war artifact and via new servlet makes it available on GCP

2022-12-08 23:57 UTC, jianglai reviewed
Use imperative mood in PR description, i. e. "Add new console backbone".

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1876#-:-NIo9z40ANWQQyWugzXn:b-16m69h)* status: 0 of 73 files reviewed, all discussions resolved (waiting on @gbrodman and @weiminyu)



<!-- Sent from Reviewable.io -->

2022-12-09 20:34 UTC, gbrodman requested changes
have you deployed this to any of the environments as a demo? looks neat 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1876#-:-NIsZ_ZV1yDbyyVtY1UG:b2uhi66)* status: 0 of 73 files reviewed, 10 unresolved discussions (waiting on @ptkach and @weiminyu)

___
*[`config/presubmits.py` line 89 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIsYasgEwJc0IgL4Vql:-NIsYasgEwJc0IgL4Vqm:bxqd6al) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/config/presubmits.py#L89)):*
> ```Python
>     PresubmitCheck(
>         r".*Copyright 20\d{2} The Nomulus Authors\. All Rights Reserved\.",
>         ("java", "js", "soy", "sql", "py", "sh", "gradle"), {
> ```

let's add .ts files here too
___
*[`console-webapp/angular.json` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsPLdC1lU5gDQMLnfc:-NIsPLdC1lU5gDQMLnfd:b4wkp8h) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/angular.json#L1)):*
> ```JSON
> {
> ```

This file is autogenerated by Angular, right? 
___
*[`console-webapp/build.gradle` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsRE6l1C7Phs59eX7z:-NIsRE6m5kNwScaay2a0:bn7z6cg) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/build.gradle#L1)):*
> ```Gradle
> // Copyright 2019 The Nomulus Authors. All Rights Reserved.
> ```

hehe probably want to check the year on this and all of the other copyrights 
___
*[`console-webapp/dev-proxy.config.json` line 4 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsShz58xfm64Q-xgSC:-NIsShz58xfm64Q-xgSD:b32m58g) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/dev-proxy.config.json#L4)):*
> ```JSON
>   "/registrar":
>   {
>     "target": "http://localhost:8080/registrar",
> ```

What's the deal with this file, again? And for what it's worth, we might want to use the url of `/console` instead of `/registrar` so that we can possibly run both of them at once. 

edit: I think we do use console in other places?
___
*[`console-webapp/karma.conf.js` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsTFVf-sPiA8a-NjVO:-NIsTFVf-sPiA8a-NjVP:b-c21ozp) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/karma.conf.js#L1)):*
> ```JavaScript
> // Karma configuration file, see link for more information
> ```

Should add a copyright notice just in case (unless this is autogenerated? how did this come about?) 
___
*[`console-webapp/src/main.ts` line 8 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIs_nUF7o-582y1cy2n:-NIs_nUF7o-582y1cy2o:b-8ghwos) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/console-webapp/src/main.ts#L8)):*
> ```XML
> 
> if (environment.production) {
>   enableProdMode();
> ```

do you know what this does? 
___
*[`console-webapp/src/app/app.component.spec.ts` line 5 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIsYOAC49DZKpQ-a0P3:-NIsYOAC49DZKpQ-a0P4:bd21ttq) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/console-webapp/src/app/app.component.spec.ts#L5)):*
> ```XML
> import { AppComponent } from './app.component';
> 
> describe('AppComponent', () => {
> ```

q: is this generated automatically somehow, or did you have to write this from scratch? 
___
*[`console-webapp/src/environments/environment.ts` line 10 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIs_Icn3q661BUIRp88:-NIs_Icn3q661BUIRp89:b2k0q8z) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/console-webapp/src/environments/environment.ts#L10)):*
> ```XML
> 
> /*
>  * For easier debugging in development mode, you can import the following file
> ```

do you know what this is all about? 
___
*[`core/gradle.lockfile` line 51 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsHnHaEBSgZDlkDYoo:-NIsHnHaEBSgZDlkDYop:b-k21q4b) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/core/gradle.lockfile#L51)):*
> ```
> com.google.api.grpc:grpc-google-cloud-spanner-admin-instance-v1:6.31.2=compileClasspath,default,deploy_jar,nonprodCompileClasspath,nonprodRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> com.google.api.grpc:grpc-google-cloud-spanner-v1:6.31.2=compileClasspath,default,deploy_jar,nonprodCompileClasspath,nonprodRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> com.google.api.grpc:grpc-google-cloud-storage-v2:2.15.1-alpha=compileClasspath,default,deploy_jar,nonprodCompileClasspath,nonprodRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> ```

I don't think we'd want to downgrade dependencies, why is this happening? 
___
*[`core/src/main/java/google/registry/env/common/default/WEB-INF/web.xml` line 97 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIsaAE8Ez9EBAV9riqK:-NIsaAE8Ez9EBAV9riqL:b-gnxuym) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/core/src/main/java/google/registry/env/common/default/WEB-INF/web.xml#L97)):*
> ```XML
>   </servlet-mapping>
> 
> <!--  &lt;!&ndash; Security config &ndash;&gt;-->
> ```

haha this is nitty but i think this probably shouldn't have been replaced


<!-- Sent from Reviewable.io -->

2022-12-12 16:51 UTC, ptkach reviewed
Thanks! Yes, it's available in QA - {QA_URL}/console/

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1876#-:-NJ5zWrmDKOQDNkYIYLc:b-1ukv4l)* status: 0 of 75 files reviewed, 10 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[`config/presubmits.py` line 89 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIsYasgEwJc0IgL4Vql:-NJ5znSkEibMAF2MPBMV:b-896fix) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/config/presubmits.py#L89)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

let's add .ts files here too
</blockquote></details>

Done.
___
*[`console-webapp/angular.json` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsPLdC1lU5gDQMLnfc:-NJ5zp4q33C8MPrIL5aI:bsztsew) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/angular.json#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This file is autogenerated by Angular, right? 
</blockquote></details>

As of now yes, I've not made any changes to it, but likely will
___
*[`console-webapp/build.gradle` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsRE6l1C7Phs59eX7z:-NJ6-7UN9joqKQaUiUOZ:b82wwnw) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/build.gradle#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

hehe probably want to check the year on this and all of the other copyrights 
</blockquote></details>

Yeah, I've copied the most used one in the project (which is 2019), as I assumed we will probably want to write some script to update all of them at once. Updated to 2022
___
*[`console-webapp/dev-proxy.config.json` line 4 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsShz58xfm64Q-xgSC:-NJ6-QTwAgANvGDe4AHs:bcsyqcz) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/dev-proxy.config.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What's the deal with this file, again? And for what it's worth, we might want to use the url of `/console` instead of `/registrar` so that we can possibly run both of them at once. 

edit: I think we do use console in other places?
</blockquote></details>

This file is a local proxy config, required so that relative webapp requests could reach the right back-end instance, which is as of now /registrar I believe. Note - we can't make requests like http://localhost:8080/registrar directly from webapp as that would be considered a same-origin violation 
___
*[`console-webapp/karma.conf.js` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsTFVf-sPiA8a-NjVO:-NJ60K_p9mLh44jkx9V1:b-xxswi4) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/karma.conf.js#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Should add a copyright notice just in case (unless this is autogenerated? how did this come about?) 
</blockquote></details>

As of now it's what has been created by Angular CLI, eventually I will likely make changes as we go. Should I add a copyright now or later in that case?
___
*[`console-webapp/src/main.ts` line 8 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIs_nUF7o-582y1cy2n:-NJ614016rSVcL6Rv0k-:bq8ofl8) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/console-webapp/src/main.ts#L8)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

do you know what this does? 
</blockquote></details>

Yes, it triggers runtime optimization like assertions removal, etc - https://angular.io/api/core/enableProdMode
___
*[`console-webapp/src/app/app.component.spec.ts` line 5 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIsYOAC49DZKpQ-a0P3:-NJ62r0r2baNhbFnaG52:b6znv6) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/console-webapp/src/app/app.component.spec.ts#L5)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

q: is this generated automatically somehow, or did you have to write this from scratch? 
</blockquote></details>

At this moment it's pretty much what has come with angular init command, however we will make changes to it as we go.
___
*[`console-webapp/src/environments/environment.ts` line 10 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIs_Icn3q661BUIRp88:-NJ64LTl6GjfkU3fc9a-:b-cr8dpp) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/console-webapp/src/environments/environment.ts#L10)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

do you know what this is all about? 
</blockquote></details>

It basically makes an error stack trace readable by showing an actual stack trace free from zone library related wrappers. Angular uses zone library to track actions and call callbacks, so lots of errors will have zone related functions in the call stack. However it should not be used in prod, as it says in the comment as performance suffers in that case 
___
*[`core/gradle.lockfile` line 51 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsHnHaEBSgZDlkDYoo:-NJ65X2s0rm9SNALMbFG:bx96fae) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/core/gradle.lockfile#L51)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think we'd want to downgrade dependencies, why is this happening? 
</blockquote></details>

Why downgrade? 2.15.1 -> 2.16.0 ? However I've just made another run by update_deps script, so it could've been different.
___
*[`core/src/main/java/google/registry/env/common/default/WEB-INF/web.xml` line 97 at r3](https://reviewable.io/reviews/google/nomulus/1876#-NIsaAE8Ez9EBAV9riqK:-NJ66N1q4R-9Dlhpzay5:b-bnz574) ([raw file](https://github.com/google/nomulus/blob/67c9d67c4977a161c30bca7589b7434799d76d54/core/src/main/java/google/registry/env/common/default/WEB-INF/web.xml#L97)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

haha this is nitty but i think this probably shouldn't have been replaced
</blockquote></details>

Good catch, IDE has made this change somehow


<!-- Sent from Reviewable.io -->

2023-01-03 21:43 UTC, gbrodman requested changes
I think the test failure is probably a flake, or just needing a rebase? 

> Reviewed 25 of 73 files at r1, 31 of 32 files at r4, 18 of 19 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1876#-:-NKUZTlU7G6hT6g6t-1R:b1bgbev)* status: all files reviewed, 8 unresolved discussions (waiting on @ptkach and @weiminyu)

___
*[`console-webapp/.browserslistrc` line 10 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_-pp8mBX04MKBf1C:-NKU_-pp8mBX04MKBf1D:bz3asek) ([raw file](https://github.com/google/nomulus/blob/f692a0d0692d58b489016c0909e8cdbe7b423b73/console-webapp/.browserslistrc#L10)):*
> ```Browserslist
> # You can see what browsers were selected by your queries by running:
> #   npx browserslist
> ```

any reason not to just use the `defaults` option?  first bit in https://github.com/browserslist/browserslist#best-practices 
___
*[`console-webapp/.editorconfig` line 1 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_DSl5V9JUOdHx4EG:-NKU_DSl5V9JUOdHx4EH:b-vp5jm7) ([raw file](https://github.com/google/nomulus/blob/f692a0d0692d58b489016c0909e8cdbe7b423b73/console-webapp/.editorconfig#L1)):*
> ```EditorConfig
> # Editor configuration, see https://editorconfig.org
> ```

question: is this in addition to the standard Typescript linting (https://typescript-eslint.io/)? We probably want to use at least the standard linter. 
___
*[`console-webapp/.gitignore` line 23 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_ndV4nqzhdj0OGjZ:-NKU_ndV4nqzhdj0OGj_:b-gu7o30) ([raw file](https://github.com/google/nomulus/blob/f692a0d0692d58b489016c0909e8cdbe7b423b73/console-webapp/.gitignore#L23)):*
> ```ignore
> *.sublime-workspace
> 
> # Visual Studio Code
> ```

I guess we're going to want to use VScode, huh :/ 
___
*[`console-webapp/dev-proxy.config.json` line 4 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsShz58xfm64Q-xgSC:-NKUan0iAoI7lljzwy-S:bpngw4r) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/dev-proxy.config.json#L4)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

This file is a local proxy config, required so that relative webapp requests could reach the right back-end instance, which is as of now /registrar I believe. Note - we can't make requests like http://localhost:8080/registrar directly from webapp as that would be considered a same-origin violation 
</blockquote></details>

I'm not entirely sure what you mean, can you explain further please? 
___
*[`console-webapp/karma.conf.js` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsTFVf-sPiA8a-NjVO:-NKUbdW31i95bGb0a2J4:b-bny0in) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/karma.conf.js#L1)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

As of now it's what has been created by Angular CLI, eventually I will likely make changes as we go. Should I add a copyright now or later in that case?
</blockquote></details>

Yeah if we make changes let's add the copyright  just in case 
___
*[`console-webapp/package.json` line 4 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKUcf8J2UAPTzFCSK5Z:-NKUcf8J2UAPTzFCSK5_:bgga5uf) ([raw file](https://github.com/google/nomulus/blob/f692a0d0692d58b489016c0909e8cdbe7b423b73/console-webapp/package.json#L4)):*
> ```JSON
>   "name": "console-webapp",
>   "version": "0.0.0",
>   "scripts": {
> ```

are these just little aliases / shortcuts? 
___
*[`console-webapp/tsconfig.app.json` line 1 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKtY0O1C1R04N2Xn3xs:-NKtY0O1C1R04N2Xn3xt:b-mol5rf) ([raw file](https://github.com/google/nomulus/blob/f692a0d0692d58b489016c0909e8cdbe7b423b73/console-webapp/tsconfig.app.json#L1)):*
> ```JSON
> /* To learn more about this file see: https://angular.io/config/tsconfig. */
> ```

just checking, did you make any changes to the tsconfig*.json files? 
___
*[`console-webapp/src/favicon.ico` line 0 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKtYHO64gqzMPzD7hsY:-NKtYHO64gqzMPzD7hsZ:bvc4kil) ([raw file](https://github.com/google/nomulus/blob/f692a0d0692d58b489016c0909e8cdbe7b423b73/console-webapp/src/favicon.ico#L0)):*
this can be for another time but we'll probably need a new favicon :P 
___
*[`console-webapp/src/index.html` line 5 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKtYdLhAH3UB26AD4Eo:-NKtYdLhAH3UB26AD4Ep:b-aa4rae) ([raw file](https://github.com/google/nomulus/blob/f692a0d0692d58b489016c0909e8cdbe7b423b73/console-webapp/src/index.html#L5)):*
> ```HTML
> <head>
>   <meta charset="utf-8">
>   <title>ConsoleWebapp</title>
> ```

nit, but maybe something like `Nomulus Console`?  I think it's what shows up in the browser's tab bar
___
*[`console-webapp/src/app/app.component.html` line 2 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKtZM4W75-wds0CAVRU:-NKtZM4W75-wds0CAVRV:b-2dgl29) ([raw file](https://github.com/google/nomulus/blob/f692a0d0692d58b489016c0909e8cdbe7b423b73/console-webapp/src/app/app.component.html#L2)):*
> ```HTML
> <div class="toolbar" role="banner">
>   Console Webapp
> ```

same comment here re: title perhaps? 
___
*[`core/gradle.lockfile` line 51 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsHnHaEBSgZDlkDYoo:-NKt_ZOiDfTR0M1no3_9:bcqwidl) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/core/gradle.lockfile#L51)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Why downgrade? 2.15.1 -> 2.16.0 ? However I've just made another run by update_deps script, so it could've been different.
</blockquote></details>

The earlier version downgraded the dependency from 2.16 to 2.15.1 for some reason, but it seems like the new run of update_deps fixed that. 


<!-- Sent from Reviewable.io -->

2023-01-05 17:49 UTC, ptkach reviewed
Failure was not related to my change and should be fixed with https://github.com/google/nomulus/pull/1893 . I just rebased, so will see

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1876#-:-NL1ZxNOCJUw9bVrWn-Z:b1ff6sp)* status: all files reviewed, 8 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], and @weiminyu)

___
*[`console-webapp/.browserslistrc` line 10 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_-pp8mBX04MKBf1C:-NL1_9qUApFYoOP_JrGs:bxgieoc) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/.browserslistrc#L10)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

any reason not to just use the `defaults` option?  first bit in https://github.com/browserslist/browserslist#best-practices 
</blockquote></details>

I will update it as we go, not sure yet what features we will use during development, so it's hard to say at the moment. What you see is what's been generated by angular cli
___
*[`console-webapp/.editorconfig` line 1 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_DSl5V9JUOdHx4EG:-NL1c6A82hDo_U5nSupZ:bps9i7e) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/.editorconfig#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

question: is this in addition to the standard Typescript linting (https://typescript-eslint.io/)? We probably want to use at least the standard linter. 
</blockquote></details>

Yes, it's an addition, mainly to make sure that by using the VSCODE and Intellij idea we follow the same styles. It has no rules yet, because I wanted to sync up with you and possibly other team members before  setting any rules. Once it's done I will add Angular lint as well.
___
*[`console-webapp/.gitignore` line 23 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_ndV4nqzhdj0OGjZ:-NL1coSu1KEBYrxXo8hZ:bmg6vz8) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/.gitignore#L23)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I guess we're going to want to use VScode, huh :/ 
</blockquote></details>

It's not necessary, but as one of the most used IDEs for front-end/angular projects I figured we should add VSCode rules here as well. I will likely use it for editing console-webapp project, while using intellij idea for editing java part
___
*[`console-webapp/dev-proxy.config.json` line 4 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsShz58xfm64Q-xgSC:-NL1xi3j7OWIPPw6-eTn:b-r1sva1) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/dev-proxy.config.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I'm not entirely sure what you mean, can you explain further please? 
</blockquote></details>

During development you will run console front-end development server, say at http://localhost:20000. This server provides hot reloading, serves html/js/css/etc.
You will also want to start a back-end server (API) to integrate with front-end requests, which will be responsible for serving API requests, say at http://localhost:8080/registrar (this is where it starts at the moment thus thats what I put in the config for now)

In this scenario requests from front-end server with static content at localhost:20000 to back-end API server instance at localhost:8080 will get rejected as is, because they violate same-origin policy (localhost:20000 != localhost:8080)

For this particular scenario it's a common practice to provide a proxy target to front-end server, making it basically proxying any request to an actual local instance of back-end. So front-end makes a request to relative endpoint /getSomeData, which hits front-end server at localhost:20000/getSomeData, which then redirects this to localhost:8080/registrar/getSomeData and back. This avoids any CORS violation and makes code the same in prod and locally allowing relative requests to work.
___
*[`console-webapp/karma.conf.js` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsTFVf-sPiA8a-NjVO:-NL2-aMl5e7HT40tb6Be:b-vllp5m) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/karma.conf.js#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah if we make changes let's add the copyright  just in case 
</blockquote></details>

I will add as soon as I make any changes, I believe that makes more sense
___
*[`console-webapp/package.json` line 4 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKUcf8J2UAPTzFCSK5Z:-NL2-jZf-WYTvLrARAjE:b78nsnk) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/package.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

are these just little aliases / shortcuts? 
</blockquote></details>

Yes, these are front-end project related scripts. It's a common practice to keep front-end build, test, start, etc tasks under scripts section in package.json and that's where everyone would expect them to be. We obviously also need gradle as well for instance to install front-end deps as otherwise those scripts would fail and keep things inline with the rest of the project. 
___
*[`console-webapp/tsconfig.app.json` line 1 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKtY0O1C1R04N2Xn3xs:-NL20yCA9oavfYnWGTLw:bbdhl7a) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/tsconfig.app.json#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

just checking, did you make any changes to the tsconfig*.json files? 
</blockquote></details>

Nope, not yet, thus no copyright
___
*[`console-webapp/src/favicon.ico` line  at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKtYHO64gqzMPzD7hsY:-NL215lH6pHx84noSWl1:bnaadn8) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/src/favicon.ico#L)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this can be for another time but we'll probably need a new favicon :P 
</blockquote></details>

of course, I believe we will need some other images as well, but we will deal with it as we go
___
*[`console-webapp/src/index.html` line 5 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKtYdLhAH3UB26AD4Eo:-NL21t0VCHY-zw_S1Vxs:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/src/index.html#L5)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit, but maybe something like `Nomulus Console`?  I think it's what shows up in the browser's tab bar
</blockquote></details>

Updated
___
*[`console-webapp/src/app/app.component.html` line 2 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKtZM4W75-wds0CAVRU:-NL21uuJA0vmq4oNMSDz:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/src/app/app.component.html#L2)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

same comment here re: title perhaps? 
</blockquote></details>

Updated
___
*[`console-webapp/src/app/home/home.component.ts` line 15 at r5](https://reviewable.io/reviews/google/nomulus/1876#-NInRrujYr2qvJGvIgVD-r5-15:-NL222YQ49TN5XDk7NBk:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c3ffafcdcab3da40eeaf5c647db73f65ee9790d8/console-webapp/src/app/home/home.component.ts#L15)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import OnInit.

[Show more details](https://github.com/google/nomulus/se [...]

2023-01-05 19:08 UTC, gbrodman requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1876)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot], @ptkach, and @weiminyu)

___
*[`console-webapp/.browserslistrc` line 10 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_-pp8mBX04MKBf1C:-NL2EniC-oPyq9mVWCHN:b-7utz8l) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/.browserslistrc#L10)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I will update it as we go, not sure yet what features we will use during development, so it's hard to say at the moment. What you see is what's been generated by angular cli
</blockquote></details>

if there's no reason not to use the "defaults" option let's just use it -- it seems like that'll be simpler than having to ever worry about updating it
___
*[`console-webapp/.editorconfig` line 1 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_DSl5V9JUOdHx4EG:-NL2FDvr4DvSWzYbC--I:bp7x0za) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/.editorconfig#L1)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Yes, it's an addition, mainly to make sure that by using the VSCODE and Intellij idea we follow the same styles. It has no rules yet, because I wanted to sync up with you and possibly other team members before  setting any rules. Once it's done I will add Angular lint as well.
</blockquote></details>

sounds great
___
*[`console-webapp/.gitignore` line 23 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_ndV4nqzhdj0OGjZ:-NL2FIQX9hjfaRBWAudw:b-fc4e9l) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/.gitignore#L23)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

It's not necessary, but as one of the most used IDEs for front-end/angular projects I figured we should add VSCode rules here as well. I will likely use it for editing console-webapp project, while using intellij idea for editing java part
</blockquote></details>

yep yep, that all sounds reasonable 
___
*[`console-webapp/dev-proxy.config.json` line 4 at r2](https://reviewable.io/reviews/google/nomulus/1876#-NIsShz58xfm64Q-xgSC:-NL2HnqUCvhbuPgfDfrr:b-48muok) ([raw file](https://github.com/google/nomulus/blob/eecee8400162c8c81262febe86ff6443e2e91a5d/console-webapp/dev-proxy.config.json#L4)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

During development you will run console front-end development server, say at http://localhost:20000. This server provides hot reloading, serves html/js/css/etc.
You will also want to start a back-end server (API) to integrate with front-end requests, which will be responsible for serving API requests, say at http://localhost:8080/registrar (this is where it starts at the moment thus thats what I put in the config for now)

In this scenario requests from front-end server with static content at localhost:20000 to back-end API server instance at localhost:8080 will get rejected as is, because they violate same-origin policy (localhost:20000 != localhost:8080)

For this particular scenario it's a common practice to provide a proxy target to front-end server, making it basically proxying any request to an actual local instance of back-end. So front-end makes a request to relative endpoint /getSomeData, which hits front-end server at localhost:20000/getSomeData, which then redirects this to localhost:8080/registrar/getSomeData and back. This avoids any CORS violation and makes code the same in prod and locally allowing relative requests to work.
</blockquote></details>

OK yeah I see what you mean. I was a bit confused because the current registrar console is served at `/registrar` (the backend serves other JSONy endpoints at other places). Sweet, this makes sense. 


<!-- Sent from Reviewable.io -->

2023-01-05 19:41 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1876)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], and @weiminyu)

___
*[`console-webapp/.browserslistrc` line 10 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_-pp8mBX04MKBf1C:-NL2R8FC8aNWvoVb_xdE:be7cqmh) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/.browserslistrc#L10)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

if there's no reason not to use the "defaults" option let's just use it -- it seems like that'll be simpler than having to ever worry about updating it
</blockquote></details>

As I mentioned before - this currently is what's been generated by angular cli and based on the docs is what angular actually supports - https://angular.io/guide/browser-support , so chances are making it different will cause fail-safe issues, while I prefer fail-fast. 


<!-- Sent from Reviewable.io -->

2023-01-05 20:22 UTC, gbrodman approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1876)* status: all files reviewed, 1 unresolved discussion (waiting on @github-code-scanning[bot] and @weiminyu)

___
*[`console-webapp/.browserslistrc` line 10 at r6](https://reviewable.io/reviews/google/nomulus/1876#-NKU_-pp8mBX04MKBf1C:-NL2aG-T1W1Pxta32g9B:bvsnjfa) ([raw file](https://github.com/google/nomulus/blob/76e3ef28407b6384828b38e40c8a2be2d559e8eb/console-webapp/.browserslistrc#L10)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

As I mentioned before - this currently is what's been generated by angular cli and based on the docs is what angular actually supports - https://angular.io/guide/browser-support , so chances are making it different will cause fail-safe issues, while I prefer fail-fast. 
</blockquote></details>

sgtm with the knowledge that it will still likely work on older browsers (e.g. chrome from a couple versions ago) but these are just the guarantees 


<!-- Sent from Reviewable.io -->

2023-01-05 21:23 UTC, merged