Disable id preassignment when writing to sql
google/nomulus pull request #1893
Opened 2023-01-04 18:00 UTC by weiminyu

See b/264416932 for details.

2023-01-04 19:31 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1893)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java` line 178 at r1](https://reviewable.io/reviews/google/nomulus/1893#-NKy5CDeDnyThb2Zx6La:-NKyG1e489L1mmKxpGjh:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c76a7b6e3b6f52b8f8c2693d52e6f9a33847c35a/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L178)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

We should just delete the `setId` method as it is only used here. It was added because the `@Id` annotation used to trigger ID allocation from `IdService` by virtue of the class `Spec11ThreatMatch` being a `Buildable`. This this is no longer the case as the triggering annotation is now a more explicit `@IdAllocation`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-04 20:43 UTC, jianglai requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1893)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java` line 178 at r1](https://reviewable.io/reviews/google/nomulus/1893#-NKy5CDeDnyThb2Zx6La:-NKyWXjR2y2gCPysWUwl:bes8064) ([raw file](https://github.com/google/nomulus/blob/c76a7b6e3b6f52b8f8c2693d52e6f9a33847c35a/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L178)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant delete the method definition...

Also, the comment here can be deleted too.


<!-- Sent from Reviewable.io -->

2023-01-04 21:29 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1893)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java` line 178 at r1](https://reviewable.io/reviews/google/nomulus/1893#-NKy5CDeDnyThb2Zx6La:-NKyEXFq-0ywJhCT0fQE:bmo4acx) ([raw file](https://github.com/google/nomulus/blob/c76a7b6e3b6f52b8f8c2693d52e6f9a33847c35a/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L178)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I meant delete the method definition...

Also, the comment here can be deleted too.
</blockquote></details>

It's deleted. Reviewable did not show it somehow.
___
*[`core/src/main/java/google/registry/model/reporting/Spec11ThreatMatch.java` line 144 at r2](https://reviewable.io/reviews/google/nomulus/1893#-NKyfd5V1ZRnET6LpTYq:-NKyfd5V1ZRnET6LpTYr:b-875k1z) ([raw file](https://github.com/google/nomulus/blob/db9525903d765da6a1afc170a9e1fcf352486209/core/src/main/java/google/registry/model/reporting/Spec11ThreatMatch.java#L144)):*
> ```Java
>       getInstance().id = id;
>       return this;
>     }
> ```

Here.



_Code quote:_
```Java
    public Builder setId(Long id) {
      getInstance().id = id;
      return this;
    }
```


<!-- Sent from Reviewable.io -->

2023-01-05 01:44 UTC, jianglai approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1893)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot and @weiminyu)

___
*[`core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java` line 178 at r1](https://reviewable.io/reviews/google/nomulus/1893#-NKy5CDeDnyThb2Zx6La:-NKzaHgh4nPA9DR6OJHw:bskijwy) ([raw file](https://github.com/google/nomulus/blob/c76a7b6e3b6f52b8f8c2693d52e6f9a33847c35a/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L178)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

It's deleted. Reviewable did not show it somehow.
</blockquote></details>

OK, weird.

Please delete the comment, it is not correct any more.



_Code quote:_
```Java
b/264416932
```


<!-- Sent from Reviewable.io -->

2023-01-05 16:04 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1893)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java` line 178 at r1](https://reviewable.io/reviews/google/nomulus/1893#-NKy5CDeDnyThb2Zx6La:-NL1elNL5RHFf_2p_JRr:bui6hnt) ([raw file](https://github.com/google/nomulus/blob/c76a7b6e3b6f52b8f8c2693d52e6f9a33847c35a/core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java#L178)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

OK, weird.

Please delete the comment, it is not correct any more.
</blockquote></details>

We need a reminder that the id issue is not solved. Depending on the end solution, this is as good a place as anywhere else.


<!-- Sent from Reviewable.io -->

2023-01-05 16:04 UTC, merged