Add support for Nordn upload without using pull queues.
google/nomulus pull request #1925
Opened 2023-01-31 19:09 UTC by jianglai

This PR adds an alternative method to upload Lordn to Nordn server
without using App Engine pull queue. Currently both methods are enabled
so the same domain would appear in both uploads. This is fine as
duplicates are not forbidden, but omissisns are.

After this PR is deployed and runs for a while, the pull queue-based
method can be removed, as long as we are confident that there are no
domains that are included in the pull queue, but do not have the
lordn_phase column set, which should be the case after all
pre-deployment enqueued domains are processed (typically in the next
Nordn uploads, which happens every 12 hours).

See: go/registry-pull-queue-redesign

2023-02-01 01:31 UTC, jianglai reviewed
> Reviewed 7 of 10 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-02-03 16:03 UTC, jianglai reviewed
> Reviewed 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-02-03 16:03 UTC, jianglai reviewed
> Reviewed 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-02-07 18:29 UTC, jianglai reviewed
> Reviewed 4 of 4 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys and @weiminyu)



<!-- Sent from Reviewable.io -->

2023-02-09 20:49 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys, @gbrodman, and @weiminyu)



<!-- Sent from Reviewable.io -->

2023-02-10 15:48 UTC, jianglai commented
Gentle ping.

2023-02-15 16:37 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys, @gbrodman, @ptkach, and @weiminyu)



<!-- Sent from Reviewable.io -->

2023-02-23 15:10 UTC, jianglai reviewed
Gentle ping again.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925#-:-NOyosAICuli9RrS9DGB:bvtxan2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys, @gbrodman, @ptkach, and @weiminyu)



<!-- Sent from Reviewable.io -->

2023-02-23 20:27 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, @jianglai, and @ptkach)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 408 at r10](https://reviewable.io/reviews/google/nomulus/1925#-NOzil9wDjCQErfIpFpU:-NOzil9xCU7bJVljsif0:bf2wkfp) ([raw file](https://github.com/google/nomulus/blob/a6c0db1fed578a52749126e8eca35fe43b61ddba/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L408)):*
> ```Java
>                     ? hasSignedMarks
>                         ? LordnPhase.SUNRISE
>                         : hasClaimsNotice ? LordnPhase.CLAIMS : LordnPhase.NONE
> ```

Consider adding parentheses to help readabliilty.



_Code quote:_
```Java
                    ? hasSignedMarks
                        ? LordnPhase.SUNRISE
                        : hasClaimsNotice ? LordnPhase.CLAIMS : LordnPhase.NONE
```
___
*[`core/src/main/java/google/registry/tmch/NordnUploadAction.java` line 166 at r10](https://reviewable.io/reviews/google/nomulus/1925#-NOztoNZD70OglRUVjRT:-NOztoNZD70OglRUVjRU:bf8g3w4) ([raw file](https://github.com/google/nomulus/blob/a6c0db1fed578a52749126e8eca35fe43b61ddba/core/src/main/java/google/registry/tmch/NordnUploadAction.java#L166)):*
> ```Java
>                 // a peak in claims during TLD launch (sunrise is NOT first-come-first-serve, so
>                 // there should be no expectation of a peak during it), we can consider temporarily
>                 // increasing the frequency of Nordn upload to reduce the size of each batch.
> ```

This may not be enough.Right now, we often see domains loading at 10 - 20 entries per second.
If nordn upload can run no more than every 3 hours, as stated in the cron.xml file, this transaction
may see a large number domains during peak time  that may take minutes to load, increasing the risk
of rollbacks.

We should probably run some numbers using .app as an example.



_Code quote:_
```Java
increasing the frequency of Nordn upload
```


<!-- Sent from Reviewable.io -->

2023-02-23 21:03 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, @ptkach, and @weiminyu)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 408 at r10](https://reviewable.io/reviews/google/nomulus/1925#-NOzil9wDjCQErfIpFpU:-NOzyX0T9_W6xVubZEsl:b4jno8z) ([raw file](https://github.com/google/nomulus/blob/a6c0db1fed578a52749126e8eca35fe43b61ddba/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L408)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Consider adding parentheses to help readabliilty.
</blockquote></details>

I did try to add parentheses but it only seemed to make things worse. I think the indentation here is more helpful. Plus the code is throwaway and will be deleted soon after the migration.

I've reordered the ternary so it cascades down nicely.
___
*[`core/src/main/java/google/registry/tmch/NordnUploadAction.java` line 166 at r10](https://reviewable.io/reviews/google/nomulus/1925#-NOztoNZD70OglRUVjRT:-NP-48VQ0103jYR_eBsO:bsmciaw) ([raw file](https://github.com/google/nomulus/blob/a6c0db1fed578a52749126e8eca35fe43b61ddba/core/src/main/java/google/registry/tmch/NordnUploadAction.java#L166)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This may not be enough.Right now, we often see domains loading at 10 - 20 entries per second.
If nordn upload can run no more than every 3 hours, as stated in the cron.xml file, this transaction
may see a large number domains during peak time  that may take minutes to load, increasing the risk
of rollbacks.

We should probably run some numbers using .app as an example.

</blockquote></details>

Just checked the current pull queue and there are only 4 tasks pending (across all TLDs) with 3 hours to go till the next upload (i.e. 9 hours after the last one). I think we are probably safe until the next sunrise (which again should not be an issue as it is not first come first serve, so there should be no expectation of a surge).


<!-- Sent from Reviewable.io -->

2023-02-23 21:03 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1925)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, @ptkach, and @weiminyu)



<!-- Sent from Reviewable.io -->

2023-02-28 17:57 UTC, merged