Generate and use an IAP-enabled ID token in the proxy
google/nomulus pull request #1926
Opened 2023-02-01 17:48 UTC by gbrodman

This is only generated and used if "iapClientId" is set in the proxy config. If so, we use code similar to
https://cloud.google.com/iap/docs/authentication-howto#obtaining_an_oidc_token_for_the_default_service_account to generate an ID token that is valid for IAP. We set the token on the Proxy-Authorization header so that we can keep using the pre-existing access token as well -- IAP allows for us to use either the Authorization header or the Proxy-Authorization header.

2023-02-03 01:53 UTC, jianglai requested changes
Is there a reason why we cannot set the IAP client ID now? If it is going to be required latter anyway, and having both headers do not impact anything, why not just set it up from the get-go?

Also, please not in the PR description how this is tested.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1926#-:-NNJvEBq9pCKpZN1KQ-k:b-vnnm2j)* status: all files reviewed, 9 unresolved discussions (waiting on @gbrodman)

___
*[`proxy/src/main/java/google/registry/proxy/EppProtocolModule.java` line 163 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJuF0y1lwIZG8kVJjV:-NNJuF0y1lwIZG8kVJjW:b-nz56dh) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/EppProtocolModule.java#L163)):*
> ```Java
>         helloBytes,
>         metrics,
>         iapClientId);
> ```

nit: Can we have `ipaClientId` follow `refreshedCredentialsSupplier`in the argument order?



_Code quote:_
```Java
iapClientId)
```
___
*[`proxy/src/main/java/google/registry/proxy/ProxyModule.java` line 239 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJtujc1CgP3l6UkNMH:-NNJtujc1CgP3l6UkNMI:b4bgi7u) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/ProxyModule.java#L239)):*
> ```Java
>         credentials.refreshIfExpired();
>       } catch (IOException e) {
>         throw new RuntimeException("Cannot refresh access token.", e);
> ```

Cannot refresh credential.



_Code quote:_
```Java
Cannot refresh access token.
```
___
*[`proxy/src/main/java/google/registry/proxy/WhoisProtocolModule.java` line 104 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJuZ2kE-aMezD8jjo8:-NNJuZ2l9fpUsjig-9_P:b-sm33yk) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/WhoisProtocolModule.java#L104)):*
> ```Java
>         refreshedCredentialsSupplier,
>         metrics,
>         iapClientId);
> ```

Same nit about argument order.



_Code quote:_
```Java
iapClientId
```
___
*[`proxy/src/main/java/google/registry/proxy/handler/EppServiceHandler.java` line 68 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJue_l9M_-OGS69QP5:-NNJue_l9M_-OGS69QP6:b-1kzc9c) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/handler/EppServiceHandler.java#L68)):*
> ```Java
>       byte[] helloBytes,
>       FrontendMetrics metrics,
>       Optional<String> iapClientId) {
> ```

And here.



_Code quote:_
```Java
Optional<String> iapClientId)
```
___
*[`proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java` line 91 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJujey2zVclmOv65eR:-NNJujey2zVclmOv65eS:b-1kzc9c) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java#L91)):*
> ```Java
>       Supplier<GoogleCredentials> refreshedCredentialsSupplier,
>       FrontendMetrics metrics,
>       Optional<String> iapClientId) {
> ```

And here.



_Code quote:_
```Java
Optional<String> iapClientId
```
___
*[`proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java` line 128 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJuuMx4O5L-rFAWqfA:-NNJuuMx4O5L-rFAWqfB:bees6gw) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java#L128)):*
> ```Java
>             .set(HttpHeaderNames.PROXY_AUTHORIZATION, "Bearer " + idToken.getTokenValue());
>       } catch (IOException e) {
>         throw new RuntimeException("Error when attempting to retrieve IAP ID token", e);
> ```

I think for now we can log this at severe instead of throwing, this way we can be sure that the existing functionality would not be broken.



_Code quote:_
```Java
 throw new RuntimeException("Error when attempting to retrieve IAP ID token", e);
```
___
*[`proxy/src/main/java/google/registry/proxy/handler/WhoisServiceHandler.java` line 40 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJv4Ud4b-efIhydh1y:-NNJv4UeAfn4_hC7239E:b-meseu3) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/handler/WhoisServiceHandler.java#L40)):*
> ```Java
>       Supplier<GoogleCredentials> refreshedCredentialsSupplier,
>       FrontendMetrics metrics,
>       Optional<String> iapClientId) {
> ```

order.



_Code quote:_
```Java
Optional<String> iapClientId
```
___
*[`proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJwJhk4LMiBHVUGPgQ:-NNJwJhk4LMiBHVUGPgR:bkmhb7z) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java#L70)):*
> ```Java
>   private static final String PROTOCOL = "epp";
> 
>   private static final ComputeEngineCredentials mockCredentials =
> ```

Does it have to be a `ComputeEngineCredentials`? Just mocking a`GoogleCredentials` won't work?



_Code quote:_
```Java
ComputeEngineCredentials
```
___
*[`proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java` line 84 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJxX6AAbkY0w-YnOKd:-NNJxX6AAbkY0w-YnOKe:b9k5aw8) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java#L84)):*
> ```Java
>           HELLO.getBytes(UTF_8),
>           metrics,
>           Optional.empty());
> ```

If you really want to use optional here, you have to double the number of tests so we can verify that the `Proxy-Authorization` header is actually present in the requests, when the IPA client ID is present. As far as I can tell, you modified all the tests to use `Optional.empty()`, which tells me that there are no tests that verifies the part of the code branch that adds the additional header, right?

So this goes back to my question above -- is there any advantage in using an optional here?



_Code quote:_
```Java
Optional.empty()
```


<!-- Sent from Reviewable.io -->

2023-02-06 23:02 UTC, gbrodman reviewed
We can definitely set it up now / ASAP. I tested on QA that if we have the client ID in the config but IAP isn't configured, it'll still just use the standard pre-existing auth. 

Updated PR with testing notes

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1926#-:-NNce-EhEGMId6_e8YTO:bxejcpq)* status: 3 of 14 files reviewed, 9 unresolved discussions (waiting on @jianglai)

___
*[`proxy/src/main/java/google/registry/proxy/EppProtocolModule.java` line 163 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJuF0y1lwIZG8kVJjV:-NNcf2pPAicyJc2A6Yln:b-5sfafh) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/EppProtocolModule.java#L163)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

nit: Can we have `ipaClientId` follow `refreshedCredentialsSupplier`in the argument order?
</blockquote></details>

I'll put it right after `helloBytes` so that the `@Named` params are together and in alphabetical order 
___
*[`proxy/src/main/java/google/registry/proxy/ProxyModule.java` line 239 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJtujc1CgP3l6UkNMH:-NNcfDeEAoRjQJ2qBvy2:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/ProxyModule.java#L239)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Cannot refresh credential.
</blockquote></details>

Done.
___
*[`proxy/src/main/java/google/registry/proxy/WhoisProtocolModule.java` line 104 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJuZ2kE-aMezD8jjo8:-NNcgLOV6DGdph45eDCN:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/WhoisProtocolModule.java#L104)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Same nit about argument order.
</blockquote></details>

Done.
___
*[`proxy/src/main/java/google/registry/proxy/handler/EppServiceHandler.java` line 68 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJue_l9M_-OGS69QP5:-NNcgMwo3Blh8GdNuizy:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/handler/EppServiceHandler.java#L68)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

And here.
</blockquote></details>

Done.
___
*[`proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java` line 91 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJujey2zVclmOv65eR:-NNcgNcV8jb8rE28fI8e:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java#L91)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

And here.
</blockquote></details>

Done.
___
*[`proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java` line 128 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJuuMx4O5L-rFAWqfA:-NNchNPdAMcKP1iFCt5X:bdaek36) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java#L128)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I think for now we can log this at severe instead of throwing, this way we can be sure that the existing functionality would not be broken.
</blockquote></details>

good point
___
*[`proxy/src/main/java/google/registry/proxy/handler/WhoisServiceHandler.java` line 40 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJv4Ud4b-efIhydh1y:-NNcgOZT18-EBppAc366:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/handler/WhoisServiceHandler.java#L40)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

order.
</blockquote></details>

Done.
___
*[`proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJwJhk4LMiBHVUGPgQ:-NNchDtS2bNVLLdJKrP4:b-e85xii) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java#L70)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Does it have to be a `ComputeEngineCredentials`? Just mocking a`GoogleCredentials` won't work?
</blockquote></details>

Kind of, yes. `GoogleCredentials` doesn't implement `IdTokenProvider` (`ComputeEngineCredentials` does), so if we want to test that in these tests we have to use `ComputeEngineCredentials`. This is made clearer in the other comment now 
___
*[`proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java` line 84 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJxX6AAbkY0w-YnOKd:-NNci0oxB43TiQ9jE64m:b6xwpc7) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java#L84)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

If you really want to use optional here, you have to double the number of tests so we can verify that the `Proxy-Authorization` header is actually present in the requests, when the IPA client ID is present. As far as I can tell, you modified all the tests to use `Optional.empty()`, which tells me that there are no tests that verifies the part of the code branch that adds the additional header, right?

So this goes back to my question above -- is there any advantage in using an optional here?
</blockquote></details>

Sort of. As it stands, the EppProtocolModuleTest tests do test the Proxy-Authorization path because they use the module itself (which provides a fake IAP client ID). 

However, I think you're probably right and we should use a (fake) IAP client ID everywhere. I've done that and also added a test each to EppServiceModuleTest and WhoisServiceModuleTest to test the situation(s) where we don't have an IAP client ID.


<!-- Sent from Reviewable.io -->

2023-02-07 16:44 UTC, jianglai approved these changes
Oh I see. If IAP is not configured and we make up some fake string in the config file, when we try to create the token, the code would throw I presume? I guess in that case we should use an optional. Even though the exception would only be logged, but not propagate up the stack any more, it still would be messy.

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1926#-:-NNgkC3W09xeKyoBu0R0:b-hjlbpi)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[`proxy/src/main/java/google/registry/proxy/EppProtocolModule.java` line 163 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJuF0y1lwIZG8kVJjV:-NNggKn24Il3J0aziQdm:bcevog2) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/EppProtocolModule.java#L163)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I'll put it right after `helloBytes` so that the `@Named` params are together and in alphabetical order 
</blockquote></details>

I wouldn't care too much about alphabetical order and would swap `helloBytes`'s place with it, so the depedencies needed for auth are grouped together. But I'll leave this up to you.
___
*[`proxy/src/main/java/google/registry/proxy/config/default-config.yaml` line 10 at r2](https://reviewable.io/reviews/google/nomulus/1926#-NNgghOG-rggggMBic4Y:-NNgghOG-rggggMBic4Z:b-te1ak2) ([raw file](https://github.com/google/nomulus/blob/eeb727e6e397a69a9e0b67c9574e18e9d9beafda/proxy/src/main/java/google/registry/proxy/config/default-config.yaml#L10)):*
> ```YAML
> # GCP project ID
> projectId: your-gcp-project-id
> # IAP client ID, if IAP is enabled for this project
> ```

Add a blank line above.



_Code quote:_
```YAML
 IAP client ID,
```
___
*[`proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java` line 125 at r2](https://reviewable.io/reviews/google/nomulus/1926#-NNgidIY7e1ESEQyGMJk:-NNgidIZCqn44tbCUJx5:b-sralvx) ([raw file](https://github.com/google/nomulus/blob/eeb727e6e397a69a9e0b67c9574e18e9d9beafda/proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java#L125)):*
> ```Java
>         IdToken idToken =
>             idTokenProvider.idTokenWithAudience(
>                 iapClientId.get(), ImmutableList.of(Option.FORMAT_FULL));
> ```

Can you add a comment on what this does and why it is needed?



_Code quote:_
```Java
Option.FORMAT_FULL
```


<!-- Sent from Reviewable.io -->

2023-02-07 19:30 UTC, gbrodman reviewed
Yes, it throws an exception if we have a garbage value in the iapClientId section of the proxy config (regardless of whether or not IAP is configured for the GAE app). 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1926#-:-NNhJuSuA8BFfWHC6U6z:bm7xlm0)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @jianglai)

___
*[`proxy/src/main/java/google/registry/proxy/EppProtocolModule.java` line 163 at r1](https://reviewable.io/reviews/google/nomulus/1926#-NNJuF0y1lwIZG8kVJjV:-NNhKvVY4jf5ymQuIg-l:b-hsxhua) ([raw file](https://github.com/google/nomulus/blob/8cf9233a15fbde7bd9a5533d92da59713e395b3c/proxy/src/main/java/google/registry/proxy/EppProtocolModule.java#L163)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I wouldn't care too much about alphabetical order and would swap `helloBytes`'s place with it, so the depedencies needed for auth are grouped together. But I'll leave this up to you.
</blockquote></details>

yeah fair enough 
___
*[`proxy/src/main/java/google/registry/proxy/config/default-config.yaml` line 10 at r2](https://reviewable.io/reviews/google/nomulus/1926#-NNgghOG-rggggMBic4Y:-NNhLt8i47x5CcgXR_cU:b-896fix) ([raw file](https://github.com/google/nomulus/blob/eeb727e6e397a69a9e0b67c9574e18e9d9beafda/proxy/src/main/java/google/registry/proxy/config/default-config.yaml#L10)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Add a blank line above.
</blockquote></details>

Done.
___
*[`proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java` line 125 at r2](https://reviewable.io/reviews/google/nomulus/1926#-NNgidIY7e1ESEQyGMJk:-NNhLlIA4zTSSv1eABEj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/eeb727e6e397a69a9e0b67c9574e18e9d9beafda/proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java#L125)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Can you add a comment on what this does and why it is needed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-08 02:45 UTC, jianglai approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2023-02-09 19:50 UTC, merged