Move App Engine cron jobs to cloud scheduler
google/nomulus pull request #1939
Opened 2023-02-10 19:50 UTC by ptkach

2023-02-13 19:21 UTC, jianglai requested changes
> Reviewed 9 of 10 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 111 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NO-w7iX274QTQilZf2R:-NO-w7iX274QTQilZf2S:b-kt6suv) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/config/RegistryConfig.java#L111)):*
> ```Java
>     @Provides
>     @Config("cloudSchedulerServiceAccountEmailPrefix")
>     public static String provideCloudSchedulerServiceAccountEmailPrefix(
> ```

Just provide the whole email address here. Using a prefix only confuses things. It's easier to see what the email is in one place.



_Code quote:_
```Java
provideCloudSchedulerServiceAccountEmailPrefix
```
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOBBOABC9q7S0nIQUrV:-NOBBOABC9q7S0nIQUrW:byih8ss) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

A few general comment:

1) I didn't realize Cloud Scheduler doesn't have a `cron.xml` or `cron.yaml` equivalent and everything is done via `gcloud` or pantheon.

2) If we are going to make a config file ourselves, there is no need to stick to the xml format that mostly derives from `cron.xml`. I think YAML would be more succinct and readable.

3) Again, if we are making our own config file to parse, we can make a lot of the fields optional. For example, there is no need for `name`, We probably want to make the entire URL configurable (maybe at the root level, so we don't have to write it for every entry), and `method` can be optional with GET being the default. `target` is probably also not needed. We only ever use backend here, and with the migration to GKE, we probably won't have the service name visible to the outside any more. Every endpoint would be on the same domain, with the path being the only differentiating factor. Lastly, the description can be comments in YAML file instead actual fields.



_Code quote:_
```XML
<?xml version="1.0" encoding="UTF-8"?>
```
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 70 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOB9haAC5XLVZeEPYTd:-NOB9haAC5XLVZeEPYTe:b-eh4aod) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L70)):*
> ```XML
>       Syncs RegistrarContact changes in the past hour to Google Groups.
>     </description>
>     <schedule>15 */1 * * *</schedule>
> ```

Should be 0.



_Code quote:_
```XML
15
```
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 92 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOBB-ve1syunQkEWyfv:-NOBB-ve1syunQkEWyfw:b-aog1kw) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L92)):*
> ```XML
>       This job resaves all our resources, projected in time to "now".
>     </description>
>     <schedule>0 9 1 * *</schedule>
> ```

The cron job runs on the first monday of the month. Though I doubt it matters.

It would help if we can make a note on any deviation from the cron job schedule.



_Code quote:_
```XML
    </description>
    <schedule>0 9 1 * *</schedule>
```
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml` line 1 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NOAZAKNAuJRtIRVXe_r:-NOAZAKNAuJRtIRVXe_s:b-8zfsqe) ([raw file](https://github.com/google/nomulus/blob/b1cd8c5a6fb3dbf7837d71286f202cbe3dfa1d72/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

Have you tested what happens when you deploy an empty cron.xml file? I suspect it should work as expected and delete all existing cron jobs for the project, but it doesn't hurt to test.

The cron jobs are update as part of the spinnaker deployment pipeline here:

https://cs.opensource.google/nomulus/nomulus/+/master:release/cloudbuild-deploy.yaml;l=48?q=cron&ss=nomulus%2Fnomulus

You should be able to verify by running the `gcloud` command yourself, after you convert the `cron.xml` file to `cron.yaml` with `./gradle stage`.

Also, we should add a TODO to delete this file after the next deployment, and remove cron from the link above.

Lastly, we should be changing the files in all environments at the same time. It's bad practice to have them in different state. Do ample testing to make sure they work, and update them altogether.



_Code quote:_
```XML
<?xml version="1.0" encoding="UTF-8"?>
<cronentries>
```
___
*[`core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java` line 22 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NOAXEuh2yaSVRGScNRw:-NOAXEuh2yaSVRGScNRx:b-yvnsii) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java#L22)):*
> ```Java
>  * <p>Currently used by cloud scheduler service account
>  */
> public class ServiceAccountAuthenticationMechanism implements AuthenticationMechanism {
> ```

It seems unnecessary to copy-paste most of the code from `IapHeaderAuthenticationMechanism` here. The new code needs to be reviewed and there's always room for error, even with copy-paste.

The two classes can be merged into just an `IdTokenAuthenticationMechanism`, where you inject the different `TokenVerifier` and a `String Email -> AuthResult result` function that takes care converting the email address that you get from the `TokenVerifier`.



_Code quote:_
```Java
public class ServiceAccountAuthenticationMechanism implements AuthenticationMechanism {
```
___
*[`core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java` line 33 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NOAYvd87yBVlcXrzBZm:-NOAYvd87yBVlcXrzBZn:b-tqtvlh) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java#L33)):*
> ```Java
>   public ServiceAccountAuthenticationMechanism(
>       @Named("serviceAccount") TokenVerifier tokenVerifier,
>       @Config("projectId") String projectId,
> ```

This is not used.



_Code quote:_
```Java
@Config("projectId") String projectId,
```
___
*[`core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java` line 60 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NOAZ-Ng5ZVmoxzcfoN-:-NOAZ-Ng5ZVmoxzcfoN0:b7y794i) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java#L60)):*
> ```Java
>     }
>     String emailAddress = (String) token.getPayload().get("email");
>     if (emailAddress.startsWith(cloudSchedulerEmailPrefix)) {
> ```

Is there any reason to only match the prefix, but not the full string?



_Code quote:_
```Java
if (emailAddress.startsWith(cloudSchedulerEmailPrefix)) {
```
___
*[`release/cloudbuild-deploy.yaml` line 46 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NOB7WMsCtTQTpzJX7z1:-NOB7WMsCtTQTpzJX7z2:br38iu4) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/release/cloudbuild-deploy.yaml#L46) [...]

2023-02-13 20:09 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 111 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NO-w7iX274QTQilZf2R:-NOBFnk7A6fYb1D2ZXuB:b3u9hku) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/config/RegistryConfig.java#L111)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Just provide the whole email address here. Using a prefix only confuses things. It's easier to see what the email is in one place.
</blockquote></details>

The reason for it being a prefix is that service account email address consists of the following - { prefix@ } + { project } + iam.gserviceaccount.com. By making the prefix the same on all platforms (alpha, prod, sandbox, ...) and excluding a variable part (project) from the check we simplify our code and avoid unnecessary boilerplate .
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOBBOABC9q7S0nIQUrV:-NOBH9MaCMup4k1eIhy8:bjy78ut) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L1)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

A few general comment:

1) I didn't realize Cloud Scheduler doesn't have a `cron.xml` or `cron.yaml` equivalent and everything is done via `gcloud` or pantheon.

2) If we are going to make a config file ourselves, there is no need to stick to the xml format that mostly derives from `cron.xml`. I think YAML would be more succinct and readable.

3) Again, if we are making our own config file to parse, we can make a lot of the fields optional. For example, there is no need for `name`, We probably want to make the entire URL configurable (maybe at the root level, so we don't have to write it for every entry), and `method` can be optional with GET being the default. `target` is probably also not needed. We only ever use backend here, and with the migration to GKE, we probably won't have the service name visible to the outside any more. Every endpoint would be on the same domain, with the path being the only differentiating factor. Lastly, the description can be comments in YAML file instead actual fields.
</blockquote></details>

1. Unfortunately that's what it is. I've mentioned in b/239727032 as part of my plan to tackle the task, though at the time I thought it'd be yaml instead of xml
2. I've considered yaml at first, as I even mentioned in my plan for this task in the b/239727032. However the reasoning for using xml instead of yaml are pretty strong:
2.1 xml was used and format is familiar to everyone involved with the project, 
2.2 yaml parser is not part of golang standard library and would require either manual work or 3rd party tools. As I was trying to keep the script minimal I thought it's not worth it
3. Though we can make some fields like `method` and `target` optional, `name` **can not** be optional as cloud scheduler heavily relies on some identifier of the task to create, update and delete them. `URL` is not a good candidate for this job, thus making `name` a good choice for it. To be honest I was wrestling on idea to make `method` and `target` optional but then I decided that it might not be clear enough what's default what's not and I decided it'd make it more straightforward if it was required. 
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 70 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOB9haAC5XLVZeEPYTd:-NOBL9FI3bXmB1q84vPw:bwk9udb) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L70)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Should be 0.
</blockquote></details>

Typo, will fix. Thanks
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 92 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOBB-ve1syunQkEWyfv:-NOBLMP54tEOOpsnGG0n:bnjhmpp) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L92)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The cron job runs on the first monday of the month. Though I doubt it matters.

It would help if we can make a note on any deviation from the cron job schedule.
</blockquote></details>

Unfortunately "every first monday" is not supported by unix cron format, so as I previously mentioned I was trying to be as close as possible to original schedule, but not always exact. This is so far the worst case. Prob will see more in the rest of cron.xml files
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml` line 1 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NOAZAKNAuJRtIRVXe_r:-NOBLsg-08oEGdp_d7XV:b-cglrmv) ([raw file](https://github.com/google/nomulus/blob/b1cd8c5a6fb3dbf7837d71286f202cbe3dfa1d72/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml#L1)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Have you tested what happens when you deploy an empty cron.xml file? I suspect it should work as expected and delete all existing cron jobs for the project, but it doesn't hurt to test.

The cron jobs are update as part of the spinnaker deployment pipeline here:

https://cs.opensource.google/nomulus/nomulus/+/master:release/cloudbuild-deploy.yaml;l=48?q=cron&ss=nomulus%2Fnomulus

You should be able to verify by running the `gcloud` command yourself, after you convert the `cron.xml` file to `cron.yaml` with `./gradle stage`.

Also, we should add a TODO to delete this file after the next deployment, and remove cron from the link above.

Lastly, we should be changing the files in all environments at the same time. It's bad practice to have them in different state. Do ample testing to make sure they work, and update them altogether.
</blockquote></details>

Yes, I tested in alpha and all ae cron jobs got wiped out with this change. 
I will add a todo. 
In this case I feel like a safe path forward is gradual removal. We can discuss the next candidates for removal, but making this change for all envs within the same PR would bloat the change and would require more effort from reviewer, increasing a possibility if missing something and if there's an issue it'd immediately get distributed everywhere. Since we're not in rush I don't think it's worth the risk. However I will submit empty configs for all envs, that should be beneficial for consistent script execution. 
___
*[`core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java` line 22 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NOAXEuh2yaSVRGScNRw:-NOBNZz86wKoUFwUChCv:bnskmqu) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java#L22)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It seems unnecessary to copy-paste most of the code from `IapHeaderAuthenticationMechanism` here. The new code needs to be reviewed and there's always room for error, even with copy-paste.

The two classes can be merged into just an `IdTokenAuthenticationMechanism`, where you inject the different `TokenVerifier` and a `String Email -> AuthResult result` function that take [...]

2023-02-22 21:49 UTC, jianglai requested changes
> Reviewed 1 of 2 files at r3, 8 of 13 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: all files reviewed, 23 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 111 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NO-w7iX274QTQilZf2R:-NOuQeFk4Fwlh5tUH_F6:bq00sk5) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/config/RegistryConfig.java#L111)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

The reason for it being a prefix is that service account email address consists of the following - { prefix@ } + { project } + iam.gserviceaccount.com. By making the prefix the same on all platforms (alpha, prod, sandbox, ...) and excluding a variable part (project) from the check we simplify our code and avoid unnecessary boilerplate .
</blockquote></details>

There's always a trade off between re-usability and code clarity. In this instance I think we gain very little by using a prefix here. Yes you save a few keystrokes when updating the per-environment config files, but the savings do not come from thin air. Instead your Java code needs to handle reconstruction of the email address, at the same time your config file becomes less legible. There's also a mental cost for anyone reading the code to keep track of the reconstruction as well. For example by looking at this code snippet alone, a reader has no idea what the proper domain is to convert the prefix to an email address.

So unless there're a lot of instances where we use service account addresses this way (and there's no guarantee that service account format does not change in the future), it doesn't seem worth it to introduce complexity here just to make the config file a little less crowded.
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOBBOABC9q7S0nIQUrV:-NOuV4F_6aJKl9UcaifD:bltrnnw) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L1)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

1. Unfortunately that's what it is. I've mentioned in b/239727032 as part of my plan to tackle the task, though at the time I thought it'd be yaml instead of xml
2. I've considered yaml at first, as I even mentioned in my plan for this task in the b/239727032. However the reasoning for using xml instead of yaml are pretty strong:
2.1 xml was used and format is familiar to everyone involved with the project, 
2.2 yaml parser is not part of golang standard library and would require either manual work or 3rd party tools. As I was trying to keep the script minimal I thought it's not worth it
3. Though we can make some fields like `method` and `target` optional, `name` **can not** be optional as cloud scheduler heavily relies on some identifier of the task to create, update and delete them. `URL` is not a good candidate for this job, thus making `name` a good choice for it. To be honest I was wrestling on idea to make `method` and `target` optional but then I decided that it might not be clear enough what's default what's not and I decided it'd make it more straightforward if it was required. 
</blockquote></details>

If `name` is what Cloud Scheduler uses as the unique identifier for each task, I guess we will keep it. We should get rid of `target` and include the full URL in the config at least. With the migration to GKE the concert of "target" will be gone (even within GAE, "target" is not really the correct nomenclature -- they are called "service"). It's better to just list the URL here, instead of relying on your deployment script to synthesize the URL, the logic of which you'll have to change anyway.

On keeping `method` so that the default is clear, I don't think it is necessary as we only use GET anyway. But if you do want to keep it, shouldn't it be part of the root element so you don't have to repeat it every time? The same goes for the `timezone` tag, which is only specified in some element, even though I think the default UTC so they are really redundant. If anything `timezone` is more important to be explicit than `method`. If you choose to be explicit, you should specify both of them (at the root and override if necessary, in my opinion).

Regarding YAML vs XML, I wouldn't count "xml was used and the format is familiar with everyone" as a point toward XML's favor. YAML is even more in the project, for example in the project config files, in Cloud Build config files, in k8s config files for the proxy, etc. There's certainly no barrier to entry to use YAML. In fact, I think GCP is actively [moving toward YAML](https://cloud.google.com/sdk/gcloud/reference/beta/app/migrate-config).

In the future, I think we'd have most of our configs in YAML as opposed to XML. The Gradle GAE plugin already converts the app engine related XMLs to YAMLs before calling `gcloud` to deploy them.  You can probably do the same and call the convert subcommand mentioned above to convert the cron.xml files to YAML before editing them.

The concern regarding golang not supporting YAML natively, isn't it as simple is importing the appropriate library (like this one: https://github.com/go-yaml/yaml)?

Ultimately I prefer YAML to XML, but it's more or less a personal preference. If you stick to XML, there's no need to stick with tags like `cronentries` or `cron`, where `taskentries` and `task` are probably more appropriate.
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 70 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOB9haAC5XLVZeEPYTd:-NOuOigBBuvIyA3qTZu7:b-387fno) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L70)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Fix submitted
</blockquote></details>

Just as a general FYI, there's no need to reply to comments before the code change is in. When a reply is made, reviewable notifies the other party but there's really nothing to review until the code change is also there.
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 92 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOBB-ve1syunQkEWyfv:-NOuP3in2D797U07re2Z:b-26x2gd) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L92)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Unfortunately "every first monday" is not supported by unix cron format, so as I previously mentioned I was trying to be as close as possible to original schedule, but not always exact. This is so far the worst case. Prob will see more in the rest of cron.xml files
</blockquote></details>

Yes, I understand that it's not possible to do "every first monday" and it's most likely fine for the majority of the jobs affected. I'm just saying that whenever there's a discrepancy we should make a note to that effect so it's easier to tell where the discrepancies are.
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 129 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOv0tI46JC9aJrOSAdx:-NOv0tI5AGJw_NXeqkvj:b-n5j9wd) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L129)):*
> ``` [...]

2023-02-27 18:58 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: 8 of 21 files reviewed, 23 unresolved discussions (waiting on @gbrodman, @jianglai, and @weiminyu)

___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 111 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NO-w7iX274QTQilZf2R:-NPIZHyiDe9e8bMWgETp:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/config/RegistryConfig.java#L111)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

There's always a trade off between re-usability and code clarity. In this instance I think we gain very little by using a prefix here. Yes you save a few keystrokes when updating the per-environment config files, but the savings do not come from thin air. Instead your Java code needs to handle reconstruction of the email address, at the same time your config file becomes less legible. There's also a mental cost for anyone reading the code to keep track of the reconstruction as well. For example by looking at this code snippet alone, a reader has no idea what the proper domain is to convert the prefix to an email address.

So unless there're a lot of instances where we use service account addresses this way (and there's no guarantee that service account format does not change in the future), it doesn't seem worth it to introduce complexity here just to make the config file a little less crowded.
</blockquote></details>

Updated
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOBBOABC9q7S0nIQUrV:-NPInYa-9cy8bf20a9NY:b97zzys) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L1)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

If `name` is what Cloud Scheduler uses as the unique identifier for each task, I guess we will keep it. We should get rid of `target` and include the full URL in the config at least. With the migration to GKE the concert of "target" will be gone (even within GAE, "target" is not really the correct nomenclature -- they are called "service"). It's better to just list the URL here, instead of relying on your deployment script to synthesize the URL, the logic of which you'll have to change anyway.

On keeping `method` so that the default is clear, I don't think it is necessary as we only use GET anyway. But if you do want to keep it, shouldn't it be part of the root element so you don't have to repeat it every time? The same goes for the `timezone` tag, which is only specified in some element, even though I think the default UTC so they are really redundant. If anything `timezone` is more important to be explicit than `method`. If you choose to be explicit, you should specify both of them (at the root and override if necessary, in my opinion).

Regarding YAML vs XML, I wouldn't count "xml was used and the format is familiar with everyone" as a point toward XML's favor. YAML is even more in the project, for example in the project config files, in Cloud Build config files, in k8s config files for the proxy, etc. There's certainly no barrier to entry to use YAML. In fact, I think GCP is actively [moving toward YAML](https://cloud.google.com/sdk/gcloud/reference/beta/app/migrate-config).

In the future, I think we'd have most of our configs in YAML as opposed to XML. The Gradle GAE plugin already converts the app engine related XMLs to YAMLs before calling `gcloud` to deploy them.  You can probably do the same and call the convert subcommand mentioned above to convert the cron.xml files to YAML before editing them.

The concern regarding golang not supporting YAML natively, isn't it as simple is importing the appropriate library (like this one: https://github.com/go-yaml/yaml)?

Ultimately I prefer YAML to XML, but it's more or less a personal preference. If you stick to XML, there's no need to stick with tags like `cronentries` or `cron`, where `taskentries` and `task` are probably more appropriate.
</blockquote></details>

In this particular case, there's no benefit of yaml over xml and "as simple as importing a library" is not as simple as **not** importing the library 
Updated tags and removed default tags.
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 92 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOBB-ve1syunQkEWyfv:-NP3uQpP5O4OzfnRatEe:b-896fix) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L92)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Yes, I understand that it's not possible to do "every first monday" and it's most likely fine for the majority of the jobs affected. I'm just saying that whenever there's a discrepancy we should make a note to that effect so it's easier to tell where the discrepancies are.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 129 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOv0tI46JC9aJrOSAdx:-NP3uT2L3gFt6v9UBkbZ:ba3dfob) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L129)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is it actually being used anywhere?
</blockquote></details>

Removed
___
*[`core/src/main/java/google/registry/env/crash/default/WEB-INF/cloud-scheduler-tasks.xml` line 127 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuiRD-0x0xPQ8YgGwj:-NP3uirY0ZEFaRhulXSe:b-896fix) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/crash/default/WEB-INF/cloud-scheduler-tasks.xml#L127)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

14. Though in reality it's the same as there is only one 14th hour each day.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml` line 24 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuiz8U0e6pRiC_q-U1:-NP3vAZB-5WdCGTtFR0M:b-896fix) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml#L24)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Isn't this the same as `*/8`?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml` line 71 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuj5H8AMxH5cdsaRnI:-NP3vCuZ-TLICs2v1PAw:b-896fix) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml#L71)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

`*/12`?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml` line 108 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOujVbrAhDvtrpiDhez:-NP3vndy5_PuqGv0lTnE:bs9gjpm) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml#L108)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i [...]

2023-02-28 16:41 UTC, jianglai requested changes
> Reviewed 11 of 13 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: 20 of 21 files reviewed, 10 unresolved discussions (waiting on @gbrodman, @ptkach, and @weiminyu)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 25 at r7](https://reviewable.io/reviews/google/nomulus/1939#-NPNSADuENXrhQVitAvk:-NPNSADuENXrhQVitAvl:b9a3ufh) ([raw file](https://github.com/google/nomulus/blob/abdae93bb7d33910e50321254f3574fb7b6cc6d8/core/src/main/java/google/registry/config/files/default-config.yaml#L25)):*
> ```YAML
>   toolsServiceUrl: https://localhost
>   pubapiServiceUrl: https://localhost
>   # Cloud scheduler email
> ```

"Service account used by Cloud Scheduler to send authenticated requests."



_Code quote:_
```YAML
Cloud scheduler email
```
___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 1 at r2](https://reviewable.io/reviews/google/nomulus/1939#-NOBBOABC9q7S0nIQUrV:-NPNSJApC5gvkW-HGEju:b9gwbpy) ([raw file](https://github.com/google/nomulus/blob/783b962a6083a34f78b9d21b23d3643e2bb7f88b/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L1)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

In this particular case, there's no benefit of yaml over xml and "as simple as importing a library" is not as simple as **not** importing the library 
Updated tags and removed default tags.
</blockquote></details>

Well, in general I don't think it's a big issue to rely on third party libraries, our Java code has many dependencies. So I would not count "having to import a library" as a negative.

But sure, as long as XML works, I don't feel strongly either way.
___
*[`core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml` line 71 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuj5H8AMxH5cdsaRnI:-NPNTe7L3RzTnanjHorI:b-a5y0d7) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml#L71)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you forgot to actually update this one.
___
*[`core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml` line 91 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOumju---kr8axSQdNK:-NPNU-jo1at3EEXFX-eh:b50mb7c) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L91)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Same as prod - it should be a separate PR for the same reasons . Added a todo
</blockquote></details>

Where's the TODO?
___
*[`core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java` line 60 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NOAZ-Ng5ZVmoxzcfoN-:-NPNUlzP8Fq2UCwp8AOy:b-7y1x5o) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java#L60)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Updated, but just to clarify - can you please explain why is it insecure? As far as I understand the config, where it's stored, is not public, so the only thing exposed is a variable name. Thanks
</blockquote></details>

Yes, the actual prefix is private, but it is still prone to brute force attacks. If you check for the whole email address, an attacker would have no way to fake a JWT with an email that ends with a domain that they do not control.
___
*[`release/cloudbuild-deploy.yaml` line 46 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuv56XAT7ge2WnUil3:-NPNXRdz44mYYA3LtTNZ:b-g6yq8m) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/cloudbuild-deploy.yaml#L46)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I know, it's as good as any other place, but it's also where the cron config used to be, so kinda I'd expect to find a new config there as well . 
</blockquote></details>

Well, they'll need to be moved out of `WEB-INF` anyway after the migration as they are not part of the Java servlet. The only reason that they are there is because added requirements from GAE.
___
*[`release/cloudbuild-deploy.yaml` line 57 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuwUX0EInDJNAHHWfJ:-NPN_6Og2ydpyJ8xN4G7:blhcnfu) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/cloudbuild-deploy.yaml#L57)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Removed
</blockquote></details>

Does it still work? The variable `project_id` used below in the for loop should not persist between steps, that's why I suggested saving it in a text file and read from it.



_Code quote:_
```YAML
PROJECT_ID
```
___
*[`release/builder/cloudSchedulerDeployer.go` line 96 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuy6Rb-ixeH9i1ndBs:-NPN_Y8OBYn4D__HceBR:bzhgzq6) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/builder/cloudSchedulerDeployer.go#L96)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

The reason it's hardcoded is that it's not available at the time of the deployment anywhere but in the actual file. Parsing the file to get the value is an overkill. 
I checked all tags we currently provde and I don't see any resembling a location. Providing a tag with location only to pass it down to the script is no better than actually having it in the script, at least for me it'd be easier to find if we ever need to change it. 
We can omit it alltogether, which would always default to App Engine default location if it's available. However as soon as we deprecate App Engine we will be back to square 1. 

Let me know if you have a better idea. 
</blockquote></details>

It can be an argument that you pass to this script. When you call the script from Cloud Build, the variable can be defined in the GCB config script, or it can be passed in from the GCB trigger that runs the job.
___
*[`release/builder/cloudSchedulerDeployer.go` line 118 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOv-lBXEAwok8n8bibd:-NPNn83--O8JrLS3p3gH:b-gh1rl2) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/builder/cloudSchedulerDeployer.go#L118)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Nope, there's no such thing in golang stdlib. 
I've considered it, from code perspective it'd be easier, otherwise it's not a good idea:
- What if the task is currently running or about to run the moment we delete it for no reason, before creating it again? 
- What if deletion is successfull, but recreation fails? This is not an issue in the current implementation 
- Performance wise it's worse. Consider the case like 100 tasks had been created long ago, updated config got 99 tasks

Which is why I believe current approach is better.
</blockquote></details>

It seems like picking something like Python would be easier as it supports set difference and you also have extensibility from PIP. But I digress...

Regarding the three points, I think 1 and 3 are not big concerns because all Cloud Scheduler does is to send HTTP requests, which in itself shouldn't take too long. Even in case where the server takes time to respond and therefore holding on to the connection, Cloud Scheduler *should* be smart enough to not abruptly  [...]

2023-02-28 17:54 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: 20 of 21 files reviewed, 12 unresolved discussions (waiting on @gbrodman, @jianglai, and @ptkach)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 26 at r8](https://reviewable.io/reviews/google/nomulus/1939#-NPO-njBCQufgBy3DBCJ:-NPO-njBCQufgBy3DBCK:bxwfvn9) ([raw file](https://github.com/google/nomulus/blob/76151b91e1f99a4cef407aa1f909e98c0e82034f/core/src/main/java/google/registry/config/files/default-config.yaml#L26)):*
> ```YAML
>   pubapiServiceUrl: https://localhost
>   # Cloud scheduler email
>   cloudSchedulerServiceAccountEmail: cloud-scheduler-email@email.com
> ```

Have the real configs in nomulus-internal been updated already?



_Code quote:_
```YAML
cloudSchedulerServiceAccountEmail: cloud-scheduler-email@email.com
```
___
*[`core/src/main/java/google/registry/request/auth/AuthModule.java` line 25 at r8](https://reviewable.io/reviews/google/nomulus/1939#-NPO7rkh2t_9P3TlWxAK:-NPO7rkh2t_9P3TlWxAL:baxb0wp) ([raw file](https://github.com/google/nomulus/blob/76151b91e1f99a4cef407aa1f909e98c0e82034f/core/src/main/java/google/registry/request/auth/AuthModule.java#L25)):*
> ```Java
> import google.registry.config.RegistryConfig.Config;
> import javax.inject.Named;
> import javax.inject.Singleton;
> ```

Please avoid introducing new string-based annotation.

See go/di-practices/prefer-custom-qualifiers 

Its guice-centric but still relevant.



_Code quote:_
```Java
Named
```


<!-- Sent from Reviewable.io -->

2023-02-28 19:00 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: 14 of 21 files reviewed, 12 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], @jianglai, and @weiminyu)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 25 at r7](https://reviewable.io/reviews/google/nomulus/1939#-NPNSADuENXrhQVitAvk:-NPO0KsS48GC8afq5PO3:b-896fix) ([raw file](https://github.com/google/nomulus/blob/abdae93bb7d33910e50321254f3574fb7b6cc6d8/core/src/main/java/google/registry/config/files/default-config.yaml#L25)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

"Service account used by Cloud Scheduler to send authenticated requests."
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 26 at r8](https://reviewable.io/reviews/google/nomulus/1939#-NPO-njBCQufgBy3DBCJ:-NPOJiEEEhu3sq4-R6ay:b-d3pawk) ([raw file](https://github.com/google/nomulus/blob/76151b91e1f99a4cef407aa1f909e98c0e82034f/core/src/main/java/google/registry/config/files/default-config.yaml#L26)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Have the real configs in nomulus-internal been updated already?
</blockquote></details>

Yes, added you to the CR
___
*[`core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml` line 71 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuj5H8AMxH5cdsaRnI:-NPO0eP4BS6Iwdqyw2fe:b-896fix) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml#L71)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I think you forgot to actually update this one.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml` line 91 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOumju---kr8axSQdNK:-NPO0j026zda92rriJgf:b-xxp6xm) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L91)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Where's the TODO?
</blockquote></details>

https://github.com/google/nomulus/blob/76151b91e1f99a4cef407aa1f909e98c0e82034f/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L135
___
*[`core/src/main/java/google/registry/request/auth/AuthModule.java` line 25 at r8](https://reviewable.io/reviews/google/nomulus/1939#-NPO7rkh2t_9P3TlWxAK:-NPOMP9XC0JrbNKqI1o1:bnpykjp) ([raw file](https://github.com/google/nomulus/blob/76151b91e1f99a4cef407aa1f909e98c0e82034f/core/src/main/java/google/registry/request/auth/AuthModule.java#L25)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Please avoid introducing new string-based annotation.

See go/di-practices/prefer-custom-qualifiers 

Its guice-centric but still relevant.


</blockquote></details>

Good suggestion, updated
___
*[`core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java` line 60 at r1](https://reviewable.io/reviews/google/nomulus/1939#-NOAZ-Ng5ZVmoxzcfoN-:-NPO1d6W5yunFgCwbdnQ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d7ae4027b28728b3b2887c6b54be5a5f8eaab07a/core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java#L60)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Yes, the actual prefix is private, but it is still prone to brute force attacks. If you check for the whole email address, an attacker would have no way to fake a JWT with an email that ends with a domain that they do not control.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java` line 56 at r6](https://reviewable.io/reviews/google/nomulus/1939#-NNwsBsrM9ZydtJk5s5s-r6-56:-NPO1eTX7NHunjVC26-r:b-896fix) ([raw file](https://github.com/google/nomulus/blob/95d2234308c50faf2435c5709d7b74599a91b54a/core/src/main/java/google/registry/request/auth/ServiceAccountAuthenticationMechanism.java#L56)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Reference equality test on strings

String values compared with  == .

[Show more details](https://github.com/google/nomulus/security/code-scanning/768)
</blockquote></details>

Done.
___
*[`release/cloudbuild-deploy.yaml` line 46 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuv56XAT7ge2WnUil3:-NPOFAPJ1_A7wlctsOTX:b-qfd0hc) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/cloudbuild-deploy.yaml#L46)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Well, they'll need to be moved out of `WEB-INF` anyway after the migration as they are not part of the Java servlet. The only reason that they are there is because added requirements from GAE.
</blockquote></details>

I don't think we're going to stop using servlets, we're just going to stop using app engine as a servlet container. Aside from that any other location would require some separate copy/paste efforts in order for it be accessed by the deployer script, not sure that's necessary, given that we can access the files with approach "free of charge" so to say. 
___
*[`release/cloudbuild-deploy.yaml` line 57 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuwUX0EInDJNAHHWfJ:-NPOGQtu6jNtaX-PomUt:b-7kwk2f) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/cloudbuild-deploy.yaml#L57)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Does it still work? The variable `project_id` used below in the for loop should not persist between steps, that's why I suggested saving it in a text file and read from it.
</blockquote></details>

Correct, upon testing I noticed that it's breaking. Parsing the file to get the PROJECT_ID doesn't feel efficient, so that can stay, but I'm removing the bottleneck which is ```gcutil cp``` and ```tar -xvf``` here, that should make it better. 
___
*[`release/builder/cloudSchedulerDeployer.go` line 96 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuy6Rb-ixeH9i1ndBs:-NPOHHsQ47KqatFoJDnM:b8t2hgg) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/builder/cloudSchedulerDeployer.go#L96)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It can be an argument that you pass to this script. When you call the script from Cloud Build, the variable can be defined in the GCB config script, or it can be passed in from the GCB trigger that runs the job.
</blockquote></details>

Yes, but the argument I'm making is that it's no better that having it in the script itself. Plus that'd make triggering cloud build locally more complicated as it'd require taking care of one more variable (tag?) . 
___
*[`release/builder/cloudSchedulerDeployer.go` line 118 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOv-lBXEAwok8n8bibd:-NPOIKAe4_dq_-42VJTY:b-8b1kp6) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/builder/cloudSchedulerDeployer.go#L118)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It seems like picking something like Python would be easier as it supports set difference and you also have extensibility from PIP. But I digress...

Regarding the three points, I think 1 and 3 are not big concerns because all Cloud Scheduler does is to send HTTP requests, which in itself shouldn' [...]

2023-02-28 20:12 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: 14 of 21 files reviewed, 12 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], @jianglai, and @weiminyu)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 26 at r8](https://reviewable.io/reviews/google/nomulus/1939#-NPO-njBCQufgBy3DBCJ:-NPOdWVUAuObFeBOkUM_:bllr9s2) ([raw file](https://github.com/google/nomulus/blob/76151b91e1f99a4cef407aa1f909e98c0e82034f/core/src/main/java/google/registry/config/files/default-config.yaml#L26)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Yes, added you to the CR
</blockquote></details>

Also to expand on that - I've already created corresponding service accounts for all environments. However it's hard to test service account in prod without releasing, so I hope I've not missed any permissions there. 


<!-- Sent from Reviewable.io -->

2023-03-01 18:26 UTC, jianglai approved these changes
> Reviewed 1 of 1 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], and @weiminyu)

___
*[`core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml` line 91 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOumju---kr8axSQdNK:-NPSs9VG1rubSrBExusJ:b-epsz6w) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L91)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

https://github.com/google/nomulus/blob/76151b91e1f99a4cef407aa1f909e98c0e82034f/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L135
</blockquote></details>

Hmm, for some reason reviewable is not showing this diff for me...
___
*[`core/src/main/java/google/registry/request/auth/AuthModule.java` line 25 at r8](https://reviewable.io/reviews/google/nomulus/1939#-NPO7rkh2t_9P3TlWxAK:-NPSsgJf7fuhk9JGOYFR:bg933w8) ([raw file](https://github.com/google/nomulus/blob/76151b91e1f99a4cef407aa1f909e98c0e82034f/core/src/main/java/google/registry/request/auth/AuthModule.java#L25)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Good suggestion, updated
</blockquote></details>

To be fair, qualifiers like this should be their own annotations, but bindings from config can and should probably still be `@Named("some-string")`,
___
*[`release/cloudbuild-deploy.yaml` line 46 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuv56XAT7ge2WnUil3:-NPT0bnUBoSAKZ0uusMB:b-ev6wo5) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/cloudbuild-deploy.yaml#L46)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I don't think we're going to stop using servlets, we're just going to stop using app engine as a servlet container. Aside from that any other location would require some separate copy/paste efforts in order for it be accessed by the deployer script, not sure that's necessary, given that we can access the files with approach "free of charge" so to say. 
</blockquote></details>

Why would it require a separate "copy/paste" effort? We [control](https://cs.opensource.google/nomulus/nomulus/+/master:release/build_nomulus_for_env.sh) what goes in the deployment tarball so we can just put whatever we need there.

It just feels a bit off to put some random config file where it doesn't need to be. I guess it can stay here for now so that we can get this PR out of the door. But also remember that anything that you put in `WEB-INF` gets packaged in your servlet, even though these files are not needed at runtime. When we get to the point where we actually are making GKE images, we may think about moving (more) files around because they don't have to be constrained by GAE's requirements.
___
*[`release/builder/cloudSchedulerDeployer.go` line 96 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuy6Rb-ixeH9i1ndBs:-NPT2hia5n7bevSKCExU:bxqawg2) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/builder/cloudSchedulerDeployer.go#L96)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Yes, but the argument I'm making is that it's no better that having it in the script itself. Plus that'd make triggering cloud build locally more complicated as it'd require taking care of one more variable (tag?) . 
</blockquote></details>

Well, there would always be a trade off between flexibility and easy of use. I wouldn't call having to add another substitution when triggering a local build "more difficult".

But in any case, this probably won't matter much it only controls where the request is coming from (I assume)? Maybe if someone only runs a registry in Europe, they would like the request to be sent from Europe, but for us it doesn't make much of a difference because 1) Right now GAE runs in us-central1 and 2) in the future we would have multiple PoPs for GKE using Cloud Load Balancer.


<!-- Sent from Reviewable.io -->

2023-03-01 18:31 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], and @weiminyu)

___
*[`core/src/main/java/google/registry/request/auth/AuthModule.java` line 25 at r8](https://reviewable.io/reviews/google/nomulus/1939#-NPO7rkh2t_9P3TlWxAK:-NPTRQwS26zU2HicNO6C:bqy67xj) ([raw file](https://github.com/google/nomulus/blob/76151b91e1f99a4cef407aa1f909e98c0e82034f/core/src/main/java/google/registry/request/auth/AuthModule.java#L25)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

To be fair, qualifiers like this should be their own annotations, but bindings from config can and should probably still be `@Named("some-string")`,
</blockquote></details>

Fair enough
___
*[`release/cloudbuild-deploy.yaml` line 46 at r5](https://reviewable.io/reviews/google/nomulus/1939#-NOuv56XAT7ge2WnUil3:-NPTR0Op0D2t1hNF033N:b-hfghm4) ([raw file](https://github.com/google/nomulus/blob/00e5b7b571ac6c6692b60b285d6053e8a3837e2b/release/cloudbuild-deploy.yaml#L46)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Why would it require a separate "copy/paste" effort? We [control](https://cs.opensource.google/nomulus/nomulus/+/master:release/build_nomulus_for_env.sh) what goes in the deployment tarball so we can just put whatever we need there.

It just feels a bit off to put some random config file where it doesn't need to be. I guess it can stay here for now so that we can get this PR out of the door. But also remember that anything that you put in `WEB-INF` gets packaged in your servlet, even though these files are not needed at runtime. When we get to the point where we actually are making GKE images, we may think about moving (more) files around because they don't have to be constrained by GAE's requirements.
</blockquote></details>

Sounds good


<!-- Sent from Reviewable.io -->

2023-03-01 18:33 UTC, weiminyu approved these changes
> Reviewed 1 of 13 files at r4, 4 of 9 files at r5, 7 of 13 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1939)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @github-code-scanning[bot])



<!-- Sent from Reviewable.io -->

2023-03-01 18:40 UTC, merged