dns refresh entity
google/nomulus pull request #1941
Opened 2023-02-22 18:22 UTC by jianglai

- Add a table to record EPP resources needing DNS refresh
- Create a DnsRefreshRequest entity backed by the corresponding table

2023-03-01 21:15 UTC, jianglai reviewed
> Reviewed 8 of 8 files at r1, 5 of 5 files at r2, 1 of 14 files at r3, 42 of 42 files at r4, 15 of 15 files at r5, all commit messages.
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-03-02 18:51 UTC, jianglai reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2023-03-09 14:41 UTC, jianglai reviewed
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2023-03-09 14:41 UTC, jianglai reviewed
Gentle ping.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941#-:-NQ5oSi23iol7kP1Ge9D:bq2fntq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2023-03-13 14:11 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2023-03-13 15:47 UTC, gbrodman requested changes
> Reviewed 1 of 8 files at r1, 5 of 5 files at r2, 1 of 14 files at r3, 28 of 42 files at r4, 12 of 15 files at r5, 1 of 3 files at r6, 2 of 2 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: all files reviewed, 7 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/dns/DnsQueue.java` line 115 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQa8WkEMn_T5b5K2IP:-NQQa8WkEMn_T5b5K2IQ:bjm0nsd) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/dns/DnsQueue.java#L115)):*
> ```Java
> 
>   /** Adds a task to the queue to refresh the DNS information for the specified subordinate host. */
>   protected TaskHandle addHostRefreshTask(String hostName) {
> ```

I might be missing it, but does anything extend this / is there any reason to make these methods protected? 
___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 717 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQaY6vCSbpq9owHIjT:-NQQaY6vCSbpq9owHIjU:b-k22g0l) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L717)):*
> ```Java
>       dnsUtils.requestDomainDnsRefresh(newDomain.getDomainName());
>     }
>     if (!(DatabaseMigrationStateSchedule.getValueAtTime(tm().getTransactionTime())
> ```

hmm it feels like there must be a better way of doing this, especially if we keep adding more states in the future 

Maybe something using the ordering of the states to see if we are currently at-or-after a particular state (in this case, NORDN_SQL)? 

To be honest, at some point we may want to change it to be a feature-flag system rather than a single map with stages. 
___
*[`core/src/main/java/google/registry/model/common/DnsRefreshRequest.java` line 59 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQdZ1j2t9PoV4WLNKD:-NQQdZ1j2t9PoV4WLNKE:bab4m5i) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/model/common/DnsRefreshRequest.java#L59)):*
> ```Java
> 
>   @Column(nullable = false)
>   private DateTime processTime;
> ```

the naming of this is vague, since it could be referring to something either in the past or the future 

something like `lastProcessedTime` would be clearer as to exactly what it's referring to (this would apply for the things like messages that refer to this variable too of course)
___
*[`core/src/test/java/google/registry/dns/DnsUtilsTest.java` line 149 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQbzr29Ms7QX2_tgX5:-NQQbzr29Ms7QX2_tgX6:bbdv4a3) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/dns/DnsUtilsTest.java#L149)):*
> ```Java
>   }
> 
>   private static void useDnsSql() {
> ```

what's up with this method? we shouldn't need all these calls 
___
*[`core/src/test/java/google/registry/dns/RefreshDnsOnHostRenameActionTest.java` line 63 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQcGKk6OEsvWBmIfF6:-NQQcGKk6OEsvWBmIfF7:bb69l0f) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/dns/RefreshDnsOnHostRenameActionTest.java#L63)):*
> ```Java
>     createTld("tld");
>   }
> ```

extra newline
___
*[`core/src/test/java/google/registry/model/common/DnsRefreshRequestTest.java` line 36 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQcZ5P9pxBzzLlUPQl:-NQQcZ5P9pxBzzLlUPQm:b-aexbm6) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/model/common/DnsRefreshRequestTest.java#L36)):*
> ```Java
>   }
> 
>   DnsRefreshRequest request;
> ```

nit: "private", and also I don't see any reason why we couldn't just create the request here inline 
___
*[`core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java` line 91 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQcs2f2AF--bTrmtL5:-NQQcs2f2AF--bTrmtL6:b-8fbynr) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java#L91)):*
> ```Java
>   DomainSqlTest.class,
>   DomainHistoryTest.class,
>   DnsRefreshRequestTest.class,
> ```

nit: alphabetization 


<!-- Sent from Reviewable.io -->

2023-03-13 19:45 UTC, jianglai reviewed
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/dns/DnsQueue.java` line 115 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQa8WkEMn_T5b5K2IP:-NQRCg8XA3Hz3b9PD-Wv:ba2jxvb) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/dns/DnsQueue.java#L115)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I might be missing it, but does anything extend this / is there any reason to make these methods protected? 
</blockquote></details>

I made it protected so that only the newly added `DnsUtils` can use it. The goal is to not call this method directly and rely on `DnsUtils` because the latter is able to decide whether to use the pull queue-based or the SQL-based flow based on the current time and the database migration schedule.
___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 717 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQaY6vCSbpq9owHIjT:-NQRDNzF5SaJb9DB9tZ7:bfpqe4r) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L717)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

hmm it feels like there must be a better way of doing this, especially if we keep adding more states in the future 

Maybe something using the ordering of the states to see if we are currently at-or-after a particular state (in this case, NORDN_SQL)? 

To be honest, at some point we may want to change it to be a feature-flag system rather than a single map with stages. 
</blockquote></details>

I completely agree with you that this is ugly as ****. As you said the best way to handle this to make `DatabaseMigrationStateSchedule` support `isBefore(MigrationState)`/`isAfter(MigrationState)`.

However the migration state schedule class is never meant for this and we kind of shoehorned it in there to give us the ability to set a flag at a given time (again, like you suggested). The switching logic regarding Nordn will be deleted as soon as we confirm that SQL mode is working properly on production.

It might be worth considering if we want to set up a proper flag system (with time triggers) so that we can turn on features orthogonally. For now I think the best way forward is to piggy back on the migration schedule, which we intentionally didn't delete because of one-off migration related switches like this. I don't foresee us needing it any more after the Nordn and DNS SQL migration.
___
*[`core/src/main/java/google/registry/model/common/DnsRefreshRequest.java` line 59 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQdZ1j2t9PoV4WLNKD:-NQRTZNo54SfXEXEjk6l:bjnfoyb) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/model/common/DnsRefreshRequest.java#L59)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

the naming of this is vague, since it could be referring to something either in the past or the future 

something like `lastProcessedTime` would be clearer as to exactly what it's referring to (this would apply for the things like messages that refer to this variable too of course)
</blockquote></details>

Yeah, `lastProcessedTime` is probably a more apt name. I did explain what this field is supposed to store in the getter method's javadoc. If we change the name now, we'd need to do another schema deployment (unless we want to update the filed name but not update the column name accordingly, which seems like a bad idea).

I kinda feel that it could work as is, unless you feel strongly that we should change the name.
___
*[`core/src/test/java/google/registry/dns/DnsUtilsTest.java` line 149 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQbzr29Ms7QX2_tgX5:-NQRIpP820tfWGjfOR1N:b-d31l39) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/dns/DnsUtilsTest.java#L149)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what's up with this method? we shouldn't need all these calls 
</blockquote></details>

We do need it because otherwise the `DnsUtils` will always use the pull queue mode in tests. We have to configure the migration schedule so to control which mode to use.
___
*[`core/src/test/java/google/registry/dns/RefreshDnsOnHostRenameActionTest.java` line 63 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQcGKk6OEsvWBmIfF6:-NQRJC7pA7UKB85sZw1w:b-896fix) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/dns/RefreshDnsOnHostRenameActionTest.java#L63)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

extra newline
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/model/common/DnsRefreshRequestTest.java` line 36 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQcZ5P9pxBzzLlUPQl:-NQRVP7gB-WZzf7hBo7e:b-896fix) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/model/common/DnsRefreshRequestTest.java#L36)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit: "private", and also I don't see any reason why we couldn't just create the request here inline 
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java` line 91 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQcs2f2AF--bTrmtL5:-NQRJMTw6m1wxFnO-2sd:b-kl8g4c) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java#L91)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit: alphabetization 
</blockquote></details>

good catch!


<!-- Sent from Reviewable.io -->

2023-03-14 14:44 UTC, gbrodman requested changes
> Reviewed 3 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: all files reviewed, 4 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/dns/DnsQueue.java` line 115 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQa8WkEMn_T5b5K2IP:-NQRXrqbCmTRDwbUKdIN:bctlzm0) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/dns/DnsQueue.java#L115)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I made it protected so that only the newly added `DnsUtils` can use it. The goal is to not call this method directly and rely on `DnsUtils` because the latter is able to decide whether to use the pull queue-based or the SQL-based flow based on the current time and the database migration schedule.
</blockquote></details>

Oh I see, can we make it package-private instead then? I was confused because I was like "wait, this class doesn't have any subclasses" so I thought it might have been a typo or something. 
___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 717 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQaY6vCSbpq9owHIjT:-NQVVZ0t8BvSgMxG8OSU:b-e35evn) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L717)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I completely agree with you that this is ugly as ****. As you said the best way to handle this to make `DatabaseMigrationStateSchedule` support `isBefore(MigrationState)`/`isAfter(MigrationState)`.

However the migration state schedule class is never meant for this and we kind of shoehorned it in there to give us the ability to set a flag at a given time (again, like you suggested). The switching logic regarding Nordn will be deleted as soon as we confirm that SQL mode is working properly on production.

It might be worth considering if we want to set up a proper flag system (with time triggers) so that we can turn on features orthogonally. For now I think the best way forward is to piggy back on the migration schedule, which we intentionally didn't delete because of one-off migration related switches like this. I don't foresee us needing it any more after the Nordn and DNS SQL migration.
</blockquote></details>

yeah I think the pull queue migration(s) are hopefully the last time we need it :( 
___
*[`core/src/main/java/google/registry/model/common/DnsRefreshRequest.java` line 59 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQdZ1j2t9PoV4WLNKD:-NQVYnzr5ihCIM7SQFSb:byas5z6) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/model/common/DnsRefreshRequest.java#L59)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Yeah, `lastProcessedTime` is probably a more apt name. I did explain what this field is supposed to store in the getter method's javadoc. If we change the name now, we'd need to do another schema deployment (unless we want to update the filed name but not update the column name accordingly, which seems like a bad idea).

I kinda feel that it could work as is, unless you feel strongly that we should change the name.
</blockquote></details>

yeah, unfortunately I think we should probably change it since (hopefully) this will be around forever, right? 

If it sounds good to you, we could easily do that schema change today and then a second release this week so that we can merge this PR in before the end of the week?

sorry about this, I recognize it's inconvenient 
___
*[`core/src/test/java/google/registry/dns/DnsUtilsTest.java` line 149 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQbzr29Ms7QX2_tgX5:-NQVW1nu5xCKNGz0lr2o:b-7qeeps) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/dns/DnsUtilsTest.java#L149)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

We do need it because otherwise the `DnsUtils` will always use the pull queue mode in tests. We have to configure the migration schedule so to control which mode to use.
</blockquote></details>

My point is that I wouldn't expect that it would require multiple calls, since you're just overwriting the schedule each time 


<!-- Sent from Reviewable.io -->

2023-03-14 17:48 UTC, jianglai reviewed
> Reviewed 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: all files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/dns/DnsQueue.java` line 115 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQa8WkEMn_T5b5K2IP:-NQVbASX0cKESJ1HFMQj:b-qweozj) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/dns/DnsQueue.java#L115)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Oh I see, can we make it package-private instead then? I was confused because I was like "wait, this class doesn't have any subclasses" so I thought it might have been a typo or something. 
</blockquote></details>

You are right, they should have been package-private.
___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 717 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQaY6vCSbpq9owHIjT:-NQVbNMQ56l1tlESnVAU:b-gj224x) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L717)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah I think the pull queue migration(s) are hopefully the last time we need it :( 
</blockquote></details>

Made b/273512400 to track the feature request to implement a flag system.
___
*[`core/src/main/java/google/registry/model/common/DnsRefreshRequest.java` line 59 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQdZ1j2t9PoV4WLNKD:-NQViC9t97E5cIMHd1cU:bby8ebf) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/model/common/DnsRefreshRequest.java#L59)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah, unfortunately I think we should probably change it since (hopefully) this will be around forever, right? 

If it sounds good to you, we could easily do that schema change today and then a second release this week so that we can merge this PR in before the end of the week?

sorry about this, I recognize it's inconvenient 
</blockquote></details>

That's fine. I'll be out for the next two weeks and it's unlikely that the whole migration will be done before EOW anyway. The good thing is that this column is not used yet so there's need for a data migration.

Created #1962 to rename the column. Note that this PR currently contains changes in #1962, which would be diffbased away once #1962 is merged.
___
*[`core/src/test/java/google/registry/dns/DnsUtilsTest.java` line 149 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQbzr29Ms7QX2_tgX5:-NQViaj3BNF5tneT7UCd:bvupnl6) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/dns/DnsUtilsTest.java#L149)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

My point is that I wouldn't expect that it would require multiple calls, since you're just overwriting the schedule each time 
</blockquote></details>

You'd think so :P but no, `DatabaseMigrationStateSchedule` also checks that you only transition to the next state from your current state as of now, in the new schedule. Since the time is set to 2020, we cannot add the entire schedule at once because that would make us jump directly from the initial state (`DATASTORE_ONLY`) to the latest state in the new schedule, which is illegal.

I was lazy to figure out a better way, but setting the clock to `START_OF_TIME` temporarily seems to be more elegant solution.


<!-- Sent from Reviewable.io -->

2023-03-14 19:06 UTC, gbrodman approved these changes
> Reviewed 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/model/common/DnsRefreshRequest.java` line 59 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQdZ1j2t9PoV4WLNKD:-NQWVn9N9VXoq9Fwxlr2:b-idfm8j) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/main/java/google/registry/model/common/DnsRefreshRequest.java#L59)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

That's fine. I'll be out for the next two weeks and it's unlikely that the whole migration will be done before EOW anyway. The good thing is that this column is not used yet so there's need for a data migration.

Created #1962 to rename the column. Note that this PR currently contains changes in #1962, which would be diffbased away once #1962 is merged.
</blockquote></details>

thanks! 
___
*[`core/src/test/java/google/registry/dns/DnsUtilsTest.java` line 149 at r9](https://reviewable.io/reviews/google/nomulus/1941#-NQQbzr29Ms7QX2_tgX5:-NQWVXeHAdx_BIq3T7oe:bo55zaw) ([raw file](https://github.com/google/nomulus/blob/36134b7bd0d2f4e01c09fce4bf6212fa57432aaa/core/src/test/java/google/registry/dns/DnsUtilsTest.java#L149)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

You'd think so :P but no, `DatabaseMigrationStateSchedule` also checks that you only transition to the next state from your current state as of now, in the new schedule. Since the time is set to 2020, we cannot add the entire schedule at once because that would make us jump directly from the initial state (`DATASTORE_ONLY`) to the latest state in the new schedule, which is illegal.

I was lazy to figure out a better way, but setting the clock to `START_OF_TIME` temporarily seems to be more elegant solution.
</blockquote></details>

that works! yeah this is definitely better than setting it multiple times, even though it's slightly weird to manipulate time


<!-- Sent from Reviewable.io -->

2023-03-15 18:22 UTC, gbrodman approved these changes
> Reviewed 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-03-16 13:46 UTC, jianglai reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-03-16 17:02 UTC, merged