Separate DEFAULT_TOKEN type into CREATE and RENEW types
google/nomulus pull request #1952
Opened 2023-03-03 20:29 UTC by sarahcaseybot

This separates the DEFAULT_TOKEN type into DEFAULT_CREATE_TOKEN and DEFAULT_RENEW_TOKEN. This will allow us to store default tokens for both types of commands on the same field of the TLD but distinguish what specific command that token should be applied to. 

This marks the DEFAULT_TOKEN type as deprecated, however I do not believe there currently are any tokens in production or sandbox with that type, so it may be safe to remove it entirely.

2023-03-07 21:46 UTC, gbrodman requested changes
Thoughts on adding a check to make sure that no new instances of `DEFAULT_TOKEN` are created? That way, if there are none in prod / sandbox right now, we can guarantee that it's safe to remove it entirely. 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1952#-:-NPxktLmB7ChBlVdUeGz:bhkaxon)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[`core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java` line 379 at r1](https://reviewable.io/reviews/google/nomulus/1952#-NPy1VgF8LNRKqRCznIs:-NPy1VgGAN-1ohPdyiYG:b-q5hs1z) ([raw file](https://github.com/google/nomulus/blob/199a9e96f98b8c908bae2da93d96430e32be7ca5/core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java#L379)):*
> ```Java
>         .hasMessageThat()
>         .isEqualTo(
>             "Invalid value for -t parameter. Allowed values:[DEFAULT_CREATE_PROMO, DEFAULT_PROMO,"
> ```

we probably want to update this message too (don't want to allow DEFAULT_PROMO) 


<!-- Sent from Reviewable.io -->

2023-03-09 19:05 UTC, gbrodman requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1952)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tools/GenerateAllocationTokensCommand.java` line 283 at r2](https://reviewable.io/reviews/google/nomulus/1952#-NQ6kfqR02kHVnbHpqIi:-NQ6kfqR02kHVnbHpqIj:br7lk3t) ([raw file](https://github.com/google/nomulus/blob/03eab5bf05a48276389bdafd0cc82f6b92c160e4/core/src/main/java/google/registry/tools/GenerateAllocationTokensCommand.java#L283)):*
> ```Java
>     // Don't allow DEFAULT_TOKEN token type on new tokens so the deprecated type is safe to remove
>     // in the future
>     checkArgument(
> ```

Can we just put this in the AllocationToken.Builder class so that we can be 100% sure it's not created anywhere? 
___
*[`core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java` line 379 at r1](https://reviewable.io/reviews/google/nomulus/1952#-NPy1VgF8LNRKqRCznIs:-NQ6kkyy10GzKo80FIJH:bjo6cx4) ([raw file](https://github.com/google/nomulus/blob/199a9e96f98b8c908bae2da93d96430e32be7ca5/core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java#L379)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I'm not sure how to change this message since this is autogenerated based on the values in the enum
</blockquote></details>

oh dang 


<!-- Sent from Reviewable.io -->

2023-03-09 19:07 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1952)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 124 at r2](https://reviewable.io/reviews/google/nomulus/1952#-NQ6l4ES-QMVxW13dzo_:-NQ6l4ES-QMVxW13dzoa:b3xj911) ([raw file](https://github.com/google/nomulus/blob/03eab5bf05a48276389bdafd0cc82f6b92c160e4/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L124)):*
> ```Java
>      * Token saved on a TLD to use on a create request if no other token is passed from the client
>      */
>     DEFAULT_CREATE_PROMO,
> ```

Is this the right approach?  I believe our current planned promo will use all the exact same discounts on creates and renews, so won't this make more work for us?

I think adding a separate field that, if specified, lists just the allowable actions (which could be expanded to include TRANSFERS in the future as well) would make more sense, but I'm also not clear if we even need this quite yet.


<!-- Sent from Reviewable.io -->

2023-03-09 20:25 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1952)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 124 at r2](https://reviewable.io/reviews/google/nomulus/1952#-NQ6l4ES-QMVxW13dzo_:-NQ7285J2ovg6Rl7oeyi:b-4ru31m) ([raw file](https://github.com/google/nomulus/blob/03eab5bf05a48276389bdafd0cc82f6b92c160e4/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L124)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I did not know the plan was to use the same discounts for creates and renews, but I assumed if we did that we would create separate default tokens  for these actions in order to fine tune the promotions by action. However I suppose it could also be done by adding a separate field to the AllocationToken object. However, that will require a database change which the token type change does not require.
</blockquote></details>

It's worth talking to Bruno, but, it seems somewhat counter-intuitive to me that we'd have multiple tokens to manage for a single promotion.  That means that every time a partner is added (or drops out), we'd have to update multiple tokens.


<!-- Sent from Reviewable.io -->

2023-03-10 16:35 UTC, closed without merging

2023-03-11 18:36 UTC, CydeWeys commented
Yes, so after discussion with Bruno the final decision is to leave `DEFAULT` here alone and to add a new `Set<Enum>` field (or similar) that governs the list of allowable EPP actions for a given token, which would default to "all actions" if unspecified.

This seems to be the best way forward as it prevents combinatorial explosion, e.g. it seems plausible we could also need the ability to limit explicitly specified tokens to CREATES, RENEWS, TRANSFERS, etc., only (or any combination thereof), and in order to do so it wouldn't be desirable to need to keep splitting off the types like this.

2023-03-11 18:37 UTC, CydeWeys commented
Oh, and by abandoning the PR and starting anew, you're losing the history of discussion on this existing PR.  It would probably be better to continue using this PR, but to change the code in it to implement the new idea.