Check allowedEppActions when validating tokens
google/nomulus pull request #1972
Opened 2023-03-22 21:16 UTC by sarahcaseybot

2023-03-24 16:47 UTC, CydeWeys commented on core/src/test/resources/google/registry/flows/domain/domain_check_fee_multiple_commands_allocationtoken_response_v12.xml
> +            <fee:class>Token Not Supported</fee:class>
This is inconsistent with the existing fee:classes, which are all of the form lower-case-hyphenated.

2023-03-24 21:06 UTC, gbrodman requested changes
> Reviewed 12 of 17 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1972)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java` line 308 at r2](https://reviewable.io/reviews/google/nomulus/1972#-NRKPhkg4aoyqhCTFrYe:-NRKPhkg4aoyqhCTFrYf:bui1xyx) ([raw file](https://github.com/google/nomulus/blob/9b4c2e2ec489ba7b8395e20a70585517a5d93038/core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java#L308)):*
> ```Java
>               recurrences.getOrDefault(domainName, null));
>           responseItems.add(builder.setDomainNameIfSupported(domainName).build());
>         } catch (AssociationProhibitsOperationException | StatusProhibitsOperationException e) {
> ```

what's the type of issue that could cause this? We probably want to explain that in a comment at the start of the catch block so that it's clear how this might come about to any readers. 
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 306 at r2](https://reviewable.io/reviews/google/nomulus/1972#-NRKQWXBAe3w6FlO3RGD:-NRKQWXBAe3w6FlO3RGE:b-rl9lbt) ([raw file](https://github.com/google/nomulus/blob/9b4c2e2ec489ba7b8395e20a70585517a5d93038/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L306)):*
> ```Java
>       extends AssociationProhibitsOperationException {
>     AllocationTokenNotValidForCommandException() {
>       super("Allocation token not valid for the EPP command");
> ```

This can only happen on default tokens, right? Could it possibly be confusing to the user if they try to do something without specifying an allocation token and they get this message? 
___
*[`core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java` line 881 at r2](https://reviewable.io/reviews/google/nomulus/1972#-NRKR8VnEeLT2h19v1Ze:-NRKR8VnEeLT2h19v1Zf:b74m9f2) ([raw file](https://github.com/google/nomulus/blob/9b4c2e2ec489ba7b8395e20a70585517a5d93038/core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java#L881)):*
> ```Java
> 
>   @Test
>   void testFeeExtension_multipleCommands_tokenNotValidForAll_v06() throws Exception {
> ```

apologies for the nittiness, but can we use "some" instead of "all" in the test name? "all" can be a bit ambiguous (could mean either "some aren't valid" or "all aren't valid") 

same below


<!-- Sent from Reviewable.io -->

2023-03-31 19:13 UTC, gbrodman requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1972)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java` line 308 at r2](https://reviewable.io/reviews/google/nomulus/1972#-NRKPhkg4aoyqhCTFrYe:-NRt4MWf7w0i-KqVjBEG:budhfa8) ([raw file](https://github.com/google/nomulus/blob/9b4c2e2ec489ba7b8395e20a70585517a5d93038/core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java#L308)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In that case wouldn't it be the case that we only need to surround the call to AllocationTokenFlowUtils.validateToken with the try/catch block? 

Also, we'd want to catch the specific exceptions that we expect could be thrown, e.g. AllocationTokenNotValidForTldException 


<!-- Sent from Reviewable.io -->

2023-04-03 18:19 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1972)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java` line 308 at r2](https://reviewable.io/reviews/google/nomulus/1972#-NRKPhkg4aoyqhCTFrYe:-NS7IAtj0hMcEVB0OZf7:bdtdjdu) ([raw file](https://github.com/google/nomulus/blob/9b4c2e2ec489ba7b8395e20a70585517a5d93038/core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java#L308)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

No, I think we need to keep it this way because we do not want to call handleFeeRequest if the token is not valid. Instead, we just want to return a fee response item with the fee class of "token-not-supported" which is what's done in the catch block. 

AllocationTokenNotValidForTldException is not the only exception we want to catch. We want to catch all the AssociationProhibitsOperationExceptions and StatusProhibitsOperationExceptions since those would fail on actual EPP requests. This is actually an improvement from previous behavior. Before this change, you could pass in an invalid allocation token to the feeCheck command and it would still return a fee in the fee extension even though the actual create would fail. 
</blockquote></details>

1. i think it might be better to put a `continue` in the catch block, that way it's clear that `handleFeeRequest` isn't throwing the exception and it'll reduce indentation 
2. are those the actual exceptions that get thrown, or is a subclass of those like AllocationTokenNotValidForTldException? My point is that we should be as specific as possible 
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 306 at r2](https://reviewable.io/reviews/google/nomulus/1972#-NRKQWXBAe3w6FlO3RGD:-NS7KznZ6bkukaRl-4uN:b-kz85lq) ([raw file](https://github.com/google/nomulus/blob/9b4c2e2ec489ba7b8395e20a70585517a5d93038/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L306)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

No, this should not  happen with default tokens. This should happen if a token was created for only one (or some) command(s) and a user tries to use it for a different flow. Currently we only have tokens implemented for CREATE and RENEW, but could add more in the future. Perhaps if we want to temporarily discount RESTORE like we did during covid, we could create an allocation token making RESTORE free, but that token should not work on CREATE and RENEW.
</blockquote></details>

yeah right I think I misread this, my bad 


<!-- Sent from Reviewable.io -->

2023-04-04 17:59 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1972)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2023-04-04 18:29 UTC, merged