Add Java code for storing and using IDN tables per-TLD
google/nomulus pull request #1977
Opened 2023-03-30 19:05 UTC by gbrodman

This includes changes to make sure that we use the proper per-TLD IDN tables as well as setting/updating/removing them via the Create/Update TLD commands.

2023-04-05 18:47 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tldconfig/idn/IdnLabelValidator.java` line 31 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHgKef8xo3bIMoB7o1:-NSHjKrQ2OCqlLlbBnCO:b38zqc0) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/main/java/google/registry/tldconfig/idn/IdnLabelValidator.java#L31)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Should the default tables be in the configuration file?
</blockquote></details>

I think our goal is to get to the point where don't have the concept of default IDN tables at all -- they'll be explicitly set for every TLD.  Existing launched ones will be `[EXTENDED_LATIN, JAPANESE]`, and the 8 we're launching now plus additional ones down the road will simply be `UNCONFUSABLE_LATIN`.
___
*[`core/src/test/java/google/registry/tools/UpdateTldCommandTest.java` line 1060 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHj8-hCrIbyPfC9ceC:-NSHj8-iE3A8ih6ThNdf:b-6i1wf7) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/test/java/google/registry/tools/UpdateTldCommandTest.java#L1060)):*
> ```Java
>   void testSuccess_setsIdnTables() throws Exception {
>     assertThat(Registry.get("xn--q9jyb4c").getIdnTables()).isEmpty();
>     runCommandForced("--idn_tables=extended_latin,ja", "xn--q9jyb4c");
> ```

Note that I'm renaming `ja` to `japanese` in PR #1981, so you'll need to update these.


<!-- Sent from Reviewable.io -->

2023-04-05 18:51 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977)* status: all files reviewed, 4 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Registry.java` line 492 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHkT-i3KCHnPbkASqb:-NSHkT-i3KCHnPbkASqc:b-k3hek4) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/main/java/google/registry/model/tld/Registry.java#L492)):*
> ```Java
> 
>   /** A lis of allowed {@link IdnTableEnum}s for this TLD, or empty if we should use the default. */
>   List<IdnTableEnum> idnTables;
> ```

Why is this a list instead of a set?  It feels like it should be a set to me.  Ordering doesn't matter, does it?  Plus it needs to be unique.


<!-- Sent from Reviewable.io -->

2023-04-05 18:51 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 408 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHkalo2W-ZkfknKajP:-NSHkalo2W-ZkfknKajQ:bqtns7) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L408)):*
> ```Java
>       }
>       if (idnTables != null) {
>         if (idnTables.equals(ImmutableList.of(""))) {
> ```

Why would this ever happen?  `""` isn't a valid IDN table name.


<!-- Sent from Reviewable.io -->

2023-04-05 18:53 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 257 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHkkW76qO92Zs7NiJp:-NSHkkW76qO92Zs7NiJq:b-j4hwdx) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L257)):*
> ```Java
>           "A comma-separated list of the IDN tables to use for this TLD. Specify an empty list to"
>               + " remove any previously-set tables and to use the default.")
>   List<String> idnTables;
> ```

Instead of `String` here, this should be using `IdnTableEnum`.


<!-- Sent from Reviewable.io -->

2023-04-05 18:53 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 257 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHkkW76qO92Zs7NiJp:-NSHkzmZ816cXvQBFeMJ:b4j3sht) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L257)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Instead of `String` here, this should be using `IdnTableEnum`.
</blockquote></details>

Or does `EnumParameter` not support that.  If that's the case, the `description` should at least mention the constraint on what strings are passed in here.


<!-- Sent from Reviewable.io -->

2023-04-05 20:54 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Registry.java` line 492 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHkT-i3KCHnPbkASqb:-NSI6vJf2_D3HNVOWv1v:b-yxb5xz) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/main/java/google/registry/model/tld/Registry.java#L492)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why is this a list instead of a set?  It feels like it should be a set to me.  Ordering doesn't matter, does it?  Plus it needs to be unique.
</blockquote></details>

ehhhh yeah the command has to be a list but it is true that we can have this be a set (doesn't change sql representation) 
___
*[`core/src/main/java/google/registry/tldconfig/idn/IdnLabelValidator.java` line 31 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHgKef8xo3bIMoB7o1:-NSI7CB54lFp02dGvoKo:bglexdp) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/main/java/google/registry/tldconfig/idn/IdnLabelValidator.java#L31)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think our goal is to get to the point where don't have the concept of default IDN tables at all -- they'll be explicitly set for every TLD.  Existing launched ones will be `[EXTENDED_LATIN, JAPANESE]`, and the 8 we're launching now plus additional ones down the road will simply be `UNCONFUSABLE_LATIN`.
</blockquote></details>

yep yep 
___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 257 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHkkW76qO92Zs7NiJp:-NSIBFsD2Ptgg_GjULHe:bue4ksj) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L257)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Or does `EnumParameter` not support that.  If that's the case, the `description` should at least mention the constraint on what strings are passed in here.
</blockquote></details>

can't use a parameter here since that doesn't support the empty list (which is the equivalent of setting it to have the default value, removing the existing values) 
___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 408 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHkalo2W-ZkfknKajP:-NSI7FBcErpZYhmc5hYf:bbzmjps) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L408)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why would this ever happen?  `""` isn't a valid IDN table name.
</blockquote></details>

this is so you can remove the set to set it back to be the default value (this is definitely necessary) 
___
*[`core/src/test/java/google/registry/tools/UpdateTldCommandTest.java` line 1060 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHj8-hCrIbyPfC9ceC:-NSI7Jq784FmF8XSWL3v:b2nign3) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/test/java/google/registry/tools/UpdateTldCommandTest.java#L1060)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Note that I'm renaming `ja` to `japanese` in PR #1981, so you'll need to update these.
</blockquote></details>

yep


<!-- Sent from Reviewable.io -->

2023-04-05 21:18 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977)* status: 3 of 10 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/test/java/google/registry/tools/UpdateTldCommandTest.java` line 1060 at r1](https://reviewable.io/reviews/google/nomulus/1977#-NSHj8-hCrIbyPfC9ceC:-NSIH2mG4kGa_VGqsFD2:b-bqwit2) ([raw file](https://github.com/google/nomulus/blob/00628f4ba6d8b712fec4f099b79a16a7b17a69e5/core/src/test/java/google/registry/tools/UpdateTldCommandTest.java#L1060)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yep
</blockquote></details>

I had to back out this change.  I had forgotten that the IDN table used by a given domain name is already saved on domain names in the `Domain.idnTableName` field.  (Run e.g. `nomprod get_domain xn--p8j9a0d9c9a.xn--q9jyb4c`)  It's not worth doing a data migration just to rename this enum value.


<!-- Sent from Reviewable.io -->

2023-04-06 19:54 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tldconfig/idn/IdnLabelValidator.java` line 44 at r2](https://reviewable.io/reviews/google/nomulus/1977#-NSN7FI-DacUomORhknc:-NSN7FI-DacUomORhknd:b-m6k3ap) ([raw file](https://github.com/google/nomulus/blob/4dc01dc64fad7ab4f0e38848d7dfee58be9e19c3/core/src/main/java/google/registry/tldconfig/idn/IdnLabelValidator.java#L44)):*
> ```Java
>     ImmutableSet<IdnTableEnum> idnTablesForTld = tld.getIdnTables();
>     ImmutableSet<IdnTableEnum> idnTables =
>         isNullOrEmpty(idnTablesForTld) ? DEFAULT_IDN_TABLES : idnTablesForTld;
> ```

This shouldn't use `isNullOrEmpty()` as `getIdnTables()` is itself already using `nullToEmptyImmutableCopy()` to ensure that an empty set is returned, plus `getIdnTables()` is not annotated with `@Nullable` so it shouldn't be returning null anyway.
___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 417 at r2](https://reviewable.io/reviews/google/nomulus/1977#-NSN6yfeDjvfkKSnFPVE:-NSN6yfeDjvfkKSnFPVF:b34fwn2) ([raw file](https://github.com/google/nomulus/blob/4dc01dc64fad7ab4f0e38848d7dfee58be9e19c3/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L417)):*
> ```Java
>           checkArgument(
>               validIdnStringValues.containsAll(upperCaseIdnTables),
>               "IDN tables %s contained invalid value(s). Valid values: %s",
> ```

Shouldn't the error message say which values were invalid?  The valid ones aren't actionable, so no need to repeat them.


<!-- Sent from Reviewable.io -->

2023-04-06 20:03 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/tldconfig/idn/IdnLabelValidator.java` line 44 at r2](https://reviewable.io/reviews/google/nomulus/1977#-NSN7FI-DacUomORhknc:-NSN8x5A0C6QomRS61Vy:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4dc01dc64fad7ab4f0e38848d7dfee58be9e19c3/core/src/main/java/google/registry/tldconfig/idn/IdnLabelValidator.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This shouldn't use `isNullOrEmpty()` as `getIdnTables()` is itself already using `nullToEmptyImmutableCopy()` to ensure that an empty set is returned, plus `getIdnTables()` is not annotated with `@Nullable` so it shouldn't be returning null anyway.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 417 at r2](https://reviewable.io/reviews/google/nomulus/1977#-NSN6yfeDjvfkKSnFPVE:-NSN9ObY1MTMp_MHHL4t:b-2k2znm) ([raw file](https://github.com/google/nomulus/blob/4dc01dc64fad7ab4f0e38848d7dfee58be9e19c3/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L417)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Shouldn't the error message say which values were invalid?  The valid ones aren't actionable, so no need to repeat them.
</blockquote></details>

Changed the wording to "possible" since we're displaying what values the user **should** use instead of what they did. 


<!-- Sent from Reviewable.io -->

2023-04-06 20:12 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1977#-:-NSNBmxl2Qd597jCIO9R:bnfp4nl)* status: 7 of 10 files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2023-04-06 21:33 UTC, merged