Use a TLD's configured TTLs if they are present
google/nomulus pull request #1992
Opened 2023-04-13 20:23 UTC by sarahcaseybot

This was requested in b/253635762. If the TLD does not have configured TTLs, the defaults from the config file will still be used.

2023-04-13 20:29 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1992)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java` line 152 at r1](https://reviewable.io/reviews/google/nomulus/1992#-NSwI1j4-5HbCJQ91_mq:-NSwI1j55d5fnKi_TYs8:b-m83jqc) ([raw file](https://github.com/google/nomulus/blob/3993874772001ca53125f9103208151655cd1669/core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java#L152)):*
> ```Java
>                 .setTtl(
>                     (int)
>                         (tld.getDnsDsTtl() != null
> ```

A better pattern would be having these getters return Optionals, which are nicer to work with (especially for defaulting values) than nulls.


<!-- Sent from Reviewable.io -->

2023-04-14 21:29 UTC, gbrodman requested changes
> Reviewed 4 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1992)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java` line 182 at r2](https://reviewable.io/reviews/google/nomulus/1992#-NT0d1NG0QXM2jrCl0qN:-NT0d1NG0QXM2jrCl0qO:b-8a3uja) ([raw file](https://github.com/google/nomulus/blob/be4f8fea998b9996120dd3812db04f458dfdb845/core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java#L182)):*
> ```Java
>                     (int)
>                         (tld.getDnsNsTtl().isPresent()
>                             ? tld.getDnsNsTtl().get().getStandardSeconds()
> ```

unfortunate that the int cast is necessary here and that we cannot use the "new" (not actually that new) Optional::ifPresentOrElse 

either way, if you want you can collapse this somewhat into `(tld.getDsNsTtl().isPresent() ? tld.getDnsNsTtl() : defaultNsTtl).getStandardSeconds()  

(and this would be the same in every other place we have this pattern in this PR) 
___
*[`core/src/main/java/google/registry/dns/writer/dnsupdate/DnsUpdateWriter.java` line 278 at r2](https://reviewable.io/reviews/google/nomulus/1992#-NT0e8qfEngw2B6YBEzm:-NT0e8qg3q0YdcmQWvwh:bzgagia) ([raw file](https://github.com/google/nomulus/blob/be4f8fea998b9996120dd3812db04f458dfdb845/core/src/main/java/google/registry/dns/writer/dnsupdate/DnsUpdateWriter.java#L278)):*
> ```Java
>   }
> 
>   private Duration selectDnsAPlusAAAATtl(Host host) {
> ```

this is pretty much the same logic that's in CloudDnsWriter, what would it look like if we had one common function that took as input a default Duration and a Function<Tld, Duration>? 
___
*[`core/src/main/java/google/registry/model/tld/Registry.java` line 676 at r2](https://reviewable.io/reviews/google/nomulus/1992#-NT0cOVxCVeEjRH5W15b:-NT0cOVxCVeEjRH5W15c:bwcjl6f) ([raw file](https://github.com/google/nomulus/blob/be4f8fea998b9996120dd3812db04f458dfdb845/core/src/main/java/google/registry/model/tld/Registry.java#L676)):*
> ```Java
>   /** Returns the time to live for A and AAAA records. */
>   public Optional<Duration> getDnsAPlusAaaaTtl() {
>     if (dnsAPlusAaaaTtl == null) {
> ```

Optional.ofNullable (same below) 


<!-- Sent from Reviewable.io -->

2023-04-17 17:02 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1992)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java` line 152 at r1](https://reviewable.io/reviews/google/nomulus/1992#-NSwI1j4-5HbCJQ91_mq:-NTF8GnJ7JDmjvN3Xl3S:behn5lg) ([raw file](https://github.com/google/nomulus/blob/3993874772001ca53125f9103208151655cd1669/core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java#L152)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There's a much better way to do this without having to use ternaries that I'm sure you've seen in our codebase before.  Use `.orElse()`.  Without that, the `Optional` is not nicer than the previous nullable handling.
___
*[`core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java` line 182 at r2](https://reviewable.io/reviews/google/nomulus/1992#-NT0d1NG0QXM2jrCl0qN:-NTF8ZyCEiftv1Dwvr2L:b-da491n) ([raw file](https://github.com/google/nomulus/blob/be4f8fea998b9996120dd3812db04f458dfdb845/core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java#L182)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

unfortunate that the int cast is necessary here and that we cannot use the "new" (not actually that new) Optional::ifPresentOrElse 

either way, if you want you can collapse this somewhat into `(tld.getDsNsTtl().isPresent() ? tld.getDnsNsTtl() : defaultNsTtl).getStandardSeconds()  

(and this would be the same in every other place we have this pattern in this PR) 
</blockquote></details>

Again use `.orElse()` here.
___
*[`core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java` line 248 at r2](https://reviewable.io/reviews/google/nomulus/1992#-NTF91z7-nZzikxKg4X8:-NTF91z7-nZzikxKg4X9:buhrvre) ([raw file](https://github.com/google/nomulus/blob/be4f8fea998b9996120dd3812db04f458dfdb845/core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java#L248)):*
> ```Java
>   }
> 
>   private Duration selectDnsAPlusAAAATtl(String host) {
> ```

A better name for this method would be something like `getDnsTtlForHostsTld()`.  `select` doesn't mean much to me at first read.

Also, because of the way this is used everywhere, it might be better to have it return an `int`.
___
*[`core/src/main/java/google/registry/dns/writer/dnsupdate/DnsUpdateWriter.java` line 195 at r2](https://reviewable.io/reviews/google/nomulus/1992#-NTF9mi1BSEQWj7FRRMp:-NTF9mi1BSEQWj7FRRMq:btg553q) ([raw file](https://github.com/google/nomulus/blob/be4f8fea998b9996120dd3812db04f458dfdb845/core/src/main/java/google/registry/dns/writer/dnsupdate/DnsUpdateWriter.java#L195)):*
> ```Java
>               toAbsoluteName(domain.getDomainName()),
>               DClass.IN,
>               tld.getDnsDsTtl().isPresent()
> ```

More situations in this file where `orElse()` is the better choice.


<!-- Sent from Reviewable.io -->

2023-04-17 17:04 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1992)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java` line 152 at r1](https://reviewable.io/reviews/google/nomulus/1992#-NSwI1j4-5HbCJQ91_mq:-NTFA0BOEKKJr16B-29L:bl9obg7) ([raw file](https://github.com/google/nomulus/blob/3993874772001ca53125f9103208151655cd1669/core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java#L152)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There's a much better way to do this without having to use ternaries that I'm sure you've seen in our codebase before.  Use `.orElse()`.  Without that, the `Optional` is not nicer than the previous nullable handling.
</blockquote></details>

So to clarify, it would look something like `(int) tld.getDnsDsTtl().orElse(defaultDsTtl).getStandardSeconds()`


<!-- Sent from Reviewable.io -->

2023-04-18 15:40 UTC, gbrodman approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1992)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/dns/writer/dnsupdate/DnsUpdateWriter.java` line 278 at r2](https://reviewable.io/reviews/google/nomulus/1992#-NT0e8qfEngw2B6YBEzm:-NTK0AsT8ZDjnUTYgMp7:b5pf8yu) ([raw file](https://github.com/google/nomulus/blob/be4f8fea998b9996120dd3812db04f458dfdb845/core/src/main/java/google/registry/dns/writer/dnsupdate/DnsUpdateWriter.java#L278)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this is pretty much the same logic that's in CloudDnsWriter, what would it look like if we had one common function that took as input a default Duration and a Function<Tld, Duration>? 
</blockquote></details>

never mind, for some reason i thought that the method call on the TLD object was different when it's the same 


<!-- Sent from Reviewable.io -->

2023-04-21 17:47 UTC, merged