Don't allow a list of the empty string in TLD fields
google/nomulus pull request #2011
Opened 2023-04-26 15:32 UTC by gbrodman

If the user does, e.g. `--allowed_nameservers=` (or contact ids) that shouldn't mean a list consisting solely of the empty string.

2023-04-26 15:43 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2011)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 210 at r1](https://reviewable.io/reviews/google/nomulus/2011#-NTyDp8lBZ6r-5ku3TV2:-NTyDp8lBZ6r-5ku3TV3:bbdnzev) ([raw file](https://github.com/google/nomulus/blob/837ffa3cc973a00ef6163058abef99c98efa8ea5/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L210)):*
> ```Java
>   @Parameter(
>       names = "--allowed_nameservers",
>       description = "A comma-separated list of allowed nameservers for the TLD")
> ```

I think a better way to fix this would be to add a `validateWith` directive here, and create a new validator for a list of strings that disallows empty strings being in the list (is that ever a valid use case? it seems like it's always a bug, analogous to the default Java List implementation allowing null as a value).


<!-- Sent from Reviewable.io -->

2023-04-26 17:29 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2011)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 210 at r1](https://reviewable.io/reviews/google/nomulus/2011#-NTyDp8lBZ6r-5ku3TV2:-NTybAqLCsp9PkVlpJd_:b-65tzqi) ([raw file](https://github.com/google/nomulus/blob/837ffa3cc973a00ef6163058abef99c98efa8ea5/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L210)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think a better way to fix this would be to add a `validateWith` directive here, and create a new validator for a list of strings that disallows empty strings being in the list (is that ever a valid use case? it seems like it's always a bug, analogous to the default Java List implementation allowing null as a value).
</blockquote></details>

the proper use is the listConverter (not just "converter"), not validateWith (since we're converting, not validating). 

this ends up being a significantly larger PR but it's probably for the best 


<!-- Sent from Reviewable.io -->

2023-04-28 17:44 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2011)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/params/StringListParameter.java` line 23 at r3](https://reviewable.io/reviews/google/nomulus/2011#-NU7xXNX1tAbuX3cN8Je:-NU7xXNYD6JEoN0lv-1u:b-w7djpz) ([raw file](https://github.com/google/nomulus/blob/d4aee0a7b92adce855489a501057d0b2d37e0b24/core/src/main/java/google/registry/tools/params/StringListParameter.java#L23)):*
> ```Java
> 
> /**
>  * Converter for lists of String params that doesn't allow a list of the empty string.
> ```

This description isn't exactly correct.  It's not that it isn't allowed (which implies an error would be thrown), it's that it converts it.  A better description would be something about how all empty string elements are removed.


<!-- Sent from Reviewable.io -->

2023-04-28 17:44 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2011#-:-NU7xpAm6I4VY3XV2W36:bnfp4nl)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2023-04-28 18:23 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2011)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/tools/params/StringListParameter.java` line 23 at r3](https://reviewable.io/reviews/google/nomulus/2011#-NU7xXNX1tAbuX3cN8Je:-NU85gLz0FqyhxG4BHav:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d4aee0a7b92adce855489a501057d0b2d37e0b24/core/src/main/java/google/registry/tools/params/StringListParameter.java#L23)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This description isn't exactly correct.  It's not that it isn't allowed (which implies an error would be thrown), it's that it converts it.  A better description would be something about how all empty string elements are removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-28 21:59 UTC, merged