Console contacts API
google/nomulus pull request #2033
Opened 2023-05-11 17:08 UTC by ptkach

2023-05-16 20:21 UTC, gbrodman requested changes
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: 5 of 6 files reviewed, 11 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/model/registrar/RegistrarPoc.java` line 111 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVa98tkB5GIA3VJo7I5:-NVa98tkB5GIA3VJo7I6:b-qfceht) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/model/registrar/RegistrarPoc.java#L111)):*
> ```Java
> 
>   /** External email address of this contact used for registry lock confirmations. */
>   String registryLockEmailAddress;
> ```

I think we can actually expose this as well, looking at the previously-existing JSON map 

same with a few other fields that I think can be exposed (ones that are already exposed in the map). Unless there's some reason not to? 
___
*[`core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java` line 68 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVa9esOD52NsjaBHkFg:-NVa9esOD52NsjaBHkFh:bfvh1az) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java#L68)):*
> ```Java
> 
>   ConsoleDomainGetAction consoleDomainGetAction();
> ```

 :( sad that we have to have two separate actions 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 23 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaAUlt0QWLYrr_kbhP:-NVaAUlt0QWLYrr_kbhQ:b2wgiz9) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L23)):*
> ```Java
> public class ContactInfoAction {
> 
>   private static boolean isAuthorized(AuthResult authResult) {
> ```

technically this is `isAuthenticated`, not authorized 

also maybe we should have this in a common area since it seems like we'll use it a lot?
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 28 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaA6E36sKUEE5-DgI0:-NVa9qfFAsw3Z1psqqES:b-s98lcp) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L28)):*
> ```Java
>     }
>     UserAuthInfo authInfo = authResult.userAuthInfo().get();
>     if (!authInfo.consoleUser().isPresent()) {
> ```

just return this as the result 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 65 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBgAJ5JUQhLesfMLT:-NVaBgAJ5JUQhLesfMLU:b-w3l5ed) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L65)):*
> ```Java
>         return;
>       }
> ```

you note this in the description, but TODO: check authorization (that PR merged so if you rebase it should be fine) 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 66 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBEk12o7FM8K31Udi:-NVaBEk12o7FM8K31Udj:bk1fo4) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L66)):*
> ```Java
>       }
> 
>       Iterable<RegistrarPoc> am =
> ```

immutable list, not iterable
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBHbt7G2EE4wZ9Cc8:-NVaBHbt7G2EE4wZ9Cc9:buf11aq) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L70)):*
> ```Java
>                   () ->
>                       tm().query(
>                               "FROM RegistrarPoc WHERE registrarId = :registrarId",
> ```

better to use QueryComposer vs using raw strings when we're dealing with simple fields like this 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 88 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBqgA7MFljDI9-nH5:-NVaBqgA7MFljDI9-nH6:bu8dirn) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L88)):*
> ```Java
>       method = Action.Method.POST,
>       auth = Auth.AUTH_PUBLIC_LOGGED_IN)
>   public static class ContactInfoPostAction implements JsonGetAction {
> ```

eh probably better to have these in separate files, we don't want to have two separate big classes in one file 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBxKt3Hxo0H0zi5rb:-NVaBxKt3Hxo0H0zi5rc:b-cwablz) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L90)):*
> ```Java
>   public static class ContactInfoPostAction implements JsonGetAction {
> 
>     private static final String PATH = "/console-api/settings/contacts/upd";
> ```

ehhh probably "post" instead of an abbreviation in the URL? Just to be 100% clear (we're not going to run out of URL space or anything)
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 126 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaCiXi2nQ80DUCTT0-:-NVaCiXi2nQ80DUCTT00:bezo4az) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L126)):*
> ```Java
>                           String.format("Unknown registrar %s", registrarId)));
> 
>       RegistrarPoc.updateContacts(registrar, ImmutableSet.copyOf(registrarPocs));
> ```

I think we need this to be more clever / particular than this. Instead of a clean put/update, we likely want this to be a sort of a patch, because the object we pass back and forth from the front end does not include all fields of the object. I believe, for instance, that this would delete entirely the registry lock password + salt. 
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 168 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaCL4JCVfzfpQqFYwD:-NVaCL4JCVfzfpQqFYwE:b-ad2yan) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L168)):*
> ```Java
>   @Provides
>   @Parameter("contacts")
>   static String provideContacts(HttpServletRequest req) {
> ```

This shouldn't be a String if we can at all avoid it. We should be doing the conversion to a collection of RegistrarPoc objects as soon as possible
___
*[`core/src/test/resources/google/registry/module/frontend/frontend_routing.txt` line 4 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaDEA-7PzgBgdLNMvW:-NVaDEA-7PzgBgdLNMvX:b-g8eb84) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/test/resources/google/registry/module/frontend/frontend_routing.txt#L4)):*
> ```help
> /_dr/epp                          EppTlsAction                  POST     n  INTERNAL,API        APP  PUBLIC
> /console-api/domain               ConsoleDomainGetAction        GET      n  API,LEGACY          USER PUBLIC
> /console-api/settings/contacts    ContactInfoGetAction           [...]

2023-05-18 20:01 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: 1 of 11 files reviewed, 13 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/model/registrar/RegistrarPoc.java` line 111 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVa98tkB5GIA3VJo7I5:-NVdz0fd9Glnoehzd7wG:b-x6sa4m) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/model/registrar/RegistrarPoc.java#L111)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we can actually expose this as well, looking at the previously-existing JSON map 

same with a few other fields that I think can be exposed (ones that are already exposed in the map). Unless there's some reason not to? 
</blockquote></details>

I've exposed what seems to be used by front-end based on the mockups, as there's no reason to send data back and forth over the network connection unless it's not used. Have I missed the place where this field is used on UI?
___
*[`core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java` line 68 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVa9esOD52NsjaBHkFg:-NVdzUmbArFb8f5XKmgv:bhihqy5) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java#L68)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

 :( sad that we have to have two separate actions 
</blockquote></details>

Action represents a request handler, since we're trying to follow REST, we leverage different request methods, which require different request handlers. I don't see how it could've been limited to a single action (not to confuse with an endpoint (PATH)) given that. How did you imagine it?
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 168 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaCL4JCVfzfpQqFYwD:-NVf2Bej6Hrw_91nyAfL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L168)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This shouldn't be a String if we can at all avoid it. We should be doing the conversion to a collection of RegistrarPoc objects as soon as possible
</blockquote></details>

Done.
___
*[`core/src/test/resources/google/registry/module/frontend/frontend_routing.txt` line 4 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaDEA-7PzgBgdLNMvW:-NVf3avj2MwegeY0O7nk:bcct999) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/test/resources/google/registry/module/frontend/frontend_routing.txt#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i don't think these are the same paths from the Java classes?
</blockquote></details>

Good catch, forgot to update after renaming
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 23 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaAUlt0QWLYrr_kbhP:-NVe4BUz1BeQZD62q4r3:b-896fix) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L23)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

technically this is `isAuthenticated`, not authorized 

also maybe we should have this in a common area since it seems like we'll use it a lot?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 28 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaA6E36sKUEE5-DgI0:-NVe4AvR9JY2fswSI2n5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L28)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

just return this as the result 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 65 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBgAJ5JUQhLesfMLT:-NVefcTm3OKWNmSuanDS:bxai7q3) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L65)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

you note this in the description, but TODO: check authorization (that PR merged so if you rebase it should be fine) 
</blockquote></details>

Done. Adding tests
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 66 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBEk12o7FM8K31Udi:-NVefl2Y01f0Sdvcu_sc:b-896fix) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L66)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

immutable list, not iterable
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBHbt7G2EE4wZ9Cc8:-NVejcebA6zx-KR6Ozmj:b-g8bg2v) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L70)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

better to use QueryComposer vs using raw strings when we're dealing with simple fields like this 
</blockquote></details>

Great suggestion, thanks
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 88 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBqgA7MFljDI9-nH5:-NVf3k5i5isCf7719R2O:b-896fix) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L88)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

eh probably better to have these in separate files, we don't want to have two separate big classes in one file 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaBxKt3Hxo0H0zi5rb:-NVf4Mox1fp2fL3ZRcg7:b-y085tx) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L90)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ehhh probably "post" instead of an abbreviation in the URL? Just to be 100% clear (we're not going to run out of URL space or anything)
</blockquote></details>

I've specifically named it "upd" as "post" is after all an implementation detail, which I didn't want to spill onto url naming, but I've made an update. 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java` line 126 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVaCiXi2nQ80DUCTT0-:-NVkRk079HTQiF1PF6TD:bq2fbo1) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/ui/server/console/settings/ContactInfoAction.java#L126)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think  [...]

2023-05-18 20:02 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: 1 of 12 files reviewed, 13 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 50 at r2](https://reviewable.io/reviews/google/nomulus/2033#gh-1198205126:-NVkS3xPE2VuLvQNfXzj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/802732636996e6af829c64491bf7662b3768c68d/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L50)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Missing Override annotation

This method overrides [Runnable.run](1); it is advisable to add an Override annotation.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1141)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-19 22:21 UTC, gbrodman requested changes
> Reviewed 1 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: 2 of 12 files reviewed, 13 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/model/registrar/RegistrarPoc.java` line 111 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVa98tkB5GIA3VJo7I5:-NVoex2F2Z_N2CJ8Siyv:b-y5b3bc) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/model/registrar/RegistrarPoc.java#L111)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I've exposed what seems to be used by front-end based on the mockups, as there's no reason to send data back and forth over the network connection unless it's not used. Have I missed the place where this field is used on UI?
</blockquote></details>

Yeah I suppose we shouldn't expose things until / unless we need to. 

The reason potentially to expose the registry lock email address (because it can be different from the login email address) would be so that we can display it when saying "we are going to send a confirmation email to abc@registrar.com to verify the lock" -- if we don't display that, the user might get confused about what email address to check. 
___
*[`core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java` line 68 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVa9esOD52NsjaBHkFg:-NVofj0X3Z9l-CfNUlHh:byp7q61) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java#L68)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Action represents a request handler, since we're trying to follow REST, we leverage different request methods, which require different request handlers. I don't see how it could've been limited to a single action (not to confuse with an endpoint (PATH)) given that. How did you imagine it?
</blockquote></details>

er yeah, what I meant was that we have to have two separate paths and that makes me sad

question: I remember that we discussed that the reason for that is that the routes are stored as a map with string keys; is there any reason why that must be the case? I'm thinking of the possibility of changing `Router::route` to accept both a path and a method, which would allow us to have multiple methods at the same path. Have you tried this already? 


<!-- Sent from Reviewable.io -->

2023-05-22 16:15 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: 2 of 12 files reviewed, 13 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/model/registrar/RegistrarPoc.java` line 111 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVa98tkB5GIA3VJo7I5:-NW3CHWI5uBMJCn8AHgD:bshu62j) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/model/registrar/RegistrarPoc.java#L111)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah I suppose we shouldn't expose things until / unless we need to. 

The reason potentially to expose the registry lock email address (because it can be different from the login email address) would be so that we can display it when saying "we are going to send a confirmation email to abc@registrar.com to verify the lock" -- if we don't display that, the user might get confused about what email address to check. 
</blockquote></details>

I'm sure this and some other cases might gonna come up in the future, but I think it'd be better to deal with them when we get there.
___
*[`core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java` line 68 at r1](https://reviewable.io/reviews/google/nomulus/2033#-NVa9esOD52NsjaBHkFg:-NW3CVGL2uLX7PZIj8Eq:b-v62fn2) ([raw file](https://github.com/google/nomulus/blob/97c23e9ae13427aaf297d6670462f698530c61a6/core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java#L68)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

er yeah, what I meant was that we have to have two separate paths and that makes me sad

question: I remember that we discussed that the reason for that is that the routes are stored as a map with string keys; is there any reason why that must be the case? I'm thinking of the possibility of changing `Router::route` to accept both a path and a method, which would allow us to have multiple methods at the same path. Have you tried this already? 
</blockquote></details>

I've checked the possibility to use Path + Method as a route identifier, which is a quite intuitive solution to this kind of task. However, as I discovered and what I assume is the reason why it'd not been developed as such in the first place, we have `isPrefix` routes. `isPrefix` routes present a challenge to map path and the method to the route when path might be either strict equal or equal by prefix. This is the place I'm talking about - https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/Router.java;l=59 

As I thought about the solutions to that challenge and the risk of potential regression the change might cause I figured it's not necessary worth the benefit of having a single Path to multiple actions. 


<!-- Sent from Reviewable.io -->

2023-05-23 19:00 UTC, gbrodman requested changes
still need to change the title of the PR since that's what gets marked as the squash commit message

> Reviewed 4 of 10 files at r2, 2 of 4 files at r3, 3 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033#-:-NW8u8A43g6e0Ck6ajFM:ba0f1nh)* status: 9 of 13 files reviewed, 13 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 12 at r5](https://reviewable.io/reviews/google/nomulus/2033#-NW8tKPG4nqwe7zicp-m:-NW8tKPG4nqwe7zicp-n:b-rdmchs) ([raw file](https://github.com/google/nomulus/blob/12a6fe0622258b6240ae1c3b6a35ca73e2160350/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L12)):*
> ```Java
> 
>   private static boolean isAuthenticated(AuthResult authResult) {
>     if (!authResult.isAuthenticated()
> ```

this can be collapsed into one return statement
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 21 at r5](https://reviewable.io/reviews/google/nomulus/2033#-NW8tMcT7gfmyRt8Ao9a:-NW8tMcT7gfmyRt8Ao9b:b-obi6dx) ([raw file](https://github.com/google/nomulus/blob/12a6fe0622258b6240ae1c3b6a35ca73e2160350/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L21)):*
> ```Java
> 
>   private static boolean isAuthorizedRead(User user, String registrarId) {
>     return user.getUserRoles().hasGlobalPermission(ConsolePermission.VIEW_REGISTRAR_DETAILS)
> ```

don't need to check the global permission explicitly, `hasPermission` already does that  (same with the next method) 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 25 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8xi0wAP9rhuY-0Yll:-NW8xi0wAP9rhuY-0Ylm:b-4j2xw0) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L25)):*
> ```Java
>   }
> 
>   private static boolean isAuthorizedWrite(User user, String registrarId) {
> ```

given that we can reduce this down to one line, I think the method is probably unnecessary. More so because I think it's probably best to tie the exact permission (EDIT_REGISTRAR_DETAILS) to the place in which it's used (the POST section of the ConsoleAction). Does that make sense? 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 48 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8vViH8wMu-njsgGoi:-NW8vViH8wMu-njsgGoj:bur845b) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L48)):*
> ```Java
>     }
>     return true;
>   }
> ```

this can also be collapsed into one return statement



_Code quote:_
```Java
    boolean isAuthorized =
        isReadOperation
            ? isAuthorizedRead(user, registrarId)
            : isAuthorizedWrite(user, registrarId);

    if (!isAuthorized) {
      response.setStatus(HttpStatusCodes.STATUS_CODE_FORBIDDEN);
      return false;
    }
    return true;
  }
```
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 51 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8w8bLA3UkJBgFHhE9:-NW8w8bLA3UkJBgFHhEA:bdyfy4r) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L51)):*
> ```Java
> 
>   @Override
>   public abstract void run();
> ```

don't think we need to have this method 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 1 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8y8PjAweyFCExHbkf:-NW8y8PjAweyFCExHbkg:b-wqhi78) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L1)):*
> ```Java
> package google.registry.ui.server.console.settings;
> ```

license
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 61 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8yAN-26IltAEec8BZ:-NW8yAN-26IltAEec8B_:b-m4af7s) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L61)):*
> ```Java
>     boolean isGet = this.req.getMethod().equals(GET.toString());
> 
>     if (!verifyUserPermissions(isGet, registrarId, authResult, response)) {
> ```

better to check the particular permission (read, write) in the area where we're doing the thing (GET, POST sections) 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 86 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8yM6j9OeoTD4U6KB0:-NW8yM6j9OeoTD4U6KB1:b-4hj1vx) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L86)):*
> ```Java
>   private void postHandler() {
>     if (!contacts.isPresent()) {
>       response.setStatus(HttpStatusCodes.STATUS_CODE_SERVER_ERROR);
> ```

if the contacts aren't present, that seems more like a 400 
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 174 at r4](https://reviewable.io/reviews/google/nomulus/2033#-NW37m4C0R909jVCQ5Py:-NW37m4C0R909jVCQ5Pz:bhpecxr) ([raw file](https://github.com/google/nomulus/blob/325a25c7f77ff95bd91de7039710ff5c9ce8ca6c/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L174)):*
> ```Java
>   public static ImmutableSet<RegistrarPoc> provideContacts(HttpServletRequest req) {
>     GsonBuilder builder = new GsonBuilder();
>     Gson gson = builder.create();
> ```

we should inject the gson instead of creating it anew 
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java` line 280 at r4](https://reviewable.io/reviews/google/nomulus/2033#-NW39FFY6pVLGc2MVLKc:-NW39FFY6pVLGc2MVLKd:b47frh8) ([raw file](https://github.com/google/nomulus/blob/325a25c7f77ff95bd91de7039710ff5c9ce8ca6c/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L280)):*
> ```Java
>         throw new ForbiddenException("Only OWNERs can update the contacts");
>       }
>       RegistrarSettingsAction.checkContactRequirements(contacts, updatedContacts);
> ```

don't think the qualification should be necessary
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java` line 38 at r4](https://reviewable.io/reviews/google/nomulus/2033#-NW3A11YE9SEtysmn_Gs:-NW3A11YE9SEtysmn_Gt:bb7phvt) ([raw file](https://github.com/google/nomulus/blob/325a25c7f77ff95bd91de7039710ff5c9ce8ca6c/core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java#L38)):*
> ```Java
> import org.junit.jupiter.api.extension.RegisterExtension;
> 
> /** Tests for {@link google.registry.ui.server.console.settings.ContactGetAction}. */
> ```

typo
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactGetActionTest.java` line 29 at r2](https://reviewable.io/reviews/google/nomulus/2033#gh-1198205124:-NW8yzKz7F3hWci7dFtV:b8muzva) ([raw file](https://github.com/google/nomulus/blob/802732636996e6af829c64491bf7662b3768c68d/core/src/test/java/google/registry/ui/server/console/settings/ContactGetActionTest.java#L29)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: ContactGetActionTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1140)
</blockquote></details>

w [...]

2023-05-23 19:43 UTC, ptkach reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033#-:-NW95bOW8lObu7pdOb0u:bb6un1j)* status: 6 of 13 files reviewed, 13 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 12 at r5](https://reviewable.io/reviews/google/nomulus/2033#-NW8tKPG4nqwe7zicp-m:-NW95d2aBwpq7WvZ5I-r:b-896fix) ([raw file](https://github.com/google/nomulus/blob/12a6fe0622258b6240ae1c3b6a35ca73e2160350/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L12)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this can be collapsed into one return statement
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 21 at r5](https://reviewable.io/reviews/google/nomulus/2033#-NW8tMcT7gfmyRt8Ao9a:-NW95dz0BaOeSW-iPDYL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/12a6fe0622258b6240ae1c3b6a35ca73e2160350/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L21)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

don't need to check the global permission explicitly, `hasPermission` already does that  (same with the next method) 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 25 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8xi0wAP9rhuY-0Yll:-NW95f7nBY39IfXrtVy3:b4ipo7i) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L25)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

given that we can reduce this down to one line, I think the method is probably unnecessary. More so because I think it's probably best to tie the exact permission (EDIT_REGISTRAR_DETAILS) to the place in which it's used (the POST section of the ConsoleAction). Does that make sense? 
</blockquote></details>

I've removed the global permission check, however I don't think it's better to check in the place, at least not in the moment. I think what i have is quite clean with separation of concerns and entire auth + authz checks being handled by a single method - `verifyUserPermissions` 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 48 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8vViH8wMu-njsgGoi:-NW96JExA3oClfvoZwuJ:bbtbnpq) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L48)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this can also be collapsed into one return statement
</blockquote></details>

not sure how exactly, as there's a `setStatus` call there. 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 51 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8w8bLA3UkJBgFHhE9:-NW96cmGBnqQrHPLfTU3:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L51)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

don't think we need to have this method 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 1 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8y8PjAweyFCExHbkf:-NW96dVVEbY4WgdKgS6Z:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

license
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 61 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8yAN-26IltAEec8BZ:-NW96iMGCk5HALCX1aMu:bqua9iy) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L61)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

better to check the particular permission (read, write) in the area where we're doing the thing (GET, POST sections) 
</blockquote></details>

Based on the comments you seem to be looking at some weird outdated state with old and new functionality mixed in together. Anyhow - this is no longer present
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 86 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8yM6j9OeoTD4U6KB0:-NW96xO2CbIbNjxcfZLk:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L86)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

if the contacts aren't present, that seems more like a 400 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 174 at r4](https://reviewable.io/reviews/google/nomulus/2033#-NW37m4C0R909jVCQ5Py:-NW96xzsBTidQ2wlQWXH:b-896fix) ([raw file](https://github.com/google/nomulus/blob/325a25c7f77ff95bd91de7039710ff5c9ce8ca6c/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L174)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we should inject the gson instead of creating it anew 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java` line 280 at r4](https://reviewable.io/reviews/google/nomulus/2033#-NW39FFY6pVLGc2MVLKc:-NW97NwMCYLXVxGWQsin:b-896fix) ([raw file](https://github.com/google/nomulus/blob/325a25c7f77ff95bd91de7039710ff5c9ce8ca6c/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L280)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

don't think the qualification should be necessary
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java` line 38 at r4](https://reviewable.io/reviews/google/nomulus/2033#-NW3A11YE9SEtysmn_Gs:-NW97VGuDT3cBhRK6zzL:blxh6oy) ([raw file](https://github.com/google/nomulus/blob/325a25c7f77ff95bd91de7039710ff5c9ce8ca6c/core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java#L38)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

typo
</blockquote></details>

It appears that you've been looking at outdated version, this has been removed
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactGetActionTest.java` line 29 at r2](https://reviewable.io/reviews/google/nomulus/2033#gh-1198205124:-NW97clxCdhpORDQ23ys:b9d5ren) ([raw file](https://github.com/google/nomulus/blob/802732636996e6af829c64491bf7662b3768c68d/core/src/test/java/google/registry/ui/server/console/settings/ContactGetActionTest.java#L29)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

weird, I don't think I've seen this notification before? 
</blockquote></details>

Yeah, haven't seen one either. Anyways this file has been removed 


<!-- Sent from Reviewable.io -->

2023-05-23 20:03 UTC, gbrodman requested changes
> Reviewed 2 of 7 files at r5, 4 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: 12 of 13 files reviewed, 9 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 25 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8xi0wAP9rhuY-0Yll:-NW9885z4geEr5AHwFB6:bypx15m) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L25)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I've removed the global permission check, however I don't think it's better to check in the place, at least not in the moment. I think what i have is quite clean with separation of concerns and entire auth + authz checks being handled by a single method - `verifyUserPermissions` 
</blockquote></details>

the main point is that this only works for the very specific VIEW_REGISTRAR_DETAILS and EDIT_REGISTRAR_DETAILS permissions, and it's not immediately obvious when you're looking at the ContactAction which permission(s) are necessary. This base class is meant to handle all actions / possibilities so the caller should specify what permission(s) the caller needs. 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 48 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8vViH8wMu-njsgGoi:-NW98Cbf0-X1PI_jDcIE:b-nb96kx) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L48)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

not sure how exactly, as there's a `setStatus` call there. 
</blockquote></details>

ugh yeah my bad
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 61 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8yAN-26IltAEec8BZ:-NW98utlBQ54mtvAf00t:bz3damw) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L61)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Based on the comments you seem to be looking at some weird outdated state with old and new functionality mixed in together. Anyhow - this is no longer present
</blockquote></details>

nah I believe I'm looking at the most recent version, this is just tying in with my comment(s) on the ConsoleActionBase -- the `handleGet` method should call `verifyUserPermissions(registrarId, authResult, response, ConsolePermission.VIEW_REGISTRAR_DETAILS` so that we have "the contact GET action requires VIEW_REGISTRAR_DETAILS" right next to each other. 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 118 at r7](https://reviewable.io/reviews/google/nomulus/2033#-NW9AkOQ1G-IZ44ytlg4:-NW9AkOQ1G-IZ44ytlg5:b9jtbc9) ([raw file](https://github.com/google/nomulus/blob/83273b5fd894d6469a9b70522d9e300e5fedb4cb/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L118)):*
> ```Java
>             registrar,
>             oldContacts,
>             Collections.singletonMap(
> ```

ehhh probably want to use ImmutableMap.of() here 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 120 at r7](https://reviewable.io/reviews/google/nomulus/2033#-NW9AmHh4HaFXcIxjM4f:-NW9AmHh4HaFXcIxjM4g:b-9llhbe) ([raw file](https://github.com/google/nomulus/blob/83273b5fd894d6469a9b70522d9e300e5fedb4cb/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L120)):*
> ```Java
>             Collections.singletonMap(
>                 "contacts",
>                 contacts.get().stream().map(c -> c.toJsonMap()).collect(Collectors.toList())));
> ```

similarly, `toImmutableList` is better here
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 121 at r7](https://reviewable.io/reviews/google/nomulus/2033#-NW9B6Io8jYU7UkXMbOy:-NW9B6IpEsknMQ9V-Puj:b-h3l6kj) ([raw file](https://github.com/google/nomulus/blob/83273b5fd894d6469a9b70522d9e300e5fedb4cb/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L121)):*
> ```Java
>                 "contacts",
>                 contacts.get().stream().map(c -> c.toJsonMap()).collect(Collectors.toList())));
>     RegistrarSettingsAction.checkContactRequirements(oldContacts, updatedContacts);
> ```

this can throw the FormException / ContactRequirementException that are probably not well-handled by the default HTTP service handler. We probably want to have logic for what happens in those cases.  
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 175 at r7](https://reviewable.io/reviews/google/nomulus/2033#-NW9BheYDJC8lABms23_:-NW9BheYDJC8lABms23a:b-9brk0p) ([raw file](https://github.com/google/nomulus/blob/83273b5fd894d6469a9b70522d9e300e5fedb4cb/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L175)):*
> ```Java
>     Optional<String> maybeContactsJson = extractOptionalParameter(req, "contacts");
>     if (!maybeContactsJson.isPresent()) {
>       return Optional.ofNullable(null);
> ```

Use `extractOptionalParameter(...).map(.....)` to simplify this whole thing into a one-liner  
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java` line 38 at r4](https://reviewable.io/reviews/google/nomulus/2033#-NW3A11YE9SEtysmn_Gs:-NW9C5KmCuYjaIuPRUKP:bcmvhod) ([raw file](https://github.com/google/nomulus/blob/325a25c7f77ff95bd91de7039710ff5c9ce8ca6c/core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java#L38)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

It appears that you've been looking at outdated version, this has been removed
</blockquote></details>

I'm not, I'm referring to the fact that this class is ConsoleDomainGetAction but it's referencing `ContactGetAction` which no longer exists


<!-- Sent from Reviewable.io -->

2023-05-25 14:53 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: 7 of 13 files reviewed, 8 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java` line 25 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8xi0wAP9rhuY-0Yll:-NWIMwvC2F2a0jMxkETx:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/ConsoleActionBase.java#L25)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

the main point is that this only works for the very specific VIEW_REGISTRAR_DETAILS and EDIT_REGISTRAR_DETAILS permissions, and it's not immediately obvious when you're looking at the ContactAction which permission(s) are necessary. This base class is meant to handle all actions / possibilities so the caller should specify what permission(s) the caller needs. 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 61 at r6](https://reviewable.io/reviews/google/nomulus/2033#-NW8yAN-26IltAEec8BZ:-NWIMxbDE5Fv8G1nPVa-:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6fd53a9a25e8b45a68fb19c8aa9818fdd2a3f5f3/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L61)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nah I believe I'm looking at the most recent version, this is just tying in with my comment(s) on the ConsoleActionBase -- the `handleGet` method should call `verifyUserPermissions(registrarId, authResult, response, ConsolePermission.VIEW_REGISTRAR_DETAILS` so that we have "the contact GET action requires VIEW_REGISTRAR_DETAILS" right next to each other. 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 118 at r7](https://reviewable.io/reviews/google/nomulus/2033#-NW9AkOQ1G-IZ44ytlg4:-NWIMyPdAkfs0q17SfnT:b-n321ji) ([raw file](https://github.com/google/nomulus/blob/83273b5fd894d6469a9b70522d9e300e5fedb4cb/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L118)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ehhh probably want to use ImmutableMap.of() here 
</blockquote></details>

I don't agree, as ImmutableMap doesn't convey the right message, which in this case is -  we specifically use a **sole** key-value map, with the key "contacts" for a reason. 
`singletonMap` is immutable and limited to a single key-value pair, which is exactly what we need here.  
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 120 at r7](https://reviewable.io/reviews/google/nomulus/2033#-NW9AmHh4HaFXcIxjM4f:-NWIOLPg0jZSZzuUEAyP:b-896fix) ([raw file](https://github.com/google/nomulus/blob/83273b5fd894d6469a9b70522d9e300e5fedb4cb/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L120)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

similarly, `toImmutableList` is better here
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 121 at r7](https://reviewable.io/reviews/google/nomulus/2033#-NW9B6Io8jYU7UkXMbOy:-NWIOME95mCFULGXbWai:b-9r94yc) ([raw file](https://github.com/google/nomulus/blob/83273b5fd894d6469a9b70522d9e300e5fedb4cb/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L121)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this can throw the FormException / ContactRequirementException that are probably not well-handled by the default HTTP service handler. We probably want to have logic for what happens in those cases.  
</blockquote></details>

Handing added, `ContactRequirementException` extends from `FormException` 
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 175 at r7](https://reviewable.io/reviews/google/nomulus/2033#-NW9BheYDJC8lABms23_:-NWIOY0A8_phZe5qJO5x:b-896fix) ([raw file](https://github.com/google/nomulus/blob/83273b5fd894d6469a9b70522d9e300e5fedb4cb/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L175)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Use `extractOptionalParameter(...).map(.....)` to simplify this whole thing into a one-liner  
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-25 20:42 UTC, gbrodman requested changes
hopefully the test failures are easy enough to fix, I think they should be?

> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033#-:-NWJdO8sEqxZNIEMfsDY:bwsa8r5)* status: all files reviewed, 11 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 78 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJHvEq9z6rPlkbeTxO:-NWJHvEq9z6rPlkbeTxP:bdj4lqz) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L78)):*
> ```Java
>   @Override
>   public void run() {
>     boolean isGet = this.req.getMethod().equals(GET.toString());
> ```

this doesn't require a separate variable any more 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 80 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJH0_h9l4-Rm0f3OXY:-NWJH0_h9l4-Rm0f3OXZ:bvn237l) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L80)):*
> ```Java
>     boolean isGet = this.req.getMethod().equals(GET.toString());
> 
>     if (!isAuthenticated(authResult, response)) {
> ```

we don't have to do this here, but maybe at some point we move this call into ConsoleActionBase and then have a method in subclasses like this `protected void runWithUser(User user) {}`

maybe then we would even store the User as a protected instance variable so we don't need to pass it around

thoughts? 
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 173 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJIElUBdP0wXvjs76I:-NWJIElUBdP0wXvjs76J:b-6z82zi) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L173)):*
> ```Java
>   public static Optional<ImmutableSet<RegistrarPoc>> provideContacts(
>       HttpServletRequest req, Gson gson) {
>     return Optional.ofNullable(
> ```

can remove the `Optional.ofNullable` and the `orElse(null)` 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 124 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJXqNk120IzdaXQqcW:-NWJXqNk120IzdaXQqcX:b-mwgi7d) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L124)):*
> ```Java
>     action.run();
>     assertThat(RESPONSE.getStatus()).isEqualTo(HttpStatusCodes.STATUS_CODE_OK);
>     assertThat(
> ```

another option would be to loadAllOf(RegistrarPoc.class), filter to ones where the registrar ID matches, map to the names, then use the assertion `containsExactly` to verify that we got precisely the contacts we intend (no more, no less) 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 131 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJY4L51ltApfvtaRuM:-NWJY4L51ltApfvtaRuN:bx16ndq) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L131)):*
> ```Java
>             loadAllOf(RegistrarPoc.class).stream()
>                 .anyMatch(registrarPoc -> "Test Registrar 2".equals(registrarPoc.getName())))
>         .isEqualTo(true);
> ```

isTrue()
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 150 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJYN8Q2QZDDmceDQxO:-NWJYN8Q2QZDDmceDQxP:bjls1id) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L150)):*
> ```Java
>     assertThat(RESPONSE.getStatus()).isEqualTo(HttpStatusCodes.STATUS_CODE_OK);
>     assertThat(
>             loadAllOf(RegistrarPoc.class).stream()
> ```

probably cleaner to loadAllOf() then filter() to the name, then assert that the email address matches directly
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 178 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJYg1jEgxIAmDpPbUq:-NWJYg1jEgxIAmDpPbUr:bt0i0z9) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L178)):*
> ```Java
>             loadAllOf(RegistrarPoc.class).stream()
>                 .anyMatch(registrarPoc -> "Test Registrar 1".equals(registrarPoc.getName())))
>         .isEqualTo(false);
> ```

isFalse()
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 200 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJcrqt-GvKkEMrRS1W:-NWJcrqt-GvKkEMrRS1X:bmawzok) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L200)):*
> ```Java
>     assertThat(RESPONSE.getStatus()).isEqualTo(HttpStatusCodes.STATUS_CODE_FORBIDDEN);
>   }
> ```

We probably want a test for the situation where the user is entirely absent?
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 212 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJc_nw5cQCdKYKcj3J:-NWJc_nw5cQCdKYKcj3K:b-87qm49) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L212)):*
> ```Java
>       Action.Method method, AuthResult authResult, String registrarId, String contacts) {
>     if (method.equals(Action.Method.GET)) {
>       when(request.getMethod()).thenReturn(Action.Method.GET.toString());
> ```

this and the first line of the `else` block can be moved out of the block since they're both just using `method.toString()`
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 214 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJJGa8BgNMzLFBIPfd:-NWJJGa8BgNMzLFBIPfe:b-nizuqi) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L214)):*
> ```Java
>       when(request.getMethod()).thenReturn(Action.Method.GET.toString());
>       return new ContactAction(
>           request, authResult, RESPONSE, GSON, registrarId, Optional.ofNullable(null));
> ```

nit: Optional.empty() 


<!-- Sent from Reviewable.io -->

2023-05-26 16:24 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: all files reviewed, 11 unresolved discussions (waiting on @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 80 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJH0_h9l4-Rm0f3OXY:-NWNq6Ny3rBnsejeKGBS:bq06f23) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L80)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we don't have to do this here, but maybe at some point we move this call into ConsoleActionBase and then have a method in subclasses like this `protected void runWithUser(User user) {}`

maybe then we would even store the User as a protected instance variable so we don't need to pass it around

thoughts? 

</blockquote></details>

I wonder why do we need it at all? I've followed your implementation in `ConsoleDomainGetAction`, but after giving it more thoughts I'm not sure it's actually required. 
I think `@Action auth` takes care of verification that requested level of Auth is provided in the request, which in this case is `Auth.AUTH_PUBLIC_LOGGED_IN`. I've checked what is the response if this checked is commented/removed and as I suspected the response is - not authorized, in other words the request is bounced back without reaching the action. Please suggest what you think?


<!-- Sent from Reviewable.io -->

2023-05-26 16:38 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: all files reviewed, 11 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 80 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJH0_h9l4-Rm0f3OXY:-NWNuDLV4geDsAzsz89t:b5a7i2z) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L80)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I wonder why do we need it at all? I've followed your implementation in `ConsoleDomainGetAction`, but after giving it more thoughts I'm not sure it's actually required. 
I think `@Action auth` takes care of verification that requested level of Auth is provided in the request, which in this case is `Auth.AUTH_PUBLIC_LOGGED_IN`. I've checked what is the response if this checked is commented/removed and as I suspected the response is - not authorized, in other words the request is bounced back without reaching the action. Please suggest what you think?
</blockquote></details>

Yeah I think you're basically right, and that's a good point. 

My only note would be that AUTH_PUBLIC_LOGGED_IN currently would allow the legacy auth system which means that a call we make to `authResult.userAuthInfo().get().consoleUser()` would return in an empty optional. I don't think this would result in any actually-bad results, but we might get odd errors in our logs. This shouldn't happen though unless someone is doing serious shenanigans since it would require trying to hit the new console endpoints from the old console. 


<!-- Sent from Reviewable.io -->

2023-05-29 20:25 UTC, ptkach reviewed
It wasn't obvious what the problem was. Turns out it was spacing that's off. Fixed now.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033#-:-NWd9BXt3xjP8noGu5mM:b-ypx31d)* status: 8 of 14 files reviewed, 10 unresolved discussions (waiting on @action, @gbrodman, and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 78 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJHvEq9z6rPlkbeTxO:-NWd9KcX0qU5E6nEUNN9:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L78)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this doesn't require a separate variable any more 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 80 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJH0_h9l4-Rm0f3OXY:-NWd9L2C4AAWDcnw62b9:b-673wlb) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L80)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah I think you're basically right, and that's a good point. 

My only note would be that AUTH_PUBLIC_LOGGED_IN currently would allow the legacy auth system which means that a call we make to `authResult.userAuthInfo().get().consoleUser()` would return in an empty optional. I don't think this would result in any actually-bad results, but we might get odd errors in our logs. This shouldn't happen though unless someone is doing serious shenanigans since it would require trying to hit the new console endpoints from the old console. 
</blockquote></details>

Ok, I removed the check now, I don't think we need it. 
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 173 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJIElUBdP0wXvjs76I:-NWd9Zs-2uUMzp0ryixY:byt6tjn) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L173)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can remove the `Optional.ofNullable` and the `orElse(null)` 
</blockquote></details>

I've updated the code so this no longer in place
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 124 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJXqNk120IzdaXQqcW:-NWd9hPz214Gc2Xd4V8N:brnwo1r) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L124)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

another option would be to loadAllOf(RegistrarPoc.class), filter to ones where the registrar ID matches, map to the names, then use the assertion `containsExactly` to verify that we got precisely the contacts we intend (no more, no less) 
</blockquote></details>

Good suggestion, thanks
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 131 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJY4L51ltApfvtaRuM:-NWd9j5Z96GmwwTNT-ff:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L131)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

isTrue()
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 150 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJYN8Q2QZDDmceDQxO:-NWd9lNl77uXa7PjQVT7:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L150)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

probably cleaner to loadAllOf() then filter() to the name, then assert that the email address matches directly
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 178 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJYg1jEgxIAmDpPbUq:-NWd9mVUEg3-npiZ76oj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L178)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

isFalse()
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 200 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJcrqt-GvKkEMrRS1W:-NWd9nWb3LSvnxRbS0st:bzhg0k6) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L200)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We probably want a test for the situation where the user is entirely absent?
</blockquote></details>

I believe that'd be a test of our @Action functionality, instead of `ContactAction`, given that it's not part of the `ContactAction` responsibility any more, therefore I don't think it's needed here. 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 212 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJc_nw5cQCdKYKcj3J:-NWdB12g5uNwt-PLc9yk:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L212)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this and the first line of the `else` block can be moved out of the block since they're both just using `method.toString()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-30 17:37 UTC, gbrodman requested changes
> Reviewed 4 of 6 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: all files reviewed, 6 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/request/RequestModule.java` line 254 at r10](https://reviewable.io/reviews/google/nomulus/2033#-NWhiEZg8cqxZfFvH1Tn:-NWhiEZg8cqxZfFvH1To:burvemc) ([raw file](https://github.com/google/nomulus/blob/04e64a1b133b4e38354e58805a405900e96b4bf7/core/src/main/java/google/registry/request/RequestModule.java#L254)):*
> ```Java
> 
>   @Provides
>   @JsonPayload
> ```

i'm a bit confused by this part; don't we already have the @JsonPayload provided up above on line 196? 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 124 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJXqNk120IzdaXQqcW:-NWhgDrH0_kJc4NefzyI:bmwtevl) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L124)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Good suggestion, thanks
</blockquote></details>

`containsExactly` is even less wordy than `containsExactlyElementsIn`, doesn't require creation of a separate list (same below)
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 200 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJcrqt-GvKkEMrRS1W:-NWhhXGM2oihguzG1n-k:bsz9fdf) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L200)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I believe that'd be a test of our @Action functionality, instead of `ContactAction`, given that it's not part of the `ContactAction` responsibility any more, therefore I don't think it's needed here. 
</blockquote></details>

yep this is correct, we can assume that there is some type of user because of the PUBLIC_LOGGED_IN auth bit 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 160 at r10](https://reviewable.io/reviews/google/nomulus/2033#-NWhhHtzEPtQz-BHUTJw:-NWhhHtzEPtQz-BHUTJx:b-c7zi00) ([raw file](https://github.com/google/nomulus/blob/04e64a1b133b4e38354e58805a405900e96b4bf7/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L160)):*
> ```Java
>         .forEach(r -> testResult.put(r.getName(), r.getEmailAddress()));
>     assertThat(testResult)
>         .containsExactlyEntriesIn(
> ```

can also use containsExactly here 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 226 at r10](https://reviewable.io/reviews/google/nomulus/2033#-NWhhl7y5Rej3hD8X61m:-NWhhl7y5Rej3hD8X61n:b-j2n62q) ([raw file](https://github.com/google/nomulus/blob/04e64a1b133b4e38354e58805a405900e96b4bf7/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L226)):*
> ```Java
>           request, authResult, RESPONSE, GSON, registrarId, Optional.empty());
>     } else {
>       when(request.getReader())
> ```

Is this actually used now that we pass in `maybeContacts` as a constructor param to the action? 


<!-- Sent from Reviewable.io -->

2023-05-30 17:38 UTC, gbrodman reviewed
still failing formatting, might help to run `./gradlew javaIncrementalFormatApply` when pushing to avoid minor failures like that

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033#-:-NWhjD97Eol24Wq8qR3g:bbclsvk)* status: all files reviewed, 6 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)



<!-- Sent from Reviewable.io -->

2023-05-30 20:53 UTC, ptkach reviewed
Updated

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033#-:-NWiQMKyCDJyMEKnHwXE:b-bu91xm)* status: 11 of 14 files reviewed, 6 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], and @jsonpayload)

___
*[`core/src/main/java/google/registry/request/RequestModule.java` line 254 at r10](https://reviewable.io/reviews/google/nomulus/2033#-NWhiEZg8cqxZfFvH1Tn:-NWiQOAU7VHS_-5Na3h4:ba3dfob) ([raw file](https://github.com/google/nomulus/blob/04e64a1b133b4e38354e58805a405900e96b4bf7/core/src/main/java/google/registry/request/RequestModule.java#L254)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i'm a bit confused by this part; don't we already have the @JsonPayload provided up above on line 196? 
</blockquote></details>

Removed
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 124 at r8](https://reviewable.io/reviews/google/nomulus/2033#-NWJXqNk120IzdaXQqcW:-NWiQRCk6k1NMMmslcWA:bl6sruz) ([raw file](https://github.com/google/nomulus/blob/2d394c8f0e35d0f12b268f7f0d00c23922d44249/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L124)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

`containsExactly` is even less wordy than `containsExactlyElementsIn`, doesn't require creation of a separate list (same below)
</blockquote></details>

Updated, plenty of different options to choose from to do basically the same
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 160 at r10](https://reviewable.io/reviews/google/nomulus/2033#-NWhhHtzEPtQz-BHUTJw:-NWiQt2SCbkOtWZmwqjm:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/04e64a1b133b4e38354e58805a405900e96b4bf7/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L160)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can also use containsExactly here 
</blockquote></details>

Updated
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 226 at r10](https://reviewable.io/reviews/google/nomulus/2033#-NWhhl7y5Rej3hD8X61m:-NWiNvDmA0D3tO_Ib7bE:b-9sa4h8) ([raw file](https://github.com/google/nomulus/blob/04e64a1b133b4e38354e58805a405900e96b4bf7/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L226)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Is this actually used now that we pass in `maybeContacts` as a constructor param to the action? 
</blockquote></details>

`provideJsonBody` was using it under the hood. `maybeContacts` wasn't dealing with specifics, but just passing down the request instance, from which then the data was read. That's why the spy was used


<!-- Sent from Reviewable.io -->

2023-05-30 21:14 UTC, gbrodman requested changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: all files reviewed, 3 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 119 at r11](https://reviewable.io/reviews/google/nomulus/2033#-NWiTbpoDS401HMHMIGL:-NWiTbpoDS401HMHMIGM:b-9ptbxr) ([raw file](https://github.com/google/nomulus/blob/4bcfc70c2a6a3f53f086d051fb1180b2fafcff8c/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L119)):*
> ```Java
>             .orElseThrow(
>                 () ->
>                     new IllegalStateException(String.format("Unknown registrar %s", registrarId)));
> ```

sorry this should probably be IllegalArgumentException 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 226 at r10](https://reviewable.io/reviews/google/nomulus/2033#-NWhhl7y5Rej3hD8X61m:-NWiSeR5CQaK9taiPdB_:b-wz2z4a) ([raw file](https://github.com/google/nomulus/blob/04e64a1b133b4e38354e58805a405900e96b4bf7/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L226)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

`provideJsonBody` was using it under the hood. `maybeContacts` wasn't dealing with specifics, but just passing down the request instance, from which then the data was read. That's why the spy was used
</blockquote></details>

right I think I see what you mean, where you also want to test the injection 


<!-- Sent from Reviewable.io -->

2023-05-30 21:24 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot])



<!-- Sent from Reviewable.io -->

2023-05-31 19:06 UTC, ptkach reviewed
@gbrodman As discussed offline created a separate producer for the json body to provide Optional data. Updated the rest accordingly 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033#-:-NWnBy_wDpZx_4ARceWR:bd0ogi0)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])



<!-- Sent from Reviewable.io -->

2023-05-31 19:18 UTC, gbrodman requested changes
thx for doing that and testing it out 

> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033#-:-NWnEPIZA3whupP7cSQ8:b9gs01i)* status: all files reviewed, 3 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/request/OptionalJsonPayload.java` line 15 at r13](https://reviewable.io/reviews/google/nomulus/2033#-NWnEaL9CoivQc0LLR5g:-NWnEaL9CoivQc0LLR5h:bkgbe1t) ([raw file](https://github.com/google/nomulus/blob/7690e3a52d31372568dcd07fd0fba7f74e4e0def/core/src/main/java/google/registry/request/OptionalJsonPayload.java#L15)):*
> ```Java
> @Qualifier
> @Documented
> public @interface OptionalJsonPayload {}
> ```

you can just put this in RequestModule if you want; that's what we do in other places (this will fail tests since it doesn't have a license header) 


<!-- Sent from Reviewable.io -->

2023-05-31 19:35 UTC, ptkach reviewed
👍 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033#-:-NWnHgWb48tTwdIXDw6Z:b3k5lcb)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/request/OptionalJsonPayload.java` line 15 at r13](https://reviewable.io/reviews/google/nomulus/2033#-NWnEaL9CoivQc0LLR5g:-NWnHnbDCv1659mhooqD:bgitk4w) ([raw file](https://github.com/google/nomulus/blob/7690e3a52d31372568dcd07fd0fba7f74e4e0def/core/src/main/java/google/registry/request/OptionalJsonPayload.java#L15)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

you can just put this in RequestModule if you want; that's what we do in other places (this will fail tests since it doesn't have a license header) 
</blockquote></details>

That's fine, it's currently inline with the rest of qualifiers in requestmodule. Updated the license 


<!-- Sent from Reviewable.io -->

2023-05-31 19:36 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2033)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/request/OptionalJsonPayload.java` line 15 at r13](https://reviewable.io/reviews/google/nomulus/2033#-NWnEaL9CoivQc0LLR5g:-NWnIvCP-2IhYPM0DHXl:b2mf838) ([raw file](https://github.com/google/nomulus/blob/7690e3a52d31372568dcd07fd0fba7f74e4e0def/core/src/main/java/google/registry/request/OptionalJsonPayload.java#L15)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

That's fine, it's currently inline with the rest of qualifiers in requestmodule. Updated the license 
</blockquote></details>

gotcha! 


<!-- Sent from Reviewable.io -->

2023-05-31 20:34 UTC, merged