Refactor OIDC-based auth mechanism
google/nomulus pull request #2049
Opened 2023-06-07 13:45 UTC by jianglai

This PR changes the two flavors of OIDC authentication mechanisms to
verify the same audience. This allows the same token to pass both
mechanisms. Previously the regular OIDC flavor uses the project id as
its required audience, which does not work for local user credentials
(such as ones used by the nomulus tool), which requires a valid OAuth
client ID as audience when minting the token (project id is NOT a valid
OAuth client ID).

I considered allowing multiple audiences, but the result is not as clean
as just using the same everywhere, because the fall-through logic would
have generated a lot of noises for failed attempts.

This PR also changes the client side to solely use OIDC token whenever
possible, including the proxy, cloud scheduler and cloud tasks. The nomulus
tool still uses OAuth access token by default because it requires USER level
authentication, which in turn requires us to fill the User table with objects
corresponding to the email address of everyone needing access to the tool.

TESTED=verified each client is able to make authenticated calls on QA with or
without IAP.

2023-06-07 16:17 UTC, jianglai reviewed
> Reviewed 21 of 35 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 4 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
> Dismissed @github-code-scanning[bot] from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2049)* status: 33 of 36 files reviewed, 1 unresolved discussion (waiting on @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java` line 86 at r1](https://reviewable.io/reviews/google/nomulus/2049#gh-1221650325:-NXLPfAB1-sOwoO6Qk2h:bwxkk1v) ([raw file](https://github.com/google/nomulus/blob/578663a7405497b7bd0d01a2f7350602c30438cc/core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java#L86)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Insertion of sensitive information into log files

This [potentially sensitive information](1) is written to a log file.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1502)
</blockquote></details>

We need to see the token in case of authentication failure.
___
*[`core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java` line 86 at r4](https://reviewable.io/reviews/google/nomulus/2049#gh-1221799400:-NXLajj-BuwMCP4wJhcI:b-896fix) ([raw file](https://github.com/google/nomulus/blob/3f30d17c5541c45c53ebe0387d200917a43cccba/core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java#L86)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Insertion of sensitive information into log files

This [potentially sensitive information](1) is written to a log file.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1503)
</blockquote></details>

Done.
___
*[`util/src/main/java/google/registry/util/OidcTokenUtils.java` line 63 at r1](https://reviewable.io/reviews/google/nomulus/2049#gh-1221650299:-NXLdIUq3kF1Mk4vjTmS:b-848932) ([raw file](https://github.com/google/nomulus/blob/578663a7405497b7bd0d01a2f7350602c30438cc/util/src/main/java/google/registry/util/OidcTokenUtils.java#L63)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Dereferenced variable may be null

Variable [idToken](1) may be null at this access because of [this](2) assignment.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1494)
</blockquote></details>

Moot.


<!-- Sent from Reviewable.io -->

2023-06-07 16:17 UTC, jianglai reviewed
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2049)* status: 33 of 36 files reviewed, all discussions resolved (waiting on @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/tools/RequestFactoryModule.java` line 46 at r1](https://reviewable.io/reviews/google/nomulus/2049#gh-1221650305:-NXLdW_a24kOWbN_wpBq:b-896fix) ([raw file](https://github.com/google/nomulus/blob/578663a7405497b7bd0d01a2f7350602c30438cc/core/src/main/java/google/registry/tools/RequestFactoryModule.java#L46)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Useless parameter

The parameter 'projectId' is never used.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1501)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-07 18:51 UTC, jianglai reviewed
> Reviewed 2 of 35 files at r1, 1 of 1 files at r9, 21 of 21 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2049)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-06-08 12:33 UTC, jianglai reviewed
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2049)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-06-12 17:52 UTC, jianglai reviewed
> Reviewed 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2049)* status: all files reviewed, 12 unresolved discussions (waiting on @gbrodman and @ptkach)

___
*[`core/src/main/java/google/registry/batch/CloudTasksUtils.java` line 67 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRMNlv6vwRGfeG1loN:-NXkD7Ny7iA9bk747-aC:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/batch/CloudTasksUtils.java#L67)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can we just use the name `oauthClientId` everywhere so that it's clear what type of client ID it is and what it's used for? 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/batch/CloudTasksUtils.java` line 181 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRLwOv2K2Qlz32ctGy:-NXkDBLf8THXmW9A0LoQ:b-34lz9t) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/batch/CloudTasksUtils.java#L181)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this means that switching to GKE will require an actual code change (rather than just a config change) right? this is just the App Engine default service account
</blockquote></details>

Correct. On GKE we should be able to use `OidcTokenUtils` to get the OIDC token directly from the default credential, instead of having to rely on the `OidcToken.Builder` class which requires the service account explicitly. On GAE the ADC is an [`AppIdentityCredential`](https://github.com/googleapis/google-api-java-client/blob/main/google-api-client-appengine/src/main/java/com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredential.java) that does not implement `IdTokenProvider`.

I think after we get the token from `OidcTokenUtils`, we can use [`OidcToken.parseFrom`](https://cloud.google.com/java/docs/reference/google-cloud-tasks/2.13.0/com.google.cloud.tasks.v2.OidcToken#com_google_cloud_tasks_v2_OidcToken_parseFrom_byte___) to inject the token into the request. It will need to be tested. If it doesn't work, we can always explicitly provide the service account and still use `OidcToken.Builder`, though the former option is more desirable.
___
*[`core/src/main/java/google/registry/batch/CloudTasksUtils.java` line 183 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRMqjJD5GNIarsrXxK:-NXkG0y5DGfgfWowGS2L:badrdmb) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/batch/CloudTasksUtils.java#L183)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

the nittiest comment, but we can just include this line in the previous statement
</blockquote></details>

Done. Builder pattern FTW.
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 294 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRce7U3YZnY8zcv4nr:-NXkG6NkDq9EseebSTPZ:b-coqw4w) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/config/files/default-config.yaml#L294)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This is going to force changes in all of the config files right? 
</blockquote></details>

Right, I'll have a corresponding change to the internal config files that go with this PR.
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 295 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRNARf6Kn0Wx0QnM_X:-NXkITbqDC49L4FjxkR7:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/config/files/default-config.yaml#L295)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can we have a quick note explaining the replacement for the deprecated fields? 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 326 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRbFTe-flcHP3-3AJ_:-NXkIU7D9PALKoeqmUsy:b-1ythyy) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/config/files/default-config.yaml#L326)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what will be the ID in the case where we don't have IAP? Are you thinking that we just "create" it in every environment and use that client ID even when it's not enabled? 
</blockquote></details>

We just use the IAP client ID. IAP does not have to be enabled for the project. In principle we can use any client ID, but using the IAP client ID has the added benefit that there would be no change at the client side when we turn on/off IAP, the same token will be accepted with or without IAP.
___
*[`core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java` line 86 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRc84XBqnMnmry6HbE:-NXkIpXq9KOke3aVVGC0:b-5njwzn) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java#L86)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

hmmmm, is it sketchy to log the raw token itself? 
</blockquote></details>

I felt that if the token doesn't work, we might as well log it. Changed it to only log on non-production environment.
___
*[`core/src/main/java/google/registry/tools/RequestFactoryModule.java` line 45 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRcpYT9YQTTxcXgl11:-NXkJRwk7twO82Hj_Ri5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/tools/RequestFactoryModule.java#L45)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

similar to another comment can we still call it `oauthClientId` for clarity? 
</blockquote></details>

Done.
___
*[`proxy/src/main/java/google/registry/proxy/ProxyModule.java` line 263 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRg7-82PBisN6GqA5y:-NXkJ_xn9N8zi41mbBvA:b-rvpcgh) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/proxy/src/main/java/google/registry/proxy/ProxyModule.java#L263)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Does the ID token creation process refresh the credentials bundle automatically? 
</blockquote></details>

I believe refresh tokens and access tokens are only relevant for OAuth. With OIDC tokens they are always [fetched from the metadata server when requested](https://github.com/googleapis/google-auth-library-java/blob/5fa7039482298cc1c0ea09889db47081c83d990b/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L248).
___
*[`proxy/src/main/java/google/registry/proxy/config/default-config.yaml` line 11 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRgmYFE_1K6Vf5kVnn:-NXkK74Y94gAi147N8Om:b-77n76r) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/proxy/src/main/java/google/registry/proxy/config/default-config.yaml#L11)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This says "usually", is there any situation where it wouldn't be? 
</blockquote></details>

It needs to be the same as the value of `auth.oauthClientId` in the nomulus config file. Because that value should usually be the IAP client ID (unless we want to use different client IDs for IAP on/off). Updated the comment to make it clearer.
___
*[`util/src/main/java/google/registry/util/OidcTokenUtils.java` line 35 at r11](https:/ [...]

2023-06-12 20:20 UTC, gbrodman requested changes
> Reviewed 6 of 35 files at r1, 7 of 7 files at r12, all commit messages.
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2049)* status: all files reviewed, 3 unresolved discussions (waiting on @jianglai and @ptkach)

___
*[`core/src/main/java/google/registry/batch/CloudTasksUtils.java` line 181 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRLwOv2K2Qlz32ctGy:-NXks--1-hqamdJzN9vd:b6zmino) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/batch/CloudTasksUtils.java#L181)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Correct. On GKE we should be able to use `OidcTokenUtils` to get the OIDC token directly from the default credential, instead of having to rely on the `OidcToken.Builder` class which requires the service account explicitly. On GAE the ADC is an [`AppIdentityCredential`](https://github.com/googleapis/google-api-java-client/blob/main/google-api-client-appengine/src/main/java/com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredential.java) that does not implement `IdTokenProvider`.

I think after we get the token from `OidcTokenUtils`, we can use [`OidcToken.parseFrom`](https://cloud.google.com/java/docs/reference/google-cloud-tasks/2.13.0/com.google.cloud.tasks.v2.OidcToken#com_google_cloud_tasks_v2_OidcToken_parseFrom_byte___) to inject the token into the request. It will need to be tested. If it doesn't work, we can always explicitly provide the service account and still use `OidcToken.Builder`, though the former option is more desirable.
</blockquote></details>

Right yeah that makes sense. 

I suppose the route I was going down was "it seems a bit dangerous to require a code / behavioral change (as opposed to only a config change) at the same time that we switch to GKE". Am I missing something? 
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 294 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRce7U3YZnY8zcv4nr:-NXksgXpALoqU_Zb9e11:bo2mp2t) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/config/files/default-config.yaml#L294)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Right, I'll have a corresponding change to the internal config files that go with this PR.
</blockquote></details>

got it, i've seen it now 
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 304 at r12](https://reviewable.io/reviews/google/nomulus/2049#-NXkspZfCEHEoNo38z8x:-NXkspZfCEHEoNo38z8y:b-elm8p0) ([raw file](https://github.com/google/nomulus/blob/0436ecd6f6d1cad23a30529e6029fb977768dfd2/core/src/main/java/google/registry/config/files/default-config.yaml#L304)):*
> ```YAML
> 
>   # Deprecated: Use OIDC-based auth instead. This field is for OAuth-based auth
>   # that should only be used by the old registrar console.
> ```

I don't think these comments are correct, since OAuth was used primarily by the Nomulus tool and the proxy 

also this is a bit nitty but can we refer them specifically to the `oauthClientId` and `allowedServiceAccountEmails` fields in the comment? 
___
*[`core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java` line 90 at r12](https://reviewable.io/reviews/google/nomulus/2049#gh-1227057640:-NXktX864UCxkjhwDfld:bjeuwhg) ([raw file](https://github.com/google/nomulus/blob/0436ecd6f6d1cad23a30529e6029fb977768dfd2/core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java#L90)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Insertion of sensitive information into log files

This [potentially sensitive information](1) is written to a log file.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1509)
</blockquote></details>

sigh, i love that this was only flagged AFTER you removed the prod data 
___
*[`proxy/src/main/java/google/registry/proxy/config/default-config.yaml` line 15 at r12](https://reviewable.io/reviews/google/nomulus/2049#-NXlE-tj0dviYSCoShmw:-NXlE-tj0dviYSCoShmx:bvrtzsr) ([raw file](https://github.com/google/nomulus/blob/0436ecd6f6d1cad23a30529e6029fb977768dfd2/proxy/src/main/java/google/registry/proxy/config/default-config.yaml#L15)):*
> ```YAML
> # the IAP client ID, to allow the request to access IAP protected endpoints.
> # Regular OIDC authentication mechanism also checks for this audience.
> clientId: iap-client-id
> ```

just a thought looking at the other PR, thoughts on changing this to `oauthClientId` to match the variable names (since the values have to be the same)? 


<!-- Sent from Reviewable.io -->

2023-06-21 15:02 UTC, jianglai reviewed
> Reviewed 7 of 8 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2049)* status: 56 of 57 files reviewed, 3 unresolved discussions (waiting on @gbrodman and @ptkach)

___
*[`core/src/main/java/google/registry/batch/CloudTasksUtils.java` line 181 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRLwOv2K2Qlz32ctGy:-NYTKNshDVMIxq0mDG6C:b-mh8j5) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/batch/CloudTasksUtils.java#L181)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Right yeah that makes sense. 

I suppose the route I was going down was "it seems a bit dangerous to require a code / behavioral change (as opposed to only a config change) at the same time that we switch to GKE". Am I missing something? 
</blockquote></details>

We could add some logic to check which runtime we are in. But I think I have something better. Both `AppEngineCredentials` (not `AppIdentiyCredential`, which is a `GoogleCredential`, not `GoogleCredentials`...) and `ComputeEngineCrednetials` implement `ServiceAccountSigner`, which exposes the service account email address, so we can just grab that from the credential, instead having to construct our own. This should allow a seamlessly without code change.
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 304 at r12](https://reviewable.io/reviews/google/nomulus/2049#-NXkspZfCEHEoNo38z8x:-NYTKtQC4yofSsm0wExB:b-f0y2yx) ([raw file](https://github.com/google/nomulus/blob/6f6e7bea5162ad1093d636000fbb7782dda51b35/core/src/main/java/google/registry/config/files/default-config.yaml#L304)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think these comments are correct, since OAuth was used primarily by the Nomulus tool and the proxy 

also this is a bit nitty but can we refer them specifically to the `oauthClientId` and `allowedServiceAccountEmails` fields in the comment? 
</blockquote></details>

Right now OAuth is used by the tool and the proxy, but as of this PR the proxy would start using OIDC exclusively (after a deployment), and we should plan to add the user entities to allow the tool to use OIDC as well. Going forward, OAuth should only be used by the legacy console.

Can you clarify what is "them" in "refer them specifically to the `oauthClientId` and `allowedServiceAccountEmails` fields in the comment"?
___
*[`proxy/src/main/java/google/registry/proxy/config/default-config.yaml` line 15 at r12](https://reviewable.io/reviews/google/nomulus/2049#-NXlE-tj0dviYSCoShmw:-NYTRcBS-6Di2qUj2M5B:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6f6e7bea5162ad1093d636000fbb7782dda51b35/proxy/src/main/java/google/registry/proxy/config/default-config.yaml#L15)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

just a thought looking at the other PR, thoughts on changing this to `oauthClientId` to match the variable names (since the values have to be the same)? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-22 19:12 UTC, gbrodman requested changes
> Reviewed 8 of 8 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2049)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

___
*[`core/src/main/java/google/registry/batch/CloudTasksUtils.java` line 181 at r11](https://reviewable.io/reviews/google/nomulus/2049#-NXRLwOv2K2Qlz32ctGy:-NYZV7pHA_E6vxykMNW2:b-qn5lbb) ([raw file](https://github.com/google/nomulus/blob/4d9b8182b00c8fe54af4cf9eaa7d7e0b7a125118/core/src/main/java/google/registry/batch/CloudTasksUtils.java#L181)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

We could add some logic to check which runtime we are in. But I think I have something better. Both `AppEngineCredentials` (not `AppIdentiyCredential`, which is a `GoogleCredential`, not `GoogleCredentials`...) and `ComputeEngineCrednetials` implement `ServiceAccountSigner`, which exposes the service account email address, so we can just grab that from the credential, instead having to construct our own. This should allow a seamlessly without code change.
</blockquote></details>

Perfect!
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 304 at r12](https://reviewable.io/reviews/google/nomulus/2049#-NXkspZfCEHEoNo38z8x:-NYZVNKd2qXTkX57Huoa:blhj2gg) ([raw file](https://github.com/google/nomulus/blob/6f6e7bea5162ad1093d636000fbb7782dda51b35/core/src/main/java/google/registry/config/files/default-config.yaml#L304)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Right now OAuth is used by the tool and the proxy, but as of this PR the proxy would start using OIDC exclusively (after a deployment), and we should plan to add the user entities to allow the tool to use OIDC as well. Going forward, OAuth should only be used by the legacy console.

Can you clarify what is "them" in "refer them specifically to the `oauthClientId` and `allowedServiceAccountEmails` fields in the comment"?
</blockquote></details>

My point is that "should only be used by the old registrar console" is actually not true, since the old console uses the AppEngine built-in `LegacyAuthenticationMechanism`. 

```
The client_id value
  # used in registryTool.clientId field for associated tooling should be included
  # in this list.
```

this is a bit awkward and I'm not sure what it's trying to say, can we just say "the registryTool.clientId field should be included in this list"?

My second comment was related to directing the user to the `allowedServiceAccountEmails` and `oauthClientId` fields, since those are the replacement for the deprecated fields.


<!-- Sent from Reviewable.io -->

2023-06-26 14:54 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2049)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @ptkach)



<!-- Sent from Reviewable.io -->

2023-06-27 17:10 UTC, merged