Re-add 15% discount on sunrise domain creates
google/nomulus pull request #2056
Opened 2023-06-16 00:52 UTC by gbrodman

Note: previous behavior didn't care about standard vs premium pricing so we don't either

2023-06-22 15:54 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2056)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 267 at r1](https://reviewable.io/reviews/google/nomulus/2056#-NYYmmQm5uJ7LzcNdlOw:-NYYmmQnC2Z5IBlOeiW2:b-4wdfmz) ([raw file](https://github.com/google/nomulus/blob/e8120de5679a394f84c78d1e94bcfab62d6b620b/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L267)):*
> ```Java
>       validateLaunchCreateNotice(launchCreate.get().getNotice(), domainLabel, isSuperuser, now);
>     }
>     boolean isSunriseCreate = (isSuperuser || hasSignedMarks) && (tldState == START_DATE_SUNRISE);
> ```

This change seems very wrong to me from a business logic perspective?  A create without a signed mark on it cannot be a sunrise create, by definition.
___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 89 at r1](https://reviewable.io/reviews/google/nomulus/2056#-NYYo28D9R5__42O2pWg:-NYYo28D9R5__42O2pWh:b-ao2fze) ([raw file](https://github.com/google/nomulus/blob/e8120de5679a394f84c78d1e94bcfab62d6b620b/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L89)):*
> ```Java
>       Money domainCreateCost =
>           getDomainCreateCostWithDiscount(domainPrices, years, allocationToken);
>       // We might want to apply a discount to domains created during sunrise
> ```

I think this should be rewritten for clarity so it sounds less like a TODO.  Something like "Apply the sunrise discount if applicable and one is configured."
___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2056#-NYYn2X96pUU2TOCFS_j:-NYYn2X96pUU2TOCFS_k:bhrus9n) ([raw file](https://github.com/google/nomulus/blob/e8120de5679a394f84c78d1e94bcfab62d6b620b/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L90)):*
> ```Java
>           getDomainCreateCostWithDiscount(domainPrices, years, allocationToken);
>       // We might want to apply a discount to domains created during sunrise
>       if (tld.getTldState(dateTime).equals(TldState.START_DATE_SUNRISE)) {
> ```

This doesn't do the right thing.  It needs to check `isSunrise`, which is dependent on there being a signed mark.  You'll need to pass in more data to make it available here.

There are plenty of creates that occur during the sunrise phase but that aren't themselves sunrise creates (i.e. any kind of creation via an allocation token).  Those should't get this discount.
___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 93 at r1](https://reviewable.io/reviews/google/nomulus/2056#-NYYnGOPAQTZzvieaLPl:-NYYnGOPAQTZzvieaLPm:b8udmy7) ([raw file](https://github.com/google/nomulus/blob/e8120de5679a394f84c78d1e94bcfab62d6b620b/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L93)):*
> ```Java
>         domainCreateCost =
>             domainCreateCost.multipliedBy(
>                 1 - RegistryConfig.getSunriseDomainCreateDiscount(), RoundingMode.HALF_EVEN);
> ```

Maybe this should be `1.0d`?  Using an int here doesn't make it clear from reading it that it's actually doing the right thing.


<!-- Sent from Reviewable.io -->

2023-06-22 19:37 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2056)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 267 at r1](https://reviewable.io/reviews/google/nomulus/2056#-NYYmmQm5uJ7LzcNdlOw:-NYZYHKu72htd3rZiocK:b-1s1cvb) ([raw file](https://github.com/google/nomulus/blob/e8120de5679a394f84c78d1e94bcfab62d6b620b/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L267)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This change seems very wrong to me from a business logic perspective?  A create without a signed mark on it cannot be a sunrise create, by definition.
</blockquote></details>

yeah this was a miscommunication, now running with "anchor tenants and superuser creates are NOT sunrise creates" 
___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 89 at r1](https://reviewable.io/reviews/google/nomulus/2056#-NYYo28D9R5__42O2pWg:-NYZY9E0ENAXSbfszD5K:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e8120de5679a394f84c78d1e94bcfab62d6b620b/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L89)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think this should be rewritten for clarity so it sounds less like a TODO.  Something like "Apply the sunrise discount if applicable and one is configured."
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2056#-NYYn2X96pUU2TOCFS_j:-NYZYA8lEBCv6JTJcoOX:byw8zgb) ([raw file](https://github.com/google/nomulus/blob/e8120de5679a394f84c78d1e94bcfab62d6b620b/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L90)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This doesn't do the right thing.  It needs to check `isSunrise`, which is dependent on there being a signed mark.  You'll need to pass in more data to make it available here.

There are plenty of creates that occur during the sunrise phase but that aren't themselves sunrise creates (i.e. any kind of creation via an allocation token).  Those should't get this discount.
</blockquote></details>

Done.

yeah this was a miscommunication, now running with "anchor tenants and superuser creates are NOT sunrise creates" 
___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 93 at r1](https://reviewable.io/reviews/google/nomulus/2056#-NYYnGOPAQTZzvieaLPl:-NYZYAnS4hXj5_rQIbSa:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e8120de5679a394f84c78d1e94bcfab62d6b620b/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L93)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Maybe this should be `1.0d`?  Using an int here doesn't make it clear from reading it that it's actually doing the right thing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-26 18:19 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2056)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 1571 at r2](https://reviewable.io/reviews/google/nomulus/2056#-NYsuz86Cl9Dt4Ou4kHV:-NYsuz87AamPeowa3THo:b-u6d0aw) ([raw file](https://github.com/google/nomulus/blob/93c7a83a5d9074d961355015acd7debbe9d32e22/core/src/main/java/google/registry/config/RegistryConfig.java#L1571)):*
> ```Java
>   }
> 
>   /** Returns the discount, if any, that should be provided on sunrise domain creates. */
> ```

Clarify what exactly the number is.  Say it's a fractional discount between 0 and 1 inclusive.
___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 192 at r2](https://reviewable.io/reviews/google/nomulus/2056#-NYsv66z0Anw5_HPW0Pb:-NYsv67-0PGMyeDxY2mq:bncd5t) ([raw file](https://github.com/google/nomulus/blob/93c7a83a5d9074d961355015acd7debbe9d32e22/core/src/main/java/google/registry/config/files/default-config.yaml#L192)):*
> ```YAML
> 
>   # A discount, if any, to be provided to all domain creates that occur during
>   # the sunrise period. If this is 0, there will be no discount applied.
> ```

Also clarify that 1.0 means a full discount.


<!-- Sent from Reviewable.io -->

2023-06-26 20:11 UTC, CydeWeys reviewed
(And regardless of which way we hear back from Bruno on this, there should be a test of a multi-year registration.)

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2056#-:-NYtKFqTBZOHEgvrsho9:bw3kk4j)* status: 0 of 12 files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2023-06-27 19:31 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2056#-:-NYyKnai23vR1Ie1jrzF:bnfp4nl)* status: 0 of 12 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-27 22:58 UTC, gbrodman reviewed
oh actually we do test this in DomainCreateFlowTest tests -- https://github.com/google/nomulus/pull/2056/files#diff-8494ff380abdff58b3386156b91e629387041fd35493977cd0b79742f694ee57L278 changes the expected cost if we're in sunrise 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2056#-:-NYy9i-KCHy6A62a8ypV:b2qlxe4)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2023-06-27 22:58 UTC, merged