Add console-api/settings/security endpoint
google/nomulus pull request #2057
Opened 2023-06-17 15:18 UTC by ptkach

2023-07-05 16:28 UTC, ptkach commented
@gbrodman Kind reminder to review this PR. Thanks!

2023-07-05 22:23 UTC, gbrodman requested changes
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2057)* status: all files reviewed, 14 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 87 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbwCwm-gsAual-bl6E:-NZbwCwm-gsAual-bl6F:bblme79) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L87)):*
> ```Java
>   private void getHandler() {
>     try {
>       Registrar r = registrarAccessor.getRegistrar(registrarId);
> ```

probably should use a longer variable name go/java-practices/naming#single-letter-vars just in case (or just inline it, with no variable)
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 113 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbxAzl9M2YnQ9fWONp:-NZbxAzl9M2YnQ9fWONq:b5ka6ua) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L113)):*
> ```Java
>       tm().transact(
>               () -> {
>                 tm().getEntityManager().detach(savedRegistrar);
> ```

What's the purpose of detaching it here? I'm sure there is one, I just want to know the details 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 119 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbxlbK7Tc3dmpVib8Y:-NZbxlbK7Tc3dmpVib8Z:b-puwtld) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L119)):*
> ```Java
>                         .asBuilder()
>                         .setIpAddressAllowList(registrar.get().getIpAddressAllowList());
>                 if (registrar.get().getClientCertificate().isPresent()
> ```

there's a few duplicated calls to `Optional::get` at various points in this method (e.g. the registrar) and we could probably reduce complexity of some individual lines if we separate those into separate variables? 

tbh this might only apply to the registrar and transaction time 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbySzbEeXamL9UMrYZ:-NZbySzbEeXamL9UMrY_:bu3bqc5) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L139)):*
> ```Java
> 
>       response.setStatus(HttpStatusCodes.STATUS_CODE_OK);
>     } catch (RegistrarAccessDeniedException e) {
> ```

I think we can probably move this out so that only the `registrarAccessor` method is covered, right? AFAIK this should never happen because we've checked the permission for EDIT_REGISTRAR_DETAILS above 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 147 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbzmUN8SbvybaEBHHo:-NZbzmUN8SbvybaEBHHp:baf2iiz) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L147)):*
> ```Java
>   private boolean validateCertificate(
>       Optional<String> existingCertificate, String certificateString) {
>     if (!existingCertificate.isPresent() || !existingCertificate.get().equals(certificateString)) {
> ```

i know this is just copied from RegistrarSettingsAction but i think we'd probably just be better served by always calling `validateCertificate` if the "new" registrar has that particular cert present, then setting it (handling any InsecureCertificateExceptions) 

maybe like 

```
newRegistrar.getClientCertificate().ifPresent(newClientCert -> {
  try {
    certificateChecker.validateCertificate(newClientCert);
    updatedRegistrar.setClientCertificate(newClientCert, transactionTime);
  catch (ICE e) {
    // handling
  }
}
```

maybe having both calls inside a single try block (instead of having two try blocks inside the `ifPresent` calls?

seems like that might end up being more concise / clear at the cost of only a bit of extra validation 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 151 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbyw-D0Z-Q_Qsp5tDL:-NZbyw-D0Z-Q_Qsp5tDM:b-r8wctp) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L151)):*
> ```Java
>         certificateChecker.validateCertificate(certificateString);
>       } catch (InsecureCertificateException e) {
>         throw new IllegalArgumentException(e.getMessage());
> ```

we'll want exception handling here right? 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 91 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc4cxQ9y9uUoBMnRUd:-NZc4cxQ9y9uUoBMnRUe:b5tj7jz) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L91)):*
> ```Java
>   @RegisterExtension
>   final JpaTestExtensions.JpaIntegrationTestExtension jpa =
>       new JpaTestExtensions.Builder().buildIntegrationTestExtension();
> ```

if we're creating / using a clock we should have it be the JPA / SQL clock as well 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 95 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5FIe7eZFtx0s5lm1:-NZc5FIe7eZFtx0s5lm2:bymfs5i) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L95)):*
> ```Java
>   @BeforeEach
>   void beforeEach() {
>     response = new FakeResponse();
> ```

just create this inline
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 96 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5Srn8bFXlMsZ_3Q3:-NZc5Srn8bFXlMsZ_3Q4:b-1j42gm) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L96)):*
> ```Java
>   void beforeEach() {
>     response = new FakeResponse();
>     testRegistrar = saveRegistrar("registrarId");
> ```

Is there a reason to use this instead of using the built-in JpaIntegrationExtension canned data? 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 120 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5i5t0gt4chNHr9Xv:-NZc5i5t0gt4chNHr9Xw:bwt1ro7) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L120)):*
> ```Java
>     action.run();
>     assertThat(response.getStatus()).isEqualTo(HttpStatusCodes.STATUS_CODE_OK);
>     String payload = response.getPayload().replace("\\n", "").replace("\\u003d", "=");
> ```

what's up with these, out of curiosity? 

I assume it's necessary, especially since in an ideal world we wouldn't have to replace the newlines in SAMPLE_CERT in the next line 
___
*[`util/src/main/java/google/registry/util/CidrAddressBlock.java` line 489 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc8esD-L2llJWOu2UD:-NZc8esD-L2llJWOu2UE:becdqoi) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/util/src/main/java/google/registr [...]

2023-07-06 21:20 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2057)* status: 5 of 8 files reviewed, 14 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 87 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbwCwm-gsAual-bl6E:-NZgOWiJD0BROYA5fPbz:bczwrjp) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L87)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

probably should use a longer variable name go/java-practices/naming#single-letter-vars just in case (or just inline it, with no variable)
</blockquote></details>

Updated, although I think single letter variable considered to be ok when it's short-lived, like in this case - 2 lines only
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 113 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbxAzl9M2YnQ9fWONp:-NZgPADPC6fvYs2U57rx:brp3snv) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L113)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What's the purpose of detaching it here? I'm sure there is one, I just want to know the details 
</blockquote></details>

I believe it's to avoid update collisions. I've followed an existing approach - https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java;l=245 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 119 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbxlbK7Tc3dmpVib8Y:-NZgQYWM6qE3I3lxC5Sj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L119)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

there's a few duplicated calls to `Optional::get` at various points in this method (e.g. the registrar) and we could probably reduce complexity of some individual lines if we separate those into separate variables? 

tbh this might only apply to the registrar and transaction time 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbySzbEeXamL9UMrYZ:-NZgRC51-Ue2KUSnMp8r:b-762jw9) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L139)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we can probably move this out so that only the `registrarAccessor` method is covered, right? AFAIK this should never happen because we've checked the permission for EDIT_REGISTRAR_DETAILS above 
</blockquote></details>

I'm not sure removing the catch would be correct. There's multiple checks which throw in https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/auth/AuthenticatedRegistrarAccessor.java;l=222 and permission (which we cover above) is just one of them 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 147 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbzmUN8SbvybaEBHHo:-NZgvXno2d3ACVo3ZqVu:bnpykjp) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L147)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i know this is just copied from RegistrarSettingsAction but i think we'd probably just be better served by always calling `validateCertificate` if the "new" registrar has that particular cert present, then setting it (handling any InsecureCertificateExceptions) 

maybe like 

```
newRegistrar.getClientCertificate().ifPresent(newClientCert -> {
  try {
    certificateChecker.validateCertificate(newClientCert);
    updatedRegistrar.setClientCertificate(newClientCert, transactionTime);
  catch (ICE e) {
    // handling
  }
}
```

maybe having both calls inside a single try block (instead of having two try blocks inside the `ifPresent` calls?

seems like that might end up being more concise / clear at the cost of only a bit of extra validation 
</blockquote></details>

Good suggestion, updated
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 151 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbyw-D0Z-Q_Qsp5tDL:-NZgvgHnBmYDnEL8j4Pp:b1kwlvm) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L151)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we'll want exception handling here right? 
</blockquote></details>

Correct, updated
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 63 at r1](https://reviewable.io/reviews/google/nomulus/2057#gh-1233080968:-NZh3sBY3pmwqSjJydab:b-896fix) ([raw file](https://github.com/google/nomulus/blob/30adc6ddc9a19fd5812ada09722cb3406b370a0b/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L63)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: SecurityActionTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1517)
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 91 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc4cxQ9y9uUoBMnRUd:-NZgw2zB1JKyap5s1phq:b-896fix) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L91)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

if we're creating / using a clock we should have it be the JPA / SQL clock as well 
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 95 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5FIe7eZFtx0s5lm1:-NZgwGVLEBXnNEcxcrDA:blya761) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L95)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

just create this inline
</blockquote></details>

Why? it's common to all suits and it seems easier this way
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 96 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5Srn8bFXlMsZ_3Q3:-NZgwpDt6T0nefrcUJwT:bnwgplu) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L96)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Is there a reason to use this instead of using the built-in JpaIntegrationExtension canned data? 
</blockquote></details>

I prefer to rely on data scoped in the test, I believe this makes it easier to follow what's going on and more importantly makes less prone to be bro [...]

2023-07-06 22:26 UTC, gbrodman requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2057)* status: all files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 113 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbxAzl9M2YnQ9fWONp:-NZhAlDs3A3bX_tm7G8y:b-9rw7vw) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L113)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I believe it's to avoid update collisions. I've followed an existing approach - https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java;l=245 
</blockquote></details>

ah ok, I think we might not need that because we create a new object here. Have you tried not detaching it here? I think in RegistrarSettingsAction we have to do that because when we update linked objects (e.g. contacts) the original registrar object updates, even if we use `asBuilder` 

Basically, there we only did it because we needed to make 100% sure that we had a reference to the old object (which shouldn't be necessary here) 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbySzbEeXamL9UMrYZ:-NZhCMbK2TdsgHStBRi_:bl96cy7) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L139)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I'm not sure removing the catch would be correct. There's multiple checks which throw in https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/auth/AuthenticatedRegistrarAccessor.java;l=222 and permission (which we cover above) is just one of them 
</blockquote></details>

It looks like all those checks are already covered by the permission check we do above though (which makes sense, since if you have EDIT_ on a registrar, you have access to that registrar) 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 95 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5FIe7eZFtx0s5lm1:-NZhCriO5_egBqhcr1eB:bkd11ps) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L95)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Why? it's common to all suits and it seems easier this way
</blockquote></details>

it's the same amount of work (it's created once per test), it's a line of code removed, and it means that we create + declare at the same time which is good
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 96 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5Srn8bFXlMsZ_3Q3:-NZhIPiNC6xUc-X-u9Y2:bb7g23t) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L96)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I prefer to rely on data scoped in the test, I believe this makes it easier to follow what's going on and more importantly makes less prone to be broken by changes outside of the test. 
</blockquote></details>

fair
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 120 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5i5t0gt4chNHr9Xv:-NZhITYE-ADdTdu9KRbv:berhkv1) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L120)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Ugh, it took me a some time to figure out. GSON is doing escapement and inlining of the data in the request, so I had to match the changes to make a proper comparison. Couldn't find a better way
</blockquote></details>

interesting -- do you happen to know if this will cause any issues when trying to read/write the data on the front end? 
___
*[`util/src/main/java/google/registry/util/CidrAddressBlock.java` line 489 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc8esD-L2llJWOu2UD:-NZhFT8-5zdp22PQTxB5:baee7s2) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/util/src/main/java/google/registry/util/CidrAddressBlock.java#L489)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

As far as I understand closing the reader is not part of data adapters responsibility, at least I've not seen it done in an adapter:
**Data adapter you added** - https://cs.opensource.google/nomulus/nomulus/+/master:util/src/main/java/google/registry/util/DateTimeTypeAdapter.java;l=35 
**Google Maps project** - https://github.com/googlemaps/google-maps-services-java/blob/main/src/main/java/com/google/maps/internal/FareAdapter.java#L40

</blockquote></details>

haha fair enough! 


<!-- Sent from Reviewable.io -->

2023-07-07 19:03 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2057)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 113 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbxAzl9M2YnQ9fWONp:-NZlbYmd0NVlKn00t-_q:b-ynxlda) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L113)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ah ok, I think we might not need that because we create a new object here. Have you tried not detaching it here? I think in RegistrarSettingsAction we have to do that because when we update linked objects (e.g. contacts) the original registrar object updates, even if we use `asBuilder` 

Basically, there we only did it because we needed to make 100% sure that we had a reference to the old object (which shouldn't be necessary here) 
</blockquote></details>

I see, thanks for the clarification. Removed.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbySzbEeXamL9UMrYZ:-NZlcAsy9G0vyZl04FUn:bvdpm6q) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L139)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It looks like all those checks are already covered by the permission check we do above though (which makes sense, since if you have EDIT_ on a registrar, you have access to that registrar) 
</blockquote></details>

This is the case I don't see covered in perm check - https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/auth/AuthenticatedRegistrarAccessor.java;l=231

However per your suggestion I have moved catch block
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 95 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5FIe7eZFtx0s5lm1:-NZlcWnM2jBm0WTIxWGP:b-pqesmj) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L95)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it's the same amount of work (it's created once per test), it's a line of code removed, and it means that we create + declare at the same time which is good
</blockquote></details>

Moved the line to `createAction` method.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 120 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5i5t0gt4chNHr9Xv:-NZlhr5b0ZHrCO70L7o5:b74sbio) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L120)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

interesting -- do you happen to know if this will cause any issues when trying to read/write the data on the front end? 
</blockquote></details>

No, it's just an innocence here, because I have to compare it to the string I declared. 


<!-- Sent from Reviewable.io -->

2023-07-07 20:22 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2057)* status: 5 of 8 files reviewed, 6 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 143 at r4](https://reviewable.io/reviews/google/nomulus/2057#gh-1256344060:-NZm0MSF1s7MHNWCihMj:b87f0hv) ([raw file](https://github.com/google/nomulus/blob/4ebe52bf470bb39cb9ce9d4286fabea4e5f587b9/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L143)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Boxed variable is never null

The variable 'hasInvalidCerts' is only assigned values of primitive type and is never 'null', but it is declared with the boxed type 'Boolean'.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1537)
</blockquote></details>

Seems like this should be `boolean`


<!-- Sent from Reviewable.io -->

2023-07-07 20:26 UTC, gbrodman requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2057)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 113 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbxAzl9M2YnQ9fWONp:-NZlw4kZD0iob_kTW3T5:b-pmf5hk) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L113)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I see, thanks for the clarification. Removed.
</blockquote></details>

yep -- I meant to mention this in a previous comment but specifically that's because we needed / wanted to send out email updates 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 139 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZbySzbEeXamL9UMrYZ:-NZlvPtB49dpg6UIkG7w:bby6ggc) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L139)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

This is the case I don't see covered in perm check - https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/auth/AuthenticatedRegistrarAccessor.java;l=231

However per your suggestion I have moved catch block
</blockquote></details>

yeah that is....a super weird exception that should never ever happen hahaha (we probably could even just remove it) 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 99 at r4](https://reviewable.io/reviews/google/nomulus/2057#-NZm0_Bg0BeN1d44fFac:-NZm0_Bg0BeN1d44fFad:b-ox7igc) ([raw file](https://github.com/google/nomulus/blob/4ebe52bf470bb39cb9ce9d4286fabea4e5f587b9/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L99)):*
> ```Java
> 
>   private void postHandler() {
>     Registrar savedRegistrar;
> ```

variables should be declared as close as possible to when they're used go/java-style#s4.8.2.2-variables-limited-scope 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 121 at r4](https://reviewable.io/reviews/google/nomulus/2057#-NZm0nBC1TkP4w6k9Vzw:-NZm0nBC1TkP4w6k9Vzx:b-mvxswn) ([raw file](https://github.com/google/nomulus/blob/4ebe52bf470bb39cb9ce9d4286fabea4e5f587b9/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L121)):*
> ```Java
> 
>     Registrar registrarParameter = registrar.get();
>     tm().transact(
> ```

optional: it's possible that it would be neater whitespace-wise to have the within-transaction code in a separate method.

i don't know if that's actually the case, worth thinking about if you haven't 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 143 at r4](https://reviewable.io/reviews/google/nomulus/2057#gh-1256344060:-NZlvHE99fkddq0q5575:b2nigms) ([raw file](https://github.com/google/nomulus/blob/4ebe52bf470bb39cb9ce9d4286fabea4e5f587b9/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L143)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Seems like this should be `boolean`
</blockquote></details>

yee
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 95 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5FIe7eZFtx0s5lm1:-NZlzotEBOtZr0rcmDua:b-volgvc) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L95)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Moved the line to `createAction` method.
</blockquote></details>

that's still not at the declaration, which is the best way of doing it 

each class variable is created anew before each and every test

https://www.youtube.com/watch?v=cs2Wu9Co-2s
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 73 at r4](https://reviewable.io/reviews/google/nomulus/2057#-NZm-VC0E688xKN4HTkv:-NZm-VC0E688xKN4HTkw:bmauuyu) ([raw file](https://github.com/google/nomulus/blob/4ebe52bf470bb39cb9ce9d4286fabea4e5f587b9/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L73)):*
> ```Java
>   private final HttpServletRequest request = mock(HttpServletRequest.class);
>   private static final Gson GSON = UtilsModule.provideGson();
>   private FakeResponse response;
> ```

somewhat nitty, but variable declarations should be grouped by variable type (meaning private/public, static/non-static)  


<!-- Sent from Reviewable.io -->

2023-07-07 20:28 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2057)* status: all files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)



<!-- Sent from Reviewable.io -->

2023-07-12 14:51 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2057)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 99 at r4](https://reviewable.io/reviews/google/nomulus/2057#-NZm0_Bg0BeN1d44fFac:-N_-xEhT1pj8TIfh0xZm:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4ebe52bf470bb39cb9ce9d4286fabea4e5f587b9/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L99)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

variables should be declared as close as possible to when they're used go/java-style#s4.8.2.2-variables-limited-scope 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 121 at r4](https://reviewable.io/reviews/google/nomulus/2057#-NZm0nBC1TkP4w6k9Vzw:-N_9Qr_XEn3-wGR_kylH:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/4ebe52bf470bb39cb9ce9d4286fabea4e5f587b9/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L121)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

optional: it's possible that it would be neater whitespace-wise to have the within-transaction code in a separate method.

i don't know if that's actually the case, worth thinking about if you haven't 
</blockquote></details>

Updated
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 143 at r4](https://reviewable.io/reviews/google/nomulus/2057#gh-1256344060:-N_0OjIcB8nr1rNAiBp8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4ebe52bf470bb39cb9ce9d4286fabea4e5f587b9/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L143)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yee
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 95 at r2](https://reviewable.io/reviews/google/nomulus/2057#-NZc5FIe7eZFtx0s5lm1:-N_9_RwlCB4BoAOQKIPD:b-896fix) ([raw file](https://github.com/google/nomulus/blob/31cc5037fd518983e1a1affd3c935cc725f1ce07/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L95)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

that's still not at the declaration, which is the best way of doing it 

each class variable is created anew before each and every test

https://www.youtube.com/watch?v=cs2Wu9Co-2s
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 73 at r4](https://reviewable.io/reviews/google/nomulus/2057#-NZm-VC0E688xKN4HTkv:-N_0P4LR0XoUVokuerVO:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4ebe52bf470bb39cb9ce9d4286fabea4e5f587b9/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L73)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

somewhat nitty, but variable declarations should be grouped by variable type (meaning private/public, static/non-static)  
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-12 20:19 UTC, gbrodman approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2057)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot])



<!-- Sent from Reviewable.io -->

2023-07-12 20:19 UTC, merged