Fix minor RDAP typo
google/nomulus pull request #2062
Opened 2023-06-22 23:23 UTC by gbrodman

2023-06-27 20:13 UTC, CydeWeys reviewed
Commit message should mention this is for RDAP compliance with the new published profile, and link to further information (e.g. the profile, conformance checker tool, etc.).

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2062#-:-NYyU7ft6YHb8bMFI5t6:b1cj2mu)* status: 0 of 12 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-27 21:30 UTC, gbrodman reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2062#-:-NYyl17R5LkaqPxQ4Wu5:b-896fix)* status: 0 of 12 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-28 18:12 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2062)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/test/java/google/registry/rdap/RdapTestHelper.java` line 142 at r1](https://reviewable.io/reviews/google/nomulus/2062#-NZ2C3K4C4jBsVjJUfyr:-NZ2C3K4C4jBsVjJUfys:bg0nikf) ([raw file](https://github.com/google/nomulus/blob/c11fc0394503e8e25b7bffcb1ba30ce4313f75c0/core/src/test/java/google/registry/rdap/RdapTestHelper.java#L142)):*
> ```Java
>                 "description",
>                 ImmutableList.of(
>                     "URL of the ICANN RDDS Inaccuracy Complaint Form:" + " https://icann.org/wicf"),
> ```

No need to concatenate two separate strings now.


<!-- Sent from Reviewable.io -->

2023-06-28 18:12 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2062#-:-NZ2CA3uDLrF4Etqdn2F:bnfp4nl)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2023-06-29 18:40 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2062)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/test/java/google/registry/rdap/RdapTestHelper.java` line 142 at r1](https://reviewable.io/reviews/google/nomulus/2062#-NZ2C3K4C4jBsVjJUfyr:-NZ7SDQW9CgboNbrUX35:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c11fc0394503e8e25b7bffcb1ba30ce4313f75c0/core/src/test/java/google/registry/rdap/RdapTestHelper.java#L142)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

No need to concatenate two separate strings now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-30 16:24 UTC, merged