Add minor refactoring follow-up for RefreshDnsForAllDomainsAction
google/nomulus pull request #2063
Opened 2023-06-23 20:12 UTC by CydeWeys

This is a follow-on to comments in PR #2037. It makes the main loop cleaner and also removes ambiguities around database handling when the first query is run with the cursor still empty because no results have been found yet.

2023-06-28 15:30 UTC, CydeWeys reviewed
+reviewer:@gbrodman 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2063#-:-NZ1cAOv9xh7QqTDSGcA:b3une8x)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2023-06-29 19:28 UTC, gbrodman requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2063)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 96 at r1](https://reviewable.io/reviews/google/nomulus/2063#-NZ7bonH5DWKeK4WdYbK:-NZ7bonI1XCwrgfpXlZB:b-27m9yt) ([raw file](https://github.com/google/nomulus/blob/53100ed0e5a9159b8526acc28d1dad93272439f0/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L96)):*
> ```Java
>       Optional<String> lastInPreviousBatchOpt = Optional.ofNullable(lastInPreviousBatch);
>       domainsBatch = tm().transact(() -> refreshBatch(lastInPreviousBatchOpt, smearMinutes));
>       lastInPreviousBatch = domainsBatch.isEmpty() ? null : getLast(domainsBatch);
> ```

we don't need to ever use a nullable string, can do 
`lastInPreviousBatchOpt = Optional.ofNullable(getLast(domainsBatch, null))`

seems odd to kinda mix nullables and optionals 
___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2063#-NZ7c8Mc8ba_KNeDo51y:-NZ7c8Mc8ba_KNeDo51z:beycnqr) ([raw file](https://github.com/google/nomulus/blob/53100ed0e5a9159b8526acc28d1dad93272439f0/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L125)):*
> ```Java
>             .setParameter("tlds", tlds)
>             .setParameter("endOfTime", END_OF_TIME);
>     if (lastInPreviousBatch.isPresent()) {
> ```

is it cleaner to use `Optional::ifPresent`? 


<!-- Sent from Reviewable.io -->

2023-06-30 19:54 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2063)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 96 at r1](https://reviewable.io/reviews/google/nomulus/2063#-NZ7bonH5DWKeK4WdYbK:-NZCrOyC3rBm7aFo_4no:b-nio9i3) ([raw file](https://github.com/google/nomulus/blob/53100ed0e5a9159b8526acc28d1dad93272439f0/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L96)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we don't need to ever use a nullable string, can do 
`lastInPreviousBatchOpt = Optional.ofNullable(getLast(domainsBatch, null))`

seems odd to kinda mix nullables and optionals 
</blockquote></details>

You actually do need two separate variables here because whatever is passed to the transact lambda must be effectively `final`, and a variable defined outside the loop scope is not.


<!-- Sent from Reviewable.io -->

2023-06-30 19:55 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2063)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2063#-NZ7c8Mc8ba_KNeDo51y:-NZCs-d6CMYSnsVZIC7E:b-a30qci) ([raw file](https://github.com/google/nomulus/blob/53100ed0e5a9159b8526acc28d1dad93272439f0/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L125)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

is it cleaner to use `Optional::ifPresent`? 
</blockquote></details>

Not possible because `query` is not effectively final.  This was my first stab at it too, but it doesn't work.


<!-- Sent from Reviewable.io -->

2023-07-05 17:05 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2063)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 96 at r1](https://reviewable.io/reviews/google/nomulus/2063#-NZ7bonH5DWKeK4WdYbK:-NZb-h5LBgH28VpGZSaq:b2pxare) ([raw file](https://github.com/google/nomulus/blob/53100ed0e5a9159b8526acc28d1dad93272439f0/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L96)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You actually do need two separate variables here because whatever is passed to the transact lambda must be effectively `final`, and a variable defined outside the loop scope is not.
</blockquote></details>

ah I see, that's annoying :( 
___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2063#-NZ7c8Mc8ba_KNeDo51y:-NZazj0C9TyHJVb0OgK9:bwi2qtn) ([raw file](https://github.com/google/nomulus/blob/53100ed0e5a9159b8526acc28d1dad93272439f0/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L125)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Not possible because `query` is not effectively final.  This was my first stab at it too, but it doesn't work.
</blockquote></details>

is that only because of the reassignment inside the `if` statement? 

fwiw the reassignment isn't necessary; it's all the same instance 


<!-- Sent from Reviewable.io -->

2023-07-05 18:23 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2063)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2063#-NZ7c8Mc8ba_KNeDo51y:-NZbHjXO7vCxcXc_KTMy:bdkrvkg) ([raw file](https://github.com/google/nomulus/blob/53100ed0e5a9159b8526acc28d1dad93272439f0/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L125)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

is that only because of the reassignment inside the `if` statement? 

fwiw the reassignment isn't necessary; it's all the same instance 
</blockquote></details>

I'm aware that the reassignment is not necessary, and the issue is not because of that.  Changing it to the following line:

```
lastInPreviousBatch.ifPresent(() -> query.setParameter("lastInPreviousBatch", lastInPreviousBatch.get()));
```

yields the following error on the attempted use of `query`:

```
Variable used in lambda expression should be final or effectively final
```


<!-- Sent from Reviewable.io -->

2023-07-05 18:25 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2063)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2063#-NZ7c8Mc8ba_KNeDo51y:-NZbIKPI7_w9q22ZPz80:bydc6sj) ([raw file](https://github.com/google/nomulus/blob/53100ed0e5a9159b8526acc28d1dad93272439f0/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L125)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I'm aware that the reassignment is not necessary, and the issue is not because of that.  Changing it to the following line:

```
lastInPreviousBatch.ifPresent(() -> query.setParameter("lastInPreviousBatch", lastInPreviousBatch.get()));
```

yields the following error on the attempted use of `query`:

```
Variable used in lambda expression should be final or effectively final
```
</blockquote></details>

Wait never mind, that was a bad use of `ifPresent()`.  I fixed it now so that it works.


<!-- Sent from Reviewable.io -->

2023-07-05 19:04 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2063)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2023-07-05 19:09 UTC, merged