Replace less compiler with scss
google/nomulus pull request #2114
Opened 2023-08-17 20:43 UTC by ptkach

2023-08-28 20:46 UTC, gbrodman requested changes
> Reviewed 24 of 37 files at r1, 9 of 13 files at r2, 10 of 10 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2114)* status: all files reviewed, 18 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/angular.json` line 35 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxh6Dr9AcRLjbl1D9W:-Ncxh6Dr9AcRLjbl1D9X:bq78gik) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/angular.json#L35)):*
> ```JSON
>             ],
>             "stylePreprocessorOptions": {
>               "includePaths": ["node_modules/"]
> ```

is there any downside to directly including all stylesheets like this? The main one that I can think of is that it might present too many options 
___
*[`console-webapp/src/theme.scss` line 1 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxmEeC3ha5JPXFqC-i:-NcxmEeC3ha5JPXFqC-j:b-68wi4j) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/theme.scss#L1)):*
> ```SCSS
> @use "sass:map";
> ```

It looks like some of this file is taken from some of the Angular docs. Is it copy-pasted directly from somewhere, or are there significant changes? Might be good to note which was already provided and which (if any) are custom 
___
*[`console-webapp/src/app/app.component.ts` line 17 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxmrOb9BR-o9ORUYJI:-NcxmrOb9BR-o9ORUYJJ:b-gjv9ek) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/app.component.ts#L17)):*
> ```XML
> import { Component } from '@angular/core';
> import { RegistrarService } from './registrar/registrar.service';
> import { Router } from '@angular/router';
> ```

I don't think we need the Router import?
___
*[`console-webapp/src/app/app.component.ts` line 34 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxp4eB5bbNM7GVpAh5:-Ncxp4eB5bbNM7GVpAh6:b9nts5c) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/app.component.ts#L34)):*
> ```XML
>       this.renderRouter = false;
>       setTimeout(() => {
>         this.renderRouter = true;
> ```

Where is the `router-outlet` component created/used? 
___
*[`console-webapp/src/app/registrar/emptyRegistrar.component.html` line 6 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxr7F5AC_iOq_66XOq:-Ncxr7F5AC_iOq_66XOr:b-kdjx2y) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/emptyRegistrar.component.html#L6)):*
> ```HTML
>   </h1>
>   <h1>No registrar selected</h1>
>   <h4 class="mat-body-2">Please select the registrar</h4>
> ```

nit: `Please select a registrar`
___
*[`console-webapp/src/app/registrar/emptyRegistrar.component.html` line 7 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrGFsBpEfi4IncIR7:-NcxrGFsBpEfi4IncIR8:b-npxnj1) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/emptyRegistrar.component.html#L7)):*
> ```HTML
>   <h1>No registrar selected</h1>
>   <h4 class="mat-body-2">Please select the registrar</h4>
> </div>
> ```

not directly related to this file, but we'll want to handle the case where the user tries to access elements from the hamburger menu when there isn't a registrar selected 
___
*[`console-webapp/src/app/registrar/emptyRegistrar.component.ts` line 26 at r4](https://reviewable.io/reviews/google/nomulus/2114#-NcxtMfe5Y8hMUWPJPPG:-NcxtMfe5Y8hMUWPJPPH:b-x889yx) ([raw file](https://github.com/google/nomulus/blob/0801f521fcdcf5556904890f3f8d9d76ad1c0899/console-webapp/src/app/registrar/emptyRegistrar.component.ts#L26)):*
> ```XML
> })
> export class EmptyRegistrar {
>   private navigate?: Subscription;
> ```

it's not clear from the variable name what `navigate` is / does 
___
*[`console-webapp/src/app/registrar/registrar-selector.component.html` line 1 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrPDn3YOkGWdo7a0D:-NcxrPDoEtKV1wLugMt1:b-bdj2nb) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar-selector.component.html#L1)):*
> ```HTML
> <div class="console-app__registrar">
> ```

What would it take to make the registrar select box searchable? e.g. I can type in it, I type `larrytest` and it shows `larrytest` and `larrytest2`? 
___
*[`console-webapp/src/app/registrar/registrar-selector.component.html` line 7 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxpe-k1eglzJ7JcuF9:-Ncxpe-k1eglzJ7JcuFA:bzcjz1k) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar-selector.component.html#L7)):*
> ```HTML
>       <mat-select
>         [ngModel]="registrarService.activeRegistrarId"
>         (selectionChange)="registrarService.updateRegistrar($any($event.value))"
> ```

what's up with the `$any`? 
___
*[`console-webapp/src/app/registrar/registrar.component.html` line 6 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrewtBTTWM6UR5ah7:-NcxrewtBTTWM6UR5ah8:bw6x6p0) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.component.html#L6)):*
> ```HTML
>     [dataSource]="registrarService.registrars"
>     class="mat-elevation-z8"
>   >
> ```

It seems kind of odd to me that the table with all the registrars is gated behind selecting a  particular registrar. I believe you mentioned re-organizing it so that isn't the case, just wanted to flag it here regardless 
___
*[`console-webapp/src/app/registrar/registrar.component.html` line 46 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrzniEBYcg4sbQtcF:-NcxrzniEBYcg4sbQtcG:bgpwtps) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.component.html#L46)):*
> ```HTML
>     </ng-container>
>     <ng-container matColumnDef="billingAccountMap">
>       <th mat-header-cell *matHeaderCellDef>driveFolderId</th>
> ```

hehe probably want to change the header name
___
*[`console-webapp/src/app/registrar/registrar.component.html` line 62 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxs3SK4I2sgejpYPDI:-Ncxs3SK4I2sgejpYPDJ:b-85jsm0) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.component.html#L62)):*
> ```HTML
>     <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
>   </table>
> </div>
> ```

Is this currently deployed on alpha? It seems a bit different 
___
*[`console-webapp/src/app/registrar/registrar.component.ts` line 23 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxsOm5BW8m6z1hqloF:-NcxsOm5BW8m6z1hqloG:b1do8p4) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.component.ts#L23)):*
> ```XML
>   templateUrl: './registrar.component.html',
>   styleUrls: ['./registrar.component.scss'],
> })
> ```

Thoughts on renaming this to be a bit more descriptive? Something like `RegistrarsComponent`, `RegistrarsTableComponent`, or `RegistrarsListComponent`? The current name doesn't seem to match. 
___
*[`console-webapp/src/app/registrar/registrar.component.ts` line 24 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxsJYd4ZtkrYwhFSFa:-NcxsJYd4ZtkrYwhFSFb:b-hr0usb) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.component.ts#L24)):*
> ```XML
>   styleUrls: ['./registrar.component.scss'],
> })
> export class RegistrarComponent {
> ```

I'm a bit confused, because it looks like we have the list of colum [...]

2023-08-29 18:59 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2114)* status: all files reviewed, 17 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`console-webapp/angular.json` line 35 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxh6Dr9AcRLjbl1D9W:-Nd1bQfSD3i-TpvPxIWo:bbu3h3c) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/angular.json#L35)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

is there any downside to directly including all stylesheets like this? The main one that I can think of is that it might present too many options
</blockquote></details>

This question is confusing. We're not including all stylesheets by doing this. We just merely configure a compiler to automatically prepend style imports with `node_modules/`, this just allows us to write less code and more straightforward imports. 
___
*[`console-webapp/src/theme.scss` line 1 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxmEeC3ha5JPXFqC-i:-Nd1cdriBDa8gDjThQ2n:b-ls5u1d) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/theme.scss#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It looks like some of this file is taken from some of the Angular docs. Is it copy-pasted directly from somewhere, or are there significant changes? Might be good to note which was already provided and which (if any) are custom
</blockquote></details>

To be clear just`$theme-*` definitions and `define-light-theme()`  were taken from the docs, as it's more or less common unless we wanna tune the colors for them more. Everything else is custom. Not sure there's any need to provide more notes besides those already in there
___
*[`console-webapp/src/app/app.component.ts` line 17 at r3](https://reviewable.io/reviews/google/nomulus/2114#gh-1304850843:-Nd1TuOHC56L8devHNdW:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/app.component.ts#L17)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import Router.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1557)
</blockquote></details>

Done.
___
*[`console-webapp/src/app/app.component.ts` line 17 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxmrOb9BR-o9ORUYJI:-Nd1Tumr8CX9lrf8Xj26:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/app.component.ts#L17)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think we need the Router import?
</blockquote></details>

Done.
___
*[`console-webapp/src/app/app.component.ts` line 34 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxp4eB5bbNM7GVpAh5:-Nd1TzH62rCrZ-EdB3h4:b-y6h555) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/app.component.ts#L34)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Where is the `router-outlet` component created/used?
</blockquote></details>

it's in `app.component.html` and it's where router renders the components based on a routing map
___
*[`console-webapp/src/app/registrar/emptyRegistrar.component.html` line 7 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrGFsBpEfi4IncIR7:-Nd1UPMq2Qnb40rn6krX:btosc7y) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/emptyRegistrar.component.html#L7)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

not directly related to this file, but we'll want to handle the case where the user tries to access elements from the hamburger menu when there isn't a registrar selected
</blockquote></details>

Well technically it's handled already in a way that prevents users to visit any page that's guarded by `registrar.guard.ts` and renders `emptyRegistrar.component.ts` instead, forcing the users to select registrar. 
___
*[`console-webapp/src/app/registrar/emptyRegistrar.component.ts` line 26 at r4](https://reviewable.io/reviews/google/nomulus/2114#-NcxtMfe5Y8hMUWPJPPG:-Nd1Uyey0kj_McnjID0J:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0801f521fcdcf5556904890f3f8d9d76ad1c0899/console-webapp/src/app/registrar/emptyRegistrar.component.ts#L26)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it's not clear from the variable name what `navigate` is / does
</blockquote></details>

Done.
___
*[`console-webapp/src/app/registrar/registrar-selector.component.html` line 1 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrPDn3YOkGWdo7a0D:-Nd1V9nz-02zLaptv5Ro:buzj4sh) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar-selector.component.html#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What would it take to make the registrar select box searchable? e.g. I can type in it, I type `larrytest` and it shows `larrytest` and `larrytest2`?
</blockquote></details>

Technically it already is as any browser `select` these days. You can put a focus in element and start typing `larrytest`, which will make browser scroll to and highlight the element in the list. And again this is default browser behavior and material component we use just follows it. 
If we want to make it search with filter, we need to create a new component and program all interactions ourselves, like type in, cancel, focus, make accessible, etc
___
*[`console-webapp/src/app/registrar/registrar-selector.component.html` line 7 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxpe-k1eglzJ7JcuF9:-Nd1WtuHEmLXYtNKwq5V:b7n0uy4) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar-selector.component.html#L7)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what's up with the `$any`?
</blockquote></details>

I'd it as a `$event.target.value` at first, which TS compiler didn't exactly like, because it's not aware what `$event.target` type was. BTW `event.target.value` is a legit way to get value in JS. to stop TS from throwing I added `$any`, which seems to be a common solution in similar cases. Then however I figured `mat-select` provides value in `$event.value` without needing to reference the target. `$any` hasn't been cleaned out, that's all. 
___
*[`console-webapp/src/app/registrar/registrar.component.html` line 6 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrewtBTTWM6UR5ah7:-Nd1YLczBOQNYJcIYhL5:b-m4lok7) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.component.html#L6)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It seems kind of odd to me that the table with all the registrars is gated behind selecting a  particular registrar. I believe you mentioned re-organizing it so that isn't the case, just wanted to flag it here regardless
</blockquote></details>

Yeah, I removed the guard on Settings component parent and added it to particular pages instead. I also removed a link from hamburger menu. 
___
*[`console-webapp/src/app/registrar/registrar.component.html` line 46 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrzniEBYcg4sbQtcF:-Nd1Y_lABQLB-9brh0k_:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.component.html#L46)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

hehe probably  [...]

2023-08-29 20:32 UTC, gbrodman requested changes
> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2114)* status: all files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`console-webapp/angular.json` line 35 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxh6Dr9AcRLjbl1D9W:-Nd1fZOu6MjrY5mBqq7Z:b-8whfo6) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/angular.json#L35)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

This question is confusing. We're not including all stylesheets by doing this. We just merely configure a compiler to automatically prepend style imports with `node_modules/`, this just allows us to write less code and more straightforward imports.
</blockquote></details>

ohhh i see, so they'll still be qualified with `node_modules/...` cool
___
*[`console-webapp/src/theme.scss` line 1 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxmEeC3ha5JPXFqC-i:-Nd1zWVn8FrO_c8ujQIo:b-fkztuj) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/theme.scss#L1)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

To be clear just`$theme-*` definitions and `define-light-theme()`  were taken from the docs, as it's more or less common unless we wanna tune the colors for them more. Everything else is custom. Not sure there's any need to provide more notes besides those already in there
</blockquote></details>

that makes sense re: the `$theme` items 

just to make it clear, can we just separate out the "copied from docs" and "custom" blocks so that it's clear where we got this from for any future people reading it? 
___
*[`console-webapp/src/app/app.component.ts` line 34 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxp4eB5bbNM7GVpAh5:-Nd1k9o_2UgqAzuBEHMh:bg4znpu) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/app.component.ts#L34)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

it's in `app.component.html` and it's where router renders the components based on a routing map
</blockquote></details>

To be more clear with my question: I see that in this PR we're only including the `router-outlet` (tag) element if `renderRouter` here is true. I'm wondering what actually determines what gets rendered inside the `router-outlet` element, because I don't see any of our files referencing that tag. 

Or is it just automatically populated when we use the Angular router in AppRoutingModule?
___
*[`console-webapp/src/app/registrar/emptyRegistrar.component.html` line 7 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrGFsBpEfi4IncIR7:-Nd1zAVa5Kt0Wb804ItG:b-okye51) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/emptyRegistrar.component.html#L7)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Well technically it's handled already in a way that prevents users to visit any page that's guarded by `registrar.guard.ts` and renders `emptyRegistrar.component.ts` instead, forcing the users to select registrar.
</blockquote></details>

Yeah, I'm thinking we'll just want to signal these in some way, like graying out the buttons when the registrar isn't selected. Something like that, doesn't need to be in this PR 
___
*[`console-webapp/src/app/registrar/registrar-selector.component.html` line 1 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrPDn3YOkGWdo7a0D:-Nd1m8K70yIXfWUUytme:bf7tak2) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar-selector.component.html#L1)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Technically it already is as any browser `select` these days. You can put a focus in element and start typing `larrytest`, which will make browser scroll to and highlight the element in the list. And again this is default browser behavior and material component we use just follows it. 
If we want to make it search with filter, we need to create a new component and program all interactions ourselves, like type in, cancel, focus, make accessible, etc
</blockquote></details>

ah, the latter bit is annoying. And for the former, I must have been not focusing the element properly 
___
*[`console-webapp/src/app/registrar/registrar-selector.component.html` line 7 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxpe-k1eglzJ7JcuF9:-Nd1nZCi8_4RLeK3RxHt:b9sz23w) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar-selector.component.html#L7)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I'd it as a `$event.target.value` at first, which TS compiler didn't exactly like, because it's not aware what `$event.target` type was. BTW `event.target.value` is a legit way to get value in JS. to stop TS from throwing I added `$any`, which seems to be a common solution in similar cases. Then however I figured `mat-select` provides value in `$event.value` without needing to reference the target. `$any` hasn't been cleaned out, that's all.
</blockquote></details>

oh neat
___
*[`console-webapp/src/app/registrar/registrar.service.ts` line 22 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxt4jo7CYxiudS7HHF:-Nd1nd4CCt7hCinxpQ8W:b8den8m) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.service.ts#L22)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Yeah, I was testing with data on Alpha and there's a lot of blanks, which made TS complain a lot. So far I feel like at the end of the day it slows me down more than helps me out. Looking forward to when the project grows more and we start to rip those benefits.
</blockquote></details>

hmmm weird, might be old / test data in alpha that isn't ideal. Oh well. 
___
*[`console-webapp/src/app/registrar/registrar.component.ts` line 24 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxsJYd4ZtkrYwhFSFa:-Nd1pALf334I_xdcLD9U:b-z1f49d) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.component.ts#L24)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

This page is far from being finished. As I mentioned I just quickly put it together to provide a better sense of how user interactions with registrar selector and page would work. Which I think was helpful, because you provided some valuable feedback here already, which I can now incorporate into actual implementation.
</blockquote></details>

right yeah that makes sense, but we should probably remove the one that isn't being used right? 


<!-- Sent from Reviewable.io -->

2023-08-30 20:02 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2114)* status: 44 of 47 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`console-webapp/src/theme.scss` line 1 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxmEeC3ha5JPXFqC-i:-Nd6rHIp8yGRNIVEfyvY:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/theme.scss#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

that makes sense re: the `$theme` items 

just to make it clear, can we just separate out the "copied from docs" and "custom" blocks so that it's clear where we got this from for any future people reading it?
</blockquote></details>

Done.
___
*[`console-webapp/src/app/app.component.ts` line 34 at r3](https://reviewable.io/reviews/google/nomulus/2114#-Ncxp4eB5bbNM7GVpAh5:-Nd6rJP-1JLpKa9wbPNU:bw92yat) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/app.component.ts#L34)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

To be more clear with my question: I see that in this PR we're only including the `router-outlet` (tag) element if `renderRouter` here is true. I'm wondering what actually determines what gets rendered inside the `router-outlet` element, because I don't see any of our files referencing that tag. 

Or is it just automatically populated when we use the Angular router in AppRoutingModule?
</blockquote></details>

Router map determines what component is placed in the router-outlet. `renderRouter` toggle here is just a very easy and straightforward way for us to reload the components once registrar selection changes. 
___
*[`console-webapp/src/app/registrar/emptyRegistrar.component.html` line 7 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxrGFsBpEfi4IncIR7:-Nd6rcH51Jx4RYqEKkYW:b-xmif09) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/emptyRegistrar.component.html#L7)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah, I'm thinking we'll just want to signal these in some way, like graying out the buttons when the registrar isn't selected. Something like that, doesn't need to be in this PR
</blockquote></details>

We will need to think more about it, because not all the pages will need to be disabled. For instance we will allow to visit Settings -> Registrars even before selection's made
___
*[`console-webapp/src/app/registrar/registrar.component.ts` line 24 at r3](https://reviewable.io/reviews/google/nomulus/2114#-NcxsJYd4ZtkrYwhFSFa:-Nd71RZb2tKRP8mu1web:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c29482fd17603e1779e45b406afc8f94a0ffd1f4/console-webapp/src/app/registrar/registrar.component.ts#L24)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

right yeah that makes sense, but we should probably remove the one that isn't being used right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-01 12:42 UTC, gbrodman requested changes
this change is much bigger than the current commit message + title haha, we should probably update it

> Reviewed 1 of 41 files at r1, 49 of 52 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2114#-:-NdFl-pl8mIxtxW9weHW:b-l5ljlg)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`console-webapp/src/app/home/widgets/contact-widget.component.html` line 16 at r8](https://reviewable.io/reviews/google/nomulus/2114#-NdFkP7l2VPcyzC5Rhxi:-NdFkP7l2VPcyzC5Rhxj:bcnwmhj) ([raw file](https://github.com/google/nomulus/blob/73ffabe7390c6227213c198a49b3dc9539a55193/console-webapp/src/app/home/widgets/contact-widget.component.html#L16)):*
> ```HTML
>         </button>
>         <p class="secondary-text">
>           Call Google Registry support at +1 (404) 978 8419
> ```

as a TODO we will need to fill this out with info from the backend (open source and all, haha) 
___
*[`console-webapp/src/app/home/widgets/promotions-widget.component.html` line 13 at r8](https://reviewable.io/reviews/google/nomulus/2114#-NdFkaIy4-Kj4aLzY4w4:-NdFkaIy4-Kj4aLzY4w5:byv4mu5) ([raw file](https://github.com/google/nomulus/blob/73ffabe7390c6227213c198a49b3dc9539a55193/console-webapp/src/app/home/widgets/promotions-widget.component.html#L13)):*
> ```HTML
>       <div class="console-app__widget_right">
>         <button mat-button color="primary" class="console-app__widget-link">
>           Manage Preffered Parner Program
> ```

nit: Preferred (same below) 
___
*[`console-webapp/src/app/home/widgets/promotions-widget.component.html` line 19 at r8](https://reviewable.io/reviews/google/nomulus/2114#-NdFkdbhCcRAJAo1m7Ox:-NdFkdbhCcRAJAo1m7Oy:b-j3wvzw) ([raw file](https://github.com/google/nomulus/blob/73ffabe7390c6227213c198a49b3dc9539a55193/console-webapp/src/app/home/widgets/promotions-widget.component.html#L19)):*
> ```HTML
>         </p>
>         <button mat-button color="primary" class="console-app__widget-link">
>           Manage Registry Lock Program
> ```

nit: we probably don't want title capitalization, in order to be consistent


<!-- Sent from Reviewable.io -->

2023-09-01 13:14 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2114)* status: 66 of 67 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`console-webapp/src/app/home/home.component.ts` line 16 at r6](https://reviewable.io/reviews/google/nomulus/2114#gh-1312154782:-NdFqcSe1hnhmn7G6DHF:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8a117835730cb283c980b61e21bb93065acbb585/console-webapp/src/app/home/home.component.ts#L16)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import ContactWidgetComponent.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1559)
</blockquote></details>

Done.
___
*[`console-webapp/src/app/home/widgets/contact-widget.component.html` line 16 at r8](https://reviewable.io/reviews/google/nomulus/2114#-NdFkP7l2VPcyzC5Rhxi:-NdFqeIg7yVTJFip_tEv:bk2a9vg) ([raw file](https://github.com/google/nomulus/blob/73ffabe7390c6227213c198a49b3dc9539a55193/console-webapp/src/app/home/widgets/contact-widget.component.html#L16)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

as a TODO we will need to fill this out with info from the backend (open source and all, haha)
</blockquote></details>

Correct, as you can see those widgets are not functional as of now. I've created the markup and styling because I felt that it's weird not to have a home page at this stage haha 
We will replace it with template as soon as we get to the functionality for the widgets. 
___
*[`console-webapp/src/app/home/widgets/promotions-widget.component.html` line 13 at r8](https://reviewable.io/reviews/google/nomulus/2114#-NdFkaIy4-Kj4aLzY4w4:-NdFr4vF4S7PwB-iIoks:b-c3iuc) ([raw file](https://github.com/google/nomulus/blob/73ffabe7390c6227213c198a49b3dc9539a55193/console-webapp/src/app/home/widgets/promotions-widget.component.html#L13)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit: Preferred (same below)
</blockquote></details>

Yep, thanks
___
*[`console-webapp/src/app/home/widgets/promotions-widget.component.html` line 19 at r8](https://reviewable.io/reviews/google/nomulus/2114#-NdFkdbhCcRAJAo1m7Ox:-NdFrXUI5SgXRwx1YfC5:b-f6k9r) ([raw file](https://github.com/google/nomulus/blob/73ffabe7390c6227213c198a49b3dc9539a55193/console-webapp/src/app/home/widgets/promotions-widget.component.html#L19)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit: we probably don't want title capitalization, in order to be consistent
</blockquote></details>

This is how it is on the mockup, as well as the rest of the titles


<!-- Sent from Reviewable.io -->

2023-09-01 15:30 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2114)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot])



<!-- Sent from Reviewable.io -->

2023-09-01 15:48 UTC, merged