Fix Cloud Tasks retry failure
google/nomulus pull request #2118
Opened 2023-08-21 20:33 UTC by weiminyu

Replace `SC_NOT_MODIFIED` (304) with `SC_SERVICE_UNAVAILABLE` (503) when data is not available yet. Affected actions are invoice- and spec11-publishing.

It is confirmed that Cloud Tasks currently does not retry with code 304, despite the public documentation stating so. We will use 503 for now, pending the decision by Cloud Tasks whether to change behavior or documentation.

The code `TOO_EARLY` (425) is another alternative. It is not meant for our use case but at least sounds like it is. However, it is not in any javax.servlet jar. We don't want to define our own constant, and we cannot upgrade to jakarta.servlet yet.

2023-08-22 13:37 UTC, jianglai requested changes
Technically the constants in `javax.servlet.HttpServletResponse` are just aliases to integers, so if we really want to use 425, we could just use the number directly.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2118#-:-NcSSEpzBEH1Cc9c1ISL:b-xte0be)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot and @weiminyu)

___
*[`core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java` line 145 at r1](https://reviewable.io/reviews/google/nomulus/2118#-NcSSVch5-4TtRNY76WF:-NcSSVch5-4TtRNY76WG:b-sq3b3r) ([raw file](https://github.com/google/nomulus/blob/cfcafeefc63df7ef69166eb1c69d5ed76050fe73/core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java#L145)):*
> ```Java
>                     date.toString()),
>                 // TODO(b/296582836): mitigating retry problem. Remove `+10` when bug is fixed.
>                 Duration.standardMinutes(ReportingModule.ENQUEUE_DELAY_MINUTES + 10)));
> ```

Maybe we want to keep the `+10` for now, in case the change in response status doesn't work?



_Code quote:_
```Java
 + 10
```
___
*[`core/src/test/java/google/registry/reporting/spec11/GenerateSpec11ReportActionTest.java` line 97 at r1](https://reviewable.io/reviews/google/nomulus/2118#-NcSShfC4Qu_chLhMyGM:-NcSShfC4Qu_chLhMyGN:b-rqxvo7) ([raw file](https://github.com/google/nomulus/blob/cfcafeefc63df7ef69166eb1c69d5ed76050fe73/core/src/test/java/google/registry/reporting/spec11/GenerateSpec11ReportActionTest.java#L97)):*
> ```Java
>                     .nowUtc()
>                     // TODO(b/296582836): mitigating retry problem. Remove `+10` when bug is fixed.
>                     .plus(Duration.standardMinutes(ReportingModule.ENQUEUE_DELAY_MINUTES + 10))));
> ```

ditto.



_Code quote:_
```Java
 + 10
```


<!-- Sent from Reviewable.io -->

2023-08-22 15:01 UTC, weiminyu reviewed
I'd prefer referencing official API.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2118#-:-NcSkWvyBJZhdomTjDG2:br8lzhc)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java` line 145 at r1](https://reviewable.io/reviews/google/nomulus/2118#-NcSSVch5-4TtRNY76WF:-NcSkg2n8ErWlr6t8gtx:b-e4t2i4) ([raw file](https://github.com/google/nomulus/blob/cfcafeefc63df7ef69166eb1c69d5ed76050fe73/core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java#L145)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Maybe we want to keep the `+10` for now, in case the change in response status doesn't work?
</blockquote></details>

503 is verified to be working in crash. 
___
*[`core/src/test/java/google/registry/reporting/spec11/GenerateSpec11ReportActionTest.java` line 97 at r1](https://reviewable.io/reviews/google/nomulus/2118#-NcSShfC4Qu_chLhMyGM:-NcSkoXDAeVo3cAmtDio:b-q64pkt) ([raw file](https://github.com/google/nomulus/blob/cfcafeefc63df7ef69166eb1c69d5ed76050fe73/core/src/test/java/google/registry/reporting/spec11/GenerateSpec11ReportActionTest.java#L97)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

See above.


<!-- Sent from Reviewable.io -->

2023-08-22 18:20 UTC, weiminyu reviewed
425 is not necessarily better than 503 anyway.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2118#-:-NcTTR1O90bPb0DJtMiV:bwwobez)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2023-08-23 14:55 UTC, jianglai approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2023-08-23 14:55 UTC, merged