Use PrintStream in ConfirmingCommand
google/nomulus pull request #2140
Opened 2023-09-07 21:14 UTC by sarahcaseybot

2023-09-08 20:50 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2140)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tools/LoadTestCommand.java` line 85 at r1](https://reviewable.io/reviews/google/nomulus/2140#-NdqYOiu8WeVnYAco9Re:-NdqYOiu8WeVnYAco9Rf:bjaez24) ([raw file](https://github.com/google/nomulus/blob/d4d262796c3144d320e564a67f3176f7ef37ee06/core/src/main/java/google/registry/tools/LoadTestCommand.java#L85)):*
> ```Java
>   private ServiceConnection connection;
> 
>   PrintStream errorPrintStream;
> ```

How about move this to `ConfirmingCommand` and handle it in the same way we handle System.out/printSteam?



_Code quote:_
```Java
errorPrintStream
```


<!-- Sent from Reviewable.io -->

2023-09-14 18:01 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2140)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java` line 481 at r2](https://reviewable.io/reviews/google/nomulus/2140#-NeJp5WE39SwDQ9B-W4r:-NeJp5WE39SwDQ9B-W4s:by8qszi) ([raw file](https://github.com/google/nomulus/blob/b58a286efb115a41052067e59a0aa50d585d29f1/core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java#L481)):*
> ```Java
>           Joiner.on(", ").join(invalidNames),
>           tld);
>       try (PrintStream errorPrintStream = new PrintStream(System.err, false, UTF_8.name())) {
> ```

This line is no longer necessary.



_Code quote:_
```Java
try (PrintStream errorPrintStream = new PrintStream(System.err, false, UTF_8.name())) {
```
___
*[`core/src/main/java/google/registry/tools/LoadTestCommand.java` line 96 at r2](https://reviewable.io/reviews/google/nomulus/2140#-NeJpxci27CZfgwirfft:-NeJpxci27CZfgwirffu:bldtxlt) ([raw file](https://github.com/google/nomulus/blob/b58a286efb115a41052067e59a0aa50d585d29f1/core/src/main/java/google/registry/tools/LoadTestCommand.java#L96)):*
> ```Java
>     // Check validity of TLD and Client Id.
>     if (!Tlds.getTlds().contains(tld)) {
>       printError(String.format("No such TLD: %s\n", tld));
> ```

Use printf: errorPrintStream.printf("No such TLD: %s\n", tld);



_Code quote:_
```Java
printError(String.format("No such TLD: %s\n", tld))
```


<!-- Sent from Reviewable.io -->

2023-09-19 14:59 UTC, weiminyu approved these changes
> Reviewed 15 of 20 files at r1, 3 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2023-09-19 16:11 UTC, merged

2023-09-27 15:08 UTC, CydeWeys commented
Note that pull request descriptions are not visible from within git.  The only description I see in git [is what appears here](https://github.com/google/nomulus/commit/fc1857717d8298d0fad6063cbcd258c01a29c4a5):

```
Use PrintStream in ConfirmingCommand 
* Use PrintStream in ConfirmingCommand

* Add errorPrintStream

* remove unneccesary line
```

That doesn't include the why of it which is included in your PR description.  Generally the commit description and the PR description should be the same, as the latter is specific to GitHub whereas the former always appears in every clone of the repo at the base git level.