Don't include a nextUrl when accessing the console homepage
google/nomulus pull request #2149
Opened 2023-09-14 18:49 UTC by gbrodman

In this case we should just display the standard page, no need to redirect anywhere since there's nothing to redirect to.

2023-09-14 21:05 UTC, ptkach requested changes
Have you tested it on alpha? I don't think that's what we want, as far as I can predict it's going to navigate to "home page" instead of an "empty registrar page", which is what we want

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2149#-:-NeKVQR-4BJnfZkainoP:b-s9u011)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-14 21:38 UTC, gbrodman commented
just tested this locally and it seems like we just want to tell it go to to nothing (the home page)

2023-09-14 21:45 UTC, ptkach reviewed
we do want it to go to home page after selecting the registrar, you're correct. But that's not what your change does, it allows it to go to home page before making any registrar selection and it goes straight to home page, while it has to go to empty registrar page instead. 

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2149#-:-NeKdc5y01meI8ecNG0k:b-bruy1a)* status: 1 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-15 02:07 UTC, gbrodman reviewed
I don't think you saw the update to the code that I made when writing my previous comment. because that's what it does now. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2149#-:-NeL_kuU8mf9Vr3Hq8NH:b-bt6xud)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ptkach)



<!-- Sent from Reviewable.io -->

2023-09-15 14:17 UTC, ptkach requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2149)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`console-webapp/src/app/registrar/registrar.guard.ts` line 35 at r2](https://reviewable.io/reviews/google/nomulus/2149#-NeOBGO7AtKn9TyYeAqQ:-NeOBGO87LZDVLQipOHg:bw7a309) ([raw file](https://github.com/google/nomulus/blob/4ab472d6aa152c49562ad60e6b03ac75ea3ad0f2/console-webapp/src/app/registrar/registrar.guard.ts#L35)):*
> ```XML
>     // Get the full URL including any nested children (skip the initial '#/')
>     const splits = location.hash.split('#/');
>     const nextUrl = splits.length > 1 ? splits[1] : '';
> ```

Oh, I see. I think it requires a comment that empty nextUrl takes user to a router default page, which in our case is a home page.
Also it can be shortened I believe - `const nextUrl = location.hash.split('#/')[1] || ""`


<!-- Sent from Reviewable.io -->

2023-09-15 15:12 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2149)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`console-webapp/src/app/registrar/registrar.guard.ts` line 35 at r2](https://reviewable.io/reviews/google/nomulus/2149#-NeOBGO7AtKn9TyYeAqQ:-NeOOK9N91FdYfTFoXvZ:b-inwiso) ([raw file](https://github.com/google/nomulus/blob/4ab472d6aa152c49562ad60e6b03ac75ea3ad0f2/console-webapp/src/app/registrar/registrar.guard.ts#L35)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Oh, I see. I think it requires a comment that empty nextUrl takes user to a router default page, which in our case is a home page.
Also it can be shortened I believe - `const nextUrl = location.hash.split('#/')[1] || ""`
</blockquote></details>

huh I did not know that you could use `||` like that, interesting 


<!-- Sent from Reviewable.io -->

2023-09-15 15:22 UTC, ptkach approved these changes
Yeah and no IndexOutOfBounds :)

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2149#-:-NeOQohO0Y_pkKdtW7_-:b-p86pwn)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2023-09-15 16:28 UTC, merged