Switch to a stronger algorithm for password hashing
google/nomulus pull request #2191
Opened 2023-10-24 13:33 UTC by jianglai

We have been using SHA256 to hash passwords (for both EPP and registry lock),
which is now considered too weak.

This PR switches to using Scrypt, a memory-hard slow hash function, with
recommended parameters per go/crypto-password-hash.

To ease the transition, when a password is being verified, both Scrypt
and SHA256 are tried. If SHA256 verification is successful, we re-hash
the verified password with Scrypt and replace the stored SHA256 hash
with the new one. This way, as long as a user uses the password once
before the transition period ends (when Scrypt becomes the only valid
algorithm), there would be no need for manual intervention from them.

We will send out notifications to users to remind them of the transition
and urge them to use the password (which should not be a problem with
EPP, but less so with the registry lock). After the transition,
out-of-band reset for EPP password, or remove-and-add on the console for
registry lock password, would be required for the hashes that have not
been re-saved.

Note that the re-save logic is not present for console user's registry
lock password, as there is no production data for console users yet.
Only legacy GAE user's password requires re-save.

2023-10-24 13:47 UTC, jianglai reviewed
> Reviewed 7 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-10-24 13:54 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 3 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java` line 130 at r2](https://reviewable.io/reviews/google/nomulus/2191#-NhWx-os6Z7jObZY7tyP:-NhWx-os6Z7jObZY7tyQ:bya7a9v) ([raw file](https://github.com/google/nomulus/blob/31f77bb80f27e95bc6e9f10d569a21ee978a3814/core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java#L130)):*
> ```Java
>               .orElseThrow(() -> new ForbiddenException("User is not logged in"));
> 
>       String userEmail = verifyPasswordAndGetEmail(userAuthInfo, postInput);
> ```

Just move this line inside the `transact()` block.
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java` line 227 at r2](https://reviewable.io/reviews/google/nomulus/2191#-NhWx2c66SdCHNi3Ep8K:-NhWx2c66SdCHNi3Ep8L:b-4i9tb5) ([raw file](https://github.com/google/nomulus/blob/31f77bb80f27e95bc6e9f10d569a21ee978a3814/core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java#L227)):*
> ```Java
>     if (registrarPoc.getCurrentHashAlgorithm(postInput.password) != HashAlgorithm.SCRYPT) {
>       logger.atInfo().log("Rehashing existing registry lock password with Scrypt.");
>       tm().transact(
> ```

You won't need this inner transaction if you make my recommended change above.

In general we shouldn't be adding transactions anymore in existing code, merely taking the existing transactions and making them broader.
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 44 at r2](https://reviewable.io/reviews/google/nomulus/2191#-NhWxDzl0oR3hD4zaKjf:-NhWxDzl0oR3hD4zaKjg:b4bxkec) ([raw file](https://github.com/google/nomulus/blob/31f77bb80f27e95bc6e9f10d569a21ee978a3814/util/src/main/java/google/registry/util/PasswordUtils.java#L44)):*
> ```Java
>     } catch (NoSuchAlgorithmException e) {
>       // All implementations of MessageDigest are required to support SHA-256.
>       throw new RuntimeException(
> ```

I'm worried that throwing an exception like this in the static initializer might have broad consequences, potentially causing instances to fail to spin up at all, and thus be unable to process anything, even stuff unrelated to password utils?

It would be better to memoize the creation of this -- initialize it at first use (and throw an exception then on failure).


<!-- Sent from Reviewable.io -->

2023-10-24 15:37 UTC, jianglai reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java` line 130 at r2](https://reviewable.io/reviews/google/nomulus/2191#-NhWx-os6Z7jObZY7tyP:-NhXISd99peEbNO1_3gz:b-eillbs) ([raw file](https://github.com/google/nomulus/blob/31f77bb80f27e95bc6e9f10d569a21ee978a3814/core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java#L130)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Just move this line inside the `transact()` block.
</blockquote></details>

I tried it first, but this method throws a checked exception, which needs to be handled. It doesn't seem worth the hassle because:

1) Re-save a temporary measure.
2) This action is not on a critical path and is not likely to be used a lot.
3) We need to solve the issue of the `transact()` method(s) doesn't take a lambda that throws check exceptions more broadly anyway, if we want to achieve the goal of eliminating most of nested transactions, realistically, without having to add a massive amount of rethrows. As I suggested in #2133, I think the solution is to change the signatures of the `transact()` method(s) for them to allow lambdas with checked exceptions, and handle that checked exception within `transact()` itself. That PR seems to have stalled, so I am working on a PR that refactors `reTransact` and makes the necessary changes to the function signatures to allow for checked exceptions.
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java` line 227 at r2](https://reviewable.io/reviews/google/nomulus/2191#-NhWx2c66SdCHNi3Ep8K:-NhXJuG2AdSu9aPrvOnL:b4c3l3q) ([raw file](https://github.com/google/nomulus/blob/31f77bb80f27e95bc6e9f10d569a21ee978a3814/core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java#L227)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You won't need this inner transaction if you make my recommended change above.

In general we shouldn't be adding transactions anymore in existing code, merely taking the existing transactions and making them broader.
</blockquote></details>

See above.

Also, this PR is still WIP. I need to add more unit tests and test re-save feature on alpha.
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 44 at r2](https://reviewable.io/reviews/google/nomulus/2191#-NhWxDzl0oR3hD4zaKjf:-NhXGd2w3I2OQRhkn6Ng:b-slxl9y) ([raw file](https://github.com/google/nomulus/blob/31f77bb80f27e95bc6e9f10d569a21ee978a3814/util/src/main/java/google/registry/util/PasswordUtils.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I'm worried that throwing an exception like this in the static initializer might have broad consequences, potentially causing instances to fail to spin up at all, and thus be unable to process anything, even stuff unrelated to password utils?

It would be better to memoize the creation of this -- initialize it at first use (and throw an exception then on failure).
</blockquote></details>

In theory you are right. In practice we know that it's been working for years.

Changed to supplier with memoization.


<!-- Sent from Reviewable.io -->

2023-10-25 15:43 UTC, jianglai reviewed
Tested on crash. Ready for review now.

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191#-:-NhbVKJg3AoCy-zPlHcN:bilt6ve)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @ptkach)



<!-- Sent from Reviewable.io -->

2023-11-01 14:04 UTC, jianglai commented
Gentle ping.

2023-11-01 17:44 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman, @jianglai, and @ptkach)

___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 52 at r4](https://reviewable.io/reviews/google/nomulus/2191#-NiAyyI65QxLEgRYsSGZ:-NiAyyI65QxLEgRYsSG_:bvzesf) ([raw file](https://github.com/google/nomulus/blob/ff11f0af9a0fea1a2068fc6cc433f396ffdbeda2/util/src/main/java/google/registry/util/PasswordUtils.java#L52)):*
> ```Java
>   private PasswordUtils() {}
> 
>   public enum HashAlgorithm {
> ```

Needs a Javadoc.
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 84 at r4](https://reviewable.io/reviews/google/nomulus/2191#-NiAywcK49ZM8BfrifBP:-NiAywcK49ZM8BfrifBQ:bvzesf) ([raw file](https://github.com/google/nomulus/blob/ff11f0af9a0fea1a2068fc6cc433f396ffdbeda2/util/src/main/java/google/registry/util/PasswordUtils.java#L84)):*
> ```Java
> 
>   public static String hashPassword(String password, byte[] salt, HashAlgorithm algorithm) {
>     return base64().encode(algorithm.hash(password.getBytes(US_ASCII), salt));
> ```

Needs a Javadoc.
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 88 at r4](https://reviewable.io/reviews/google/nomulus/2191#-NiAyvCgDM6IAFhi-x23:-NiAyvCgDM6IAFhi-x24:bvzesf) ([raw file](https://github.com/google/nomulus/blob/ff11f0af9a0fea1a2068fc6cc433f396ffdbeda2/util/src/main/java/google/registry/util/PasswordUtils.java#L88)):*
> ```Java
> 
>   @Nullable
>   public static HashAlgorithm verifyPassword(String password, String hash, String salt) {
> ```

Needs a Javadoc.


<!-- Sent from Reviewable.io -->

2023-11-01 17:44 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, @jianglai, and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java` line 130 at r2](https://reviewable.io/reviews/google/nomulus/2191#-NhWx-os6Z7jObZY7tyP:-NiAz3p53E9GXna2RnjX:b-sdr66f) ([raw file](https://github.com/google/nomulus/blob/31f77bb80f27e95bc6e9f10d569a21ee978a3814/core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java#L130)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I tried it first, but this method throws a checked exception, which needs to be handled. It doesn't seem worth the hassle because:

1) Re-save a temporary measure.
2) This action is not on a critical path and is not likely to be used a lot.
3) We need to solve the issue of the `transact()` method(s) doesn't take a lambda that throws check exceptions more broadly anyway, if we want to achieve the goal of eliminating most of nested transactions, realistically, without having to add a massive amount of rethrows. As I suggested in #2133, I think the solution is to change the signatures of the `transact()` method(s) for them to allow lambdas with checked exceptions, and handle that checked exception within `transact()` itself. That PR seems to have stalled, so I am working on a PR that refactors `reTransact` and makes the necessary changes to the function signatures to allow for checked exceptions.
</blockquote></details>

So this should wait until after #2195 then?


<!-- Sent from Reviewable.io -->

2023-11-02 14:43 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java` line 130 at r2](https://reviewable.io/reviews/google/nomulus/2191#-NhWx-os6Z7jObZY7tyP:-NiFOQwSAuHwzU1VbzdP:bgie7mg) ([raw file](https://github.com/google/nomulus/blob/31f77bb80f27e95bc6e9f10d569a21ee978a3814/core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java#L130)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

So this should wait until after #2195 then?
</blockquote></details>

Ideally, yes. But I think registry lock action is not used frequently enough for us to worry about the performance hit with one more transaction. More importantly, it is better for us to get this change deployed so we can start converting SHA256 to Scrypt hashes and communicating with registrars regarding a conversion deadline. Even after #2195 is merged there will likely be non-trivial amount of work to fully unravel the nested transactions. I'd prefer to work on that separately and not have this change wait on that. 
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 52 at r4](https://reviewable.io/reviews/google/nomulus/2191#-NiAyyI65QxLEgRYsSGZ:-NiFQFzo-tXQZS3-osXJ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ff11f0af9a0fea1a2068fc6cc433f396ffdbeda2/util/src/main/java/google/registry/util/PasswordUtils.java#L52)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs a Javadoc.
</blockquote></details>

Done.
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 84 at r4](https://reviewable.io/reviews/google/nomulus/2191#-NiAywcK49ZM8BfrifBP:-NiFQGHaDUEKuDnO3ZAJ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ff11f0af9a0fea1a2068fc6cc433f396ffdbeda2/util/src/main/java/google/registry/util/PasswordUtils.java#L84)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs a Javadoc.
</blockquote></details>

Done.
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 88 at r4](https://reviewable.io/reviews/google/nomulus/2191#-NiAyvCgDM6IAFhi-x23:-NiFRHXaEOjHC8xvBVQP:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ff11f0af9a0fea1a2068fc6cc433f396ffdbeda2/util/src/main/java/google/registry/util/PasswordUtils.java#L88)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs a Javadoc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-02 15:17 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman, @jianglai, and @ptkach)

___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 102 at r5](https://reviewable.io/reviews/google/nomulus/2191#-NiFb74gD9wNpTYi3OpC:-NiFb74gD9wNpTYi3OpD:b70zea0) ([raw file](https://github.com/google/nomulus/blob/f57a3b13cd0e4bb0dd8c24a77f7a01dbadb2f9f0/util/src/main/java/google/registry/util/PasswordUtils.java#L102)):*
> ```Java
> 
>   /**
>    * Verifies a password by regerating the hash with the provided salt and comparing it to the
> ```

`regerating`?


<!-- Sent from Reviewable.io -->

2023-11-02 15:22 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman, @jianglai, and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java` line 232 at r5](https://reviewable.io/reviews/google/nomulus/2191#-NiFbq9n3FRGDmBGN6tg:-NiFbq9n3FRGDmBGN6th:b-rqndbb) ([raw file](https://github.com/google/nomulus/blob/f57a3b13cd0e4bb0dd8c24a77f7a01dbadb2f9f0/core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java#L232)):*
> ```Java
>                         tm().loadByEntity(registrarPoc)
>                             .asBuilder()
>                             .setAllowedToSetRegistryLockPassword(true)
> ```

What is this coming from?
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 102 at r5](https://reviewable.io/reviews/google/nomulus/2191#-NiFb74gD9wNpTYi3OpC:-NiFcDj628Li2A9m3q8v:bqk4wpr) ([raw file](https://github.com/google/nomulus/blob/f57a3b13cd0e4bb0dd8c24a77f7a01dbadb2f9f0/util/src/main/java/google/registry/util/PasswordUtils.java#L102)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`regerating`?
</blockquote></details>

Also the description needs to make it clear that it returns the algorithm if the hash is valid, otherwise returns null (or empty as suggested below).
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 111 at r5](https://reviewable.io/reviews/google/nomulus/2191#-NiFc3jQ48NkFWYD-WUQ:-NiFc3jQ48NkFWYD-WUR:bomz80z) ([raw file](https://github.com/google/nomulus/blob/f57a3b13cd0e4bb0dd8c24a77f7a01dbadb2f9f0/util/src/main/java/google/registry/util/PasswordUtils.java#L111)):*
> ```Java
>    *     works.
>    */
>   public static HashAlgorithm verifyPassword(String password, String hash, String salt) {
> ```

`Optional<HashAlgorithm>` as the return type will make this easier to understand.


<!-- Sent from Reviewable.io -->

2023-11-02 17:34 UTC, jianglai reviewed
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java` line 130 at r2](https://reviewable.io/reviews/google/nomulus/2191#-NhWx-os6Z7jObZY7tyP:-NiG15DP-RZJJ4wxQ6Ly:b-896fix) ([raw file](https://github.com/google/nomulus/blob/31f77bb80f27e95bc6e9f10d569a21ee978a3814/core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java#L130)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Leave a TODO then at least?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java` line 232 at r5](https://reviewable.io/reviews/google/nomulus/2191#-NiFbq9n3FRGDmBGN6tg:-NiG19bf25MM8AEhtihg:bczd0ft) ([raw file](https://github.com/google/nomulus/blob/f57a3b13cd0e4bb0dd8c24a77f7a01dbadb2f9f0/core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java#L232)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What is this coming from?
</blockquote></details>

LoL. I'm glad you asked. For some reason we made it so that one can only set the password once. This boolean will need to be true (setting it to be true also [nulls out any existing password](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/registrar/RegistrarPoc.java;l=433?q=registrarpoc&ss=nomulus%2Fnomulus)) for one to set the password. Once the password is set, the boolean is [reverted back to false](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/registrar/RegistrarPoc.java;l=433?q=registrarpoc&ss=nomulus%2Fnomulus), preventing any further change to the password by the registrar contact, unless they contact the admins to reset the password.

I honestly don't know why it was configured this way (basically preventing self-service password change or reset). Gus doesn't seem to know the full reason behind it either.
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 102 at r5](https://reviewable.io/reviews/google/nomulus/2191#-NiFb74gD9wNpTYi3OpC:-NiG2oBY0t638l98KhHK:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f57a3b13cd0e4bb0dd8c24a77f7a01dbadb2f9f0/util/src/main/java/google/registry/util/PasswordUtils.java#L102)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Also the description needs to make it clear that it returns the algorithm if the hash is valid, otherwise returns null (or empty as suggested below).
</blockquote></details>

Done.
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 111 at r5](https://reviewable.io/reviews/google/nomulus/2191#-NiFc3jQ48NkFWYD-WUQ:-NiG2n3qCF5t-NoIwZMK:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f57a3b13cd0e4bb0dd8c24a77f7a01dbadb2f9f0/util/src/main/java/google/registry/util/PasswordUtils.java#L111)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`Optional<HashAlgorithm>` as the return type will make this easier to understand.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-02 19:57 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @ptkach)



<!-- Sent from Reviewable.io -->

2023-11-02 20:16 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @ptkach)



<!-- Sent from Reviewable.io -->

2023-11-03 15:54 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman, @jianglai, and @ptkach)

___
*[`core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java` line 165 at r8](https://reviewable.io/reviews/google/nomulus/2191#-NiKt3Hb2IVe-_tI7X0a:-NiKt3Hb2IVe-_tI7X0b:b-jw13iw) ([raw file](https://github.com/google/nomulus/blob/bd171abfaf3b224a879f09e1a936c3e638fdcec4/core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java#L165)):*
> ```Java
>     assertThat(registrarPoc.getCurrentHashAlgorithm("hi").get()).isEqualTo(SHA256);
>     Map<String, ?> response = action.handleJsonRequest(lockRequest());
>     registrarPoc =
> ```

Don't reuse the existing variable here. This should be `RegistrarPoc updatedRegistrarPoc`


<!-- Sent from Reviewable.io -->

2023-11-03 19:23 UTC, jianglai reviewed
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @ptkach)

___
*[`core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java` line 165 at r8](https://reviewable.io/reviews/google/nomulus/2191#-NiKt3Hb2IVe-_tI7X0a:-NiLbqoH6UPS9Kl_S1ax:b85lwkw) ([raw file](https://github.com/google/nomulus/blob/bd171abfaf3b224a879f09e1a936c3e638fdcec4/core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java#L165)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Don't reuse the existing variable here. This should be `RegistrarPoc updatedRegistrarPoc`
</blockquote></details>

Done. Personally I don't see why this is necessary. It's in test and we are reloading the registrar POC after the action. 
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 84 at r4](https://reviewable.io/reviews/google/nomulus/2191#-NiAywcK49ZM8BfrifBP:-NiLc7lB7FVcYIR-jzGP:b-h83gap) ([raw file](https://github.com/google/nomulus/blob/ff11f0af9a0fea1a2068fc6cc433f396ffdbeda2/util/src/main/java/google/registry/util/PasswordUtils.java#L84)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is it?
</blockquote></details>

Sorry, forgot to push the latest commit.
___
*[`util/src/main/java/google/registry/util/PasswordUtils.java` line 102 at r5](https://reviewable.io/reviews/google/nomulus/2191#-NiFb74gD9wNpTYi3OpC:-NiLcEq28Y8Frq3hzroc:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f57a3b13cd0e4bb0dd8c24a77f7a01dbadb2f9f0/util/src/main/java/google/registry/util/PasswordUtils.java#L102)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It still says `regerating`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-03 19:34 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman and @ptkach)

___
*[`core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java` line 165 at r8](https://reviewable.io/reviews/google/nomulus/2191#-NiKt3Hb2IVe-_tI7X0a:-NiLfRJL05ipIhdl4ljq:b-xa1928) ([raw file](https://github.com/google/nomulus/blob/bd171abfaf3b224a879f09e1a936c3e638fdcec4/core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java#L165)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Done. Personally I don't see why this is necessary. It's in test and we are reloading the registrar POC after the action.
</blockquote></details>

Even tests are read by people though, and reusing variables makes the code harder to understand.


<!-- Sent from Reviewable.io -->

2023-11-03 19:35 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2191#-:-NiLfcfO0KacRl4QlzmM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman and @ptkach)



<!-- Sent from Reviewable.io -->

2023-11-03 21:29 UTC, merged