Upgrade to Java 17 runtime
google/nomulus pull request #2201
Opened 2023-10-30 19:31 UTC by jianglai

2023-10-31 15:29 UTC, jianglai reviewed
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2201)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-11-01 15:01 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2201)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/env/alpha/backend/WEB-INF/appengine-web.xml` line 6 at r2](https://reviewable.io/reviews/google/nomulus/2201#-NiAOmn6C9TLMpnxdY0G:-NiAOmn6C9TLMpnxdY0H:b-w329zh) ([raw file](https://github.com/google/nomulus/blob/5eb0ea519edac0e96506c436127e186a35c98910/core/src/main/java/google/registry/env/alpha/backend/WEB-INF/appengine-web.xml#L6)):*
> ```XML
>   <runtime>java17</runtime>
>   <service>backend</service>
>   <app-engine-apis>true</app-engine-apis>
> ```

Is this part even necessary? I thought we had migrated away from all of these by now?


<!-- Sent from Reviewable.io -->

2023-11-02 13:46 UTC, jianglai reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2201)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/env/alpha/backend/WEB-INF/appengine-web.xml` line 6 at r2](https://reviewable.io/reviews/google/nomulus/2201#-NiAOmn6C9TLMpnxdY0G:-NiFH8Bl3NS8YJChiLYl:beoolrn) ([raw file](https://github.com/google/nomulus/blob/5eb0ea519edac0e96506c436127e186a35c98910/core/src/main/java/google/registry/env/alpha/backend/WEB-INF/appengine-web.xml#L6)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is this part even necessary? I thought we had migrated away from all of these by now?
</blockquote></details>

The legacy console still use the GAE User service API. I'm in the process of removing it, but it will take the time as it requires turning on IAP and also setting up console users for registrars.


<!-- Sent from Reviewable.io -->

2023-11-02 14:08 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2201#-:-NiFM9QR7DibTlaJscgE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-11-02 14:08 UTC, merged