Download scheduler for BSA
google/nomulus pull request #2209
Opened 2023-11-03 20:43 UTC by weiminyu

2023-11-16 21:32 UTC, jianglai requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2209)* status: all files reviewed, 7 unresolved discussions (waiting on @sarahcaseybot and @weiminyu)

___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java` line 33 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjNeCsTBe5viDCKcw71:-NjNeCsTBe5viDCKcw72:b-l6tie8) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java#L33)):*
> ```Java
>   public abstract DownloadStage stage();
> 
>   /** The most recently job that ended in the {@code DONE} stage. */
> ```

recent
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java` line 48 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjOYlaH6Y2eGmCRrRjn:-NjOYlaH6Y2eGmCRrRjo:brbxjnm) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java#L48)):*
> ```Java
>         currentJob.getStage(),
>         Optional.empty(),
>         /* forceDownload= */ true);
> ```

Doesn't this boolean only matter when there's a previously completed job to compare the checksum with? If there isn't one, the current one will always be downloaded, so there shouldn't be a need to "force download". The value provided here should not impact how the code behaves, but setting it to false seems to make more logical sense.
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java` line 63 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjNfE7eETg0iHR1tNWi:-NjNfE7eETg0iHR1tNWj:bebtpf4) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java#L63)):*
> ```Java
> 
>   @Inject
>   DownloadScheduler(Duration downloadInterval, Duration maxNopInterval, Clock clock) {
> ```

How are the intervals injected without qualifiers?
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjNj22P067m5b4A810p:-NjNj22P067m5b4A810q:b-pqm2mo) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java#L69)):*
> ```Java
>   }
> 
>   public Optional<DownloadSchedule> schedule() {
> ```

Needs a javadoc. From the code it is clear that this method doesn't always "schedule" a download.
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java` line 102 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjNwMGL5Lq7Hv2xDev6:-NjNwMGL5Lq7Hv2xDev7:b-5evqi) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java#L102)):*
> ```Java
>   }
> 
>   private Optional<DownloadSchedule> scheduleNewJob(Optional<BsaDownload> prevJob) {
> ```

Even though this is a private method, I think it still warrants a javadoc to explain what the return value is.
___
*[`core/src/test/java/google/registry/bsa/persistence/DownloadSchedulerTest.java` line 97 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjP0lqyEoV-pXtLp9sD:-NjP0lqyEoV-pXtLp9sE:b2qdx1c) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/test/java/google/registry/bsa/persistence/DownloadSchedulerTest.java#L97)):*
> ```Java
>     assertThat(scheduleOptional).isPresent();
>     DownloadSchedule schedule = scheduleOptional.get();
>     assertThat(schedule.jobId()).isEqualTo(inProgressJob.jobId);
> ```

For all these comparisons with an existing `DownloadSchedule`, can't we just do `assertThat().isEqualTo()`, instead of comparing fields individually?
___
*[`core/src/test/java/google/registry/bsa/persistence/DownloadSchedulerTest.java` line 188 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjP1vw39y_NwfHe91np:-NjP1vw39y_NwfHe91nq:b-blicxp) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/test/java/google/registry/bsa/persistence/DownloadSchedulerTest.java#L188)):*
> ```Java
>     BsaDownload job = new BsaDownload();
>     job.setStage(DownloadStage.DONE);
>     tm().transact(() -> tm().insert(job));
> ```

What's wrong with using `insertOneJobAndAdvanceClock()` here?


<!-- Sent from Reviewable.io -->

2023-11-16 22:48 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2209)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/bsa/DownloadStage.java` line 18 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjP0U_55q3yD9VbTrJv:-NjPJRR1EiZMImVzHIhK:bb6un1j) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/DownloadStage.java#L18)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

It would be helpful to also include a javadoc including the meaning of the various stages (similar to what's at the top of DownloadScheduler) here as well.
</blockquote></details>

Done
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java` line 33 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjNeCsTBe5viDCKcw71:-NjPJTRj7mECdgKYmyVS:b-896fix) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java#L33)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

recent
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java` line 48 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjOYlaH6Y2eGmCRrRjn:-NjPA6rt4ueH9Z7ahd_w:b3yv2fx) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java#L48)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Doesn't this boolean only matter when there's a previously completed job to compare the checksum with? If there isn't one, the current one will always be downloaded, so there shouldn't be a need to "force download". The value provided here should not impact how the code behaves, but setting it to false seems to make more logical sense.
</blockquote></details>

Setting to `true` is safer when the goal is to not miss downloads.

Renamed to `alwaysDownload` to avoid the `force` part.
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java` line 56 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjP1PDjEfBMiKt-Icjb:-NjPIXOO5U2hIqRNxVoS:btdrh35) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java#L56)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Should we make this configurable? Are we sure this is the best interval/jitter?
</blockquote></details>

This addresses NTP clock drifts between machines. This should be more than enough.
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java` line 63 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjNfE7eETg0iHR1tNWi:-NjPIlZBA3iSc4gsh6Nn:b-2tjajh) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java#L63)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

How are the intervals injected without qualifiers?
</blockquote></details>

This class is not hooked up to the server yet. Will do that in a future PR.
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjNj22P067m5b4A810p:-NjPIqp32cOJJmTBA_MP:b-896fix) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java#L69)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Needs a javadoc. From the code it is clear that this method doesn't always "schedule" a download.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java` line 102 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjNwMGL5Lq7Hv2xDev6:-NjPIrwS8W5H3h7JFwTn:b-896fix) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java#L102)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Even though this is a private method, I think it still warrants a javadoc to explain what the return value is.
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/bsa/persistence/DownloadSchedulerTest.java` line 97 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjP0lqyEoV-pXtLp9sD:-NjPIwXyCP_fSb95UCMg:bbtjp6u) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/test/java/google/registry/bsa/persistence/DownloadSchedulerTest.java#L97)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

For all these comparisons with an existing `DownloadSchedule`, can't we just do `assertThat().isEqualTo()`, instead of comparing fields individually?
</blockquote></details>

DownloadSchedule's constructor is not obvious. An `expected = DownloadSchedule.of(currentJob)` statement does not tell the reader all the important values in the object.
___
*[`core/src/test/java/google/registry/bsa/persistence/DownloadSchedulerTest.java` line 188 at r1](https://reviewable.io/reviews/google/nomulus/2209#-NjP1vw39y_NwfHe91np:-NjPJOshCDed2xsAjDJq:b-896fix) ([raw file](https://github.com/google/nomulus/blob/94f8175142f6321171ad83108c7840e0947124e0/core/src/test/java/google/registry/bsa/persistence/DownloadSchedulerTest.java#L188)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

What's wrong with using `insertOneJobAndAdvanceClock()` here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-17 21:10 UTC, jianglai approved these changes
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2209)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java` line 71 at r2](https://reviewable.io/reviews/google/nomulus/2209#-NjU5mTS4Hdu44qiSM_i:-NjU5mTS4Hdu44qiSM_j:bwbgo8s) ([raw file](https://github.com/google/nomulus/blob/710efb3880f5d6b6ba6ac1fffc552630e81890bc/core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java#L71)):*
> ```Java
> 
>   /**
>    * Returns a {@link DownloadSchedule} instance that describes the work to be performed by an
> ```

Wouldn't it return a work in progress in some cases? In that case the work is not to be performed again, right? I think a more accurate description is "new work to be performed or current work in progress"


<!-- Sent from Reviewable.io -->

2023-11-17 21:14 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2209)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java` line 71 at r2](https://reviewable.io/reviews/google/nomulus/2209#-NjU5mTS4Hdu44qiSM_i:-NjU7fpqDvPlSA6OFBER:bhw4e8e) ([raw file](https://github.com/google/nomulus/blob/710efb3880f5d6b6ba6ac1fffc552630e81890bc/core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java#L71)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Wouldn't it return a work in progress in some cases? In that case the work is not to be performed again, right? I think a more accurate description is "new work to be performed or current work in progress"
</blockquote></details>

Will do in next PR.


<!-- Sent from Reviewable.io -->

2023-11-17 21:15 UTC, merged