Add handler for Console API requests and XSRF token creation and verification
google/nomulus pull request #2211
Opened 2023-11-06 19:14 UTC by ptkach

While working on XSRF protection I realized that we're lacking a better way to handle API request to new console. For instance I never really liked that we used `JsonGetAction` to handle **POST** and GET requests, as well as the fact that we needed to verify `consoleUser` every time and check if the request is GET or POST, etc. On top of that there's no good place where to actually do the XSRF verification. All that prompted me to create a base class that we can use for Console Api requests - `ConsoleApiAction`. For now I've migrated `ConsoleUserDataAction` to work with the new `ConsoleApiAction` and if you're ok with this approach I will continue updating existing endpoints.

2023-11-06 22:37 UTC, gbrodman requested changes
> Reviewed 3 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2211)* status: 3 of 9 files reviewed, 11 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/request/ResponseImpl.java` line 65 at r1](https://reviewable.io/reviews/google/nomulus/2211#gh-1383856575:-Nia_6vd59ceDQgFNtxt:b-5znq7q) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/request/ResponseImpl.java#L65)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Failure to use secure cookies

Cookie is added to response without the 'secure' flag being set.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1597)
</blockquote></details>

this seems like the wrong place for this note, because one sets the "secure" status on the cookie itself, not here.....
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 1 at r1](https://reviewable.io/reviews/google/nomulus/2211#-NiakR1JElPCSjj3PO6b:-NiakR1JElPCSjj3PO6c:b-wqhi78) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L1)):*
> ```Java
> package google.registry.ui.server.console;
> ```

license
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 13 at r1](https://reviewable.io/reviews/google/nomulus/2211#-NiakQ7VDC2PD3rRrNpQ:-NiakQ7W8Br8lHDNzztc:bpnc71r) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L13)):*
> ```Java
> import javax.servlet.http.Cookie;
> 
> public class ConsoleApiAction implements Runnable {
> ```

needs a javadoc
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 22 at r1](https://reviewable.io/reviews/google/nomulus/2211#-NiaaoPp0eOe2KJKO9Ag:-NiaaoPp0eOe2KJKO9Ah:bke3s6m) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L22)):*
> ```Java
>   public final void run() {
>     if (!consoleApiParams.getAuthResult().userAuthInfo().get().consoleUser().isPresent()) {
>       consoleApiParams.getRsp().setStatus(HttpStatusCodes.STATUS_CODE_UNAUTHORIZED);
> ```

maybe note that this shouldn't ever be possible because of the Auth annotations on the various implementing classes 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 34 at r1](https://reviewable.io/reviews/google/nomulus/2211#-Niad59h3yDg3JdgiGa8:-Niad59i9IDM_s1dfYL3:b69pwey) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L34)):*
> ```Java
>     }
>   }
>   ;
> ```

extra ; 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 37 at r1](https://reviewable.io/reviews/google/nomulus/2211#-Niab0YREhRw-gJtSG03:-Niab0YREhRw-gJtSG04:bielhxq) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L37)):*
> ```Java
> 
>   protected void postHandler(User user) {
>     throw new RuntimeException("Console API POST handler not implemented");
> ```

UnsupportedOperationException (same below) 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 39 at r1](https://reviewable.io/reviews/google/nomulus/2211#-NiakkEME2pKHcfJaA0g:-NiakkEME2pKHcfJaA0h:bhaz4bz) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L39)):*
> ```Java
>   public static final String PATH = "/console-api/userdata";
> 
>   private final ConsoleApiParams consoleApiParams;
> ```

just make the superclass's variable protected
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 61 at r1](https://reviewable.io/reviews/google/nomulus/2211#-Nialz7CCcNxku0WM1Ch:-Nialz7D-04-gDDpj5u4:by5zdge) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L61)):*
> ```Java
> 
>   @Override
>   protected void getHandler(User user) {
> ```

Shouldn't we do this on all GET requests? Like, why not just do this in the base class for every GET request before we actually run the code? 
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2211#-Nia_aqHCpTTOIuXtWTj:-Nia_aqIDqQBUABl9d1-:bsegenm) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L43)):*
> ```Java
>   static final String PARAM_CLIENT_ID = "clientId";
> 
>   public static class ConsoleApiParams {
> ```

let's just move this to a new file and use an AutoValue, it doesn't need to be in here   
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 46 at r1](https://reviewable.io/reviews/google/nomulus/2211#-Nial_dY3nc3uFRs6Aw-:-Nial_dY3nc3uFRs6Aw0:bbbtboa) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L46)):*
> ```Java
>     private final XsrfTokenManager xsrfTokenManager;
>     private final HttpServletRequest req;
>     private final Response rsp;
> ```

No point in saving a few characters, just use `response` everywhere

Same for `request`


<!-- Sent from Reviewable.io -->

2023-11-08 22:16 UTC, gbrodman requested changes
> Reviewed 2 of 9 files at r1, 5 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2211)* status: all files reviewed, 5 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 28 at r3](https://reviewable.io/reviews/google/nomulus/2211#-Nil-2Yp-1Jn0eD8zWd6:-Nil-2Yp-1Jn0eD8zWd7:bma2451) ([raw file](https://github.com/google/nomulus/blob/c42b59a6acadcabfda0ceceaff75a3906a7ee50e/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L28)):*
> ```Java
> 
> /** Base class for handling Console API requests */
> public class ConsoleApiAction implements Runnable {
> ```

I don't think we'd ever want to instantiate this directly, right? If not we can make it an abstract class
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 61 at r1](https://reviewable.io/reviews/google/nomulus/2211#-Nialz7CCcNxku0WM1Ch:-NikyrkHEhHioH67ETR7:b-p08ijy) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L61)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Not sure why would we do that on all GET requests. See Angular XSRF doc - https://angular.io/guide/http-security-xsrf-protection.
>> To take advantage of this, your server needs to set a token in a JavaScript readable session cookie called `XSRF-TOKEN` on either the page load or the first GET request.
</blockquote></details>

Yeah I could have phrased it better, I think, my bad. 

We always want to just set the cookie (only) on the first GET request right? I'm a bit concerned that we're only doing this in the UserDataAction. What if we did "add an XSRF cookie if and only if it doesn't already exist" on every single GET request, guaranteeing that we always set it on the first GET request no matter where it is? w
___
*[`core/src/test/java/google/registry/ui/server/ActionMembershipTest.java` line 38 at r3](https://reviewable.io/reviews/google/nomulus/2211#-Nikzouf7dxiyXE61k-M:-Nikzouf7dxiyXE61k-N:b9drs36) ([raw file](https://github.com/google/nomulus/blob/c42b59a6acadcabfda0ceceaff75a3906a7ee50e/core/src/test/java/google/registry/ui/server/ActionMembershipTest.java#L38)):*
> ```Java
>     // 2. Extending JsonAction to show that we are serving JSON POST requests
>     // 3. Extending JsonGetAction to serve JSON GET requests
>     // 3. Extending ConsoleApiAction to serve JSON requests
> ```

sorry major nit, should be 4 (and maybe specifying for the new console but eh fine either way) 


<!-- Sent from Reviewable.io -->

2023-11-09 21:00 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2211)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/request/ResponseImpl.java` line 65 at r1](https://reviewable.io/reviews/google/nomulus/2211#gh-1383856575:-NipsITFDzuaUju-mqWk:b-sko33n) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/request/ResponseImpl.java#L65)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this seems like the wrong place for this note, because one sets the "secure" status on the cookie itself, not here.....
</blockquote></details>

Done, secured at the cookie creation
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 28 at r3](https://reviewable.io/reviews/google/nomulus/2211#-Nil-2Yp-1Jn0eD8zWd6:-NipsO9j-VWkP48FQioa:b-wo63cu) ([raw file](https://github.com/google/nomulus/blob/c42b59a6acadcabfda0ceceaff75a3906a7ee50e/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L28)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think we'd ever want to instantiate this directly, right? If not we can make it an abstract class
</blockquote></details>

Good suggestion
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 61 at r1](https://reviewable.io/reviews/google/nomulus/2211#-Nialz7CCcNxku0WM1Ch:-NipsQ9d3fKeEqTZD2Q1:b-f74oqb) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L61)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah I could have phrased it better, I think, my bad. 

We always want to just set the cookie (only) on the first GET request right? I'm a bit concerned that we're only doing this in the UserDataAction. What if we did "add an XSRF cookie if and only if it doesn't already exist" on every single GET request, guaranteeing that we always set it on the first GET request no matter where it is? w
</blockquote></details>

Nah, then we'd need to start carrying about cookie expiration time to make sure that the cookie that we see is not old or expired and that is a completely new level of complexity we don't want. 
___
*[`core/src/test/java/google/registry/ui/server/ActionMembershipTest.java` line 38 at r3](https://reviewable.io/reviews/google/nomulus/2211#-Nikzouf7dxiyXE61k-M:-NipsoeM2IWYlZ5uxxCr:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c42b59a6acadcabfda0ceceaff75a3906a7ee50e/core/src/test/java/google/registry/ui/server/ActionMembershipTest.java#L38)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

sorry major nit, should be 4 (and maybe specifying for the new console but eh fine either way)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-09 21:25 UTC, gbrodman approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2211)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 61 at r1](https://reviewable.io/reviews/google/nomulus/2211#-Nialz7CCcNxku0WM1Ch:-NipyQO06eBOtocsC0Ri:bfq903) ([raw file](https://github.com/google/nomulus/blob/458446b0c6f40711deb9b09cc5ad227be145028e/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L61)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Nah, then we'd need to start carrying about cookie expiration time to make sure that the cookie that we see is not old or expired and that is a completely new level of complexity we don't want.
</blockquote></details>

sounds good! 


<!-- Sent from Reviewable.io -->

2023-11-09 22:51 UTC, merged