Add a dedicated IP header to accommodate Java 17 on GAE
google/nomulus pull request #2224
Opened 2023-11-16 16:33 UTC by jianglai

For reasons unclear at this point, Java 17's servlet implementation on
GAE injects IP addresses (including unroutable private IPs) into the
standard X-Forwarded-For header, which we currently use to embed
registrar IP addresses to check against the allow list. This results in
the server not properly parsing the header and rejecting legitimate
connections.

This PR sets a custom header that should not be interfered with by any
JVM implementation to store the IP address, while maintaining the old
header as a fallback. The proxy will set both headers to allow the
server to gracefully migrate from Java 8 and Java 17 (and potentially
rollback).

2023-11-16 16:39 UTC, jianglai reviewed
> Reviewed 10 of 11 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2023-11-16 19:37 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2224)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[`util/src/main/java/google/registry/util/ProxyHttpHeaders.java` line 37 at r3](https://reviewable.io/reviews/google/nomulus/2224#-NjOcdtK3iWbhb5-XBL_:-NjOcdtL7QutMBzYVMeP:bqn4578) ([raw file](https://github.com/google/nomulus/blob/f5dd053e3b0e7319e3a1e7680ab1e4f7b533f826/util/src/main/java/google/registry/util/ProxyHttpHeaders.java#L37)):*
> ```Java
> 
>   /** HTTP header name used to pass the client IP address from the proxy to Nomulus. */
>   public static final String IP_ADDRESS = "Client-Address";
> ```

Should probably be `X-` something based on established convention (if that's actually correct), and maybe something not quite so generic?  Put `Nomulus` in it perhaps?


<!-- Sent from Reviewable.io -->

2023-11-16 21:37 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2224)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[`util/src/main/java/google/registry/util/ProxyHttpHeaders.java` line 37 at r3](https://reviewable.io/reviews/google/nomulus/2224#-NjOcdtK3iWbhb5-XBL_:-NjP2dy35vdPcKX6D1iN:b-xzo72q) ([raw file](https://github.com/google/nomulus/blob/f5dd053e3b0e7319e3a1e7680ab1e4f7b533f826/util/src/main/java/google/registry/util/ProxyHttpHeaders.java#L37)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should probably be `X-` something based on established convention (if that's actually correct), and maybe something not quite so generic?  Put `Nomulus` in it perhaps?
</blockquote></details>

According to MDN the `X-` prefix convention is [deprecated as of 2012](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers).

Ideally we would want to change all of our custom headers to be `Nomulus-` prefixed, perhaps.


<!-- Sent from Reviewable.io -->

2023-11-27 18:45 UTC, gbrodman approved these changes
> Reviewed 10 of 11 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2224)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2023-11-28 18:19 UTC, jianglai reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2224)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2023-11-28 18:20 UTC, merged