Start using Tld's bsaEnrollStartTime field
google/nomulus pull request #2239
Opened 2023-11-30 23:11 UTC by weiminyu

2023-12-01 20:46 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jianglai, @sarahcaseybot, and @weiminyu)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 260 at r1](https://reviewable.io/reviews/google/nomulus/2239#-Nkb78nzBMeWf9try04s:-Nkb78nzBMeWf9try04t:b-d6w5ay) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L260)):*
> ```Java
> 
>   /** Checks if {@code tld} is/was/will be enrolled with BSA at the given {@code time}. */
>   public static boolean isEnrolledWithBsa(Tld tld, DateTime time) {
> ```

`now` is a more canonical var name here than `time` for our codebase.
___
*[`core/src/main/java/google/registry/tools/ConfigureTldCommand.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2239#-Nkb7K58ATe0h409UoMN:-Nkb7K58ATe0h409UoMO:b4kth2b) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/tools/ConfigureTldCommand.java#L125)):*
> ```Java
>     checkDnsWriters(newTld);
>     checkCurrency(newTld);
>     // bsaEnrollStartTime only exists in DB. Need to carry it over to the new instance.
> ```

Is this the best pattern for accomplishing adding a new field to a YAML-controlled entity?  What is "the new instance" exactly anyway?  Is this to compensate for the value not yet existing in the YAML files?  (Shouldn't we do that first though?)


<!-- Sent from Reviewable.io -->

2023-12-01 21:29 UTC, CydeWeys submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @jianglai, @JsonIgnore, and @weiminyu)

___
*[`core/src/main/java/google/registry/tools/ConfigureTldCommand.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2239#-Nkb7K58ATe0h409UoMN:-NkbHLcY5jtwC0rBJf3F:b-ihemxz) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/tools/ConfigureTldCommand.java#L125)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Yes, these lines are needed here because the field is still annotated with @JsonIgnore, but I don't see why that is necessary. The field could just be configured in the YAML files.
</blockquote></details>

Seems like this should just be in the YAML files then?


<!-- Sent from Reviewable.io -->

2023-12-02 03:32 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @jianglai, @JsonIgnore, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 260 at r1](https://reviewable.io/reviews/google/nomulus/2239#-Nkb78nzBMeWf9try04s:-NkcZ0Ou63yI5x1BgSns:bb6un1j) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L260)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`now` is a more canonical var name here than `time` for our codebase.
</blockquote></details>

Done
___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-NkcViWuCS4cXmuFtQIR:b-xystjg) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Why are you still using JsonIgnore? It's just a DateTime so it should not need any sort of custom serializer/deserializer to work with the YAML config files.
</blockquote></details>

Added comments to explain the reason.
___
*[`core/src/main/java/google/registry/tools/ConfigureTldCommand.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2239#-Nkb7K58ATe0h409UoMN:-NkcZ7DgD_QjzYCGjiSm:bd1azrg) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/tools/ConfigureTldCommand.java#L125)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Seems like this should just be in the YAML files then?
</blockquote></details>

See my response to the previous comment in Tld.java


<!-- Sent from Reviewable.io -->

2023-12-03 19:11 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @jianglai, @JsonIgnore, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-Nkl4cAP9hYRbl16XmCU:b2yoqb2) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Added comments to explain the reason.
</blockquote></details>

Basically we don't want people to inadvertently modify this property without performing related work.


<!-- Sent from Reviewable.io -->

2023-12-04 17:38 UTC, jianglai reviewed
> Reviewed 1 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: all files reviewed, 2 unresolved discussions (waiting on @JsonIgnore and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-NkpsBuz5BBL-pAzBeh8:b-i3627t) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Basically we don't want people to inadvertently modify this property without performing related work.
</blockquote></details>

Do you intend for it to be eventually managed by YAML? If so, we should make that clear in the comment.
___
*[`core/src/main/java/google/registry/tools/ConfigureTldCommand.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2239#-Nkb7K58ATe0h409UoMN:-NkptnPr6ca7dvPDORS_:b-pidmav) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/tools/ConfigureTldCommand.java#L125)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

See my response to the previous comment in Tld.java
</blockquote></details>

I'm a bit lost. Do we have to do the same thing for every field that is annotated with `@JsonIgnore`? There are many but why do you only have to do it for this field?


<!-- Sent from Reviewable.io -->

2023-12-04 17:39 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: all files reviewed, 2 unresolved discussions (waiting on @JsonIgnore and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-NkpuIpc6v57gbfXOgZM:bsa0s6d) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Do you intend for it to be eventually managed by YAML? If so, we should make that clear in the comment.
</blockquote></details>

I haven't thought it through, but probably not.


<!-- Sent from Reviewable.io -->

2023-12-04 19:00 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: all files reviewed, 2 unresolved discussions (waiting on @JsonIgnore and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-NkqBm3SAZgWbV2FUPJH:b5v0uhm) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

The spirit of adding the YAML configurations was to prevent a single person from being able to make significant production changes to a TLD without oversight. Perhaps instead of it being a nomulus tool command the procedure described in b/309175410 should be an action class that is run at the specific time specified in the TLD YAML config (this field)?
</blockquote></details>

An action class is probably the right solution, but the specifics need to be worked out later.
___
*[`core/src/main/java/google/registry/tools/ConfigureTldCommand.java` line 125 at r1](https://reviewable.io/reviews/google/nomulus/2239#-Nkb7K58ATe0h409UoMN:-NkqAj2T4diShJr8uO9Q:b-k8smgc) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/tools/ConfigureTldCommand.java#L125)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I'm a bit lost. Do we have to do the same thing for every field that is annotated with `@JsonIgnore`? There are many but why do you only have to do it for this field?
</blockquote></details>

Those are derived properties. The breakglass filed was the only meaningful field that requires special treatment, though still changed by editing the checked-in source.

The bsa time field is a new one. 


<!-- Sent from Reviewable.io -->

2023-12-04 19:04 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: all files reviewed, 2 unresolved discussions (waiting on @JsonIgnore and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-NkqClpc4jJZXP-LIbIl:bub8wcl) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

An action class is probably the right solution, but the specifics need to be worked out later.
</blockquote></details>

It is not a blocking issue for the BSA launch.


<!-- Sent from Reviewable.io -->

2023-12-04 19:22 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: all files reviewed, 2 unresolved discussions (waiting on @JsonIgnore and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-NkqGaRX2FS7NviE7cmw:b-3sd7c5) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

It is not a blocking issue for the BSA launch.
</blockquote></details>

I still don't see why it is a good idea to NOT manage the field by YAML. Do we need to change the field on the fly frequently? It is a timestamp so it's not like the rollout of the feature has to be timed precisely. 


<!-- Sent from Reviewable.io -->

2023-12-04 20:25 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: all files reviewed, 2 unresolved discussions (waiting on @JsonIgnore and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-NkqPlrFAyDRy88JndqE:b-u7qlhi) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I still don't see why it is a good idea to NOT manage the field by YAML. Do we need to change the field on the fly frequently? It is a timestamp so it's not like the rollout of the feature has to be timed precisely.
</blockquote></details>

We can manage it in yaml but it adds complexity: the yaml process must be able to schedule a task to run at the given time to perform additional setup/clean up. Then we need to implement alerting etc to make sure all failures are caught. We also need to put in checks to ensure that, if the launch time is moved forward or backward, the original task would not take effect.
And instead of checking the given time value on the fly to ensure it is in the future, we need to add a presubmit test for that.

At some point the question pops up: is it worth it?


<!-- Sent from Reviewable.io -->

2023-12-05 15:51 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)* status: all files reviewed, 2 unresolved discussions (waiting on @JsonIgnore and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-Nkuf4ke76pLhnHHR-2Y:b-3fqx5j) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Do you mean there are additional steps needed, other than simply setting the value to what the YAML file has? If so, I can understand why it is not worth the effort, until maybe we have a more generic solution for a callback feature when applying YAML configs. You should add some notes in the javadoc explaining what these steps are, though.
</blockquote></details>

There is an open bug for this: b/309175410. The details is to be worked out later.


<!-- Sent from Reviewable.io -->

2023-12-06 12:14 UTC, CydeWeys commented
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/2239)_ status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @jianglai, @JsonIgnore, and @sarahcaseybot)
> 
> _[`core/src/main/java/google/registry/model/tld/Tld.java` line 559 at r1](https://reviewable.io/reviews/google/nomulus/2239#-NkbAgMIBhIpe5trD1m_:-Nkl4cAP9hYRbl16XmCU:b2yoqb2) ([raw file](https://github.com/google/nomulus/blob/4bc8a52ee7dea9a64a0133e0294eba4262215764/core/src/main/java/google/registry/model/tld/Tld.java#L559)):_
> 
> Previously, weiminyu (Weimin Yu) wrote…
> Basically we don't want people to inadvertently modify this property without performing related work.

Right, but it becomes HARDER to inadvertently modify this property when it's in the YAML and requires a code review.  If it's just configured through a flag on the `update_tld` command then it's easier to mess up.  (Or is it just controlled by manual changes to the DB, which is itself not great?)

2023-12-06 22:11 UTC, merged