Use the error stream when HTTP response code is non-200
google/nomulus pull request #2245
Opened 2023-12-05 18:26 UTC by jianglai

2023-12-05 19:04 UTC, ptkach requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2245)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/request/UrlConnectionUtils.java` line 52 at r1](https://reviewable.io/reviews/google/nomulus/2245#-NkvMMp19-1LPijowH9D:-NkvMMp19-1LPijowH9E:b-u1nnpv) ([raw file](https://github.com/google/nomulus/blob/48572162819801d2a5c86a89d4d5a5093bf7c31f/core/src/main/java/google/registry/request/UrlConnectionUtils.java#L52)):*
> ```Java
>     int responseCode = connection.getResponseCode();
>     try (InputStream is =
>         responseCode == STATUS_CODE_OK
> ```

I think it's too strict. We might want an entire range of 2XX here


<!-- Sent from Reviewable.io -->

2023-12-05 19:09 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2245)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @ptkach)

___
*[`core/src/main/java/google/registry/request/UrlConnectionUtils.java` line 52 at r1](https://reviewable.io/reviews/google/nomulus/2245#-NkvMMp19-1LPijowH9D:-NkvNdKV5HXp8pggMPuo:bqia227) ([raw file](https://github.com/google/nomulus/blob/48572162819801d2a5c86a89d4d5a5093bf7c31f/core/src/main/java/google/registry/request/UrlConnectionUtils.java#L52)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I think it's too strict. We might want an entire range of 2XX here
</blockquote></details>

Actually, based on `getErrorStream()`, it only returns non-null if the response code is >= 400.


<!-- Sent from Reviewable.io -->

2023-12-05 19:44 UTC, gbrodman approved these changes

2023-12-06 14:03 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2245)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)



<!-- Sent from Reviewable.io -->

2023-12-06 15:42 UTC, merged