WIP
google/nomulus pull request #2255
Opened 2023-12-14 14:12 UTC by jianglai

2023-12-15 16:54 UTC, weiminyu reviewed
Are you sure java8compatibility can be removed? It checks third-party dependencies too. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-NliOV_zAln5a67wUMUx:braquvk)* status: 0 of 139 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @jianglai)



<!-- Sent from Reviewable.io -->

2023-12-15 16:57 UTC, weiminyu requested changes
You may want to check with ben about removing docs.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-NliPBgS3iMVVjINA9Sb:bvo77ns)* status: 0 of 139 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @jianglai)



<!-- Sent from Reviewable.io -->

2023-12-15 16:59 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255)* status: 0 of 139 files reviewed, 3 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`build.gradle` line 368 at r6](https://reviewable.io/reviews/google/nomulus/2255#-NliPbdJ7ytZnWq9mDpG:-NliPbdJ7ytZnWq9mDpH:b4bwves) ([raw file](https://github.com/google/nomulus/blob/217af8ad71d5bb96326d7194abeee2785600a84d/build.gradle#L368)):*
> ```Gradle
>     compileTestJava {
>       // TODO: Remove this once we migrate off AppEngine.
>       options.release = 8
> ```

I don't see the needs for this. It doesn't affect production code.



_Code quote:_
```Gradle
 options.release = 8
```


<!-- Sent from Reviewable.io -->

2023-12-18 15:46 UTC, jianglai reviewed
I would have kept java8compatibility tests in place, were it not for the fact that it also has come incompatibility issues with Java 17. I have a hard time understanding why it was needed in the first place, though. I would have expected that since all prod jars are built at Java 8 level, it would not have been possible for them to have a compile time dependency on any jars that requires Java 9+. Since this class is checking the jar files, it would not have caught any runtime dependency that requires a higher version of Java, would it?

Regarding docs, it is my firm belief (having spent considerable time upgrading it from Java 8 to Java 11) that it is not worth keeping around. @CydeWeys feel free to chime in.

> Reviewed 125 of 128 files at r1, 13 of 13 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-NlxYixE14KyrziWAZIh:b-cp7o7v)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman, @github-advanced-security[bot], and @weiminyu)

___
*[`build.gradle` line 368 at r6](https://reviewable.io/reviews/google/nomulus/2255#-NliPbdJ7ytZnWq9mDpG:-Nlx_xb6Dl6Qp-nO8f3H:bpjek8h) ([raw file](https://github.com/google/nomulus/blob/217af8ad71d5bb96326d7194abeee2785600a84d/build.gradle#L368)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

I don't see the needs for this. It doesn't affect production code.
</blockquote></details>

It doesn't. But when building with Java 17, it complains about version incompatibilities. Plus, I think it is generally a good idea to build/run your tests at the save language level as your production code.

Note that this is just a temporary measure. Once we build Java 17-level production code, we can start using Java 9+ level language features in tests again.
___
*[`core/src/main/java/google/registry/beam/spec11/SafeBrowsingTransforms.java` line 228 at r1](https://reviewable.io/reviews/google/nomulus/2255#gh-1426878819:-NldmS-h5BzKh-V7l7QH:b-iurftj) ([raw file](https://github.com/google/nomulus/blob/547400ce357f40ebf2bb6faa007facfe4f52f4fc/core/src/main/java/google/registry/beam/spec11/SafeBrowsingTransforms.java#L228)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Log Injection

This log entry depends on a [user-provided value](1).

[Show more details](https://github.com/google/nomulus/security/code-scanning/1634)
</blockquote></details>

False positive. It is OK to log the response from safebrowsing.
___
*[`prober/src/main/java/google/registry/monitoring/blackbox/handler/WebWhoisActionHandler.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2255#gh-1426878820:-NlhkQlK7b-ClHSWey8Y:b-7eu3fh) ([raw file](https://github.com/google/nomulus/blob/547400ce357f40ebf2bb6faa007facfe4f52f4fc/prober/src/main/java/google/registry/monitoring/blackbox/handler/WebWhoisActionHandler.java#L90)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Log Injection

This log entry depends on a [user-provided value](1).

[Show more details](https://github.com/google/nomulus/security/code-scanning/1635)
</blockquote></details>

Proof-of-concept code, not used.


<!-- Sent from Reviewable.io -->

2023-12-18 15:58 UTC, weiminyu reviewed
I remember situations where java 9+ dependency was leaked into the nomulus jar when we had the release=8 option set.
Maybe I remembered wrong, but it worth checking if a known 9+ dependency  can be linked with nomulus.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-Nlxc8oa3fdV6teLXjoE:b-h5me98)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2023-12-20 21:19 UTC, weiminyu reviewed
Direct dependencies are checked by the compiler so they are ok.

However, if an indirect dependency is resolved by gradle to a  version at java 9+ language level, 
the compiler cannot tell that, and the error only shows up on AppEngine.

I once saw this happening in Crash with a dependency used by the secret-manager.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-Nm83kntDAGqunSHy6qg:b-xd5sqd)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2023-12-20 21:28 UTC, jianglai commented
> Direct dependencies are checked by the compiler so they are ok.
> 
> However, if an indirect dependency is resolved by gradle to a version at java 9+ language level, the compiler cannot tell that, and the error only shows up on AppEngine.
> 
> I once saw this happening in Crash with a dependency used by the secret-manager.
> 
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-Nm83kntDAGqunSHy6qg:b-xd5sqd)_ status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

So this is not an issue specific to App Engine? In theory any Java application can declare a target version but have an indirect dependency that requires a higher version of JRE? That makes the entire Gradle build system very brittle and unreliable... Does that mean everyone who uses Gradle needs to do this check?

2023-12-21 20:58 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2023-12-21 21:22 UTC, jianglai reviewed
> Reviewed 9 of 9 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2023-12-21 21:25 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2023-12-26 19:25 UTC, jianglai reviewed
> Reviewed 20 of 20 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman, @github-advanced-security[bot], and @ptkach)



<!-- Sent from Reviewable.io -->

2024-01-02 16:31 UTC, weiminyu reviewed
In theory, yes. In practice, if you are reasonably up to date with your JVM version, you don't have  to.
Look how long it takes for libs like guava or hibernate to move past java 8. So once we move off AppEngine, it will be safe to delete this subproject.

Also, it is not that a lib specifically requires a higher version of jvm. The higher version slips in due to open-ended dependency ranges.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-Nn9zRbl85X8sCP_L71p:b-m1mg9s)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman, @github-advanced-security[bot], and @ptkach)



<!-- Sent from Reviewable.io -->

2024-01-09 19:03 UTC, jianglai reviewed
This PR is a prerequisite to enabling Java 17 runtime on App Engine. At this point I think it is not worth the effort making the java8compatiblity package work (it uses some internal APIs not available in Java 17 anymore), given that after it's merged we will quickly turn on Java 17 and make the risk of accidentally pulling in a Java 8 only dependency in the meantime minimal. It is prudent that we merge this PR sooner as it touches many parts of the code base and is likely to be in merge conflict the longer we wait on it.

> Reviewed 13 of 13 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-NnjaI836JJhjttQLAxM:bjgqdu3)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman, @github-advanced-security[bot], and @ptkach)



<!-- Sent from Reviewable.io -->

2024-01-09 19:41 UTC, weiminyu approved these changes
Approved. Once you submit it, we should probably forbid any dependency change until the AppEngine runtime environment is updated to Java 17 also.  Just last week Sarah ran into this problem briefly that was caught by the com[atibility check.

> Reviewed 1 of 128 files at r1, 1 of 13 files at r2, 1 of 20 files at r14, 1 of 20 files at r16.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-Nnjj0Je0VGMrIWwLz7b:bd90rv1)* status: 131 of 150 files reviewed, 2 unresolved discussions (waiting on @gbrodman, @github-advanced-security[bot], @jianglai, and @ptkach)



<!-- Sent from Reviewable.io -->

2024-01-09 19:43 UTC, jianglai commented
> Approved. Once you submit it, we should probably forbid any dependency change until the AppEngine runtime environment is updated to Java 17 also. Just last week Sarah ran into this problem briefly that was caught by the com[atibility check.
> 
> > Reviewed 1 of 128 files at r1, 1 of 13 files at r2, 1 of 20 files at r14, 1 of 20 files at r16.
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/2255#-:-Nnjj0Je0VGMrIWwLz7b:bd90rv1)_ status: 131 of 150 files reviewed, 2 unresolved discussions (waiting on @gbrodman, @github-advanced-security[bot], @jianglai, and @ptkach)

Sure. I'll also take another crack at making the compatiblity test work after it's merged. I just want this to go through sooner rather than later.

2024-01-09 20:56 UTC, merged