Define the --end_breakglass and --build_environment flags
google/nomulus pull request #2277
Opened 2024-01-09 21:40 UTC by sarahcaseybot

It is necessary to define these flags in a deployment before merging go/r3pr/2273 in order to prevent breaking the exisitng TLD syncing and entity presubmit testing that has already been enabled

2024-01-10 18:10 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2277)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tools/ConfigureTldCommand.java` line 67 at r1](https://reviewable.io/reviews/google/nomulus/2277#-NnoZC6C85WcDkWgsvUv:-NnoZC6C85WcDkWgsvUw:b-l5o1vt) ([raw file](https://github.com/google/nomulus/blob/50eea914dc7bb898021614fb35119c68553b24c8/core/src/main/java/google/registry/tools/ConfigureTldCommand.java#L67)):*
> ```Java
> 
>   @Parameter(
>       names = {"-b", "--breakglass"},
> ```

It might be cleaner to make this take a `boolean`, so that it will look like either:

```
nomulus update_tld dev --breakglass=true
nomulus update_tld dev --breakglass=false
```

What do you think?

Also "break glass" is two words so this should all be `breakGlass` for variables and `break_glass` for command line flags.


<!-- Sent from Reviewable.io -->

2024-01-12 19:58 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2277)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tools/ConfigureTldCommand.java` line 67 at r1](https://reviewable.io/reviews/google/nomulus/2277#-NnoZC6C85WcDkWgsvUv:-NnzEucR33e418UxSJtr:bbyqi16) ([raw file](https://github.com/google/nomulus/blob/50eea914dc7bb898021614fb35119c68553b24c8/core/src/main/java/google/registry/tools/ConfigureTldCommand.java#L67)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

When a TLD is set to break glass mode, that means that we want to prevent the build system from overwriting any changes made via the command line with whatever is saved to the configuration files. The TLD sync is done using Cloud Build with this script https://cs.opensource.google/nomulus/nomulus/+/master:release/tld-updater/sync_tlds.sh and once the --build_environment tag is added, we will add that tag to the configure_tld command call in that script. 

Your suggestion to just have --break_glass=false indicate that the break glass mode should end would automatically end break glass mode on all Cloud Build calls of that script since without specifying a --break_glass flag, it would default to false. This would mean that the local changes would be overwritten by the internal configuration file.
</blockquote></details>

`without specifying a --break\_glass flag, it would default to false`

It would be an optional parameter that takes three values -- either not specified at all (retain existing value), false, or true.  So it'd need to be a `Boolean` instead of a `boolean` and have `null` as the third state.  We have plenty of other examples in our codebase of optional boolean nomulus parameters, e.g.: 

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java;l=65-75;drc=68750569db14e79fd258b26c40745add84c9dab1

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java;l=330-336;drc=68750569db14e79fd258b26c40745add84c9dab1


<!-- Sent from Reviewable.io -->

2024-01-12 20:20 UTC, gbrodman reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2277)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java` line 540 at r2](https://reviewable.io/reviews/google/nomulus/2277#-Nnz42-h7qXk6Z4ZYeWM:-Nnz42-h7qXk6Z4ZYeWN:b-p89gye) ([raw file](https://github.com/google/nomulus/blob/68a5ec8b9520920d67b86502e17c1f406a62fa34/core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java#L540)):*
> ```Java
> 
>   @Test
>   void testSuccess_breaklassFlag_continuesBreakGlassMode() throws Exception {
> ```

nit: missing a "g"


<!-- Sent from Reviewable.io -->

2024-01-18 22:43 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2277)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/tools/ConfigureTldCommand.java` line 151 at r4](https://reviewable.io/reviews/google/nomulus/2277#-NoTjG9x2X2AGnhYHNBl:-NoTjG9x2X2AGnhYHNBm:bhs59qj) ([raw file](https://github.com/google/nomulus/blob/e7bb4807a43ead42f577a567f93ebcdc68fe1354/core/src/main/java/google/registry/tools/ConfigureTldCommand.java#L151)):*
> ```Java
>     }
>     // Set the new TLD to break glass mode if break glass flag was used
>     if (Boolean.TRUE.equals(breakGlass)) {
> ```

Shouldn't these three lines just be: `Optional.ofNullable(breakGlass).ifPresent(...);`

And by the way, shouldn't setting this new boolean to `false` turn off break glass mode? I "m not seeing where that would actually happen though?


<!-- Sent from Reviewable.io -->

2024-01-19 18:47 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2277#-:-NoY241S8dA1A7-D1BzN:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2024-01-19 19:23 UTC, merged