Restyle console based on the new design proposal
google/nomulus pull request #2336
Opened 2024-02-26 21:14 UTC by ptkach

2024-02-27 21:34 UTC, ptkach commented
@gbrodman It's still work in progress, but it's growing too big so I figured i'd give you a bit of heads up before I'm fully ready to merge. Unfortunately it'd not make sense to split it into different PR, as most of it depends on a common style/theme changes.

2024-03-11 21:43 UTC, gbrodman requested changes
> Reviewed 5 of 58 files at r1, 2 of 15 files at r2, 12 of 72 files at r3, 7 of 21 files at r4, 4 of 19 files at r7.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: 23 of 120 files reviewed, 23 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/billingInfo/billingInfo.component.html` line 7 at r4](https://reviewable.io/reviews/google/nomulus/2336#gh-1508188536:-NsPZpXI1OIG_mof1H0Z:b4eeqfm) ([raw file](https://github.com/google/nomulus/blob/ec03390a44c2817042efd65e2e64a179a6c5d36d/console-webapp/src/app/billingInfo/billingInfo.component.html#L7)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Potentially unsafe external link

External links without noopener/noreferrer are a potential security risk.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1843)
</blockquote></details>

I did not know this was an issue! Shouldn't be a big deal since we control this link, but we probably want to add the suggestion anyway 
___
*[`console-webapp/src/app/billingInfo/billingInfo.component.ts` line 28 at r6](https://reviewable.io/reviews/google/nomulus/2336#-NsP_HH26YlmjKK4473w:-NsP_HH26YlmjKK4473x:biyd5jw) ([raw file](https://github.com/google/nomulus/blob/f4c3b3946bf7474414ee0aa8c9601cde680e2e6a/console-webapp/src/app/billingInfo/billingInfo.component.ts#L28)):*
> ```XML
> 
>   driveFolderUrl = computed<string>(() => {
>     if (this.registrarService.registrar()?.driveFolderId) {
> ```

I feel like silently displaying the empty string if there's no registrar selected seems wrong -- what about some sort of error message or prompt to select a registrar? 
___
*[`console-webapp/src/app/registrar/registrarSelector.component.html` line 8 at r8](https://reviewable.io/reviews/google/nomulus/2336#-NsjS2bD5MMLV62hMbdp:-NsjS2bEDwGOSjJ-Di5W:b-id9xsf) ([raw file](https://github.com/google/nomulus/blob/52fddfef4df3b3c162ebca7c7b2dbf4d748b28db/console-webapp/src/app/registrar/registrarSelector.component.html#L8)):*
> ```HTML
>   >
>     <mat-label>Registrar</mat-label>
>     <input
> ```

It seems like we lose the "selected" checkmark on the selected registrar as soon as we type anything in to the search box (even if it's just deleting the existing text). Do you know why that might happen? 
___
*[`console-webapp/src/app/registrar/registrarSelector.component.html` line 9 at r8](https://reviewable.io/reviews/google/nomulus/2336#-NsjSE6S2oARPdf232d-:-NsjSE6T8e-AXHH45IdP:bdk2ipv) ([raw file](https://github.com/google/nomulus/blob/52fddfef4df3b3c162ebca7c7b2dbf4d748b28db/console-webapp/src/app/registrar/registrarSelector.component.html#L9)):*
> ```HTML
>     <mat-label>Registrar</mat-label>
>     <input
>       type="text"
> ```

Can we have an error message if the user puts in an invalid registrar?
___
*[`console-webapp/src/app/registrar/registrarSelector.component.html` line 23 at r8](https://reviewable.io/reviews/google/nomulus/2336#-NsjSZAmE1prFY5osEQw:-NsjSZAmE1prFY5osEQx:b-j3glkq) ([raw file](https://github.com/google/nomulus/blob/52fddfef4df3b3c162ebca7c7b2dbf4d748b28db/console-webapp/src/app/registrar/registrarSelector.component.html#L23)):*
> ```HTML
>       (optionSelected)="onSelect($event.option.value)"
>     >
>       @for (registrarId of filteredOptions; track registrarId) {
> ```

I noticed that filteredOptions is set in the constructor of the ts file. Does that mean that the object is reconstructed every time the user types a character? 
___
*[`console-webapp/src/app/registrar/registrarSelector.component.ts` line 39 at r8](https://reviewable.io/reviews/google/nomulus/2336#-NsjShOg3LMMOnA8zExA:-NsjShOg3LMMOnA8zExB:b-2aaoae) ([raw file](https://github.com/google/nomulus/blob/52fddfef4df3b3c162ebca7c7b2dbf4d748b28db/console-webapp/src/app/registrar/registrarSelector.component.ts#L39)):*
> ```XML
>   onSelect(registrarId: string) {
>     this.registrarService.updateSelectedRegistrar(registrarId);
>     this.registrarInput.set('');
> ```

Why do we set the input to the empty string here? I don't think it should be necessary? It seems like it makes the filtering behave a bit oddly (it removes the filter but keeps the text there) 
___
*[`console-webapp/src/app/support/support.component.html` line 7 at r6](https://reviewable.io/reviews/google/nomulus/2336#-NsPg1z344BmhBTnIUVn:-NsPg1z344BmhBTnIUVo:bqajbbt) ([raw file](https://github.com/google/nomulus/blob/f4c3b3946bf7474414ee0aa8c9601cde680e2e6a/console-webapp/src/app/support/support.component.html#L7)):*
> ```HTML
>     <h2>Email</h2>
>     <p class="text-l">For help with OT&E sandbox and certification, or new technical requirements for any of our new TLD launches.</p>
>     <a class="text-l" href="mailto:{{ userDataService.userData?.supportEmail }}">{{ userDataService.userData?.supportEmail || 'TODO_REMOVE@gmail.com' }}</a>
> ```

can we just count on the user data existing? If it doesn't exist, won't we have a ton of other problems? 
___
*[`console-webapp/src/app/support/support.component.html` line 9 at r6](https://reviewable.io/reviews/google/nomulus/2336#-NsPhBUbBZzdC6-3Z1PV:-NsPhBUbBZzdC6-3Z1PW:b-yw2u1t) ([raw file](https://github.com/google/nomulus/blob/f4c3b3946bf7474414ee0aa8c9601cde680e2e6a/console-webapp/src/app/support/support.component.html#L9)):*
> ```HTML
>     <a class="text-l" href="mailto:{{ userDataService.userData?.supportEmail }}">{{ userDataService.userData?.supportEmail || 'TODO_REMOVE@gmail.com' }}</a>
>     <p class="text-l">For general purpose questions once you are integrated with our registry system. If the issue is urgent, please put "Urgent" in the email title.</p>
>     <a class="text-l" href="mailto:{{ userDataService.userData?.supportEmail }}">{{ userDataService.userData?.supportEmail  || 'TODO_REMOVE@gmail.com' }}</a>
> ```

we probably only want to list the email address once, I think? 
___
*[`console-webapp/src/app/support/support.component.html` line 15 at r6](https://reviewable.io/reviews/google/nomulus/2336#-NsPhe04CqclgiiLzH4t:-NsPhe04CqclgiiLzH4u:b-ijwbft) ([raw file](https://github.com/google/nomulus/blob/f4c3b3946bf7474414ee0aa8c9601cde680e2e6a/console-webapp/src/app/support/support.component.html#L15)):*
> ```HTML
>     <a class="text-l" href="tel:{{ userDataService.userData?.supportPhoneNumber }}">{{userDataService.userData?.supportPhoneNumber || '123123123'}}</a>
>     <p class="text-l">Your telephone passcode:</p>
>     <p class="text-l console-app__support-passcode">5555</p>
> ```

we should have a TODO to actually expose + add the passcode right? 
___
*[`console-webapp/src/app/tlds/tlds.component.html` line 1 at r6](https://reviewable.io/reviews/google/nomulus/2336#-NsPUo9gDMDeCdrf9cdK:-NsPUo9gDMDeCdrf9cdL:bg60p8h) ([raw file](https://github.com/google/nomulus/blob/15368ee1c6bdd09bd27e084bac04f32b3173bca2/console-webapp/src/app/tlds/tlds.component.html#L1)):*
> ```HTML
> <div class="console-tlds__cards">
> ```

It doesn't seem like this (plus the related files) is/are being used anywhere, should we delete it? 
___
*[`console-webapp/src/assets/billing.png` line 0 at r6](https://reviewable.io/reviews/google/nomulus/2336#-NsPPmxf61UKtQx2r8fp:-NsPPmxf61UKtQx2r8fq:b-a0j7ot) ([raw file](https://github.com/google/nomulus/blob/f4c3b3946bf7474414ee0aa8c9601cde680e2e6a/console-webapp/src/assets/billing.png#L0)):*
haha where'd the images come from? 


<!-- Sent from Reviewable.io -->

2024-03-15 16:15 UTC, gbrodman requested changes
> Reviewed 24 of 58 files at r1, 23 of 72 files at r3, 2 of 21 files at r4, 1 of 8 files at r5, 4 of 19 files at r7, 4 of 20 files at r8, 1 of 14 files at r9, 14 of 30 files at r10, 2 of 13 files at r11, 5 of 5 files at r12, 2 of 2 files at r13, 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: 92 of 120 files reviewed, 37 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/registrar/registrar.service.ts` line 37 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyBqix0wXBswbUXVkL:-NsyBqix0wXBswbUXVkM:bwkvqkx) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrar.service.ts#L37)):*
> ```XML
>   icannReferralEmail?: string;
>   localizedAddress?: Address;
>   registrarId?: string;
> ```

shouldn't these fields all be required? 
___
*[`console-webapp/src/app/registrar/registrar.service.ts` line 44 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyBjbv7D0xdEgSgtIC:-NsyBjbv7D0xdEgSgtID:b-lvhvvp) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrar.service.ts#L44)):*
> ```XML
> export interface Registrar extends WhoisRegistrarFields {
>   allowedTlds?: string[];
>   faxNumber?: string;
> ```

can we keep these in alphabetical order please?
___
*[`console-webapp/src/app/registrar/registrar.service.ts` line 61 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyBf0g-LS0um7JI9WM:-NsyBf0g-LS0um7JI9WN:b-r7giaw) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrar.service.ts#L61)):*
> ```XML
>   registrarId = signal<string>('');
>   registrars = signal<Registrar[]>([
>     {
> ```

are these actually used? it seems like it queries the backend
___
*[`console-webapp/src/app/registrar/registrar.service.ts` line 264 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyCFlE1ENSaW_nIb1H:-NsyCFlE1ENSaW_nIb1I:b6gd42h) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrar.service.ts#L264)):*
> ```XML
>   }
> 
>   saveRegistrar(registrar: Registrar) {
> ```

this is only called from the registrar details component right? If so, why not just have it there? Honest question 
___
*[`console-webapp/src/app/registrar/registrarDetails.component.html` line 26 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyCYvv2SpqH__c5Yks:-NsyCYvw6wkPUwxk19-k:b-rn8yjv) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrarDetails.component.html#L26)):*
> ```HTML
>     </div>
>     <h1>{{ registrarInEdit.registrarId }}</h1>
>     <h2 *ngIf="registrarInEdit.registrarName !== registrarInEdit.registrarId">
> ```

why use the *ngIf here instead of the `@if`? 
___
*[`console-webapp/src/app/registrar/registrarDetails.component.html` line 30 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyETTdCNwg1xGc0wZq:-NsyETTdCNwg1xGc0wZr:bo74nsm) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrarDetails.component.html#L30)):*
> ```HTML
>     </h2>
>     @if(inEdit) {
>     <form (ngSubmit)="saveAndClose()">
> ```

I think we need a cancel button too (the arrow functions as such but it might not be exactly clear) 
___
*[`console-webapp/src/app/registrar/registrarDetails.component.scss` line 1 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyE008DrD684_fwHeh:-NsyE008DrD684_fwHei:bdtbgpq) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrarDetails.component.scss#L1)):*
> ```SCSS
> .console-app {
> ```

small note, not sure if we want to fix it, but the list-of-TLDs element has the text wrapping oddly on to the next line if it's long
___
*[`console-webapp/src/app/registrar/registrarDetails.component.ts` line 27 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyEdE_D6cxBCD8jTNd:-NsyEdE_D6cxBCD8jTNe:b-q5kn32) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrarDetails.component.ts#L27)):*
> ```XML
> })
> export class RegistrarDetailsComponent implements OnInit {
>   public static PATH = 'registrars/:id';
> ```

we get some really weird things going on if we use a bad registrar ID in the URL
___
*[`console-webapp/src/app/registrar/registrarDetails.component.ts` line 31 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyEihf2o-5ZDDWw3SB:-NsyEihh9l7_Zw9_LXBc:b-hda9wq) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrarDetails.component.ts#L31)):*
> ```XML
>   registrarInEdit!: Registrar;
>   columns = columns.filter((c) => !c.hiddenOnDetailsCard);
>   private subscription: any;
> ```

I think we probably don't want this to be `any` type? 
___
*[`console-webapp/src/app/registrar/registrarDetails.component.ts` line 40 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyEyrZ0ELRFAHJpSN1:-NsyEyrZ0ELRFAHJpSN2:bbfbdqm) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrarDetails.component.ts#L40)):*
> ```XML
>   ngOnInit(): void {
>     this.subscription = this.route.paramMap.subscribe((params: ParamMap) => {
>       this.registrarInEdit = structuredClone(
> ```

oh can we use `structuredClone` instead of using JSON for the deep copy? 
___
*[`console-webapp/src/app/registrar/registrarsTable.component.ts` line 91 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyA4n3Edb1J_GctQD_:-NsyA4n3Edb1J_GctQDa:boyxde3) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrarsTable.component.ts#L91)):*
> ```XML
>     private router: Router
>   ) {
>     this.dataSource = new MatTableDataSource<Registrar>(
> ```

thoughts on filtering this only on the registrar name? right now I think it filters on basically any field
___
*[`console-webapp/src/app/settings/settings.component.ts` line 26 at r11](https://reviewable.io/reviews/google/nomulus/2336#-NsyT3KZ0qaU_qPEuBuX:-NsyT3KZ0qaU_qPEuBuY:be8a23z) ([raw file](https://github.com/google/nomulus/blob/0bf474cebc79679a514474f3b00c35ffbf1acd4e/console-webapp/src/app/settings/settings.component.ts#L26)):*
> ```XML
>   public static PATH = 'settings';
> 
>   public static matchesUrl(url: string): boolean {
> ```

Why do we need this? 
___
*[`console-webapp/src/app/shared/services/userData.service.ts` line 28 at r15](https://reviewable.io/reviews/google/nomulus/2336#-Nt1kwYf1mYI29ibshzg:-Nt1kwYg7D5K42ffvqGk:be2yq8c) ([raw file](https://github.com/google/nomulus/blob/b0e9d30ab48da27fa55b0648508560c0e7723b4f/console-webapp/src/app/shared/services/userData.service.ts#L28)):*
> ```XML
>   supportPhoneNumber: string;
>   technicalDocsUrl: string;
>   passcode?: string;
> ```

I hate to be nitty but can we keep this in alphabetical order? 
___
*[`console-webapp/src/app/support/support.component.html` line 14 at r15](https://reviewable.io/reviews/google/nomulus/2336#-Nt1lgV6EpZzoUqcqJ6d:-Nt1lgV6EpZzoUqcqJ6e:b67lx4s) ([raw file](https://github.com/google/nomulus/blob/b0e9d30ab48da27fa55b0648508560c0e7723b4f/console-webapp/src/app/support/support.component.html#L14)):*
> ```HTML
>   </p>
>   <a class="text-l" href="mailto:registry-integration@google.com"
>     >registry-integration&#64;google.com</a
> ```

we still want the support email here right? 


<!-- Sent from Reviewable.io -->

2024-03-15 17:28 UTC, gbrodman requested changes
> Reviewed 1 of 58 files at r1, 3 of 72 files at r3, 1 of 14 files at r9, 2 of 30 files at r10, 1 of 13 files at r11, 4 of 13 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: 104 of 120 files reviewed, 44 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/app-routing.module.ts` line 82 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt24_WgDattBBVtK0Sm:-Nt24_Wh6vzHinyunuOg:b19dkym) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/app-routing.module.ts#L82)):*
> ```XML
>     ],
>   },
>   // {
> ```

I think we probably want to remove this bit? 
___
*[`console-webapp/src/app/home/home.component.html` line 33 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt26XVn9Mwtdtz7nStC:-Nt26XVn9Mwtdtz7nStD:b-7g0hz4) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/home/home.component.html#L33)):*
> ```HTML
>       <mat-card-actions>
>         <button mat-button color="primary" (click)="viewEpp()">
>           Update EPP Passwords
> ```

nit: password, singular
___
*[`console-webapp/src/app/home/home.component.html` line 48 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt26Sqe65LCVP1OCj89:-Nt26Sqe65LCVP1OCj8A:b-memkf5) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/home/home.component.html#L48)):*
> ```HTML
>       <mat-card-actions>
>         <button mat-button color="primary" (click)="viewRegistrars()">
>           Manage Registrars
> ```

slight nit, maybe "View Registrars"? Given that that's the word we use around this
___
*[`console-webapp/src/app/home/home.component.ts` line 36 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt26eE1-Nl9wWFXzizp:-Nt26eE1-Nl9wWFXzizq:bg665zv) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/home/home.component.ts#L36)):*
> ```XML
>     this.router.navigate([RegistrarComponent.PATH]);
>   }
>   viewEpp() {
> ```

I think we need a different name here, since eventually "view EPP" might be treated as something to actually view / run EPP commands. Maybe something about security? 
___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 6 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt277dO8oe91U4Eku3T:-Nt277dO8oe91U4Eku3U:b-2nb63d) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/settings/whois/whois.component.html#L6)):*
> ```HTML
>     mat-icon-button
>     class="console-app__whois-back"
>     aria-label="Back to whois view"
> ```

I think we probably want an explicit "cancel" button when we're in edit mode, next to the save button (in addition to the arrow) 
___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 142 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt27R2NBN4Hwie0mQl7:-Nt27R2NBN4Hwie0mQl8:b-vakw54) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/settings/whois/whois.component.html#L142)):*
> ```HTML
>     </form>
>   </div>
>   } @else {
> ```

Is it necessary to have two large blocks of code for the in-edit and not-in-edit modes? I would hope we could just have a toggle class or something. 
___
*[`console-webapp/src/app/shared/directives/locationBack.directive.ts` line 7 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt262Rt6xGgUeoc75uY:-Nt262Rt6xGgUeoc75uZ:b-g9izds) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/shared/directives/locationBack.directive.ts#L7)):*
> ```XML
>   selector: '[backButton]',
> })
> export class LocationBackDirective {
> ```

1. think we need a license
2. what's the purpose of this / where is it used? I only see it referenced in app.module.ts but it doesn't seem like it's actually used there 


<!-- Sent from Reviewable.io -->

2024-03-15 17:33 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: 104 of 120 files reviewed, 44 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/shared/directives/locationBack.directive.ts` line 7 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt262Rt6xGgUeoc75uY:-Nt2ACGi0rlRauJwu6Hb:b-gshuwr) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/shared/directives/locationBack.directive.ts#L7)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

1. think we need a license
2. what's the purpose of this / where is it used? I only see it referenced in app.module.ts but it doesn't seem like it's actually used there
</blockquote></details>

oh wait I see it -- is it only used in the registrar details page? 


<!-- Sent from Reviewable.io -->

2024-03-15 17:46 UTC, gbrodman requested changes
> Reviewed 1 of 58 files at r1, 1 of 72 files at r3, 5 of 13 files at r11, 9 of 13 files at r16.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: all files reviewed, 47 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/navigation/navigation.component.ts` line 30 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt2CYl14k4vtmIt3P5f:-Nt2CYl14k4vtmIt3P5g:bk8u1uz) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/navigation/navigation.component.ts#L30)):*
> ```XML
>   styleUrls: ['./navigation.component.scss'],
> })
> export class NavigationComponent {
> ```

i'm kind of confused what this whole component does -- does it just create the sidebar out of routes that have the correct attributes (e.g. icon)? 
___
*[`console-webapp/src/app/settings/contact/contactDetails.component.ts` line 43 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt2CwWN5Sy0kuSbtrA9:-Nt2CwWN5Sy0kuSbtrAA:buqc5a2) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/settings/contact/contactDetails.component.ts#L43)):*
> ```XML
>     if (
>       confirm(
>         `Please confirm contact ${this.contactService.contactInEdit.name} delete`
> ```

this is slightly nitty, but i think it's better grammar to say something like "Please confirm deletion of contact `name`"
___
*[`console-webapp/src/app/settings/security/security.component.html` line 83 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt2B6Bb9BKT9voZcI8H:-Nt2B6Bb9BKT9voZcI8I:bnq7fw7) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/settings/security/security.component.html#L83)):*
> ```HTML
>     </mat-card-content>
>   </mat-card>
> </div>
> ```

I think I asked a similar question elsewhere, but is it necessary to have two separate templates for in-edit vs not-in-edit? The alternative would be having some sort of class that alters the appearance / behavior of the elements 


<!-- Sent from Reviewable.io -->

2024-03-18 17:16 UTC, gbrodman requested changes
> Reviewed 6 of 6 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: all files reviewed, 48 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/domains/domainList.service.ts` line 64 at r17](https://reviewable.io/reviews/google/nomulus/2336#-NtHYEJx07l1PE-CPdag:-NtHYEJx07l1PE-CPdah:b79s8co) ([raw file](https://github.com/google/nomulus/blob/dde1e0eb0ed03787bcb6bb25c8ac8e5f646801ca/console-webapp/src/app/domains/domainList.service.ts#L64)):*
> ```XML
>       .pipe(
>         tap((domainListResult: DomainListResult) => {
>           this.checkpointTime = (domainListResult || {}).checkpointTime;
> ```

can we not just use `domainListResult?.checkpointTime`? Or why do we need this extra object creation? 
___
*[`console-webapp/src/app/registrar/registrarSelector.component.ts` line 25 at r17](https://reviewable.io/reviews/google/nomulus/2336#-NtHYxN00MaIzqNMifUq:-NtHYxN00MaIzqNMifUr:b-tgsrb7) ([raw file](https://github.com/google/nomulus/blob/dde1e0eb0ed03787bcb6bb25c8ac8e5f646801ca/console-webapp/src/app/registrar/registrarSelector.component.ts#L25)):*
> ```XML
> export class RegistrarSelectorComponent {
>   registrarInput = signal<string>('');
>   value: string = '';
> ```

what's this "value"? 


<!-- Sent from Reviewable.io -->

2024-03-18 20:00 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: all files reviewed, 48 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`console-webapp/src/app/app-routing.module.ts` line 16 at r1](https://reviewable.io/reviews/google/nomulus/2336#gh-1503311080:-NtH5rbuBO2zaZMflnLd:b-896fix) ([raw file](https://github.com/google/nomulus/blob/713d394eef7ff0f4d6c58bd0e6615bd932501ee8/console-webapp/src/app/app-routing.module.ts#L16)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import Routes.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1833)
</blockquote></details>

Done.
___
*[`console-webapp/src/app/app-routing.module.ts` line 82 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt24_WgDattBBVtK0Sm:-NtH5ylN-2Kt48qD9-pQ:bofik2o) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/app-routing.module.ts#L82)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we probably want to remove this bit?
</blockquote></details>

I think it's useful, as it soon will be a legit component. The icon is in fact the one that's expected to be there, so saves us time in the future. 
___
*[`console-webapp/src/app/billingInfo/billingInfo.component.html` line 7 at r4](https://reviewable.io/reviews/google/nomulus/2336#gh-1508188536:-NtH7G2GDP02rKQ6cx3g:b736tm1) ([raw file](https://github.com/google/nomulus/blob/ec03390a44c2817042efd65e2e64a179a6c5d36d/console-webapp/src/app/billingInfo/billingInfo.component.html#L7)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I did not know this was an issue! Shouldn't be a big deal since we control this link, but we probably want to add the suggestion anyway
</blockquote></details>

Well yeah first of all we're in control of the link, so it's not really a concern for us.
Besides - all modern browsers apply "noopener" by default to any target="_blank" links - https://chromestatus.com/feature/6140064063029248
___
*[`console-webapp/src/app/billingInfo/billingInfo.component.html` line 7 at r7](https://reviewable.io/reviews/google/nomulus/2336#gh-1516806456:-NtH7uIuD4cp8mkvyUwO:b-896fix) ([raw file](https://github.com/google/nomulus/blob/dd83781fc53f0bba01cc086ebad500bc22281d8d/console-webapp/src/app/billingInfo/billingInfo.component.html#L7)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Potentially unsafe external link

External links without noopener/noreferrer are a potential security risk.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1893)
</blockquote></details>

Done.
___
*[`console-webapp/src/app/billingInfo/billingInfo.component.ts` line 28 at r6](https://reviewable.io/reviews/google/nomulus/2336#-NsP_HH26YlmjKK4473w:-NtHA-Oa093O0ySh12Wf:b-96uhg4) ([raw file](https://github.com/google/nomulus/blob/f4c3b3946bf7474414ee0aa8c9601cde680e2e6a/console-webapp/src/app/billingInfo/billingInfo.component.ts#L28)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I feel like silently displaying the empty string if there's no registrar selected seems wrong -- what about some sort of error message or prompt to select a registrar?
</blockquote></details>

As this screen depends on selected registrar data it should behave in the same way as any other screen of sort. I added `app-selected-registrar-wrapper` to handle that
___
*[`console-webapp/src/app/domains/domainList.service.ts` line 64 at r17](https://reviewable.io/reviews/google/nomulus/2336#-NtHYEJx07l1PE-CPdag:-NtHb8ZfDqvxQYQ7jiyf:b-896fix) ([raw file](https://github.com/google/nomulus/blob/dde1e0eb0ed03787bcb6bb25c8ac8e5f646801ca/console-webapp/src/app/domains/domainList.service.ts#L64)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can we not just use `domainListResult?.checkpointTime`? Or why do we need this extra object creation?
</blockquote></details>

Done.
___
*[`console-webapp/src/app/home/home.component.html` line 33 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt26XVn9Mwtdtz7nStC:-NtHAJUsDU30zXKL9f-w:b-1lrzyf) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/home/home.component.html#L33)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit: password, singular
</blockquote></details>

Updated, but it's Password*s* in the design, so I've taken it from there
___
*[`console-webapp/src/app/home/home.component.html` line 48 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt26Sqe65LCVP1OCj89:-NtHAVS53LY0Qc3B_CEp:b-2hwukj) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/home/home.component.html#L48)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

slight nit, maybe "View Registrars"? Given that that's the word we use around this
</blockquote></details>

It's "Manage Registrars" in the design, probably hints that the screen also allows to make modifications. 
___
*[`console-webapp/src/app/home/home.component.ts` line 36 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt26eE1-Nl9wWFXzizp:-NtHB8ql6u1Poy-B8vcy:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/home/home.component.ts#L36)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we need a different name here, since eventually "view EPP" might be treated as something to actually view / run EPP commands. Maybe something about security?
</blockquote></details>

Done.
___
*[`console-webapp/src/app/navigation/navigation.component.ts` line 15 at r1](https://reviewable.io/reviews/google/nomulus/2336#gh-1503311084:-NtHBBv3Cah4chpgcsaK:b-896fix) ([raw file](https://github.com/google/nomulus/blob/713d394eef7ff0f4d6c58bd0e6615bd932501ee8/console-webapp/src/app/navigation/navigation.component.ts#L15)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import effect.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1835)
</blockquote></details>

Done.
___
*[`console-webapp/src/app/navigation/navigation.component.ts` line 30 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt2CYl14k4vtmIt3P5f:-NtHbtOu3EBc6jTAKZ5e:b-22foz4) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/navigation/navigation.component.ts#L30)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i'm kind of confused what this whole component does -- does it just create the sidebar out of routes that have the correct attributes (e.g. icon)?
</blockquote></details>

It does everything related to this navigation menu. It seems simple, but it needs some logic for it work properly and this component is responsible for this logic. To name a few:
1) it renders route and their children based on the router metadata, so we only need to maintain 1 data structure
2) it keeps browser navigation in sync with UI, in other words it always keeps current route highlighted in menu
3) it will later be responsible for showing/hiding menu items based on the user permits, eg registrar vs admin, etc

Added a comment to the component as well
___
*[`console-webapp/src/app/registrar/registrar.service.ts` line 37 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyBqix0wXBswbUXVkL:-NtHdDwP8r1p78iU8IZQ:b-vqlmn6) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrar.service.ts#L37)):*
<d [...]

2024-03-18 21:11 UTC, gbrodman requested changes
> Reviewed 19 of 19 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: all files reviewed, 19 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/home/home.component.html` line 33 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt26XVn9Mwtdtz7nStC:-NtIHi3vEGPkcpfHoYgG:bt8qpi4) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/home/home.component.html#L33)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Updated, but it's Password*s* in the design, so I've taken it from there
</blockquote></details>

yeah i think they're wrong :P 
___
*[`console-webapp/src/app/registrar/registrar.service.ts` line 37 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyBqix0wXBswbUXVkL:-NtII6tEEs2OL53meKN5:bvasopq) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrar.service.ts#L37)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I've copied it from the implementation you made - [https://cs.opensource.google/nomulus/nomulus/+/master:console-webapp/src/app/settings/whois/whois.service.ts](https://github.com/google/nomulus/pull/2155/files) without checking with back-end.
After checking into back-end I see that most of the fields (except for `ianaIdentifier`) are indeed required, updated.
</blockquote></details>

thanks -- yeah I think originally we had some of them as optional due to some mock testing data not having all the fields 
___
*[`console-webapp/src/app/registrar/registrarDetails.component.html` line 97 at r18](https://reviewable.io/reviews/google/nomulus/2336#-NtIOmFw-h3frhBtDB3Y:-NtIOmFw-h3frhBtDB3Z:b-vndm4e) ([raw file](https://github.com/google/nomulus/blob/10155fa0c791d56c1d595c379a52a234a9017df2/console-webapp/src/app/registrar/registrarDetails.component.html#L97)):*
> ```HTML
>       </mat-card-content>
>     </mat-card>
>     } }
> ```

weird, shouldn't this be formatted away? 
___
*[`console-webapp/src/app/registrar/registrarSelector.component.html` line 23 at r8](https://reviewable.io/reviews/google/nomulus/2336#-NsjSZAmE1prFY5osEQw:-NtINl-n6tpvlZPDfmon:bduginb) ([raw file](https://github.com/google/nomulus/blob/52fddfef4df3b3c162ebca7c7b2dbf4d748b28db/console-webapp/src/app/registrar/registrarSelector.component.html#L23)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

No, it's in effect, which supposed to be placed in the constructor, see https://angular.io/guide/signals - "The easiest way to provide this is to call effect within a component, directive, or service constructor"
</blockquote></details>

Right yeah I must have missed the effect call. 


<!-- Sent from Reviewable.io -->

2024-03-19 20:45 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: all files reviewed, 19 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`console-webapp/src/app/billingInfo/billingInfo.component.html` line 8 at r18](https://reviewable.io/reviews/google/nomulus/2336#gh-1529211516:-NtNDJGo6tT0VTJEqLfn:b6ujch) ([raw file](https://github.com/google/nomulus/blob/10155fa0c791d56c1d595c379a52a234a9017df2/console-webapp/src/app/billingInfo/billingInfo.component.html#L8)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Potentially unsafe external link

External links without noopener/noreferrer are a potential security risk.

[Show more details](https://github.com/google/nomulus/security/code-scanning/4030)
</blockquote></details>

Not applicable
___
*[`console-webapp/src/app/registrar/registrarDetails.component.html` line 97 at r18](https://reviewable.io/reviews/google/nomulus/2336#-NtIOmFw-h3frhBtDB3Y:-NtNDTJJ1RiL5BMfLb31:b-3hoyjj) ([raw file](https://github.com/google/nomulus/blob/10155fa0c791d56c1d595c379a52a234a9017df2/console-webapp/src/app/registrar/registrarDetails.component.html#L97)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

weird, shouldn't this be formatted away?
</blockquote></details>

I don't think prettier catching up with latest angular template syntax very well, but it soon will, so we will have to wait a little
___
*[`console-webapp/src/app/registrar/registrarDetails.component.scss` line 1 at r10](https://reviewable.io/reviews/google/nomulus/2336#-NsyE008DrD684_fwHeh:-NtNDbf42f_kQffCixoH:b-n7tq93) ([raw file](https://github.com/google/nomulus/blob/b77d28e81684181b5294608ec9392d3b95e605a7/console-webapp/src/app/registrar/registrarDetails.component.scss#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

small note, not sure if we want to fix it, but the list-of-TLDs element has the text wrapping oddly on to the next line if it's long
</blockquote></details>

Yeah it was on my radar. Should be fixed now
___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 142 at r16](https://reviewable.io/reviews/google/nomulus/2336#-Nt27R2NBN4Hwie0mQl7:-NtNMt0-6QFGldwYVhT3:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/8660c88171092d60f480d72b1e0c141a283fc53d/console-webapp/src/app/settings/whois/whois.component.html#L142)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Is it necessary to have two large blocks of code for the in-edit and not-in-edit modes? I would hope we could just have a toggle class or something.
</blockquote></details>

Updated
___
*[`console-webapp/src/app/support/support.component.html` line 9 at r6](https://reviewable.io/reviews/google/nomulus/2336#-NsPhBUbBZzdC6-3Z1PV:-NtNSF7I3kYQ499r-gdo:bvk4y90) ([raw file](https://github.com/google/nomulus/blob/f4c3b3946bf7474414ee0aa8c9601cde680e2e6a/console-webapp/src/app/support/support.component.html#L9)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we probably only want to list the email address once, I think?
</blockquote></details>

Not sure I follow your comment. it's got 2 email in the design 
___
*[`console-webapp/src/app/support/support.component.html` line 14 at r15](https://reviewable.io/reviews/google/nomulus/2336#-Nt1lgV6EpZzoUqcqJ6d:-NtNSNBc-kN3V2QXdspr:bg4xwlu) ([raw file](https://github.com/google/nomulus/blob/b0e9d30ab48da27fa55b0648508560c0e7723b4f/console-webapp/src/app/support/support.component.html#L14)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we still want the support email here right?
</blockquote></details>

It needs to be exposed via back-end


<!-- Sent from Reviewable.io -->

2024-03-20 15:13 UTC, gbrodman requested changes
> Reviewed 15 of 15 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: all files reviewed, 16 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/support/support.component.html` line 9 at r6](https://reviewable.io/reviews/google/nomulus/2336#-NsPhBUbBZzdC6-3Z1PV:-NtNXO2WBr3v_BgUuh7N:b-hqob70) ([raw file](https://github.com/google/nomulus/blob/f4c3b3946bf7474414ee0aa8c9601cde680e2e6a/console-webapp/src/app/support/support.component.html#L9)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Not sure I follow your comment. it's got 2 email in the design
</blockquote></details>

Won't they (eventually) be the same email address, meaning the support email address? 
___
*[`console-webapp/src/app/support/support.component.html` line 14 at r15](https://reviewable.io/reviews/google/nomulus/2336#-Nt1lgV6EpZzoUqcqJ6d:-NtNX7yZ5jXYmHO-8MJ7:b8z5cq0) ([raw file](https://github.com/google/nomulus/blob/b0e9d30ab48da27fa55b0648508560c0e7723b4f/console-webapp/src/app/support/support.component.html#L14)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

It needs to be exposed via back-end
</blockquote></details>

Isn't it already via ConsoleUserDataAction? 


<!-- Sent from Reviewable.io -->

2024-03-20 19:38 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: all files reviewed, 14 unresolved discussions (waiting on @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-03-20 20:05 UTC, gbrodman approved these changes
> Reviewed 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: all files reviewed, 14 unresolved discussions (waiting on @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-03-21 19:52 UTC, gbrodman approved these changes
> Reviewed 7 of 7 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2336)* status: all files reviewed, 14 unresolved discussions (waiting on @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-03-22 00:37 UTC, merged