Add nomulus deployment and service manifests
google/nomulus pull request #2389
Opened 2024-03-26 17:27 UTC by jianglai

2024-03-28 18:11 UTC, jianglai reviewed
> Reviewed 15 of 16 files at r1, 4 of 4 files at r2, 2 of 4 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2389)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)



<!-- Sent from Reviewable.io -->

2024-03-29 18:11 UTC, ptkach requested changes
See, I knew we could get rid of 2 deployments. This is now a lot better than over-the-wire requests. 
I think it's even possible to have a separate service for whois and epp traffic within nomulus and get rid of proxy image altogether, but that now is already a pretty great state. 

> Reviewed 7 of 16 files at r1, 2 of 4 files at r2, 2 of 4 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2389#-:-NuAJk6a8CnoTlmAJTE0:b6vm63v)* status: all files reviewed, 5 unresolved discussions (waiting on @jianglai)

___
*[`jetty/build.gradle` line 80 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAGzB_68IQUkuT3ebs:-NuAGzB_68IQUkuT3ebt:b-2ifrwe) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/jetty/build.gradle#L80)):*
> ```Gradle
>         }
>         exec {
>             commandLine './deploy-nomulus-for-env.sh', "${rootProject.environment}"
> ```

Given that `deploy-nomulus-for-env.sh` does deployment for both nomulus and proxy container I'd naturally expect that proxy container would be updated here as well.
___
*[`jetty/deploy-nomulus-for-env.sh` line 21 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAP3VM03lzwd9ip1d_:-NuAP3VM03lzwd9ip1da:btnw0co) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/jetty/deploy-nomulus-for-env.sh#L21)):*
> ```Shell
> 
> if [[ $# -ne 1 ]]; then
>   echo "Usage: $0 alpha|crash|qa"
> ```

I think we might want to add a check to prevent the use with any other env
___
*[`jetty/kubernetes/nomulus-deployment.yaml` line 35 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAHtFvCYmwGTykdzgh:-NuAHtFvCYmwGTykdzgi:b7j144f) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/jetty/kubernetes/nomulus-deployment.yaml#L35)):*
> ```YAML
>         resources:
>           requests:
>             cpu: "500m"
> ```

Minor but I imagine proxy needs less resources than nomulus
___
*[`jetty/kubernetes/nomulus-gateway.yaml` line 1 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAInU67pYwJj-9rqEc:-NuAInU67pYwJj-9rqEd:b-kgsg5b) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/jetty/kubernetes/nomulus-gateway.yaml#L1)):*
> ```YAML
> kind: Gateway
> ```

Neat! I didn't know gateway is not a successor to ingress. My first thought was - why I don't see ingress config here in this PR hehe 
___
*[`proxy/src/main/java/google/registry/proxy/ProxyModule.java` line 95 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAJVWe44XJ6QWcRdIP:-NuAJVWe44XJ6QWcRdIQ:bcicexd) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/proxy/src/main/java/google/registry/proxy/ProxyModule.java#L95)):*
> ```Java
>   private Integer httpsWhoisPort;
> 
>   @Parameter(
> ```

I'm assuming this is temporary until migration is done. If so I'd add a TODO to remove it


<!-- Sent from Reviewable.io -->

2024-04-09 19:01 UTC, jianglai reviewed
Getting rid of the proxy requires complete re-architecturing of Nomulus itself, as EPP/WHOIS are non-HTTP protocols. I think combining the proxy and the Nomulus HTTP server in the same pod is the best we can do without re-writing most of our stack, unfortunately.

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2389#-:-NuU8Hh63P6oYktIwpsV:blulflo)* status: all files reviewed, 5 unresolved discussions (waiting on @ptkach)

___
*[`jetty/build.gradle` line 80 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAGzB_68IQUkuT3ebs:-NuU926W5grXCdC-q2UK:b-7rpo3m) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/jetty/build.gradle#L80)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Given that `deploy-nomulus-for-env.sh` does deployment for both nomulus and proxy container I'd naturally expect that proxy container would be updated here as well.
</blockquote></details>

Good point. I haven't tested this task thoroughly, though. Most of the testing is done directly on minikube using `kubectl`.
___
*[`jetty/deploy-nomulus-for-env.sh` line 21 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAP3VM03lzwd9ip1d_:-Nv34YbL6Pmj80f1j9NI:b-hty8ph) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/jetty/deploy-nomulus-for-env.sh#L21)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I think we might want to add a check to prevent the use with any other env
</blockquote></details>

The check is done in [`verifyDeploymentConfig`](https://cs.opensource.google/nomulus/nomulus/+/master:build.gradle;l=143?q=verifydeploymentconfig&ss=nomulus%2Fnomulus), before the script is called by `deployNomulus`.

There's value in leaving the script itself flexible enough to deploy to sandbox/prod in case of need.
___
*[`jetty/kubernetes/nomulus-deployment.yaml` line 35 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAHtFvCYmwGTykdzgh:-Nv358BoBLHHPyeCqQ3U:bam3uuv) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/jetty/kubernetes/nomulus-deployment.yaml#L35)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Minor but I imagine proxy needs less resources than nomulus
</blockquote></details>

Yes, the parameters here need some fine tuning. In this PR I'm only focused on getting things to work.
___
*[`jetty/kubernetes/nomulus-gateway.yaml` line 1 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAInU67pYwJj-9rqEc:-Nv35IqtEg3cfbfgS7Xc:b1qsbod) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/jetty/kubernetes/nomulus-gateway.yaml#L1)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Neat! I didn't know gateway is not a successor to ingress. My first thought was - why I don't see ingress config here in this PR hehe
</blockquote></details>

Ingress is ["frozen"](https://kubernetes.io/docs/concepts/services-networking/ingress/) and gateway is supposed to be its successor. Typical "let's redo everything from scratch because what we have is not perfect" approach...
___
*[`proxy/src/main/java/google/registry/proxy/ProxyModule.java` line 95 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAJVWe44XJ6QWcRdIP:-Nv35hkG4aXsZQc2R9db:bd0zmud) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/proxy/src/main/java/google/registry/proxy/ProxyModule.java#L95)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I'm assuming this is temporary until migration is done. If so I'd add a TODO to remove it
</blockquote></details>

I'm not sure. Maybe we do want to preserve the ability to run the proxy in either mode. Or put it another way, there doesn't seem to be any runtime benefit to remove the ability to run the proxy in its original "remote" mode.


<!-- Sent from Reviewable.io -->

2024-04-11 14:28 UTC, jianglai commented
Gentle ping.

2024-04-11 18:36 UTC, ptkach approved these changes
> Reviewed 1 of 4 files at r2, 1 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2389)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`jetty/kubernetes/nomulus-gateway.yaml` line 1 at r7](https://reviewable.io/reviews/google/nomulus/2389#-NuAInU67pYwJj-9rqEc:-NvDRW8VEnBDypJm4hGx:b4t9yff) ([raw file](https://github.com/google/nomulus/blob/d79c160db3b4e571310c23decc44a6ae1fe1a562/jetty/kubernetes/nomulus-gateway.yaml#L1)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ingress is ["frozen"](https://kubernetes.io/docs/concepts/services-networking/ingress/) and gateway is supposed to be its successor. Typical "let's redo everything from scratch because what we have is not perfect" approach...
</blockquote></details>

yeah, certainly looks like it


<!-- Sent from Reviewable.io -->

2024-04-11 19:55 UTC, merged