Add console DUM download
google/nomulus pull request #2402
Opened 2024-04-16 15:19 UTC by ptkach

2024-04-22 17:13 UTC, ptkach reviewed
@gbrodman This one is ready

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2402#-:-Nw5myce1QrR3w6-Xi7F:b-ri0lim)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2024-04-24 19:08 UTC, gbrodman requested changes
> Reviewed 3 of 9 files at r1, 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2402)* status: all files reviewed, 11 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/domains/domainList.component.html` line 19 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGTp_r2ZtEcK1xseMy:-NwGTp_r2ZtEcK1xseMz:b-13pdr2) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/console-webapp/src/app/domains/domainList.component.html#L19)):*
> ```HTML
>       mat-stroked-button
>       color="primary"
>       href="/console-api/dum-download?registrarId={{
> ```

Just checking, does this work the way that I'd expect (where it just downloads the file)? I know sometimes broswers can be weird about downloading the file vs opening it in a window 
___
*[`core/src/main/java/google/registry/module/RequestComponent.java` line 193 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGT2AnA1Q8vm8O0NM1:-NwGT2AnA1Q8vm8O0NM2:b2ta63k) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/module/RequestComponent.java#L193)):*
> ```Java
>   ConsoleUserDataAction consoleUserDataAction();
> 
>   ConsoleDUMDownloadAction consoleDUMDownloadAction();
> ```

this is a bit nitty, but the style guide treats abbreviations as if they were just a standard word, e.g. GenericXmlSyntaxException 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 84 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUUD72CpMRNzxMrgH:-NwGUUD72CpMRNzxMrgI:bvvb7rl) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L84)):*
> ```Java
>     consoleApiParams
>         .response()
>         .setHeader("Content-Disposition", "attachment; filename=Google_Registry_DUMS.csv");
> ```

in case we have support agents doing this across multiple registrars, we should include the registrar name (and possibly the date?) in the file I think
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 91 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUcG84xvN9_lf0zGL:-NwGUcG84xvN9_lf0zGM:b-ohk09h) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L91)):*
> ```Java
>         .response()
>         .setDateHeader(
>             "Expires", DateTime.now(UTC).withTimeAtStartOfDay().plusDays(1).withTimeAtStartOfDay());
> ```

i don't think we need the multiple calls to withTimeAtStartOfDay?
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 101 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUDG03v2qzljhIt5u:-NwGUDG03v2qzljhIt5v:bk7f1fq) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L101)):*
> ```Java
>       logger.atWarning().withCause(e).log(
>           String.format("Failed to create DUM csv for %s", registrarId));
>       if (writer != null) {
> ```

it should be not super difficult to use a try-with-resources to auto-close the writer no matter what 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 116 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUj591Vq8W6AJkwEw:-NwGUj591Vq8W6AJkwEx:b2o9z6b) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L116)):*
> ```Java
>     String sql =
>         SQL_TEMPLATE
>             .replace(":registrarId", registrarId)
> ```

Use the entity manager's variable replacement instead of this to avoid possible weird things happening (we've already verified that they have the permission so we shouldn't have a weird registrar name, but just in case) 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 130 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUxbC1ZAPg5d47o3R:-NwGUxbC1ZAPg5d47o3S:bsb09ux) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L130)):*
> ```Java
> 
>     ImmutableList<String[]> formattedRecords =
>         queryResult.stream().map(r -> r.split(",")).collect(toImmutableList());
> ```

Have you tested the performance of the entity manager's `getResultStream` vs `getResultList`? An alternative to this code would be using the result stream. This would mean we'd be constructing one fewer giant list, but we'd have to do this stream / map (formatting) inside the transaction 
___
*[`core/src/test/java/google/registry/testing/FakeResponse.java` line 45 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGTfK48PAq6gzTaeOZ:-NwGTfK48PAq6gzTaeO_:b-r09rk4) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/test/java/google/registry/testing/FakeResponse.java#L45)):*
> ```Java
>   private String lastResponseStackTrace;
> 
>   public final StringWriter writer = new StringWriter();
> ```

these can be private like the others, just using the getter?
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java` line 85 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGVRw-0r0SlRmduJr3:-NwGVRw-0r0SlRmduJr4:b-k5kgnq) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java#L85)):*
> ```Java
>     FakeResponse response = (FakeResponse) consoleApiParams.response();
>     assertThat(response.getStatus()).isEqualTo(HttpStatusCodes.STATUS_CODE_OK);
>     ImmutableList<String> actual = ImmutableList.copyOf(response.writer.toString().split("\r\n"));
> ```

hold up, \r\n? that seems wrong, we probably want just \n 
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java` line 104 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGVXba-TV56H8HFa-7:-NwGVXba-TV56H8HFa-8:b-8hvhqd) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java#L104)):*
> ```Java
>   }
> 
>   ConsoleDUMDownloadAction createAction(Optional<AuthResult> maybeAuthResult) {
> ```

nit, this method can be private


<!-- Sent from Reviewable.io -->

2024-04-25 17:22 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2402)* status: 5 of 12 files reviewed, 10 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`console-webapp/src/app/domains/domainList.component.html` line 19 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGTp_r2ZtEcK1xseMy:-NwKcZfX209ALZQMq4Na:b-x61h7u) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/console-webapp/src/app/domains/domainList.component.html#L19)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Just checking, does this work the way that I'd expect (where it just downloads the file)? I know sometimes broswers can be weird about downloading the file vs opening it in a window
</blockquote></details>

Yes, just click the link get the file
___
*[`core/src/main/java/google/registry/module/RequestComponent.java` line 193 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGT2AnA1Q8vm8O0NM1:-NwKf1YYARICwh9cPB9s:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/module/RequestComponent.java#L193)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this is a bit nitty, but the style guide treats abbreviations as if they were just a standard word, e.g. GenericXmlSyntaxException
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/testing/FakeResponse.java` line 45 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGTfK48PAq6gzTaeOZ:-NwKqFXO9pxh4tqhvQZQ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/test/java/google/registry/testing/FakeResponse.java#L45)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

these can be private like the others, just using the getter?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 84 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUUD72CpMRNzxMrgH:-NwKiSMt5SuQc5Y_K3GB:bdcix65) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L84)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

in case we have support agents doing this across multiple registrars, we should include the registrar name (and possibly the date?) in the file I think
</blockquote></details>

I've considered it, but decided against for multiple reasons: 
- I think the target audience for this feature is actually registrars, not the agents. Having this ability to download DUMs in the console without reaching out to registry tech support is what we are aiming for here for partners. 
- Performance-wise registrar name in the file will require a call to DB. This seems like something we probably want to avoid in otherwise "heavy" pathway.
- My understanding is that this is not to be used frequently by registrars, like monthly or so, so date can be omitted based on that
- Name is quite long as it is, not sure adding more text to it would make it more user friendly
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 91 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUcG84xvN9_lf0zGL:-NwKjuym8is0-SWIcNRD:b-urk3pb) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L91)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i don't think we need the multiple calls to withTimeAtStartOfDay?
</blockquote></details>

Oops, not sure how did it end up there twice :)
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 101 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUDG03v2qzljhIt5u:-NwKnOSb6-CV9jDpIESA:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L101)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it should be not super difficult to use a try-with-resources to auto-close the writer no matter what
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 116 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUj591Vq8W6AJkwEw:-NwKnPdMD4oVvJNRIw4d:b-b16qe2) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L116)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Use the entity manager's variable replacement instead of this to avoid possible weird things happening (we've already verified that they have the permission so we shouldn't have a weird registrar name, but just in case)
</blockquote></details>

Updated to setParameter. For my understanding - what weird things have you anticipated? 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 130 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUxbC1ZAPg5d47o3R:-NwKpNGUA62c1-gciIMZ:b2pfao5) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L130)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Have you tested the performance of the entity manager's `getResultStream` vs `getResultList`? An alternative to this code would be using the result stream. This would mean we'd be constructing one fewer giant list, but we'd have to do this stream / map (formatting) inside the transaction
</blockquote></details>

yes, `getResultStream` was my first attempt at it, but this currently is the most performant solution. 
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java` line 29 at r2](https://reviewable.io/reviews/google/nomulus/2402#gh-1575224176:-NwLH-1h5_zWnqifDGzk:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6afbf66a36c8ff831c8806de9dc73290d0fc51fc/core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java#L29)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: ConsoleDUMDownloadActionTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/7327)
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java` line 85 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGVRw-0r0SlRmduJr3:-NwKzbRz45QR0Er-Il2C:b-2xr00l) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java#L85)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

hold up, \r\n? that seems wrong, we probably want just \n
</blockquote></details>

Can you elaborate on why is it wrong? This is a default CSV format used by Writer based on the https://www.ietf.org/rfc/rfc4180.txt 


<!-- Sent from Reviewable.io -->

2024-04-25 18:17 UTC, gbrodman requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2402)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 84 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUUD72CpMRNzxMrgH:-NwLR5Js8t4nx2dyeWNn:b-vmwiom) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L84)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I've considered it, but decided against for multiple reasons: 
- I think the target audience for this feature is actually registrars, not the agents. Having this ability to download DUMs in the console without reaching out to registry tech support is what we are aiming for here for partners. 
- Performance-wise registrar name in the file will require a call to DB. This seems like something we probably want to avoid in otherwise "heavy" pathway.
- My understanding is that this is not to be used frequently by registrars, like monthly or so, so date can be omitted based on that
- Name is quite long as it is, not sure adding more text to it would make it more user friendly
</blockquote></details>

Those are fair (though I will note that #2 is not true since the registrar ID is passed in, but that's moot)

One thing I will note is that we probably shouldn't hardcode Google Registry but rather we should use config.registryPolicy.productName in some way
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 116 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUj591Vq8W6AJkwEw:-NwLL6IR4VYgvE3q4ShO:buvpit1) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L116)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Updated to setParameter. For my understanding - what weird things have you anticipated?
</blockquote></details>

Mainly just worried about SQL injection. Like I said that wouldn't be a huge issue as the code is currently structured since we verify the registrar first, but it seems like good practice regardless 
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java` line 85 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGVRw-0r0SlRmduJr3:-NwLLqix2fZuo3G-B5S-:b-6tdkl8) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/test/java/google/registry/ui/server/console/ConsoleDUMDownloadActionTest.java#L85)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Can you elaborate on why is it wrong? This is a default CSV format used by Writer based on the https://www.ietf.org/rfc/rfc4180.txt
</blockquote></details>

oh dang I didn't know it was standard, I just assumed that we'd want to use only \n due to linux/osx standards. 


<!-- Sent from Reviewable.io -->

2024-04-25 18:19 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2402)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 84 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUUD72CpMRNzxMrgH:-NwLTtEK5HQ65AFQFxQA:bkj5yq2) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L84)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Those are fair (though I will note that #2 is not true since the registrar ID is passed in, but that's moot)

One thing I will note is that we probably shouldn't hardcode Google Registry but rather we should use config.registryPolicy.productName in some way
</blockquote></details>

not sure what happened with that link, but i was referring to point number 2


<!-- Sent from Reviewable.io -->

2024-04-25 19:37 UTC, ptkach reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2402)* status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java` line 84 at r3](https://reviewable.io/reviews/google/nomulus/2402#-NwGUUD72CpMRNzxMrgH:-NwLkUOy4iJI0_8C7YOD:b4kkxny) ([raw file](https://github.com/google/nomulus/blob/e31bc4f873776c131a3b69d29c75e03c3a66c280/core/src/main/java/google/registry/ui/server/console/ConsoleDUMDownloadAction.java#L84)):*
Added the name to the config. 
> is not true since the registrar ID is passed in, but that's moot)
Well registrarId indeed is passed in the params, but registrar name isn't, getting the name would require a DB call 
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleDumDownloadActionTest.java` line 44 at r4](https://reviewable.io/reviews/google/nomulus/2402#gh-1579874296:-NwLkuoNBGsKX0TuQL-x:b-896fix) ([raw file](https://github.com/google/nomulus/blob/be05196e56086a215418ae93bb81628554ac2c22/core/src/test/java/google/registry/ui/server/console/ConsoleDumDownloadActionTest.java#L44)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: ConsoleDumDownloadActionTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/7861)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-26 15:42 UTC, gbrodman approved these changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2402)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-04-26 16:53 UTC, merged