Add the ability to add/remove console users from a Google Group
google/nomulus pull request #2450
Opened 2024-05-22 14:03 UTC by jianglai

2024-05-22 14:53 UTC, jianglai reviewed
> Reviewed 20 of 20 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2450)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/test/java/google/registry/tools/server/UpdateUserGroupActionTest.java` line 35 at r1](https://reviewable.io/reviews/google/nomulus/2450#gh-1610063866:-NyVeW605ujESPpRg_7e:b-9j5dzw) ([raw file](https://github.com/google/nomulus/blob/1e59b109f06c4b5c1a9b3dddf27c9acb34ea1168/core/src/test/java/google/registry/tools/server/UpdateUserGroupActionTest.java#L35)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: UpdateUserGroupActionTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/9047)
</blockquote></details>

False positive. This is a test class.


<!-- Sent from Reviewable.io -->

2024-05-22 17:57 UTC, ptkach requested changes
> Reviewed 5 of 20 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2450)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

___
*[`core/src/main/java/google/registry/tools/CreateUserCommand.java` line 56 at r4](https://reviewable.io/reviews/google/nomulus/2450#-NyWQ_z--YHSYX7CLfBH:-NyWQ_z--YHSYX7CLfBI:baumrqg) ([raw file](https://github.com/google/nomulus/blob/0c04d13303b2b8800cd32bce6a504d3572935838/core/src/main/java/google/registry/tools/CreateUserCommand.java#L56)):*
> ```Java
>   protected String execute() throws Exception {
>     String ret = super.execute();
>     if (maybeGroupEmailAddress.isPresent()) {
> ```

An assumption is made here that when group email is present we always add to the group, this locks us into this assumption. I'm guessing this might be confusing for someone not familiar with what we're trying to achieve and why, like when group is present or when it's missing, etc. 
Would it make more sense to expand the command and tools with param that would accept the groupname to add to? I'm thinking this might make things more straighforward and clear


<!-- Sent from Reviewable.io -->

2024-05-22 18:40 UTC, jianglai reviewed
> Reviewed 6 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2450)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/tools/CreateUserCommand.java` line 56 at r4](https://reviewable.io/reviews/google/nomulus/2450#-NyWQ_z--YHSYX7CLfBH:-NyW_k2p0mR9i7Xsvq3g:bc9xbhn) ([raw file](https://github.com/google/nomulus/blob/0c04d13303b2b8800cd32bce6a504d3572935838/core/src/main/java/google/registry/tools/CreateUserCommand.java#L56)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

An assumption is made here that when group email is present we always add to the group, this locks us into this assumption. I'm guessing this might be confusing for someone not familiar with what we're trying to achieve and why, like when group is present or when it's missing, etc. 
Would it make more sense to expand the command and tools with param that would accept the groupname to add to? I'm thinking this might make things more straighforward and clear
</blockquote></details>

The behavior is well documented in `default-config.yaml`. I don't think we want to make it possible to specify an arbitrary group email address on the command line, as that should be part of the configuration that is under version control.

I do think it make sense to send the group as an argument to the backend so the backend doesn't rely on hard-coded group email addresses.


<!-- Sent from Reviewable.io -->

2024-05-22 20:29 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2450)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)



<!-- Sent from Reviewable.io -->

2024-05-28 14:57 UTC, ptkach reviewed
Looking at the IAP ticket that's been bouncing around I'm not 100% that this approach will get to fly. Thus I'm waiting for the to approve the change first. Otherwise we will go with `allAuthorized` approach and that will make this PR obsolete
 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2450#-:-NyzgtCiEnNeKJQJQtu-:bwcncz8)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)



<!-- Sent from Reviewable.io -->

2024-05-28 17:00 UTC, ptkach approved these changes
> Reviewed 6 of 20 files at r1, 6 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2450)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-05-28 18:10 UTC, merged