Make registrant nullable on domains
google/nomulus pull request #2477
Opened 2024-06-11 21:53 UTC by CydeWeys

This is the first step in migrating to the minimum registration data set. Note that our database model already permits null domain registrants, so this just makes the code accept it as well. Note that I haven't changed any requirements in EPP flows yet; a later step will be to check the migration schedule and then not require the registrant to be present if in a suitable state.

This does potentially affect the output of WHOIS/RDAP, but that's a NOOP so long as EPP commands and other tools continue to enforce the requirement of a registrant.

2024-06-12 19:43 UTC, CydeWeys reviewed
+reviewer:@sarahcaseybot 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2477#-:-O-CySWy857PnfV0lX9Z:b-ar4bh4)* status: 0 of 32 files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2024-06-13 20:01 UTC, gbrodman requested changes
> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2477)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java` line 281 at r1](https://reviewable.io/reviews/google/nomulus/2477#-O-ERqPn6ybOGagPH2r0:-O-HpiBP76_ulUlv8Rp7:bpagedw) ([raw file](https://github.com/google/nomulus/blob/57bba162f2ec088545cf68d6dface95fac414bcb/core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java#L281)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I'm not totally familiar with how Optional.or() works. If the change.getRegistrant returns an Optional<null>, will it set the registrant to null, or will it treat it the same as an empty optional and set the registrant to whatever the domain's registrant is? Maybe a test should be added for this
</blockquote></details>

`or` returns an Optional, that is either `this` if the value is present, or else the Optional returned by the supplier 
___
*[`core/src/test/resources/google/registry/whois/whois_domain_no_registrant.txt` line 1 at r1](https://reviewable.io/reviews/google/nomulus/2477#-O-HvRSrEM7cisM7xsWt:-O-HvRSrEM7cisM7xsWu:bllc0r4) ([raw file](https://github.com/google/nomulus/blob/57bba162f2ec088545cf68d6dface95fac414bcb/core/src/test/resources/google/registry/whois/whois_domain_no_registrant.txt#L1)):*
> ```help
> Domain Name: example.tld
> ```

is this file used anywhere? I don't see whois_domain_no_registrant appearing anywhere else 


<!-- Sent from Reviewable.io -->

2024-06-13 23:21 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2477)* status: all files reviewed, 5 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java` line 281 at r1](https://reviewable.io/reviews/google/nomulus/2477#-O-ERqPn6ybOGagPH2r0:-O-ItZhV1c8KsNGd5k_W:b-iergc3) ([raw file](https://github.com/google/nomulus/blob/57bba162f2ec088545cf68d6dface95fac414bcb/core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java#L281)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Ok. I'm realizing now there isn't a way for partners to remove a contact from a domain once a domain is created with a contact on it. I suppose that is fine for now, but I'm curious if that is something they will want in the future as we get closer to phase 2.
</blockquote></details>

Once we allow domains to not have contacts on them after August, registrars can send a `domain:update` command that removes the contacts.  That looks like this:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/resources/google/registry/flows/domain/domain_update_remove_contact.xml;l=15-21;drc=cf507dad6d7bfc9e30eb520da0c08a75d054b2bd    (note that it removes an existing contact without replacing it with a new one.)

And contacts themselves can be deleted with: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/flows/contact/ContactDeleteFlow.java


<!-- Sent from Reviewable.io -->

2024-06-13 23:22 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2477)* status: all files reviewed, 5 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/domain/DomainBase.java` line 587 at r1](https://reviewable.io/reviews/google/nomulus/2477#-O-EUvig9dtRXreBpMvn:-O-Iu1nN5LTw4CGJxVF7:bc1g3y0) ([raw file](https://github.com/google/nomulus/blob/57bba162f2ec088545cf68d6dface95fac414bcb/core/src/main/java/google/registry/model/domain/DomainBase.java#L587)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

We should probably add some sort of note or annotation here to indicate that this field will eventually be removed as part of the minimum registry dataset
</blockquote></details>

It won't necessarily be removed.  We might want Nomulus to remain compatible with thick registries (e.g. for the ccTLD use case), in which case we might never remove it.  So it's far from a done deal that it will ever be removed.  What we do know is that, come August 2025, we will set the configuration for our own running system so that contacts are no longer accepted on EPP commands (which is a separate issue from whether the codebase can support it at all).


<!-- Sent from Reviewable.io -->

2024-06-13 23:23 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2477)* status: all files reviewed, 5 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/test/java/google/registry/testing/DatabaseHelper.java` line 193 at r1](https://reviewable.io/reviews/google/nomulus/2477#-O-IG6ix5AWMfHMiJ0G9:-O-IuKSR0IVxqojfxVoy:bae4dnq) ([raw file](https://github.com/google/nomulus/blob/57bba162f2ec088545cf68d6dface95fac414bcb/core/src/test/java/google/registry/testing/DatabaseHelper.java#L193)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Doesn't need to be in this PR, but we should either change this method, or add an additional `newDomainNoContact` method to database helper that does not set a registrant (or later any of the contacts) and try to migrate most tests to using that method.
</blockquote></details>

We'll do that later.  For now, and possibly until right before August 2025, it's likely to be the default behavior in our actual running system that contacts will be included by many people.


<!-- Sent from Reviewable.io -->

2024-06-14 16:06 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2477)* status: 31 of 32 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/test/java/google/registry/whois/DomainWhoisResponseTest.java` line 304 at r1](https://reviewable.io/reviews/google/nomulus/2477#-O-IHYHl5Q5uq-aN7q21:-O-MUmAs7jc8ikfvohDb:b495d8k) ([raw file](https://github.com/google/nomulus/blob/57bba162f2ec088545cf68d6dface95fac414bcb/core/src/test/java/google/registry/whois/DomainWhoisResponseTest.java#L304)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Shouldn't this have a different response?
</blockquote></details>

Yeah this meant to use the no_registrant file you flagged below, but I forgot to append that filename when copy-pasting and also because it was taking the passed in object rather than loading it from the DB, it wasn't actually using something with no registrant present.  Fixed on all counts.
___
*[`core/src/test/resources/google/registry/whois/whois_domain_no_registrant.txt` line 1 at r1](https://reviewable.io/reviews/google/nomulus/2477#-O-HvRSrEM7cisM7xsWt:-O-MUlH92-PRf0R7nw0G:bt2vr1b) ([raw file](https://github.com/google/nomulus/blob/57bba162f2ec088545cf68d6dface95fac414bcb/core/src/test/resources/google/registry/whois/whois_domain_no_registrant.txt#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

is this file used anywhere? I don't see whois_domain_no_registrant appearing anywhere else
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2024-06-14 16:06 UTC, CydeWeys reviewed
PTAL

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2477#-:-O-MUxHk1Xpr-shGKh29:bb71pro)* status: 31 of 32 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2024-06-14 17:08 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2477)* status: all files reviewed, 4 unresolved discussions (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2024-06-14 17:35 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2477)* status: all files reviewed, 3 unresolved discussions (waiting on @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java` line 281 at r1](https://reviewable.io/reviews/google/nomulus/2477#-O-ERqPn6ybOGagPH2r0:-O-MnVHI-cKJvmHf546y:bt6vtfn) ([raw file](https://github.com/google/nomulus/blob/57bba162f2ec088545cf68d6dface95fac414bcb/core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java#L281)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Right, we will still have to make modifications to this though since that does not work for removing a registrant contact since they are treated differently than the other contacts. https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/domain/DomainCommand.java;l=354;drc=d000a5dff891601b805c1909949d98624ca95555
</blockquote></details>

That works pretty much exactly the same way in `domain:update` though.  It would look like:

```
<domain:rem>
    <domain:registrant>sh8013</domain:registrant>
</domain:rem>
```

There are `add`, `chg`, and `rem` actions for every field in `domain:update`, and if you send a `rem` that removes it. 
___
*[`core/src/main/java/google/registry/model/domain/DomainBase.java` line 587 at r1](https://reviewable.io/reviews/google/nomulus/2477#-O-EUvig9dtRXreBpMvn:-O-MnqbW-5E_l1xBVmiZ:b-1v4hms) ([raw file](https://github.com/google/nomulus/blob/57bba162f2ec088545cf68d6dface95fac414bcb/core/src/main/java/google/registry/model/domain/DomainBase.java#L587)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Hmm, ok. I still think we need to have some sort of indication though on what fields are and are not being used. Perhaps an annotation on fields that will only be used by thick registries so someone can easily tell when reading the code which fields are negligible to our Google usecase.
</blockquote></details>

We can come up with a comprehensive plan for how to tackle that later.  We haven't even necessarily made the decision to continue supporting thick registries at all.  But it won't be that complicated -- it's simply these two fields (registrant and contacts) on Domain that are either allowed to be empty, or aren't.


<!-- Sent from Reviewable.io -->

2024-06-17 21:54 UTC, CydeWeys commented
Looks like it needs another LGTM because of a last minute change.

2024-06-20 16:19 UTC, merged