Create Users when setting up OT&E and Production registrars
google/nomulus pull request #2488
Opened 2024-06-28 22:32 UTC by jianglai

2024-07-01 13:15 UTC, jianglai reviewed
> Reviewed 24 of 24 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2488)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2024-07-02 18:25 UTC, gbrodman requested changes
> Reviewed 18 of 24 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2488)* status: all files reviewed, 6 unresolved discussions (waiting on @jianglai and @ptkach)

___
*[`core/src/main/java/google/registry/model/OteAccountBuilder.java` line 270 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kFlt87WrGgrADDT50:-O0kFlt87WrGgrADDT51:b-dat64j) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/model/OteAccountBuilder.java#L270)):*
> ```Java
> 
>   /** Grants the users permission to pass IAP. */
>   public void grantIapPermission(
> ```

Doesn't seem like this is used anywhere other than the exact same places where buildAndPersist is called. I don't think they need to be separate? 
___
*[`core/src/main/java/google/registry/model/OteAccountBuilder.java` line 323 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kGE9AB-2Ji4wwmhgc:-O0kGE9B3AYfjJUGcSpR:b-59ybsk) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/model/OteAccountBuilder.java#L323)):*
> ```Java
>       String email = user.getEmailAddress();
>       if (existingUsers.containsKey(email)) {
>         // Note that other roles for the existing user are reset. We do this instead of simply
> ```

this is gross and maybe something we'll want to change in the future? I think previously we didn't want to use the email address as the primary key because we thought it might be mutable, but given that it's immutable, it should probably be the pkey...
___
*[`core/src/main/java/google/registry/model/console/UserBase.java` line 146 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kBHkE9NuataXay137:-O0kBHkE9NuataXay138:b4mwyjo) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/model/console/UserBase.java#L146)):*
> ```Java
>         .anyMatch(role -> role.hasPermission(ConsolePermission.REGISTRY_LOCK));
>   }
> ```

Thoughts on putting these in the subclass (`User`)? There's less going on there I think, and it's what we're referencing in the other classes anyway (that is, we're calling `User.grantIapPermission`, not `UserBase.grantIapPermission`
___
*[`core/src/main/java/google/registry/tools/IamClient.java` line 41 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kFDgeE2U2ln8bkt2Q:-O0kFDgeE2U2ln8bkt2R:b-szkb0v) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/tools/IamClient.java#L41)):*
> ```Java
>   @Inject
>   public IamClient(
>       @ApplicationDefaultCredential GoogleCredentialsBundle credentialsBundle,
> ```

Why is this change necessary?

(I figure this same question goes across the other places where the credential is mentioned too)
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java` line 253 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kGtya4VKcjWNtSxnL:-O0kGtya4VKcjWNtSxnM:bl86ra3) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java#L253)):*
> ```Java
>                       .setRegistrarRoles(
>                           ImmutableMap.of(
>                               registrar.getRegistrarId(), RegistrarRole.ACCOUNT_MANAGER))
> ```

Do we know what user was usually set up as the console user? I'm asking because the ACCOUNT_MANAGER role is the least permissive of the registrar roles, and i'm wondering if we might eventually need or want to set up this user as a PRIMARY_CONTACT so that they can set up their own users in the console.
___
*[`core/src/test/java/google/registry/ui/server/registrar/ConsoleOteSetupActionTest.java` line 217 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0ofkjc6-nOft5um22D:-O0ofkjd7BTnAN_o_1P2:bf2bpi3) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/test/java/google/registry/ui/server/registrar/ConsoleOteSetupActionTest.java#L217)):*
> ```Java
>   }
> 
>   private void verifyUser(String email, String registrarId) {
> ```

can we just make these static methods so we don't need to redefine them in several classes? 


<!-- Sent from Reviewable.io -->

2024-07-02 20:35 UTC, jianglai reviewed
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2488)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman and @ptkach)

___
*[`core/src/main/java/google/registry/model/OteAccountBuilder.java` line 270 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kFlt87WrGgrADDT50:-O0oqh5QAyGFXeUIw_j1:b-2kwifg) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/model/OteAccountBuilder.java#L270)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Doesn't seem like this is used anywhere other than the exact same places where buildAndPersist is called. I don't think they need to be separate?
</blockquote></details>

You are right. Previously I was checking if the group address is provided and only call this function when it does. It makes sense now to include it with `buildAndPersist`, but note that `grantIapPermission` requires several parameters that `buildAndPersist` doesn't need. If we nested the former  inside the latter, it makes the latter quite ugly and makes unit testing them separately harder.
___
*[`core/src/main/java/google/registry/model/OteAccountBuilder.java` line 323 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kGE9AB-2Ji4wwmhgc:-O0ov0IM00_05Ulkag_N:b-z4yf88) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/model/OteAccountBuilder.java#L323)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this is gross and maybe something we'll want to change in the future? I think previously we didn't want to use the email address as the primary key because we thought it might be mutable, but given that it's immutable, it should probably be the pkey...
</blockquote></details>

Right now I'm just duplicating the existing logic. I guess it probably would be a mistake for a `User` to have both a registrar role and a global role? In that sense it is probably best to replace roles other than merging them. 
___
*[`core/src/main/java/google/registry/tools/IamClient.java` line 41 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kFDgeE2U2ln8bkt2Q:-O0ovhGICfNkaAIi1Snp:b-pp7rk8) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/tools/IamClient.java#L41)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Why is this change necessary?

(I figure this same question goes across the other places where the credential is mentioned too)
</blockquote></details>

It is a better practice to request an ADC, because it allows the class to be used in all places ADC bindings are provided -- this includes places where ADCs are backed by local credentials, like in the registry tool component. When I first wrote this class, I only intended for it to be used in the registry tool, so I made it depend on the local credential, but that makes it impossible to install it in other components. So in this case it is actually necessary, in the other case I'm just making things consistent.

I guess this is the DI equivalent of "depend on interfaces, not implementations".
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java` line 253 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kGtya4VKcjWNtSxnL:-O0owU2ABY7whQ9UFolr:b4cm8ak) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java#L253)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Do we know what user was usually set up as the console user? I'm asking because the ACCOUNT_MANAGER role is the least permissive of the registrar roles, and i'm wondering if we might eventually need or want to set up this user as a PRIMARY_CONTACT so that they can set up their own users in the console.
</blockquote></details>

That may be a good idea. I think we should probably confirm with gTech if that's what they want. Also for the legacy console, it doesn't matter what roles the user has, as long as they have one for the registrar:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/auth/AuthenticatedRegistrarAccessor.java;l=287;drc=54c5a9450dcf910c2217c7a8e56a51f06d32d4f0?q=authenticated&ss=nomulus%2Fnomulus

Is the fine-grained permission currently being used in the new console?
___
*[`core/src/test/java/google/registry/ui/server/registrar/ConsoleOteSetupActionTest.java` line 217 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0ofkjc6-nOft5um22D:-O0oxeak6mHR3jypota5:biva5kc) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/test/java/google/registry/ui/server/registrar/ConsoleOteSetupActionTest.java#L217)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can we just make these static methods so we don't need to redefine them in several classes?
</blockquote></details>

Done. I think it does look less cluttered.
___
*[`core/src/main/java/google/registry/model/console/UserBase.java` line 146 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kBHkE9NuataXay137:-O0ovddb7BDYynMIWPvs:b-efzeyw) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/model/console/UserBase.java#L146)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Thoughts on putting these in the subclass (`User`)? There's less going on there I think, and it's what we're referencing in the other classes anyway (that is, we're calling `User.grantIapPermission`, not `UserBase.grantIapPermission`
</blockquote></details>


Absolutely!


<!-- Sent from Reviewable.io -->

2024-07-02 20:35 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2488)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman and @ptkach)



<!-- Sent from Reviewable.io -->

2024-07-03 18:13 UTC, gbrodman requested changes
> Reviewed 9 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2488)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

___
*[`core/src/main/java/google/registry/model/OteAccountBuilder.java` line 270 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kFlt87WrGgrADDT50:-O0tn5aJ7Lsc5rxmfX5a:b-xqojs3) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/model/OteAccountBuilder.java#L270)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

You are right. Previously I was checking if the group address is provided and only call this function when it does. It makes sense now to include it with `buildAndPersist`, but note that `grantIapPermission` requires several parameters that `buildAndPersist` doesn't need. If we nested the former  inside the latter, it makes the latter quite ugly and makes unit testing them separately harder.
</blockquote></details>

it seems like a weird structure anyway but nothing better comes to mind immediately so sgtm 
___
*[`core/src/main/java/google/registry/tools/IamClient.java` line 41 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kFDgeE2U2ln8bkt2Q:-O0tnDLa8ZAOPlfcwxOO:bhkyvb) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/tools/IamClient.java#L41)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It is a better practice to request an ADC, because it allows the class to be used in all places ADC bindings are provided -- this includes places where ADCs are backed by local credentials, like in the registry tool component. When I first wrote this class, I only intended for it to be used in the registry tool, so I made it depend on the local credential, but that makes it impossible to install it in other components. So in this case it is actually necessary, in the other case I'm just making things consistent.

I guess this is the DI equivalent of "depend on interfaces, not implementations".
</blockquote></details>

Got it, so it uses the local credential in places where that's the default anyway. Sounds good. 
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java` line 253 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kGtya4VKcjWNtSxnL:-O0pH9WJ0lJUh8Lrbq5E:b-juaf3o) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java#L253)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

That may be a good idea. I think we should probably confirm with gTech if that's what they want. Also for the legacy console, it doesn't matter what roles the user has, as long as they have one for the registrar:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/auth/AuthenticatedRegistrarAccessor.java;l=287;drc=54c5a9450dcf910c2217c7a8e56a51f06d32d4f0?q=authenticated&ss=nomulus%2Fnomulus

Is the fine-grained permission currently being used in the new console?
</blockquote></details>

To some degree it is being used / will be used very shortly, e.g. the standard ACCOUNT_MANAGER permission does not have the permission to do anything with registry locks or to edit registrar details.  Thoughts? 


<!-- Sent from Reviewable.io -->

2024-07-03 18:21 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2488)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java` line 253 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kGtya4VKcjWNtSxnL:-O0tnof8BoYcrYlTTwE0:b1snylk) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java#L253)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

To some degree it is being used / will be used very shortly, e.g. the standard ACCOUNT_MANAGER permission does not have the permission to do anything with registry locks or to edit registrar details.  Thoughts?
</blockquote></details>

I believe the registrar contacts created before this change also don't have registry lock access. I think the debate is theoretical at this point, because all we want for this PR to do is for the old console to keep working when gTech onboards new registrars, and for that purpose the role we pick doesn't make a difference.

When we start asking gTech to use the new console to do the same thing, we will probably have to revise the onboarding procedure doc and consider what role is appropriate by default. Before that, it seems reasonable to grant the least permissive role from the security point of view.


<!-- Sent from Reviewable.io -->

2024-07-03 18:27 UTC, gbrodman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2488#-:-O0tqViL3TRMzbdkUdlp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java` line 253 at r2](https://reviewable.io/reviews/google/nomulus/2488#-O0kGtya4VKcjWNtSxnL:-O0tqWUZAFfkuukiFHur:b-3vslyf) ([raw file](https://github.com/google/nomulus/blob/2a62c3be8b0e7b28a73c865a9805dbe716d9d3c1/core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java#L253)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I believe the registrar contacts created before this change also don't have registry lock access. I think the debate is theoretical at this point, because all we want for this PR to do is for the old console to keep working when gTech onboards new registrars, and for that purpose the role we pick doesn't make a difference.

When we start asking gTech to use the new console to do the same thing, we will probably have to revise the onboarding procedure doc and consider what role is appropriate by default. Before that, it seems reasonable to grant the least permissive role from the security point of view.
</blockquote></details>

Sounds like a plan! 


<!-- Sent from Reviewable.io -->

2024-07-03 19:21 UTC, merged