Change domain-check fee responses for registrars in tiered pricing pr…
google/nomulus pull request #2489
Opened 2024-07-01 17:51 UTC by gbrodman

…omos

As requested, for registrars participaing in these tiered pricing promos that wish to receive this type of response, we make the following changes:

1. The non-promotional (i.e. incorrect) price is returned as the standard domain-create fee when running a domain check.
2. The promotional (i.e. correct) price is returned as a special custom command class with a name of "STANDARD PROMO" when running a domain check.
3. Domain creates will return the non-promotional (i.e. incorrect) price rather than the actual promotional price. This is not implemented in this PR.

2024-07-08 17:19 UTC, gbrodman commented
friendly ping

2024-07-09 19:19 UTC, CydeWeys reviewed
Hah, for bullet point 1, rather than saying the "incorrect" price, I would call it the pre-promotion, "base tier" price.  Pricing tiers is after all how basically all registrars think about domain pricing, even if we don't.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2489#-:-O1NvhHpEOH70gROJOJY:b-v6nend)* status: 0 of 8 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-09 19:22 UTC, gbrodman reviewed
changed the wording, hah

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2489#-:-O1NwfYFDFY0HULZ3ngI:bh54xmr)* status: 0 of 8 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-09 19:24 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2489)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2489#-O1Nwgzy9jtgBOF1RYCT:-O1Nwgzy9jtgBOF1RYCU:bckalgk) ([raw file](https://github.com/google/nomulus/blob/43fb88edeb6d77c5e6dda9bef6472b2f267ec9a3/core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java#L43)):*
> ```Java
>     RESTORE(true),
>     UPDATE(false),
>     // We don't accept CUSTOM commands in requests but may issue them in responses.
> ```

This should be a Javadoc.
___
*[`core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java` line 52 at r1](https://reviewable.io/reviews/google/nomulus/2489#-O1NwqVJ40VlXvC3Sa-N:-O1NwqVJ40VlXvC3Sa-O:b-j2oee0) ([raw file](https://github.com/google/nomulus/blob/43fb88edeb6d77c5e6dda9bef6472b2f267ec9a3/core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java#L52)):*
> ```Java
>       try {
>         CommandName command = valueOf(string);
>         checkArgument(!command.equals(UNKNOWN) && !command.equals(CUSTOM));
> ```

At this point it's worth adding a second parameter to the enum constructor that specifies whether it is acceptable for the enum value to be present in domain check requests, which will be false for both `UNKNOWN` and `CUSTOM` and true for all others.


<!-- Sent from Reviewable.io -->

2024-07-09 19:24 UTC, CydeWeys reviewed
LGTM modulo some nits.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2489#-:-O1Nx5A33zCINZ6-su4M:b-efajn9)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2024-07-09 19:50 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2489)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2489#-O1Nwgzy9jtgBOF1RYCT:-O1Nzamf2SD0dMhl_sX3:b-896fix) ([raw file](https://github.com/google/nomulus/blob/43fb88edeb6d77c5e6dda9bef6472b2f267ec9a3/core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java#L43)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should be a Javadoc.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java` line 52 at r1](https://reviewable.io/reviews/google/nomulus/2489#-O1NwqVJ40VlXvC3Sa-N:-O1O1tfS82CluGy0-sfG:bd7r3lp) ([raw file](https://github.com/google/nomulus/blob/43fb88edeb6d77c5e6dda9bef6472b2f267ec9a3/core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java#L52)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

At this point it's worth adding a second parameter to the enum constructor that specifies whether it is acceptable for the enum value to be present in domain check requests, which will be false for both `UNKNOWN` and `CUSTOM` and true for all others.
</blockquote></details>

as discussed offline, this does not correspond to domain check requests but rather token actions. Either way, we can do some sort of "acceptable input option" thing 


<!-- Sent from Reviewable.io -->

2024-07-11 19:10 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2489#-:-O1YC6z7BiV_6t5qeLPX:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-12 16:47 UTC, merged