Change domain-create fee response for tiered promos
google/nomulus pull request #2491
Opened 2024-07-09 19:10 UTC by gbrodman

As requested, for registrars participating in these tiered pricing promos that wish to receive this type of response, we make the following changes:

1. The non-promotional (i.e. incorrect) price is returned as the standard domain-create fee when running a domain check.
2. The promotional (i.e. correct) price is returned as a special custom command class with a name of "STANDARD PROMO" when running a domain check
3. Domain creates will return the non-promotional (i.e. incorrect) price rather than the actual promotional price.

This PR does only number 3. See PR #2489 for the others.

2024-07-10 14:01 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2491)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java` line 1825 at r1](https://reviewable.io/reviews/google/nomulus/2491#gh-1671057428:-O1RwfLu4DtRrwQS24y6:b-896fix) ([raw file](https://github.com/google/nomulus/blob/df45b277edbaa21401fd3e9495396ac7053700da/core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java#L1825)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unread local variable

Variable 'AllocationToken defaultToken1' is never read.

[Show more details](https://github.com/google/nomulus/security/code-scanning/11433)
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java` line 1826 at r1](https://reviewable.io/reviews/google/nomulus/2491#gh-1671057432:-O1RwflU2ebyHmHNhBBL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/df45b277edbaa21401fd3e9495396ac7053700da/core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java#L1826)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unread local variable

Variable 'AllocationToken defaultToken2' is never read.

[Show more details](https://github.com/google/nomulus/security/code-scanning/11434)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-11 19:23 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2491)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 1791 at r2](https://reviewable.io/reviews/google/nomulus/2491#-O1YD-al2mzx-TVfWPuJ:-O1YD-al2mzx-TVfWPuK:b-jabiqi) ([raw file](https://github.com/google/nomulus/blob/ed361bc50e25cf870922d63a424e8be9a0640140/core/src/main/java/google/registry/config/RegistryConfig.java#L1791)):*
> ```Java
>    * response with the actual promotional price and a "STANDARD PROMOTION" class.
>    */
>   public static ImmutableList<String> getTieredPricingPromotionRegistrarIds() {
> ```

Feels like this should return an `ImmutableSet`, as duplicates are not allowed and ordering is unimportant.
___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 446 at r2](https://reviewable.io/reviews/google/nomulus/2491#-O1YEWux0afxUHlszQTe:-O1YEWux0afxUHlszQTf:br8bdkf) ([raw file](https://github.com/google/nomulus/blob/ed361bc50e25cf870922d63a424e8be9a0640140/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L446)):*
> ```Java
>     boolean shouldShowDefaultPrice =
>         defaultTokenUsed
>             && RegistryConfig.getTieredPricingPromotionRegistrarIds().contains(registrarId);
> ```

Yeah, see, you're making a `contains()` call here which is more efficient in a set than a list.


<!-- Sent from Reviewable.io -->

2024-07-11 19:32 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2491)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 1791 at r2](https://reviewable.io/reviews/google/nomulus/2491#-O1YD-al2mzx-TVfWPuJ:-O1YGPDP2BrJE9EYZoc2:b-5ddz57) ([raw file](https://github.com/google/nomulus/blob/ed361bc50e25cf870922d63a424e8be9a0640140/core/src/main/java/google/registry/config/RegistryConfig.java#L1791)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Feels like this should return an `ImmutableSet`, as duplicates are not allowed and ordering is unimportant.
</blockquote></details>

eh yeah it just seemed like we were only using small numbers of registrars and the config seemed to use Lists more than Sets in general. 

changed


<!-- Sent from Reviewable.io -->

2024-07-11 20:13 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2491#-:-O1YQYOp29lSJdgbFiFd:bnfp4nl)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-07-12 19:39 UTC, merged