Upgrade to Hibernate6 and Jaxb4
google/nomulus pull request #2526
Opened 2024-08-08 17:18 UTC by weiminyu

These two must upgrade together b/c shared dependencies on xml related libraries.

JAXB changes:
*  Update bindings.xjb

*  Rename javax.xml.bind annotations to jakarta.*

Hibernate modeling
*  Collection of primitive values, Enum, and String now has builtin support.

*  For collection of complex objects and map, use `UserType` for mapping. This is cleaner and easier than the previous approach based on converter and type descriptor.

HQL/JQL
*  Entity fields in query must include full path in the JPA model. E.g., the `currentBulkToken` field in DomainHistory must be written as `resource.currentBulkToken`, with `resource` being the embedded entity in DomainHistory.

*  Types are enforced in many cases. E.g., a variable of VKey type can no longer be compared with a string or number. We need to either cast it to the correct type or, if compared with a parameter, provide a VKye object in `setParamater`.

*  The type checker is also not smart. E.g., currently the `now()` SQL function needs an explicit cast to timestamp.

Hibernate-generated schema

The default aliases for certain type have changed. This affects the schema generated by Hibernate.

| Old		| New		| PSQL
| ?		| smallint	| integer
| int4		| integer	| integer
| int8		| bigint	| bigint
| float8	| float(53)	| double precision

2024-08-13 20:57 UTC, jianglai requested changes
> | Old | New | PSQL Dump  
> | int4 | integer | integer  
> | int8 | bigint | bigint  
> | float8 | float(53) | double precision  
> | timestamptz | timestamp(6) with time zone | timestamp with time zone

Can you put this block in a code block, so the columns are aligned?

> Reviewed 383 of 383 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2526#-:-O4C0PCP6sHZyaY3FXRW:b-z31ny5)* status: all files reviewed, 47 unresolved discussions (waiting on @weiminyu)

___
*[`dependencies.gradle` line 155 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CGG2iD1oOvNL1wBUs:-O4CGG2j8Q70b-9mZzu1:b-t9ioj3) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/dependencies.gradle#L155)):*
> ```Gradle
>       'com.jcraft:jsch:[0.1.55,)',
>       'com.squareup:javapoet:[1.13.0,)',
>       'com.sun.activation:javax.activation:[1.2.0,)',
> ```

Is this being used anywhere? I tried to remove it and the code still compiles. Several tests failed but they seem to be related to dependency upgrades other than this dependency being removed.



_Code quote:_
```Gradle
'com.sun.activation:javax.activation:[1.2.0,)',
```
___
*[`dependencies.gradle` line 168 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4BzFpO3k0ia9vykgYj:-O4BzFpP9biXGtb2rnVC:b1kd9f5) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/dependencies.gradle#L168)):*
> ```Gradle
>       'jakarta.mail:jakarta.mail-api:[2.1.3,)',
>       'jakarta.servlet:jakarta.servlet-api:[6.0,)',
>       'jakarta.persistence:jakarta.persistence-api:[3.2.0,)',
> ```

Can you sort the dependencies lexicographically?



_Code quote:_
```Gradle
      'jakarta.servlet:jakarta.servlet-api:[6.0,)',
      'jakarta.persistence:jakarta.persistence-api:[3.2.0,)',
```
___
*[`core/build.gradle` line 294 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4Bz78bE_gTDuPiPQyJ:-O4Bz78bE_gTDuPiPQyK:b-rh3sp4) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/build.gradle#L294)):*
> ```Gradle
>   // Dependencies needed for jaxb compilation.
>   // Use jaxb 2.2.11 because 2.3 is known to break the Ant task we use.
>   // TODO: upgrade jaxb versions to 2.4.0, already in beta by Sept 2018
> ```

Is this comment still relevant?



_Code quote:_
```Gradle
  // Use jaxb 2.2.11 because 2.3 is known to break the Ant task we use.
  // TODO: upgrade jaxb versions to 2.4.0, already in beta by Sept 2018
```
___
*[`core/src/main/java/google/registry/batch/CheckBulkComplianceAction.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C-yRLEHDYPmW8Qfys:-O4C-yRLEHDYPmW8Qfyt:bxyoo0z) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/batch/CheckBulkComplianceAction.java#L113)):*
> ```Java
>                       "token",
>                       VKey.create(
>                           AllocationToken.class, bulkPricingPackage.getToken().getKey().toString()))
> ```

Isn't `bulkPricingPckage.getToken()` enough? It returns a `VKey<AllocationToken>`.
___
*[`core/src/main/java/google/registry/model/ImmutableObject.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C2LTm5wIjYnQ3LJuN:-O4C2LTm5wIjYnQ3LJuO:b-tmyvzy) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/ImmutableObject.java#L69)):*
> ```Java
>   // Note: if this class is made to implement Serializable, this field must become 'transient' since
>   // hashing is not stable across executions. Also note that @XmlTransient is forbidden on transient
>   // fields and need to be removed if transient is added.
> ```

Need to update the javadoc. Is `@XmlTransient` no longer conflicting with `@Transient`?

Any why is `@Transient` necessary here and below now?



_Code quote:_
```Java
  // hashing is not stable across executions. Also note that @XmlTransient is forbidden on transient
  // fields and need to be removed if transient is added.
```
___
*[`core/src/main/java/google/registry/model/billing/BillingEvent.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C2qxYDg8uHdaPnA6V:-O4C2qxYDg8uHdaPnA6W:b8gye98) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingEvent.java#L54)):*
> ```Java
> 
>   /** The billable value. */
>   @CompositeType(value = JodaMoneyType.class)
> ```

Can be omitted.



_Code quote:_
```Java
value
```
___
*[`core/src/main/java/google/registry/model/billing/BillingEvent.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C2xTf2d6QiVqn5ZNw:-O4C2xTf2d6QiVqn5ZNx:b-gkn2bs) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingEvent.java#L57)):*
> ```Java
>   @AttributeOverride(
>       name = "amount",
>       // Override Hibernate6 default (numeric(38,2)) to match real schema definition (numeric(38,2).
> ```

(numeric(19, 2))



_Code quote:_
```Java
(numeric(38,2)
```
___
*[`core/src/main/java/google/registry/model/billing/BillingRecurrence.java` line 102 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C36P92ldN_BnAe4Vd:-O4C36PA-uAeEuuTC_mv:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingRecurrence.java#L102)):*
> ```Java
>    */
>   @Nullable
>   @CompositeType(value = JodaMoneyType.class)
> ```

Ditto.



_Code quote:_
```Java
value
```
___
*[`core/src/main/java/google/registry/model/billing/BillingRecurrence.java` line 105 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C38UZ5aMRTg_WW9ik:-O4C38UZ5aMRTg_WW9il:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingRecurrence.java#L105)):*
> ```Java
>   @AttributeOverride(
>       name = "amount",
>       // Override Hibernate6 default (numeric(38,2)) to match real schema definition (numeric(38,2).
> ```

Ditto.



_Code quote:_
```Java
(numeric(38,2)
```
___
*[`core/src/main/java/google/registry/model/common/TimedTransitionProperty.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C66cT5xMl8ycs6i4z:-O4C66cT5xMl8ycs6i5-:b-bx4wz9) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/common/TimedTransitionProperty.java#L43)):*
> ```Java
> // Hibernate 6, which assumes that any class implementing Map<K, V> would also have <K, V> as its
> // first two generic type parameters. If this is fixed, we can add back the ForwardingMap, which
> // can simplify the code in a few places.
> ```

I don't quite understand what `ForwardingMap` gets us, given that you only have to implement the size/equals/hashCode function. Is that all we needed?



_Code quote:_
```Java
// first two generic type parameters. If this is fixed, we can add back the ForwardingMap, which
// can simplify the code in a few places.
```
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 248 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CBzfM7TLefem53_sj:-O4CBzfM7TLefem53_sk:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L248)):*
> ```Java
>   @AttributeOverride(
>       name = "amount",
>       // Override Hibernate6 default (numeric(38,2)) to match real schema definition (numeric(38,2).
> ```

Ditto.



_Code quote:_
```Java
(numeric(38,2)
```
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 251 at r1](https://reviewable. [...]

2024-08-14 18:18 UTC, weiminyu reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2526#-:-O4GrDwKDqkRKQV-4DHT:bb6un1j)* status: 347 of 383 files reviewed, 47 unresolved discussions (waiting on @jianglai)

___
*[`dependencies.gradle` line 155 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CGG2iD1oOvNL1wBUs:-O4GpQeh1BUi7YbnG05H:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/dependencies.gradle#L155)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is this being used anywhere? I tried to remove it and the code still compiles. Several tests failed but they seem to be related to dependency upgrades other than this dependency being removed.
</blockquote></details>

Done.
___
*[`dependencies.gradle` line 168 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4BzFpO3k0ia9vykgYj:-O4GluN87lCUDAkA57Rh:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/dependencies.gradle#L168)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Can you sort the dependencies lexicographically?
</blockquote></details>

Done.
___
*[`core/build.gradle` line 294 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4Bz78bE_gTDuPiPQyJ:-O4GlxngDyb3o8A5SCpP:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/build.gradle#L294)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is this comment still relevant?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/batch/CheckBulkComplianceAction.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C-yRLEHDYPmW8Qfys:-O4GmBeV4dcg2jTOmeH5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/batch/CheckBulkComplianceAction.java#L113)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Isn't `bulkPricingPckage.getToken()` enough? It returns a `VKey<AllocationToken>`.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/ImmutableObject.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C2LTm5wIjYnQ3LJuN:-O4GmUc09X67vFQXkxNq:b3hekzl) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/ImmutableObject.java#L69)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Need to update the javadoc. Is `@XmlTransient` no longer conflicting with `@Transient`?

Any why is `@Transient` necessary here and below now?
</blockquote></details>

Apparently protected field/method is part of subclasses now, even though base class is not embeddable. 
___
*[`core/src/main/java/google/registry/model/billing/BillingEvent.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C2qxYDg8uHdaPnA6V:-O4GiOnP0DZXjUXXqmat:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingEvent.java#L54)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Can be omitted.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/billing/BillingEvent.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C2xTf2d6QiVqn5ZNw:-O4GpTWOEhaz4DsuSOZF:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingEvent.java#L57)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

(numeric(19, 2))
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/billing/BillingRecurrence.java` line 102 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C36P92ldN_BnAe4Vd:-O4GiUnJ9BMnj-tL0R6u:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingRecurrence.java#L102)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/billing/BillingRecurrence.java` line 105 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C38UZ5aMRTg_WW9ik:-O4GpUlgBLFv3LtGwSxy:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingRecurrence.java#L105)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/common/TimedTransitionProperty.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C66cT5xMl8ycs6i4z:-O4GiaINDkEpL6d0q2Xb:bjevk2d) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/common/TimedTransitionProperty.java#L43)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I don't quite understand what `ForwardingMap` gets us, given that you only have to implement the size/equals/hashCode function. Is that all we needed?
</blockquote></details>

You won't have to call `toValueMap()` in a few places.
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 248 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CBzfM7TLefem53_sj:-O4GpVsa4a3k84hM4m0m:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L248)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 251 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CCO3j5QeBTcVXsczd:-O4GijeaAXtTApPiLz_G:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L251)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java` line 44 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CCdKT70aCp6oA3UBx:-O4GrSf83enqr0-TXKxQ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java#L44)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Still need to be fully qualified?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java` line 66 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CCGgPCKfHpA08GMLt:-O4GinXl6lnpVRD-5240:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java#L66)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CC3OqChXGW2YEH8xD:-O4GpZ82CzZpRf7LAERv:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java#L6 [...]

2024-08-15 18:00 UTC, jianglai requested changes
> Reviewed 35 of 35 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2526)* status: all files reviewed, 6 unresolved discussions (waiting on @weiminyu)

___
*[`dependencies.gradle` line 168 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4BzFpO3k0ia9vykgYj:-O4M9XBoC3NMhXOVEDzC:b-94dinl) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/dependencies.gradle#L168)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`jakarta.persistence` should be below `jakarta.mail` and above `jakarta.servlet`.
___
*[`core/src/main/java/google/registry/model/billing/BillingEvent.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C2xTf2d6QiVqn5ZNw:-O4M9mqe8Onhzjxl-fTC:bkj7y8z) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingEvent.java#L57)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You need to add a close bracket to all the comment with `(numeric(19, 2)` in it.
___
*[`core/src/main/java/google/registry/model/common/TimedTransitionProperty.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C66cT5xMl8ycs6i4z:-O4H0k3R8U5s5ZKZtrAC:be7s681) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/common/TimedTransitionProperty.java#L43)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

You won't have to call `toValueMap()` in a few places.
</blockquote></details>

OK. It doesn't seem to be too much of a saving though, to be honest.
___
*[`core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CC3OqChXGW2YEH8xD:-O4H11BD0GinIU6moUot:b-qrruib) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java#L69)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ditto.

Is there a way to do this at a higher level so we don't have to override every time `JodaMoney` is used?
</blockquote></details>

I would have thought that the composite type would allow one to specify the precision within the type itself. Is it not the case?
___
*[`core/src/main/java/google/registry/persistence/converter/CidrBlockListUserType.java` line 29 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CJRxo5ZI9bRgAK2uN:-O4M92P-7GCC-CHowu5g:b-iz43vf) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/persistence/converter/CidrBlockListUserType.java#L29)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

`Object::String` is a rare case. Making it default doesn't help other cases.
</blockquote></details>

I'd think that the `toString` method is the mostly commonly used method to convert the object to a string representation. But sure.
___
*[`core/src/main/java/google/registry/persistence/converter/MapUserType.java` line 33 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CWPkS5U4MaLnCR7R_:-O4MA_cc4RdruoTX6LDh:b-2swhqr) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/persistence/converter/MapUserType.java#L33)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Updated javadoc. Also explained why it cannot be Map<String, V>
</blockquote></details>

"may not" as in "cannot" or "may or may not"? I think you meant the latter (as in the logical map does not have to be a `Map`)?
___
*[`core/src/main/java/google/registry/persistence/converter/StringCollectionUserType.java` line 39 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CVKdPBpXqLhEhEOIN:-O4M8Su4Cen2EkWiKfM_:b1jfxv7) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/persistence/converter/StringCollectionUserType.java#L39)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Then you'll need intermeidate types like StringSetUserType and StringListUserType to accommodate the difference in `toEntity`.
Moreover, it should be the concret class to decide what type of  list/set they want (immutable or not).
</blockquote></details>

That's a fair point.
___
*[`core/src/main/java/google/registry/persistence/converter/StringCollectionUserType.java` line 62 at r4](https://reviewable.io/reviews/google/nomulus/2526#-O4M8pir9M9evdleA2iX:-O4M8pir9M9evdleA2iY:b-dpi2fl) ([raw file](https://github.com/google/nomulus/blob/c732ef59c89e225f65d985877ecf4b0fb55caacc/core/src/main/java/google/registry/persistence/converter/StringCollectionUserType.java#L62)):*
> ```Java
>       return false;
>     }
>     if (one instanceof Set o1 && other instanceof Set o2) {
> ```

Does it work as expected when `one` and `other` are of different subtype of `Set`?



_Code quote:_
```Java
    if (one instanceof Set o1 && other instanceof Set o2) {
```
___
*[`core/src/main/resources/META-INF/persistence.xml` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CMG3XAXQA8jDzBe7u:-O4MB743CsmbPsba0RxJ:btno1a3) ([raw file](https://github.com/google/nomulus/blob/2d1260c01bb2956b6b39138b8b6913196083a3d1/core/src/main/resources/META-INF/persistence.xml#L90)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

They don't need to be registered.
</blockquote></details>

That's neat. So the difference between converters and user types is that the former needs to be registered but can be automatically applied, and the latter is the opposite?


<!-- Sent from Reviewable.io -->

2024-08-15 19:48 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2526)* status: 370 of 383 files reviewed, 6 unresolved discussions (waiting on @jianglai)

___
*[`dependencies.gradle` line 168 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4BzFpO3k0ia9vykgYj:-O4MJM-P5Olr_RHYlNDQ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/dependencies.gradle#L168)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

`jakarta.persistence` should be below `jakarta.mail` and above `jakarta.servlet`.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/billing/BillingEvent.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4C2xTf2d6QiVqn5ZNw:-O4MJoXK8s5IzrrRG8kM:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/billing/BillingEvent.java#L57)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

You need to add a close bracket to all the comment with `(numeric(19, 2)` in it.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CC3OqChXGW2YEH8xD:-O4MC2K0CTrdREHv2KyB:brogsls) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/model/domain/token/BulkPricingPackage.java#L69)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I would have thought that the composite type would allow one to specify the precision within the type itself. Is it not the case?
</blockquote></details>

No it doesn't. Overrides on the `MoneyMapper` attributes will be ignored, and UserType doesn't have a type code.

Besides, we should simply allow new double-columns in the db to take up be (38,2). There is no real difference wrt psql. Overrides just make easier to compare against real schema. 
___
*[`core/src/main/java/google/registry/persistence/converter/MapUserType.java` line 33 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CWPkS5U4MaLnCR7R_:-O4MEA9A7cvLvlfPf_dG:bbqmouv) ([raw file](https://github.com/google/nomulus/blob/bb93cfaead45d7dc7602e911f91dd5ac20674e20/core/src/main/java/google/registry/persistence/converter/MapUserType.java#L33)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

"may not" as in "cannot" or "may or may not"? I think you meant the latter (as in the logical map does not have to be a `Map`)?
</blockquote></details>

The latter, so should have been "might not". Fixed.
___
*[`core/src/main/java/google/registry/persistence/converter/StringCollectionUserType.java` line 62 at r4](https://reviewable.io/reviews/google/nomulus/2526#-O4M8pir9M9evdleA2iX:-O4MFUvB9GxflwR3z2c5:bb77ufg) ([raw file](https://github.com/google/nomulus/blob/c732ef59c89e225f65d985877ecf4b0fb55caacc/core/src/main/java/google/registry/persistence/converter/StringCollectionUserType.java#L62)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Does it work as expected when `one` and `other` are of different subtype of `Set`?
</blockquote></details>

Yes.
___
*[`core/src/main/resources/META-INF/persistence.xml` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2526#-O4CMG3XAXQA8jDzBe7u:-O4MYue_AbAC6EagxnTO:blhpqm4) ([raw file](https://github.com/google/nomulus/blob/2d1260c01bb2956b6b39138b8b6913196083a3d1/core/src/main/resources/META-INF/persistence.xml#L90)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

That's neat. So the difference between converters and user types is that the former needs to be registered but can be automatically applied, and the latter is the opposite?
</blockquote></details>

Just realized that UserType for non-generic types can be automatic. Just updated Duration and Money to be so. Container types cannot be automated because of their generics.

Advantage of Converters is ease of use (implement and automate) and disadvantage is the need for registration.


<!-- Sent from Reviewable.io -->

2024-08-16 01:37 UTC, jianglai approved these changes
> Reviewed 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2526)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2024-09-03 19:05 UTC, merged