Update activity/txn reporting to use new GAE log format
google/nomulus pull request #2535
Opened 2024-08-23 19:05 UTC by gbrodman

Instead of having to parse the protoPayload.line from the request logs, we just want to inspect the textPayload from the app logs (stored in a separate table). This applies to the EPP metrics from the activity reporting and the attempted-adds column for the transaction reporting.

2024-08-24 15:46 UTC, jianglai requested changes
Have you tried to run it on alpha?

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2535#-:-O53aCwYDgrZ9WHZByr3:b-7kcl0j)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java` line 85 at r1](https://reviewable.io/reviews/google/nomulus/2535#-O541Q6FD8yS64HQutVz:-O541Q6FD8yS64HQutW-:b-gt3ssk) ([raw file](https://github.com/google/nomulus/blob/3c7e1da495e20a42b59ceb7bc5b263ed4575c658/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L85)):*
> ```Java
>     // Convert reportingMonth into YYYYMMDD format for Bigquery table partition pattern-matching.
>     DateTimeFormatter logTableFormatter = DateTimeFormat.forPattern("yyyyMMdd");
>     // The monthly logs are a shared dependency for epp counts and whois metrics
> ```

This is no longer the case now that you are querying the apps logs directly for the EPP counts.

In general I felt that whole process can be simplified. We just need to query against the apps log directly. The intermediate tables are just making things more complicated than its worth. These are all views any way so they don't even save the data in case we need them. Not that they should be refactored in this PR, which we want to get out ASAP.
___
*[`core/src/main/resources/google/registry/reporting/icann/sql/cloud_sql_attempted_adds.sql` line 59 at r1](https://reviewable.io/reviews/google/nomulus/2535#-O542XJz9HSXqyG-J42K:-O542XJz9HSXqyG-J42L:byyyzdl) ([raw file](https://github.com/google/nomulus/blob/0e808a4c010f01a67e775a46c8491d9e047bd76b/core/src/main/resources/google/registry/reporting/icann/sql/cloud_sql_attempted_adds.sql#L59)):*
> ```TSQL
>     JOIN UNNEST(logMessage) AS logMessages
>     -- Look for metadata logs from epp and registrar console requests
>     WHERE requestPath IN ('/_dr/epp', '/_dr/epptool', '/registrar-xhr')
> ```

Why are we not filtering on the path any more? Was it unnecessary because only `FlowReporter` will only be called for requests for these paths anyway?



_Code quote:_
```TSQL
  WHERE requestPath IN ('/_dr/epp', '/_dr/epptool', '/registrar-xhr')
```


<!-- Sent from Reviewable.io -->

2024-08-26 14:04 UTC, gbrodman reviewed
I haven't run the actual actions in alpha, but I ran the generated queries against production data in Bigquery as a test Thoughts? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2535#-:-O5DzedC-DtSMRUmbK0H:bhxy7mf)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java` line 85 at r1](https://reviewable.io/reviews/google/nomulus/2535#-O541Q6FD8yS64HQutVz:-O5E-1Ot6JnFmu-2dBYl:b1bhkdl) ([raw file](https://github.com/google/nomulus/blob/3c7e1da495e20a42b59ceb7bc5b263ed4575c658/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L85)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

This is no longer the case now that you are querying the apps logs directly for the EPP counts.

In general I felt that whole process can be simplified. We just need to query against the apps log directly. The intermediate tables are just making things more complicated than its worth. These are all views any way so they don't even save the data in case we need them. Not that they should be refactored in this PR, which we want to get out ASAP.
</blockquote></details>

Yeah, we could possibly redo it. Thought I do see the value in having the various computations run in smaller chunks before they're brought together in the aggregation (I don't feel particularly strongly either way). 
___
*[`core/src/main/resources/google/registry/reporting/icann/sql/cloud_sql_attempted_adds.sql` line 59 at r1](https://reviewable.io/reviews/google/nomulus/2535#-O542XJz9HSXqyG-J42K:-O5DzmtK2Tkg43CH2Eot:b-ne6861) ([raw file](https://github.com/google/nomulus/blob/0e808a4c010f01a67e775a46c8491d9e047bd76b/core/src/main/resources/google/registry/reporting/icann/sql/cloud_sql_attempted_adds.sql#L59)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Why are we not filtering on the path any more? Was it unnecessary because only `FlowReporter` will only be called for requests for these paths anyway?
</blockquote></details>

Yep, exactly 


<!-- Sent from Reviewable.io -->

2024-08-26 14:11 UTC, jianglai approved these changes
That should be a good indicator, but I'd still deploy to alpha/crash/qa and do an end-to-end test just for sure. Make sure that the logs are actually exported in these environments.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2535#-:-O5E0bxiDQpBDK-eNf4a:b-aqzw21)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java` line 85 at r1](https://reviewable.io/reviews/google/nomulus/2535#-O541Q6FD8yS64HQutVz:-O5E09z5DqG2taf0Fawh:buqaau5) ([raw file](https://github.com/google/nomulus/blob/3c7e1da495e20a42b59ceb7bc5b263ed4575c658/core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java#L85)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah, we could possibly redo it. Thought I do see the value in having the various computations run in smaller chunks before they're brought together in the aggregation (I don't feel particularly strongly either way).
</blockquote></details>

I mean, we only use the path column in the monthly logs at this point, so I don't think it is actually doing any kind of pre-computing that's worth saving.


<!-- Sent from Reviewable.io -->

2024-08-26 19:16 UTC, gbrodman reviewed
tested! and made the necessary change

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2535#-:-O5F6ZNOCN-tzlxVaeR9:btf3jtp)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2024-08-26 19:22 UTC, jianglai approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2535)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2024-08-26 20:28 UTC, merged