Connect to the correct endpoints based on runtime
google/nomulus pull request #2540
Opened 2024-08-26 20:54 UTC by jianglai

2024-09-12 22:28 UTC, jianglai reviewed
> Reviewed 114 of 128 files at r1, 17 of 17 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2540)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2024-09-16 17:43 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2540)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2024-09-17 12:21 UTC, jianglai reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2540)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2024-09-17 21:08 UTC, jianglai reviewed
> Reviewed 20 of 20 files at r7, 19 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2540)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2024-09-19 19:27 UTC, gbrodman requested changes
> Reviewed 98 of 128 files at r1, 13 of 17 files at r2, 12 of 12 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 1 of 20 files at r7, 19 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2540)* status: all files reviewed, 5 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/config/ConfigUtils.java` line 32 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7Ab5T80HQdCgrqZ435:-O7Ab5T80HQdCgrqZ436:bqxij8y) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/config/ConfigUtils.java#L32)):*
> ```Java
>   public static URL makeUrl(String url) {
>     try {
>       return new URI(url).toURL();
> ```

Why are we doing the conversion to URI before returning a url? 
___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 1597 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7AYK3R6I_rCgBoTTE4:-O7AYK3R6I_rCgBoTTE5:b-sr1beh) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/config/RegistryConfig.java#L1597)):*
> ```Java
>   }
> 
>   public static String getBaseDomain() {
> ```

we could probably change this and `provideBaseDomain` so that one of them uses the other 
___
*[`core/src/main/java/google/registry/tools/ServiceConnection.java` line 62 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7Abwdf4bSgUoDwxWMR:-O7Abwdg862YWByMzS-f:b4k390b) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/tools/ServiceConnection.java#L62)):*
> ```Java
>   protected static final Pattern HTML_TITLE_TAG_PATTERN = Pattern.compile("<title>(.*?)</title>");
> 
>   protected final Service service;
> ```

can't these all still be private? I don't see any direct access anywhere (or any subclasses) 
___
*[`core/src/main/java/google/registry/tools/ServiceConnection.java` line 136 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7AbLeE5FSe5_rG5ZuV:-O7AbLeE5FSe5_rG5ZuW:b-p0myg5) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/tools/ServiceConnection.java#L136)):*
> ```Java
>     URL url = service.getServiceUrl();
>     // Currently only GAE supports connecting to canary.
>     if (service instanceof GaeService && useCanary) {
> ```

thoughts on maybe throwing an exception if the ServiceConnection is told to use the canary instance in a GKE environment? I suppose we could probably do that in the constructor 
___
*[`core/src/test/java/google/registry/batch/CloudTasksUtilsTest.java` line 163 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7AjvJx-2w_ZtvhPBKN:-O7AjvJx-2w_ZtvhPBKO:b-7uj8a) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/test/java/google/registry/batch/CloudTasksUtilsTest.java#L163)):*
> ```Java
>   @Test
>   void testSuccess_createPostTasks() {
>     Task task = cloudTasksUtils.createTask(TheAction.class, POST, params);
> ```

It seems odd to me that we can attempt to enqueue tasks with a method that is invalid for the given class. Maybe in CloudTasksUtils we verify that the given class's Action annotation contains the provided method and throw an exception otherwise? 

For testing, we could just add POST to TheAction and then use OtherAction+POST to test the failure case.


<!-- Sent from Reviewable.io -->

2024-09-20 13:52 UTC, jianglai reviewed
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2540)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/config/ConfigUtils.java` line 32 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7Ab5T80HQdCgrqZ435:-O7B0lnW0EiPb4Vi_-fr:bpegchl) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/config/ConfigUtils.java#L32)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Why are we doing the conversion to URI before returning a url?
</blockquote></details>

Because `new URL(url)` is deprecated...
___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 1597 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7AYK3R6I_rCgBoTTE4:-O7B12kE4p_YkeHOrXT5:b2s79vr) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/config/RegistryConfig.java#L1597)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we could probably change this and `provideBaseDomain` so that one of them uses the other
</blockquote></details>

Haha, you'd think that, but `getBaseDomain()` is not part of the dependency injection framework (so it can be used at places outside the dependency tree). In practice, `CONFIG_SETTINGS` is the static field providing the binding to `RegistryConfigSettings` anyway, so we *could* have `provideBaseDomain` just call `getBaseDomain`. But I felt that is better to follow the dependency injection idiom.
___
*[`core/src/main/java/google/registry/tools/ServiceConnection.java` line 62 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7Abwdf4bSgUoDwxWMR:-O7EWZLVC264dHAfzPFD:b-nl1gzo) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/tools/ServiceConnection.java#L62)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can't these all still be private? I don't see any direct access anywhere (or any subclasses)
</blockquote></details>

I think you're right. I changed them to protected in a failed attempt to make the connection field injectable, and forgot to change them back.
___
*[`core/src/main/java/google/registry/tools/ServiceConnection.java` line 136 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7AbLeE5FSe5_rG5ZuV:-O7EWlW4-awPKvcymueh:b-kcwvcj) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/tools/ServiceConnection.java#L136)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

thoughts on maybe throwing an exception if the ServiceConnection is told to use the canary instance in a GKE environment? I suppose we could probably do that in the constructor
</blockquote></details>

Sure. I'm still debating the best way to do canary in GKE, that's why I left it unimplemented for now.
___
*[`core/src/test/java/google/registry/batch/CloudTasksUtilsTest.java` line 163 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7AjvJx-2w_ZtvhPBKN:-O7Eel98BAAzRWyT5FRO:biq209v) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/test/java/google/registry/batch/CloudTasksUtilsTest.java#L163)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It seems odd to me that we can attempt to enqueue tasks with a method that is invalid for the given class. Maybe in CloudTasksUtils we verify that the given class's Action annotation contains the provided method and throw an exception otherwise? 

For testing, we could just add POST to TheAction and then use OtherAction+POST to test the failure case.
</blockquote></details>

Good point. Previously we don't have access to the action class itself. Now that we do, we might as well check the allowed methods.


<!-- Sent from Reviewable.io -->

2024-09-20 17:44 UTC, jianglai reviewed
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2540)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/test/java/google/registry/batch/CloudTasksUtilsTest.java` line 163 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7AjvJx-2w_ZtvhPBKN:-O7FXDAc-Q0KwUTfqUaK:bi9bj0b) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/test/java/google/registry/batch/CloudTasksUtilsTest.java#L163)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Good point. Previously we don't have access to the action class itself. Now that we do, we might as well check the allowed methods.
</blockquote></details>

It actually caught a bug!


<!-- Sent from Reviewable.io -->

2024-09-20 17:53 UTC, gbrodman approved these changes
> Reviewed 3 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2540)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/config/ConfigUtils.java` line 32 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7Ab5T80HQdCgrqZ435:-O7FZ-kL-7P8xIjAvHIW:b-inyh9e) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/config/ConfigUtils.java#L32)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Because `new URL(url)` is deprecated...
</blockquote></details>

Oh weird! Sounds good to me. 
___
*[`core/src/main/java/google/registry/config/RegistryConfig.java` line 1597 at r8](https://reviewable.io/reviews/google/nomulus/2540#-O7AYK3R6I_rCgBoTTE4:-O7FZEpL1lDpSrcGyKh6:bcm42wu) ([raw file](https://github.com/google/nomulus/blob/6e33abb286996787c963b6c11128c6fd6611fc92/core/src/main/java/google/registry/config/RegistryConfig.java#L1597)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Haha, you'd think that, but `getBaseDomain()` is not part of the dependency injection framework (so it can be used at places outside the dependency tree). In practice, `CONFIG_SETTINGS` is the static field providing the binding to `RegistryConfigSettings` anyway, so we *could* have `provideBaseDomain` just call `getBaseDomain`. But I felt that is better to follow the dependency injection idiom.
</blockquote></details>

Eh yeah that's fair. Silly injection. 


<!-- Sent from Reviewable.io -->

2024-09-20 19:57 UTC, merged