A batch query utility to replace TransactionManager's `loadAllOf` methods
google/nomulus pull request #2589
Opened 2024-10-10 16:37 UTC by weiminyu

TransactionManage's `loadAllOf` and `loadAllOfStream` methods are not safe: they may cause PSQL `out of shared memory` errors and also java OOM errors. The key to avoid lockup is to load batches of entities in separate transactions.

This PR added a `BatchedQueries` class, and replaced the unsafe method in one class as a demo.

2024-10-10 18:57 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2589)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])

___
*[`core/src/test/java/google/registry/persistence/transaction/BatchedQueriesTest.java` line 85 at r1](https://reviewable.io/reviews/google/nomulus/2589#gh-1795943687:-O8rmhGN5mrHIO3kzGmd:b-1ncmf2) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/test/java/google/registry/persistence/transaction/BatchedQueriesTest.java#L85)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## No clone method

No clone method, yet implements Cloneable.

[Show more details](https://github.com/google/nomulus/security/code-scanning/15662)
</blockquote></details>

Test-only
___
*[`core/src/test/java/google/registry/persistence/transaction/BatchedQueriesTest.java` line 96 at r1](https://reviewable.io/reviews/google/nomulus/2589#gh-1795943689:-O8rmdVO77D5CQspH5YN:bjx8r1o) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/test/java/google/registry/persistence/transaction/BatchedQueriesTest.java#L96)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## No clone method

No clone method, yet implements Cloneable.

[Show more details](https://github.com/google/nomulus/security/code-scanning/15661)
</blockquote></details>

Test-only.


<!-- Sent from Reviewable.io -->

2024-10-14 15:22 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2589)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 36 at r1](https://reviewable.io/reviews/google/nomulus/2589#-O9AbZ-07g7OO53_lWjt:-O9AbZ-07g7OO53_lWju:b-e029u9) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L36)):*
> ```Java
>   private BatchedQueries() {}
> 
>   public static final int DEFAULT_BATCH_SIZE = 500;
> ```

This doesn't need to be public?
___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 49 at r1](https://reviewable.io/reviews/google/nomulus/2589#-O9AboIB37x7DFlNGLuA:-O9AboIB37x7DFlNGLuB:bvwcq73) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L49)):*
> ```Java
>    * Loads all entities of type {@code T} in batches.
>    *
>    * <p>This method must not be nested in any transaction; same for the traversal of the returned
> ```

So the reason `loadAllOf()` isn't implemented as a method on transaction manager is that it needs to run at a higher level, namely, managing all of its own transactions itself?


<!-- Sent from Reviewable.io -->

2024-10-14 15:25 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2589)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 81 at r1](https://reviewable.io/reviews/google/nomulus/2589#-O9AcQJY5cbsLksaLaV9:-O9AcQJY5cbsLksaLaVA:brc3tg0) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L81)):*
> ```Java
>       checkArgument(
>           jpaEntityType.hasSingleIdAttribute(),
>           "%s must have a single ID attribute.",
> ```

No terminal periods necessary on exception messages, here and elsewhere.
___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 87 at r1](https://reviewable.io/reviews/google/nomulus/2589#-O9Ac8pI8k21-VrXV3Df:-O9Ac8pI8k21-VrXV3Dg:b-32beln) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L87)):*
> ```Java
>       var idAttr = jpaEntityType.getId(jpaEntityType.getIdType().getJavaType());
>       this.initialJpqlQuery =
>           String.format("FROM %s ORDER BY %s", jpaEntityType.getName(), idAttr.getName());
> ```

Based on this implementation, maybe we should add a caveat to the Javadoc above that new entities created after the batches have started running might or might not be returned, depending on where they fit into the sort order?


<!-- Sent from Reviewable.io -->

2024-10-14 16:29 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2589)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 36 at r1](https://reviewable.io/reviews/google/nomulus/2589#-O9AbZ-07g7OO53_lWjt:-O9AqlemCqDjQtwEWeLS:b-896fix) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L36)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This doesn't need to be public?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 49 at r1](https://reviewable.io/reviews/google/nomulus/2589#-O9AboIB37x7DFlNGLuA:-O9Ao9kUC5X2-9nSHHtu:bb77ufg) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L49)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

So the reason `loadAllOf()` isn't implemented as a method on transaction manager is that it needs to run at a higher level, namely, managing all of its own transactions itself?
</blockquote></details>

Yes.
___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 81 at r1](https://reviewable.io/reviews/google/nomulus/2589#-O9AcQJY5cbsLksaLaV9:-O9AqdJvAgkAJHeLJC_9:b-896fix) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L81)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

No terminal periods necessary on exception messages, here and elsewhere.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 87 at r1](https://reviewable.io/reviews/google/nomulus/2589#-O9Ac8pI8k21-VrXV3Df:-O9AqH5r0B9-S8-AOiWD:bcg3lr) ([raw file](https://github.com/google/nomulus/blob/9aa3bee20463a8de056aaa3929769f935ef1f38c/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L87)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Based on this implementation, maybe we should add a caveat to the Javadoc above that new entities created after the batches have started running might or might not be returned, depending on where they fit into the sort order?
</blockquote></details>

We use REPEATABLE_READ so new insertions or updates after a batch starts are not included.

Updated the method's javadoc


<!-- Sent from Reviewable.io -->

2024-10-14 17:05 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2589)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 54 at r2](https://reviewable.io/reviews/google/nomulus/2589#-O9AzJ8UDkgiPq8-vXPZ:-O9AzJ8V3Pw3o2V6zKRy:bolro8r) ([raw file](https://github.com/google/nomulus/blob/62655c598a973ed12c87b4c61ce58ac75259e406/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L54)):*
> ```Java
>    * batch's start time. New insertions or updates since then are not reflected in the result.
>    */
>   public static <T> Stream<ImmutableList<T>> loadAllOf(
> ```

Does it make sense to make this generalizable to basic batched queries, rather than the narrower use case of "get all entities of type T"?  I ask because it would be useful if this could also be used e.g. here: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java;l=114-122;drc=2b3c6525ffbbe9e7835dfdd169872d240f27927d
___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 114 at r2](https://reviewable.io/reviews/google/nomulus/2589#-O9Aysze3kunspvU-mmL:-O9Aysze3kunspvU-mmM:b-9a4v49) ([raw file](https://github.com/google/nomulus/blob/62655c598a973ed12c87b4c61ce58ac75259e406/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L114)):*
> ```Java
> 
>             var results = ImmutableList.copyOf(query.setMaxResults(batchSize).getResultList());
>             results.forEach(entityManager::detach);
> ```

Curious what the thought process behind this is?
___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 142 at r2](https://reviewable.io/reviews/google/nomulus/2589#-O9AzE4vCY7JIyDCtFJy:-O9AzE4vCY7JIyDCtFJz:bz63ust) ([raw file](https://github.com/google/nomulus/blob/62655c598a973ed12c87b4c61ce58ac75259e406/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L142)):*
> ```Java
>     public ImmutableList<T> next() {
>       var toReturn = cachedBatch;
>       cachedBatch = cachedBatch.size() < batchSize ? ImmutableList.of() : readNextBatch();
> ```

Is it necessary to cache an entire batch, or just the last element from the previous batch?


<!-- Sent from Reviewable.io -->

2024-10-14 18:53 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2589)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @github-advanced-security[bot], and @weiminyu)

___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 54 at r2](https://reviewable.io/reviews/google/nomulus/2589#-O9AzJ8UDkgiPq8-vXPZ:-O9B78Fd7KZH90X6xmXX:bqq6hdx) ([raw file](https://github.com/google/nomulus/blob/62655c598a973ed12c87b4c61ce58ac75259e406/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L54)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Does it make sense to make this generalizable to basic batched queries, rather than the narrower use case of "get all entities of type T"?  I ask because it would be useful if this could also be used e.g. here: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java;l=114-122;drc=2b3c6525ffbbe9e7835dfdd169872d240f27927d
</blockquote></details>

Will do later. They are less urgent since they won't lock up the system. 
___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 114 at r2](https://reviewable.io/reviews/google/nomulus/2589#-O9Aysze3kunspvU-mmL:-O9B7gG3BCL-OVMU7Cez:b-rhwchn) ([raw file](https://github.com/google/nomulus/blob/62655c598a973ed12c87b4c61ce58ac75259e406/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L114)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Curious what the thought process behind this is?
</blockquote></details>

You mean the `detach` call? Mainly to be consistent with `JpaTrasantcionManagerImpl`, which basically detaches every entity it loads for reasons (related to our use of immutable objects).

This call here makes it clear that the entities are for use outside of the current transaction. 
___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 142 at r2](https://reviewable.io/reviews/google/nomulus/2589#-O9AzE4vCY7JIyDCtFJy:-O9BM8Wj51sbuv8BqEgp:b520gh9) ([raw file](https://github.com/google/nomulus/blob/62655c598a973ed12c87b4c61ce58ac75259e406/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L142)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is it necessary to cache an entire batch, or just the last element from the previous batch?
</blockquote></details>

The entire batch needs to be cached. It'd be returned to the caller in one shot on the next call to `next`. 


<!-- Sent from Reviewable.io -->

2024-10-14 19:07 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2589)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @github-advanced-security[bot], and @weiminyu)

___
*[`core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java` line 54 at r2](https://reviewable.io/reviews/google/nomulus/2589#-O9AzJ8UDkgiPq8-vXPZ:-O9BQBqHB49mk6_ynKRv:b3kqx) ([raw file](https://github.com/google/nomulus/blob/9ffa3e9bdcb96565838bdb22a9dd6b8ee5fb5322/core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java#L54)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Will do later. They are less urgent since they won't lock up the system.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2024-10-14 20:07 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2589#-:-O9BdBPC490islKD4TBd:bnfp4nl)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)



<!-- Sent from Reviewable.io -->

2024-10-14 21:17 UTC, merged