tcp service
google/nomulus pull request #2627
Opened 2024-12-19 16:35 UTC by jianglai

- **WIP**
- **Expose EPP and WHOIS endpoints on reginal load balancers**

2024-12-19 21:18 UTC, jianglai reviewed
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2627)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`jetty/get-endpoints.py` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2627#-OEUv2bgE_IKWiAGRsv8:-OEVlo-S4jBLVeF2LJXO:b-pbdqz3) ([raw file](https://github.com/google/nomulus/blob/a25eb9c856a22b449a08862aad352a93312737d8/jetty/get-endpoints.py#L55)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Just a suggestion I found a hard way myself. Instead of parsing the output as a lines, which is ok, but not great. You can pretty much always use ```--format=json``` instead . This allows for safer and cleaner approach.
</blockquote></details>

Agreed.


<!-- Sent from Reviewable.io -->

2024-12-19 22:35 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2627)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)



<!-- Sent from Reviewable.io -->

2024-12-19 22:35 UTC, jianglai commented on jetty/get-endpoints.py
> +    name = content['metadata']['name']
Done.
<!-- Reviewable comment -OEW2od3775jjhp6KJY1:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-20 15:11 UTC, ptkach requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2627)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

___
*[`jetty/get-endpoints.py` line 137 at r4](https://reviewable.io/reviews/google/nomulus/2627#-OEZbCNKEYk1A1Qsl78x:-OEZbCNKEYk1A1Qsl78y:bdb4a3s) ([raw file](https://github.com/google/nomulus/blob/7f5b913105ebbfb88e860f9aa30bf3e78d18d92a/jetty/get-endpoints.py#L137)):*
> ```Python
>             for service in ['whois', 'whois-canary', 'epp', 'epp-canary']:
>                 map_key = service.replace('-', '_')
>                 for ip in get_endpoints('services', service,
> ```

It looks like it can be simplified. kubectl accepts ```jsonpath``` param, which I think would make it easier by doing something like this ```jsonpath='{.status.loadBalancer.ingress[0}.ip}'``` . I've not checked it though, I just realized I'd be really surprised if they didn't and stumbled upon this doc https://kubernetes.io/docs/reference/kubectl/jsonpath/


<!-- Sent from Reviewable.io -->

2024-12-23 20:49 UTC, jianglai reviewed
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2627)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`jetty/get-endpoints.py` line 137 at r4](https://reviewable.io/reviews/google/nomulus/2627#-OEZbCNKEYk1A1Qsl78x:-OEpGzsO5MxwRLleWIKa:br6chf9) ([raw file](https://github.com/google/nomulus/blob/7f5b913105ebbfb88e860f9aa30bf3e78d18d92a/jetty/get-endpoints.py#L137)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

It looks like it can be simplified. kubectl accepts ```jsonpath``` param, which I think would make it easier by doing something like this ```jsonpath='{.status.loadBalancer.ingress[0}.ip}'``` . I've not checked it though, I just realized I'd be really surprised if they didn't and stumbled upon this doc https://kubernetes.io/docs/reference/kubectl/jsonpath/
</blockquote></details>

It does look much nicer!


<!-- Sent from Reviewable.io -->

2024-12-23 21:31 UTC, ptkach approved these changes
> Reviewed 3 of 4 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2627)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-12-26 15:24 UTC, jianglai reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2627)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)



<!-- Sent from Reviewable.io -->

2024-12-26 16:17 UTC, merged