Add a CertificateChecker class
google/nomulus pull request #793
Opened 2020-09-03 22:32 UTC by sarahcaseybot

2020-09-10 04:11 UTC, jianglai requested changes
> Reviewed 75 of 77 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 75 of 77 files reviewed, 6 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 40 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGpz7sCBKCPNl2f6-97:-MGpz7sCBKCPNl2f6-98:b-xdbnnk) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L40)):*
> ```
> EC_KEY_LENGTH
> ```
Change to `EC_CURVE`.

We are only going to support P-256 curve. Per crypto-help:

"Also drop the 'or higher' on P-256. It's not very coherent as there are multiple 256-bit, 384-bit, etc., curves. More importantly, good EC implementations are curve-specific. That means it is bad to choose uncommon curves, both because you'll stray outside of where people have put in performance and hardening work, and it's harmful to the ecosystem. The more diversity there is in curves, the harder it is to focus the world's very limited cryptographic implementation effort on the right things."
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 41 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGpuJVkAtBzMEaiwiop:-MGpuJVkAtBzMEaiwioq:bgmq0ou) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L41)):*
> ```
> DSA_KEY_LENGTH, // key length is too low
> ```
We forbid DSA certificates out right. Only RSA and ECDSA is supported.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 57 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGpyrs_2OGjQ8aD2V7Z:-MGpyrs_2OGjQ8aD2V7_:b-bsaali) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L57)):*
> ```
> } else {
> ```
I don't think the `else` block is necessary. We are returning *all* violations here. An expired cert can also have a validity length that's too long, for example.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 98 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGq-XbtDo6Og8QDPtBL:-MGq-XbtDo6Og8QDPtBM:b-cahm5q) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L98)):*
> ```
> isValidNow
> ```
The method name is misleading. A certificate could have expired and still return true for this method. Change to `notYetValid` and check if the method returns false instead.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 107 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGq-r9V2ef7Nrm8S5Uu:-MGq-r9V2ef7Nrm8S5Uv:bqek1w6) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L107)):*
> ```
> 826
> ```
Don't hard code this value. Let's take a `maxValidityDays` from the class constructor, change this method to take in a  second parameter, and pass `maxValidityDays` as that parameter from the `checkCertificate` method.

The `maxValidityDays` can then be specified in the config file. The `CertificateChecker` class can be injected with this value using Dagger.

The same goes for the other constants used in this class.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 126 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGqAUmvArdJOHngmPyF:-MGqAUmvArdJOHngmPyG:b8vmaoc) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L126)):*
> ```
> >= 256
> ```
We should check that it equals 256, not no less than.

Also need to check spec.getCurve().getField() and make sure it is a prime field (ECFieldFp).


<!-- Sent from Reviewable.io -->

2020-09-11 00:59 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 75 of 77 files reviewed, 6 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 126 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGqAUmvArdJOHngmPyF:-MGueJyE8SltfAVK1lX4:b-5ji6eq) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L126)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done. Not sure how I can create a test for non-prime fields
</blockquote></details>

Pick a 2^m curve from https://www.secg.org/SEC2-Ver-1.0.pdf?
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 78 at r2](https://reviewable.io/reviews/google/nomulus/793#-MGudnAZ2ST1gH3JBZz_:-MGudnAZ2ST1gH3JBZza:bl4du7t) ([raw file](https://github.com/google/nomulus/blob/df31e4caca2a057ecf1eb8e3984f53eaec48264f/util/src/main/java/google/registry/util/CertificateChecker.java#L78)):*
> ```
> Lengths
> ```
Strength. For RSA we check the key length. For ECDSA we check the curve type.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 130 at r2](https://reviewable.io/reviews/google/nomulus/793#-MGue3_y6d2HaFClvhB7:-MGue3_y6d2HaFClvhB8:bw7i1r5) ([raw file](https://github.com/google/nomulus/blob/df31e4caca2a057ecf1eb8e3984f53eaec48264f/util/src/main/java/google/registry/util/CertificateChecker.java#L130)):*
> ```
> checkEcKeyLength
> ```
`checkEcCurveType`
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 134 at r2](https://reviewable.io/reviews/google/nomulus/793#-MGuezSa7e6yc-GN5GqU:-MGuezSa7e6yc-GN5GqV:bof391g) ([raw file](https://github.com/google/nomulus/blob/df31e4caca2a057ecf1eb8e3984f53eaec48264f/util/src/main/java/google/registry/util/CertificateChecker.java#L134)):*
> ```
> getCharacteristic()
> ```
How did you get this function? I only see `getFieldSize` as the sole method of interface `ECField`.

https://source.corp.google.com/piper///depot/google3/third_party/java_src/jdk/openjdk11/dev/src/src/java.base/share/classes/java/security/spec/ECField.java;l=1;bpv=0;bpt=1;rcl=229163191?q=ECField.java&sq=package:piper%20file:%2F%2Fdepot%2Fgoogle3%20-file:google3%2Fexperimental


<!-- Sent from Reviewable.io -->

2020-09-14 22:23 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 75 of 77 files reviewed, 16 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 107 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGq-r9V2ef7Nrm8S5Uu:-MHDgor_D9kXC7JBHPKl:b-7gmtad) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L107)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unfortunately it's not so simple (see above comment), since configuration lives in `core` while this is in `util`, which `core` depends on.  See more details in previous comment.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 36 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDfFhe51Cl-jr5Fujd:-MHDfFhe51Cl-jr5Fuje:b-10lg2) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L36)):*
> ```Java
> 
>   @Inject
>   public CertificateChecker(int maxValidityDays, int daysToExpiration, int minimumRsaKeyLength) {
> ```

You would need `@Config(...)` annotations on all of these to actually load them from the config file properly; Dagger doesn't know how to separate these raw ints on its own.  And you'll similarly need to actually add these new config options to the config file.

But the larger problem is that the core subproject (where all the config stuff lives) depends on the util subproject, and not the other way around.  So it's not even possible to do it this way.  Thus you can't `@Inject` it; you'll have to have an `@Provides` method somewhere in the core package that itself depends on the 3 relevant `@Config` options.

This should probably therefore not be a public constructor, but rather, a public static `create()` method (which is preferred over constructors by Effective Java).
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 49 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDdZ9PBMQKIvBfZPIq:-MHDdZ9PBMQKIvBfZPIr:bxvb7h9) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L49)):*
> ```Java
>     EXPIRED,
>     NEARING_EXPIRATION, // less than 30 days to expiration
>     RSA_KEY_LENGTH, // key length is too low
> ```

`WEAK_RSA_KEY_LENGTH`? `RSA_KEY_LENGTH_TOO_SMALL`?  This way it's obvious what the problem is from the name itself.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 50 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDdSVU1zhD4O2MOJZU:-MHDdSVVB7x44XF0loe9:b-ugik9v) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L50)):*
> ```Java
>     NEARING_EXPIRATION, // less than 30 days to expiration
>     RSA_KEY_LENGTH, // key length is too low
>     EC_CURVE, // uses a curve other than P-256
> ```

How about something like `ELLIPTIC_CURVE_NOT_ALLOWED` or similar?
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 52 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDdjFJAD471t3IVUf5:-MHDdjFJAD471t3IVUf6:bz1p3ea) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L52)):*
> ```Java
>     EC_CURVE, // uses a curve other than P-256
>     NOT_YET_VALID, // certificate start date has not passed yet
>     VALIDITY_LENGTH // validity length is too long
> ```

`VALIDITY_PERIOD_TOO_LONG`?
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 61 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDdsbZAAFaYLmNbpAe:-MHDdsbZAAFaYLmNbpAf:b4l1bk3) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L61)):*
> ```Java
>   public ImmutableSet<CertificateViolation> checkCertificate(
>       X509Certificate certificate, Date now) {
>     ImmutableSet.Builder<CertificateViolation> violations = ImmutableSet.builder();
> ```

`new ImmutableSet.Builder<>()` for consistency with rest of codebase.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 74 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDe5h_BAsivGw5bAxQ:-MHDe5h_BAsivGw5bAxR:b-7n9o7q) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L74)):*
> ```Java
>       }
>     }
>     if (!checkValidityLength(certificate, maxValidityDays)) {
> ```

Maybe name this something akin to `isValidityLengthValid` or similar.  The other methods are prefixed with is to denote a boolean return type; that should be happening here as well for semantic parallelism.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 80 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDeXAf220yhki9r0cd:-MHDeXAf220yhki9r0ce:b-rq7ekg) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L80)):*
> ```Java
>     // Check Key Lengths
>     PublicKey key = certificate.getPublicKey();
>     switch (key.getAlgorithm()) {
> ```

There's only two cases here; an if/else if would be simpler.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 82 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDehSxEvnVbJawfVbm:-MHDehSxEvnVbJawfVbn:b-7gpc9q) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L82)):*
> ```Java
>     switch (key.getAlgorithm()) {
>       case "RSA":
>         if (!checkRsaKeyLength((RSAPublicKey) key, minimumRsaKeyLength)) {
> ```

Same comments regarding check vs is/has.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 99 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDepjXBKm8BZuoiMkt:-MHDepjXBKm8BZuoiMku:b-l4nw8t) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L99)):*
> ```Java
> 
>   private static boolean isExpired(X509Certificate certificate, Date now) {
>     return certificate.getNotAfter().before(now);
> ```

Most of these helper methods are so simple it really seems like they should be inlined.  Certainly any of the one-liners like this one.
___
*[util/src/main/java/google/registry/util/SelfSignedCaCertificate.java, line 101 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDh69G9fpAl_vGwOEp:-MHDh69G9fpAl_vGwOEq:b-tyalh) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/SelfSignedCaCertificate.java#L101)):*
> ```Java
>     ContentSigner signer;
>     if (keyPair.getPublic().getAlgorithm().equals("EC")) {
>       signer = new JcaContentSignerBuilder("SHA256WithECDSA").build(keyPair.getPrivate());
> ```

Rather than duplicating the same line 3 times with just a different String each time, extract the String.  So it'll be something like ...

```
String alg;
if (...) {
  alg = "...";
} else if (...) {
  alg = "...";
} else {
  alg = "...";
}
signer = new JcaContentSignerBuilder(alg).build(keyPair.getPrivate());
```

___
*[util/src/main/java/google/registry/util/SelfSignedCaCertificate.java, line 104 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDhRWH3QOZVNwsDdIs:-MHDhRWH3QOZVNwsDdIt:bpds88t) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8f [...]

2020-09-15 02:37 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 75 of 77 files reviewed, 16 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 126 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGqAUmvArdJOHngmPyF:-MHE_uuc95gCa8R2pkdz:b-f97i38) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L126)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

It looks to me like al P-256 curves are over prime fields
</blockquote></details>

yes, all P-256 curves are over prime fields. I meant that we should create a curve over 2^m field and make sure that it fails this test. So just picking any F2m curve should do the job I think? 
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 78 at r2](https://reviewable.io/reviews/google/nomulus/793#-MGudnAZ2ST1gH3JBZz_:-MHEaayb4-aTQKZBa0yO:bulygo3) ([raw file](https://github.com/google/nomulus/blob/df31e4caca2a057ecf1eb8e3984f53eaec48264f/util/src/main/java/google/registry/util/CertificateChecker.java#L78)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it?
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 130 at r2](https://reviewable.io/reviews/google/nomulus/793#-MGue3_y6d2HaFClvhB7:-MHEbpLz7_t6opGTJa5-:b-4dwh1w) ([raw file](https://github.com/google/nomulus/blob/df31e4caca2a057ecf1eb8e3984f53eaec48264f/util/src/main/java/google/registry/util/CertificateChecker.java#L130)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why am I not seeing the change? Did you push the latest commit?
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 134 at r2](https://reviewable.io/reviews/google/nomulus/793#-MGuezSa7e6yc-GN5GqU:-MHE_WYvB5WpALLyc48I:b3pfk5w) ([raw file](https://github.com/google/nomulus/blob/df31e4caca2a057ecf1eb8e3984f53eaec48264f/util/src/main/java/google/registry/util/CertificateChecker.java#L134)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

spec.getCurve().getField() does not return and ECFieldFP type, but instead it returns a FiniteField type. I added a variable that cast it to an ECFieldFp
</blockquote></details>

Interesting. I see here that `EcllipticCurve.getField` returns an `ECField`.

https://source.corp.google.com/piper///depot/google3/third_party/java_src/jdk/openjdk8/u60/trunk/jdk/src/share/classes/java/security/spec/EllipticCurve.java;rcl=229163191;l=130

But anyway, it compiles so I guess it runs :D
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 36 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDfFhe51Cl-jr5Fujd:-MHEZJwjEBSxF-C7ewbn:bvyrfaw) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L36)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You would need `@Config(...)` annotations on all of these to actually load them from the config file properly; Dagger doesn't know how to separate these raw ints on its own.  And you'll similarly need to actually add these new config options to the config file.

But the larger problem is that the core subproject (where all the config stuff lives) depends on the util subproject, and not the other way around.  So it's not even possible to do it this way.  Thus you can't `@Inject` it; you'll have to have an `@Provides` method somewhere in the core package that itself depends on the 3 relevant `@Config` options.

This should probably therefore not be a public constructor, but rather, a public static `create()` method (which is preferred over constructors by Effective Java).
</blockquote></details>

I agree with what Ben said. Though actually setting up dependency injection can wait till the next PR. In this one we just need to remove the `@Inject` annotation.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 80 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDeXAf220yhki9r0cd:-MHEaf984SF2scO0F5Ho:b-oifctb) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L80)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There's only two cases here; an if/else if would be simpler.
</blockquote></details>

Actually I think there's a bug when we fall through to default. If the certificate is not RSA or ECDSA we should add a `DISALLOWED_CERTIFICATE_ALGORITHM` enum to the violations.


<!-- Sent from Reviewable.io -->

2020-09-16 03:14 UTC, jianglai requested changes
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 76 of 77 files reviewed, 15 unresolved discussions (waiting on @CydeWeys, @Inject, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 126 at r1](https://reviewable.io/reviews/google/nomulus/793#-MGqAUmvArdJOHngmPyF:-MHJkEJU32SjCz_ubuBa:b-diq1bq) ([raw file](https://github.com/google/nomulus/blob/df94ce0f225f3fa11292109d417ce814d2b7e71f/util/src/main/java/google/registry/util/CertificateChecker.java#L126)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Do you think I should make this a separate type of violation?
</blockquote></details>

I think `ELLIPTIC_CURVE_NOT_ALLOW` is appropriate. We are requiring a specific elliptic curve (P-256), so using a curve over 2^m field is not allowed.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 134 at r2](https://reviewable.io/reviews/google/nomulus/793#-MGuezSa7e6yc-GN5GqU:-MHJkhqg096P3UoTwQyz:b-pz8o9m) ([raw file](https://github.com/google/nomulus/blob/df31e4caca2a057ecf1eb8e3984f53eaec48264f/util/src/main/java/google/registry/util/CertificateChecker.java#L134)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

This is using the type ECCurve, not EllipticCurve
</blockquote></details>

Doesn't `ECparameterSpec.getCurve()` return a `EllipticCurve`?

https://source.corp.google.com/piper///depot/google3/third_party/java_src/jdk/openjdk8/u60/trunk/jdk/src/share/classes/java/security/spec/ECParameterSpec.java;l=86
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 45 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHJtQ49DVU89GSgJ3uY:-MHJtQ49DVU89GSgJ3uZ:bmv4a7w) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L45)):*
> ```
> CertificateViolation
> ```
A problem with using Enums is that we lose the information on the exact offending value. e. g. we don't know what is the RSA key length, we only know that it is lower than 2048. I can foresee this being a problem for us during debugging, when a client asks why is their connection not getting through.

Maybe making them subclasses of a `CertificateViolationException` is better?
___
*[util/src/main/java/google/registry/util/SelfSignedCaCertificate.java, line 113 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHJkz3M7fcVL3WiN14n:-MHJkz3M7fcVL3WiN14o:bdhfot4) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/SelfSignedCaCertificate.java#L113)):*
> ```
> Unecpected
> ```
Unexpected


<!-- Sent from Reviewable.io -->

2020-09-16 03:51 UTC, jianglai reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 14 unresolved discussions (waiting on @CydeWeys, @Inject, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 45 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHJtQ49DVU89GSgJ3uY:-MHK1A4j8Mrk8p_Prp3Y:b3pfms0) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L45)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> CertificateViolation
> ```
A problem with using Enums is that we lose the information on the exact offending value. e. g. we don't know what is the RSA key length, we only know that it is lower than 2048. I can foresee this being a problem for us during debugging, when a client asks why is their connection not getting through.

Maybe making them subclasses of a `CertificateViolationException` is better?
</blockquote></details>

OK, maybe not an exception, as we don't throw these. But we still need `CertificateViolation` to be a normal class other than an enum to be more flexible for the reason I mentioned above.


<!-- Sent from Reviewable.io -->

2020-09-17 22:14 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 7 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 80 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDeXAf220yhki9r0cd:-MHT4jto7k6Hsf5ey4bb:b-8b5pw2) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L80)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still don't understand why this isn't just

```
if { ... }
else if { ... }
else { ... }
```

That'd be much fewer lines of code for identical functionality, no?
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 99 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHT6qMM7mllCjgG3mQs:-MHT6qMM7mllCjgG3mQt:b-v0rd2a) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L99)):*
> ```Java
>   }
> 
>   /** Returns true if the validity period is 825 days or less. */
> ```

This comment isn't exactly correct; it's not using 825 days, but rather, whatever is passed into it.

Also, once we finalize our requirements, it's quite possible that this logic needs to be more complicated, e.g. certs created after so-and-so date have a max validity period of 825 days, and then certs created after so-and-so later date have a max validity period of 398 days, because this is how you phase in more stringent requirements.  So `maxValidityDays` ideally should be replaced with a map of DateTimes to ints, where each entry represents the concept of "Certificates issued on/after this time have this max validity length".

See e.g. https://chromium.googlesource.com/chromium/src/+/master/net/docs/certificate_lifetimes.md for what phased roll-in of tighter security requirements by issue date looks like.
___
*[util/src/main/java/google/registry/util/SelfSignedCaCertificate.java, line 101 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDh69G9fpAl_vGwOEp:-MHT5C1531UrpFftUCDw:bg7dsfw) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/SelfSignedCaCertificate.java#L101)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Rather than using a switch here, it seems like what you really want is a map of String to String.  Something like ...

```
  // Needs a better name than "ALGS".
  // Also you might want to use an ImmutableMap.Builder().put(...).put(...).put(...).build(); if this doesn't format well.
  private static final ImmutableMap<String, String> ALGS =
      ImmutableMap.of(
          "EC", "SHA256WithECDSA",
          "DSA", "SHA256WithDSA",
          "RSA", "SHA256WithRSAEncryption");
  ...

  // Now inside of createCaCert():
  checkArgument(ALGS.containsKey(publicKeyAlg), "...");
  String signatureAlgorithm = ALGs.get(publicKeyAlg);
```
___
*[util/src/main/java/google/registry/util/SelfSignedCaCertificate.java, line 113 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHT5QAj1SSkMFGANXwo:-MHT5QAj1SSkMFGANXwp:b-mrah67) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/SelfSignedCaCertificate.java#L113)):*
> ```Java
>         break;
>       default:
>         throw new RuntimeException("Unecpected public key algorithm");
> ```

How about IllegalArgumentException?  RuntimeException is super-generic.


<!-- Sent from Reviewable.io -->

2020-09-18 15:49 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 8 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 80 at r3](https://reviewable.io/reviews/google/nomulus/793#-MHDeXAf220yhki9r0cd:-MHWtpJQ8hGsKXFrOlrA:b-in5u2a) ([raw file](https://github.com/google/nomulus/blob/9367aa65e29f2a7a8fb5828cccd6c01745229746/util/src/main/java/google/registry/util/CertificateChecker.java#L80)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I still don't understand why this isn't just

```
if { ... }
else if { ... }
else { ... }
```

That'd be much fewer lines of code for identical functionality, no?
</blockquote></details>

Yeah, I agree that using ifs is probably easier on the eyes.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 99 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHT6qMM7mllCjgG3mQs:-MHWtwkj2zW6VQBeEM8c:bh8a41w) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L99)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This comment isn't exactly correct; it's not using 825 days, but rather, whatever is passed into it.

Also, once we finalize our requirements, it's quite possible that this logic needs to be more complicated, e.g. certs created after so-and-so date have a max validity period of 825 days, and then certs created after so-and-so later date have a max validity period of 398 days, because this is how you phase in more stringent requirements.  So `maxValidityDays` ideally should be replaced with a map of DateTimes to ints, where each entry represents the concept of "Certificates issued on/after this time have this max validity length".

See e.g. https://chromium.googlesource.com/chromium/src/+/master/net/docs/certificate_lifetimes.md for what phased roll-in of tighter security requirements by issue date looks like.
</blockquote></details>

Let's sort this out in the Tuesday meeting where we plan to finalize on the notification email.


<!-- Sent from Reviewable.io -->

2020-09-18 16:55 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 10 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 45 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHJtQ49DVU89GSgJ3uY:-MHWztnA2kuebq2JyATt:b-tst2v8) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L45)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

OK, maybe not an exception, as we don't throw these. But we still need `CertificateViolation` to be a normal class other than an enum to be more flexible for the reason I mentioned above.
</blockquote></details>

Yeah, they're definitely not exceptions, not only because they're not being thrown but also because we're building up an entire collection of these and returning them all at once (whereas exceptions only report the first error encountered).

Beyond that, given the additional complexity of your proposed approach, I'm not 100% worth it given how the added value of the information is pretty small.  Like, for example, the minimum RSA key length is 2048.  That's really clear, both in the documentation and in the error message for these enums (not added yet but it will have to be).  So whether an offending RSA cert happened to have a key length of 1024 or 1536 doesn't *really* matter.  It doesn't affect the solution to the problem, which is that you have to generate a cert meeting the specs. 
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 46 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHX0M7bASB9slSj48bd:-MHX0M7bASB9slSj48be:btiz5ba) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L46)):*
> ```Java
>    */
>   public enum CertificateViolation {
>     EXPIRED,
> ```

One thing I think we might want for all of these is a display message, depending on how these are being used anyway.  Imagine we're running this checker in the upload path for a new SSL cert in the registrar console.  We can't just return a display message saying "RSA_KEY_LENGTH_TOO_SMALL, VALIDITY_PERIOD_TOO_LONG"; we need some human-friendly readable messages that explain exactly what's wrong.  E.g. for RSA_KEY_LENGTH_TOO_SMALL that would be something like "RSA key length must be at least 2,048 bits".

See `RegistrarContact.Type` for an example of an enum that uses a display string.  In this particular case I think the display string should be called `displayMessage` or similar.  Basically, the messages that you currently have as inline comments should instead be actual strings that can be used by other parts of the program (and cleaned up just a tad to include all the relevant information, and proper sentence formatting).
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 47 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHX4Y35CZh5NcnCkcPP:-MHX4Y35CZh5NcnCkcPQ:b-i2jbvz) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L47)):*
> ```Java
>   public enum CertificateViolation {
>     EXPIRED,
>     NEARING_EXPIRATION, // less than 30 days to expiration
> ```

I'm seeing a potential issue with this one.  Every other enum value here is legitimately a Certificate *Violation*, as the name of the enum implies.  If any single one of these others is encountered, then the cert is invalid and won't be accepted.

But `NEARING_EXPIRATION` isn't a violation, it's just a warning.  So we end up with some special-casing behavior that'd be best to avoid.  E.g. consider the following cases for the return value of `checkCertificate()` and what that means:

```
()                                              --> cert is valid
(EXPIRED)                                       --> cert is invalid
(NOT_YET_VALID, RSA_KEY_LENGTH_TOO_SMALL)       --> cert is invalid
(NEARING_EXPIRATION)                            --> cert is valid (?!?!)
(NEARING_EXPIRATION, VALIDITY_PERIOD_TOO_LONG)  --> cert is invalid       
``` 

So basically, the way this is currently designed, requires special-casing a return value of a set containing only `NEARING_EXPIRATION`, which I don't think is ideal nor expected.  There's a variety of ways to solve this issue -- each enum value could have a severity level of WARNING or ERROR (which would be another field added to the enum along with `displayMessage` from my previous comment).  Or we could have two separate methods instead of just `checkCertificate`, one that returns all errors and one that returns all errors and all warnings.  Or two separate enums entirely and two versions of `checkCertificate`, one that returns only errors and one that returns only warnings.  Or if this is the only envisioned warning, we could special case it out entirely and not have it be in the enum at all, and just be a concern for a different method `boolean isCertificateExpiringSoon(...)` that would be used only in cases where we have a display path to reflect the result to (e.g. registrar uploads through the console).

I guess I'm slightly preferring adding another field for WARNING vs ERROR, and then having two methods instead of just `checkCertificate` as follows:

```
// Returns all warnings and errors; responsibility is on the caller to deal with them.
ImmutableSet<CertificationViolation> checkCertificate(...);

// Helper method that returns true iff checkCertificate() above returns 0 errors.
// This would be used e.g. by the proxy when a new connection is established.
boolean isCertificateValid(...);
```

But what are your thoughts?
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 99 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHT6qMM7mllCjgG3mQs:-MHX7ch-7h2FoFB-Ez_G:bww0tqw) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L99)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Let's sort this out in the Tuesday meeting where we plan to finalize on the notification email.
</blockquote></details>

SGTM.  I'm pretty sure though that we don't want to immediately invalidate the good majority of our partner certs even though they were adhering to all SSL cert security best practices at the time at which they were issued.  Browsers don't do this for good reason; the upgrade path is carefully designed such that you only ever need to change things upon next renewal, rather than being forced into additional renewals that you weren't otherwise going to be facing.


<!-- Sent from Reviewable.io -->

2020-09-20 02:43 UTC, jianglai requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 134 at r2](https://reviewable.io/reviews/google/nomulus/793#-MGuezSa7e6yc-GN5GqU:-MHdNjUACzdq-hhjaCML:b-ogltoi) ([raw file](https://github.com/google/nomulus/blob/df31e4caca2a057ecf1eb8e3984f53eaec48264f/util/src/main/java/google/registry/util/CertificateChecker.java#L134)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

This is using https://source.corp.google.com/piper///depot/google3/third_party/java_src/bouncycastle_bcprov/v1_65/java/org/bouncycastle/jce/spec/ECParameterSpec.java?q=org.bouncycastle.jce.spec.ECParameterSpec&sq=package:piper%20file:%2F%2Fdepot%2Fgoogle3%20-file:google3%2Fexperimental

Regardless, I looked into this a little more and spec.getCurve.getfield.getDimension returns 1 if the curve is over a prime field and 2 if the curve is over a 2^m field. I added a check for this to isEcCurveTypeValid() 
</blockquote></details>

Ah I see. Thanks!
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 45 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHJtQ49DVU89GSgJ3uY:-MHdJPxa6X2rpaxXLj2_:b-cg0efb) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L45)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I added in display messages, but I made the messages more generic since minimumRsaKeyLength, daysToExpiration, and maxValidityDays are not  static values.
</blockquote></details>

We definitely want the error message to show exactly what is expected. I think this is another reason why a normal class is preferable than enums. 
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 47 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHX4Y35CZh5NcnCkcPP:-MHdMDCy3feSoqXmS2Ia:b-7xjkxt) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L47)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Yes, my original plan was to have the caller check the response to see if it contains only NEARING_EXPIRATION, but I see how that is not ideal. I'm not sure though that creating a distinction between Warnings and Errors is necessary, since I don't anticipate there being anything else we will need to warn about besides nearing expiration. 

Although, if we do decide to enforce the new requirements in phases, perhaps it could be useful being able to initially label all of the violations as warnings and then change them to errors as we begin enforcing them. But as I recall, our intention is to begin enforcing all the new requirements at the same time. 

I am leaning towards just keeping the enum as is without adding a warning/error value and removing NEARING_EXPIRATION and adding a second method to this class isCertificateExpiringSoon() that can be called if checkCertificate() returns an empty set.
</blockquote></details>

I think removing `NEARING_EXPIRATION` as an enum and adding a second (boolean) method is preferable. The reason being that it is unlikely that we check all the the other violations together with `NEARNING_EXPIRATION`, which will run as a background job periodically and send warning emails. For all other "real" violations, we will need to perform the check synchronously at the time of the connection. So it make sense to separate them to two different methods.

I also doubt that we will enforce the restrictions pertaining to certificates in phases. We will first enforce connection restrictions (TLS version, cipher suite), then the certificate restrictions. But it doesn't make much sense to gradually roll out enforcement on the different certificate violations because if a certificate is in violation, a new one would need to be generated and provided to us. It is much easier to tell registrars **all** the requirements and have them generate a compliant certificate, instead of telling them piecemeal and risk subjecting them to multiple iterations of certificate issurance.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 126 at r5](https://reviewable.io/reviews/google/nomulus/793#-MHdNu-I-d42O-_kJVit:-MHdNu-I-d42O-_kJViu:bnxvlcx) ([raw file](https://github.com/google/nomulus/blob/38d9ae59a9e1dc68ad7b8be1cf045d872e20bdf3/util/src/main/java/google/registry/util/CertificateChecker.java#L126)):*
> ```
> getDimension() == 1
> ```
Add some comment. No one knows that dimension = 1 means...


<!-- Sent from Reviewable.io -->

2020-09-20 02:44 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 8 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 99 at r4](https://reviewable.io/reviews/google/nomulus/793#-MHT6qMM7mllCjgG3mQs:-MHdOX4i9WDDGTo49Kpz:bb6ywmx) ([raw file](https://github.com/google/nomulus/blob/1fde32abda652cd8408dbca981f8b4c1a2a481ed/util/src/main/java/google/registry/util/CertificateChecker.java#L99)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

SGTM.  I'm pretty sure though that we don't want to immediately invalidate the good majority of our partner certs even though they were adhering to all SSL cert security best practices at the time at which they were issued.  Browsers don't do this for good reason; the upgrade path is carefully designed such that you only ever need to change things upon next renewal, rather than being forced into additional renewals that you weren't otherwise going to be facing.
</blockquote></details>

LGTM


<!-- Sent from Reviewable.io -->

2020-09-24 02:41 UTC, jianglai requested changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 76 of 77 files reviewed, 11 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 63 at r6](https://reviewable.io/reviews/google/nomulus/793#-MHxxHxQ5uMYGQUNR4nb:-MHxxHxQ5uMYGQUNR4nc:b-ma0kob) ([raw file](https://github.com/google/nomulus/blob/d65a8ad2aa835e07f96340441cb0864736bf8b23/util/src/main/java/google/registry/util/CertificateChecker.java#L63)):*
> ```
> maxValidityDays, validityLength
> ```
I think we should be consistent in our error message. If we don't customize it for individual violations (for example in `NotYetValidViolation` we didn't say when the `notBefore` data is), we shouldn't include the `validityLength` either.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 72 at r6](https://reviewable.io/reviews/google/nomulus/793#-MHxxafE3OREbJ406p2R:-MHxxafE3OREbJ406p2S:bi9zvnx) ([raw file](https://github.com/google/nomulus/blob/d65a8ad2aa835e07f96340441cb0864736bf8b23/util/src/main/java/google/registry/util/CertificateChecker.java#L72)):*
> ```
> rsaPublicKey.getModulus().bitLength()
> ```
Same comment as above.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 85 at r6](https://reviewable.io/reviews/google/nomulus/793#-MHxxos96K4P4iw3Fsyx:-MHxxos96K4P4iw3Fsyy:b-lboncx) ([raw file](https://github.com/google/nomulus/blob/d65a8ad2aa835e07f96340441cb0864736bf8b23/util/src/main/java/google/registry/util/CertificateChecker.java#L85)):*
> ```
> check
> ```
Should still be "is".
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 93 at r6](https://reviewable.io/reviews/google/nomulus/793#-MHxxwUO0AmO3iO1HRh7:-MHxxwUO0AmO3iO1HRh8:b-n8m7t9) ([raw file](https://github.com/google/nomulus/blob/d65a8ad2aa835e07f96340441cb0864736bf8b23/util/src/main/java/google/registry/util/CertificateChecker.java#L93)):*
> ```
> getValidityLength
> ```
`getValidityLengthInDays`.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 135 at r6](https://reviewable.io/reviews/google/nomulus/793#-MHxyo3bAxl9J6YjbT5a:-MHxyo3bAxl9J6YjbT5b:b-ia3ld0) ([raw file](https://github.com/google/nomulus/blob/d65a8ad2aa835e07f96340441cb0864736bf8b23/util/src/main/java/google/registry/util/CertificateChecker.java#L135)):*
> ```
> equals
> ```
Would it be easier if we use `AutoValue` to implement the `CertificateViolation`? It would get rid of boilerplates like the `equals` method.


<!-- Sent from Reviewable.io -->

2020-09-25 18:07 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 75 of 77 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 40 at r7](https://reviewable.io/reviews/google/nomulus/793#-MI5PXnZ5gVI51W8iXI6:-MI5PXnZ5gVI51W8iXI7:b-vj5jgw) ([raw file](https://github.com/google/nomulus/blob/4add7d9fcb56babd44fec1b7a4c7863eec077757/util/src/main/java/google/registry/util/CertificateChecker.java#L40)):*
> ```Java
>       int daysToExpiration,
>       int minimumRsaKeyLength,
>       ImmutableSet<Integer> curves) {
> ```

This should be something like `ImmutableSet<String> allowedEcCurves`.  Curves have names, e.g. NIST P-256 is different from secp256k1.  It's not clear how using just the number 256 could differentiate between the two.  And there's also apparently an secp256r1.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 106 at r7](https://reviewable.io/reviews/google/nomulus/793#-MI5PxuL7n_3xCCbsk0W:-MI5PxuL7n_3xCCbsk0X:b-ohsqsl) ([raw file](https://github.com/google/nomulus/blob/4add7d9fcb56babd44fec1b7a4c7863eec077757/util/src/main/java/google/registry/util/CertificateChecker.java#L106)):*
> ```Java
>         return false;
>       }
>       return curves.contains(spec.getCurve().getOrder().bitLength());
> ```

Is this actually checking the name of the curve?  Or just its bit length?  It looks like it's doing the latter, but we want the former.  There are lots of curves that share e.g. a 256 bit key length, but we only specifically want to accept the NIST P-256 curve.  This looks to be surprisingly hard to do, e.g. here's one random apparent solution based on a minute of Googling: https://stackoverflow.com/a/49937941/31040  (We'd want to do more research before just using that approach.)


<!-- Sent from Reviewable.io -->

2020-09-25 18:14 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 75 of 77 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 106 at r7](https://reviewable.io/reviews/google/nomulus/793#-MI5PxuL7n_3xCCbsk0W:-MI5TJ8uAZ4o0QyKA-uv:b-6p0fte) ([raw file](https://github.com/google/nomulus/blob/4add7d9fcb56babd44fec1b7a4c7863eec077757/util/src/main/java/google/registry/util/CertificateChecker.java#L106)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is this actually checking the name of the curve?  Or just its bit length?  It looks like it's doing the latter, but we want the former.  There are lots of curves that share e.g. a 256 bit key length, but we only specifically want to accept the NIST P-256 curve.  This looks to be surprisingly hard to do, e.g. here's one random apparent solution based on a minute of Googling: https://stackoverflow.com/a/49937941/31040  (We'd want to do more research before just using that approach.)
</blockquote></details>

Bleagh there just don't seem to be great ways to do anything related to getting the actual curve names ... https://stackoverflow.com/a/54627737/31040


<!-- Sent from Reviewable.io -->

2020-09-26 03:17 UTC, jianglai requested changes
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 76 of 77 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 135 at r6](https://reviewable.io/reviews/google/nomulus/793#-MHxyo3bAxl9J6YjbT5a:-MI7N7CF7iWw22SEcjej:b1r5hqg) ([raw file](https://github.com/google/nomulus/blob/d65a8ad2aa835e07f96340441cb0864736bf8b23/util/src/main/java/google/registry/util/CertificateChecker.java#L135)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I don't think so because you can't extend an autovalue class https://github.com/google/auto/blob/master/value/userguide/howto.md#inherit
</blockquote></details>

What I meant was that to have an `AutoValue` class of `CertificateViolation`, which contains field `name` and `message`. We then can create instances of the class (not subclasses).

Sorry that we have to go from enums to subclasses to instances. Now that I think about it, since these are essentially value classes, subclassing doesn't really buy us anything that multiple instances give us. The original idea of using Enum would have sufficed had we not want to be able to customize the error message at runtime. Using immutable value classes (AutoValue) seems to be the best middle ground and it does cut down the boilerplate one has to write.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 40 at r7](https://reviewable.io/reviews/google/nomulus/793#-MI5PXnZ5gVI51W8iXI6:-MI7L35S6fw257l3Ihnl:broz9dm) ([raw file](https://github.com/google/nomulus/blob/4add7d9fcb56babd44fec1b7a4c7863eec077757/util/src/main/java/google/registry/util/CertificateChecker.java#L40)):*
> secp256r1
`secp256r1` is the NIST P-256 curve (https://tools.ietf.org/search/rfc4492#appendix-A). I think we should probably update the email draft to use the exact string instead of "NIST P-256".

I know that we can create keys using the string `secp256r1`, as shown in the tests. Can we do the opposite and extract this string from a certificate? That would make testing this condition much easier.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 106 at r7](https://reviewable.io/reviews/google/nomulus/793#-MI5PxuL7n_3xCCbsk0W:-MI7MRwP2mdL1xwo6Oze:b47nfym) ([raw file](https://github.com/google/nomulus/blob/4add7d9fcb56babd44fec1b7a4c7863eec077757/util/src/main/java/google/registry/util/CertificateChecker.java#L106)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

spent a couple hours looking into this, and unfortunately that does look like the best way to do it
</blockquote></details>

I have to say, given the number of hours we collectively spent on this, and the fact that no registrar is actually using ECDSA certs, maybe we should consider only supporting RSA at the moment. If we encounter strong push backs from registrars, we can then spend even more time on supporting ECDSA. Or we should relax our requirement and allow any P-256 and P-384 curves.

Thoughts? 


<!-- Sent from Reviewable.io -->

2020-09-28 20:23 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 76 of 77 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 106 at r7](https://reviewable.io/reviews/google/nomulus/793#-MI5PxuL7n_3xCCbsk0W:-MILMmd_6nvlA6-fXYDk:b-2xen65) ([raw file](https://github.com/google/nomulus/blob/4add7d9fcb56babd44fec1b7a4c7863eec077757/util/src/main/java/google/registry/util/CertificateChecker.java#L106)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I have to say, given the number of hours we collectively spent on this, and the fact that no registrar is actually using ECDSA certs, maybe we should consider only supporting RSA at the moment. If we encounter strong push backs from registrars, we can then spend even more time on supporting ECDSA. Or we should relax our requirement and allow any P-256 and P-384 curves.

Thoughts? 
</blockquote></details>

We could just allow all ECDSA certs for now and reserve the option to restrict them in the future.  If someone is using ECDSA it's likely they already know what they're doing.  So say we support X, Y, and Z curves, but don't enforce it (yet?) and just allow all curves, and then if we need to later on we can actually add in the validation for X, Y, and Z if necessary.


<!-- Sent from Reviewable.io -->

2020-09-29 02:38 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: 76 of 77 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 106 at r7](https://reviewable.io/reviews/google/nomulus/793#-MI5PxuL7n_3xCCbsk0W:-MIMholECjvbSYAiEpcn:b7t6wj2) ([raw file](https://github.com/google/nomulus/blob/4add7d9fcb56babd44fec1b7a4c7863eec077757/util/src/main/java/google/registry/util/CertificateChecker.java#L106)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

We could just allow all ECDSA certs for now and reserve the option to restrict them in the future.  If someone is using ECDSA it's likely they already know what they're doing.  So say we support X, Y, and Z curves, but don't enforce it (yet?) and just allow all curves, and then if we need to later on we can actually add in the validation for X, Y, and Z if necessary.
</blockquote></details>

Actually, I tried the second SO link you provided. We can get the OID of the public key as suggested in the answer and map the OID to curve names. There is a 1:1 mapping (from running the code in your first SO link):

```
[secp256r1,NIST P-256,X9.62 prime256v1,1.2.840.10045.3.1.7]
[secp384r1,NIST P-384,1.3.132.0.34]
```

OID is the last part.


<!-- Sent from Reviewable.io -->

2020-09-30 03:28 UTC, jianglai approved these changes
> Reviewed 54 of 54 files at r8.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 50 at r8](https://reviewable.io/reviews/google/nomulus/793#-MIS1Sk80y85EL9rCk7C:-MIS1Sk80y85EL9rCk7D:bgcuzxk) ([raw file](https://github.com/google/nomulus/blob/c3c7ef100822b77dedcb5d4307f97b32d70118cf/util/src/main/java/google/registry/util/CertificateChecker.java#L50)):*
> ```
> violations.add(
>           CertificateViolation.create("Expired Certificate", "This certificate is expired."));
> ```
Might be easier to make create these instances in the constructor and have getters for them when you need to refer to them outside the class. Saves you the trouble of creating them every time in the test.
___
*[util/src/test/java/google/registry/util/CertificateCheckerTest.java, line 86 at r8](https://reviewable.io/reviews/google/nomulus/793#-MIS2QZdEvCSTgPy5rS_:-MIS2QZdEvCSTgPy5rSa:b-219yvu) ([raw file](https://github.com/google/nomulus/blob/c3c7ef100822b77dedcb5d4307f97b32d70118cf/util/src/test/java/google/registry/util/CertificateCheckerTest.java#L86)):*
> ```
>     assertThat(violations).hasSize(1);
>     assertThat(violations.iterator().next().name()).isEqualTo("Expired Certificate");
> ```
If you do what I suggested in the other comment, you can do assertThat().containsExactly() here, and in other tests.


<!-- Sent from Reviewable.io -->

2020-09-30 03:30 UTC, jianglai requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 57 at r8](https://reviewable.io/reviews/google/nomulus/793#-MIS2pxS1YMbviRGdOHI:-MIS2pxS1YMbviRGdOHJ:b-bu7xy6) ([raw file](https://github.com/google/nomulus/blob/c3c7ef100822b77dedcb5d4307f97b32d70118cf/util/src/main/java/google/registry/util/CertificateChecker.java#L57)):*
> ```
> if (validityLength > maxValidityDays)
> ```
Didn't we say we want to have two `maxValidityDays` depending on when the certificate is issued?


<!-- Sent from Reviewable.io -->

2020-10-01 01:51 UTC, jianglai approved these changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 86 at r9](https://reviewable.io/reviews/google/nomulus/793#-MIWqYZDAexE-WCq_Q7A:-MIWqYZE8YEVvs6B_ncj:b-r3jgc0) ([raw file](https://github.com/google/nomulus/blob/e5fe2451ed47bfcd6eb01ef8c71883f4c2ee92c4/util/src/main/java/google/registry/util/CertificateChecker.java#L86)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>       if (certificate.getNotBefore().before(DateTime.parse("2020-09-01T00:00:00Z").toDate())) {
>         if (validityLength > 825) {
>           violations.add(certificateOldValidityLengthValidViolation);
>         }
> ```
</details>

This could be just `if (a && b)`, right?


<!-- Sent from Reviewable.io -->

2020-10-01 19:02 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 3 unresolved discussions (waiting on @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 32 at r10](https://reviewable.io/reviews/google/nomulus/793#-MI_XSZ14KgC16jveGHV:-MI_XSZ14KgC16jveGHW:b-sxb1zr) ([raw file](https://github.com/google/nomulus/blob/3d68a565847b4fda941d2e5bea0821a23c3e9a0a/util/src/main/java/google/registry/util/CertificateChecker.java#L32)):*
> ```Java
>   private final int daysToExpiration;
>   private final int minimumRsaKeyLength;
>   public final CertificateViolation certificateExpiredViolation;
> ```

These can be static, right?  And if so, they should be initialized statically here (and once), rather than in every constructor call.

But see my below comment on enums first.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 131 at r10](https://reviewable.io/reviews/google/nomulus/793#-MI_WkYT5EC67NY7MQp9:-MI_WkYT5EC67NY7MQpA:b-gy655q) ([raw file](https://github.com/google/nomulus/blob/3d68a565847b4fda941d2e5bea0821a23c3e9a0a/util/src/main/java/google/registry/util/CertificateChecker.java#L131)):*
> ```Java
>  */
> @AutoValue
> abstract class CertificateViolation {
> ```

Remind me again why this isn't just an enum with two fields per my earlier suggestion?  I don't see anything here as written that would necessitate using an `@AutoValue` class.


<!-- Sent from Reviewable.io -->

2020-10-06 15:44 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793)* status: all files reviewed, 6 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 86 at r9](https://reviewable.io/reviews/google/nomulus/793#-MIWqYZDAexE-WCq_Q7A:-MIyYORT7wLWcA8Gr4xE:ba78vjc) ([raw file](https://github.com/google/nomulus/blob/e5fe2451ed47bfcd6eb01ef8c71883f4c2ee92c4/util/src/main/java/google/registry/util/CertificateChecker.java#L86)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>       if (certificate.getNotBefore().before(DateTime.parse("2020-09-01T00:00:00Z").toDate())) {
>         if (validityLength > 825) {
>           violations.add(certificateOldValidityLengthValidViolation);
>         }
> ```
This could be just `if (a && b)`, right?
</blockquote></details>

That would introduce a bug -- the else clause below would have to be modified as well.  It's probably simpler the way it is here.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 32 at r10](https://reviewable.io/reviews/google/nomulus/793#-MI_XSZ14KgC16jveGHV:-MIyWoS_3JmrS-Y-65eA:b-o0uacz) ([raw file](https://github.com/google/nomulus/blob/3d68a565847b4fda941d2e5bea0821a23c3e9a0a/util/src/main/java/google/registry/util/CertificateChecker.java#L32)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

No because the messages rely on the validity days/ keylength/days to expiration values passed to the constructor
</blockquote></details>

I have some further ideas on how to improve this but I'm not 100% sure they'll work and I don't want to keep dragging this review on for a relatively unimportant code style issue, so I'll approve for now and then I might send you a subsequent PR to modify this if one of my ideas pans out.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 52 at r10](https://reviewable.io/reviews/google/nomulus/793#-MIyVxLE0wIXK4SILRJK:-MIyVxLF2behOZbTL8dd:b-5wmcdw) ([raw file](https://github.com/google/nomulus/blob/3d68a565847b4fda941d2e5bea0821a23c3e9a0a/util/src/main/java/google/registry/util/CertificateChecker.java#L52)):*
> ```Java
>             "Validity Period Too Long",
>             String.format(
>                 "The certificate must have a validity length of less than %d days if created"
> ```

This is worded in a slightly confusing way, in that it talks about before September 1 and after it, but not on it.  It also puts the old deprecated validity period that is being phased out first, when it should go last.   How about:

"The certificate's validity length must be less than or equal to 398 days, or 825 days if issued prior to 2020-09-01."
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 86 at r10](https://reviewable.io/reviews/google/nomulus/793#-MIyXQFw1M6XIeJUS0GK:-MIyXQFw1M6XIeJUS0GL:b-ug18ef) ([raw file](https://github.com/google/nomulus/blob/3d68a565847b4fda941d2e5bea0821a23c3e9a0a/util/src/main/java/google/registry/util/CertificateChecker.java#L86)):*
> ```Java
>     int validityLength = getValidityLengthInDays(certificate);
>     if (validityLength > maxValidityDays) {
>       if (certificate.getNotBefore().before(DateTime.parse("2020-09-01T00:00:00Z").toDate())) {
> ```

Can we do this the other way around?  I.e. convert the `Date` on the certificate to a `DateTime`, and then use `DateTime` logic to compare the two?  I trust `DateTime` more because it's what we use elsewhere in our codebase and thus we have more familiarity with its functions than with `Date`.
___
*[util/src/test/java/google/registry/util/CertificateCheckerTest.java, line 82 at r10](https://reviewable.io/reviews/google/nomulus/793#-MIyYfgk7oUGMTBLo0Ev:-MIyYfgk7oUGMTBLo0Ew:ba5gshb) ([raw file](https://github.com/google/nomulus/blob/3d68a565847b4fda941d2e5bea0821a23c3e9a0a/util/src/test/java/google/registry/util/CertificateCheckerTest.java#L82)):*
> ```Java
>     ImmutableSet<CertificateViolation> violations =
>         certificateChecker.checkCertificate(certificate, DateTime.now(UTC).toDate());
>     assertThat(violations).containsExactly(certificateChecker.certificateExpiredViolation);
> ```

Yeah, see, this is really weird, relying on specific error object instances like this (that won't necessarily always even be exposed from the point of the callsite, which won't be in the same package like the test classes are).

Lai led you down the wrong path here with the suggestion to use class instances.  Sorry :(   I'll fix it.
___
*[util/src/main/java/google/registry/util/SelfSignedCaCertificate.java, line 17 at r10](https://reviewable.io/reviews/google/nomulus/793#-MIyZDAm29d1yvlI-_U_:-MIyZDAm29d1yvlI-_Ua:bre1eof) ([raw file](https://github.com/google/nomulus/blob/3d68a565847b4fda941d2e5bea0821a23c3e9a0a/util/src/main/java/google/registry/util/SelfSignedCaCertificate.java#L17)):*
> ```Java
> package google.registry.util;
> 
> import static com.google.appengine.repackaged.com.google.common.base.Preconditions.checkArgument;
> ```

This is the wrong import.  We shouldn't be using App Engine's repackaged version.
___
*[util/src/main/java/google/registry/util/SelfSignedCaCertificate.java, line 105 at r10](https://reviewable.io/reviews/google/nomulus/793#-MIy_JWT9SSdc2OBSpdf:-MIy_JWT9SSdc2OBSpdg:b-l1gw6t) ([raw file](https://github.com/google/nomulus/blob/3d68a565847b4fda941d2e5bea0821a23c3e9a0a/util/src/main/java/google/registry/util/SelfSignedCaCertificate.java#L105)):*
> ```Java
>       throws Exception {
>     X500Name owner = new X500Name("CN=" + fqdn);
>     ContentSigner signer;
> ```

Just move this down below where you assign `signer` a value?


<!-- Sent from Reviewable.io -->

2020-10-06 15:45 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/793#-:-MIy__XE3PVMG1bAGK22:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @jianglai and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2020-10-06 19:47 UTC, merged