Migrate Registry objects to a TLD table in Cloud SQL
google/nomulus pull request #803
Opened 2020-09-14 16:28 UTC by sarahcaseybot

2020-09-14 17:23 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/803)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @hstonec, and @sarahcaseybot)

___
*[db/src/main/resources/sql/flyway/V54__add_tld_table.sql, line 37 at r1](https://reviewable.io/reviews/google/nomulus/803#-MHCctsR8m6CBaoqen8o:-MHCctsR8m6CBaoqen8p:b12qbj3) ([raw file](https://github.com/google/nomulus/blob/0d2612d91a4af3d39aa5ab6dc43009f14eae1ea3/db/src/main/resources/sql/flyway/V54__add_tld_table.sql#L37)):*
> ```
> premium_list
> ```
How about using `premium_list_name`?
___
*[db/src/main/resources/sql/flyway/V54__add_tld_table.sql, line 55 at r1](https://reviewable.io/reviews/google/nomulus/803#-MHCbK8H90P0ZsxnVUad:-MHCbK8H90P0ZsxnVUae:bgmh0jx) ([raw file](https://github.com/google/nomulus/blob/0d2612d91a4af3d39aa5ab6dc43009f14eae1ea3/db/src/main/resources/sql/flyway/V54__add_tld_table.sql#L55)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> create table "Tld_reservedLists" (
>        tld_tld_name text not null,
>         reserved_lists text
>     );
> ```
</details>

Maybe we should just use an array column to store the associated reserved lists in Tld table, mainly because even we have a join table, we still cannot apply the foreign key constrains here because the reserved list name is not the primary key of `ReservedList` table.


<!-- Sent from Reviewable.io -->

2020-09-14 21:57 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/803)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @hstonec, and @sarahcaseybot)

___
*[db/src/main/resources/sql/flyway/V54__add_tld_table.sql, line 55 at r1](https://reviewable.io/reviews/google/nomulus/803#-MHCbK8H90P0ZsxnVUad:-MHDbMXbEWc5NAXsTs4s:b-fmdmqw) ([raw file](https://github.com/google/nomulus/blob/0d2612d91a4af3d39aa5ab6dc43009f14eae1ea3/db/src/main/resources/sql/flyway/V54__add_tld_table.sql#L55)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> create table "Tld_reservedLists" (
>        tld_tld_name text not null,
>         reserved_lists text
>     );
> ```
Maybe we should just use an array column to store the associated reserved lists in Tld table, mainly because even we have a join table, we still cannot apply the foreign key constrains here because the reserved list name is not the primary key of `ReservedList` table.
</blockquote></details>

Agreed that if an array column works, it's preferable to a join table.


<!-- Sent from Reviewable.io -->

2020-09-15 15:27 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/803)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @hstonec and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 382 at r2](https://reviewable.io/reviews/google/nomulus/803#-MHHMPTR4do3kDyR028c:-MHHMPTR4do3kDyR028d:b-bvw4gw) ([raw file](https://github.com/google/nomulus/blob/ae0d2d990d6697b15f78cca53c88896446d8f054/core/src/main/java/google/registry/model/registry/Registry.java#L382)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> /** The set of reserved lists that are applicable to this registry. */
>   @Transient Set<Key<ReservedList>> reservedLists;
>   @Column(name = "reserved_list_names", nullable = false)
>   Set<String> reservedListNames;
> ```
</details>

Can we try to reuse the `Set<Key<ReservedList>> reservedLists` by adding a converter? We can add a new converter(or change the existing `ReservedListKeyConverter` if it is no longer needed here) to extend `StringSetConverter`.


<!-- Sent from Reviewable.io -->

2020-09-16 16:20 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/803)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 105 at r3](https://reviewable.io/reviews/google/nomulus/803#-MHMgsFj0Ra1DqxahlcL:-MHMgsFj0Ra1DqxahlcM:bas9wf8) ([raw file](https://github.com/google/nomulus/blob/189df936c1820d59cc96e2e4c519f4383a8c7a86/core/src/main/java/google/registry/model/registry/Registry.java#L105)):*
> ```
> @Transient String tldStr;
> ```
Do we need to have a `@PostLoad` method to set this after the entity is loaded from Cloud SQL?

I actually don't quite understand why `testCloudSqlPersistence()` succeeded because `registry.tldStr` should have the correct value but `persisted.tldStr` should be null, how are they equal. Did I miss anything here?
___
*[core/src/main/java/google/registry/persistence/converter/ReservedListKeyConverter.java, line 25 at r3](https://reviewable.io/reviews/google/nomulus/803#-MHMezRqBJ18xlZraF7U:-MHMezRr574YHp1ZdApW:b-u9b17e) ([raw file](https://github.com/google/nomulus/blob/189df936c1820d59cc96e2e4c519f4383a8c7a86/core/src/main/java/google/registry/persistence/converter/ReservedListKeyConverter.java#L25)):*
> ```
> ReservedListKeyConverter
> ```
nit: Rename this to `ReservedListKeySetConverter` ?


<!-- Sent from Reviewable.io -->

2020-09-16 18:48 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/803)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/registry/Registry.java, line 105 at r3](https://reviewable.io/reviews/google/nomulus/803#-MHMgsFj0Ra1DqxahlcL:-MHNDqy6D6dVNXYcXf39:b-qslue3) ([raw file](https://github.com/google/nomulus/blob/189df936c1820d59cc96e2e4c519f4383a8c7a86/core/src/main/java/google/registry/model/registry/Registry.java#L105)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I'm not totally sure why it works either, but my guess is that it's because the tldStr is set to the tldName in the builder
</blockquote></details>

I tested this locally and I think what happened was the comparison was put in the same transaction which was used to save the entity, in this case, Hibernate returned the original entity object instead of fetching it from the actual database(which makes sense), if you changed the test to something like below you will see the error:

```
Registry registry =
        Registry.get("tld").asBuilder().setReservedLists(rl15).setPremiumList(pl).build();
    jpaTm().transact(() -> jpaTm().saveNew(registry));
    Registry persisted = jpaTm().transact(() -> jpaTm().load(VKey.createSql(Registry.class, registry.tldStrId)));
    assertThat(persisted).isEqualTo(registry);
```

I think the conclusion is we need to have a `@PostLoad` method to set the `tldStr` correctly.


<!-- Sent from Reviewable.io -->

2020-09-16 20:19 UTC, hstonec approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/803#-:-MHNZUnc2hbHtlQmyaYt:bnfp4nl)* status: 0 of 9 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-17 16:47 UTC, merged