Add delete expired domains action
google/nomulus pull request #836
Opened 2020-10-12 19:47 UTC by CydeWeys

This will be scheduled to run daily via App Engine cron in a subsequent PR.

2021-02-01 19:28 UTC, gbrodman requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/836)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 1 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSTxUpUCo0St5ESmo8D:-MSTxUpUCo0St5ESmo8E:ba0k3ej) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L1)):*
> ```Java
> // Copyright 2021 The Nomulus Authors. All Rights Reserved.
> ```

aha, 2021!
___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSTyB-62trm2dnEZNqO:-MSTyB-62trm2dnEZNqP:b-17pcxb) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L84)):*
> ```Java
>   DeleteExpiredDomainsAction(
>       EppController eppController,
>       @Config("registryAdminClientId") String registryAdminClientId,
> ```

nit: registrarId, not clientId right? at least in the variable name (if not config name)
___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 127 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSU32Mi3IspWxWikFtb:-MSU32Mi3IspWxWikFtc:b-g60lp0) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L127)):*
> ```Java
>     // Note: This query is (and must be) non-transactional, and thus, is only eventually consistent.
>     ImmutableList<DomainBase> domainsToDelete =
>         ofy().load().type(DomainBase.class).filter("autorenewEndTime <=", runTime).list().stream()
> ```

What about after we shift to SQL? 
___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 157 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSU0zyBBJzZSdpyMnqd:-MSU0zyBBJzZSdpyMnqe:bdxqd9d) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L157)):*
> ```Java
>                 () -> {
>                   DomainBase transDomain = tm().loadByKey(domain.createVKey());
>                   if (!domain.getAutorenewEndTime().isPresent()
> ```

This check (isPresent) is because the autorenew end time is treated as null in cases where there is no defined end (when it should be treated as END_OF_TIME) right? 


<!-- Sent from Reviewable.io -->

2021-02-01 22:10 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/836)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSTyB-62trm2dnEZNqO:-MSUcV6dCPVUzIKrvuif:b-5yhqxi) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L84)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit: registrarId, not clientId right? at least in the variable name (if not config name)
</blockquote></details>

The variable name should match the config name for clarity's sake.  Post-DB-migration, if we decide we want to fully change everything in the codebase from `clientId` to `registrarId`, we can do so, and at that point we'd rename this variable along with the named Dagger `@Config`.
___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 127 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSU32Mi3IspWxWikFtb:-MSUcmlv2ny-FRIqGK3R:b-700rq1) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L127)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What about after we shift to SQL? 
</blockquote></details>

We'll have to do this differently then.  (Same issue as with all the other mapreduces.)

Fortunately, this is a simple query that's even easier in Cloud SQL than in Datastore.
___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 157 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSU0zyBBJzZSdpyMnqd:-MSUd2dW5qT_1KZ4Ek7c:b188yc8) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L157)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This check (isPresent) is because the autorenew end time is treated as null in cases where there is no defined end (when it should be treated as END_OF_TIME) right? 
</blockquote></details>

`END_OF_TIME` will be returned as `empty` by `getAutorenewEndTime()`, hence this check, yes.  And yes, this one line of code might get simpler if `END_OF_TIME` weren't being coerced to empty, but more other lines of code elsewhere would get more complicated.


<!-- Sent from Reviewable.io -->

2021-02-01 22:16 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/836)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/test/java/google/registry/batch/DeleteExpiredDomainsActionTest.java, line 80 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSU84OKCMrdWjIlLSKs:-MSUeluoEvEslWvyIUoq:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/test/java/google/registry/batch/DeleteExpiredDomainsActionTest.java#L80)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Should also have a test for when there are multiple domains to delete.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-01 23:06 UTC, gbrodman approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/836)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSTyB-62trm2dnEZNqO:-MSUqIENBN4SyHjktTau:b-hiqjwf) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L84)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The variable name should match the config name for clarity's sake.  Post-DB-migration, if we decide we want to fully change everything in the codebase from `clientId` to `registrarId`, we can do so, and at that point we'd rename this variable along with the named Dagger `@Config`.
</blockquote></details>

Yeah, I suppose a large scale refactor then is quite simple. 
___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 127 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSU32Mi3IspWxWikFtb:-MSUoZq12os44cq89dNR:b8h1tik) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L127)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

We'll have to do this differently then.  (Same issue as with all the other mapreduces.)

Fortunately, this is a simple query that's even easier in Cloud SQL than in Datastore.
</blockquote></details>

This isn't a mapreduce but yeah; I'm not sure if we have a centralized repository of "random things that will need to be changed before we completely cut over" but this would probably go on it. 


<!-- Sent from Reviewable.io -->

2021-02-02 22:52 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/836)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 127 at r1](https://reviewable.io/reviews/google/nomulus/836#-MSU32Mi3IspWxWikFtb:-MSZvP-K-lIEpfG4_olZ:bylkjdw) ([raw file](https://github.com/google/nomulus/blob/4b106907c72e6c20ac06fc9d15a058671b4e338b/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L127)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This isn't a mapreduce but yeah; I'm not sure if we have a centralized repository of "random things that will need to be changed before we completely cut over" but this would probably go on it. 
</blockquote></details>

Yeah, I didn't mean "mapreduce" so much as "all async backend batch jobs", most (all?) of which are already conveniently located in the `batch` package where this one too is going.  We're definitely not likely to forget this one, and this migration can fortunately be solved pretty easily with some kind of dual-query DAO method with a signature like `List<DomainBase> findExpiredDomains()` that is aware of which DB is primary and runs the appropriate query (while also using the appropriate trans action manager's concept of "now").  But the mechanism of being aware of which DB is primary isn't quite in yet, and the migration path will be more complicated for many of the other batch jobs that the path I've laid out here, especially the ones that are currently mapreduces but later become SQL queries.  Realistically thus just need to be two entirely different codepaths that get executed based on which DB is primary.


<!-- Sent from Reviewable.io -->

2021-02-02 23:46 UTC, merged