Add certificate checks to RegistrarSettingsAction
google/nomulus pull request #843
Opened 2020-10-19 22:57 UTC by sarahcaseybot

2020-10-20 02:31 UTC, jianglai submitted a review, later dismissed
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/843)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java, line 338 at r1](https://reviewable.io/reviews/google/nomulus/843#-MK2e8TK70_ah04K2qCK:-MK2e8TK70_ah04K2qCL:b-tjtgak) ([raw file](https://github.com/google/nomulus/blob/9845658f0868594bd5867c2067378e48a372afd0/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L338)):*
> ```
>     if(tm().getTransactionTime().isBefore(DateTime.parse("2020-11-01T00:00:00Z"))){
>       return;
>     }
> ```
I suspect that by the time we deploy this change, it would have already been past 2020-11-01.

In any case, we should add a TODO to remove it.
___
*[core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java, line 343 at r1](https://reviewable.io/reviews/google/nomulus/843#-MK2j4NjEEraT-NNlZrp:-MK2j4NjEEraT-NNlZrq:bhdwp5z) ([raw file](https://github.com/google/nomulus/blob/9845658f0868594bd5867c2067378e48a372afd0/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L343)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     try {
>       certificate =
>           (X509Certificate)
>               CertificateFactory.getInstance("X509")
>                   .generateCertificate(new ByteArrayInputStream(certificateString.getBytes(UTF_8)));
>     } catch (CertificateException e) {
>       throw new IllegalArgumentException("Unable to read given certificate.");
>     }
> ```
</details>

It looks like we should just move this logic into the `checkCertificate` method. Instead of taking an `X509Certificate` as argument, it will take a `Certificate` and try to convert it to`X509Certificate` first. This way you don't need this conversion done here, as well as in the nomulus tool command. It also kinda make sense that the certificate checker only works with X509 certs, so if any other type of cert is provided, it should error out.


<!-- Sent from Reviewable.io -->

2020-10-22 15:37 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/843)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java, line 343 at r1](https://reviewable.io/reviews/google/nomulus/843#-MK2j4NjEEraT-NNlZrp:-MKFwkFQ397_v0U-PrHi:bhu53hk) ([raw file](https://github.com/google/nomulus/blob/9845658f0868594bd5867c2067378e48a372afd0/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L343)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>     try {
>       certificate =
>           (X509Certificate)
>               CertificateFactory.getInstance("X509")
>                   .generateCertificate(new ByteArrayInputStream(certificateString.getBytes(UTF_8)));
>     } catch (CertificateException e) {
>       throw new IllegalArgumentException("Unable to read given certificate.");
>     }
> ```
It looks like we should just move this logic into the `checkCertificate` method. Instead of taking an `X509Certificate` as argument, it will take a `Certificate` and try to convert it to`X509Certificate` first. This way you don't need this conversion done here, as well as in the nomulus tool command. It also kinda make sense that the certificate checker only works with X509 certs, so if any other type of cert is provided, it should error out.
</blockquote></details>

Agreed.  There's a lot of code duplication at the various callsites of `checkCertificate()`.  This indicates to me that there's additional common functionality that can be refactored into a centralized place.  I like Lai's suggestion to centralize handling of the `X509` conversion, and I also think that the turning the individual violation messages into a newline-delimited string is a common enough pattern that it too should have a helper method in `CertificateChecker`.
___
*[core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java, line 322 at r2](https://reviewable.io/reviews/google/nomulus/843#-MKFwO8I7xC4vcDeebTb:-MKFwO8I7xC4vcDeebTc:b-hveki2) ([raw file](https://github.com/google/nomulus/blob/531255ddbf316127112e5387f8d0f25d8aa38c96/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L322)):*
> ```Java
>         .ifPresent(
>             certificateString -> {
>               validateCertificate(certificateString);
> ```

What happens on Nov 1 if a registrar has an invalid cert configured per the new rules and they then try to change anything else in the registrar console?  I don't see any check here that only triggers the validation if a new cert is being set?  (Rather than an existing one being retained.)


<!-- Sent from Reviewable.io -->

2020-10-22 16:19 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/843)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java, line 322 at r2](https://reviewable.io/reviews/google/nomulus/843#-MKFwO8I7xC4vcDeebTb:-MKG5JcFBejMF1vK6wvQ:b-1hcc80) ([raw file](https://github.com/google/nomulus/blob/531255ddbf316127112e5387f8d0f25d8aa38c96/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L322)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What happens on Nov 1 if a registrar has an invalid cert configured per the new rules and they then try to change anything else in the registrar console?  I don't see any check here that only triggers the validation if a new cert is being set?  (Rather than an existing one being retained.)
</blockquote></details>

That’s a very good point. Good catch. If I recall correctly the front end always sends the entire registrar entity back, not just the changed part. So we’ll need some logic in the backend to compare that with what’s stored and determine the diff.


<!-- Sent from Reviewable.io -->

2020-10-23 02:51 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/843)* status: 3 of 10 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java, line 313 at r3](https://reviewable.io/reviews/google/nomulus/843#-MKIM7ATCxcbeUqoa4Z9:-MKIM7ATCxcbeUqoa4ZA:b2ih3j) ([raw file](https://github.com/google/nomulus/blob/9c69fed49a481c73e1a3509d5073b2db1fef0f8d/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L313)):*
> ```Java
>     RegistrarFormFields.CLIENT_CERTIFICATE_FIELD
>         .extractUntyped(args)
>         .ifPresent(
> ```

This is complicated enough now that a normal `if` statement would be better.
___
*[core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java, line 315 at r3](https://reviewable.io/reviews/google/nomulus/843#-MKIMF_GCCK91AAqI-p7:-MKIMF_GCCK91AAqI-p8:b-qiklsd) ([raw file](https://github.com/google/nomulus/blob/9c69fed49a481c73e1a3509d5073b2db1fef0f8d/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L315)):*
> ```Java
>         .ifPresent(
>             certificateString -> {
>               String existingCertificate = initialRegistrar.getClientCertificate();
> ```

There's enough logic duplicated here between the two certs that it makes sense to extract it to a helper method.
___
*[util/src/main/java/google/registry/util/CertificateChecker.java, line 82 at r3](https://reviewable.io/reviews/google/nomulus/843#-MKILkvuAg6aKWtz3syB:-MKILkvuAg6aKWtz3syC:bbfubhj) ([raw file](https://github.com/google/nomulus/blob/9c69fed49a481c73e1a3509d5073b2db1fef0f8d/util/src/main/java/google/registry/util/CertificateChecker.java#L82)):*
> ```Java
>     ImmutableSet<CertificateViolation> violations = checkCertificate(certificateString);
>     if (!violations.isEmpty()) {
>       String displayMessages = getAllDisplayMessages(violations);
> ```

You can just inline this.


<!-- Sent from Reviewable.io -->

2020-10-23 02:53 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/843)* status: 3 of 10 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @jianglai, and @sarahcaseybot)

___
*[core/src/test/java/google/registry/ui/server/registrar/SecuritySettingsTest.java, line 73 at r3](https://reviewable.io/reviews/google/nomulus/843#-MKIMh8A1c-yxCP_FZUn:-MKIMh8A1c-yxCP_FZUo:b-zb9xft) ([raw file](https://github.com/google/nomulus/blob/9c69fed49a481c73e1a3509d5073b2db1fef0f8d/core/src/test/java/google/registry/ui/server/registrar/SecuritySettingsTest.java#L73)):*
> ```Java
>     assertMetric(CLIENT_ID, "update", "[OWNER]", "ERROR: FormFieldException");
>   }
> ```

Is there a test somewhere that a registrar console update on some setting that isn't the SSL certificate succeeds post-Nov 1 even if the certificate on file is not compliant with the new requirements?


<!-- Sent from Reviewable.io -->

2020-10-23 15:00 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/843)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java, line 315 at r4](https://reviewable.io/reviews/google/nomulus/843#-MKKy4sbETrCffxvXeaJ:-MKKy4sbETrCffxvXeaK:b-cppzsc) ([raw file](https://github.com/google/nomulus/blob/0224be9a36d8f0018f2a3c3dc4fee157ce879784/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L315)):*
> ```Java
>         RegistrarFormFields.CLIENT_CERTIFICATE_FIELD.extractUntyped(args);
>     if (certificateString.isPresent()) {
>       String existingCertificate = initialRegistrar.getClientCertificate();
> ```

You can just inline this and save a line.  (Which has the benefit of not overloading the same variable name in two different scopes within the same function, which is slightly confusing.)
___
*[core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java, line 324 at r4](https://reviewable.io/reviews/google/nomulus/843#-MKKyHQD2M2Ml2Fr3XaC:-MKKyHQD2M2Ml2Fr3XaD:b-816h6l) ([raw file](https://github.com/google/nomulus/blob/0224be9a36d8f0018f2a3c3dc4fee157ce879784/core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java#L324)):*
> ```Java
>         RegistrarFormFields.FAILOVER_CLIENT_CERTIFICATE_FIELD.extractUntyped(args);
>     if (failoverCertificateString.isPresent()) {
>       String existingCertificate = initialRegistrar.getFailoverClientCertificate();
> ```

Same.


<!-- Sent from Reviewable.io -->

2020-10-23 15:00 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/843#-:-MKKyQsX15cjcpwI7Gmt:bnfp4nl)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @jianglai and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2020-10-23 19:34 UTC, CydeWeys reviewed
> Dismissed @jianglai from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/843)* status: 3 of 10 files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2020-10-23 19:34 UTC, CydeWeys reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/843#-:-MKLxB48CSiesGgiWdhD:bnfp4nl)* status: 3 of 10 files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2020-10-23 19:46 UTC, merged