An automated rollback tool for Nomulus
google/nomulus pull request #847
Opened 2020-10-22 17:47 UTC by weiminyu

A tool that directs traffic between deployed versions. It handles the
conversion between Nomulus tags and AppEngine versions, executes schema
compatibility tests, ensures that steps are executed in the correct order,
and updates deployment records appropriately.

2020-10-23 16:34 UTC, mindhog requested changes
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: all files reviewed, 32 unresolved discussions (waiting on @weiminyu)

___
*[rollback_tool, line 2 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKG4zy5qflKeo2O0C-:-MKKG4zy5qflKeo2O0C0:b-b8dc9a) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/rollback_tool#L2)):*
> ```
> #!/bin/sh
> # Wrapper for nom_build.py.
> ```

"Wrapper for rollback_tool"

We might want to just get rid of these wrappers and instead move the python scripts directly to this location.  They're not buying us very much.
___
*[release/rollback/appengine.py, line 34 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKHHzV556Yt10Ag5uf:-MKKHHzW0-YrRBiz_LCL:by0hr7o) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L34)):*
> ```Python
>         super().__init__(
>             self, f'Received paged response unexpectedly when calling {uri}. '
>             'Consider increase PAGE_SIZE.')
> ```

*increasing
___
*[release/rollback/appengine.py, line 40 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKHOOFA5CGzFqwzREF:-MKKHOOFA5CGzFqwzREG:bic6vm) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L40)):*
> ```Python
>     """Wrapper around the AppEngine Admin REST API client.
> 
>     This class provides wrapper methods around the RESET API for service and
> ```

RESET -> REST?
___
*[release/rollback/appengine.py, line 45 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKI0XgD_TCsnXXqtjl:-MKKI0XgD_TCsnXXqtjm:b-tgy339) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L45)):*
> ```Python
> 
>     # AppEngine services under management.
>     SERVICES = frozenset(['backend', 'default', 'pubapi', 'tools'])
> ```

In python, we generally put constants at the module level.
___
*[release/rollback/appengine.py, line 48 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKH_bD9MpRQKstMgQJ:-MKKH_bD9MpRQKstMgQK:b-7j35jn) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L48)):*
> ```Python
> 
>     # Forces 'list' calls (for services and versions) to return all
>     # results in one shot, to avoid having to handl pagination. This values
> ```

*handle
___
*[release/rollback/appengine.py, line 65 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKIS6a1oRzsP8yrjeP:-MKKIS6a1oRzsP8yrjeQ:b-korrpu) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L65)):*
> ```Python
>         """Initialize this instance for an AppEngine(GCP) project."""
>         self._project = project
>         apps = service_lookup.apps(
> ```

It's likely a little clearer to just wrap this whole expression in parens, e.g.:


    apps = (service_lookup.apps()
            if service_lookup is not None
            else discover.build('appengine', 'v1beta').apps())
___
*[release/rollback/appengine.py, line 104 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKLf6d4nOH5Yy0X7Xk:-MKKLf6e3Q6IFM-NyVuQ:b-t2pu79) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L104)):*
> ```
>                 versions_with_traffic = service.get('split',
>                                                     {}).get('allocations',
>                                                             {}).keys()
> ```
If you parenthesize the expression, I think you can fit it all into the next line:

    versions_with_traffic = (
        service.get .... keys())
___
*[release/rollback/appengine.py, line 125 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKWWhL9JjfgwoSGRhO:-MKKWWhM0217xd8kuboY:b-dphk78) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L125)):*
> ```Python
> 
>         Args:
>             versions: A collection of the Service objects, each containing the
> ```

It doesn't look like a collection of service objects from the type annotation?
___
*[release/rollback/appengine.py, line 155 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKZsYHAmK6GDxNSKDk:-MKKZsYHAmK6GDxNSKDl:b-8na42x) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L155)):*
> ```Python
>                             f'Expecting exactly one scaling, found {scalings}')
> 
>                     scaling = common.AppEngineScaling(next(iter(scalings)))
> ```

I think you should just be able to use scalings[0] here.
___
*[release/rollback/appengine_test.py, line 34 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKcnr89gR7amgV-yrr:-MKKcnr89gR7amgV-yrs:b3oz8r1) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine_test.py#L34)):*
> ```Python
>     # Assign mocked API response to mock_request.execute.
>     mock_request = mock.Mock('googleapiclient.http.HttpRequest')
>     mock_request.uri = mock.Mock(return_value='myuri')
> ```

it's easier and more idiomatic to set these up like this:
   mock_request.uri.return_value = 'myuri'

The secondary mock objects are magically created upon attribute access.

Speaking of magic, it's generally preferrable to use MagicMock.  This does everything Mock does but also provides the special attributes (e.g. __len__, __iter__, ...) to give you a more generally usable object.
___
*[release/rollback/appengine_test.py, line 61 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKf8il9d6xIUXYh-PV:-MKKf8il9d6xIUXYh-PW:by7ba2y) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine_test.py#L61)):*
> ```Python
>     def _set_mocked_response(
>             self, responses: Union[Dict[str, Any], List[Dict[str,
>                                                              Any]]]) -> None:
> ```

Agh! It burns!  Please move responses to its own line (you can drop the ") -> None:" to the next line if it doesn't fit)
___
*[release/rollback/common.py, line 65 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKujxK0zFTyVBuQngP:-MKKujxK0zFTyVBuQngQ:btces4s) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/common.py#L65)):*
> ```Python
>     version_id: str
> 
>     def __eq__(self, other):
> ```

This merits a comment indicating that you are defining your own __eq__ to allow the equality property to work for derived classes.  (you could simply add this to the discussion on subclasses in the docstring) 
___
*[release/rollback/common.py, line 80 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKjUEv-5-aM7L4kYFf:-MKKjUEv-5-aM7L4kYFg:bhzqm7g) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/common.py#L80)):*
> ```Python
>         scaling: The scaling scheme of this version. This value determines what
>                  steps are needed for the rollback. If a version is on
>                  automatic scaling, we only need to direct traffic to it or
> ```

We generally format lines after the first one with a 4 character hanging indent, as you have it below.
___
*[release/rollback/common.py, line 87 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKjswE7VCNDHyBBId_:-MKKjswE7VCNDHyBBIda:b-88e6hu) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/common.py#L87)):*
> ```Python
>                  it is shutdown, and to its original configured number when
>                  brought up.
>         manual_scaling_instances: The originally configure VM [...]

2020-10-24 02:31 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: 1 of 11 files reviewed, 32 unresolved discussions (waiting on @mindhog)

___
*[rollback_tool, line 2 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKG4zy5qflKeo2O0C-:-MKLuWKa0XASx_vS_3Y_:b83bexl) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/rollback_tool#L2)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

"Wrapper for rollback_tool"

We might want to just get rid of these wrappers and instead move the python scripts directly to this location.  They're not buying us very much.
</blockquote></details>

Done.

We probably just want to move the main scripts here, right? It would require us to set up python paths for the other files appropriately.
 
___
*[release/rollback/appengine.py, line 34 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKHHzV556Yt10Ag5uf:-MKLv--E5gn2SrkyRvKD:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L34)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

*increasing
</blockquote></details>

Done.
___
*[release/rollback/appengine.py, line 40 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKHOOFA5CGzFqwzREF:-MKLvpiJ3RZHKCm2ZY-P:b-sgk69w) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L40)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

RESET -> REST?
</blockquote></details>

Done.

Sorry, so many typos. 

I spent a lot of time on these files. Every word looks so familiar...
___
*[release/rollback/appengine.py, line 45 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKI0XgD_TCsnXXqtjl:-MKLytjpAGsIKbiwqCU0:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L45)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

In python, we generally put constants at the module level.
</blockquote></details>

Done.
___
*[release/rollback/appengine.py, line 48 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKH_bD9MpRQKstMgQJ:-MKLyubjCleBzy-RS0Pi:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L48)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

*handle
</blockquote></details>

Done.
___
*[release/rollback/appengine.py, line 65 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKIS6a1oRzsP8yrjeP:-MKLzF5g-9ix0qYaftNS:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L65)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

It's likely a little clearer to just wrap this whole expression in parens, e.g.:


    apps = (service_lookup.apps()
            if service_lookup is not None
            else discover.build('appengine', 'v1beta').apps())
</blockquote></details>

Done.
___
*[release/rollback/appengine.py, line 104 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKLf6d4nOH5Yy0X7Xk:-MKLzUK56_R-tbHWp_td:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L104)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

> ```
>                 versions_with_traffic = service.get('split',
>                                                     {}).get('allocations',
>                                                             {}).keys()
> ```
If you parenthesize the expression, I think you can fit it all into the next line:

    versions_with_traffic = (
        service.get .... keys())

</blockquote></details>

Done.
___
*[release/rollback/appengine.py, line 125 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKWWhL9JjfgwoSGRhO:-MKM-Tph-SfdW0h6ejXi:b7ety6b) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L125)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

It doesn't look like a collection of service objects from the type annotation?
</blockquote></details>

A set. My language was a bit loose. 
___
*[release/rollback/appengine.py, line 155 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKZsYHAmK6GDxNSKDk:-MKM04W7-6ZDuzp-XqXc:b-9uxirz) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L155)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I think you should just be able to use scalings[0] here.
</blockquote></details>

This is a set so can't use subscription. It's small so I converted into a list.
___
*[release/rollback/appengine_test.py, line 34 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKcnr89gR7amgV-yrr:-MKM2iFA8HQGYISq3mEp:b-tz9w7a) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine_test.py#L34)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

it's easier and more idiomatic to set these up like this:
   mock_request.uri.return_value = 'myuri'

The secondary mock objects are magically created upon attribute access.

Speaking of magic, it's generally preferrable to use MagicMock.  This does everything Mock does but also provides the special attributes (e.g. __len__, __iter__, ...) to give you a more generally usable object.
</blockquote></details>

Done.

Interestingly, I can't use mock_request.uri.return_value when mock_request is mocked with a spec. 
Doing so will get a 'Mocked object does not have attr uri'. error.

Also had to remove all specs from other places. Not that I'm making use of the spec anyway.
___
*[release/rollback/appengine_test.py, line 61 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKf8il9d6xIUXYh-PV:-MKM3G421KiGmC067Vxk:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine_test.py#L61)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Agh! It burns!  Please move responses to its own line (you can drop the ") -> None:" to the next line if it doesn't fit)
</blockquote></details>

Done.
___
*[release/rollback/common.py, line 65 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKujxK0zFTyVBuQngP:-MKM4xlBAS40-DvkRb4C:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/common.py#L65)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

This merits a comment indicating that you are defining your own __eq__ to allow the equality property to work for derived classes.  (you could simply add this to the discussion on subclasses in the docstring) 
</blockquote></details>

Done.
___
*[release/rollback/common.py, line 80 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKjUEv-5-aM7L4kYFf:-MKM6-eTEB2o7zipauTG:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/common.py#L80)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

We generally format lines after the first one with a 4 character hanging indent, as you have it below.
</blockquote></details>

Done.
___
*[release/rollback/common.py, line 87 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKjswE7VCNDHyBBId_:-MKM6DQaEfxrL3Y8Y4AV:b-896fix) ([raw file](https://github [...]

2020-10-26 12:01 UTC, mindhog approved these changes
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: all files reviewed, 6 unresolved discussions (waiting on @mindhog and @weiminyu)

___
*[rollback_tool, line 2 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKG4zy5qflKeo2O0C-:-MKZa4w88QVkFQ1IZIRS:b7qxfvl) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/rollback_tool#L2)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Done.

We probably just want to move the main scripts here, right? It would require us to set up python paths for the other files appropriately.
 
</blockquote></details>

Yes, that's right.  That can be done from within the scripts themselves.
___
*[release/rollback/appengine.py, line 125 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKWWhL9JjfgwoSGRhO:-MKZd2ZQDkhlwY-fUkFM:bwu5a9i) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L125)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

A set. My language was a bit loose. 
</blockquote></details>

Actually, it was more the "Service" versus "VersionKey" thing that confused me.  
___
*[release/rollback/appengine_test.py, line 34 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKcnr89gR7amgV-yrr:-MKZfYQG7nCHr8Pk1om5:b-vi95gs) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine_test.py#L34)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Done.

Interestingly, I can't use mock_request.uri.return_value when mock_request is mocked with a spec. 
Doing so will get a 'Mocked object does not have attr uri'. error.

Also had to remove all specs from other places. Not that I'm making use of the spec anyway.
</blockquote></details>

I don't think you can use a spec with a string classname, I think you have to use  either an object or a list of method/attribute names.  Also, any trickery in the class (e.g. __getattr__) is likely to confuse the spec code.
___
*[release/rollback/common.py, line 87 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKjswE7VCNDHyBBId_:-MKZgRR-CoXuVsR4Hykg:b7adkgz) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/common.py#L87)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, I was referring to the first line after manual_scaling_instances.
___
*[release/rollback/README.md, line 47 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKL6cZE37pNmvyxryYu:-MKZlfMo0Biz-cqqgeUn:byveq4) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/README.md#L47)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This uses the wrapper in the nomulus root directory
</blockquote></details>

Isn't that also called rollback_tool, though?
___
*[release/rollback/README.md, line 31 at r2](https://reviewable.io/reviews/google/nomulus/847#-MKZkakF-YsoKfdcR9RX:-MKZkakG0vsKcOoQ7IUH:b-nn7a0b) ([raw file](https://github.com/google/nomulus/blob/3c8d6a5249786d1ce618e4ed7f2e791cb6a1bf88/release/rollback/README.md#L31)):*
> ```Markdown
> Registry team members should use virtualenv or venv to install the GCP
> libraries. A 'sudo pip install' may intefere with the Linux tooling on your
> corp desktop.
> ```

Note that non-sudo pip (or pip3, because it's different from the python2 one)  installs to ~/.local which may be preferable to a virtualenv in some cases.


<!-- Sent from Reviewable.io -->

2020-10-26 14:49 UTC, mindhog approved these changes
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @mindhog and @weiminyu)



<!-- Sent from Reviewable.io -->

2020-10-26 14:49 UTC, mindhog reviewed
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: all files reviewed, 5 unresolved discussions (waiting on @mindhog and @weiminyu)



<!-- Sent from Reviewable.io -->

2020-10-26 15:01 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @mindhog)

___
*[release/rollback/appengine.py, line 125 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKWWhL9JjfgwoSGRhO:-MK_IGf65NfkSb3zDNb-:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/appengine.py#L125)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Actually, it was more the "Service" versus "VersionKey" thing that confused me.  
</blockquote></details>

Done.
___
*[release/rollback/common.py, line 87 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKKjswE7VCNDHyBBId_:-MK_HyCGDz8lt9yEGnG1:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/common.py#L87)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Actually, I was referring to the first line after manual_scaling_instances.
</blockquote></details>

Done.
___
*[release/rollback/README.md, line 47 at r1](https://reviewable.io/reviews/google/nomulus/847#-MKL6cZE37pNmvyxryYu:-MK_Dyr27pZJz0PTpeYa:b-11mib9) ([raw file](https://github.com/google/nomulus/blob/0f22c691d149c948885bdff01453b99df506102d/release/rollback/README.md#L47)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Isn't that also called rollback_tool, though?
</blockquote></details>

Yeah, you are right.
___
*[release/rollback/README.md, line 31 at r2](https://reviewable.io/reviews/google/nomulus/847#-MKZkakF-YsoKfdcR9RX:-MK_H8aj9Qzg1SewPRMa:b-bynbfj) ([raw file](https://github.com/google/nomulus/blob/3c8d6a5249786d1ce618e4ed7f2e791cb6a1bf88/release/rollback/README.md#L31)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Note that non-sudo pip (or pip3, because it's different from the python2 one)  installs to ~/.local which may be preferable to a virtualenv in some cases.
</blockquote></details>

Added a note about pip3 without virtualenv


<!-- Sent from Reviewable.io -->

2020-10-27 21:37 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @CydeWeys, @mindhog, and @weiminyu)

___
*[release/rollback/README.md, line 93 at r4](https://reviewable.io/reviews/google/nomulus/847#-MKfySP60fg1mbaKVpkB:-MKfySP60fg1mbaKVpkC:b-6wpodr) ([raw file](https://github.com/google/nomulus/blob/5ad133d8f6030ae0a53098573c8574fabc9c3d41/release/rollback/README.md#L93)):*
> ```
> backend nomulus-v048    nomulus-20201012-RC00
> ```
Is it possible to display the date that this release got deployed? I feel that is useful to help determine(or double check) which version we want to roll back to.
___
*[release/rollback/README.md, line 97 at r4](https://reviewable.io/reviews/google/nomulus/847#-MKfyYSF8nw39Y6cqpJ6:-MKfyYSF8nw39Y6cqpJ7:b-1xrkzr) ([raw file](https://github.com/google/nomulus/blob/5ad133d8f6030ae0a53098573c8574fabc9c3d41/release/rollback/README.md#L97)):*
> ```
> tools   nomulus-v048    nomulus-20201012-RC00
> backend nomulus-v049    nomulus-20201019-RC00
> ```
Maybe add some delimiter between two groups? Though that may break the row pattern. Also, it is possible to sort them in reverse-chronological order?


<!-- Sent from Reviewable.io -->

2020-10-28 01:15 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @CydeWeys, @hstonec, and @mindhog)

___
*[release/rollback/README.md, line 93 at r4](https://reviewable.io/reviews/google/nomulus/847#-MKfySP60fg1mbaKVpkB:-MKggc358EPBBFHSbVUf:blslu72) ([raw file](https://github.com/google/nomulus/blob/5ad133d8f6030ae0a53098573c8574fabc9c3d41/release/rollback/README.md#L93)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> backend nomulus-v048    nomulus-20201012-RC00
> ```
Is it possible to display the date that this release got deployed? I feel that is useful to help determine(or double check) which version we want to roll back to.
</blockquote></details>

Opened b/171838964.  We need to enhance the deployment book-keeping to support this.
___
*[release/rollback/README.md, line 97 at r4](https://reviewable.io/reviews/google/nomulus/847#-MKfyYSF8nw39Y6cqpJ6:-MKgiJp_DCTCoPuIpT4s:b-asv2zq) ([raw file](https://github.com/google/nomulus/blob/5ad133d8f6030ae0a53098573c8574fabc9c3d41/release/rollback/README.md#L97)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> tools   nomulus-v048    nomulus-20201012-RC00
> backend nomulus-v049    nomulus-20201019-RC00
> ```
Maybe add some delimiter between two groups? Though that may break the row pattern. Also, it is possible to sort them in reverse-chronological order?
</blockquote></details>

I think the current chronological order would make more sense if you execute the command in a shell window.
In a typical case, you would see that the 4 lines immediately above the prompt show the release that is currently
serving, and the next 4 lines up would be the rollback target. In reverse chronological order, you would  look up,
find the top line, then try to determine what release it is, since it could be earlier than the target.


<!-- Sent from Reviewable.io -->

2020-10-28 11:34 UTC, mindhog reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: all files reviewed, 7 unresolved discussions (waiting on @CydeWeys, @hstonec, and @mindhog)



<!-- Sent from Reviewable.io -->

2020-10-28 14:33 UTC, hstonec approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys and @mindhog)



<!-- Sent from Reviewable.io -->

2020-10-29 13:55 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/847#-:-MKod5fg5bhiR4SthqEj:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @CydeWeys and @mindhog)



<!-- Sent from Reviewable.io -->

2020-10-29 14:37 UTC, merged