Make DatastoreHelper support Postgresql
google/nomulus pull request #849
Opened 2020-10-26 15:40 UTC by hstonec

This PR replaced all of the `ofy()` calls in `DatastoreHelper` with corresponding `tm()` calls so it can be used for SQL tests. It also made the following major changes:

1. Added a few APIs in `TransactionManager` to support special `ofy()` behaviors, e.g. `tm().saveWithoutBackup()`. This is to help maintain a single code path in our application.
2. Changed `BillingEventTest` to work with both Datastore and SQL to verify the above change works.
3. Added `@TestOfyAndSql`, `@TestOfyOnly` and `@TestSqlOnly` annotations to be used with `@DualDatabaseTest` to improve flexibility.

2020-10-27 16:59 UTC, mindhog requested changes
> Reviewed 28 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/849)* status: all files reviewed, 7 unresolved discussions (waiting on @gbrodman and @hstonec)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 214 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeQPT66fFE6Mf1_Fs7:-MKeQPT66fFE6Mf1_Fs8:br2er13) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L214)):*
> ```Java
>   @Override
>   public <T> ImmutableList<T> loadAll(Class<T> clazz) {
>     return ImmutableList.copyOf(getOfy().load().type(clazz));
> ```

So does this actually work in a transaction?
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 1001 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeRcFaEvx8PDD5WuA5:-MKeRcFb3idvnUydNTuE:btshr1p) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/main/java/google/registry/model/registrar/Registrar.java#L1001)):*
> ```Java
>                         Registrar.class,
>                         clientId,
>                         Key.create(getCrossTldKey(), Registrar.class, clientId))));
> ```

Should we provide a static Registrar.createVKey(clientId) to create this?
___
*[core/src/main/java/google/registry/model/reporting/HistoryEntry.java, line 277 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeTLZD5fNKuuZizM3o:-MKeTLZE7FcRCJjndv-k:b-u9e766) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/main/java/google/registry/model/reporting/HistoryEntry.java#L277)):*
> ```Java
>   private void setDomainTransactionRecords(Set<DomainTransactionRecord> domainTransactionRecords) {
>     this.domainTransactionRecords =
>         domainTransactionRecords == null ? null : ImmutableSet.copyOf(domainTransactionRecords);
> ```

Can we use nullToEmptyImmutableCopy() here?
___
*[core/src/test/java/google/registry/model/billing/BillingEventTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeeiMc8wg_J1_nTiL_:-MKeeiMd40BppDEH5mt9:bjfjxr4) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/test/java/google/registry/model/billing/BillingEventTest.java#L84)):*
> ```Java
>                 .setXmlBytes(new byte[0])
>                 .build()
>                 .toChildHistoryEntity());
> ```

Why do we need all of the additional fields now?
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 361 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeh9g5EiF9DrfWlIa8:-MKeh9g5EiF9DrfWlIa9:bd1hajg) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/test/java/google/registry/testing/DatastoreHelper.java#L361)):*
> ```Java
>     tm().transact(
>             () ->
>                 ofyOrJpaTm(
> ```

Why does this need to be nested in tm().transact()?  Isn't ofyOrJpaTm() sufficient?
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 372 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKehvoW4yQhxZQXgtXF:-MKehvoW4yQhxZQXgtXG:b-25ajt3) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/test/java/google/registry/testing/DatastoreHelper.java#L372)):*
> ```
> cached
> ```
*cache
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 376 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKehRnG8s41UxI2Mrdl:-MKehRnG8s41UxI2Mrdm:bbpub6f) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/test/java/google/registry/testing/DatastoreHelper.java#L376)):*
> ```
> seesion 
> ```
*session


<!-- Sent from Reviewable.io -->

2020-10-28 11:30 UTC, mindhog requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/849)* status: all files reviewed, 7 unresolved discussions (waiting on @gbrodman and @hstonec)

___
*[core/src/main/java/google/registry/model/reporting/HistoryEntry.java, line 277 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeTLZD5fNKuuZizM3o:-MKiyGOLEOmepgAIun1q:bk3lm4g) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/main/java/google/registry/model/reporting/HistoryEntry.java#L277)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can we use nullToEmptyImmutableCopy() here?
</blockquote></details>

forceEmptyToNull(), rather...


<!-- Sent from Reviewable.io -->

2020-10-28 15:21 UTC, hstonec reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/849)* status: all files reviewed, 7 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 214 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeQPT66fFE6Mf1_Fs7:-MKjl-OW5BK_E5kFpv9m:b634f6g) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L214)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

So does this actually work in a transaction?
</blockquote></details>

No it doesn't, Datastore only supports querying entities within same entity group in a transaction. I added a test to verify that this throws an exception.


<!-- Sent from Reviewable.io -->

2020-10-28 15:22 UTC, hstonec reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/849)* status: all files reviewed, 7 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 214 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeQPT66fFE6Mf1_Fs7:-MKjnKLMDeQFRX_D-Eyr:b-a5dd31) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L214)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

No it doesn't, Datastore only supports querying entities within same entity group in a transaction. I added a test to verify that this throws an exception.
</blockquote></details>

sorry, I accidentally clicked the publish button, I am still working on addressing all your comment. 


<!-- Sent from Reviewable.io -->

2020-10-28 19:15 UTC, hstonec reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/849)* status: 24 of 28 files reviewed, 7 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 1001 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeRcFaEvx8PDD5WuA5:-MKjoBpKDGVxbid0RzXP:bwi30o) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/main/java/google/registry/model/registrar/Registrar.java#L1001)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Should we provide a static Registrar.createVKey(clientId) to create this?
</blockquote></details>

Seems no harm to do that, done.
___
*[core/src/main/java/google/registry/model/reporting/HistoryEntry.java, line 277 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeTLZD5fNKuuZizM3o:-MKjqDId8gB2IHew25Tb:b-9jbg14) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/main/java/google/registry/model/reporting/HistoryEntry.java#L277)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

forceEmptyToNull(), rather...
</blockquote></details>

It seems `forceEmptyToNull` doesn't do a copy for the original set so we still need to check its result to make a copy if it is not null. 
___
*[core/src/test/java/google/registry/model/billing/BillingEventTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeeiMc8wg_J1_nTiL_:-MKjqXRVAI-AMg45qcNY:bo65w34) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/test/java/google/registry/model/billing/BillingEventTest.java#L84)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Why do we need all of the additional fields now?
</blockquote></details>

Because we add `not null` constraints on those fields in the SQL schema.
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 361 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKeh9g5EiF9DrfWlIa8:-MKjr5q6BFHA8CDjxWbd:b597jk6) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/test/java/google/registry/testing/DatastoreHelper.java#L361)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Why does this need to be nested in tm().transact()?  Isn't ofyOrJpaTm() sufficient?
</blockquote></details>

You are right, I changed to use transact for the sql part only.
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 372 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKehvoW4yQhxZQXgtXF:-MKjrl373QxoTmdoePdi:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/test/java/google/registry/testing/DatastoreHelper.java#L372)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

> ```
> cached
> ```
*cache
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 376 at r1](https://reviewable.io/reviews/google/nomulus/849#-MKehRnG8s41UxI2Mrdl:-MKjrnDh19YAtwbYNcPV:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f78f14b5671bb3146c8406bfcace1bf2593fe997/core/src/test/java/google/registry/testing/DatastoreHelper.java#L376)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

> ```
> seesion 
> ```
*session
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 19:30 UTC, mindhog approved these changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/849)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)



<!-- Sent from Reviewable.io -->

2020-10-28 20:28 UTC, gbrodman requested changes
> Reviewed 1 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/849)* status: 27 of 28 files reviewed, 9 unresolved discussions (waiting on @hstonec and @mindhog)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 80 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkmqdn2xAER5NQgffC:-MKkmqdn2xAER5NQgffD:bqz8nyl) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/model/domain/DomainHistory.java#L80)):*
> ```Java
>     // We need to handle null case here because Hibernate sometimes accesses this method before
>     // parent gets initialized
>     return parent == null ? null : parent.getName();
> ```

should we do similar in ContactHistory and HostHistory?
___
*[core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java, line 243 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkpG7r8xma3YORwp3K:-MKkpG7r8xma3YORwp3L:bbjm0pm) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L243)):*
> ```Java
>   }
> 
>   @Override
> ```

Is it worth mentioning in general that the *WithoutBackup methods are for the sake of unifying the JPA transaction manager with the Datastore transaction manager (and perhaps a note on the Datastore commit log backup mechanism and the fact that it isn't necessary in SQL)? 

e: i see it's mentioned in the interface
___
*[core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java, line 419 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkpf0Z72LK6J84A-N4:-MKkpf0Z72LK6J84A-N5:b-bj3etm) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L419)):*
> ```Java
>     assertInTransaction();
>     if (!getEntityManager().contains(entity)) {
>       getEntityManager().merge(entity);
> ```

What's up with merge() here? Wouldn't that persist the entity? 
___
*[core/src/main/java/google/registry/persistence/transaction/TransactionManagerUtil.java, line 31 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkqURL7LaJANMPZJkn:-MKkqURL7LaJANMPZJko:bjz93eo) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/persistence/transaction/TransactionManagerUtil.java#L31)):*
> ```Java
>    * the {@link Supplier} is executed in a transaction.
>    */
>   public static <T> T transactIfJpaTm(Supplier<T> supplier) {
> ```

nitty, but I think it might be more semantically correct to call this a Callable since the point is that we're performing an action, not retrieving a value. It also preserves the symmetry between passing either a Runnable or a Callable into transact() methods 

Similar for ofyOrJpaTm() and ofyTmOrDoNothing()
___
*[core/src/test/java/google/registry/model/billing/BillingEventTest.java, line 168 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkrCgv2HbtxEXYkHr0:-MKkrCgv2HbtxEXYkHr1:bhln5o3) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/model/billing/BillingEventTest.java#L168)):*
> ```Java
>                     .setRecurringEventKey(recurring.createVKey())));
>     modification =
>         ofyTmOrDoNothing(
> ```

This is because Modification isn't stored in SQL yet right? Will this break once that happens (i'd hope so)? 

Similar question for the other places where we interact with modifications and ofyTmOrDoNothing 
___
*[core/src/test/java/google/registry/model/billing/BillingEventTest.java, line 220 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkrPHH3Lp2RGYf6W7o:-MKkrPHH3Lp2RGYf6W7p:bmx7gxo) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/model/billing/BillingEventTest.java#L220)):*
> ```Java
>   }
> 
>   @TestOfyAndSql
> ```

wouldn't this be SQL-only? 
___
*[core/src/test/java/google/registry/testing/AppEngineExtension.java, line 390 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkrsg5BCucpAD6Chv1:-MKkrsg5BCucpAD6Chv2:b-xz008f) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/testing/AppEngineExtension.java#L390)):*
> ```Java
>     ofyOrJpaTm(
>         () -> {
>           if (withDatastore && !withoutCannedData) {
> ```

unrelated to this PR, but a negative-boolean is sad times (i.e. it should be withCannedData) 
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 810 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKksKJ1EPpXmfOQd5t7:-MKksKJ1EPpXmfOQd5t8:b-7x2ttm) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/testing/DatastoreHelper.java#L810)):*
> ```Java
> 
>   public static ImmutableList<PollMessage> getPollMessages(String clientId) {
>     return transactIfJpaTm(
> ```

Out of curiosity, is there any downside to <always> using a transaction in these places where we're calling `transactIfJpaTm`? 
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 1055 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKksjwM3KbZuRu4GOF7:-MKksjwN2A2zf95CIqSJ:b-ow43xb) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/testing/DatastoreHelper.java#L1055)):*
> ```Java
>                         unsorted = tm().loadAll(DomainHistory.class);
>                       } else {
>                         unsorted =
> ```

do we need to assign `unsorted` here? I'd assume `fail` propagates the exception
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 1059 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKksyumEyw4tFs0gB-8:-MKksyumEyw4tFs0gB-9:bxakntb) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/testing/DatastoreHelper.java#L1059)):*
> ```Java
>                                 "Expected an EppResource instance, but got " + resource.getClass());
>                       }
>                       return ImmutableList.sortedCopyOf(DateTimeComparator.getInstance(), unsorted);
> ```

I don't think we actually filter the returned history objects to only those parented by the resource in question 
___
*[core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java, line 54 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKktJo73HOnChBkQ5un:-MKktJo87izZ6dxaIRBS:bb7lbs2) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java#L54)):*
> ```Java
> 
>   @Override
>   public Stream<TestTemplateInvocationContext> provideTestTemplateInvocationContexts(
> ```

nice


<!-- Sent from Reviewable.io -->

2020-10-28 23:25 UTC, hstonec reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/849)* status: 23 of 30 files reviewed, 9 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 80 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkmqdn2xAER5NQgffC:-MKlAGcA5NtA1th13Vq1:bfbq99i) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/model/domain/DomainHistory.java#L80)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

should we do similar in ContactHistory and HostHistory?
</blockquote></details>

Good point, done.
___
*[core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java, line 243 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkpG7r8xma3YORwp3K:-MKlQ8Xr5dPLDcu6SPlZ:buzrep5) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L243)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Is it worth mentioning in general that the *WithoutBackup methods are for the sake of unifying the JPA transaction manager with the Datastore transaction manager (and perhaps a note on the Datastore commit log backup mechanism and the fact that it isn't necessary in SQL)? 

e: i see it's mentioned in the interface
</blockquote></details>

I added a little more descriptions to those interfaces.
___
*[core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java, line 419 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkpf0Z72LK6J84A-N4:-MKlAYOP0AB1eWTnoVVg:b-3sk094) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L419)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What's up with merge() here? Wouldn't that persist the entity? 
</blockquote></details>

`EntityManager.remove()` throws exception if it is a detached entity, so we have to `merge` the entity first then remove it.

Actually, there was an issue with the previous, I should use the returned entity instead of the provided one for `remove`, it's been fixed and I added a test to verify it works.
___
*[core/src/main/java/google/registry/persistence/transaction/TransactionManagerUtil.java, line 31 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkqURL7LaJANMPZJkn:-MKlFFEe2WrF0Dy1rrWh:btephy9) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/persistence/transaction/TransactionManagerUtil.java#L31)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nitty, but I think it might be more semantically correct to call this a Callable since the point is that we're performing an action, not retrieving a value. It also preserves the symmetry between passing either a Runnable or a Callable into transact() methods 

Similar for ofyOrJpaTm() and ofyTmOrDoNothing()
</blockquote></details>

Yeah, the problem is Callable.call() throws `Exception` which we may not want to handle, so I guess we may still have to stick with Supplier unless we define our own interface.
___
*[core/src/test/java/google/registry/model/billing/BillingEventTest.java, line 168 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkrCgv2HbtxEXYkHr0:-MKlJ8Nu3v7LY6K50oxO:b-13z2fe) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/model/billing/BillingEventTest.java#L168)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This is because Modification isn't stored in SQL yet right? Will this break once that happens (i'd hope so)? 

Similar question for the other places where we interact with modifications and ofyTmOrDoNothing 
</blockquote></details>

Correct, we decided to not support Modification in SQL so we may just remove the related tests after the migration.
___
*[core/src/test/java/google/registry/model/billing/BillingEventTest.java, line 220 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkrPHH3Lp2RGYf6W7o:-MKlK2jX6qcS7m13enPR:b-r88k0r) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/model/billing/BillingEventTest.java#L220)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

wouldn't this be SQL-only? 
</blockquote></details>

This is an existing `ofy` test, so I'd say we keep it for both DBs.
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 810 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKksKJ1EPpXmfOQd5t7:-MKl5M2h36K1NU-rhUeb:b-2bxn5p) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/testing/DatastoreHelper.java#L810)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Out of curiosity, is there any downside to <always> using a transaction in these places where we're calling `transactIfJpaTm`? 
</blockquote></details>

In general, `ofy().load()` will try to look up the entity from the session cache before actually querying Datastore if the operation is not in a transaction(transaction always creates a fresh session cache), so this is more efficient.

For this case, I just want to make sure the behavior is as same as before, it may or may not affect the result without using `transactIfJpaTm`.
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 1055 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKksjwM3KbZuRu4GOF7:-MKl7JGW9jNkJ948hS9w:b-9yy7en) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/testing/DatastoreHelper.java#L1055)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

do we need to assign `unsorted` here? I'd assume `fail` propagates the exception
</blockquote></details>

Right, done.
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 1059 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKksyumEyw4tFs0gB-8:-MKlA084DWibzqVZ9yxc:b-t9dd0o) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/test/java/google/registry/testing/DatastoreHelper.java#L1059)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think we actually filter the returned history objects to only those parented by the resource in question 
</blockquote></details>

Good catch, added the filter logic.


<!-- Sent from Reviewable.io -->

2020-10-29 15:10 UTC, gbrodman approved these changes
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/849)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java, line 419 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkpf0Z72LK6J84A-N4:-MKotVh22znN7srDM7NC:b-kfeyp4) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L419)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

`EntityManager.remove()` throws exception if it is a detached entity, so we have to `merge` the entity first then remove it.

Actually, there was an issue with the previous, I should use the returned entity instead of the provided one for `remove`, it's been fixed and I added a test to verify it works.
</blockquote></details>

sweet, thanks 
___
*[core/src/main/java/google/registry/persistence/transaction/TransactionManagerUtil.java, line 31 at r2](https://reviewable.io/reviews/google/nomulus/849#-MKkqURL7LaJANMPZJkn:-MKou4Gd-hOliunQRU9c:b-s3lnqe) ([raw file](https://github.com/google/nomulus/blob/6f58e0266eb815999d29d2c6208d6c455585ae76/core/src/main/java/google/registry/persistence/transaction/TransactionManagerUtil.java#L31)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

Yeah, the problem is Callable.call() throws `Exception` which we may not want to handle, so I guess we may still have to stick with Supplier unless we define our own interface.
</blockquote></details>

I see, that sounds fine. 


<!-- Sent from Reviewable.io -->

2020-10-29 15:41 UTC, merged