Add an extension to verify transaction replay
google/nomulus pull request #857
Opened 2020-11-02 15:56 UTC by mindhog

Add ReplayExtension, which can be applied to test suites to verify that
transactions committed to datastore can be replayed to SQL.

This introduces a ReplayQueue class, which serves as a stand-in for the
current lack of replay-from-commit-logs.  It also includes replay logic in
TransactionInfo which introduces the concept of "entity class weights."
Entity weighting allows us store and delete objects in an order that is
consistent with the direction of foreign key and deferred foreign key
relationships.  As a general rule, lower weight classes must have no direct or
indirect non-deferred foreign key relationships on higher weight classes.

It is expected that much of this code will change when the final replay
mechanism is implemented.

NOTE: this code currently breaks the one test that it is applied to
(DomainCreateFlowTest) due to a few outstanding persistence bugs.
Merge after these are resolved.  Also, we'll want to revisit this if the
final replay mechanism is implemented soon.

2020-11-12 02:58 UTC, hstonec requested changes
> Reviewed 4 of 6 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 115 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuKSii1Lm7ues0-SZb:-MLuKSii1Lm7ues0-SZc:bhymo3e) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L115)):*
> ```
>     Integer weightObject = CLASS_WEIGHTS.get(entry.getKey().getKind());
>     int weight = weightObject == null ? 0 : weightObject;
> ```
Use `Map.getOrDefault()` instead?
___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 134 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuLRyt424pWGtFZOlb:-MLuLRyt424pWGtFZOlc:b-y1nkkh) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L134)):*
> ```
> jpaTm().delete(VKey.from(entry.getKey()));
> ```
There is a `TransactionManager.delete(entity)` method you may want to try here.
___
*[core/src/test/java/google/registry/flows/FlowTestCase.java, line 104 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuM5mJCWGu7i4zThYk:-MLuM5mJCWGu7i4zThYl:b-mkt04b) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/flows/FlowTestCase.java#L104)):*
> ```
> //          .withClock(clock)
> ```
remove this line?
___
*[core/src/test/java/google/registry/testing/AppEngineExtension.java, line 485 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuMLU7BCbgRxsoYP5C:-MLuMLU7BCbgRxsoYP5D:b-mgusrg) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/testing/AppEngineExtension.java#L485)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>       // If there is a replay extension, we'll want to call its replayToSql() method.
>       ReplayExtension replayer =
>           (ReplayExtension)
>               context.getStore(ExtensionContext.Namespace.GLOBAL).get(ReplayExtension.class);
>       if (replayer != null) {
>         replayer.replayToSql();
>       }
> ```
</details>

As we call `replay` inside the `ReplayExtension` anyway, do we still need this?
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 40 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuNbtF2QiFeN-GhtCV:-MLuNbtF2QiFeN-GhtCW:btqzdsv) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/testing/ReplayExtension.java#L40)):*
> ```
>     DatastoreHelper.setClock(clock);
>     DatastoreHelper.setAlwaysSaveWithBackup(true);
> ```
If those fields/states are only associated with `ReplayExtension`, can we put them here instead of having a static fields in `DatastoreHelper`?


<!-- Sent from Reviewable.io -->

2020-11-12 19:13 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman and @hstonec)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 115 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuKSii1Lm7ues0-SZb:-MLxi7XoAJPGN0oBf85w:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L115)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
>     Integer weightObject = CLASS_WEIGHTS.get(entry.getKey().getKind());
>     int weight = weightObject == null ? 0 : weightObject;
> ```
Use `Map.getOrDefault()` instead?
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 134 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuLRyt424pWGtFZOlb:-MLxiGjN0tWSdBUpfoHt:bubx7jp) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L134)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> jpaTm().delete(VKey.from(entry.getKey()));
> ```
There is a `TransactionManager.delete(entity)` method you may want to try here.
</blockquote></details>

In this case, we don't have an entity.  Just a key and the Delete.SENTINEL.
___
*[core/src/test/java/google/registry/flows/FlowTestCase.java, line 104 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuM5mJCWGu7i4zThYk:-MLxikgy5PGWB5qnmClS:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/flows/FlowTestCase.java#L104)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> //          .withClock(clock)
> ```
remove this line?
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/testing/AppEngineExtension.java, line 485 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuMLU7BCbgRxsoYP5C:-MLxqZ1X3oxfoptnCR-n:b-aj424m) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/testing/AppEngineExtension.java#L485)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
>       // If there is a replay extension, we'll want to call its replayToSql() method.
>       ReplayExtension replayer =
>           (ReplayExtension)
>               context.getStore(ExtensionContext.Namespace.GLOBAL).get(ReplayExtension.class);
>       if (replayer != null) {
>         replayer.replayToSql();
>       }
> ```
As we call `replay` inside the `ReplayExtension` anyway, do we still need this?
</blockquote></details>

Unfortunately, yes.  I've added more comments that hopefully clarify the situation, PTAL?
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 40 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuNbtF2QiFeN-GhtCV:-MLxquVN0k9JvXAsCAab:b-b27s1c) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/testing/ReplayExtension.java#L40)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
>     DatastoreHelper.setClock(clock);
>     DatastoreHelper.setAlwaysSaveWithBackup(true);
> ```
If those fields/states are only associated with `ReplayExtension`, can we put them here instead of having a static fields in `DatastoreHelper`?
</blockquote></details>

We could, although we would need to access them from DatastoreHelper somehow.

We could:
1) Make them static fields of ReplayExtension with accessors to allow DatastoreHelper to read them.
2) Make them instance variables of ReplayExtension and inject the ReplayExtension instance into DatastoreHelper
3) Leave everything as it is.
4) Something else?

What would you prefer?  (It all seems equally ugly to me, so no preference here :-)


<!-- Sent from Reviewable.io -->

2020-11-13 15:30 UTC, hstonec requested changes
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/test/java/google/registry/testing/AppEngineExtension.java, line 485 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuMLU7BCbgRxsoYP5C:-MM1A0SfEU_65ZU1y951:b-uyasw) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/testing/AppEngineExtension.java#L485)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Unfortunately, yes.  I've added more comments that hopefully clarify the situation, PTAL?
</blockquote></details>

makes sense, thanks for the explanation.
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 40 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuNbtF2QiFeN-GhtCV:-MM1BChz6P6jc_TmGvxI:b-od0496) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/testing/ReplayExtension.java#L40)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

We could, although we would need to access them from DatastoreHelper somehow.

We could:
1) Make them static fields of ReplayExtension with accessors to allow DatastoreHelper to read them.
2) Make them instance variables of ReplayExtension and inject the ReplayExtension instance into DatastoreHelper
3) Leave everything as it is.
4) Something else?

What would you prefer?  (It all seems equally ugly to me, so no preference here :-)
</blockquote></details>

hmm, that is unfortunate, I think we can leave them in DatastoreHelper and add some comments to remind us that they are actually only used by this extension.


<!-- Sent from Reviewable.io -->

2020-11-13 15:30 UTC, hstonec reviewed
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)



<!-- Sent from Reviewable.io -->

2020-11-13 16:35 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 11 of 19 files reviewed, 2 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 40 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuNbtF2QiFeN-GhtCV:-MM1SQvt18adnmgT1BXB:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/testing/ReplayExtension.java#L40)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

hmm, that is unfortunate, I think we can leave them in DatastoreHelper and add some comments to remind us that they are actually only used by this extension.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-13 16:37 UTC, hstonec approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857#-:-MM1Sy4SDd6fchVNfoB3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)



<!-- Sent from Reviewable.io -->

2020-11-13 22:08 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: all files reviewed, 8 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/ReplayQueue.java, line 23 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2V77d0W3LvqrFQsQ9:-MM2V77e3biAY-1Vfjda:bbrkabd) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/main/java/google/registry/model/ofy/ReplayQueue.java#L23)):*
> ```Java
>  * Implements simplified datastore to SQL transaction replay.
>  *
>  * <p>This code is to be removed when the actual replay cron job is implemented.
> ```

:) we shall see
___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 105 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2Y3TT6GZ5MTudHzj5:-MM2Y3TT6GZ5MTudHzj6:bj5z8pq) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L105)):*
> ```Java
>   static final ImmutableMap<String, Integer> CLASS_WEIGHTS =
>       ImmutableMap.of(
>           "HistoryEntry", -1,
> ```

Why not use Class objects here? Does the Key object not allow that? 
___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 110 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2Y5qS37hufzWFI_66:-MM2Y5qS37hufzWFI_67:b-o6misg) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L110)):*
> ```Java
>   // The beginning of the range of weights reserved for delete.  This must be greater than any of
>   // the values in CLASS_WEIGHTS.
>   static final int DELETE_RANGE = 100;
> ```

it's unlikely but maybe it might be good to have this be significantly higher? No risk of conflict, however unlikely 
___
*[core/src/main/java/google/registry/model/reporting/HistoryEntry.java, line 186 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2Yow64pjBPPeaD5am:-MM2Yow64pjBPPeaD5an:boxtrq6) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/main/java/google/registry/model/reporting/HistoryEntry.java#L186)):*
> ```Java
>   /** Whether this change was requested by a registrar. */
>   @Column(nullable = false, name = "historyRequestedByRegistrar")
>   Boolean requestedByRegistrar = false;
> ```

I think we wanted this to be null by default? At least I thought that's what Ben said, but he might have been referring to xmlBytes 
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 124 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2ditPDZNK1MBYnb0n:-MM2ditPDZNK1MBYnb0o:b-cw9uu1) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/test/java/google/registry/testing/DatastoreHelper.java#L124)):*
> ```Java
> /** Static utils for setting up test resources. */
> public class DatastoreHelper {
> ```

Does this PR cover all the changes that would be necessary to make to DatastoreHelper?

(also we shouldn't do it here ,but we should rename the class at some point :) )
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 25 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2dDrQ-mupiyUjhdc3:-MM2dDrRAQI_hd_mj2rj:b8moxf0) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/test/java/google/registry/testing/ReplayExtension.java#L25)):*
> ```Java
>  * A JUnit extension that replays datastore transactions against postgresql.
>  *
>  * <p>This extension must be ordered before AppEngineExtension. If AppEngineExtension is not used,
> ```

To be clear, this is because we want objects set up in the AppEngineExtension to be replayed as well? Assuming so, we may wish to explain that here. 

Can we also explain why it should be after the JPATME as well? To someone reading the code in a month or two it might not be clear, might be helpful to avoid having them dig 
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 26 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2dKpkDNf4ELbN1vTr:-MM2dKpkDNf4ELbN1vTs:bgwcmn5) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/test/java/google/registry/testing/ReplayExtension.java#L26)):*
> ```Java
>  *
>  * <p>This extension must be ordered before AppEngineExtension. If AppEngineExtension is not used,
>  * JpaTransactionManagerException must be, and this extension should be ordered _after_
> ```

nit: s/Exception/Extension/g
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 54 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2daPN5Rt4B-ZINXEx:-MM2daPN5Rt4B-ZINXEy:b-uvj7w1) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/test/java/google/registry/testing/ReplayExtension.java#L54)):*
> ```Java
> 
>   public void replayToSql() {
>     DatastoreHelper.setAlwaysSaveWithBackup(false);
> ```

Out of curiosity, what is the purpose of setting this back to false after the tests? 


<!-- Sent from Reviewable.io -->

2020-11-16 13:28 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: all files reviewed, 7 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 105 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2Y3TT6GZ5MTudHzj5:-MMG8gfs9bKm4ZJYZXF2:bx85f6s) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L105)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Why not use Class objects here? Does the Key object not allow that? 
</blockquote></details>

We don't get the class object in the objectify key, just the unqualified class name.
___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 110 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2Y5qS37hufzWFI_66:-MMG9ziM7AshUgvSZQB5:bome0up) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L110)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it's unlikely but maybe it might be good to have this be significantly higher? No risk of conflict, however unlikely 
</blockquote></details>

Actually, it occurs to me that the cleanest way to do this is to compute it from the values, so done.
___
*[core/src/main/java/google/registry/model/reporting/HistoryEntry.java, line 186 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2Yow64pjBPPeaD5am:-MMGA9Op2iG5alAug_8K:b-80spgx) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/main/java/google/registry/model/reporting/HistoryEntry.java#L186)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we wanted this to be null by default? At least I thought that's what Ben said, but he might have been referring to xmlBytes 
</blockquote></details>

We were last discussing it in the context of xmlBytes.  The case for this field being null is AFAIK just datastore, it's cheaper to store a null field than a false value.  This isn't likely to be a big deal for new history entries, though. 
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 124 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2ditPDZNK1MBYnb0n:-MMGAlcO7-ZvEueFIQM7:b-xkxqwx) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/test/java/google/registry/testing/DatastoreHelper.java#L124)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Does this PR cover all the changes that would be necessary to make to DatastoreHelper?

(also we shouldn't do it here ,but we should rename the class at some point :) )
</blockquote></details>

I believe so, yes.
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 25 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2dDrQ-mupiyUjhdc3:-MMGDjL01R6RuzGWoohV:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/test/java/google/registry/testing/ReplayExtension.java#L25)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

To be clear, this is because we want objects set up in the AppEngineExtension to be replayed as well? Assuming so, we may wish to explain that here. 

Can we also explain why it should be after the JPATME as well? To someone reading the code in a month or two it might not be clear, might be helpful to avoid having them dig 
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 26 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2dKpkDNf4ELbN1vTr:-MMGDqJy5EQhJVTx07HT:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/test/java/google/registry/testing/ReplayExtension.java#L26)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit: s/Exception/Extension/g
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 54 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2daPN5Rt4B-ZINXEx:-MMGDxyv0eu_c82Wc6ZY:b-ym1nvo) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/test/java/google/registry/testing/ReplayExtension.java#L54)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Out of curiosity, what is the purpose of setting this back to false after the tests? 
</blockquote></details>

IIUIC, all of the database tests are run in the same process and most don't use the replay extension at this time.  Therefore, we want to turn off the functionality when the test is complete, otherwise it would break for tests that didn't have the other necessary extensions set up correctly.


<!-- Sent from Reviewable.io -->

2020-11-16 16:22 UTC, gbrodman approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 105 at r4](https://reviewable.io/reviews/google/nomulus/857#-MM2Y3TT6GZ5MTudHzj5:-MMGr-Sg03kL5wk3ipi7:b7afptu) ([raw file](https://github.com/google/nomulus/blob/7d8c51fcf8d40545eb6df362e0e5fd7a3a571f5d/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L105)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

We don't get the class object in the objectify key, just the unqualified class name.
</blockquote></details>

annoying, but all right. We shouldn't have conflicts anyway. 


<!-- Sent from Reviewable.io -->

2020-11-16 20:59 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 11 of 18 files reviewed, 2 unresolved discussions (waiting on @hstonec and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 116 at r6](https://reviewable.io/reviews/google/nomulus/857#-MMHqStX4pyNLfaDyK1R:-MMHqStX4pyNLfaDyK1S:be746nm) ([raw file](https://github.com/google/nomulus/blob/87e2c7fbc46003a025df4cee445e070ea915e26e/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L116)):*
> ```Java
>   private static int getWeight(ImmutableMap.Entry<Key<?>, Object> entry) {
>     int weight = CLASS_WEIGHTS.getOrDefault(entry.getKey().getKind(), 0);
>     return entry.getValue().equals(Delete.SENTINEL) ? DELETE_RANGE + -weight : weight;
> ```

Actually, two questions:
1. i think we can remove the + in  DELETE_RANGE + -weight 
2. shouldn't we make the delete range higher? If we're subtracting weights from the DELETE_RANGE for deletes, we'd want to make DELETE_RANGE start at the (max weight * 2) + 1, right? 


<!-- Sent from Reviewable.io -->

2020-11-16 23:09 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 11 of 18 files reviewed, 2 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 116 at r6](https://reviewable.io/reviews/google/nomulus/857#-MMHqStX4pyNLfaDyK1R:-MMIJ4rw-9o1GDqbZ2qX:brqrvcv) ([raw file](https://github.com/google/nomulus/blob/87e2c7fbc46003a025df4cee445e070ea915e26e/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L116)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Actually, two questions:
1. i think we can remove the + in  DELETE_RANGE + -weight 
2. shouldn't we make the delete range higher? If we're subtracting weights from the DELETE_RANGE for deletes, we'd want to make DELETE_RANGE start at the (max weight * 2) + 1, right? 
</blockquote></details>

1) done
2) Good catch!  Fixed the calculation and added a couple of tests (since the code clearly merits it).


<!-- Sent from Reviewable.io -->

2020-11-17 11:28 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 2 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 116 at r6](https://reviewable.io/reviews/google/nomulus/857#-MMHqStX4pyNLfaDyK1R:-MMKxRPV9_7IQpcnl-RM:b-896fix) ([raw file](https://github.com/google/nomulus/blob/87e2c7fbc46003a025df4cee445e070ea915e26e/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L116)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

1) done
2) Good catch!  Fixed the calculation and added a couple of tests (since the code clearly merits it).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 15:47 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 3 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 115 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMLsdxb1qjp7G8IyyNP:-MMLsdxc-lPOYGWlb_5H:b8kh025) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L115)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   static final ImmutableMap<String, Integer> CLASS_WEIGHTS =
>       ImmutableMap.of(
>           "HistoryEntry", -1,
>           "DomainBase", 1);
> ```
</details>

We should probably create a schema inspector that builds an ordered list from the declared foreign key constraints.


<!-- Sent from Reviewable.io -->

2020-11-17 16:01 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 3 unresolved discussions (waiting on @gbrodman, @hstonec, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 115 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMLsdxb1qjp7G8IyyNP:-MMLvt5z5GrRb4TvU9HS:b-xae38d) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L115)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>   static final ImmutableMap<String, Integer> CLASS_WEIGHTS =
>       ImmutableMap.of(
>           "HistoryEntry", -1,
>           "DomainBase", 1);
> ```
We should probably create a schema inspector that builds an ordered list from the declared foreign key constraints.
</blockquote></details>

That would be awesome!  Can we get programmatic access to the schema or would we have to parse it?


<!-- Sent from Reviewable.io -->

2020-11-17 16:10 UTC, hstonec reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 3 unresolved discussions (waiting on @gbrodman, @hstonec, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 115 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMLsdxb1qjp7G8IyyNP:-MMLw_GU3Vk5SO4F8IcO:bfid9om) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L115)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

That would be awesome!  Can we get programmatic access to the schema or would we have to parse it?
</blockquote></details>

I think SchemaCrawler should be able to do that, see [here](https://www.schemacrawler.com/how-to.html#api). FYI, we use SchemaCrawler to genereate the ER diagram so it is already added.


<!-- Sent from Reviewable.io -->

2020-11-17 16:11 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 3 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 115 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMLsdxb1qjp7G8IyyNP:-MMLxr0d5YXTfUT3hfRA:biie3ur) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L115)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

I think SchemaCrawler should be able to do that, see [here](https://www.schemacrawler.com/how-to.html#api). FYI, we use SchemaCrawler to genereate the ER diagram so it is already added.
</blockquote></details>

JDBC's Connection.getMetaData() returns a java.sql.DatabaseMetadata instance. We can start from there.


<!-- Sent from Reviewable.io -->

2020-11-17 16:19 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 3 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 116 at r6](https://reviewable.io/reviews/google/nomulus/857#-MMHqStX4pyNLfaDyK1R:-MMM-6JA31C9H-EQ9g9w:b8z5m1p) ([raw file](https://github.com/google/nomulus/blob/87e2c7fbc46003a025df4cee445e070ea915e26e/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L116)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not sure this fixes the issue -- in the test, for example, we have classes with weights 10 and 20 and a delete range start of 21. That means that a delete of object 10 would happen before the addition of object 20 


<!-- Sent from Reviewable.io -->

2020-11-17 16:26 UTC, weiminyu submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 115 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMLsdxb1qjp7G8IyyNP:-MMM0iFEB48u5xv1LYF9:b-ubeiw4) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L115)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

JDBC's Connection.getMetaData() returns a java.sql.DatabaseMetadata instance. We can start from there.
</blockquote></details>

Also, if we build an list we won't need (negative) weights.
___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 120 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMM-O8o2__O-W6aYbeA:-MMM-O8o2__O-W6aYbeB:bqd18i0) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L120)):*
> ```
>   static final int DELETE_RANGE = calculateDeleteRangeStart(CLASS_WEIGHTS);
> ```
How about (Integer.MAX / 2)?


<!-- Sent from Reviewable.io -->

2020-11-17 16:37 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 116 at r6](https://reviewable.io/reviews/google/nomulus/857#-MMHqStX4pyNLfaDyK1R:-MMM-YPsApXHl5YBZH41:b-lh8f46) ([raw file](https://github.com/google/nomulus/blob/87e2c7fbc46003a025df4cee445e070ea915e26e/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L116)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I'm not sure this fixes the issue -- in the test, for example, we have classes with weights 10 and 20 and a delete range start of 21. That means that a delete of object 10 would happen before the addition of object 20 
</blockquote></details>

You're right.  I keep forgetting to flip the delete range.  PTAL?


<!-- Sent from Reviewable.io -->

2020-11-17 16:48 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @hstonec, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 120 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMM-O8o2__O-W6aYbeA:-MMM5HaZ8T3V1xDTkXCG:b-boshqn) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L120)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>   static final int DELETE_RANGE = calculateDeleteRangeStart(CLASS_WEIGHTS);
> ```
How about (Integer.MAX / 2)?
</blockquote></details>

Now what fun would that be?  ;-)  Done.


<!-- Sent from Reviewable.io -->

2020-11-17 17:08 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @hstonec, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 120 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMM-O8o2__O-W6aYbeA:-MMMAS4R5yJEOUtosN1Z:b-1mxygf) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L120)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Now what fun would that be?  ;-)  Done.
</blockquote></details>

haha wasn't this the original code? 


<!-- Sent from Reviewable.io -->

2020-11-17 17:09 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @hstonec, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 120 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMM-O8o2__O-W6aYbeA:-MMMAYG4Di01QvIWj55f:b7w54bt) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L120)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

haha wasn't this the original code? 
</blockquote></details>

wait, never mind it wasn't, I must be thinking of some other thing 


<!-- Sent from Reviewable.io -->

2020-11-17 17:50 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @hstonec, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 120 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMM-O8o2__O-W6aYbeA:-MMMJWwE2-wPedjA9NhM:bv6dpn7) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L120)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

wait, never mind it wasn't, I must be thinking of some other thing 
</blockquote></details>

Gus, are you good?  (I think your comments retracted your LGTM)


<!-- Sent from Reviewable.io -->

2020-11-17 18:13 UTC, gbrodman approved these changes
> Reviewed 7 of 8 files at r6, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/model/ofy/TransactionInfo.java, line 120 at r7](https://reviewable.io/reviews/google/nomulus/857#-MMM-O8o2__O-W6aYbeA:-MMMPID_DtYs4tRIM7qL:b-z9gy74) ([raw file](https://github.com/google/nomulus/blob/8103092ede619c9e58b63ccb68adad0cb207a1f0/core/src/main/java/google/registry/model/ofy/TransactionInfo.java#L120)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Gus, are you good?  (I think your comments retracted your LGTM)
</blockquote></details>

yeah, we should be good to go 


<!-- Sent from Reviewable.io -->

2020-11-17 18:24 UTC, mindhog reviewed
> Dismissed @weiminyu from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec and @mindhog)



<!-- Sent from Reviewable.io -->

2020-11-17 18:24 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: all files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/test/java/google/registry/testing/AppEngineExtension.java, line 485 at r2](https://reviewable.io/reviews/google/nomulus/857#-MLuMLU7BCbgRxsoYP5C:-MMMRql50suxxQHLL-bK:bb6sh2i) ([raw file](https://github.com/google/nomulus/blob/d67bcc7d7221a8d64469d999e588d995d3b735fe/core/src/test/java/google/registry/testing/AppEngineExtension.java#L485)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

makes sense, thanks for the explanation.
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2020-11-17 18:26 UTC, mindhog reviewed
> Dismissed @hstonec from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/857)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-17 18:29 UTC, merged