Make sure post load work happens in GracePeriod
google/nomulus pull request #878
Opened 2020-11-19 14:38 UTC by weiminyu

The GracePeriod method with ofy @OnLoad annotation is not called.

Apparently Ofy only checks for @OnLoad on first-class entities,
not embedded ones.

Added a call to this method from DomainContent's OnLoad method.

Reproduced issue with a test and verified that the fix works.

2020-11-19 15:07 UTC, mindhog requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/878)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @hstonec, and @weiminyu)

___
*[core/src/test/java/google/registry/model/domain/DomainBaseTest.java, line 174 at r1](https://reviewable.io/reviews/google/nomulus/878#-MMW1VIxD0d0tL_ACrUR:-MMW1VIxD0d0tL_ACrUS:b5jnis9) ([raw file](https://github.com/google/nomulus/blob/c16c504e99a0cce703fb12d024cb06c05dd78fcb/core/src/test/java/google/registry/model/domain/DomainBaseTest.java#L174)):*
> ```Java
>     Entity entity = tm().transact(() -> ofy().save().toEntity(domain));
>     entity.setUnindexedProperty("gracePeriods.gracePeriodId", null);
>     DomainBase domainFromEntity = tm().transact(() -> ofy().load().fromEntity(entity));
> ```

Should make this ofyTm() (or just use ofy().transact()) just so it's clear and portable if we want to make this a DualDatabaseTest.


<!-- Sent from Reviewable.io -->

2020-11-19 15:14 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/878)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[core/src/main/java/google/registry/model/domain/GracePeriod.java, line 58 at r1](https://reviewable.io/reviews/google/nomulus/878#-MMW2Myq69HYK0QQQO3e:-MMW2Myq69HYK0QQQO3f:b-tqyaiy) ([raw file](https://github.com/google/nomulus/blob/e1ce3579044ae6842f237bc57ea8810ab7e19c14/core/src/main/java/google/registry/model/domain/GracePeriod.java#L58)):*
> ```
>   @OnLoad
>   void onLoad() {
> ```
Do you mind to try something like this:

```
void onLoad(@AlsoLoad("gracePeriodId") gracePeriodId) {
   // code...
}
```

`@AlsoLoad` is a workaround of `@OnLoad` for non-entity class, we use it in [Address](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/eppcommon/Address.java;l=179?q=address&ss=nomulus%2Fnomulus) which is also an `@Embed` class.


<!-- Sent from Reviewable.io -->

2020-11-19 15:15 UTC, hstonec reviewed
Thanks for fixing this!

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/878#-:-MMW3fQ9BhwndW1KwD30:b-whxd1j)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @weiminyu)



<!-- Sent from Reviewable.io -->

2020-11-23 18:18 UTC, hstonec approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/878)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)



<!-- Sent from Reviewable.io -->

2020-11-23 18:45 UTC, mindhog approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/878)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2020-11-23 18:47 UTC, merged