Add an action to resave all Domain entities
google/nomulus pull request #889
Opened 2020-11-25 22:44 UTC by hstonec

We added a new field `gracePeriodId` to `GracePeriod` class but it cannot get assigned until the Domain entity is loaded. So, using this action can load all existing Domain entities and resave them to set `gracePeriodId`.

2020-11-25 22:54 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/889)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/889#-MN0b4TU1XLWBIKoUac9:-MN0b4TV9FBNEBwh8ynT:b-jbx045) ([raw file](https://github.com/google/nomulus/blob/7d10c88104970b4dae33ed95087013eaaba20d89/core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java#L44)):*
> ```Java
>     path = "/_dr/task/resaveAllDomains",
>     auth = Auth.AUTH_INTERNAL_OR_ADMIN)
> public class ResaveAllDomainsAction implements Runnable {
> ```

Why is this new action necessary when `ResaveAllEppResourcesAction` already exists?

It seems to me we could just run that, and then use BQ the next day to verify that everything is set?


<!-- Sent from Reviewable.io -->

2020-11-25 23:36 UTC, hstonec reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/889)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/889#-MN0b4TU1XLWBIKoUac9:-MN0kVTrDhYEpW_lLUtx:bo0bowm) ([raw file](https://github.com/google/nomulus/blob/7d10c88104970b4dae33ed95087013eaaba20d89/core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why is this new action necessary when `ResaveAllEppResourcesAction` already exists?

It seems to me we could just run that, and then use BQ the next day to verify that everything is set?
</blockquote></details>

Because that will resave all entities but we only need to do it for domains.


<!-- Sent from Reviewable.io -->

2020-11-26 20:28 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/889)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/889#-MN0b4TU1XLWBIKoUac9:-MN5EG6yEdwpTsI7bzty:b-a3hv52) ([raw file](https://github.com/google/nomulus/blob/7d10c88104970b4dae33ed95087013eaaba20d89/core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java#L44)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

Because that will resave all entities but we only need to do it for domains.
</blockquote></details>

So?  Re-save more entities then (we already run it at least monthly anyway).  It's certainly not worth writing/reviewing all this extra code just to avoid doing some extra database re-saves.  Just run what we already have.


<!-- Sent from Reviewable.io -->

2020-11-26 20:36 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/889)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/889#-MN0b4TU1XLWBIKoUac9:-MN5FOY68k5uziikoBgr:blqf1m3) ([raw file](https://github.com/google/nomulus/blob/7d10c88104970b4dae33ed95087013eaaba20d89/core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

So?  Re-save more entities then (we already run it at least monthly anyway).  It's certainly not worth writing/reviewing all this extra code just to avoid doing some extra database re-saves.  Just run what we already have.
</blockquote></details>

The advantage of using something we already have is that we know it's good and working because it's been running successfully for years.  This is new untested code.  We should always opt for what we already have if possible.

For example, there's one fairly significant error here, which is that it's not calling `cloneProjectedAtTime` on the EPP resources before re-saving them.  `ResaveAllEppResources` does that.  There may be more, but it's not worth looking into in depth; just use what we already have.

Another option you could have gone with is adding a URL parameter to be able to filter the EPP resources that `ResaveAllEppResources` runs on (with it continuing to default to all 3).  I still don't think that's necessary, but that would be a better option than writing an entirely new mapreduce if the only issue is that the existing one runs over too much data.


<!-- Sent from Reviewable.io -->

2020-11-26 20:47 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/889)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/889#-MN0b4TU1XLWBIKoUac9:-MN5Ioe5CSsoU9iLWrf4:b-bf99ez) ([raw file](https://github.com/google/nomulus/blob/7d10c88104970b4dae33ed95087013eaaba20d89/core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The advantage of using something we already have is that we know it's good and working because it's been running successfully for years.  This is new untested code.  We should always opt for what we already have if possible.

For example, there's one fairly significant error here, which is that it's not calling `cloneProjectedAtTime` on the EPP resources before re-saving them.  `ResaveAllEppResources` does that.  There may be more, but it's not worth looking into in depth; just use what we already have.

Another option you could have gone with is adding a URL parameter to be able to filter the EPP resources that `ResaveAllEppResources` runs on (with it continuing to default to all 3).  I still don't think that's necessary, but that would be a better option than writing an entirely new mapreduce if the only issue is that the existing one runs over too much data.
</blockquote></details>

Oh, and another advantage of that approach (if we even think it's necessary -- I'm still not sold) is that if we have some kind of migration to do on contacts or hosts, then we get it for free, rather than having to write entirely new actions for them as well.


<!-- Sent from Reviewable.io -->

2020-11-30 16:11 UTC, hstonec reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/889)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java, line 44 at r1](https://reviewable.io/reviews/google/nomulus/889#-MN0b4TU1XLWBIKoUac9:-MNOuO0G4OFvjZ_Mhfmq:b-hhibt9) ([raw file](https://github.com/google/nomulus/blob/7d10c88104970b4dae33ed95087013eaaba20d89/core/src/main/java/google/registry/batch/ResaveAllDomainsAction.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Oh, and another advantage of that approach (if we even think it's necessary -- I'm still not sold) is that if we have some kind of migration to do on contacts or hosts, then we get it for free, rather than having to write entirely new actions for them as well.
</blockquote></details>

Makes sense, I just verified that we run `resaveAllEppResources` monthly, so I think we can just wait until 12/2 or 12/3 to verify all GracePeriod in DomainBase have a valid id. Will close this PR.


<!-- Sent from Reviewable.io -->

2020-11-30 16:12 UTC, closed without merging