Parameterize the serialization of objects being written to SQL
google/nomulus pull request #892
Opened 2020-12-01 23:17 UTC by gbrodman

We shouldn't require that objects written to SQL during a Beam pipeline
be VersionedEntity objects -- they may be non-Objectify entities. As a
result, we should allow the user to specify what the objects are that
should be written to SQL.

Note: we will need to clean up the Spec11PipelineTest more but that can
be out of the scope of this PR.

2020-12-02 19:33 UTC, gbrodman commented
Weimin, thoughts on this approach? The primary point of this is to be able to write any type of entity to SQL with this transform, rather than specifically the VersionedEntity objects. The Spec11Pipeline has an example of how this could be used in a non-VersionedEntity context.

2020-12-08 21:03 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/892)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[core/src/main/java/google/registry/beam/initsql/Transforms.java, line 281 at r1](https://reviewable.io/reviews/google/nomulus/892#-MO35rayEPQnJNgj4eQZ:-MO35rayEPQnJNgj4eQ_:b-vf6ceo) ([raw file](https://github.com/google/nomulus/blob/c5c8f315d825b582755bd7d71d51c6e6c983c5ad/core/src/main/java/google/registry/beam/initsql/Transforms.java#L281)):*
> ```
> <T>
> ```
Let's make it <T extends Serializable> for now, so that we can get rid of the objectDescriptor. 
___
*[core/src/main/java/google/registry/beam/initsql/Transforms.java, line 286 at r1](https://reviewable.io/reviews/google/nomulus/892#-MO36Lsq-Dp-OXNWv0s8:-MO36Lsq-Dp-OXNWv0s9:bnkx567) ([raw file](https://github.com/google/nomulus/blob/c5c8f315d825b582755bd7d71d51c6e6c983c5ad/core/src/main/java/google/registry/beam/initsql/Transforms.java#L286)):*
> ```
> SerializableFunction<T, Object> jpaConverter
> ```
For a general purpose transform, this should be optional. Alternatively , we can overload the method without this param.

Please update the javadoc.
___
*[core/src/main/java/google/registry/beam/initsql/Transforms.java, line 287 at r1](https://reviewable.io/reviews/google/nomulus/892#-MO36bXf7qAGUYmiiyvM:-MO36bXf7qAGUYmiiyvN:b9kfrkx) ([raw file](https://github.com/google/nomulus/blob/c5c8f315d825b582755bd7d71d51c6e6c983c5ad/core/src/main/java/google/registry/beam/initsql/Transforms.java#L287)):*
> ```
> TypeDescriptor<T> objectDescriptor
> ```
We don't need this if T extends serializable.
___
*[core/src/main/java/google/registry/beam/initsql/Transforms.java, line 294 at r1](https://reviewable.io/reviews/google/nomulus/892#-MO36hJP2jcWq9NTwEjl:-MO36hJP2jcWq9NTwEjm:b-gbb0yq) ([raw file](https://github.com/google/nomulus/blob/c5c8f315d825b582755bd7d71d51c6e6c983c5ad/core/src/main/java/google/registry/beam/initsql/Transforms.java#L294)):*
> ```
> objectDescriptor
> ```
Serializable.class


<!-- Sent from Reviewable.io -->

2020-12-09 16:57 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/892)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/beam/initsql/Transforms.java, line 281 at r1](https://reviewable.io/reviews/google/nomulus/892#-MO35rayEPQnJNgj4eQZ:-MO7Hngm94_lByA8GgfN:bf3ms5z) ([raw file](https://github.com/google/nomulus/blob/c5c8f315d825b582755bd7d71d51c6e6c983c5ad/core/src/main/java/google/registry/beam/initsql/Transforms.java#L281)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> <T>
> ```
Let's make it <T extends Serializable> for now, so that we can get rid of the objectDescriptor. 
</blockquote></details>

(i'm assuming you meant `Serializable` here, as in the other comments)

Unfortunately we cannot. If we use `TypeDescriptor.of(Serializable.class)` here, then that means we lose any possible references to the specific type T for the rest of the method. If we do that, then we would just remove the generic-ization all together and we would just use `Serializable` everywhere, not `T`

This means we would lose a <ton> of flexibility when calling this, since the converter that takes the object from VersionedEntity (for instance) to Object (e.g. `(versionedEntity) -> ofy().toPojo(versionedEntity.getEntity().get())`) requires that we know the type of the object being converted (and presumably any other converters would also require that information). So we kind of need the <T>. 
___
*[core/src/main/java/google/registry/beam/initsql/Transforms.java, line 286 at r1](https://reviewable.io/reviews/google/nomulus/892#-MO36Lsq-Dp-OXNWv0s8:-MO7KuyLC04ZIetz_Vmq:b-a25ywj) ([raw file](https://github.com/google/nomulus/blob/c5c8f315d825b582755bd7d71d51c6e6c983c5ad/core/src/main/java/google/registry/beam/initsql/Transforms.java#L286)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> SerializableFunction<T, Object> jpaConverter
> ```
For a general purpose transform, this should be optional. Alternatively , we can overload the method without this param.

Please update the javadoc.
</blockquote></details>

Yep, that sounds good 
___
*[core/src/main/java/google/registry/beam/initsql/Transforms.java, line 287 at r1](https://reviewable.io/reviews/google/nomulus/892#-MO36bXf7qAGUYmiiyvM:-MO7Qpq6C6VXNJ-VSXTH:bogthd6) ([raw file](https://github.com/google/nomulus/blob/c5c8f315d825b582755bd7d71d51c6e6c983c5ad/core/src/main/java/google/registry/beam/initsql/Transforms.java#L287)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> TypeDescriptor<T> objectDescriptor
> ```
We don't need this if T extends serializable.
</blockquote></details>

(see other comment)
___
*[core/src/main/java/google/registry/beam/initsql/Transforms.java, line 294 at r1](https://reviewable.io/reviews/google/nomulus/892#-MO36hJP2jcWq9NTwEjl:-MO7QqkICPcrDB7btGsd:bogthd6) ([raw file](https://github.com/google/nomulus/blob/c5c8f315d825b582755bd7d71d51c6e6c983c5ad/core/src/main/java/google/registry/beam/initsql/Transforms.java#L294)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> objectDescriptor
> ```
Serializable.class
</blockquote></details>

(see other comment)


<!-- Sent from Reviewable.io -->

2020-12-09 20:34 UTC, weiminyu approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/892)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @weiminyu)



<!-- Sent from Reviewable.io -->

2020-12-09 20:52 UTC, merged