Modify SignedMarkRevocationList to not swallow CloudSQL failures in u…
google/nomulus pull request #898
Opened 2020-12-07 23:02 UTC by sarahcaseybot

…nittests

2020-12-08 15:47 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/898)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @hstonec, and @sarahcaseybot)

___
*[package-lock.json, line 11 at r1](https://reviewable.io/reviews/google/nomulus/898#-MO1wvaM3rUSniVi6F7i:-MO1wvaM3rUSniVi6F7j:bxm14ek) ([raw file](https://github.com/google/nomulus/blob/39bf3db89e22f8aebfbcb6f0c79bc9d1d0063c1d/package-lock.json#L11)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>   "packages": {
>     "": {
>       "name": "nomulus",
>       "version": "1.0.0",
>       "license": "Apache-2.0",
>       "dependencies": {
>         "google-closure-library": "20190325.0.0"
>       },
>       "devDependencies": {
> ```
</details>

Revert the change to this file? sometimes this file got unnecessary changes by gradle.
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java, line 242 at r1](https://reviewable.io/reviews/google/nomulus/898#-MO2-UTP8uVhBzu9PMEv:-MO2-UTP8uVhBzu9PMEw:boy7avg) ([raw file](https://github.com/google/nomulus/blob/39bf3db89e22f8aebfbcb6f0c79bc9d1d0063c1d/core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java#L242)):*
> ```
>           if (RegistryEnvironment.get().equals(RegistryEnvironment.UNITTEST)) {
>             throw new RuntimeException(message);
>           }
> ```
As this is used multiple times in the code, I suggest we put it in a function to simplify the code. Also, I am thinking if it is better to have something like `suppressExceptionWhenNotInTest(() -> {......})` to wrap the whole `try... catch` block, loggings and this if condition. Thoughts?


<!-- Sent from Reviewable.io -->

2020-12-09 15:39 UTC, hstonec requested changes
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/898)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java, line 242 at r1](https://reviewable.io/reviews/google/nomulus/898#-MO2-UTP8uVhBzu9PMEv:-MO77N4H7PP0vTL9Taah:brk42o) ([raw file](https://github.com/google/nomulus/blob/39bf3db89e22f8aebfbcb6f0c79bc9d1d0063c1d/core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java#L242)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Agreed, this is useful. Added to SignedMarkRevocationList.java, but this function is generic enough that it can be used for most dual read/write entities. Any ideas on a better place to put it?
</blockquote></details>

How about making it a static method in a new Java class under `util` sub project?


<!-- Sent from Reviewable.io -->

2020-12-09 15:39 UTC, hstonec reviewed
> Reviewed 1 of 5 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/898)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2020-12-09 15:53 UTC, CydeWeys requested changes
In commit message: The product name is "Cloud SQL", not "CloudSQL".  https://cloud.google.com/sql

Also I'd just say "throw" rather than "not swallow" (which is kind of a double negative).  Something like "Throw errors on SignedMarkRevocationList Cloud SQL failures in unit tests"

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/898#-:-MO7B7fGCuiW9XZxngyB:bogzaca)* status: all files reviewed, 2 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 67 at r2](https://reviewable.io/reviews/google/nomulus/898#-MO7B06h6L3qcJaPfY_t:-MO7B06h6L3qcJaPfY_u:b-sillvb) ([raw file](https://github.com/google/nomulus/blob/e07d6ccf79771abda389b82fe5594de5b458a7a9/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L67)):*
> ```Java
>           SignedMarkRevocationListDao.save(signedMarkRevocationList);
>           logger.atInfo().log(
>               "Inserted %,d signed mark revocations into Cloud SQL",
> ```

Log messages should generally have periods at the end of them.
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 67 at r2](https://reviewable.io/reviews/google/nomulus/898#-MO7CBdz3vxy56w0p0Jo:-MO7CBe--k6tgWzE5RzF:bjalats) ([raw file](https://github.com/google/nomulus/blob/e07d6ccf79771abda389b82fe5594de5b458a7a9/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L67)):*
> ```Java
>           SignedMarkRevocationListDao.save(signedMarkRevocationList);
>           logger.atInfo().log(
>               "Inserted %,d signed mark revocations into Cloud SQL",
> ```

TIL about `%,d`.  That's fun.


<!-- Sent from Reviewable.io -->

2020-12-11 14:37 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/898)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @hstonec, and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/DatabaseMigrationUtils.java, line 21 at r3](https://reviewable.io/reviews/google/nomulus/898#-MOHDlKO4tkqdbWDgzrg:-MOHDlKO4tkqdbWDgzrh:byyy7on) ([raw file](https://github.com/google/nomulus/blob/5db5fa35843200b2c0452978d3e64bd878b8f13f/core/src/main/java/google/registry/model/DatabaseMigrationUtils.java#L21)):*
> ```
> public class DatabaseMigrationUtils {
> ```
Adding a private default constructor as this class only contains static methods?
___
*[core/src/main/java/google/registry/model/DatabaseMigrationUtils.java, line 25 at r3](https://reviewable.io/reviews/google/nomulus/898#-MOHD13U3morSPottA43:-MOHD13U3morSPottA44:b5onwad) ([raw file](https://github.com/google/nomulus/blob/5db5fa35843200b2c0452978d3e64bd878b8f13f/core/src/main/java/google/registry/model/DatabaseMigrationUtils.java#L25)):*
> ```
> /** Exceptions are only thrown in unit tests. Otherwise exceptions are logged, but not thrown. */
> ```
nit: We usually use a verb phrase that describes what the method does.
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java, line 242 at r1](https://reviewable.io/reviews/google/nomulus/898#-MO2-UTP8uVhBzu9PMEv:-MOHDcq5BRW7DpVXR8TG:b32wwp) ([raw file](https://github.com/google/nomulus/blob/39bf3db89e22f8aebfbcb6f0c79bc9d1d0063c1d/core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java#L242)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I can't add it under util/ cause it causes a circular dependency on RegistryEnvironment, so I added a DatabaseMigrationUtils class under model/ in core/. 

As I discussed yesterday with @cydeweys, in the future I can add additional methods to this utils class to indicate exceptions should be thrown in other environments. This will allow us to essentially do the migration in all the environments other than prod, monitor for thrown exceptions for a little while, and then do the migration in prod when we are confident that there will be no issues. 
</blockquote></details>

sg


<!-- Sent from Reviewable.io -->

2020-12-14 22:19 UTC, hstonec approved these changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/898)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)



<!-- Sent from Reviewable.io -->

2020-12-15 21:14 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/898)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java, line 248 at r4](https://reviewable.io/reviews/google/nomulus/898#-MOcFBorDrURnF8L4pfo:-MOcFBorDrURnF8L4pfp:bzdd3t) ([raw file](https://github.com/google/nomulus/blob/e40f2129e5bc381813940bff6a40fe559834e785/core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java#L248)):*
> ```Java
>       }
>     } else {
>       if (datastoreList.size() != 0) {
> ```

Use `!___.isEmpty()`, not `___.size != 0`


<!-- Sent from Reviewable.io -->

2020-12-15 21:14 UTC, CydeWeys approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/898#-:-MOcFOSYBXzC660XtLN5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2020-12-15 22:34 UTC, merged