Convert HostDeleteFlow to tm()
google/nomulus pull request #921
Opened 2021-01-06 16:45 UTC by hstonec

2021-01-07 17:06 UTC, gbrodman requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/921)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec)

___
*[core/src/main/java/google/registry/flows/ResourceFlowUtils.java, line 129 at r1](https://reviewable.io/reviews/google/nomulus/921#-MQSn_Q8CGODkBWnCZep:-MQSn_Q9CAhJZ_sSAzNZ:bwj50dq) ([raw file](https://github.com/google/nomulus/blob/44a80c2049c9a373ae731a38f43f9db0363b8dc2/core/src/main/java/google/registry/flows/ResourceFlowUtils.java#L129)):*
> ```Java
>                       // TODO(shicong): Add a query to get contact's linked domain.
>                       throw new UnsupportedOperationException(
>                           "Query contact's linked domain is not supported");
> ```

In a vacuum, this exception message might not make a lot of sense.  Can we explain that in SQL, we have no way to grab domain links from contacts at the moment? 

Of course this might go away soon if you're implementing contact flow conversions soon anyway. 
___
*[core/src/main/java/google/registry/flows/ResourceFlowUtils.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/921#-MQSnpmd9dWPTKClaJ8K:-MQSnpmd9dWPTKClaJ8L:bhk5eob) ([raw file](https://github.com/google/nomulus/blob/44a80c2049c9a373ae731a38f43f9db0363b8dc2/core/src/main/java/google/registry/flows/ResourceFlowUtils.java#L135)):*
> ```Java
>                     }
>                     keys =
>                         (Iterable<VKey<DomainBase>>)
> ```

Is this cast necessary? What fails without it? 
___
*[core/src/main/java/google/registry/flows/ResourceFlowUtils.java, line 144 at r1](https://reviewable.io/reviews/google/nomulus/921#-MQSnuCh7ug_fWFjjG6m:-MQSnuCh7ug_fWFjjG6n:b-5gt693) ([raw file](https://github.com/google/nomulus/blob/44a80c2049c9a373ae731a38f43f9db0363b8dc2/core/src/main/java/google/registry/flows/ResourceFlowUtils.java#L144)):*
> ```Java
>                                     repoId ->
>                                         DomainBase.createVKey(
>                                             Key.create(DomainBase.class, (String) repoId)))
> ```

Can you not set the result type to be String somewhere so that we can avoid this cast? I thought that was possible but I might be wrong. 


<!-- Sent from Reviewable.io -->

2021-01-08 16:47 UTC, hstonec reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/921)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/flows/ResourceFlowUtils.java, line 129 at r1](https://reviewable.io/reviews/google/nomulus/921#-MQSn_Q8CGODkBWnCZep:-MQXrE-T0oBg16suaR5Q:bfgpoa7) ([raw file](https://github.com/google/nomulus/blob/44a80c2049c9a373ae731a38f43f9db0363b8dc2/core/src/main/java/google/registry/flows/ResourceFlowUtils.java#L129)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

In a vacuum, this exception message might not make a lot of sense.  Can we explain that in SQL, we have no way to grab domain links from contacts at the moment? 

Of course this might go away soon if you're implementing contact flow conversions soon anyway. 
</blockquote></details>

Yeah, my original idea was to keep the scope of the change smaller to help review but I think it also makes sense to make the change for both use cases together so I did that.

It turns out that it is better to refactor the `queryForLinkedDomains` in `EppResourceUtils` in stead of changing it here because `EppResourceUtils.isLinked` also uses `queryForLinkedDomains`.
___
*[core/src/main/java/google/registry/flows/ResourceFlowUtils.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/921#-MQSnpmd9dWPTKClaJ8K:-MQXs2Nd-N98FkirAIJ1:bxb8ajw) ([raw file](https://github.com/google/nomulus/blob/44a80c2049c9a373ae731a38f43f9db0363b8dc2/core/src/main/java/google/registry/flows/ResourceFlowUtils.java#L135)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Is this cast necessary? What fails without it? 
</blockquote></details>

Yeah, I think it mainly because `javax.persistence.Query` (returned by `createNativeQuery`) doesn't include the type information, it can only return the raw `List` or `Stream` without type information so we have to make the cast here.
___
*[core/src/main/java/google/registry/flows/ResourceFlowUtils.java, line 144 at r1](https://reviewable.io/reviews/google/nomulus/921#-MQSnuCh7ug_fWFjjG6m:-MQXt6_R8EkTiLSMK4o9:bgbyk6c) ([raw file](https://github.com/google/nomulus/blob/44a80c2049c9a373ae731a38f43f9db0363b8dc2/core/src/main/java/google/registry/flows/ResourceFlowUtils.java#L144)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Can you not set the result type to be String somewhere so that we can avoid this cast? I thought that was possible but I might be wrong. 
</blockquote></details>

The compiler complains the type mismatch if we don't do the cast, I guess it is also caused by the native `Query` object like the above case.


<!-- Sent from Reviewable.io -->

2021-01-08 18:33 UTC, gbrodman requested changes
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/921)* status: all files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/main/java/google/registry/flows/ResourceFlowUtils.java, line 129 at r1](https://reviewable.io/reviews/google/nomulus/921#-MQSn_Q8CGODkBWnCZep:-MQYGWpu5v_v2conDTie:bqog80t) ([raw file](https://github.com/google/nomulus/blob/44a80c2049c9a373ae731a38f43f9db0363b8dc2/core/src/main/java/google/registry/flows/ResourceFlowUtils.java#L129)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

Yeah, my original idea was to keep the scope of the change smaller to help review but I think it also makes sense to make the change for both use cases together so I did that.

It turns out that it is better to refactor the `queryForLinkedDomains` in `EppResourceUtils` in stead of changing it here because `EppResourceUtils.isLinked` also uses `queryForLinkedDomains`.
</blockquote></details>

Agreed
___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 423 at r2](https://reviewable.io/reviews/google/nomulus/921#-MQYFpu95kVwjKXNe0uN:-MQYFpu95kVwjKXNe0uO:b-koa27h) ([raw file](https://github.com/google/nomulus/blob/70e555552a7469d1f1f3cc26975499ddf05b9002/core/src/main/java/google/registry/model/EppResourceUtils.java#L423)):*
> ```Java
>                           .getEntityManager()
>                           .createQuery(CONTACT_LINKED_DOMAIN_QUERY, String.class)
>                           .setParameter("fkRepoId", key)
> ```

key.getSqlKey() ?
___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 433 at r2](https://reviewable.io/reviews/google/nomulus/921#-MQYFw4XCBKdiDMAO42Q:-MQYFw4XCBKdiDMAO42R:be99v42) ([raw file](https://github.com/google/nomulus/blob/70e555552a7469d1f1f3cc26975499ddf05b9002/core/src/main/java/google/registry/model/EppResourceUtils.java#L433)):*
> ```Java
>                           .setParameter("now", now.toDate());
>                 }
>                 return (ImmutableSet<VKey<DomainBase>>)
> ```

casting is gross but hopefully temporary in the long run? 


<!-- Sent from Reviewable.io -->

2021-01-08 20:52 UTC, hstonec reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/921)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 423 at r2](https://reviewable.io/reviews/google/nomulus/921#-MQYFpu95kVwjKXNe0uN:-MQYjzzC4nWjzqrQ7_mM:bfh2tfz) ([raw file](https://github.com/google/nomulus/blob/70e555552a7469d1f1f3cc26975499ddf05b9002/core/src/main/java/google/registry/model/EppResourceUtils.java#L423)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

key.getSqlKey() ?
</blockquote></details>

This is a JPQL query which requires the parameter to be the same type as the property type(as you can see 1 line below that I passed `now` instead of `now.toDate()` because it requires jodaTime).
___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 433 at r2](https://reviewable.io/reviews/google/nomulus/921#-MQYFw4XCBKdiDMAO42Q:-MQYl8Kq8IvgPiX-LVtV:b-jk0emd) ([raw file](https://github.com/google/nomulus/blob/70e555552a7469d1f1f3cc26975499ddf05b9002/core/src/main/java/google/registry/model/EppResourceUtils.java#L433)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

casting is gross but hopefully temporary in the long run? 
</blockquote></details>

Yeah, I think after the migration we may be able to refactor this or get rid of the query at all.


<!-- Sent from Reviewable.io -->

2021-01-12 21:11 UTC, gbrodman approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/921)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-13 15:56 UTC, merged