Add object comparison to replay tests
google/nomulus pull request #925
Opened 2021-01-11 15:39 UTC by mindhog

Allow optional object comparison in the replay test extension and enable it
for the DomainCreateFlow test.

To faciliate this, add two new field annotations to ImmutableObject:
DoNotCompare, to be used for fields that are not relevant to either database,
and Insignificant, to be used for fields that are mutated after they have been                                                                    
accessed and therefore violate immutability (there is currently only one of                                                                       
these, however we might discover more in the course of adding more comparisons
to the replay test.

2021-01-12 17:29 UTC, hstonec requested changes
> Reviewed 6 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/925)* status: 6 of 16 files reviewed, 3 unresolved discussions (waiting on @hstonec and @mindhog)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumListUtils.java, line 116 at r1](https://reviewable.io/reviews/google/nomulus/925#-MQrTf1f4Pn3NySoXEvC:-MQrTf1f4Pn3NySoXEvD:b9aae0r) ([raw file](https://github.com/google/nomulus/blob/00dd911ecb395ebe714f2331cd8b4f79b881b182/core/src/main/java/google/registry/model/registry/label/PremiumListUtils.java#L116)):*
> ```
>       //      logger.atSevere().withCause(t).log(
>       //          "Error loading price of domain %s.%s from Cloud SQL.", label,
>       // registry.getTldStr());
> ```
Why comment out these logs?
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 43 at r1](https://reviewable.io/reviews/google/nomulus/925#-MQrcMoe0BZhA9RlNZke:-MQrcMof8TIOFq-Ep0Px:b207p4f) ([raw file](https://github.com/google/nomulus/blob/00dd911ecb395ebe714f2331cd8b4f79b881b182/core/src/test/java/google/registry/testing/ReplayExtension.java#L43)):*
> ```
>  * <p>If the "compare" flag is set in the constructor, this will also compare all touched objects in
>  * both databases after performing the replay.
> ```
How do we determine if we need to enable the comparison? I guess I am just worried if it is safe to not compare everything as ideally they are supposed to be same.
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 50 at r1](https://reviewable.io/reviews/google/nomulus/925#-MQrUQt7AQyzlWeOCELi:-MQrUQt7AQyzlWeOCELj:b8oy1ra) ([raw file](https://github.com/google/nomulus/blob/00dd911ecb395ebe714f2331cd8b4f79b881b182/core/src/test/java/google/registry/testing/ReplayExtension.java#L50)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   public ReplayExtension(FakeClock clock, boolean compare) {
>     this.clock = clock;
>     this.compare = compare;
>   }
> ```
</details>

How about having some static factory methods to avoid the boolean parameter? Like `createComparable(clock)` and `createNonComparable(clock)`.

Also, why is the `@DoNotCompare` not sufficient in the case that `compare = false`? If certain mutable fields are excluded from the comparison, I'd expect the rest of the fields are supposed to be same.


<!-- Sent from Reviewable.io -->

2021-01-14 15:56 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/925)* status: 6 of 15 files reviewed, 3 unresolved discussions (waiting on @hstonec)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumListUtils.java, line 116 at r1](https://reviewable.io/reviews/google/nomulus/925#-MQrTf1f4Pn3NySoXEvC:-MR0JMDY3K5jxQObTwB9:bopyedo) ([raw file](https://github.com/google/nomulus/blob/00dd911ecb395ebe714f2331cd8b4f79b881b182/core/src/main/java/google/registry/model/registry/label/PremiumListUtils.java#L116)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
>       //      logger.atSevere().withCause(t).log(
>       //          "Error loading price of domain %s.%s from Cloud SQL.", label,
>       // registry.getTldStr());
> ```
Why comment out these logs?
</blockquote></details>

Gah!  I knew this was going to happen.  I've been commenting it out locally to remove the noisy severe error stack trace (as Ben suggested).  It was only a matter of time before it ended up in a CL.

Thanks for catching it!
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 43 at r1](https://reviewable.io/reviews/google/nomulus/925#-MQrcMoe0BZhA9RlNZke:-MR0JsmD2ZFCN5G_q4KO:blhnkf7) ([raw file](https://github.com/google/nomulus/blob/00dd911ecb395ebe714f2331cd8b4f79b881b182/core/src/test/java/google/registry/testing/ReplayExtension.java#L43)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
>  * <p>If the "compare" flag is set in the constructor, this will also compare all touched objects in
>  * both databases after performing the replay.
> ```
How do we determine if we need to enable the comparison? I guess I am just worried if it is safe to not compare everything as ideally they are supposed to be same.
</blockquote></details>

We want to enable it for all replay tests.  I've put it on a flag because it likely requires fixes and I didn't want to have to deal with fixing everything all at once.

I'm going to work through all of the replay tests with this.
___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 50 at r1](https://reviewable.io/reviews/google/nomulus/925#-MQrUQt7AQyzlWeOCELi:-MR0L_TwD5U8_sjssCIH:bx9zifl) ([raw file](https://github.com/google/nomulus/blob/00dd911ecb395ebe714f2331cd8b4f79b881b182/core/src/test/java/google/registry/testing/ReplayExtension.java#L50)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
>   public ReplayExtension(FakeClock clock, boolean compare) {
>     this.clock = clock;
>     this.compare = compare;
>   }
> ```
How about having some static factory methods to avoid the boolean parameter? Like `createComparable(clock)` and `createNonComparable(clock)`.

Also, why is the `@DoNotCompare` not sufficient in the case that `compare = false`? If certain mutable fields are excluded from the comparison, I'd expect the rest of the fields are supposed to be same.
</blockquote></details>

Added the static factory methods (used createWith/Without as that seemed more consistent with extension naming).

Regarding DoNotCompare, I'm not sure I understand the question?

If you're asking why we also need "Insignificant" , the semantics are different: "DoNotCompare" affects only isEqualAcrossDatabases(), which is done specifically for cross database comparison and does not break immutability.  "Insignificant" affects the memoized hash value,  A difference in those fields affects equality checks throughout the codebase.
 


<!-- Sent from Reviewable.io -->

2021-01-15 17:24 UTC, hstonec requested changes
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/925)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 50 at r1](https://reviewable.io/reviews/google/nomulus/925#-MQrUQt7AQyzlWeOCELi:-MR5zXFoDkpjzbRgLdRm:b-19ik13) ([raw file](https://github.com/google/nomulus/blob/00dd911ecb395ebe714f2331cd8b4f79b881b182/core/src/test/java/google/registry/testing/ReplayExtension.java#L50)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Added the static factory methods (used createWith/Without as that seemed more consistent with extension naming).

Regarding DoNotCompare, I'm not sure I understand the question?

If you're asking why we also need "Insignificant" , the semantics are different: "DoNotCompare" affects only isEqualAcrossDatabases(), which is done specifically for cross database comparison and does not break immutability.  "Insignificant" affects the memoized hash value,  A difference in those fields affects equality checks throughout the codebase.
 
</blockquote></details>

I see, thanks for the explanation. So, I think what I am confused is what is the problem that prevents us from doing the cross database comparison even we exclude certain fields with `@DoNotCompare`?


<!-- Sent from Reviewable.io -->

2021-01-15 18:37 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/925)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 50 at r1](https://reviewable.io/reviews/google/nomulus/925#-MQrUQt7AQyzlWeOCELi:-MR6Fd-i1zoB2t_H1Ji0:b-t09p4e) ([raw file](https://github.com/google/nomulus/blob/00dd911ecb395ebe714f2331cd8b4f79b881b182/core/src/test/java/google/registry/testing/ReplayExtension.java#L50)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

I see, thanks for the explanation. So, I think what I am confused is what is the problem that prevents us from doing the cross database comparison even we exclude certain fields with `@DoNotCompare`?
</blockquote></details>

I believe it is because the one case where we're using the Insignificant field is DomainTransactionRecord.id, which is not currently a top-level entity object and we're only checking the DoNotCompare label on top-level objects (by "top-level" I mean "the object is an Entity in Datastore").  That is to say, isEqualAcrossDatabases() is not currently recursive. 

This in itself is problematic, and I need to do something about it before comparisons will work for DomainRenewFlowTest (which needs a DoNotCompare for the serverApproveEntities field on a TransferData object that is accessed through a DomainBase object).  However, I think in conjunction with that we'll probably also want to do something to ensure that the final hash values of our persisted objects are correct -- basically, enforcing the use of the Insignificant annotation where appropriate.  


<!-- Sent from Reviewable.io -->

2021-01-15 19:19 UTC, hstonec approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/925)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/test/java/google/registry/testing/ReplayExtension.java, line 50 at r1](https://reviewable.io/reviews/google/nomulus/925#-MQrUQt7AQyzlWeOCELi:-MR6U5UPDv9rPe5GUXzz:b9y6xnt) ([raw file](https://github.com/google/nomulus/blob/00dd911ecb395ebe714f2331cd8b4f79b881b182/core/src/test/java/google/registry/testing/ReplayExtension.java#L50)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I believe it is because the one case where we're using the Insignificant field is DomainTransactionRecord.id, which is not currently a top-level entity object and we're only checking the DoNotCompare label on top-level objects (by "top-level" I mean "the object is an Entity in Datastore").  That is to say, isEqualAcrossDatabases() is not currently recursive. 

This in itself is problematic, and I need to do something about it before comparisons will work for DomainRenewFlowTest (which needs a DoNotCompare for the serverApproveEntities field on a TransferData object that is accessed through a DomainBase object).  However, I think in conjunction with that we'll probably also want to do something to ensure that the final hash values of our persisted objects are correct -- basically, enforcing the use of the Insignificant annotation where appropriate.  
</blockquote></details>

I see, that makes sense.


<!-- Sent from Reviewable.io -->

2021-01-15 19:20 UTC, merged