Convert (most) HistoryEntry ofy calls to tm
google/nomulus pull request #933
Opened 2021-01-19 18:15 UTC by gbrodman

As part of this change, it was necessary to do changes in the JPATM that
are similar (but the opposite) of the changes that we did in
DatastoreTM with regards to converting HistoryEntries to and from the
*History classes.

We leave the ofy() calls in the MapReduce ResaveAllHistoryEntriesAction
for now; that can be converted during the Beam pipeline transition.

Some other tests required registrar-name fixes as well -- because
*History objects have a foreign key on the Registrar table, we have to
use a "real" registrar name in tests.

2021-01-20 19:44 UTC, gbrodman commented
no changes in the version I just pushed, just hoping to fix the LGTM build by retrying

2021-01-21 14:18 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/933)* status: 0 of 25 files reviewed, 5 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 45 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Fs173NvWj2VcQvZv:-MR_Fs186g-YkLNU1__b:bnfh8ct) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L45)):*
> ```
> jpaTm().assertInTransaction();
> ```
I was wondering why not just wrap the whole method in a transaction? Nested transactions are fine as jpaTm will resolve them.
___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 65 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_IkQz40px03_3ecWh:-MR_IkQz40px03_3ecWi:b-2vb7nr) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L65)):*
> ```
> String tableName = String.format("%sHistory", parentObjectPrefix);
> ```
I think you can use `String entityName = jpaTm().getEntityManager().getMetamodel().entity(clazz).getName()` to retrieve the entity name.
___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Eg2n40q8mIbjb7wv:-MR_Eg2n40q8mIbjb7ww:b-7a03su) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L91)):*
> ```
> clazz.getSimpleName()
> ```
I think you can use this to retrieve the entity name: `String entityName = jpaTm().getEntityManager().getMetamodel().entity(clazz).getName();`
___
*[core/src/main/java/google/registry/rdap/RdapJsonFormatter.java, line 938 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_H8UaDD78se3EuiWw:-MR_H8UaDD78se3EuiWx:b1lzxpp) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L938)):*
> ```
> private static Iterable<? extends HistoryEntry> loadHistoryEntriesForResource
> ```
I was wondering why not just make `HistoryEntryDao.loadHistoryObjectsForResource` the same as this one? That way we don't need to expose the implementation details to the business layer, like `RdapJsonFormatter`.
___
*[core/src/main/java/google/registry/tools/GetHistoryEntriesCommand.java, line 90 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Hewh8L3UY4rUrP8s:-MR_Hewh8L3UY4rUrP8t:b-trnzrn) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/tools/GetHistoryEntriesCommand.java#L90)):*
<details><summary><i alt="summary">Quoted 27 lines of code…</i></summary>

> ```
>   private Iterable<? extends HistoryEntry> loadEntriesForSingleResource(
>       VKey<? extends EppResource> parentKey) {
>     if (tm().isOfy()) {
>       return ofy()
>           .load()
>           .type(HistoryEntry.class)
>           .ancestor(parentKey.getOfyKey())
>           .order("modificationTime")
>           .filter("modificationTime >=", after)
>           .filter("modificationTime <=", before);
>     } else {
>       return jpaTm()
>           .transact(() -> HistoryEntryDao.loadHistoryObjectsForResource(parentKey, after, before));
>     }
>   }
>   private Iterable<? extends HistoryEntry> loadAllHistoryEntries() {
>     if (tm().isOfy()) {
>       return ofy()
>           .load()
>           .type(HistoryEntry.class)
>           .order("modificationTime")
>           .filter("modificationTime >=", after)
>           .filter("modificationTime <=", before);
>     } else {
>       return jpaTm().transact(() -> HistoryEntryDao.loadAllHistoryObjects(after, before));
>     }
>   }
> ```
</details>

I have similar question as above, why not just make the corresponding functions in `HistoryEntryDao` the same as these two?


<!-- Sent from Reviewable.io -->

2021-01-21 16:34 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/933)* status: 0 of 25 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @hstonec)

___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 45 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Fs173NvWj2VcQvZv:-MR_iaEZ-EO9VfAy_LoA:baw2qmq) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L45)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> jpaTm().assertInTransaction();
> ```
I was wondering why not just wrap the whole method in a transaction? Nested transactions are fine as jpaTm will resolve them.
</blockquote></details>

The theory is that the DAO shouldn't be responsible for transaction management since it is just a simple retriever -- a transaction should usually be at the level of business-level logic, or a single "action" which is outside the scope of the DAO. I don't think it's terrible either way though 

One plus is that it makes testing easier if we have the transaction inside the DAO, I suppose.
___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 65 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_IkQz40px03_3ecWh:-MR_k2rC4fee6Ne3bP-E:b3brru5) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L65)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> String tableName = String.format("%sHistory", parentObjectPrefix);
> ```
I think you can use `String entityName = jpaTm().getEntityManager().getMetamodel().entity(clazz).getName()` to retrieve the entity name.
</blockquote></details>

good call, that's better
___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Eg2n40q8mIbjb7wv:-MR_k3t05KOF5yNg_CA4:b3brru5) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L91)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> clazz.getSimpleName()
> ```
I think you can use this to retrieve the entity name: `String entityName = jpaTm().getEntityManager().getMetamodel().entity(clazz).getName();`
</blockquote></details>

good call, that's better
___
*[core/src/main/java/google/registry/rdap/RdapJsonFormatter.java, line 938 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_H8UaDD78se3EuiWw:-MR_mldo6ZONATiNhlEJ:bjaayd8) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L938)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> private static Iterable<? extends HistoryEntry> loadHistoryEntriesForResource
> ```
I was wondering why not just make `HistoryEntryDao.loadHistoryObjectsForResource` the same as this one? That way we don't need to expose the implementation details to the business layer, like `RdapJsonFormatter`.
</blockquote></details>

You mean in terms of one, the other, or both of
1. splitting the logic to ofy or jpa based on what the current transaction manager is?
2. Sorting
?


<!-- Sent from Reviewable.io -->

2021-01-21 18:41 UTC, hstonec requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/933)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @hstonec)

___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Eg2n40q8mIbjb7wv:-MRaDdU3AdAgDDYbqYJ-:b2exqa4) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L91)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

good call, that's better
</blockquote></details>

Did you submit the change? It looks the same as before.
___
*[core/src/main/java/google/registry/rdap/RdapJsonFormatter.java, line 938 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_H8UaDD78se3EuiWw:-MRaEE251ako9ww-QgBl:b-ccxbbj) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L938)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

You mean in terms of one, the other, or both of
1. splitting the logic to ofy or jpa based on what the current transaction manager is?
2. Sorting
?
</blockquote></details>

Sorry, I mean why not just make `HistoryEntryDao.loadHistoryObjectsForResour` work for both `ofy` and `jpa` by merging the logic of `loadHistoryEntriesForResource` to it? That way we can delete `loadHistoryEntriesForResource` and make the Dao the only place using `ofy` and `jpa`.


<!-- Sent from Reviewable.io -->

2021-01-21 20:19 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/933)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @hstonec)

___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 45 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Fs173NvWj2VcQvZv:-MRaaSD04rJu53bHjkpX:byg0i39) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L45)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

The theory is that the DAO shouldn't be responsible for transaction management since it is just a simple retriever -- a transaction should usually be at the level of business-level logic, or a single "action" which is outside the scope of the DAO. I don't think it's terrible either way though 

One plus is that it makes testing easier if we have the transaction inside the DAO, I suppose.
</blockquote></details>

Yeah, I think it's better with the transactions inside the DAO -- this way the caller doesn't need to wonder if we're using ofy or JPA w/r/t starting transactions. 
___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Eg2n40q8mIbjb7wv:-MRaKeoC4106sukWzheU:b-dm0e5x) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L91)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

Did you submit the change? It looks the same as before.
</blockquote></details>

Not yet, I was waiting to resolve the other comments (sorry for the confusion) 
___
*[core/src/main/java/google/registry/rdap/RdapJsonFormatter.java, line 938 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_H8UaDD78se3EuiWw:-MRaKhh_Bcjga7selqqE:b-er0dra) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L938)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

Sorry, I mean why not just make `HistoryEntryDao.loadHistoryObjectsForResour` work for both `ofy` and `jpa` by merging the logic of `loadHistoryEntriesForResource` to it? That way we can delete `loadHistoryEntriesForResource` and make the Dao the only place using `ofy` and `jpa`.
</blockquote></details>

Yep, so both 1 and 2. That makes sense and is what I thought, just wanted to make sure we were on the same page. 
___
*[core/src/main/java/google/registry/tools/GetHistoryEntriesCommand.java, line 90 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Hewh8L3UY4rUrP8s:-MRaaY3cDABMxSqM78qF:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/tools/GetHistoryEntriesCommand.java#L90)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
>   private Iterable<? extends HistoryEntry> loadEntriesForSingleResource(
>       VKey<? extends EppResource> parentKey) {
>     if (tm().isOfy()) {
>       return ofy()
>           .load()
>           .type(HistoryEntry.class)
>           .ancestor(parentKey.getOfyKey())
>           .order("modificationTime")
>           .filter("modificationTime >=", after)
>           .filter("modificationTime <=", before);
>     } else {
>       return jpaTm()
>           .transact(() -> HistoryEntryDao.loadHistoryObjectsForResource(parentKey, after, before));
>     }
>   }
>   private Iterable<? extends HistoryEntry> loadAllHistoryEntries() {
>     if (tm().isOfy()) {
>       return ofy()
>           .load()
>           .type(HistoryEntry.class)
>           .order("modificationTime")
>           .filter("modificationTime >=", after)
>           .filter("modificationTime <=", before);
>     } else {
>       return jpaTm().transact(() -> HistoryEntryDao.loadAllHistoryObjects(after, before));
>     }
>   }
> ```
I have similar question as above, why not just make the corresponding functions in `HistoryEntryDao` the same as these two?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-21 20:20 UTC, gbrodman reviewed
Note: I realized I should write tests for the HistoryEntryDao so i'll write those up now / soon 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/933#-:-MRaacs152yvT_Qtysg_:b-ywqzhb)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @hstonec)



<!-- Sent from Reviewable.io -->

2021-01-22 15:25 UTC, hstonec requested changes
I assume you are still working on the test right?

> Reviewed 19 of 20 files at r1, 2 of 6 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/933#-:-MRegqc4-ukklVwprFY3:b-j7ds9f)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 45 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Fs173NvWj2VcQvZv:-MRb3RvNBwUFYYyCth8x:b-1xqunv) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L45)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah, I think it's better with the transactions inside the DAO -- this way the caller doesn't need to wonder if we're using ofy or JPA w/r/t starting transactions. 
</blockquote></details>

Yeah, and it is also consistent with the other DAOs we have.


<!-- Sent from Reviewable.io -->

2021-01-22 18:28 UTC, gbrodman reviewed
yep, sorry for the delay -- just pushed it 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/933#-:-MRfLhPj1fyhndvtDrpt:bzfklkr)* status: 25 of 26 files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java, line 45 at r2](https://reviewable.io/reviews/google/nomulus/933#-MR_Fs173NvWj2VcQvZv:-MRfLjGB-zz8KGww82Yd:b-896fix) ([raw file](https://github.com/google/nomulus/blob/8d8bf5685dd741ec135a90a87cea1ba39f522590/core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java#L45)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

Yeah, and it is also consistent with the other DAOs we have.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-22 18:34 UTC, hstonec approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/933)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-22 19:43 UTC, merged