Refactor SignedMarkRevocationListDao for easy primary database cutover
google/nomulus pull request #943
Opened 2021-01-26 00:04 UTC by sarahcaseybot

2021-01-26 17:03 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java, line 108 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRz_Aor5q2Owa5osM8y:-MRz_Aor5q2Owa5osM8z:b-y8v0yp) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java#L108)):*
> ```Java
>       memoizeWithShortExpiration(
>           () -> {
>             // (TODO(Sarahbot@): Load value for primary database from Datastore once go/r3pr/926 is
> ```

It might be a bit hairy in terms of branch management, but it's probably better to have this branch based off the branch from #926 . That way, we can actually implement the real solution instead of having a middle awkward state, and when that branch gets merged in we can just change the target branch of this PR to be master. 

Does that seem reasonable to you? 

(similar thought for `save()` below) 
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRzcKBx4W3MT98q3nhn:-MRzcKBx4W3MT98q3nho:b6b4s96) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L45)):*
> ```Java
>   private static final FluentLogger logger = FluentLogger.forEnclosingClass();
> 
>   @VisibleForTesting static final int SHARD_SIZE = 10000;
> ```

I think this is a duplicate variable? Is this defined both in the DAO and the class?
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 47 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRzbmSx7_BHvsAFyWtW:-MRzbmSy1039cOpH9QSQ:b8il1id) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L47)):*
> ```Java
>   @VisibleForTesting static final int SHARD_SIZE = 10000;
> 
>   /**
> ```

Javadoc comments should conform to the standard javadoc style, with a short single-line descriptive phrase with a `<p>`-tagged paragraph description later on 

If we can fix these everywhere in this review that'd be great; I know that some of them already existed in the code :) 
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 53 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRzd8-r0RTe5y0C9yQj:-MRzd8-r0RTe5y0C9yQk:bcsdo8p) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L53)):*
> ```Java
>    * logged but no exception will be thrown.
>    */
>   static SignedMarkRevocationList load(String primaryDatabase) {
> ```

In general, I think it's probably best if the caller doesn't need to know which database is primary. This might be reliant on #926 going through, but it seems better to me if the DAO encapsulates all of the logic of switching between databases. That way, the SignedMarkRevocationList class doesn't need to worry about that logic and it can exist only in the class that deals with retrieving from whichever data store.  
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 56 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRzZfS--9iUPrVzY8fB:-MRzZfS--9iUPrVzY8fC:b-g800od) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L56)):*
> ```Java
>     SignedMarkRevocationList primaryList;
>     switch (primaryDatabase) {
>       case "Datastore":
> ```

It's better to use an enum instead of a raw string (apply this everywhere that these strings are used) 
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 75 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRzcOS7-Ap-EfyqVq7r:-MRzcOS7-Ap-EfyqVq7s:b-utt6pu) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L75)):*
> ```Java
>    * database.
>    */
>   private static void loadAndCompare(SignedMarkRevocationList primaryList, String primaryDatabase) {
> ```

this method is copied directly right? Reviewable doesn't answer that question well unfortunately 
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 155 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRzcZiV0fmomEX3rCCw:-MRzcZiV0fmomEX3rCCx:b2awksy) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L155)):*
> ```Java
>    * error will be logged but no exception will be thrown.
>    */
>   static void save(String primaryDatabase, SignedMarkRevocationList signedMarkRevocationList) {
> ```

`loadAndCompare` and `save` have their parameters in the opposite order; we should be consistent on the parameter ordering to avoid confusion 


<!-- Sent from Reviewable.io -->

2021-01-26 17:25 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 56 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRzZfS--9iUPrVzY8fB:-MRziCYj-XWcinSZIjX5:bjvaeob) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L56)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It's better to use an enum instead of a raw string (apply this everywhere that these strings are used) 
</blockquote></details>

Refer to Chapter 6 of Effective Java 3rd ed ( http://go/ej3e ), starting on page 157.  The most relevant subsection is the first one entitled "Use enums instead of int constants", which applies equally to freeform strings as to ints, but the entire chapter is worth a read as it's full of good info (same goes for the entire book).


<!-- Sent from Reviewable.io -->

2021-01-26 17:28 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 56 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRzZfS--9iUPrVzY8fB:-MRzjCnr4VwKoDHSoG7N:b-rhfpaq) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L56)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Refer to Chapter 6 of Effective Java 3rd ed ( http://go/ej3e ), starting on page 157.  The most relevant subsection is the first one entitled "Use enums instead of int constants", which applies equally to freeform strings as to ints, but the entire chapter is worth a read as it's full of good info (same goes for the entire book).
</blockquote></details>

Oh fun, there's a way to link directly to the relevant chapter:  http://go/ej3e-34


<!-- Sent from Reviewable.io -->

2021-01-28 16:08 UTC, gbrodman reviewed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: all files reviewed, 7 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-02 16:03 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java, line 108 at r1](https://reviewable.io/reviews/google/nomulus/943#-MRz_Aor5q2Owa5osM8y:-MSYU-I6-AMsIOa_JUjQ:b-whquo1) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java#L108)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I tried doing this, but couldn't figure out how to do it without potentially losing everything. I think it's best to just hold off on this PR until [#926](https://github.com/google/nomulus/pull/926) is merged. 
</blockquote></details>

Sounds good, we can punt until then. Let us know when that's the case please! 


<!-- Sent from Reviewable.io -->

2021-02-08 22:37 UTC, gbrodman requested changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: all files reviewed, 8 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/DatabaseMigrationUtils.java, line 44 at r2](https://reviewable.io/reviews/google/nomulus/943#-MT2l0RW7nK5t0ero4OI:-MT2l0RW7nK5t0ero4OJ:bh2bu5f) ([raw file](https://github.com/google/nomulus/blob/f3f194d0b2a029ee7d02251e78ad6342168b542f/core/src/main/java/google/registry/model/DatabaseMigrationUtils.java#L44)):*
> ```Java
>   public static PrimaryDatabase getPrimaryDatabase(TransitionId transitionId) {
>     Optional<DatabaseTransitionSchedule> schedule =
>         DatabaseTransitionSchedule.getCached(transitionId);
> ```

This isn't part of this PR, but why is the DatabaseTransitionSchedule's cache a cache from String -> schedule rather than TransitionId -> schedule? 
___
*[core/src/main/java/google/registry/model/DatabaseMigrationUtils.java, line 48 at r2](https://reviewable.io/reviews/google/nomulus/943#-MT2lEHf7bxKg8smHo8M:-MT2lEHf7bxKg8smHo8N:b-q6rwr0) ([raw file](https://github.com/google/nomulus/blob/f3f194d0b2a029ee7d02251e78ad6342168b542f/core/src/main/java/google/registry/model/DatabaseMigrationUtils.java#L48)):*
> ```Java
>       return PrimaryDatabase.DATASTORE;
>     }
>     return schedule.get().getPrimaryDatabase();
> ```

this whole thing can be simplified as 

`return DatabaseTransitionSchedule.getCached(transitionId).map(DatabaseTransitionSchedule::getPrimaryDatabase).orElse(PrimaryDatabase.DATASTORE);`
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java, line 107 at r2](https://reviewable.io/reviews/google/nomulus/943#-MT2lWf6C-4cDOJjREUm:-MT2lWf6C-4cDOJjREUn:bsvmyry) ([raw file](https://github.com/google/nomulus/blob/f3f194d0b2a029ee7d02251e78ad6342168b542f/core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java#L107)):*
> ```Java
>   private static final Supplier<SignedMarkRevocationList> CACHE =
>       memoizeWithShortExpiration(
>           () -> {
> ```

nit: change lambda to method reference
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 48 at r2](https://reviewable.io/reviews/google/nomulus/943#-MT2ljrz16mTQ99RLBVY:-MT2ljrz16mTQ99RLBVZ:bn7135r) ([raw file](https://github.com/google/nomulus/blob/f3f194d0b2a029ee7d02251e78ad6342168b542f/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L48)):*
> ```Java
> 
>   private static final FluentLogger logger = FluentLogger.forEnclosingClass();
>   private static final TransitionId TRANSITION_ID = TransitionId.SIGNED_MARK_REVOCATION_LIST;
> ```

This is unnecessary, just reference the field either with a static import or with `TransitionId.SIGNED_MARK_REVOCATION_LIST` if you don't mind the verbosity 
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 53 at r2](https://reviewable.io/reviews/google/nomulus/943#-MT2lt5uD9L2YWYlMFWH:-MT2lt5uD9L2YWYlMFWI:b-341qh2) ([raw file](https://github.com/google/nomulus/blob/f3f194d0b2a029ee7d02251e78ad6342168b542f/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L53)):*
> ```Java
>    * Loads the {@link SignedMarkRevocationList}.
>    *
>    * <p>loads the list from the specified primary database, and attempts to load from the secondary
> ```

nit: capital L
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 69 at r2](https://reviewable.io/reviews/google/nomulus/943#-MT2m1Y1-NXhL6_26Th3:-MT2m1Y1-NXhL6_26Th4:b-uu60g5) ([raw file](https://github.com/google/nomulus/blob/f3f194d0b2a029ee7d02251e78ad6342168b542f/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L69)):*
> ```Java
>         primaryList = loadFromCloudSql().get();
>         break;
>       default:
> ```

this switch / default statement feels like overkill when it's going to only have two possible values 
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 170 at r2](https://reviewable.io/reviews/google/nomulus/943#-MT2mEjS8BklGIgi1qov:-MT2mEjS8BklGIgi1qow:bd3r011) ([raw file](https://github.com/google/nomulus/blob/f3f194d0b2a029ee7d02251e78ad6342168b542f/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L170)):*
> ```Java
>     PrimaryDatabase primaryDatabase =
>         tm().transactNew(() -> DatabaseMigrationUtils.getPrimaryDatabase(TRANSITION_ID));
>     switch (primaryDatabase) {
> ```

same comment re: switch being unnecessarily complex
___
*[core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java, line 143 at r1](https://reviewable.io/reviews/google/nomulus/943#-MT2mcF-8yguUInM2XEJ:-MT2mcF-8yguUInM2XEK:b69ypa7) ([raw file](https://github.com/google/nomulus/blob/392806995ca9ed3e587502f90da7736070e84f60/core/src/test/java/google/registry/model/smd/SignedMarkRevocationListTest.java#L143)):*
> ```Java
> 
>   @Test
>   void test_getCreationTime_missingInCloudSQL() {
> ```

shouldn't something like this test still exist somewhere?


<!-- Sent from Reviewable.io -->

2021-02-10 21:16 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 170 at r2](https://reviewable.io/reviews/google/nomulus/943#-MT2mEjS8BklGIgi1qov:-MTCmsuEAqLc9SFyY1h9:b-obxf8p) ([raw file](https://github.com/google/nomulus/blob/f3f194d0b2a029ee7d02251e78ad6342168b542f/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L170)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

see other comment above re: this if/else statement
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 70 at r3](https://reviewable.io/reviews/google/nomulus/943#-MTCmSg-2d7fVRs97jXE:-MTCmSg-2d7fVRs97jXF:bxtes14) ([raw file](https://github.com/google/nomulus/blob/b9c8ba020a7f39374e9ce9501f7eb0e6e9fe14b8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L70)):*
> ```Java
>       primaryList = loadFromCloudSql();
>     } else {
>       throw new IllegalArgumentException("Unrecognized value for primary database.");
> ```

I'd say we would want to say the value here but tbh we probably don't even need this since there's only going to be two types of databases 

```
if (primaryDatabase.equals(DATASTORE) {
  primaryList = loadFromDatastore();
} else {
  primaryList = loadFromSql();
}
```

Same goes for the other else-if below
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 73 at r3](https://reviewable.io/reviews/google/nomulus/943#-MTClbFQ4Dt2-toC6tEk:-MTClbFQ4Dt2-toC6tEl:b-xbaynu) ([raw file](https://github.com/google/nomulus/blob/b9c8ba020a7f39374e9ce9501f7eb0e6e9fe14b8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L73)):*
> ```Java
>     }
>     if (!primaryList.isPresent()) {
>       throw new RuntimeException(String.format("List not found in %s.", primaryDatabase.name()));
> ```

When throwing new exceptions, avoid RuntimeException, see Effective Java pg. 301

In the vast majority of cases we can throw either IllegalArgumentException (the caller passed something bad in) or IllegalStateException, when the receiving object is in a bad state.
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 89 at r3](https://reviewable.io/reviews/google/nomulus/943#-MTCmqE87ttQRBNWIX8y:-MTCmqE87ttQRBNWIX8z:b-gfxa5b) ([raw file](https://github.com/google/nomulus/blob/b9c8ba020a7f39374e9ce9501f7eb0e6e9fe14b8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L89)):*
> ```Java
>     Optional<SignedMarkRevocationList> secondaryList =
>         primaryDatabase.equals(DATASTORE) ? loadFromCloudSql() : loadFromDatastore();
>     if (secondaryList.isPresent() && secondaryList.get().size() > 0) {
> ```

For this line, see CollectionUtils::isNullOrEmpty
___
*[core/src/test/java/google/registry/model/smd/SignedMarkRevocationListDaoTest.java, line 203 at r3](https://reviewable.io/reviews/google/nomulus/943#-MTCn5DM0QbK7mwFN2de:-MTCn5DM0QbK7mwFN2df:b-p8jfto) ([raw file](https://github.com/google/nomulus/blob/b9c8ba020a7f39374e9ce9501f7eb0e6e9fe14b8/core/src/test/java/google/registry/model/smd/SignedMarkRevocationListDaoTest.java#L203)):*
> ```Java
>         SignedMarkRevocationList.create(
>             fakeClock.nowUtc(), ImmutableMap.of("mark", fakeClock.nowUtc().minusHours(3)));
>     jpaTm().transact(() -> jpaTm().getEntityManager().persist(list2));
> ```

we should use the raw jpaTm().put/insert methods
___
*[core/src/test/java/google/registry/model/smd/SignedMarkRevocationListDaoTest.java, line 219 at r3](https://reviewable.io/reviews/google/nomulus/943#-MTCnEsO-M8woaaifUre:-MTCnEsO-M8woaaifUrf:b-vpgnyo) ([raw file](https://github.com/google/nomulus/blob/b9c8ba020a7f39374e9ce9501f7eb0e6e9fe14b8/core/src/test/java/google/registry/model/smd/SignedMarkRevocationListDaoTest.java#L219)):*
> ```Java
>     assertThat(thrown)
>         .hasMessageThat()
>         .contains("Signed mark revocation list in secondary database is empty.");
> ```

Can we specify the database (sql or datastore) in this message? 
___
*[core/src/test/java/google/registry/model/smd/SignedMarkRevocationListDaoTest.java, line 228 at r3](https://reviewable.io/reviews/google/nomulus/943#-MTCnJk-8j0oTv_rEgko:-MTCnJk-8j0oTv_rEgkp:b-p8jfto) ([raw file](https://github.com/google/nomulus/blob/b9c8ba020a7f39374e9ce9501f7eb0e6e9fe14b8/core/src/test/java/google/registry/model/smd/SignedMarkRevocationListDaoTest.java#L228)):*
> ```Java
>         SignedMarkRevocationList.create(
>             fakeClock.nowUtc(), ImmutableMap.of("mark", fakeClock.nowUtc().minusHours(1)));
>     jpaTm().transact(() -> jpaTm().getEntityManager().persist(list));
> ```

we should use the raw jpaTm().put/insert methods


<!-- Sent from Reviewable.io -->

2021-02-12 18:16 UTC, gbrodman requested changes
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 68 at r4](https://reviewable.io/reviews/google/nomulus/943#-MTMRbjE5AqaWUINPGcv:-MTMRbjE5AqaWUINPGcw:b-jqc4wj) ([raw file](https://github.com/google/nomulus/blob/0390c7e5f78f89f06510ce65cbf529dfbb8a8dc8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L68)):*
> ```Java
>     if (!primaryList.isPresent()) {
>       throw new IllegalStateException(
>           String.format("List not found in %s.", primaryDatabase.name()));
> ```

If we're going to throw an exception here, we should make this more clear -- what type of list are we talking about? We should also make it clear that this is the primary DB 
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 93 at r4](https://reviewable.io/reviews/google/nomulus/943#-MTMS1AM1tO7P_jjfV6N:-MTMS1AM1tO7P_jjfV6O:bav3rq9) ([raw file](https://github.com/google/nomulus/blob/0390c7e5f78f89f06510ce65cbf529dfbb8a8dc8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L93)):*
> ```Java
>                   "Unequal SM revocation lists detected, %s list with revision id"
>                       + " %d has %d different records than the current primary database list.",
>                   primaryDatabase.name(),
> ```

i think this should be the secondary list
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 116 at r4](https://reviewable.io/reviews/google/nomulus/943#-MTMS7KD3IgMa10Jy83G:-MTMS7KD3IgMa10Jy83H:bb0g18v) ([raw file](https://github.com/google/nomulus/blob/0390c7e5f78f89f06510ce65cbf529dfbb8a8dc8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L116)):*
> ```Java
>         throw new IllegalStateException(
>             String.format(
>                 "Signed mark revocation list in %s is empty.",
> ```

Should clarify that we're talking about the primary list
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 173 at r4](https://reviewable.io/reviews/google/nomulus/943#-MTMSBR_6gfxHXAT1ewA:-MTMSBR_6gfxHXAT1ewB:b-a85y2y) ([raw file](https://github.com/google/nomulus/blob/0390c7e5f78f89f06510ce65cbf529dfbb8a8dc8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L173)):*
> ```Java
>     PrimaryDatabase primaryDatabase =
>         tm().transactNew(
>                 () ->
> ```

Here's we're just doing the if-else statement (with no exception) and above we're doing if-elif-else (with an exception) 

we should choose one; the plain if-else is probably fine 


<!-- Sent from Reviewable.io -->

2021-02-12 18:28 UTC, gbrodman reviewed
> Reviewed 1 of 5 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: all files reviewed, 4 unresolved discussions (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-12 19:46 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: all files reviewed, 4 unresolved discussions (waiting on @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 173 at r4](https://reviewable.io/reviews/google/nomulus/943#-MTMSBR_6gfxHXAT1ewA:-MTMlslF2WaiJWx7aOmt:b-8xbq9k) ([raw file](https://github.com/google/nomulus/blob/0390c7e5f78f89f06510ce65cbf529dfbb8a8dc8/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L173)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Im confused by what you are referring to in this comment. There are no elifs in this class. If you are talking about the exception thrown in the load() method after loading from the primary database, that is necessary since the load only returns an optional and we have to check that it exists before attempting to compare it to the list from the secondary database.
</blockquote></details>

yeah reviewable was showing me old code unfortunately 


<!-- Sent from Reviewable.io -->

2021-02-12 21:37 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 69 at r5](https://reviewable.io/reviews/google/nomulus/943#-MTN8xHP0kPayqFFFZBO:-MTN8xHP0kPayqFFFZBP:bjqsm9u) ([raw file](https://github.com/google/nomulus/blob/95085d29c51fc838c157c8becb570b67d13d4a88/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L69)):*
> ```Java
>       throw new IllegalStateException(
>           String.format(
>               "Sm revocation list not found in the primary database (%s).",
> ```

What's up with the abbrev / capitalization here? It seems inconsistent 
___
*[core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java, line 75 at r5](https://reviewable.io/reviews/google/nomulus/943#-MTNA8dGC2vFuHFiuM23:-MTNA8dGC2vFuHFiuM24:b-8jy2pi) ([raw file](https://github.com/google/nomulus/blob/95085d29c51fc838c157c8becb570b67d13d4a88/core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java#L75)):*
> ```Java
>         () -> loadAndCompare(primaryDatabase, primaryList.get()),
>         String.format(
>             "Error loading and comparing the sm revocation list from the secondary database (%s).",
> ```

Why not just list out the object, `SignedMarkRevocationList`? Simpler. 


<!-- Sent from Reviewable.io -->

2021-02-14 04:44 UTC, gbrodman approved these changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/943)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-14 14:58 UTC, merged