Proposal for sql-injection prevention
google/nomulus pull request #954
Opened 2021-02-04 03:59 UTC by weiminyu

This PR proposes a coding style convention that helps prevent
SQL-injection attacks, and is easy to enforce in the presubmit check.

SQL-injections can be effectively prevented if all parameterized queries
are generated using the proper param-binding methods. In our project
which uses Hibernate exclusively, this can be achieved if we all follow
a simple convention: only use constant sql templates assigned to static
final String variables as the first parameter to creat(Native)Query
methods.

This PR adds a presubmit check to enforce the proposed rule, and
modified one class as a demo. If the team agrees with this proposal, we
will change all other use cases.

2021-02-04 19:17 UTC, mindhog reviewed
Interesting approach!  Couldn't we get the same benefit by also allowing a string constant?  Those could be also checked by regex.

I ask because IMO there's a lot to be gained by having the query string in close proximity to where its parameters are applied.  

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954#-:-MSiSuix9Gc7nKK3Lmj6:buy5k6p)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @CydeWeys, @gbrodman, @jianglai, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-04 20:41 UTC, weiminyu reviewed
Sure, if we can find a pattern that safely handles escapes. I can try but I'm not very good at this. And to be really useful, we will have to allow formatting-inspired concatenation of constants like "select " \+ "from".

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954#-:-MSikJkVBfmzObBmOY99:b-dhetaw)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @CydeWeys, @gbrodman, @jianglai, @mindhog, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-04 21:00 UTC, weiminyu reviewed
I think I figured it out.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954#-:-MSiq6f5CUXQxh43h79n:b-ifkqr0)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @CydeWeys, @gbrodman, @jianglai, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-04 21:41 UTC, CydeWeys reviewed
What does "String constant" mean exactly?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954#-:-MSizF9V01CEuMjNAXcI:b8arkq7)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @gbrodman, @jianglai, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-05 02:43 UTC, mindhog reviewed
https://download.mikroe.com/documents/compilers/mikroc/pic/help/string_constants.htm

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954#-:-MSk3WWPD_BUt_DEENR2:b-w7freg)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @gbrodman, @jianglai, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-05 03:25 UTC, weiminyu reviewed
Most call sites are accepted now. Those remaining use String.format() and need to be converted to Criteria-based queries.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954#-:-MSkD-RAEQD-BS0F1feO:b-j8ge9h)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @gbrodman, @jianglai, @mindhog, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-05 14:05 UTC, mindhog requested changes
Awesome!  I was going to offer my somewhat rusty regex skills, but you've pretty much nailed it.

LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954#-:-MSmSdf0CGhIBPrqSJMn:b3usji7)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @jianglai, @mindhog, @sarahcaseybot, and @weiminyu)

___
*[config/presubmits.py, line 200 at r2](https://reviewable.io/reviews/google/nomulus/954#-MSmUAtR7ks3brfBNQXp:-MSmUAtS31WcLrZ2KWCX:b-kssvbj) ([raw file](https://github.com/google/nomulus/blob/26ce87ef04c9feed809a9512e3c53c5c1802bba9/config/presubmits.py#L200)):*
> ```Python
>         #    parameter
>         r'.*\.create(Native)?Query\('
>         '(?!(\s*([A-Z_]+|"([^"]|\\")*"(\s*\+\s*"([^"]|\\")*")*)'
> ```

Use the "r" prefix for these strings as well.  You want the regex to process the backslashes, not the compiler.  As an example, "\\)" (without the r prefix) would be a literal end paren instead of a group ending.


<!-- Sent from Reviewable.io -->

2021-02-05 16:13 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @jianglai, @mindhog, and @sarahcaseybot)

___
*[config/presubmits.py, line 200 at r2](https://reviewable.io/reviews/google/nomulus/954#-MSmUAtR7ks3brfBNQXp:-MSmiwFVErG4HjLXK6Dd:b-896fix) ([raw file](https://github.com/google/nomulus/blob/26ce87ef04c9feed809a9512e3c53c5c1802bba9/config/presubmits.py#L200)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Use the "r" prefix for these strings as well.  You want the regex to process the backslashes, not the compiler.  As an example, "\\)" (without the r prefix) would be a literal end paren instead of a group ending.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 17:02 UTC, CydeWeys reviewed
> Proposal for sql-injection prevention

This commit summary line is gonna need to be rewritten prior to going in, something like "Add a presubmit check to require use of templated SQL strings"

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954#-:-MSn7z_QBU2rXkigHykH:bryxphm)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @jianglai, @mindhog, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-05 19:42 UTC, weiminyu reviewed
Will do

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954#-:-MSnhpGG6ZcFJEpXoH3J:bebrt1w)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @jianglai, @mindhog, and @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-05 20:24 UTC, mindhog approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/954)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys, @gbrodman, and @jianglai)



<!-- Sent from Reviewable.io -->

2021-02-07 00:28 UTC, merged