Add string constants for HTTP header names
google/nomulus pull request #956
Opened 2021-02-04 19:34 UTC by sarahcaseybot

2021-02-04 21:07 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/956)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 17 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSiqtv791wPhFm8f5kO:-MSiqtv791wPhFm8f5kP:b-7uszgo) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L17)):*
> ```Java
> package google.registry.util;
> 
> /** Utility class of HTTP header names. */
> ```

Needs more elaboration here, like "that are used for communication between the proxy and Nomulus"
___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 18 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSiqeXPBnPWnOKbBdcY:-MSiqeXPBnPWnOKbBdcZ:b-cu4qtq) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L18)):*
> ```Java
> 
> /** Utility class of HTTP header names. */
> public final class HttpHeaders {
> ```

`HttpHeaders` is a bit generic.  All of these headers are specifically for communication between the proxy and nomulus, right?  How about `ProxyHttpHeaders`?  It's a little bit longer, but you can also statically import at usage sites.
___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 21 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSir3ds5n4xiYNG2Vuh:-MSir3ds5n4xiYNG2Vui:b-ex52e7) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L21)):*
> ```Java
> 
>   /**
>    * Header used to pass a full SSL certificate from the proxy to the backend.
> ```

All of these Javadocs should specifically clarify that they're HTTP headers, e.g. "HTTP header used for the full SSL certificate..."
___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 21 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSirHbJ0n7rjspP6UIR:-MSirHbJ0n7rjspP6UIS:bbveo09) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L21)):*
> ```Java
> 
>   /**
>    * Header used to pass a full SSL certificate from the proxy to the backend.
> ```

"Backend" is a bit of an overloaded word -- in most of our codebase, "backend" specifically refers to the `backend` service running on GAE, which is not what's going on here -- these requests are actually going to the `default` and `pubapi` services.  I'd use a different word for all of these Javadocs that is less over-loaded, like "the registry GAE app" or "Nomulus".


<!-- Sent from Reviewable.io -->

2021-02-04 22:35 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/956)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 26 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSjAhsQ7xsr14tK2reJ:-MSjAhsQ7xsr14tK2reK:brcr6qk) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L26)):*
> ```Java
>    * certificate used for login to the backend for validation.
>    */
>   public static final String FULL_CERTIFICATE = "X-SSL-Full-Certificate";
> ```

Are these defined in any library files somewhere? I didn't see them in a cursory search but they might exist
___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 32 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSjAnOr9WUMtB_5l3nP:-MSjAnOr9WUMtB_5l3nQ:b-5wf90z) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L32)):*
> ```Java
> 
>   /** Header used to pass the client IP address from the proxy to the backend. */
>   public static final String IP_ADDRESS = "X-Forwarded-For";
> ```

I think this one exists in a library 


<!-- Sent from Reviewable.io -->

2021-02-05 15:30 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/956)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 18 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSiqeXPBnPWnOKbBdcY:-MSmnr9P64xMwsxFPJWX:b-7bcdgk) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L18)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks.  And I see now that this would've conflicted with `com.google.common.net.HttpHeaders`, so another reason to be more specific.
___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 26 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSjAhsQ7xsr14tK2reJ:-MSmnl-lEl3Pv2n_ykan:bg2h2nj) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L26)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I only found X-Forwarded-For in another library
</blockquote></details>

I wonder if it makes sense to centralize all of them here rather than pulling in headers from 3 different libraries from callsites?  E.g. 

```
public static final String X_FORWARDED_FOR = HttpHeaders.X_FORWARDED_FOR;
```

That way, everywhere else, all the headers being used would be coming from this one file.


<!-- Sent from Reviewable.io -->

2021-02-05 17:02 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/956)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 26 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSjAhsQ7xsr14tK2reJ:-MSn8HUP3U1y1su9F1Vl:bj2mnrc) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L26)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I wonder if it makes sense to centralize all of them here rather than pulling in headers from 3 different libraries from callsites?  E.g. 

```
public static final String X_FORWARDED_FOR = HttpHeaders.X_FORWARDED_FOR;
```

That way, everywhere else, all the headers being used would be coming from this one file.
</blockquote></details>

(That's a question for both of you.)


<!-- Sent from Reviewable.io -->

2021-02-05 19:17 UTC, gbrodman requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/956)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @sarahcaseybot)

___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 26 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSjAhsQ7xsr14tK2reJ:-MSnc2k7DtRyaM-7zrOe:bp0hf37) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L26)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

I think that's valuable for this header, but looking at the entire code base, I don't think it makes sense to add all uses of an HttpHeaders to this class since it will require significant refactoring across many classes and I fear it may inadvertently break something.
</blockquote></details>

Would would it break? I think centralization would be nice, but I haven't inspected the entire codebase. 


<!-- Sent from Reviewable.io -->

2021-02-08 22:22 UTC, gbrodman approved these changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/956)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[util/src/main/java/google/registry/util/ProxyHttpHeaders.java, line 40 at r2](https://reviewable.io/reviews/google/nomulus/956#-MT2j62TBpOdsLDBSfDK:-MT2j62TBpOdsLDBSfDL:bi8fwo0) ([raw file](https://github.com/google/nomulus/blob/77862340a145699e7ff07f939d80b64f03dbdd40/util/src/main/java/google/registry/util/ProxyHttpHeaders.java#L40)):*
> ```Java
> 
>   /**
>    * HTTP header name passed from Nomulus to proxy to indicate that an EPP session should be closed.
> ```

If we keep the old comment it fits on one line :P 


<!-- Sent from Reviewable.io -->

2021-02-08 22:30 UTC, CydeWeys reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/956)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[util/src/main/java/google/registry/util/HttpHeaders.java, line 26 at r1](https://reviewable.io/reviews/google/nomulus/956#-MSjAhsQ7xsr14tK2reJ:-MT2kaXO9IYFkIZjwfp0:b-3xjaax) ([raw file](https://github.com/google/nomulus/blob/7f917e60bd129976fd22579e77fd9f16c220798e/util/src/main/java/google/registry/util/HttpHeaders.java#L26)):*
<details><summary><i>Previously, sarahcaseybot wrote…</i></summary><blockquote>

It shouldn't break anything since it is just moving the definition of String constants. I'm just worried because many of the proxy classes use headers, but I do not fully understand how all these classes work, so i'm weary of modifying them. 
</blockquote></details>

I wasn't suggesting adding everything used from `HttpHeaders` here, just the others that you previously had in this file but then removed on Gus's suggestion.  So only the headers that are passed between the proxy and Nomulus.  That's not that many, right?

Also if you're just refactoring strings that have the same value it has a low potential to break anything.


<!-- Sent from Reviewable.io -->

2021-02-11 14:06 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/956)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-11 16:25 UTC, gbrodman approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/956)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)



<!-- Sent from Reviewable.io -->

2021-02-11 17:02 UTC, merged