Revert BEAM pipeline back to SQL credential file
google/nomulus pull request #961
Opened 2021-02-10 02:55 UTC by weiminyu

Stop using the SecretManager for SQL credential in BEAM for now. The
SecretManager cannot be injected into the code on pipeline workers
because RegistryEnvironment is not set.

See b/179839014 for details.

The SecretManager is verified to work with Registry server and Nomulus tool.

2021-02-10 13:13 UTC, mindhog requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/961)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @weiminyu)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 222 at r1](https://reviewable.io/reviews/google/nomulus/961#-MTB3d_V-KyO0-qLJf3V:-MTB3d_V-KyO0-qLJf3W:b-fzvv0o) ([raw file](https://github.com/google/nomulus/blob/e1a36a255d611b9317990e320c9fb0ff9a13d314/core/src/main/java/google/registry/persistence/PersistenceModule.java#L222)):*
> ```Java
>         logger.atWarning().log("Wrong password for nomulus.");
>       }
>       logger.atWarning().log("Credentials in the kerying and the secret manager match.");
> ```

This warning isn't actually correct if either of the previous conditions was true.  Also, should it be atInfo()?


<!-- Sent from Reviewable.io -->

2021-02-10 20:39 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/961)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 222 at r1](https://reviewable.io/reviews/google/nomulus/961#-MTB3d_V-KyO0-qLJf3V:-MTCeNQh-ccwbErY8D6Y:bhl9zba) ([raw file](https://github.com/google/nomulus/blob/e1a36a255d611b9317990e320c9fb0ff9a13d314/core/src/main/java/google/registry/persistence/PersistenceModule.java#L222)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

This warning isn't actually correct if either of the previous conditions was true.  Also, should it be atInfo()?
</blockquote></details>

Fixed logging statements. 

Logging at warn so that it is easier to find in the log viewer on beam dashboard. It will be removed soon.  


<!-- Sent from Reviewable.io -->

2021-02-10 20:58 UTC, gbrodman requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/961)* status: all files reviewed, 4 unresolved discussions (waiting on @mindhog and @weiminyu)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 217 at r2](https://reviewable.io/reviews/google/nomulus/961#-MTCj6Uk1RxzKrDb6YAc:-MTCj6Uk1RxzKrDb6YAd:bgqvakg) ([raw file](https://github.com/google/nomulus/blob/858e22b1fdb9da049ff2efebae703f7005121fc3/core/src/main/java/google/registry/persistence/PersistenceModule.java#L217)):*
> ```Java
>       if (!Objects.equals(username, credential.login())) {
>         logger.atWarning().log(
>             "Wrong login for nomulus. Expecting %s, found %s.", username, credential.login());
> ```

We might want to use "username" here instead of "login" since "login" is a bit ambiguous and can refer to either the username or the username+password combination
___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 224 at r2](https://reviewable.io/reviews/google/nomulus/961#-MTCiyrC4kqSGSJB1GID:-MTCiyrC4kqSGSJB1GIE:b-jigze2) ([raw file](https://github.com/google/nomulus/blob/858e22b1fdb9da049ff2efebae703f7005121fc3/core/src/main/java/google/registry/persistence/PersistenceModule.java#L224)):*
> ```Java
>       }
>     } catch (Exception e) {
>       logger.atWarning().withCause(e).log("Failed to get SQL credential from Secret Manager");
> ```

I might warn this at error, since this shouldn't be happening? 

nit: period at the end of the sentence
___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 299 at r2](https://reviewable.io/reviews/google/nomulus/961#-MTCjEqj3DuvVwgSSSgj:-MTCjEqj3DuvVwgSSSgk:bobomso) ([raw file](https://github.com/google/nomulus/blob/858e22b1fdb9da049ff2efebae703f7005121fc3/core/src/main/java/google/registry/persistence/PersistenceModule.java#L299)):*
> ```Java
>       logger.atWarning().log("Credentials in the kerying and the secret manager match.");
>     } catch (Throwable e) {
>       logger.atWarning().withCause(e).log("Failed to get SQL credential from Secret Manager");
> ```

Same thing here, should we log at error? 


<!-- Sent from Reviewable.io -->

2021-02-10 21:10 UTC, weiminyu reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/961)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 217 at r2](https://reviewable.io/reviews/google/nomulus/961#-MTCj6Uk1RxzKrDb6YAc:-MTClJVZAFJmcHqc5msG:b-896fix) ([raw file](https://github.com/google/nomulus/blob/858e22b1fdb9da049ff2efebae703f7005121fc3/core/src/main/java/google/registry/persistence/PersistenceModule.java#L217)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We might want to use "username" here instead of "login" since "login" is a bit ambiguous and can refer to either the username or the username+password combination
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 224 at r2](https://reviewable.io/reviews/google/nomulus/961#-MTCiyrC4kqSGSJB1GID:-MTClgib394dqOSJjF96:bdolmhs) ([raw file](https://github.com/google/nomulus/blob/858e22b1fdb9da049ff2efebae703f7005121fc3/core/src/main/java/google/registry/persistence/PersistenceModule.java#L224)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I might warn this at error, since this shouldn't be happening? 

nit: period at the end of the sentence
</blockquote></details>

This is expected until we get the SecretManager injection fixed. 
___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 299 at r2](https://reviewable.io/reviews/google/nomulus/961#-MTCjEqj3DuvVwgSSSgj:-MTCltXkBRzzM_6M0_QB:b-896fix) ([raw file](https://github.com/google/nomulus/blob/858e22b1fdb9da049ff2efebae703f7005121fc3/core/src/main/java/google/registry/persistence/PersistenceModule.java#L299)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Same thing here, should we log at error? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 21:17 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/961)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-02-11 16:34 UTC, mindhog approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/961)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-11 19:06 UTC, merged