Partially convert RDAP ofy calls to tm calls
google/nomulus pull request #964
Opened 2021-02-11 22:13 UTC by gbrodman

This converts the simple retrieval actions but does not touch the more
complicated search actions -- those use some ofy() query searching logic
and will likely end up being significantly more complicated than this
change. Here, though, we are just changing the calls that can be
converted easily to tm() lookups.

To change in future PRs:
- RdapDomainSearchAction
- RdapEntitySearchAction
- RdapNameserverSearchAction
- RdapSearchActionBase

2021-02-17 17:04 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/964)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/rdap/RdapEntityAction.java, line 75 at r1](https://reviewable.io/reviews/google/nomulus/964#-MTkwmPk8ynzvA6SZzoV:-MTkwmPk8ynzvA6SZzoW:b-7fs6uj) ([raw file](https://github.com/google/nomulus/blob/36f1202a4a101b1c1c91eee4ce8b8ccb4a03ff97/core/src/main/java/google/registry/rdap/RdapEntityAction.java#L75)):*
> ```Java
>       VKey<ContactResource> contactVKey = VKey.create(ContactResource.class, pathSearchString);
>       Optional<ContactResource> contactResource =
>           transactIfJpaTm(() -> tm().loadByKeyIfPresent(contactVKey));
> ```

What's the thought process behind the several calls to `transactIfJpaTm()` in this PR?
___
*[core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java, line 198 at r1](https://reviewable.io/reviews/google/nomulus/964#-MTksMWo6pG0_ynDgOJL:-MTksMWo6pG0_ynDgOJM:b-euk86q) ([raw file](https://github.com/google/nomulus/blob/36f1202a4a101b1c1c91eee4ce8b8ccb4a03ff97/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L198)):*
> ```Java
>   public void run() {
>     ImmutableSetMultimap<String, String> ianaToBaseUrls = getRdapBaseUrlsPerIanaId();
>     Registrar.loadAllCached()
> ```

This is a bit different than what the previous line was doing.  I think we do want to add a `Registrar.loadAllKeys()` method to call from here.  It should be very similar to the existing `Registrar.loadAll()` method, just calling `.keys()` for `ofy` (like the line you removed here) and then also the SQL equivalent to load the ids only.


<!-- Sent from Reviewable.io -->

2021-02-17 18:00 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/964)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/rdap/RdapEntityAction.java, line 75 at r1](https://reviewable.io/reviews/google/nomulus/964#-MTkwmPk8ynzvA6SZzoV:-MTl7Mc39cMm-kboW62j:b-tudnn8) ([raw file](https://github.com/google/nomulus/blob/36f1202a4a101b1c1c91eee4ce8b8ccb4a03ff97/core/src/main/java/google/registry/rdap/RdapEntityAction.java#L75)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What's the thought process behind the several calls to `transactIfJpaTm()` in this PR?
</blockquote></details>

This is fairly common across the codebase because ofy() doesn't necessarily require transactions for reads but SQL does. 
___
*[core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java, line 198 at r1](https://reviewable.io/reviews/google/nomulus/964#-MTksMWo6pG0_ynDgOJL:-MTl8MVo5Wsc0gQqYTMQ:b-j6egrx) ([raw file](https://github.com/google/nomulus/blob/36f1202a4a101b1c1c91eee4ce8b8ccb4a03ff97/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L198)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is a bit different than what the previous line was doing.  I think we do want to add a `Registrar.loadAllKeys()` method to call from here.  It should be very similar to the existing `Registrar.loadAll()` method, just calling `.keys()` for `ofy` (like the line you removed here) and then also the SQL equivalent to load the ids only.
</blockquote></details>

I see what you mean, and it's actually even simpler than what you are thinking it is. Done. 


<!-- Sent from Reviewable.io -->

2021-02-18 01:19 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/964)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/rdap/RdapEntityAction.java, line 75 at r1](https://reviewable.io/reviews/google/nomulus/964#-MTkwmPk8ynzvA6SZzoV:-MTmhm_Z0hUz6lG-f0HJ:b77po8p) ([raw file](https://github.com/google/nomulus/blob/36f1202a4a101b1c1c91eee4ce8b8ccb4a03ff97/core/src/main/java/google/registry/rdap/RdapEntityAction.java#L75)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This is fairly common across the codebase because ofy() doesn't necessarily require transactions for reads but SQL does. 
</blockquote></details>

Hrm, I do wonder what the performance implications of all of these additional read transactions in SQL might end up looking like.  As RDAP becomes more populart his might need to use a cached codepath (like WHOIS).


<!-- Sent from Reviewable.io -->

2021-02-18 22:35 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/964)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/rdap/RdapEntityAction.java, line 75 at r1](https://reviewable.io/reviews/google/nomulus/964#-MTkwmPk8ynzvA6SZzoV:-MTrH7-G0JAmuIGSjdM-:b2nawm2) ([raw file](https://github.com/google/nomulus/blob/36f1202a4a101b1c1c91eee4ce8b8ccb4a03ff97/core/src/main/java/google/registry/rdap/RdapEntityAction.java#L75)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Hrm, I do wonder what the performance implications of all of these additional read transactions in SQL might end up looking like.  As RDAP becomes more populart his might need to use a cached codepath (like WHOIS).
</blockquote></details>

Agreed, we will likely need to add a caching layer. 


<!-- Sent from Reviewable.io -->

2021-02-18 22:41 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/964)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/rdap/RdapEntityAction.java, line 75 at r1](https://reviewable.io/reviews/google/nomulus/964#-MTkwmPk8ynzvA6SZzoV:-MTrIVod5RqnEfgxmXGP:b-a9bkyx) ([raw file](https://github.com/google/nomulus/blob/36f1202a4a101b1c1c91eee4ce8b8ccb4a03ff97/core/src/main/java/google/registry/rdap/RdapEntityAction.java#L75)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Agreed, we will likely need to add a caching layer. 
</blockquote></details>

filed b/180645230


<!-- Sent from Reviewable.io -->

2021-02-23 16:28 UTC, merged