Fix ContactTransferData SQL loads
google/nomulus pull request #967
Opened 2021-02-16 21:37 UTC by mindhog

ContactTransferData is currently loaded back from SQL as an unspecialized
TransferData object.  Replace it with the ContactTransferData object that we
use it to reconstitute.

It's likely that this could be done more straightforwardly with a schema
change.

2021-02-19 16:23 UTC, gbrodman requested changes
sorry about that, this slipped through my radar for some reason :/ 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/967#-:-MTv5JRX1fBhslrL5hhT:b7u6jvg)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/poll/PollMessage.java, line 424 at r1](https://reviewable.io/reviews/google/nomulus/967#-MTv5PQIBmBn-T75LCOT:-MTv5PQJ4tLiEihr-OiK:bpg1ry9) ([raw file](https://github.com/google/nomulus/blob/921994b5351d5b1977294e245c93e74a240f724e/core/src/main/java/google/registry/model/poll/PollMessage.java#L424)):*
> ```Java
>         // ContactTransferResponse that we just created so that the value is consistently
>         // specialized.
>         transferResponse = contactTransferResponses.get(0);
> ```

any preference between this structure vs 

transferResponse = new ContactTransferResponse.Builder().... [creating the thing]
contactTransferResponses = ImmutableList.of(transferResponse)

?

I'm always a bit squeamish when I see direct index access to a list (in case it changes in the future) though I don't feel super strongly here 


<!-- Sent from Reviewable.io -->

2021-02-19 21:08 UTC, gbrodman reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/967)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-02-22 14:47 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/967)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/poll/PollMessage.java, line 424 at r1](https://reviewable.io/reviews/google/nomulus/967#-MTv5PQIBmBn-T75LCOT:-MU9CJDTCfJatHp_KW7n:bohqzsr) ([raw file](https://github.com/google/nomulus/blob/921994b5351d5b1977294e245c93e74a240f724e/core/src/main/java/google/registry/model/poll/PollMessage.java#L424)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

any preference between this structure vs 

transferResponse = new ContactTransferResponse.Builder().... [creating the thing]
contactTransferResponses = ImmutableList.of(transferResponse)

?

I'm always a bit squeamish when I see direct index access to a list (in case it changes in the future) though I don't feel super strongly here 
</blockquote></details>

Agreed, done.


<!-- Sent from Reviewable.io -->

2021-02-22 16:11 UTC, gbrodman approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/967)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-22 18:42 UTC, merged