Add GetPremiumListCommand
google/nomulus pull request #972
Opened 2021-02-23 20:47 UTC by gbrodman

When testing the premium list refactor, it would have been nice and
convenient to have this. Currently we have no way of inspecting premium
list contents that I'm aware of.

2021-02-26 19:35 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/972)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[core/src/main/java/google/registry/tools/GetPremiumListCommand.java, line 31 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUo7l178CVxj_tyijJ:-MUUo7l178CVxj_tyijK:b-g94uh7) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/main/java/google/registry/tools/GetPremiumListCommand.java#L31)):*
> ```Java
> public class GetPremiumListCommand implements CommandWithRemoteApi {
> 
>   public static final String PATH = "/_dr/admin/getPremiumList";
> ```

What is this about?
___
*[core/src/main/java/google/registry/tools/GetPremiumListCommand.java, line 42 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUoGMp4eDJrsAyNpXg:-MUUoGMp4eDJrsAyNpXh:b-97c4en) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/main/java/google/registry/tools/GetPremiumListCommand.java#L42)):*
> ```Java
>         ImmutableList<String> printedEntities =
>             Streams.stream(PremiumListDualDao.loadAllPremiumListEntries(premiumListName))
>                 .map(entry -> String.format("%s,%s", entry.getLabel(), entry.getValue()))
> ```

Implement this as a `.toString()` method on the `PremiumListEntry` instead.  This seems more widely applicable (and indeed it may already have some existing uses like this that may need to be refactored to use your new `toString()`).
___
*[core/src/main/java/google/registry/tools/GetPremiumListCommand.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUosrz5PUXAyY1cO9m:-MUUosrz5PUXAyY1cO9n:bv0i5s5) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/main/java/google/registry/tools/GetPremiumListCommand.java#L45)):*
> ```Java
>                 .collect(toImmutableList());
>         System.out.println(String.format("%s:", premiumListName));
>         System.out.println(Joiner.on("\n").join(printedEntities));
> ```

Instead of `collect()ing` to an ImmutableList above (which I suspect uses a bit more memory), you can use a concatenating String collector to directly collect to a string.  All of this then ends up looking like:

```
System.out.printf(
    "%s: %s\n",
    premiumListName,
    Streams.stream(PremiumListDualDao.loadAllPremiumListEntries(premiumListName).map(PremiumListEntry::toString).Collectors.joining("\n"));
```
___
*[core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java, line 37 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUpVxWBEymvX9-PudF:-MUUpVxWBEymvX9-PudG:b-j097cb) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java#L37)):*
> ```Java
>     runCommand("tld");
>     // can't guarantee ordering of the list entries
>     assertInStdout("tld:\n");
> ```

Use `assertStdoutIs()` here to make a stronger more ironclad assertion, rather than merely asserting about what it might contain.
___
*[core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUpa3S8jRWjinMQvU5:-MUUpa3S8jRWjinMQvU6:b-816h6l) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java#L45)):*
> ```Java
>     runCommand("tld", "nonexistent");
>     // can't guarantee ordering of the list entries
>     assertInStdout("tld:\n");
> ```

Same.


<!-- Sent from Reviewable.io -->

2021-02-26 20:06 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/972)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/tools/GetPremiumListCommand.java, line 31 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUo7l178CVxj_tyijJ:-MUUtHfY-0NJtKlowzO9:b-uhcop5) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/main/java/google/registry/tools/GetPremiumListCommand.java#L31)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

What is this about?
</blockquote></details>

sneaky lil bit of code, ignore it 
___
*[core/src/main/java/google/registry/tools/GetPremiumListCommand.java, line 42 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUoGMp4eDJrsAyNpXg:-MUUuljX8Hf8NCUo9f3D:bhcb2hi) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/main/java/google/registry/tools/GetPremiumListCommand.java#L42)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Implement this as a `.toString()` method on the `PremiumListEntry` instead.  This seems more widely applicable (and indeed it may already have some existing uses like this that may need to be refactored to use your new `toString()`).
</blockquote></details>

Done. (and one other usage) 
___
*[core/src/main/java/google/registry/tools/GetPremiumListCommand.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUosrz5PUXAyY1cO9m:-MUUvjOg7mWBmmO_idx4:b-hfluvg) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/main/java/google/registry/tools/GetPremiumListCommand.java#L45)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Instead of `collect()ing` to an ImmutableList above (which I suspect uses a bit more memory), you can use a concatenating String collector to directly collect to a string.  All of this then ends up looking like:

```
System.out.printf(
    "%s: %s\n",
    premiumListName,
    Streams.stream(PremiumListDualDao.loadAllPremiumListEntries(premiumListName).map(PremiumListEntry::toString).Collectors.joining("\n"));
```
</blockquote></details>

yeah, we can do something like that (not exactly what you wrote, but very close) 
___
*[core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java, line 37 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUpVxWBEymvX9-PudF:-MUUwGmu6ObcA_3SaHSb:b-sshrun) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java#L37)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use `assertStdoutIs()` here to make a stronger more ironclad assertion, rather than merely asserting about what it might contain.
</blockquote></details>

nah, see the comment (which I can make more detailed) -- we can't guarantee the ordering in Postgres unless we specifically sort it, which doesn't really seem to make sense for something like this 
___
*[core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUpa3S8jRWjinMQvU5:-MUUwRhv40QsUEtOJeQB:bsmfnc3) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java#L45)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

see other comment 


<!-- Sent from Reviewable.io -->

2021-02-26 21:47 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/972)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 213 at r2](https://reviewable.io/reviews/google/nomulus/972#-MUVI8FnElEzTJnTRHzS:-MUVI8FnElEzTJnTRHzT:b-8xw39w) ([raw file](https://github.com/google/nomulus/blob/9b869b24d6fa1851f8bcc6139bab7d7a5e995741/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L213)):*
> ```Java
>     @Override
>     public String toString() {
>       // Don't include the comment so that we can use this when exporting the premium list
> ```

Why is the comment being excluded?  This seems useful, no?  It doesn't make sense that you would save one thing but then get it back with one of that data missing?
___
*[core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java, line 37 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUpVxWBEymvX9-PudF:-MUVIRFP1a7T1_1z2HJe:b-z616ox) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java#L37)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nah, see the comment (which I can make more detailed) -- we can't guarantee the ordering in Postgres unless we specifically sort it, which doesn't really seem to make sense for something like this 
</blockquote></details>

Disagree, it sounds like specifically sorting it would be super helpful.  We keep our .txt files sorted and the entire point of this PR is you want to be able to easily compare lists ... being sorted makes that a lot easier!

Phrased in a different way, why would randomly shuffled be preferable to a sensible ordering?


<!-- Sent from Reviewable.io -->

2021-02-26 21:48 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/972)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 213 at r2](https://reviewable.io/reviews/google/nomulus/972#-MUVI8FnElEzTJnTRHzS:-MUVItAn2i_d1ItGWMV-:b8tx5ly) ([raw file](https://github.com/google/nomulus/blob/9b869b24d6fa1851f8bcc6139bab7d7a5e995741/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L213)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why is the comment being excluded?  This seems useful, no?  It doesn't make sense that you would save one thing but then get it back with one of that data missing?
</blockquote></details>

Hrm, it's because the comment is for internal use only which we don't want to include in the registrar-accessible export generated in `ExportPremiumTermsAction`, huh.

It sounds like the comment should be included here, and then we leave `ExportPremiumTermsAction` alone and continue to only do the label/price there.


<!-- Sent from Reviewable.io -->

2021-02-26 22:21 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/972)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 213 at r2](https://reviewable.io/reviews/google/nomulus/972#-MUVI8FnElEzTJnTRHzS:-MUVLIaFBJ5UXe80iYHW:b-vp3pc1) ([raw file](https://github.com/google/nomulus/blob/9b869b24d6fa1851f8bcc6139bab7d7a5e995741/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L213)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Hrm, it's because the comment is for internal use only which we don't want to include in the registrar-accessible export generated in `ExportPremiumTermsAction`, huh.

It sounds like the comment should be included here, and then we leave `ExportPremiumTermsAction` alone and continue to only do the label/price there.
</blockquote></details>

Talked offline and we'll keep this as is, since we're getting rid of the `comment` storage in the SQL world 
___
*[core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java, line 37 at r1](https://reviewable.io/reviews/google/nomulus/972#-MUUpVxWBEymvX9-PudF:-MUVMdp65wEIXj1UDGTS:bpf8mte) ([raw file](https://github.com/google/nomulus/blob/d04c8be1162074a9549ba3a96286dcc6effa1ed7/core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java#L37)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Disagree, it sounds like specifically sorting it would be super helpful.  We keep our .txt files sorted and the entire point of this PR is you want to be able to easily compare lists ... being sorted makes that a lot easier!

Phrased in a different way, why would randomly shuffled be preferable to a sensible ordering?
</blockquote></details>

Yeah, we can sort it -- the lists should always be sorted anyway 


<!-- Sent from Reviewable.io -->

2021-03-02 22:41 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/972)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java, line 200 at r3](https://reviewable.io/reviews/google/nomulus/972#-MUp4hEL2BnGw8LT60ES:-MUp4hEL2BnGw8LT60ET:bnaftb6) ([raw file](https://github.com/google/nomulus/blob/f237292212318dd3027250c40577486be0ac1a4a/core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java#L200)):*
> ```Java
>                     .createQuery(
>                         "FROM PremiumEntry pe WHERE pe.revisionId = :revisionId "
>                             + "ORDER BY pe.domainLabel ASC",
> ```

So this wasn't exactly what I was suggesting, as the ordering isn't always required, but only in the get command and some other stuff.  But seeing as how this isn't in the main code path actually used for checking domain prices, eh.  It's not a big deal.  This particular code path isn't used for all that much anyway.

Note that you're only ordering the Cloud SQL code path, so what exactly is going on in the Datastore code path?  It's taking advantage of the fact that we happen to already sort lists prior to saving them in Datastore, but this isn't necessarily enforced anywhere?  It's a little bit messy.  Leaving the DAO alone, and then doing the sorting in-memory in just the `GetPremiumListCommand` (where it will sort the premium list equally regardless of which data source it's coming from) feels cleaner to me.


<!-- Sent from Reviewable.io -->

2021-03-02 22:56 UTC, gbrodman reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/972)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java, line 200 at r3](https://reviewable.io/reviews/google/nomulus/972#-MUp4hEL2BnGw8LT60ES:-MUp8uf7032vKY9-yfzG:bnd4agf) ([raw file](https://github.com/google/nomulus/blob/f237292212318dd3027250c40577486be0ac1a4a/core/src/main/java/google/registry/schema/tld/PremiumListSqlDao.java#L200)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

So this wasn't exactly what I was suggesting, as the ordering isn't always required, but only in the get command and some other stuff.  But seeing as how this isn't in the main code path actually used for checking domain prices, eh.  It's not a big deal.  This particular code path isn't used for all that much anyway.

Note that you're only ordering the Cloud SQL code path, so what exactly is going on in the Datastore code path?  It's taking advantage of the fact that we happen to already sort lists prior to saving them in Datastore, but this isn't necessarily enforced anywhere?  It's a little bit messy.  Leaving the DAO alone, and then doing the sorting in-memory in just the `GetPremiumListCommand` (where it will sort the premium list equally regardless of which data source it's coming from) feels cleaner to me.
</blockquote></details>

Yeah, the lists are already sorted in Datastore. That seems reasonable, done. 


<!-- Sent from Reviewable.io -->

2021-03-02 23:03 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/972)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2021-03-03 00:59 UTC, merged