Explicitly set fanout tasks HTTP method to POST
google/nomulus pull request #978
Opened 2021-03-01 03:49 UTC by jianglai

For unknown reasons some of the fanout actions triggered by cron use GET
to hit Nomulus endpoints, which only accept POST. This should not have
happened and there's even a test to make sure the default method is
POST. Nevertheless we make the method selection explicit.

2021-03-02 14:57 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/978)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/main/java/google/registry/cron/TldFanoutAction.java, line 178 at r1](https://reviewable.io/reviews/google/nomulus/978#-MUnQp3wB19CAbiDZO2Y:-MUnQp3wB19CAbiDZO2Z:b-com90f) ([raw file](https://github.com/google/nomulus/blob/cb75ecd99cef838ac66915ebc90cc721cfe5c218/core/src/main/java/google/registry/cron/TldFanoutAction.java#L178)):*
> ```
> options.method(Method.POST)
> ```
There are quite a few cron-triggered actions that are configured to accept GET only. E.g., ResaveAllEppResources, and DeleteContactsAndHosts, etc. Would this change cause trouble to them?


<!-- Sent from Reviewable.io -->

2021-03-02 16:05 UTC, jianglai commented
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/978)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jianglai)
> 
> _[core/src/main/java/google/registry/cron/TldFanoutAction.java, line 178 at r1](https://reviewable.io/reviews/google/nomulus/978#-MUnQp3wB19CAbiDZO2Y:-MUnQp3wB19CAbiDZO2Z:b-com90f) ([raw file](https://github.com/google/nomulus/blob/cb75ecd99cef838ac66915ebc90cc721cfe5c218/core/src/main/java/google/registry/cron/TldFanoutAction.java#L178)):_
> 
> > ```
> > options.method(Method.POST)
> > ```
> 
> There are quite a few cron-triggered actions that are configured to accept GET only. E.g., ResaveAllEppResources, and DeleteContactsAndHosts, etc. Would this change cause trouble to them?

This change only makes the POST method explicitly, which is set as default anyway. In fact there already exists a test to make sure that the requests are POSTs. As stated in the PR description this change should be a null op and it is still not fully understood why some fanout actions enqueue requests as GET.

The ones you listed are directly requested by the cron job itself, which is always a GET. They will not be affected by this PR. The fanouts are requested by cron (via GET), and then enqueue another (POST) request in a task queue for async operation.

Do you still have the URL to the failed fanout? I would like to take another look to make sure nothing is overlooked.

2021-03-02 16:45 UTC, weiminyu requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/978)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/main/java/google/registry/cron/TldFanoutAction.java, line 178 at r1](https://reviewable.io/reviews/google/nomulus/978#-MUnQp3wB19CAbiDZO2Y:-MUnoida2w3MtXjBsaes:bg0keg3) ([raw file](https://github.com/google/nomulus/blob/cb75ecd99cef838ac66915ebc90cc721cfe5c218/core/src/main/java/google/registry/cron/TldFanoutAction.java#L178)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

This change only makes the POST method explicitly, which is set as default anyway. In fact there already exists a test to make sure that the requests are POSTs. As stated in the PR description this change should be a null op and it is still not fully understood why some fanout actions enqueue requests as GET.

The ones you listed are directly requested by the cron job itself, which is always a GET. They will not be affected by this PR. The fanouts are requested by cron (via GET), and then enqueue another (POST) request in a task queue for async operation.

Do you still have the URL to the failed fanout? I would like to take another look to make sure nothing is overlooked. 
</blockquote></details>

The only failing job in production is /_dr/task/icannReportingUpload, which consistently fails nowadays.


<!-- Sent from Reviewable.io -->

2021-03-02 16:46 UTC, weiminyu approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/978#-:-MUnpFO451PDTbcsWE8d:bb6ywmx)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

2021-03-02 20:53 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/978)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/cron/TldFanoutAction.java, line 178 at r1](https://reviewable.io/reviews/google/nomulus/978#-MUnQp3wB19CAbiDZO2Y:-MUohMdb9FPu490PKucA:b5xvee2) ([raw file](https://github.com/google/nomulus/blob/cb75ecd99cef838ac66915ebc90cc721cfe5c218/core/src/main/java/google/registry/cron/TldFanoutAction.java#L178)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

The only failing job in production is /_dr/task/icannReportingUpload, which consistently fails nowadays.
</blockquote></details>

OK now that I took another look, the GETs are indeed triggered by cron job, see https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml;drc=2cf190e44866da1bf126aeaf3378f39b4e8d754c;l=283.

Normally the cron job triggers the staging action, which then enqueues an upload actions with POST. There's also this separate cron job that does catch up for when things went wrong. I think the solution here is to either allow GET for this job, or to have this cron job trigger the action through fanout like it does with uploads.

Any preference?


<!-- Sent from Reviewable.io -->

2021-03-03 02:58 UTC, jianglai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/978)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/cron/TldFanoutAction.java, line 178 at r1](https://reviewable.io/reviews/google/nomulus/978#-MUnQp3wB19CAbiDZO2Y:-MUq0LTCEQcEkgWBeZWx:bqzvgja) ([raw file](https://github.com/google/nomulus/blob/cb75ecd99cef838ac66915ebc90cc721cfe5c218/core/src/main/java/google/registry/cron/TldFanoutAction.java#L178)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

OK now that I took another look, the GETs are indeed triggered by cron job, see https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml;drc=2cf190e44866da1bf126aeaf3378f39b4e8d754c;l=283.

Normally the cron job triggers the staging action, which then enqueues an upload actions with POST. There's also this separate cron job that does catch up for when things went wrong. I think the solution here is to either allow GET for this job, or to have this cron job trigger the action through fanout like it does with uploads.

Any preference?
</blockquote></details>

See #984. This PR is to be abandoned.


<!-- Sent from Reviewable.io -->

2021-03-03 14:02 UTC, closed without merging