Disable whois caching in nomulus tool
google/nomulus pull request #980
Opened 2021-03-02 15:00 UTC by mindhog

The whois commands previously served output generated from cached EppResource
objects in most cases.  While this is entirely appropriate from server-side,
it is less useful when these commands are run from nomulus tool and, in fact,
when run from the "shell" command this results in changes that have been
applied from the shell not being visible from a subsequent "whois".  The
command may instead serve information on an earlier, cached version of the
resource instead of the latest version.

This implementation uses dagger for parameterization of cached/non-cached
modes.  I did consider the possibility of simply parameterizing the query
commands in all cases as discussed, however, having gone down the
daggerization path and having gotten it to work, I have to say I find this
approach preferrable.  There's really no case for identifying
cached/non-cached on a per-command basis and doing so would require
propagating the flag throughout all levels of the API and all callsites.

Tested: In addition to the new unit test which explicitly verifies the
caching/noncaching behavior of the new commands, tested the actual failing
sequence from "nomulus -e sandbox shell" and verified that the correct results
are served after a mutation.

2021-03-02 23:07 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/980)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java, line 1 at r1](https://reviewable.io/reviews/google/nomulus/980#-MUpBN4q0ORjClqXLWPk:-MUpBN4r0Bp0ZvICfsFN:b-8k883n) ([raw file](https://github.com/google/nomulus/blob/62aa5bbc7867a6b817eeb7e5fadb8c0520f3a9e1/core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java#L1)):*
> ```Java
> // Copyright 2017 The Nomulus Authors. All Rights Reserved.
> ```

2021?


<!-- Sent from Reviewable.io -->

2021-03-03 16:11 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/980)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java, line 1 at r1](https://reviewable.io/reviews/google/nomulus/980#-MUpBN4q0ORjClqXLWPk:-MUsqizPBUC8E_5h3yBq:bjmepzr) ([raw file](https://github.com/google/nomulus/blob/62aa5bbc7867a6b817eeb7e5fadb8c0520f3a9e1/core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java#L1)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

2021?
</blockquote></details>

Done.  Copy-paste kills.


<!-- Sent from Reviewable.io -->

2021-03-04 20:10 UTC, CydeWeys requested changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/980)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java, line 1 at r1](https://reviewable.io/reviews/google/nomulus/980#-MUpBN4q0ORjClqXLWPk:-MUyrBdS93suvfM9l2ry:b-ypw44v) ([raw file](https://github.com/google/nomulus/blob/62aa5bbc7867a6b817eeb7e5fadb8c0520f3a9e1/core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java#L1)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Done.  Copy-paste kills.
</blockquote></details>

I think you might have more errors of this kind in this PR?


<!-- Sent from Reviewable.io -->

2021-03-04 20:39 UTC, mindhog reviewed
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/980)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java, line 1 at r1](https://reviewable.io/reviews/google/nomulus/980#-MUpBN4q0ORjClqXLWPk:-MUyxlJ7DXowmTDTTZyw:b-896fix) ([raw file](https://github.com/google/nomulus/blob/62aa5bbc7867a6b817eeb7e5fadb8c0520f3a9e1/core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java#L1)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think you might have more errors of this kind in this PR?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-04 23:03 UTC, CydeWeys approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/980)* status: 0 of 13 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-08 17:33 UTC, mindhog reviewed
I was seeing some interesting test failures on Kokoro that appear to be race-conditions associated with the per-test cache parameters.  I didn't think this should be possible, based on my understanding of our test/build framework, but moving the test into "fragileTests" seems to alleviate it.

I'm going to merge the change as-is and try to debug the failures in a separate PR. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/980#-:-MVHsOLm2N3jBp2TuK6G:b1dz9mo)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @mindhog)



<!-- Sent from Reviewable.io -->

2021-03-08 17:33 UTC, merged